### ISSUE TITLE
Geojson popup content not showing up

### ISSUE THREAD

**Issue by achourasia** [python-visualization/folium#100]
I have a geojson (tri.json) which has polygons with popup content. When I plot it with folium as follows, the popup does not work. If I import my json at [geojson.io](http://bl.ocks.org/d/2f2489bb1bfb94650b21) the popup works fine.

What may be going wrong?

**tri.py**
```
    import folium

    # Map origin
    cx = -117.7495299743632
    cy = 35.74053999839425

    # Set center and zoom level of the map
    map_1 = folium.Map(location=[cy, cx], zoom_start=12,)

    # Mark center - this popup works
    #map_1.polygon_marker(location=[cy,cx], popup=str('This one works'))

    # Add patches to the map
    map_1.geo_json(geo_path='tri.json')

    map_1.create_map(path="tri.html", plugin_data_out=True)
```

**tri.json**
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.7495299744,
              35.7405399984
            ],
            [
              -117.7422264169,
              35.7472081889
            ],
            [
              -117.7521555454,
              35.7536368252
            ]
          ]
        ]
      },
      "type": "Feature",
      "id": 1,
      "properties": {
        "name": "AirportLake,Subsection0",
        "popupContent": "sid:1 fault:AirportLake,Subsection0"
      }
    }
  ]
}
```

**Comment by birdage** [comment]
@achourasia is the geojson in the right location, id pop open the inspector and see if you have a 400 error or not found for the geojson file.

**Comment by achourasia** [comment]
Yes, I can see the triangle on the map, but nothing happens when I click on the triangle.

**Comment by birdage** [comment]
@achourasia i dont see anything immediately apparent in the code relating to tooltip 
https://github.com/python-visualization/folium/blob/master/folium/folium.py#L705-L743, when looking at the geojson example you posted the bind the popup to some content (like this view-source:http://bl.ocks.org/anonymous/raw/2f2489bb1bfb94650b21/) and i dont see anything initially for that, ill take a further look

**Comment by birdage** [comment]
@achourasia for the geojson layer i dont see any popup content i.e [here](https://github.com/python-visualization/folium/blob/master/folium/folium.py#L866-L867)

**Comment by birdage** [comment]
@achourasia should be a simple fix...

**Comment by birdage** [comment]
related to https://github.com/python-visualization/folium/issues/3 and https://github.com/python-visualization/folium/issues/6

**Comment by oztalha** [comment]
so, is there another way to add popupcontent  to geojson polygons, Having an optional third element in the columns argument (used with pandas) would be great; see e.g.:

    states.geo_json( columns=['state', 'shareGov', 'popups'],
                geo_path=state_geo, data=df, data_out='gov_share.json',
                key_on='feature.properties.name',
                fill_color='PuRd', fill_opacity=0.7, line_opacity=0.2,
                legend_name='Incumbent Governor Vote Share (%)')

**Comment by ocefpaf** [comment]
@achourasia Can you test PR #102 and give some feedback.

**Comment by achourasia** [comment]
@birdage @ocefpaf sorry for the delay, I tried the latest master, and the popups now work. Thanks

**Comment by achourasia** [comment]
Popup does not work in 0.2.1 release

**Comment by TomDarley** [comment]
Found a fix, not ideal but delete .fitBounds(e.target.getBounds()) from html and it will work.
