### ISSUE TITLE
folium does not display a map with three markers

### ISSUE THREAD

**Issue by mybox2003** [python-visualization/folium#1003]
```python
import folium

customers = [(80.61666667, 58.05), (79.5, 76.98333333), (79.55, 90.61666667), (78.06666667, 14.25)]
m = folium.Map(location=[70, 100], zoom_start=1)
folium.Marker(location=customers[0]).add_to(m)
folium.Marker(location=customers[1]).add_to(m)
folium.Marker(location=customers[2]).add_to(m)
m

```
if markers are 2, then the folium displays a map with markers, but if markers are 3, then I see an empty window in jupyter, there are no errors. How to fix it?

I tried to use version 0.6.0  and 0.5.0

**Comment by ocefpaf** [comment]
That is a limitation in jupyter, you have to options:

1. use the option `--NotebookApp.iopub_data_rate_limit=1000000000` to increase the iopub data in jupyter

2. save an HTML and reload it with a helper function like:

```python
def embed_map(m):
    from IPython.display import HTML

    m.save('index.html')
    with open('index.html') as f:
        html = f.read()

    iframe = '<iframe srcdoc="{srcdoc}" style="width: 100%; height: 750px; border: none"></iframe>'
    srcdoc = html.replace('"', '&quot;')
    return HTML(iframe.format(srcdoc=srcdoc))


embed_map(m)
```

**Comment by mybox2003** [comment]
I tried `jupyter notebook --NotebookApp.iopub_data_rate_limit=10000000` in the regular console the result was the same. 
After that I launched `jupyter notebook --generate-config` and edited the file `~/.jupyter/jupyter_notebook_config.py`  increased the parameter and restarted the kernel, but result was the same.

**Comment by ocefpaf** [comment]
Works fine for me even without the increased iopub (it is just 3 icons after all :smile:):

![screenshot from 2018-10-25 09-36-31](https://user-images.githubusercontent.com/950575/47500577-8de30100-d839-11e8-81c0-fc1247d58ff9.png)


I tested that con chrome, chromium, and firefox.

**Comment by mybox2003** [comment]
I use win-64, python 2.7 and folium 0.6.0 and see the same picture only if I put one or two marks. If there are more marks, then I see a blank screen. What else could be the problem?

**Comment by Conengmo** [comment]
Could it be... Python 2.7? Try upgrading to Python3.
https://python3statement.org/

**Comment by ocefpaf** [comment]
> I use win-64, python 2.7 and folium 0.6.0 and see the same picture only if I put one or two marks. If there are more marks, then I see a blank screen. What else could be the problem? I also use chrome.

Can you try to save the HTML and load it back in your browser? Also, we highly recommend moving to python3 as @Conengmo hinted above. The next version of `folium` we will probably drop Python 2 support.

**Comment by mybox2003** [comment]
The saved html is valid, all markers are displayed, but it is loaded back into a notebook in the form of an empty window. Reinstalled the conda and use python 3. Pre-configured `jupyter notebook --NotebookApp.iopub_data_rate_limit=10000000`

**Comment by mybox2003** [comment]
Any more ideas?

**Comment by Conengmo** [comment]
Maybe first but your markers in a `FeatureGroup`? Other than that I have no idea.

**Comment by mybox2003** [comment]
why is the issue closed?

**Comment by ocefpaf** [comment]
Because it is not a folium issue. It is related to browser/jupyter. You
just confirmed above that the HTML is okay.

**Comment by mybox2003** [comment]
Thanks a lot
