### ISSUE TITLE
How to enable getFeatureInfo

### ISSUE THREAD

**Issue by meteoDaniel** [python-visualization/folium#1006]
Dear all, 

 i am having WmsTileLayer and I want to enable getFeatureInfo like `leaflet-betterwms`. I hope anyone could help. 

Thanks a lot. Best regards

**Comment by Conengmo** [comment]
Hi @meteoDaniel,

Can you provide a bit more info about what you want to do? I'm not familiar with `leaflet-betterwms` or a `getFeatureInfo` option.

**Comment by meteoDaniel** [comment]
I have found a Thread about this topic: 

https://gist.github.com/rclark/6908938

**Comment by meteoDaniel** [comment]
https://docs.geoserver.org/stable/en/user/services/wms/reference.html#getfeatureinfo

**Comment by meteoDaniel** [comment]
??

**Comment by ocefpaf** [comment]
One would need to create a plugin for better wms. Closing this b/c I don't believe we should support all the code needed for that inside the base folium, but this is a good candidate for an external plugin.

**Comment by michelmetran** [comment]
I understand that through betterwms, from Leaflet, it would be possible to use the GetFeatureInfo function of a Geoserver (or Mapservcer or ArcGIS Server) that is making the WMS layer available, correct!?

I'm looking for this in folium. I managed to add the WMS layer, but now I need to be able to generate a popup (similar to folium.GeoJsonPopup) of the features of this WMS.

I leave a comment to follow the unfolding of this issue...
