### ISSUE TITLE
key_on=`feature.properties.name` not working

### ISSUE THREAD

**Issue by darcyprice** [python-visualization/folium#1018]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```        
    def get_choropleth(self, request):
        # load shape of zone (world countries)
        countries_geo = 'mapping_twitter/state_geo/mapping_twitter/json/world_countries.json'
        # load data for each country
        country_data = self.get_object().display_locations() # get location frequency from object

        # convert the dict into a pd.DataFrame
        pd_df = pd.DataFrame(
            data=list(country_data.items()),
            columns=['Country', 'Tweets'])

        # Initialize the map
        m = folium.Map(
            location=[37, -102],
            zoom_start=2,
            no_wrap=True)

        # plot the choropleth points
        m.choropleth(
            geo_data=countries_geo,
            name='choropleth',
            data=pd_df,
            columns=['Country', 'Tweets'],
            key_on='feature.properties.name',
            fill_color='BuPu',
            fill_opacity=0,
            legend_name='Number of Tweets')
        folium.LayerControl().add_to(m)
```
#### Problem description

I'm using [world-countries.json](https://github.com/python-visualization/folium/blob/master/examples/data/world-countries.json) as the JSON, but for some reason, `key_on=feature.properties.name` isn't working?

#### Expected Output

I am expecting a choropleth based on the data frame, but instead, I am getting a blank map.

#### Output of ``folium.__version__``

`folium = "==0.6.0"`

**Comment by ocefpaf** [comment]
Without a reproducible example we cannot debug this. We cannot know what is in 

```python
country_data = self.get_object().display_locations()
```

from your code above.

PS: I just tested a working example and `key_on=` is working properly. You probably have a usage question there. Please take it to our gitter where more users can help you:

https://gitter.im/python-visualization/folium
