### ISSUE TITLE
'Map' object has no attribute 'simple_marker' 

### ISSUE THREAD

**Issue by dmccrickard** [python-visualization/folium#1019]
Hello there,

I am trying to create a folium map using the code below, but I get an error message saying **'Map' object has no attribute 'simple_marker'** 

I have attached a screenshot of the error message I am getting. 

Would you happen to know why this is happening? 

Many thanks in advance for your help on this!

```
import folium

belfast_coordinates = (54.607868, -5.926437)

MAX_RECORDS = 1000
  
map = folium.Map(location=belfast_coordinates, zoom_start=12)

for each in allcrime[0:MAX_RECORDS].iterrows():
    map.simple_marker(
        location = [each[1]['Longitude'],each[1]['Latitude']], 
        clustered_marker = True)
  
display(map)

```
![folium map error](https://user-images.githubusercontent.com/45168501/48704547-ce425e80-ebee-11e8-8f39-15d13ffd98b2.PNG)

**Comment by ocefpaf** [comment]
Simple marker was removed a long time ago. Please check the docs from a modern version of folium: http://python-visualization.github.io/folium/
