### ISSUE TITLE
Transparent GeoJson

### ISSUE THREAD

**Issue by jackemcpherson** [python-visualization/folium#1020]
Trying to create a transparent GeoJson, i only want to see the tooltips over a choropleth.

Trying the below, but getting nowhere.

```python
style_function = {'fillColor': '#00FFFFFF',
                 'lineColor': '#00FFFFFF'}

folium.GeoJson(combined,
               tooltip=folium.GeoJsonTooltip(fields=['LGA','MBRS'],
                                             aliases=['Location','Members']),
               style_function=style_function).add_to(m)

folium.LayerControl().add_to(m)

```
Can you tell me how to make the GeoJson layer transparent?

Thanks.

Jack.

**Comment by jtbaker** [comment]
Hey @jackemcpherson, the issue is that your style function is a dictionary instead of a function returning a dictionary.

Rewrite it like this:

```
style = {'fillColor': '#00FFFFFF', 'lineColor': '#00FFFFFF'}

folium.GeoJson(combined,
               tooltip=folium.GeoJsonTooltip(fields=['LGA','MBRS'],
                                             aliases=['Location','Members']),
               style_function=lambda x: style).add_to(m)
```

or:

```
def style_function:
    return {'fillColor': '#00FFFFFF', 'lineColor': '#00FFFFFF'}

folium.GeoJson(combined,
               tooltip=folium.GeoJsonTooltip(fields=['LGA','MBRS'],
                                             aliases=['Location','Members']),
               style_function=style_function).add_to(m)
```

and that should be good. Hope this helps!

**Comment by jackemcpherson** [comment]
Thanks a lot for getting back to me, both options worked!

Just for anybody finding this in future: replace the dict from my code with:

`{'fillColor': '#00000000', 'color': '#00000000'}`

**Comment by Conengmo** [comment]
@jtbaker maybe assert `style_function` is callable, raise a meaningful error otherwise? What do you think, user-friendly or overkill?

**Comment by jtbaker** [comment]
@Conengmo! Good thinking! I like it. I've PR'd a fix in #1024.

**Comment by paaghi** [comment]
I came across a similar problem like yours. Try to set the 'fillOpacity' property in your style function. Because according to [the original Leaflet documentation](https://leafletjs.com/reference-1.5.0.html#path-option), the default value is 0.2. I hope it helps.

**Comment by mmgamboa** [comment]
Thanks @paaghi I came with the same problem and your comment solved it out. Cheers, Martín.

**Comment by yoondev23** [comment]
geo_poly = folium.GeoJson(data=sd_busan, style_function=lambda x: {'lineColor': 'yellow','fillColor': 'yellow', 'fillOpacity': 0.001})
geo_poly.add_to(m)

위 코드에서 linecolor가 적용되지 않고 있습니다. 혹시 참고해야할 문제가 있나요 ?
