### ISSUE TITLE
Map does not appear if the popup in CircleMarker contains an apostrophe

### ISSUE THREAD

**Issue by mcherep** [python-visualization/folium#1027]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
m = folium.Map(
        location=[46.8182,8.2275],
        zoom_start=2
    )

folium.CircleMarker(
                location=[46.8182,8.2275],
                popup=folium.Popup("Côte d'Ivoire"),
            ).add_to(m)

m
```
#### Problem description

If the popup in a CircleMarker contains an apostrophe (See example above) the map is not printed.

#### Expected Output

I expect the map to show the popup properly

#### Output of ``folium.__version__``

Version '0.6.0'

**Comment by ocefpaf** [comment]
You can update to 0.7 or do like in `cell [3]` from [this notebook](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Popups.ipynb).
