### ISSUE TITLE
Folium map not showing in nbviewer

### ISSUE THREAD

**Issue by el-grudge** [python-visualization/folium#1028]
When uploading my jupyter notebook which contains a folium map to github, the map disappears, and a horizontal sliding bar appears instead of it.

Here is the link to the nbviewer page of the notebook:

https://github.com/el-grudge/01--Introduction-to-DataCamp-Projects/blob/master/Introduction%20to%20DataCamp%20Projects%201.ipynb

Here is the code that creates the map:

```python
import folium
phone_map = folium.Map()

companies = [
    {'loc': [37.4970,  127.0266], 'label': 'Samsung: 20.5%'},
    {'loc': [37.3318, -122.0311], 'label': 'Apple: 14.4%'},
    {'loc': [22.5431,  114.0579], 'label': 'Huawei: 8.9%'}] 

for company in companies:
    marker = folium.Marker(location=company['loc'], popup=company['label'])
    marker.add_to(phone_map)

phone_map
```

**Comment by ocefpaf** [comment]
You mean GitHub and not nbviewer, right? I can see you map on nbviewer just fine:

http://nbviewer.jupyter.org/github/el-grudge/01--Introduction-to-DataCamp-Projects/blob/master/Introduction%20to%20DataCamp%20Projects%201.ipynb

Not that GitHub scrubs the JS the map won't show in their rendering. This is not an issue with `folium` BTW.

**Comment by el-grudge** [comment]
Thanks for the feedback, and yes i meant github.
