### ISSUE TITLE
Support for satellite imagery base map tileset as standard, built-in option

### ISSUE THREAD

**Issue by jcox-nd** [python-visualization/folium#1030]
Does the capability exist (or is it planned to be implemented) to have satellite imagery as the base map / tileset as a standard, built-in option? For example, Google with API key, HERE satellite, OpenMapTiles Satellite, or some similar service? In particular, I'm most interested in Google or HERE with API key, owing to the high quality.

If this is possible to achieve with the current release, can you please provide some instructions or an example for a particular service, like OSM, Google or HERE?

If this doesn't exist as a standard option, or at least as a documented example in the documentation, I would like to request that it be added.

**Comment by ocefpaf** [comment]
All you have to do is to pass the URL like:

```python
import os
import folium

keysc = map(os.getenv, ['HEREMAPS_APP_ID', 'HEREMAPS_APP_CODE'])

tiles = f(
    'https://1.base.maps.api.here.com/maptile/2.1/maptile/newest/normal.day/{z}/{x}/{y}/256/png8?'
    'lg=eng&
    'app_id={app_id}&'
    'app_code={app_code}'
)

folium.Map(location=(42, -42), tiles=tiles, zoom_start=10, attr='HERE.com')
```

That is documented and we have some examples in the GitHub examples folder and teh documentation quickstart. For more tiles sources see the last cell from http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/TilesExample.ipynb
