### ISSUE TITLE
How to avoid whole tile layer url in LayerControl?

### ISSUE THREAD

**Issue by meteoDaniel** [python-visualization/folium#1033]
How to avoid this dirty url in the layer control?

```python

    base_map = folium.Map(location=[50.377157, 9.36088], zoom_start=6,
                          tiles='https://api.mapbox.com/styles/v1/'
                                'mapbox/{theme}-v9/tiles/256/{z}/{x}/{y}?'
                                'access_token={token}'.format(theme='dark', z='{z}', x='{x}', y='{y}',
                                                              token=ACCESS_TOKEN_MAPBOX),
                          attr='Live Wetter Map')
```
![bildschirmfoto von 2018-11-30 16-14-09](https://user-images.githubusercontent.com/27021858/49297723-cc647f00-f4bb-11e8-99fb-8c6353900716.png)

**Comment by ocefpaf** [comment]
You can use the `TileLayer` class instead and customize name.

**Comment by ocefpaf** [comment]
> But this might be a bug if it is not posible to avoid this behaviour.

I don't follow.

> Otherwise you have to rename the "tiles" Option in Map Class. Because it is not working as expected.

The expected behavior is to use the URL for unnamed tiles. That is correct.

> My target is to use the mapbox layer as my basemap and not as an additonal tileLayer to the Openstreetmap.

Start with an empty map, tile=None, and add you tile.

**Comment by eoefelein** [comment]
When I specify tile=None in instantiating the folium map object, and later specify with TileLayer, the state names disappear. But when I specify tile=my_custom_tile, I have the same issue, where the entire api name appears in the map's layer control. I haven't found a way to fix it.

**Comment by aleks-mariusz** [comment]
btw, for anyone thinking issue #1316 could be a proper work-around for this: doing it that way seems to NOT have the intended effect, as when i do this, there is NO basemap selected on-loading the page (showing you a mapless page), and you then have to actually click on one of the tile layers in the layer control to display any map layer.. 

really seems like a bug (or poor workflow), just not sure whether it's a folium issue or a LeafLet issue?

i worked around it after m.save by using regex to in-place edit the file, changing the url being embedded as the name of the `layer_control....base_layers` array:

```
with open('index.html', 'r') as f:
    content = f.read()
    content_new = re.sub('"http.*" : tile_layer', r'"your mapname" : tile_layer', content)
with open("index.html", "w") as f:
    f.write(content_new)
```

as with any hacky "solution", YMMV

**Comment by Conengmo** [comment]
can you share a code snippet that didn't work for you? This works for me:

```
m = Map(tiles=None)
TileLayer(
    'https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png',
    attr='attr',
    name='name'
).add_to(m)
```

![afbeelding](https://user-images.githubusercontent.com/33519926/194568078-a0aca8d2-081c-4040-b8e9-18d864d0c847.png)
