### ISSUE TITLE
folium.features.GeoJson could give a more descriptive error when passing GeoDataFrames with missing geometries

### ISSUE THREAD

**Issue by wtadler** [python-visualization/folium#1037]
I frequently pass GeoDataFrames to folium.features.GeoJson. When GeoDataFrames with missing geometries are passed, it gives `ValueError: Unhandled object` and then prints the table. It might be better if it said something more descriptive about how the GeoDataFrame was missing geometries.

[This](https://github.com/python-visualization/folium/blob/master/folium/features.py#L412) appears to be the relevant line. GeoDataFrames with missing geometries do not have the `__geo_interface__` property. Not sure if this is something worth addressing in Folium or in GeoPandas.

#### Replicate error with
```python
import geopandas as gpd
import folium as f

df = gpd.read_file(gpd.datasets.get_path('nybb'))
df.loc[0, 'geometry'] = None

f.features.GeoJson(df)
```

#### Output
```
ValueError: Unhandled object    BoroCode       BoroName     Shape_Leng    Shape_Area  \
0         5  Staten Island  330470.010332  1.623820e+09   
1         4         Queens  896344.047763  3.045213e+09   
2         3       Brooklyn  741080.523166  1.937479e+09   
3         1      Manhattan  359299.096471  6.364715e+08   
4         2          Bronx  464392.991824  1.186925e+09   

                                            geometry  
0                                               None  
1  (POLYGON ((1029606.076599121 156073.8142089844...  
2  (POLYGON ((1021176.479003906 151374.7969970703...  
3  (POLYGON ((981219.0557861328 188655.3157958984...  
4  (POLYGON ((1012821.805786133 229228.2645874023...  .
```
#### Output of ``folium.__version__``
`0.6.0`

**Comment by ocefpaf** [comment]
> How about silently stripping out the rows that have no geometries?

I'm not really sure that is a good idea. I'd rather leave data cleaning to the user than implicitly dropping empty rows. 99.99% of the cases an empty geometry row is indicative of another problem in the data.

**Comment by wtadler** [comment]
What about cleaning the data and raising a warning?

Or should it just raise a more descriptive exception when there are any empty geometries?

**Comment by ocefpaf** [comment]
> Or should it just raise a more descriptive exception when there are any empty geometries?

:+1:

**Comment by wtadler** [comment]
How about:

```python
        elif hasattr(data, 'geometry'):
            if any(data['geometry'].isnull()):
                raise ValueError('Some objects have missing geometries.')
            self.embed = True
            if hasattr(data, 'to_crs'):
                data = data.to_crs(epsg='4326')
            self.data = json.loads(json.dumps(data.to_json()))  # noqa
```

**Comment by ocefpaf** [comment]
Sounds good. How about an error message like:

`Cannot render objects with missing geometries`?

**Comment by wtadler** [comment]
Okay, I'll make a PR.

**Comment by ocefpaf** [comment]
> Okay, I'll make a PR.

Thanks!
