### ISSUE TITLE
Add timestamped geo json to FeatureGroup

### ISSUE THREAD

**Issue by nghia1991ad** [python-visualization/folium#1038]
Hi, could I ask if there is a way to add time stamped geojson object to FeautureGroup? I try to add and the object just disappear. Thanks

**Comment by Conengmo** [comment]
Hi @nghia1991ad, 

The docstring of `TimestampedGeoJson` says:

> Creates a TimestampedGeoJson plugin from timestamped GeoJSONs to append into a map with Map.add_child.

So apparently no, you cannot add it to a `FeatureGroup`.

**Comment by nghia1991ad** [comment]
Thanks for the reply, could I ask if there any other way to add TimestampGeoJson object into layers?

**Comment by Conengmo** [comment]
Not that I know of. You could look in the code and see if there's a way.

**Comment by meteoDaniel** [comment]
Having the same issue

**Comment by julschwarz** [comment]
same issue here!

**Comment by skukovsky** [comment]
Are there any solutions?

**Comment by HugoCambier01** [comment]
Still the same issue. 
Any solution to gather 2 TimestampedGeoJson with same "times" in a single map with only 1 timeline bar and in 2 different layers ? 
Adding TimestampedGeoJson to GroupFeature would do the trick but it seems that it is still impossible
