### ISSUE TITLE
Is there a way to add markers to Choropleth maps?

### ISSUE THREAD

**Issue by nonoumasy** [python-visualization/folium#1043]
I would like to add markers/popup with Choropleth maps. Will this be supported in the future?

**Comment by ocefpaf** [comment]
> I would like to add markers/popup with Choropleth maps. Will this be supported in the future?

Unless I don't understand your question it already is. Just create the objects and add them to the map.

**Comment by nonoumasy** [comment]
Most markers have a specific long and lat. So how do you position it when its a polygon in a choropleth map?
Can you point me where I can find this in the docs?
