### ISSUE TITLE
Most markers have a specific long and lat. So how do you position it when its a polygon in a choropleth map?

### ISSUE THREAD

**Issue by nonoumasy** [python-visualization/folium#1044]
Most markers have a specific long and lat. So how do you position it when its a polygon in a choropleth map?
Can you point me where I can find this in the docs?

_Originally posted by @nonoumasy in https://github.com/python-visualization/folium/issues/1043#issuecomment-450232469_

**Comment by ocefpaf** [comment]
Markers only exist at a point. Maybe you mean a popup? If so please check the docs or ask on gitter/stackoverflow. Let's keep the issue tracker for code issues and usage questions in those other two.
