### ISSUE TITLE
How to let the bottom line show green on the top when there is lots of lines overlay at the same time?

### ISSUE THREAD

**Issue by Smith7z** [python-visualization/folium#1048]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behavior is a problem and what is the expected output.]

**Comment by Smith7z** [comment]
When I use the search plugin,I found many lines are overlay at the same time.
So it didn't turn green when the line is under the bottom of other line.

**Comment by Smith7z** [comment]
Also,how can let "search" plugin not show this cluster of lines at the first?

**Comment by ocefpaf** [comment]
With the code to debug this there is nothing we can do :-/

Also, you may have reached the a plugin limitation there.
