### ISSUE TITLE
Merge fol_template.htm and geojson_template.html

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#105]
@birdage While investigating #30 I found out that several changes to `fol_template.html` are not in `geojson_template.html`, like the custom and clustered markers.

That makes me wonder if we should have only one base template and a sub-template for geojson (not sure how to do that), or only one template that works for both even if we load unnecessary java-stuff.

**Comment by birdage** [comment]
this is correct i just updated the base map fol template when i made the changes, i think you are right we should have one template for these things.

**Comment by themiurgo** [comment]
I agree. I think this is a result of the fact that geojson is considered in folium to be used mostly as an overlay (from the docs: "Folium allows you to plot a GeoJSON or TopoJSON overlay on the map").

This is generally false, and recently it's not uncommon to have find marker features, lines, and polygons encoded as geojson (as shown in [geojson.io](http://geojson.io) and [GitHub](
https://help.github.com/articles/mapping-geojson-files-on-github/), for example).

I think it would be good to slowly change this aspect of folium and handle geojson similarly to any other feature, following closely Leaflet behaviour (http://leafletjs.com/examples/geojson.html).

**Comment by ocefpaf** [comment]
>  it's not uncommon to have find marker features, lines, and polygons encoded as geojson (as shown in geojson.io and GitHub, for example).

@themiurgo that sounds interesting and, after reading #120, I can see the appeal.  The HTML looks much clearer.  However, if I understood it correctly, all GeoJSON would be embedded in the HTML, right?  I guess that some people appreciate the fact that can have a separate file for the GeoJSON.  Still, that does not stop us from implementing something for makers, lines, polygons and etc.

> I think it would be good to slowly change this aspect of folium and handle geojson similarly to any other feature, following closely Leaflet behaviour (http://leafletjs.com/examples/geojson.html).

Agreed.  Is that something you would like to tackle?

**Comment by themiurgo** [comment]
> @themiurgo that sounds interesting and, after reading #120, I can see the appeal. The HTML looks much clearer. However, if I understood it correctly, all GeoJSON would be embedded in the HTML, right? I guess that some people appreciate the fact that can have a separate file for the GeoJSON. Still, that does not stop us from implementing something for makers, lines, polygons and etc.

Yes, although #120 is related, what I mean here is related to the types fragmentation in folium. In Leaflet there is a thing as Feature, and you can have popups on it. In Folium each feature is handled very differently, so you end up having popups in markers but not in geojson or lines (for example) and you need to replicate code to obtain the same behaviour. GeoJSON suffers this particularly much (as you were noting in this issue. Handling all the features more generally would simplify the code and extend new functionalities to all the objects automatically.

> I think it would be good to slowly change this aspect of folium and handle geojson similarly to any other feature, following closely Leaflet behaviour (http://leafletjs.com/examples/geojson.html).

Although I won't officially commit to it, I can definitely try to slowly fix this. These days I'm working a lot on folium because of my work, so I'm happy to contribute back some modifications I needed to make to suit my needs, if they're in line with the project.

**Comment by ocefpaf** [comment]
We are all volunteers here so do not worry about "officially commit to it" :wink:

> These days I'm working a lot on folium because of my work.

Glad folium is of value for you and that your work is making the code base better.  If what you are doing is open and publishable do you mind sending as a preview?  I would like to start an examples page for folium docs.

**Comment by themiurgo** [comment]
At the moment not having much open / publishable unfortunately, but will definitely send something if this changes.

**Comment by ocefpaf** [comment]
> Handling all the features more generally would simplify the code and extend new functionalities to all the objects automatically.

BTW: I am all for that!  I just don't have to time now.  But anything you throw at us will be review with care :stuck_out_tongue_winking_eye:

**Comment by ocefpaf** [comment]
This is being addressed in #147.
