### ISSUE TITLE
Folium choropleth map using pandas dataframe field as fill_color variable

### ISSUE THREAD

**Issue by cjamwill** [python-visualization/folium#1051]
```python
# Your code here

#Grab Westminster parliamentary constituency shapefiles from Martin Chorley's github repository
import requests
import json
url='https://github.com/martinjc/UK-GeoJSON/blob/master/json/electoral/gb/wpc.json?raw=true'
r = requests.get(url)

with open("wpc.json", "wb") as code:
    code.write(r.content)

#Free up memory...
r=None

with open('wpc.json', 'r') as output:
    boundaries = json.load(output)

#import csv with election results - see attached file "election winners 2017"
import pandas as pd

election_winners_2017 = pd.read_csv('election_winners_2017')


#create folium map

data_map = folium.Map(location=[55, -0.2], zoom_start=5)

data_map.choropleth(geo_data=boundaries,
                   data=election_winners_2017,
                   columns=['Code', 'Year 2017'],
                   key_on='feature.properties.PCON13CD',
                   fill_color = election_winners_2017['Colour']
                   #fill_color = 'BuPu'
                   )

data_map.save('data_map.html')


```
#### Problem description

Hi - I'm using folium to map the last UK election winners, by UK constituency. I have the relevant GeoJson boundaries, and linking data indicating the winner of each constituency. 

My target is to colour each constituency on the map with the colour of the relevant part (Conservative = blue, Labour = red etc). I have a field in my data set (election winners 2017) called "Colour" which has a description of the colour, eg 'blue'. Also have a field in the same dataframe called "Colour Brewer" which has the hex values of colours.

I'm using the choropleth class to overlay the geojson. I'd then like to assign the election_winners_2017['Colour'] field from the dataframe to the fill_color property, though this is returning an value error 
"ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()."

Any ideas on how I can adjust my code to obtain the desired effect?

[this should explain **why** the current behavior is a problem and what is the expected output.]

#### Expected Output

Constituencies coloured based on the dataframe field election_winners_2017['Colour']

Expected image below:

![image](https://user-images.githubusercontent.com/46572078/51025748-c070e000-1584-11e9-857c-374fd9e7d522.png)

Found at the below link:

https://blog.ouseful.info/2015/04/17/creating-interactive-election-maps-using-folium-and-ipython-notebooks/

#### Output of ``folium.__version__``

0.6.0

[election_winners_2017.zip](https://github.com/python-visualization/folium/files/2748949/election_winners_2017.zip)

**Comment by jtbaker** [comment]
Take a look at he example uses of `Choropleth` (it's been converted to its own class, although I think the original map method is still available) at the [nbviewer example](https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/GeoJSON_and_choropleth.ipynb)(full repo [here](https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/)).

I think your main issue is that `fill_color` wants to be passed a string representing a color ramp scale.

The GeoJson may meet your needs a little better if you want more manual control over the colors.

Check out an example of how to use it in conjunction with a few other features [here](https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/plugin-Search.ipynb)
