### ISSUE TITLE
Map does not scale in Jupyter Notebook / Lab

### ISSUE THREAD

**Issue by roberteyre** [python-visualization/folium#1057]
```python

m = folium.Map(
    location=[27.705562, 85.321767],
    tiles='Stamen Toner',
    zoom_start=12,
    width='50%', height='60%',
    control_scale=True,
    zoom_control=False,
    max_zoom=12, min_zoom=12
)

```
#### Problem description

Draws the map at the correct scale, but the cell remains the size of the map before rescaling.

#### Expected Output

Cell height to scale to the Map height

**Comment by roberteyre** [comment]
EDIT: found a work around, however I still believe the issue stands.

f = folium.Figure(width=400, height=450)

m = folium.Map(
    location=[27.695562, 85.321767],
    tiles='Stamen Toner',
    zoom_start=12,
    control_scale=True,
    zoom_control=False,
    max_zoom=12, min_zoom=12
)

folium.Rectangle(kathmandu_coords, color='red', fill_color='black', fill_opacity=0.05).add_to(m)

f.add_child(m)

f

**Comment by Conengmo** [comment]
Hi @roberteyre, thanks for bringing this up. I found this issue that relates to this:
https://github.com/python-visualization/folium/issues/229

You say you think the issue still stands. Can you tell what you think the behavior should be and why?
