### ISSUE TITLE
Show circle marker when selecting a single point

### ISSUE THREAD

**Issue by ljredman1** [python-visualization/folium#1064]
```
import folium
import pandas as pd

ladcor_df = pd.read_csv("C:\\Users\\lredman\\algo-datascience\\algo_datascience_luke_test\\ladcor_store_locations.csv")
glasgow_town_list = ['alexandria', 'clydebank', 'coatbridge', 'glasgow', 'johnstone', 'renfrew', 'hamilton', 'paisley']
glasgow_df = ladcor_df[ladcor_df['town_name'].isin(glasgow_town_list)]
glasgow_df = glasgow_df[glasgow_df['store_postcode'].str.startswith('G')]
glasgow_df['label'] = glasgow_df['store'] + ' - ' + glasgow_df['store_address'] + ', ' + glasgow_df['store_postcode']
glasgow_df['colour'] = 'red'
glasgow_df.loc[glasgow_df['brand_id']==82211.0,'colour'] = 'blue'

location=[55.8642, -4.2518]
locationlist = glasgow_df[["latitude","longitude"]].values.tolist()
labels = glasgow_df['label'].values.tolist()

m = folium.Map(location=location, zoom_start=11)
feature_group = folium.FeatureGroup(name='Store Address')

for point in range(len(locationlist)):
    if 'Coral' in labels[point]:
        color = 'blue'
    else:
        color = 'red'

    popup = folium.Popup(labels[point], parse_html=True)
    folium.Marker(locationlist[point], popup=popup, icon=folium.Icon(color=color)).add_to(m)
    folium.Circle(locationlist[point], popup=labels[point], radius=500, fill=True).add_to(feature_group)
    feature_group.add_to(m)
    folium.LayerControl().add_to(m)

m.save('map.html')

```

Hi guys,

I am trying to create an interactive map showing store locations of Ladbrokes and Coral in Glasgow. I want to be able to select a store and then have a circle marker highlight a 500m radius around just that store. Currently I can only show it for all stores.

Does anyone know if this is possible?

Thanks in advance

**Comment by ljredman1** [comment]
Ignore me all, I have figured it out...

import folium
import pandas as pd

ladcor_df = pd.read_csv("C:\\Users\\lredman\\algo-datascience\\algo_datascience_luke_test\\ladcor_store_locations.csv")
glasgow_town_list = ['alexandria', 'clydebank', 'coatbridge', 'glasgow', 'johnstone', 'renfrew', 'hamilton', 'paisley']
glasgow_df = ladcor_df[ladcor_df['town_name'].isin(glasgow_town_list)]
glasgow_df = glasgow_df[glasgow_df['store_postcode'].str.startswith('G')]
glasgow_df['label'] = glasgow_df['store'] + ' - ' + glasgow_df['store_address'] + ', ' + glasgow_df['store_postcode']
glasgow_df['colour'] = 'red'
glasgow_df.loc[glasgow_df['brand_id']==82211.0,'colour'] = 'blue'

location=[55.8642, -4.2518]
locationlist = glasgow_df[["latitude","longitude"]].values.tolist()
latlist = glasgow_df['latitude'].values.tolist()
longlist = glasgow_df['longitude'].values.tolist()
labels = glasgow_df['label'].values.tolist()

m = folium.Map(location=location, zoom_start=11)

store_list = []
for i in range(0, len(latlist)):
    if 'Coral' in labels[i]:
        color = 'blue'
    else:
        color = 'red'
    locals()['store_group_' + str(i)] = folium.FeatureGroup(name=labels[i])
    popup = folium.Popup(labels[i], parse_html=True)
    folium.Marker([latlist[i], longlist[i]], popup=popup, icon=folium.Icon(color=color)).add_to(m)
    folium.Circle([latlist[i], longlist[i]], radius=500, fill=True).add_to(locals()['store_group_' + str(i)])
    locals()['store_group_' + str(i)].add_to(m)
    store_list.append('store_group_' + str(i))

folium.LayerControl().add_to(m)

m.save('ladcor_glasgow_map.html')


Rubber duck debugging at its best!

**Comment by Conengmo** [comment]
Good to hear :)
