### ISSUE TITLE
MouseLocation plugin not showing up

### ISSUE THREAD

**Issue by FabeG** [python-visualization/folium#1065]
I tried to use the mouseLocation plugin (with folium master version):

import folium
import folium.plugins
m = folium.Map(location=[48, 8.33])
folium.plugins.MousePosition().add_to(m)
m.save('test.html')

But nothing appeared.

There seems to be a problem with the url referencing this plugin: 

<script src="https://rawcdn.githack.com/ardhi/Leaflet.MousePosition/c32f1c84/src/L.Control.MousePosition.js"></script>
<link rel="stylesheet" href="https://rawcdn.githack.com/ardhi/Leaflet.MousePosition/c32f1c84/src/L.Control.MousePosition.css"/>

The javascript console raised a 403 Forbidden error.

Changing rawcdn into raw (then https://raw.githack.com/ardhi/Leaflet.MousePosition/c32f1c84/src/L.Control.MousePosition.css and raw.githack.com/ardhi/Leaflet.MousePosition/c32f1c84/src/L.Control.MousePosition.js) in the generated html file made the plugin appear. 

Since I am not familiar with rawcdn.githack I have no idea where the problem could come from.

**Comment by Conengmo** [comment]
Hi @FabeG, I don't seem to have this problem. Can you verify that it's still a problem for you?

We do want to use the rawcdn version of the link. See https://raw.githack.com/

Maybe we should update the URL with a freshly created link from raw.githack.com. Can you try if that solves the issue maybe?

https://github.com/ardhi/Leaflet.MousePosition/blob/master/src/L.Control.MousePosition.js

**Comment by FabeG** [comment]
Hi @Conengmo, no more problem now with the initial URL (https://rawcdn.githack.com/ardhi/Leaflet.MousePosition/c32f1c84/src/L.Control.MousePosition.js). Strange problem, then...
Would it be possible for this URL to have been temporarly unavailable ?

**Comment by Conengmo** [comment]
Your guess is as good as mine :) But good to hear it is no longer a problem. I'll close the issue then.
