### ISSUE TITLE
airplane_marker

### ISSUE THREAD

**Issue by md-thomas** [python-visualization/folium#1066]
Would it be possible to get an airplane marker?
Or, have the ability to rotate a Marker that uses a CustomIcon?

**Comment by md-thomas** [comment]
I found a rotate icon example.
Not exactly what I was looking for, but I will try and use that.

**Comment by Conengmo** [comment]
There already is an airplane icon: https://fontawesome.com/v4.7.0/icon/plane
You can use it with our regular `Icon` class, but note you have to change the prefix.
https://python-visualization.github.io/folium/docs-v0.6.0/modules.html#folium.map.Icon
You can also give in an angle there.

**Comment by yana209** [comment]
The markers with plane icon appears as plane on the default marker instead of the plane itself. Is there no way, to use the icon itself without it being embedded in the marker?

**Comment by Conengmo** [comment]
You could use DivIcon to have a custom image. See the example notebooks for some inspiration.
