### ISSUE TITLE
PyQt4.QWebKit.QWebView

### ISSUE THREAD

**Issue by md-thomas** [python-visualization/folium#1067]
This may not be supported, but I'll ask anyway.

I'm embedding the html inside a QtWidget (QWebView).

Any time I add elements (Marker, Circle, Polygon) to the map, the map doesn't render, using v0.7.0.
folium v0.6.0 appears to work correctly.

Both versions work, whenever I use a web browser to view the html.

OS: CentOS 7.6.1810
qt: 1.4.8.7-2
qtwebkit: 2.3.4-6
PyQt4: 4.10.1-13
PyQt4-webkit: 4.10.1-2

I can provide the working/non-working html, if needed.

**Comment by Conengmo** [comment]
Hmm don't know... we switched to Javascript template literals recently, maybe that has something to do with it?
