### ISSUE TITLE
Can I display multiple values on a Popup?

### ISSUE THREAD

**Issue by nonoumasy** [python-visualization/folium#1068]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here

```
#### Problem description

I would like to have add multiple values on the popup from a pandas dataframe.
eg
date_occured
crime_level
crime_code_description

#### Expected Output
Here is a link to a WIP map.
file:///Users/nonoumasy/Desktop/crime_map.html. 
the popup works but only uses 1 value.

One possible solution would be to combine the value into one column first and then add that to the popup.

**Comment by Conengmo** [comment]
Assuming you're using regular popups: you can combine values in a single string, which you pass to the popup. This is normal Python stuff, not something we're going to do in folium.

e.g.
```
my_string = 'date: {}, value: {}'.format(date_occured, crime_level)
Popup(my_string)
```

If you're using geojson, have a look at the `GeoJsonTooltip` class and the relevant example Jupyter notebooks. It doesn't work with a pandas dataframe, but you can take those values and put them in the geojson to use with `GeoJsonTooltip`.
