### ISSUE TITLE
Choropleth does not work...

### ISSUE THREAD

**Issue by APandaInFjord** [python-visualization/folium#1069]
My data set is directly from here:
https://www.eriksmistad.no/upload/fylker.json

I just added a column of integer numbers into it, titled Nummer_Restauranter

What I want to do is to make a choropleth map which shows Nummer_Restauranter per Fylker.

The codes I used is 

```
map_Oslo_center = folium.Map(location=[59.9139, 10.7522],
                    zoom_start = 11)
map_Oslo_center.choropleth(
    geo_data=Fylker_with_count_rest,
    name='geometry',
    data=Fylker_with_count_rest,
    columns=['fylkesnummer', 'Nummer_Restauranter'],
    key_on='feature.properties.navn',
    fill_color='Reds',
    fill_opacity=0.5,
    line_opacity=1.0,
    legend_name='Number of Restuarnt per Fylker'
)
folium.LayerControl().add_to(map_Oslo_center)
display(map_Oslo_center)   
```

All I got is a map with Oslo in the center and legend, but no choropleth. And no error message.

Can anyone help with this?

Thanks in advance!

(Add: Fylker_with_count_rest is just the download of https://www.eriksmistad.no/upload/fylker.json
except that after download I added a column (Nummer_Restauranter) of integers into it.)

**Comment by Conengmo** [comment]
`feature.properties.navn` field in your geojson is a list instead of a number, that should be fixed.

I don't have you `Fylker_with_count_rest` data, so can't check that.

**Comment by APandaInFjord** [comment]
Hi, Fylker_with_count_rest is just the download of https://www.eriksmistad.no/upload/fylker.json
except that after download I added a column (Nummer_Restauranter) of integers into it.

**Comment by Conengmo** [comment]
The choropleth class expects you to use two data sources: a geojson object and a pandas data frame. The class will use values from the data frame and apply them to the geometry in the geojson. You don’t seem to use a pandas data frame, instead your values already are in the geojson data. That means that using the choropleth class won’t work for you.

Instead have a look at the GeoJson class, and it’s style_function argument in particular. There are examples available in the example notebooks.

**Comment by APandaInFjord** [comment]
I have tried with two datasets also. Aslo did not work. I am afraid there is something wrong with the choropleth function. But using style_functioned worked.
