### ISSUE TITLE
Input From Map

### ISSUE THREAD

**Issue by Joey-Clary** [python-visualization/folium#1070]
I have been looking around the documentation and I know how to view the latitude and longitude of a marker when it is placed on the map, but is it possible to return the latitude and longitude of a marker when it is placed instead of just displaying it? I need to use this imputed latitude and longitude elsewhere in the program to display data correlated to that location.

Thanks for any help!

**Comment by ocefpaf** [comment]
If you want to do that in a notebook not that two way interactions are not trivial in Jupyter notebooks as it used to be in the old IPython notebook. I recommend you looking it `ipyleafet` b/c it is supported by the Jupyter team.

If you are using something else, like `dash`, or your own thing, you will need to mess with the JS to get a variable back to create your callback, there is nothing built-in in folium for that.

**Comment by stefanocudini** [comment]
if I understand correctly at now it is not possible to insert user input on the folium map?
