### ISSUE TITLE
Link to http://python-visualization.github.io/folium/ results in 404 Error

### ISSUE THREAD

**Issue by tylere** [python-visualization/folium#1077]
#### Problem description

On the repo's main page https://github.com/python-visualization/folium
the link to http://python-visualization.github.io/folium/
results in a 404 File Not Found error.

**Comment by ocefpaf** [comment]
Thanks for reporting. The docs are in flux at the moment and will be up soon.

**Comment by ocefpaf** [comment]
The docs are up again. We have versioned docs in

http://python-visualization.github.io/folium/version-v0.8.2

dev dcos in

http://python-visualization.github.io/folium/dev/

and current version in 

http://python-visualization.github.io/folium
