### ISSUE TITLE
jQuery google cdn cannot use in China. Can replace it with other cdn provider

### ISSUE THREAD

**Issue by liweiwp** [python-visualization/folium#1085]
We all know that google api cannot use in China, so the jQuery the folium reference is not available also. When using folium in China, it's so bad, can replace this with other cdn provider, I change the iQuery from google to code.jquery.com, the map can display normal.

**Comment by Conengmo** [comment]
Fair enough, seems like a small change. PR pending.

**Comment by ocefpaf** [comment]
Just a minor comment. When you say:

> We all know that google api cannot use in China,

it implies that we knowingly used something that would be blocked and hence accepted the block. I for one did not know and never intended to use something that would block users anywhere.

**Comment by liweiwp** [comment]
> Just a minor comment. When you say:
> 
> > We all know that google api cannot use in China,
> 
> it implies that we knowingly used something that would be blocked and hence accepted the block. I for one did not know and never intended to use something that would block users anywhere.

Sorry for say that. Indeed this is special in my region.

**Comment by ocefpaf** [comment]
> Sorry for say that. Indeed this is special in my region.

No problem. I just want to make sure that we don't want exclude anyone. PR #1086 should fix it, if you can test please let us know. I'm planning on a new release with that fix next week.
