### ISSUE TITLE
How to scale the markers and lines for panning and zooming ?

### ISSUE THREAD

**Issue by dvu4** [python-visualization/folium#1092]
#### Problem description

Is there any way I can scale the lines and icons on map when zooming in/out the map in Folium? .

**Comment by Conengmo** [comment]
Not that I know of in folium. You would have to look at the underlying Leafletjs library to see if it’s possible. If it is, you can either hack it yourself or we can add it to folium. Either way, nice if you report back here if you find anything.

**Comment by tishacian** [comment]
Hi,
I might have a point accordingly to this question, it would be really great if the Leaflet method get_Zoom() could be implemented in Folium in order to adapt the GeoJSON for each zoom level.

Thanks for your great work btw!
