### ISSUE TITLE
Adding a fixed image logo to a python/folium map

### ISSUE THREAD

**Issue by spanishinquistion** [python-visualization/folium#1093]
Hello, I am trying to doing some data analysis and plotting the results to a map via folium, which works. However, I am obligated to acknowledge the creators of the data and want to post their logo on the map. 
The logo should always be visible and a marker is not if you scroll/move around so I need a better suggestion. 

icon = folium.features.CustomIcon('mylogo.png',icon_size=(100, 100))
folium.Marker([ lat, long],popup='many thanks to the data guys', icon=icon).add_to(mymap)

Can I work around by posting a .png/jpg as a legend? Something that stays on screen and is not lat/lon dependent? Or a better idea?

**Comment by ocefpaf** [comment]
Check https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/FloatImage.ipynb

**Comment by ocefpaf** [comment]
It was fixed and changing master to main should work: https://nbviewer.org/github/python-visualization/folium/blob/main/examples/FloatImage.ipynb

**Comment by EmanuelCastanho** [comment]
Can FloatImage be grouped in a layer?
I am using FloatImage to display a colorbar and I would like it to show on the map only when a specific layer is activated.
