### ISSUE TITLE
HeatMapWithTime not displayed in browser when adblock extension is enabled

### ISSUE THREAD

**Issue by mazzma12** [python-visualization/folium#1096]
Already solved here #881 but it looks like it is backed on my version. See description below

#### Please add a code sample or a nbviewer link, copy-pastable if possible
* Enable adblock addon in your browser (used  ublock with firefox 65.0.1)
* Run the example HeatMapWithTime.ipynb available here: https://github.com/python-visualization/folium/blob/master/examples/HeatMapWithTime.ipynb

#### Problem description
The heatmap does not show up

#### Output of ``folium.__version__``

0.7.0, 0.8.0, 0.8.2

#### Solution

Disable Adblock extension 

#### Suggestion 

Advertise about it as it was really long to find out.

**Comment by Conengmo** [comment]
Hi @mazzma12, thanks for sharing your bug report. I understand that it can be frustrating to figure this kind of problem out.

Can you check in your ublock logger which resource got blocked in particular? Maybe we can circumvent it just like the previous time.

**Comment by mazzma12** [comment]
```
    html.gr__localhost21,933
        body.notebook_app.command_mode21,932
            div1
                div#MathJax_Hidden
            div#MathJax_Message
            noscript
            div#header408
                div#header-container.container11
                    div#ipython_notebook.nav.navbar-brand2
                        a[href^="/tree"]1
                    span#save_widget.save_widget3
                        span#notebook_name.filename
                        span.checkpoint_status
                        span.autosave_status
                    span#kernel_logo_widget1
                    span#login_widget1
                div.header-bar
                div#menubar-container.container393
                div.lower-header-bar
            div#site21,505
            div#pager.ui-resizable8
            div1
            svg#js-plotly-tester1
```
Sorry for the formatting, this is the closest I got. Can this help ?

**Comment by mazzma12** [comment]
Got it : `https://rawcdn.githack.com/pa7/heatmap.js/develop/plugins/leaflet-heatmap/leaflet-heatmap.js`

```
Filter/heatmap.js
Filter listEasyPrivacy 
Root contextlocalhost
Contextmail.google.com
Partyness(3,3) localhost ⋯ google.com ⇒ githack.com
Typescript
URLhttps://rawcdn.githack.com/pa7/heatmap.js/develop/plugins/leaflet-heatmap/leaflet-heatmap.js
```

**Comment by Conengmo** [comment]
Ah good one. We can host that one as well, just like the other one. Would you like to make a PR?

**Comment by mazzma12** [comment]
Sure I can try. I am just curious about 2 things : 
* What about the library license? I do not see any for [this one](https://rawcdn.githack.com/pa7/heatmap.js/develop/plugins/leaflet-heatmap/leaflet-heatmap.js) could it be a problem? 
* How do you deal with the fact that libraries get updated?

**Comment by Conengmo** [comment]
The library license is MIT, so no problems there: https://github.com/pa7/heatmap.js/blob/master/LICENSE

Yeah updates will be tricky, but this library is already very stable. The [last release](https://github.com/pa7/heatmap.js/releases) was in 2016, so I think we're safe ignoring updates.

**Comment by mazzma12** [comment]
Coming back to this and I see that https://rawgit.com/ is now deprecated. I started including the library in the template folder, but I am not sure what todo next.

**Comment by jtbaker** [comment]
Hey @mazzma12, there is a new proxy service that works the came way at https://rawcdn.githack.com we've factored most of our code over to use I believe.

**Comment by mazzma12** [comment]
Thx just figured out how it works

**Comment by jtbaker** [comment]
All good! It looks like we already have a version hosted for exactly this issue here: https://github.com/python-visualization/folium/blob/master/folium/templates/pa7_hm.min.js
so just make sure to reference it with the cdn reference for it in the root element: https://rawcdn.githack.com/python-visualization/folium/master/folium/templates/pa7_hm.min.js

**Comment by mazzma12** [comment]
Not sure what's wrong, is it because it points to the develop branch?
```python
        figure.header.add_child(
            JavascriptLink('https://rawcdn.githack.com/pa7/heatmap.js/develop/plugins/leaflet-heatmap/leaflet-heatmap.js'),  # noqa
            name='leaflet-heatmap.js')
``` 
heatmap_with_time.py:173

**Comment by Conengmo** [comment]
?? 

You'll have to copy the JS code from https://rawcdn.githack.com/pa7/heatmap.js/develop/plugins/leaflet-heatmap/leaflet-heatmap.js to a new file in our folium repo. Then once that PR is merged, we can replace the use of https://rawcdn.githack.com/pa7/heatmap.js/develop/plugins/leaflet-heatmap/leaflet-heatmap.js in `heatmap_with_time.py` with the address of the same file in our folium repo.

**Comment by Conengmo** [comment]
This change was done: https://github.com/python-visualization/folium/commit/fc95a604e908a4e7f896900fdfb7ca73f866d069
