### ISSUE TITLE
Timeslider function for polylines?

### ISSUE THREAD

**Issue by hackenjoe** [python-visualization/folium#1103]
Hello,

is there an extension for adding timeslider to a folium map featuring markers and polylines? All that I found was a heatmap with such a function... It would be nice to show only the polylines at a given timestamp (e.g. switch polylines between 3 p.m and 3 a.m).

**Comment by ocefpaf** [comment]
You will need a time stamped geojson. See cell [8] from this example:

https://nbviewer.jupyter.org/github/python-visualization/folium/blob/32f8fddcbaee9e8f566ad5c142d378b44aafd84c/examples/Plugins.ipynb

PS: this is a usage question and not an issue with the code base. Please ask that on gitter and/or stackoverflow, not the issue tracker.
