### ISSUE TITLE
[Support] PopUp text in different lines

### ISSUE THREAD

**Issue by trburak35** [python-visualization/folium#1110]
folium.Marker(location=[data["lat"], data["long"]], popup=("Name: " + str(data["name"]))).add_to(m)
![ce8e6086f11b3c1c2a3e14c2ec572b1c](https://user-images.githubusercontent.com/48861529/54867839-fa2c4700-4d7c-11e9-955d-e294c73bd6bf.png)
![268594a226ca2717e0db87df01db49b3](https://user-images.githubusercontent.com/48861529/54867846-0dd7ad80-4d7d-11e9-9f10-b9f9082d130d.png)

```
#### Problem description

This is meant to create a marker for a location and display the locations name, it does this correctly. The problem is at every space between words it creates a new line.


#### Expected Output

How would I make all the text be in the same line, ideally inside python. Is there an attribute to simply add inside the marker command?

Cheers

**Comment by Conengmo** [comment]
Try the ‘max_width’ argument with the ‘Popup’ class. If you use a number you can increase the width. If you look at the folium example notebooks you can find examples of how to use the ‘Popup’ class.

**Comment by trburak35** [comment]
I took a look and added the width line but still no change.
![](https://i.gyazo.com/e51e27c6e48f3d6f4f6cbfe08b9c7071.png)
