### ISSUE TITLE
remove markers

### ISSUE THREAD

**Issue by AndrewMarines** [python-visualization/folium#1115]
How can i remove markers/circle from a map knowing his coordinates?
in case there's no possibility how can i remove all markers/circle from a map?

**Comment by Conengmo** [comment]
Hi Andrew, you can put the markers in a `FeatureGroup` and add a `LayerControl` to your map. Here's an example: https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/FeatureGroup.ipynb

Other than that there is not really an option in folium to dynamically delete markers... You could of course add custom Javascript to do this! You would have to look at the Leaflet documentation for how to do this.

**Comment by jwhendy** [comment]
This is the closest I've come to finding what I'm looking for. I'm novice level, so forgive the question... it's not apparent how one might toggle the `FeatureGroup` via code. Is the only way to achieve this via clicking using `LayerControl`?

Is there an `.foo(m)` that is basically the opposite of `.add_to(m)`?
