### ISSUE TITLE
folium.plugins doesn't work on Azure Jupyter notebook 

### ISSUE THREAD

**Issue by nonoumasy** [python-visualization/folium#1119]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python

from folium.plugins import FastMarkerCluster

```
#### Problem description

ERROR:root:An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 8))

---------------------------------------------------------------------------
TemplateAssertionError                    Traceback (most recent call last)
<ipython-input-60-3384a527373d> in <module>()
----> 1 from folium.plugins import FastMarkerCluster

~/anaconda3_420/lib/python3.5/site-packages/folium/plugins/__init__.py in <module>()
     29 from folium.plugins.polyline_text_path import PolyLineTextPath
     30 from folium.plugins.scroll_zoom_toggler import ScrollZoomToggler
---> 31 from folium.plugins.search import Search
     32 from folium.plugins.terminator import Terminator
     33 from folium.plugins.time_slider_choropleth import TimeSliderChoropleth

~/anaconda3_420/lib/python3.5/site-packages/folium/plugins/search.py in <module>()
     18 
     19 
---> 20 class Search(MacroElement):
     21     """
     22     Adds a search tool to your map.

~/anaconda3_420/lib/python3.5/site-packages/folium/plugins/search.py in Search()
     90 
     91         {% endmacro %}
---> 92         """)  # noqa
     93 
     94     def __init__(self, layer, search_label=None, search_zoom=None,

~/anaconda3_420/lib/python3.5/site-packages/jinja2/environment.py in __new__(cls, source, block_start_string, block_end_string, variable_start_string, variable_end_string, comment_start_string, comment_end_string, line_statement_prefix, line_comment_prefix, trim_blocks, lstrip_blocks, newline_sequence, keep_trailing_newline, extensions, optimized, undefined, finalize, autoescape)
    924             frozenset(extensions), optimized, undefined, finalize, autoescape,
    925             None, 0, False, None)
--> 926         return env.from_string(source, template_class=cls)
    927 
    928     @classmethod

~/anaconda3_420/lib/python3.5/site-packages/jinja2/environment.py in from_string(self, source, globals, template_class)
    860         globals = self.make_globals(globals)
    861         cls = template_class or self.template_class
--> 862         return cls.from_code(self, self.compile(source), globals, None)
    863 
    864     def make_globals(self, d):

~/anaconda3_420/lib/python3.5/site-packages/jinja2/environment.py in compile(self, source, name, filename, raw, defer_init)
    563         except TemplateSyntaxError:
    564             exc_info = sys.exc_info()
--> 565         self.handle_exception(exc_info, source_hint=source_hint)
    566 
    567     def compile_expression(self, source, undefined_to_none=True):

~/anaconda3_420/lib/python3.5/site-packages/jinja2/environment.py in handle_exception(self, exc_info, rendered, source_hint)
    752             self.exception_handler(traceback)
    753         exc_type, exc_value, tb = traceback.standard_exc_info
--> 754         reraise(exc_type, exc_value, tb)
    755 
    756     def join_path(self, template, parent):

~/anaconda3_420/lib/python3.5/site-packages/jinja2/_compat.py in reraise(tp, value, tb)
     35     def reraise(tp, value, tb=None):
     36         if value.__traceback__ is not tb:
---> 37             raise value.with_traceback(tb)
     38         raise value
     39 

<unknown> in template()

~/anaconda3_420/lib/python3.5/site-packages/jinja2/environment.py in _generate(self, source, name, filename, defer_init)
    513         .. versionadded:: 2.5
    514         """
--> 515         return generate(source, self, name, filename, defer_init=defer_init)
    516 
    517     def _compile(self, source, filename):

~/anaconda3_420/lib/python3.5/site-packages/jinja2/compiler.py in generate(node, environment, name, filename, stream, defer_init)
     60     generator = environment.code_generator_class(environment, name, filename,
     61                                                  stream, defer_init)
---> 62     generator.visit(node)
     63     if stream is None:
     64         return generator.stream.getvalue()

~/anaconda3_420/lib/python3.5/site-packages/jinja2/visitor.py in visit(self, node, *args, **kwargs)
     36         f = self.get_visitor(node)
     37         if f is not None:
---> 38             return f(node, *args, **kwargs)
     39         return self.generic_visit(node, *args, **kwargs)
     40 

~/anaconda3_420/lib/python3.5/site-packages/jinja2/compiler.py in visit_Template(self, node, frame)
    814         self.pull_locals(frame)
    815         self.pull_dependencies(node.body)
--> 816         self.blockvisit(node.body, frame)
    817         self.outdent()
    818 

~/anaconda3_420/lib/python3.5/site-packages/jinja2/compiler.py in blockvisit(self, nodes, frame)
    490         try:
    491             for node in nodes:
--> 492                 self.visit(node, frame)
    493         except CompilerExit:
    494             pass

~/anaconda3_420/lib/python3.5/site-packages/jinja2/visitor.py in visit(self, node, *args, **kwargs)
     36         f = self.get_visitor(node)
     37         if f is not None:
---> 38             return f(node, *args, **kwargs)
     39         return self.generic_visit(node, *args, **kwargs)
     40 

~/anaconda3_420/lib/python3.5/site-packages/jinja2/compiler.py in visit_Macro(self, node, frame)
   1179 
   1180     def visit_Macro(self, node, frame):
-> 1181         macro_frame = self.macro_body(node, frame)
   1182         self.newline()
   1183         if frame.toplevel:

~/anaconda3_420/lib/python3.5/site-packages/jinja2/compiler.py in macro_body(self, node, frame, children)
    728         self.buffer(frame)
    729         self.pull_locals(frame)
--> 730         self.blockvisit(node.body, frame)
    731         self.return_buffer_contents(frame)
    732         self.outdent()

~/anaconda3_420/lib/python3.5/site-packages/jinja2/compiler.py in blockvisit(self, nodes, frame)
    490         try:
    491             for node in nodes:
--> 492                 self.visit(node, frame)
    493         except CompilerExit:
    494             pass

~/anaconda3_420/lib/python3.5/site-packages/jinja2/visitor.py in visit(self, node, *args, **kwargs)
     36         f = self.get_visitor(node)
     37         if f is not None:
---> 38             return f(node, *args, **kwargs)
     39         return self.generic_visit(node, *args, **kwargs)
     40 

~/anaconda3_420/lib/python3.5/site-packages/jinja2/compiler.py in visit_Output(self, node, frame)
   1307                             self.write('context, ')
   1308                         close += 1
-> 1309                     self.visit(item, frame)
   1310                     self.write(')' * close)
   1311                     if frame.buffer is not None:

~/anaconda3_420/lib/python3.5/site-packages/jinja2/visitor.py in visit(self, node, *args, **kwargs)
     36         f = self.get_visitor(node)
     37         if f is not None:
---> 38             return f(node, *args, **kwargs)
     39         return self.generic_visit(node, *args, **kwargs)
     40 

~/anaconda3_420/lib/python3.5/site-packages/jinja2/compiler.py in visit_Filter(self, node, frame)
   1574         # and want to write to the current buffer
   1575         if node.node is not None:
-> 1576             self.visit(node.node, frame)
   1577         elif frame.eval_ctx.volatile:
   1578             self.write('(context.eval_ctx.autoescape and'

~/anaconda3_420/lib/python3.5/site-packages/jinja2/visitor.py in visit(self, node, *args, **kwargs)
     36         f = self.get_visitor(node)
     37         if f is not None:
---> 38             return f(node, *args, **kwargs)
     39         return self.generic_visit(node, *args, **kwargs)
     40 

~/anaconda3_420/lib/python3.5/site-packages/jinja2/compiler.py in visit_Filter(self, node, frame)
   1563         func = self.environment.filters.get(node.name)
   1564         if func is None:
-> 1565             self.fail('no filter named %r' % node.name, node.lineno)
   1566         if getattr(func, 'contextfilter', False):
   1567             self.write('context, ')

~/anaconda3_420/lib/python3.5/site-packages/jinja2/compiler.py in fail(self, msg, lineno)
    425     def fail(self, msg, lineno):
    426         """Fail with a :exc:`TemplateAssertionError`."""
--> 427         raise TemplateAssertionError(msg, lineno, self.name, self.filename)
    428 
    429     def temporary_identifier(self):

TemplateAssertionError: no filter named 'tojson'

**Comment by Conengmo** [comment]
Hi @nonoumasy, thanks for your bug report. 

Can you tell which folium version you are using? `print(folium.__version__)`

And which version of Jinja2?

```
import jinja2
print(jinja2.__version__)
```

We recently started using Jinja2's `tojson` filter, which requires jinja2 v2.9 or higher.

**Comment by Conengmo** [comment]
I updated the Jinja2 requirement in PR #1122.

**Comment by nonoumasy** [comment]
I believe it was the most updated version since I did a pip install from
the Azure notebook.
I decided to stay away from Azure notebooks for misc reasons so this is not
an issue with me.
thanks

**Comment by Conengmo** [comment]
Alright, I’ll close the issue then. If someone else has the same problem please let us know what version of Python, folium and Jinja2 you are using.
