### ISSUE TITLE
`IndexError` in Choropleth when providing `bins` as a sequence.

### ISSUE THREAD

**Issue by sjagter** [python-visualization/folium#1130]
Firstly, thanks to the contributors for this great package, it makes it really easy to make pretty awesome looking maps.

#### Please add a code sample or a nbviewer link, copy-pastable if possible

Sample code to generate error:

```python
    column_name = 'example_column_name'
    bin_intervals = [0,10,20,30,40,50,100]
    folium.Choropleth(
        geo_data=gdf,
        name=f'{column_name} Choropleth',
        data=data,
        columns=['id', column_name],
        key_on='feature.properties.id',
        bins=bin_intervals,
        fill_color='YlOrRd',
        fill_opacity=0.7,
        line_opacity=0.2,
        legend_name=f'{column_name} (%)',
        show=True
    ).add_to(m)
```
#### Problem description

I am getting an `IndexError` when drawing a Choropleth using a `bins` parameter as a  sequence.

Sample of the stacktrace from code quoted above:

```python
.../folium/features.py in color_scale_fun(x)
   1007
   1008                 color_idx = np.digitize(value_of_x, bin_edges, right=False) - 1
-> 1009                 return color_range[color_idx], fill_opacity
   1010
   1011         else:

IndexError: list index out of range
```

Drawing a choropleth with a provided sequence for bins is expected to work and not result in an error.

#### Expected Output

A correctly drawn map with choropleth according to the given `bins` parameter is expected.

#### Output of ``folium.__version__``

I was using the latest release 0.8.3, I cannot check this now as I am using my own edited version of the 0.8.0 branch where I "fixed" the issue.

#### Custom fix

I was able to get a correctly drawn map with `bins` working as expected by cloning branch v.0.8.0 and changing line 1073 in `folium/features.py`:

```python
            nb_bins = len(bin_edges) - 1
```
to
```python
            nb_bins = len(bin_edges)
```

Doing the same on the `master` branch made my layer selection button disappear.

I didn't have the time to check if this will break anything else, and hence would not want to create a PR with this change :)

**Comment by sjagter** [comment]
An additional hack to improve my "fix" above that allows both `int` and sequence type of bins to be specified...
```python
            if (type(bins)==int) or (type(bins)==str):
                nb_bins = len(bin_edges) - 1
            else:
                nb_bins = len(bin_edges)
```

**Comment by Conengmo** [comment]
I'm a bit surprised by this error. It seems incorrect to have the number of bins be equal to the number of bin edges.

Could you maybe share a working example that will produce this error, including some data?

**Comment by sjagter** [comment]
Hi, thanks for responding. I figured out the problem, but I don't know enough about the underlying code to know why it's breaking. It is a combination of using integer valued bin intervals, and having a choropleth maximum equal to the maximum of the bin intervals.

To repoduce, altering code from [here](https://python-visualization.github.io/folium/quickstart.html#Choropleth-maps):

```python
import folium
import pandas as pd

url = 'https://raw.githubusercontent.com/python-visualization/folium/master/examples/data'
state_geo = f'{url}/us-states.json'
state_unemployment = f'{url}/US_Unemployment_Oct2012.csv'
state_data = pd.read_csv(state_unemployment)

# Using integers to define bins
bins = [0, 1, 2, 3, 4, 6, 12]
# Setting one of the values to the max of the bin
state_data['Unemployment'].iloc[20] = 12.0

m = folium.Map(location=[48, -102], zoom_start=3)

folium.Choropleth(
    geo_data=state_geo,
    data=state_data,
    columns=['State', 'Unemployment'],
    key_on='feature.id',
    fill_color='BuPu',
    fill_opacity=0.7,
    line_opacity=0.5,
    legend_name='Unemployment Rate (%)',
    bins=bins,
    reset=True
).add_to(m)

m
```
This gives an error: `IndexError: list index out of range`

In order to prevent the error, I figured out that converting bins to `float` fixes things:

```python
m = folium.Map(location=[48, -102], zoom_start=3)

folium.Choropleth(
    geo_data=state_geo,
    data=state_data,
    columns=['State', 'Unemployment'],
    key_on='feature.id',
    fill_color='BuPu',
    fill_opacity=0.7,
    line_opacity=0.5,
    legend_name='Unemployment Rate (%)',
    bins=[float(x) for x in bins],
    reset=True
).add_to(m)

m
```

**Comment by Conengmo** [comment]
Thanks, this looks like it should be enough to reproduce the error. It looks like we're not doing something right with ints and floats, as you said. Later I'll look into our code to see what we should fix, or if someone else wants to work in this that's also welcome!

**Comment by sjagter** [comment]
Pleasure, hope it helps! Fortunately it's very easy to work around this on the user side.

**Comment by LeonardoFurtado** [comment]
I will try fix it.

**Comment by muneeb699** [comment]
I have the same bug while working with Choropleth. And I am able to solve by this https://github.com/python-visualization/folium/issues/1130#issuecomment-504949715
