### ISSUE TITLE
Problem with Folium search plugin (Data=marker_cluster)

### ISSUE THREAD

**Issue by 18495** [python-visualization/folium#1132]
I get a couple of stuck when i use folium.plugins.Search(marker_cluster) ,the first one search bar is not respond when i try to searching the second customicon png and default marker appear at the same place.
![Screenshot](https://user-images.githubusercontent.com/24371617/56736649-6087f900-6771-11e9-8d94-4676a40c3136.png)
how can i get rid off these  default marker?.
thanks!.
```
 import folium
 from folium import plugins
 from folium.plugins import Search

points = {
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"properties": {
"name": "one",
'icons': 'C:\\Users\\avion\\Desktop\\pandas\\my project\\factory.png'
},
"geometry": {
"type": "Point",
"coordinates": [-71.0636, 42.3581]
}
},
{
"type": "Feature",
"properties": {
"name": "two",
'icons': 'C:\\Users\\avion\\Desktop\\pandas\\my project\\factory.png'
},
"geometry": {
"type": "Point",
"coordinates": [-74.78991444, 42.82995815]
}
},
{
"type": "Feature",
"properties": {
"name": "three",
'icons': 'C:\\Users\\avion\\Desktop\\pandas\\my project\\factory.png'
},
"geometry": {
"type": "Point",
"coordinates": [-78.56603306, 39.17929819]
}
}
]
}

m = folium.Map(
location=[42.82995815, -74.78991444],
tiles = 'cartodbpositron',
zoom_start=1
)

style_one = lambda x: {'fillColor': 'green'}
marker_cluster = folium.plugins.MarkerCluster(name = 'site location').add_to(m)
for feature in points['features']:
    lon, lat = feature['geometry']['coordinates']
    icon = feature['properties']['icons']
    name = feature['properties']['name']
    icon = folium.CustomIcon(icon_image = icon,
                                 icon_size = (30,35),
                                 icon_anchor = (0,0))
    marker =folium.Marker(location = [lat, lon] ,popup =(folium.Popup(str(name))), 
                                   tooltip = "<strong>"+str(name)+"</strong>",
                                     icon = icon).add_to(marker_cluster)
geojson_obj = folium.GeoJson(points, style_function=style_one).add_to(marker_cluster)
statesearch = Search(layer=marker_cluster,
                     geom_type='Point',
                     placeholder="Search",
                     collapsed=True,
                     search_label='name',
                     search_zoom=14,
                     position='topright'
                    ).add_to(m)

m.save('example.html')
```

**Comment by Conengmo** [comment]
I don't really understand your issue. Looking at your code, it seems you're adding a `GeoJson` object to a `MarkerCluster`, that seems weird to me. I don't suppose that's how it's intended. Please check out our example notebooks and take it from there.

These issues are meant for tracking bugs and new functionalities, if you need more help debugging your code than Stackoverflow is probably a better channel.

**Comment by 18495** [comment]
So how can i search using featuregroup or markercluster other than GeoJson 
in the plugins.Serach?

**Comment by LouisManiere** [comment]
Dear 18495,
I am also interessed if someone know the method to use the search plugin with featuregroup or markercluster. It works perfectly with GeoJson data but not with featuregroup or markercluster with the same code. I don't have any error message, I have the search box on the map but it couldn't find any place. The box searching without finding anything. This is the only post I could find about that subject, since the 3 May, maybe someone have found a solution.

**Comment by diegoquintanav** [comment]
Probably because it's not implemented

https://github.com/python-visualization/folium/blob/60ae79cd1f4f16fc48e206947c7cef870ea28b8e/folium/plugins/search.py#L120

**Comment by lindsaymorgan** [comment]
so it is fixed? I still can't search from markcluster yet.
