### ISSUE TITLE
Extend the ability to provide custom color table in geo_json()

### ISSUE THREAD

**Issue by achourasia** [python-visualization/folium#114]
The geo_json() method only provides fixed number of color maps and upto six threshold values.
This imposes severe limitation when a custom color mapping is desired. Conceivably one could pass pass a custom color table or lookup table as a tuple for example. 

Perhaps add an argument colormap = list of value, red, green, blue, opacity tuples
An option to interpolate colors will be awesome, as currently that is missing as well.

```
# Lookup table with (Value, Red, Green, Blue) tuples 
lookup = [ (-0.5, 255, 0 , 0),
                 (0.0, 0, 255 , 0),
                 (0.5, 0, 0 , 255),
               ]
````

Even better would an ability to also provide transparency, although this may require too much work
```
# Lookup table with (Value, Red, Green, Blue, Opacity) tuples 
lookup = [ (-0.5, 255, 0 , 0, 128),
                 (0.0, 0, 255 , 0, 255),
                 (0.5, 0, 0 , 255, 192),
               ]
```

**Comment by ocefpaf** [comment]
Duplication of #89
