### ISSUE TITLE
Please put all the data used in the examples online

### ISSUE THREAD

**Issue by KellyPared** [python-visualization/folium#1143]
I am using Colab for some students, and we cannot access these files.
![image](https://user-images.githubusercontent.com/40581033/57184941-4c3ead00-6e91-11e9-892d-dabee8c5778e.png)

**Comment by ocefpaf** [comment]
I assigned myself to re-write those exemples pulling the data from the internet instead of relying on local files. I'll work on this during the rest of the sprints.

Thanks for the issue @KellyPared!

**Comment by ocefpaf** [comment]
Done in #1152! There was only one example that must ready from disc b/c it is actually about reading from disc :smile: Everything else should work now without the need for local data.
