### ISSUE TITLE
Feedback for Tutorial

### ISSUE THREAD

**Issue by bbeyer** [python-visualization/folium#1145]
Things to be Added to `folium` quickstart/tutorial:

- Seems like you need to get the location data from somewhere other than the map that is on the screen zoomed in.  Is this true?  If so, it might be helpful to give instructions on how to get the data from Google maps.

- It looks like all the iterations could be done within the initial cell to end with a final product.  It seems it could be helpful to explain the process of inserting a cell below to create separate examples that follow along with the tutorial.

- Click Control-Enter (after the m instance) is also something that I needed to know to have my map appear.

- Some exercises that may help a newbie:
  - How to change the image with the different types of maps available - seems there are different kinds available in folium
  - You wrote "The default tiles are set to OpenStreetMap, but Stamen Terrain, Stamen Toner, Mapbox Bright*, and Mapbox Control Room, and many others tiles are built in."
  - No image showed for Mapbox Bright - (turns out not all levels available)
  - No image showed for Mapbox Control Room
  - How to zoom in on the image with the different numbers.  For me, 16 was a better zoom that we had discovered during the Education Summit.  I tried it and my maps are zoomed in appropriately.  This may be obvious to a more experienced user or discovered by simply thinking about the zoom level command.
  - What colors are available for the list of markers and what other icons are available to put within the icon such as cloud and info sign?

**Comment by ocefpaf** [comment]
> Things to be Added to `folium` quickstart/tutorial:
> 
> * Seems like you need to get the location data from somewhere other than the map that is on the screen zoomed in.  Is this true?  If so, it might be helpful to give instructions on how to get the data from Google maps.

Most of the time the user knows the location of interested. When that is not true we have a convenience method [LatLngPopup](https://python-visualization.github.io/folium/modules.html#folium.features.LatLngPopup). We should an example on how to use that in the quickstart.

> * It looks like all the iterations could be done within the initial cell to end with a final product.  It seems it could be helpful to explain the process of inserting a cell below to create separate examples that follow along with the tutorial.
> * Click Control-Enter (after the m instance) is also something that I needed to know to have my map appear.

We will defer to a Jupyter tutorial for those two points to avoid bloating folium's documentation.

> * Some exercises that may help a newbie:
>   
>   * How to change the image with the different types of maps available - seems there are different kinds available in folium
>   * You wrote "The default tiles are set to OpenStreetMap, but Stamen Terrain, Stamen Toner, Mapbox Bright*, and Mapbox Control Room, and many others tiles are built in."

The quickstart "kind of covers" how to change the basemap but [this example](https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/TilesExample.ipynb) from the gallery has more examples.

>   * No image showed for Mapbox Bright - (turns out not all levels available)
>   * No image showed for Mapbox Control Room

Those two are not available on all levels and it fails silently. I thought about adding an error check for them but the available levels may change with time. This behavior is document in the docstring and I'll add a note to the quickstart too. 

>   * How to zoom in on the image with the different numbers.  For me, 16 was a better zoom that we had discovered during the Education Summit.  I tried it and my maps are zoomed in appropriately.  This may be obvious to a more experienced user or discovered by simply thinking about the zoom level command.

There is no obvious way actually. One must experiment with zoom levels for different maps/apps and that will vary depending on what one wants to show.

>   * What colors are available for the list of markers and what other icons are available to put within the icon such as cloud and info sign?

The docs on markers is lacking, sorry. I'll fix the quickstart first and then I'll add more on the markers.
