### ISSUE TITLE
Folium Heatmap doesn't load properly

### ISSUE THREAD

**Issue by failmetwice** [python-visualization/folium#1146]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Rendering map 

def infection_heatmap(dic, regions_trans, map_name):
    '''Init Visuals'''
    [...]
    regions, fol_map = init_render(dic, regions_trans)

    #render regions
    for k in regions:
        location = regions[k]["localisation"]
        
        circle_size += [...] #float 
        prc_infected = [...] #float [0,1]

        point = [ [location[0], location[1], prc_infected * 5000] ]
        HeatMap(    data= point,
                    radius= circle_size 
                ).add_to(fol_map)

    fol_map.save(map_name)
    print("Infection map generated")

```
#### Problem description

When i open the map to take a screenshot. For some points It add a 'semi-dot' that looks to start from the upper left  corner of the tile.

How can i delete the 'semi-dot'

#### Output with heatmap

![screen-2006-1-inf](https://user-images.githubusercontent.com/50375047/57316639-89f03f80-70f6-11e9-9ce6-ec363da56e16.png)

![screen-2007-1-inf](https://user-images.githubusercontent.com/50375047/57316668-9aa0b580-70f6-11e9-97b2-6e7a9d7b7c15.png)

**Comment by Conengmo** [comment]
I don't really know what's going on here. Without data it's hard to say. I'm closing the issue because it's quite stale. If you still need help with this please provide a fully functioning code snippet, include a data sample so we can run it.
