### ISSUE TITLE
Upgrade to Leaflet 1.5.0

### ISSUE THREAD

**Issue by Conengmo** [python-visualization/folium#1147]
Leaflet 1.5.0 just got released: https://github.com/Leaflet/Leaflet/releases/tag/v1.5.0

Looking at the release notes it seems there are no breaking changes.

We can update:

- our links to the Leaflet resources
- our links to the Leaflet documentation

Let's wait, I don't know, two weeks before merging this to see if any hot fix releases are done.

**Comment by YangDawu** [comment]
does folium still use the old tag? does it make a difference?
