### ISSUE TITLE
Syntax error when trying to create a map with different cluster criteria using folium

### ISSUE THREAD

**Issue by barbaramchd** [python-visualization/folium#1159]
Hi,
I am just a beginner in Python and appreciate any help.

I am trying to create a map using folium. This map needs to have clusters that follow a different criteria than only distance.
Per example, suppose I have the U.S. map and I am analyzing this map by "country_level= 1", "state_level=2", and "city_level=3". Points in a different state or city should not cluster (i.g.: points from New York should not cluster with points from New Jersey when analyzing in a "state_level".

This is what I've done so far, however I have an error and I think that even if it works, it won't have the expected output:

import pandas as pd
import folium
from folium.features import CustomIcon
from folium.plugins import MarkerCluster

df = pd.read_csv(r'Pakistan.csv')
data = df[['Latitude', 'Longitude']].values.tolist()

x = list(df['Latitude'])
y = list(df['Longitude'])
ID = list(df['S'])

latmean = df['Latitude'].mean()
lonmean = df['Longitude'].mean()

tooltip = 'Click me!'

cluster = MarkerCluster().add_to(m)
#for Latitude, Longitude, S in zip(df['Latitude'], df['Longitude'], df['S']):
    #folium.Marker(location=[Latitude[S], [Longitude[S]].add_to(cluster)
def zoom_level (identification):
    if ID in range (1, 4):
        col = 'blue'
        max_zoom = 15
    elif ID in range (5, 8):
        col = 'red'
        min_zoom = 16
        max_zoom = 17
    else:
        col = 'green'
        min_zoom = 18
        max_zoom = 20
        
for lt, ln, el in zip(x, y, ID):
    folium.Marker(location=[x, y], popup=('<strong>Location str(ID)<strong>'), icon=folium.Icon(color=color(ID), icon='cloud').add_to(cluster)

#m.add_child(folium.LatLngPopup())
folium.LayerControl(collapsed=False).add_to(m)
m.save('map2.html')
```
ERROR:

  File "<ipython-input-9-9410e2673f2e>", line 26
    folium.LayerControl().add_to(m)
         ^
SyntaxError: invalid syntax

**Comment by ocefpaf** [comment]
The is an unbalanced `(` in your code. Closing this b/c it is not an issue with `folium`. You can get python help in StackOverflow or other python tutorial sites. Please use the `folium` issue tracker to issue in the code base.
