### ISSUE TITLE
Mapbox tiles down?

### ISSUE THREAD

**Issue by BrendanMoore42** [python-visualization/folium#1160]
Heatmaps generated with Mapbox tiles have stopped working this week--they're even down at https://python-graph-gallery.com/288-map-background-with-folium/. Any ideas on when they will be available again?

**Comment by ocefpaf** [comment]
No idea. You should raise that upstream with mapbox. In folium we are considering to removing the built-in tiles that require an API, like mapbox, and letting the user configure that with the URL instead. Closing this b/c it is not a problem with folium.

**Comment by Conengmo** [comment]
We use the v3 version of the API, which has been deprecated since 2015. Relevant issue here: https://github.com/python-visualization/folium/issues/922

**Comment by ocefpaf** [comment]
IMO we should just drop it. It is easy enough for the end user to use it and maintaining the "shortcut" can be cumbersome.

**Comment by Conengmo** [comment]
Agreed. I would like to simplify the current setup with all the files into a single list of a selection of free tile servers.

Relevant related issue: https://github.com/python-visualization/folium/issues/993
