### ISSUE TITLE
basemap doesn't appear when changing default crs to EPSG4326

### ISSUE THREAD

**Issue by KarenChen9999** [python-visualization/folium#1161]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here
# default crs
m = folium.Map(location=[45.5236, -122.6750],  tiles='OpenStreetMap')
m
# change default crs to EPSG4326
m = folium.Map(location=[45.5236, -122.6750], crs='EPSG4326', tiles='OpenStreetMap')
m
```
#### Problem description
the base map is quite different to default after changing crs to EPSG4326. Can anyone explain why? Also if i need to use EPSG4326, how can i still get the correct base map.
[this should explain **why** the current behavior is a problem and what is the expected output.]

**Comment by Conengmo** [comment]
I don't know much about CRS, but what I understood is you need to match the CRS value with the tiles you are using. The OpenStreetMap tiles use our default CRS, EPSG3857, so if you change that obviously things will look bad or won't work (I haven't tried it though). The `crs` option is to be used when you have a tileset that needs a different CRS. So when you say you need to use EPS4326, do you mean you have a tileset that needs that?

Anyway, this is not something to change in folium so I'm closing this issue. Feel free to add more to it. We can always reopen if there is something that needs to be fixed or enhanced.

**Comment by KarenChen9999** [comment]
Hello,

I need to plot tiff(raster) square grids. When I use default CRS, my grids turn out to be not in the right position. It works fine when i change the default CRS to EPSG4326. But then i lose the basemap.

What is the work around solution if I need to plot square grids in raster format and still be able to plot base map?

Thanks and regards,

Karen



________________________________

**Comment by GuodongZhu** [comment]
I have similar issue. When I changed to EPSG4326, I still have basemap, but the basemap is obvious wrong. The circle I drew around Dallas, TX now appear in the Atlantic ocean
