### ISSUE TITLE
Assign a Minimum and Maximum Extrema to Heatmapwithtime

### ISSUE THREAD

**Issue by jzimmm** [python-visualization/folium#1164]
I'm currently using folium to create a heatmap using the heatmapwithtime plugin to show the changes over time. However I would like to change the global max and min values for the heat layer. The regular heatmap plugin allows you change the max value but you can't change anything with heatmapwithtime. Is there a way to get around this?

**Comment by gabrielmpp** [comment]
What I do on my project is scale the data, adjust the gradient intervals and change the colorbar values accordingly. It is quite a work around, but I could get a nice result:
![image](https://user-images.githubusercontent.com/25806757/59570218-a041d180-908c-11e9-8f76-523b465ea121.png)

**Comment by jzimmm** [comment]
Can you explain how you do this with a little more specificity please? I'm not quite sure what you mean.

**Comment by Conengmo** [comment]
folium is maintained by volunteers, so feel free to open a PR with a patch. Not sure what you want exactly, and if it's possible, but you can have a look at the source code, and the underlying JS library we use:

https://github.com/python-visualization/folium/blob/master/folium/plugins/heat_map_withtime.py

**Comment by jzimmm** [comment]
@gabrielmpp Hello you did not respond to me the first time. Could you please explain how you were able to create the color bar?

**Comment by gabrielmpp** [comment]
I just assigned the colobar HTML to a variable 'colorbar' and used Template and MacroElement from branca.element to create a macro and insert that in the folium map. I may be able to upload a sample of the HTML if you want.  See if the following lines work with a simple HTML colorbar:
```
    macro = MacroElement()
    macro._template = Template(colorbar)
    map.get_root().add_child(macro)
```

**Comment by jzimmm** [comment]
@gabrielmpp Thank you for the response! I understand how to create the color bar. What I'm saying is that if you zoom in and out on the heatmap the heat colors change. Even if you set uselocalextrema to False. If you could explain how you accounted for that as well as how you were able to tell what colors represented what values on the map. Currently I have no clue how to tell what the threshold is between a red value and an orange value for instance. All I know is that reds gradient is set to o.9, and orange is is set to 0.7. That doesn't tell me much about the actual data value for that color.

**Comment by gabrielmpp** [comment]
Use `scale_radius=True` in `plugins.HeatMapWithTime` so that the heat colors won't change as you zoom in and out. Then, by knowing max and min of your dataset, you can associate the gradient fractions (0.1, 0.8...) to values in your legend.

**Comment by jzimmm** [comment]
@gabrielmpp Your a legend bro. Thanks a lot for the help! My research project should go much smoother now

**Comment by dustcenter** [comment]
> What I do on my project is scale the data, adjust the gradient intervals and change the colorbar values accordingly. It is quite a work around, but I could get a nice result: ![image](https://user-images.githubusercontent.com/25806757/59570218-a041d180-908c-11e9-8f76-523b465ea121.png)

Hello. I try to plot some data on folium Heatmapwithtime and I need to changing Weight exceed 1 like your map. can you help me?

> I'm currently using folium to create a heatmap using the heatmapwithtime plugin to show the changes over time. However I would like to change the global max and min values for the heat layer. The regular heatmap plugin allows you change the max value but you can't change anything with heatmapwithtime. Is there a way to get around this?

Hello. I try to plot some data on folium Heatmapwithtime and I need to changing Weight exceed 1 . can you help me?

**Comment by Conengmo** [comment]
Looks like the original issue was solved thanks to @gabrielmpp, so I'll close this one.
