### ISSUE TITLE
Online map

### ISSUE THREAD

**Issue by VyacheslavBabenko** [python-visualization/folium#1165]
Hello. I have a problem: I want to use follium to make my flightradar, this is a task from the university. How can I constantly take information from api from flightradar without reloading the map? Maybe you need to use ajax somehow, I don't know, please help.

**Comment by Conengmo** [comment]
Hi Vyacheslav,

Unfortunately we lack the resources to help you with your homework. I hope you understand. I can tell you that folium doesn't really have anything to do ajax calls, you would have to go work on the underlying Javascript code to make that work. Maybe at some point it makes more sense to use Leaflet natively.

To get you started check out this Flask example: https://github.com/python-visualization/folium/blob/master/examples/flask_example.py

Maybe you can stop using folium once you have a working HTML file with Leaflet code, and add a Leaflet AJAX plugin yourself.

That's it, good luck!
