### ISSUE TITLE
Mapbox Bright and Mapbox Control Room shows blank or not appearing

### ISSUE THREAD

**Issue by 47nikhil** [python-visualization/folium#1177]
import folium
m = folium.Map(location=[-59.1759, -11.6016],tiles='Mapbox Bright',zoom_start=2)
m.save("E:\Project python\Maping\Try1.html")

The above code I tried doesn't work. The output I get is blank screen just zoom in/out option. nothing else. Tried all zoom level and browser but doesn't work. I am not able to see output posted online. rest of the map work fine.
if you have solution then please post.
or
Is their any alternative to Mapbox Bright.

![try](https://user-images.githubusercontent.com/52858158/61179800-b3ae7100-a627-11e9-90fd-33474df80999.JPG)
![try2](https://user-images.githubusercontent.com/52858158/61179801-b3ae7100-a627-11e9-94be-6becb5432279.JPG)
![try3](https://user-images.githubusercontent.com/52858158/61179802-b3ae7100-a627-11e9-96ac-5c4b325321a0.JPG)

**Comment by Conengmo** [comment]
I'm not sure the Mapbox tiles are supposed to still work. See https://github.com/python-visualization/folium/issues/922

For a list of available tilesets see https://leaflet-extras.github.io/leaflet-providers/preview/

I think we'll do some work on the way we handle tiles now, and deprecate the non-public tile providers that are currently broken, such as Mapbox. It'll be easy for users to provide those URL's themselves if they want to use them. The linked issue has an example on that.

**Comment by 47nikhil** [comment]
Thanks for clearing doubts.

**Comment by juanlet** [comment]
I had the same problem. Thanks for clarifying

**Comment by superdalton** [comment]
wow. Thank God I found this after 30 mins. I had the same problem . This ironed it out.

**Comment by aleangel** [comment]
Same problem. Thanks for the answers. Solved now.

**Comment by CriticalWill** [comment]
@juanlet , @superdalton , @aleangel 
I ran across this post and wanted to relay I've been using Maptiler (free) that offers a much larger range of tile sets and gives fairly detailed guidance on using your chosen tile set in your code. 
Best of luck!

**Comment by aleangel** [comment]
Thanks for your kind help. 
Regards

إسكندر الملاك

Le 1 mai 2020 à 10:06, CriticalWill <notifications@github.com> a écrit :






@juanlet , @superdalton , @aleangel
I ran across this post and wanted to relay I've been using Maptiler (free) that offers a much larger range of tile sets and gives fairly detailed guidance on using your chosen tile set in your code.
Best of luck!

**Comment by UjuAyoku** [comment]
A token is now required to create Mapbox Bright.

1. Go to https://account.mapbox.com/ and create a free account with an email address (for verification) 
2. After verification, login and copy the 'Default public token' on the first page

# insert the token 
world_map = folium.Map(tiles='https://api.mapbox.com/styles/v1/mapbox/light-v10/tiles/{z}/{x}/{y}?access_token=INSERT TOKEN HERE, attr='Mapbox Bright')

# code should look like below:
world_map = folium.Map(tiles='https://api.mapbox.com/styles/v1/mapbox/light-v10/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoieWVsbG93dHdpb.....................P9btqwA', attr='Mapbox Bright') 

# display the map
world_map

**Comment by UjuAyoku** [comment]
A token is now required to create Mapbox Bright.

Go to https://account.mapbox.com/ and create a free account with an email address (for verification)

After verification, login and copy the 'Default public token' on the first page

Insert the token
world_map = folium.Map(tiles='https://api.mapbox.com/styles/v1/mapbox/light-v10/tiles/{z}/{x}/{y}?access_token=INSERT_TOKEN_HERE, attr='Mapbox Bright')

Code should look like below:
world_map = folium.Map(tiles='https://api.mapbox.com/styles/v1/mapbox/light-v10/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoieWVsbG93dHdpb.....................P9btqwA', attr='Mapbox Bright')

Display the map
world_map

**Comment by UjuAyoku** [comment]
A token is now required to use Mapbox Bright.

Go to https://account.mapbox.com/ and create a free account with an email address (for verification)

After verification, login and copy the 'Default public token' on the first page

Insert the token
world_map = folium.Map(tiles='https://api.mapbox.com/styles/v1/mapbox/light-v10/tiles/{z}/{x}/{y}?access_token=INSERT_TOKEN_HERE, attr='Mapbox Bright')

Code should look like below:
world_map = folium.Map(tiles='https://api.mapbox.com/styles/v1/mapbox/light-v10/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoieWVsbG93dHdpb.....................P9btqwA', attr='Mapbox Bright')

Display the map
world_map
