### ISSUE TITLE
How add click-for-marker with iframe?

### ISSUE THREAD

**Issue by piotrpiotr1** [python-visualization/folium#1183]
Question:

How to add click-for-marker functionality with iframe popup? I want add new point with iframe or html popup inside the popup. ClickForMarker has only string parametr.

https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Quickstart.ipynb

And  https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Popups.ipynb

**Comment by piotrpiotr1** [comment]
Guys?

**Comment by ocefpaf** [comment]
> Guys?

And Gals!

`ClickForMarker` takes a `popup` argument. Did you try to create your `iframe` and pass it to ClickForMarker like `folium.ClickForMarker(popup=iframe)`?

**Comment by piotrpiotr1** [comment]
_TypeError: sequence item 1: expected str instance, IFrame found_ 

or 
popup = html also not working (nothing happend)

**Comment by ocefpaf** [comment]
> So, I can only put string into popup.

See cell number [9]:

https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Popups.ipynb

The fix for `ClickForMarker` would be simple.
Just remove the strong concatenation in `self.popup = ''.join(['"', popup, '"'])`.

**Comment by piotrpiotr1** [comment]
@ocefpaf where to remove?
