### ISSUE TITLE
CSS loaded via HTTP in heat_map_withtime.py not available with Jupyter served on HTTPS

### ISSUE THREAD

**Issue by sradomski** [python-visualization/folium#1192]
The CSS file `http://apps.socib.es/Leaflet.TimeDimension/dist/leaflet.timedimension.control.min.css` loaded in line 178 from `heat_map_withtime.py` is a hard-coded HTTP URL, which will not be loaded when Folium is embedded in a Jupyter Notebook served via HTTPS:

E.g. Chrome will complain:
<code>
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure stylesheet '<URL>'. This request has been blocked; the content must be served over HTTPS.
</code>

**Comment by Conengmo** [comment]
Thanks for the report. Is the fix simply changing that URL to https? Do you want to make a PR and check that it fixes your problem?

**Comment by sradomski** [comment]
An url of `         https://cdn.rawgit.com/socib/Leaflet.TimeDimension/master/dist/leaflet.timedimension.control.min.css` will work fine.

**Comment by Conengmo** [comment]
Good one, that'll work. Since rawgit.com is deprecated though we switched to https://rawcdn.githack.com.

**Comment by Conengmo** [comment]
This has been resolved, the resource now comes from a https url.
