### ISSUE TITLE
Archiving documents containing folium maps

### ISSUE THREAD

**Issue by 1kastner** [python-visualization/folium#1196]
#### Problem description

I need to archive a Jupyter Notebook containing folium maps. Because technology changes and map tiles might move in 10 or 20 years, I would need to somehow save all the content into one file, which could be either XML, PDF or TIFF (or a mix of these). And I need to do this on a large scale, that means it should be some kind of batch processing doing the job.

#### Solution found so far

Some browsers allow headless printing, but the folium maps can easily be distorted and messed up inside Jupyter Notebooks. Furthermore, some map tiles are not fully loaded at the time of printing.

#### Question

Has anybody encountered a similar question? How can this be solved? I do not want to change the source code of the HTML/CSS/JS on my side as this might not be a stable and reliable solution.

#### Further sources
I tried to find answers at:

-  https://superuser.com/questions/1463819/print-fully-loaded-website-as-pdf-with-chrome-in-headless-mode
-  https://bugs.chromium.org/p/chromium/issues/detail?id=986740#c3

but there has been no good answer so far.

**Comment by 1kastner** [comment]
As this is partly an issue of Leaflet.js, one issue has been created at https://github.com/Leaflet/Leaflet/issues/6751 -- anyhow the question at hand is bigger than only the distortion of the PDF here.

**Comment by ocefpaf** [comment]
Leaflet tile maps are supposed to be dynamic and "archiving" them is not an easy task. `folium` has an [experimental method](https://github.com/python-visualization/folium/blob/60ae79cd1f4f16fc48e206947c7cef870ea28b8e/folium/folium.py#L296-L324) to save a `png` image. Any PRs to improve that functionality are welcomed.  Closing this b/c it s beyond the scope of `folium`.

**Comment by 1kastner** [comment]
@ocefpaf do you have an idea of how it can be improved? Or where the issue is located?

**Comment by ocefpaf** [comment]
> @ocefpaf do you have an idea of how it can be improved?

I was hoping that you, as someone requesting this feature, would tell us :smile: 

> Or where the issue is located?

There are no open issues. Please test that feature and open one with your feedback.

**Comment by 1kastner** [comment]
Thanks a lot for your input

**Comment by 1kastner** [comment]
Btw, for Chrome the result is pretty much the same, see [example_folium_archiving_chrome.pdf](https://github.com/python-visualization/folium/files/3492123/example_folium_archiving_chrome.pdf)
