### ISSUE TITLE
Content Encoding

### ISSUE THREAD

**Issue by sbreuss** [python-visualization/folium#12]
I'm using the library but encountered some problems with german umlauts. Could you please add a the encoding to the head section of the html templates to fix character encoding issues?

<code>&lt;meta http-equiv="content-type" content="text/html; charset=UTF-8" /&gt;</code>

Best Regards,
Simon Breuss

**Comment by deveshdatwani** [comment]
I know it has been a long time, but I am facing the same issue. I too cannot display foreign languages on my maps. The templates folder doesn't containt fol_template.html anymore. Can anyone help me out?

**Comment by Conengmo** [comment]
@deveshdatwani could you please open a new issue? Please include a data sample and a code snippet that we can run that reproduces your issue. If you open a new issue it will show you what other information to include as well.

**Comment by deveshdatwani** [comment]
He @Conengmo , sorry for getting back so late. I solved the issue. Turned out, the issue was in the Branca library. Do you want me to share my code?

**Comment by Conengmo** [comment]
If you’d like, please 😀 either here, or maybe better in a new issue or PR in the branca repo

**Comment by mjalalimanesh** [comment]
> I know it has been a long time, but I am facing the same issue. I too cannot display foreign languages on my maps. The templates folder doesn't containt fol_template.html anymore. Can anyone help me out?

 Hey @deveshdatwani How did you solve this problem? I'm having an issue with displaying foreign languages on my maps as a popup

**Comment by Conengmo** [comment]
@mjalalimanesh are you using Jupyter notebooks? Please install branca from its git master branch, that should hopefully solve your issue. We’re preparing to do a release as well, so future readers probably only have to upgrade their branca version with pip.

**Comment by deveshdatwani** [comment]
@mjalalimanesh I'll post the solution in an hour or so. I had to tweak branca.

**Comment by mjalalimanesh** [comment]
Yes @Conengmo, I was using Jupiter. Updating branca solved the issue, thank you. thank you @deveshdatwani
