### ISSUE TITLE
Support GeoJSON simplestyle

### ISSUE THREAD

**Issue by themiurgo** [python-visualization/folium#120]
It would be great to support GeoJSON simplestyle (https://github.com/mapbox/simplestyle-spec), as it already happens in geojson.io and GitHub.

**Comment by ocefpaf** [comment]
@BibMartin Now that the re-factoring dust is settling we should start thinking about this.

**Comment by BibMartin** [comment]
It can be done base on #266 discussion. See @ocefpaf 's idea.

**Comment by themiurgo** [comment]
When this is ready I'd make it default, as I can see only advantages and no drawbacks. What do you think?

**Comment by ocefpaf** [comment]
We never found a champion for this implementation and I am biased to leave `folium` as-is. It is relatively simple for someone to create `style_function` that parses the `simplestyle`.
