### ISSUE TITLE
Easy way to add title for folium maps

### ISSUE THREAD

**Issue by abbey2017** [python-visualization/folium#1202]
```python
#Here is my contribution to include title to folium maps:
m = folium.Map()

title_html = '''
             <h3 align="center" style="font-size:20px"><b>Your map title</b></h3>
             '''
m.get_root().html.add_child(folium.Element(title_html))

m
```
#### Problem description
There is currently no argument for title in the the folium.Map() method. 

The current available method to include title is quite difficult requiring some lines of html code and then passing that through get_root().html.add_child()
#### Expected Output
It would be great to have something like:
folium.Map(title="Your map title")

**Comment by ocefpaf** [comment]
> folium.Map(title="Your map title")

It is `folium.Map(titles=url, attr="attribution")`. Please check the docs!

**Comment by abbey2017** [comment]
Please pay attention to my comment. This is not a tile issue. The issue is about an easy a to add a TITLE at the top of the map.

Thanks.

**Comment by ocefpaf** [comment]
There is no title! The HTML canvas is for mapping. Anything else should be done editing HTML or using branca.

**Comment by abbey2017** [comment]
Well, alternatives like bokeh offers an easier way to add title and even legends unless folium is strictly for software developers.

**Comment by ocefpaf** [comment]
Bokeh is a plotting library and not a exclusive mapping library. Please, go for Bokeh for those needs! Better yet, check geoviews.

**Comment by abbey2017** [comment]
No worries.

**Comment by AdnanHodzic** [comment]
> 

Also think this would be a great addition, hence not sure why the issue was closed. 

Does anyone have any workarounds how to set page title in Folium maps?

**Comment by abhasdudeja** [comment]
I do think that this is a necessary addition since there are some standards on how to create a better map.

**Comment by rodreras** [comment]
Dispite this topic being closed, I'd like to highlight that leafmap library can put title in your map. [Check their example documentation](https://leafmap.org/notebooks/25_map_title/)
