### ISSUE TITLE
Choropleth Plot not showing on colab notebook

### ISSUE THREAD

**Issue by AneeshaaSC** [python-visualization/folium#1203]
I run the below code snippet found in Plotly documentation. But the plot doesn't show on Google Colab. Could someone please advise on how I can get this working there?
```
import plotly.express as px

gapminder = px.data.gapminder().query("year==2007")
fig = px.choropleth(gapminder, locations="iso_alpha",
                    color="lifeExp", # lifeExp is a column of gapminder
                    hover_name="country", # column to add to hover information
                    color_continuous_scale=px.colors.sequential.Plasma)
fig.show()

```

**Comment by Conengmo** [comment]
Hi @AneeshaaSC,

I'm afraid your posting in the wrong repository. This is folium, not Plotly. folium incidently also can be used for choropleths, but your question is about Plotly. I suggest you ask it somewhere where Plotly questions are supposed to go, I don't know where, maybe Stackoverflow?

**Comment by AneeshaaSC** [comment]
Apologies.

**Comment by Conengmo** [comment]
No worries, good luck with your issue.
