### ISSUE TITLE
Any motivation for adding options to style the visualizations using no tiles? changing the bg color etc.

### ISSUE THREAD

**Issue by shriphani** [python-visualization/folium#1204]

**Comment by Conengmo** [comment]
Hi @shriphani, to be honest I haven’t considered this before. What would be the use case? Do you have ideas on what options you’d like?

**Comment by shriphani** [comment]
Hi, so I've been using folium in 2 ways - overlaying on leaflet, and then plotting regular geojsons - like one would with d3.

In the latter use-case I do a bunch of things - for instance background images (not tile rasters), high contrast colors etc. In the former, I would like to control tooltips, fonts etc.

I would be happy with just being able to drop css in the HTML it spits out so the notebook and the saved html can be styled. 

I can take a crack at this if you'd be interested - doesn't seem too hard to me. I could possibly just drop it in the head sections of the HTML where it just overrides leaflet.css.

**Comment by Conengmo** [comment]
I don't think this is something we want to include in folium, but I'd be happy to be shown a use case we are currently missing.

Adding custom CSS to your map is pretty simple currently:

```
Element('<style></style').add_to(m.get_root().header)
```
