### ISSUE TITLE
How does one [deep]copy a map object?

### ISSUE THREAD

**Issue by jwhendy** [python-visualization/folium#1207]
I was hoping to cycle through a dataframe of `(lat, lon)` locations and add a big, opaque point for each, then a less opaque, smaller point. As I go, I want the small dots to stay to draw attention to each new point added.

I tried this without success (well, via `df.iterrows()` on my end, but here's a simper reproducible example):

```
bbox = [[44.935, -93.09], [44.955, -93.06]]
m = folium.Map(location=[np.mean([bbox[0][0], bbox[1][0]]), np.mean([bbox[0][1], bbox[1][1]])])
m.fit_bounds(bounds=bbox)

m1 = m
#m1 = folium.Map(location=[np.mean([bbox[0][0], bbox[1][0]]), np.mean([bbox[0][1], bbox[1][1]])])
#m1.fit_bounds(bounds=bbox)

folium.Circle(location=[44.95, -93.07], radius=50, fill=True, stroke=False, fill_opacity=0.8, fill_color='blue').add_to(m1)
IPython.display.display(m1)
time.sleep(2)
IPython.display.clear_output(wait=True)

folium.Circle(location=[44.95, -93.07], radius=20, fill=True, stroke=False, fill_opacity=0.3, fill_color='blue').add_to(m)
IPython.display.display(m)
time.sleep(2)
IPython.display.clear_output(wait=True)
```

I'm guessing `m1` is actually referencing `m` and is not really a copy. I tried `m1 = copy.deepcopy(m)` but get `TypeError: __new__() missing 1 required positional argument: 'source'`

Any suggestions? If I create the `m1` object explicitly using the commented lines above, it works, but this wouldn't work to create the desired effect of having existing translucent dots always there and only adding the new opaque dot on each iteration.

**Comment by jwhendy** [comment]
Update: had the idea to use a `FeatureGroup`, but this requires me initializing `m1` each time. So (in pseudocode):

```
fg = folium.FeatureGroup()
loop:
    m1 = folium.Map()
    fg.add_to(m1)
    c = folium.Circle(big_opaque)
    c.add_to(m1)
    display(m1)

    c = folium.Circle(small_translucent)
    c.add_to(fg)
    fg.add_to(m)
    display(m)
```
Is this the best way? Maybe there is no overhead to constantly initializing and adding a feature group vs. copying...

**Comment by Conengmo** [comment]
Hi @jwhendy, cool idea! 

Note that messing with the tree structure underlying folium is a bit more advanced and can lead to quirks. So I wouldn’t recommend deep copying a Map object or trying to delete objects in the Map tree. Unless you’d like to dive in that of course, it’s all quite hackable.

I was thinking, since you have a sleep of 2 seconds anyway why not create a new Map each time? Seems unnecessary to optimize this for performance.

**Comment by Conengmo** [comment]
I’ll close the issue by the way because I don’t think anything in this is actionable. Making ‘Map’ deep copyable is not something I think we want to build. Making it robust for all users and maintaining that would take quite some effort.

**Comment by jwhendy** [comment]
Thanks for the feedback. I wasn't sure on the performance hit of recreating a new map, as well as having to re-add all previous points vs. just adding the ones since the last time through the loop. My process is working well, though. I'll post the output so you can see it!

It's a hobby project exploring accident data I was able to get from my city to see if the accident rate changed since the bridge was redone. Turns out it has :) Thankfully `folium` could enable me to verify this. Now I'm trying to create a compelling graphic to see about getting improved signage. Should have my final result later today.

**Comment by jwhendy** [comment]
I'll probably putz with it a little more, but this was the gist... I may try one where each accident starts out at one size and then reduces gradually to the final size. I was hoping it would be more apparent that the accident rate on this bridge is much higher after the rebuild, but I don't feel it conveys that super strongly.

In any case, thanks to `folium` for enabling a fun visualization project!

![animation-reduced](https://user-images.githubusercontent.com/379357/65392321-33983c00-dd39-11e9-8c9a-7365a6d8861a.gif)

**Comment by Conengmo** [comment]
Cool project @jwhendy, thanks for sharing!
