### ISSUE TITLE
Combining `GeoJson` markers in a `MarkerCluster` shows unclustered markers

### ISSUE THREAD

**Issue by diegoquintanav** [python-visualization/folium#1209]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
with open('examples/data/search_bars_rome.json') as f:
    data = json.load(f)
data_url = 'https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/search_bars_rome.json'

m = folium.Map((41.9, 12.5), tiles='cartodbpositron')
marker_cluster = folium.plugins.MarkerCluster(name='mc').add_to(m)
folium.GeoJson(data_url, embed=False).add_to(marker_cluster)
folium.GeoJson(data_url, embed=False, name='geojson').add_to(m)
folium.LayerControl(collapsed=False).add_to(m)
m.save('_map.html')
m
```
#### Problem description

I expected to see the markers in a clustered fashion

![image](https://user-images.githubusercontent.com/16281387/65758404-5780c680-e119-11e9-9ad5-8cdd69b5ab1e.png)

I can't tell from #1190, #1129 and #1188 if this is fixed in version 0.10.0, and if it is, what's the right syntax?

#### Expected Output

Clustered markers (This was taken from another example)

![image](https://user-images.githubusercontent.com/16281387/65758962-41bfd100-e11a-11e9-9c7c-4ccc76d358ac.png)

#### Output of ``folium.__version__``

'0.10.0'

**Comment by fullonic** [comment]
Hi @diegoquintanav, I think that #1190  fixed the problem you mention, and it was done after the release of version 10. Therefore, would be better install folium directly from github give it a try again.

**Comment by fullonic** [comment]
Confirmed! It works with folium installed directly from github.
I had time to run your script and here is a screenshot of your the html file.

![Screenshot_2019-10-24 Screenshot](https://user-images.githubusercontent.com/13336073/67504760-4f6d6580-f68a-11e9-8acd-9921d959f9a8.png)

**Comment by vjsequi** [comment]
I am having the same issues I'm afraid. It doesn't render the MarkerCluster at all.

![image](https://user-images.githubusercontent.com/41633498/84541454-54515900-acef-11ea-9678-50bad4aef774.png)

![image](https://user-images.githubusercontent.com/41633498/84541475-5f0bee00-acef-11ea-8ac7-d2c63241fe66.png)

![image](https://user-images.githubusercontent.com/41633498/84541715-d0e43780-acef-11ea-94f8-cfb1924c3675.png)

![image](https://user-images.githubusercontent.com/41633498/84541530-82cf3400-acef-11ea-9103-bcbb0a56c374.png)

Thanks for your help!

**Comment by Conengmo** [comment]
It seems #1190 (merged July 2019) and #1289 (merged April 2020) are at odds with each other. We have to resolve the conflicting requirements. Some ideas:

- make the ajax call synchronous and add to parent when it finished
- move the embedded data to the `GeoJson()` call and accept that not al functionality will work when not embedding data.

**Comment by vjsequi** [comment]
I think I've found a way round it. If you make the GeoJson a subgroup of the MarkerCluster it seems to work. Although weirdly you need to untick and tick GeoJson layer (Housing) for it show anything.

```Python
with open('examples/data/search_bars_rome.json') as f:
    data = json.load(f)
data_url = 'https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/search_bars_rome.json'

m = folium.Map((41.9, 12.5), tiles='cartodbpositron')
marker_cluster = folium.plugins.MarkerCluster(name='Developments')
mc1= folium.plugins.FeatureGroupSubGroup(marker_cluster, 'Housing')
m.add_child(marker_cluster)
m.add_child(Housing)
mc1.add_child(folium.GeoJson(data_url, embed=False))
folium.LayerControl(collapsed=False).add_to(m)
m
```
![image](https://user-images.githubusercontent.com/41633498/84565535-b9459700-ad61-11ea-89e6-2052c7293ebf.png)

My next query is, how can I show labels, either tooltips or popups? Substituting `mc1` with the code below doesn't seem to work.
```Python
mc1.add_child(folium.GeoJson(data_url, tooltip=folium.GeoJsonTooltip(fields=['addr:street']), embed=False))
```

**Comment by Conengmo** [comment]
It seems combining `GeoJsonTooltip` and `MarkerCluster` plugin is not supported behavior. Note that while everything in the base folium library should work well together we can't guarantee that for the plugins.

I don't think using the `FeatureGroupSubGroup` plugin is a real solution here. I'll make a PR where we do the ajax call asynchronously.

**Comment by Conengmo** [comment]
The fix has been merged. It will be in the next release, v0.12.0, release date yet unknown. If you want it earlier you can install folium from the main branch:

```
pip install git+https://github.com/python-visualization/folium.git@master
```
