### ISSUE TITLE
Prevent image caching in leaflet popup?

### ISSUE THREAD

**Issue by maragard** [python-visualization/folium#1214]
[Copied from SO](https://stackoverflow.com/questions/58357496/prevent-image-caching-in-leaflet-popup)

So I have a Python web service that creates maps with Folium/Leaflet.js. Each plotted point is a marker with a custom popup:

```python
folium.Marker(
            location=(row['lat'], row['lng']),
            icon=folium.Icon(color=color_mapper[type]),
            popup=folium.Popup(f'<p>{info_str} taken at {row["time"]} <br> \
                                    Description: {row["description"]}</p> \
                                    <img src={row["photoURL"]} width=300 height=500>'),
                tooltip=info_str
)
```
As of now when the generated HTML file is opened, any images in the popup will be loaded alongside the tilesets and plotted points. This has led to extremely slow loading times and excessive charges on each image loading call for each map. I there a way to override the popup's default behavior and only load the image when the popup is opened?

**Comment by Conengmo** [comment]
Hi @maragard,

This is not something that folium can do. But you can mess around in the Leaflet Javascript that code that folium generates to make this happen. I'm thinking using the marker's onclick event to fill the popup. Here's a bit on that:

https://gis.stackexchange.com/questions/141548/how-to-update-a-popup-content-from-its-marker

Hope that helps. We rely on volunteers for new features, so if you get this working it'd be great if you can share your approach here. It may be something to consider opening a PR for, though I hope you understand I can't promise that it'll be included.

**Comment by marciogranzotto** [comment]
@maragard any luck with this? I'm having the same problem. I have a map with over 3000 pins each containing an external image (camera snapshot).
