### ISSUE TITLE
Possible to have different GeoJson layer level ?

### ISSUE THREAD

**Issue by shiron263** [python-visualization/folium#1218]
#### Problem description
I would like to make a map that display different layer level in the area that we want.
[This map](https://france-geojson.gregoiredavid.fr/) is a perfect example of the result i'm looking for.
For the moment I just have the first step, i display all region of France and i'm stuck here because i don't know how to get the click of the mouse with Folium ( or if it's not possible, i don't know how to use the highlight_function to display an another GeoJson file in the area that the mouse is ).

**Comment by Danieldavid521** [comment]
I think you may want the function folium.FeatureGroup(), and then you will use the .add_child() function to call the multiple layers
