### ISSUE TITLE
Add auto start to Locate Control plugin

### ISSUE THREAD

**Issue by fullonic** [python-visualization/folium#1219]
Actually the locate control plugin doesn't provide a way of auto start, being necessary the user click on plugin button to get they position showed on map.
However the Leaftlet plugin gives the possibility of having a auto start simply by doing lc.start(); after plugin is initiation. [source](https://github.com/domoritz/leaflet-locatecontrol#methods)

@Conengmo , if you are okay with implementing this on folium plugin I'm happy in making a PR.

I already implemented and tested [here](https://github.com/fullonic/folium/commit/ec32b6fc003b305ac37dfe6492eda679f17f5890) and works as expected.

**Comment by Conengmo** [comment]
Sounds good!

**Comment by fullonic** [comment]
@Conengmo , I made a PR  #1220 that closes this issue. Stay well

**Comment by Conengmo** [comment]
Thanks @fullonic, it looks good, I'll give it a try later and merge if nothing weird comes up.

**Comment by mejl** [comment]
How do you use it?

**Comment by fullonic** [comment]
Hi @mejl. To use this functionality, you just need to initiate the `LocateControl` plugin with the `auto_start=True` instead of the default value `False`. https://github.com/python-visualization/folium/blob/67aab11039cd990d73fdf14566380286835ff84b/folium/plugins/locate_control.py#L68

**Comment by mejl** [comment]
Hello @fullonic. That worked, thank you.
