### ISSUE TITLE
how edit a layer wfs and geojson in folium?

### ISSUE THREAD

**Issue by Jackelinem** [python-visualization/folium#1225]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behavior is a problem and what is the expected output.]

**Comment by Conengmo** [comment]
Hi @Jackelinem, we really need some more info to answer your question. If your question is not really an issue but more an ask for help, it's maybe better to post it on Stackoverflow instead using the `folium` tag. https://stackoverflow.com/questions/tagged/folium
