### ISSUE TITLE
Tile Layer Missing options

### ISSUE THREAD

**Issue by ozak** [python-visualization/folium#123]
Hi,

I tried using the ``add_tile_layer`` command, but noticed there are many options that one would like to pass which are not available. See [here](http://leafletjs.com/reference.html#tilelayer) for possible options.

**Comment by birdage** [comment]
hi @ozak, this was a basic implementation of a WMS tile layer, feel free to add to it and give back to the community if it does not meet your needs

**Comment by ozak** [comment]
@birdage That was precisely my idea!

**Comment by birdage** [comment]
@ozak love it! :beers:

**Comment by ozak** [comment]
@birdage I just added the missing options.

On another front, is there a way to choose which projection to set the map if one wants to use e.g. OSM? From what I see, it seems to start using spherical mercator, but I'd like to be able to change that. Any pointers?

**Comment by birdage** [comment]
@ozak there is a plugin here https://github.com/kartena/Proj4Leaflet to do just that but i dont know if it does it out the box

**Comment by ocefpaf** [comment]
This is being addressed in #124.  I am closing this to tidy-up the issues list.
