### ISSUE TITLE
Upgrade to Leaflet v1.6.0

### ISSUE THREAD

**Issue by Conengmo** [python-visualization/folium#1230]
Leaflet v1.6.0 has been released.

https://github.com/Leaflet/Leaflet/releases/tag/v1.6.0

- [x] Check the release notes for changes that may impact us.
- [ ] Bump the version and test if everything still works.
- [ ] Merge the PR

**Comment by ocefpaf** [comment]
According to https://github.com/Leaflet/Leaflet/releases/tag/v1.6.0 there are two API changes that I don't think will affect `folium`.
