### ISSUE TITLE
Something is wrong with HeatMapWithTime()

### ISSUE THREAD

**Issue by sokgong** [python-visualization/folium#1231]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here
https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/HeatMapWithTime.ipynb
```
#### Problem description
when I test the plugins in the example and the link above, the map output does not show anything except the base map. I think this is due to upgrade of Leaflet?

[this should explain **why** the current behavior is a problem and what is the expected output.]

**Comment by exitxingling** [comment]
Hello, has this issue been resolved?

**Comment by JRHutson** [comment]
I'm still seeing the issue. Also finding tutorials that appear to be impacted.
https://www.kaggle.com/daveianhickey/how-to-folium-for-maps-heatmaps-time-data

**Comment by sknzl** [comment]
Same here. Getting following JS errors when trying to use HeatMapWithTime

``
ReferenceError: nezasa is not defined leaflet.timedimension.min.js:18:252
``

``
TypeError: L.TimeDimension is undefined
``

``
TypeError: L.timeDimension is not a function
``

**Comment by JRHutson** [comment]
Saw a merge request from someone that appeared related. Pulled the latest code and imported Folium directly from that. HeatMapWithTime is working now for me. Not sure how long it takes for that to be updated on PIP.

**Comment by Conengmo** [comment]
I believe this is the same as https://github.com/python-visualization/folium/issues/1221

we'll do a release asap

**Comment by Conengmo** [comment]
We just released v0.10.1 which should fix this issue. It's available on Pypi.

**Comment by sknzl** [comment]
@Conengmo thanks for the fix! Sorry for not checking #1221 before.
I installed the latest master, and the TimeDimension error is gone. However I get now a different JS error when trying to use HeatMapWithTime:

```
ReferenceError: HeatmapOverlay is not defined
```

**Comment by Conengmo** [comment]
Can you try disabling your ad blocker? That might help. It sometimes blocks resources that have 'heatmap' in the name.

**Comment by sknzl** [comment]
That solved it. Thanks! That's an odd one, since no other js resource seems to be blocked.

**Comment by Conengmo** [comment]
Good to hear! We've had this issue before, hosting the JS library ourself under a different name solved it. I'll open an issue to do the same thing with the new culprit, which I'm pretty sure is `https://rawcdn.githack.com/pa7/heatmap.js/develop/plugins/leaflet-heatmap/leaflet-heatmap.js`.

**Comment by blextar** [comment]
Hi all, I see this issue has been closed but I'm getting a weird behaviour with my heatmap that seems related. The map works fine when I create it and open it locally but it stops working when I push it to its github page (the controls are not visualised correctly)
https://blextar.github.io/WuFlu/

Any idea of what may be happening?

**Comment by sknzl** [comment]
@blextar 
I'm seeing following error in the browser console when accessing your page:
```
Mixed Content: The page at 'https://blextar.github.io/WuFlu/' was loaded over HTTPS, but requested an insecure stylesheet 'http://apps.socib.es/Leaflet.TimeDimension/dist/leaflet.timedimension.control.min.css'. This request has been blocked; the content must be served over HTTPS.
```

I guess that's a new issues, since the css asset related to the controls is requested from a server that does not support https.

In `timestamped_geo_json.py`
```
https://rawcdn.githack.com/socib/Leaflet.TimeDimension/master/dist/leaflet.timedimension.control.min.css
```
is used, while in `heat_map_withtime.py` the http link is used
```
http://apps.socib.es/Leaflet.TimeDimension/dist/leaflet.timedimension.control.min.css
```

**Comment by Conengmo** [comment]
Good find @sknzl ! As you can see folium is already quite old :) do you want to open a PR with the updated url?

**Comment by blextar** [comment]
Thanks for the quick reply @sknzl. FYI, just in case you'll try to access that page again to replicate the error, I've manually edited http -> https for the moment.
