### ISSUE TITLE
Widgets for folium heatmapwithtime plugin not showing up. 

### ISSUE THREAD

**Issue by pfwangs** [python-visualization/folium#1232]
#### Please add a code sample or a nbviewer link, copy-pastable if possible
I am trying to follow this guide, however, I get the same made twice even when I use https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/HeatMapWithTime.ipynb

```python
# hm = plugins.HeatMapWithTime(
    data,
    index=time_index,
    auto_play=True,
    max_opacity=0.3
)

```

**Comment by YangJing524** [comment]
is this issue resloved?

**Comment by Conengmo** [comment]
We would need more information to investigate this. At least a code snippet that produces the error, any relevant error messages in Python or in your browser console, screenshots of how the map looks like, etc.
