### ISSUE TITLE
Unable to remove markers or polylines added to the Map

### ISSUE THREAD

**Issue by prashanthgpkr** [python-visualization/folium#1233]
I am currently using Folium (0.10.0) to create a Map for a given data. In my specific use case, I would like to add markers and then delete the specific markers as the data gets updated. This also should work with respective polylines that are plotted between these markers.

I have been looking for the appropriate way to do this, but not able to find any solution so far. Could any one please let me know, if there is any way to solve this issue?

**Comment by Conengmo** [comment]
I'm afraid folium is not really suitable for this. It's a one way street from Python to Javascript. Dynamically updating your map when your data in Python changes is not possible, other than rerendering the entire map.

You could check it this other library called ipyleaflet, it focuses more on interactivity in Jupyter notebooks: https://github.com/jupyter-widgets/ipyleaflet

**Comment by pstatonwx** [comment]
@Conengmo Just curious if any progress has been made on this since posting - hoping it's possible now :)
