### ISSUE TITLE
TimestampedGeoJson does not plot entire image

### ISSUE THREAD

**Issue by samirak93** [python-visualization/folium#1235]
I'm trying to make a TimestampedGeoJson using a geojson file. I've previously done that and the output was correct. Now when I try with a different data, the plot is not complete. 

This is an example where it worked fine (this was done long back). [https://github.com/samirak93/snow/blob/master/Complete_Notebook.ipynb](https://github.com/samirak93/snow/blob/master/Complete_Notebook.ipynb)

This is the example I'm trying to plot now.

```
import urllib.request, json 
import urllib.request, json 
from folium.plugins import TimestampedGeoJson
import folium
from folium import plugins

with urllib.request.urlopen("https://gist.githubusercontent.com/samirak93/3ca0672e89677c248cb4853e374a02ac/raw/5c46cfdcefc4aca2e459ddd60f99a9e21db1843f/myfile.geojson") as url:
    data = json.loads(url.read().decode())
    
geomap = folium.Map(location=[51.4919263,-0.1867], zoom_start=10, tiles="cartodbpositron")

TimestampedGeoJson(
    data,
    auto_play=False,
    date_options='YYY'
    ).add_to(geomap)

plugins.Fullscreen(position='topright', force_separate_button=True).add_to(geomap)
geomap
```

The plot when plotted with Matplotlib's Contourf
![image](https://user-images.githubusercontent.com/22864480/70198296-504ed980-16c3-11ea-9d02-22c4845a79ae.png)

The image when plotted on folium:

![image](https://user-images.githubusercontent.com/22864480/70198335-6f4d6b80-16c3-11ea-95b9-dd8cae6cfc71.png)

```
Python version: 3.7.5
Folium version: 0.10.1
```

Any feedback would be helpful. 

Thanks.

**Comment by Conengmo** [comment]
Could you look in your browser's console and share any error messages that might be there?

**Comment by samirak93** [comment]
This is the output on the chrome console.

![image](https://user-images.githubusercontent.com/22864480/70253617-5df27680-1738-11ea-85b6-89089a3365b9.png)

Checked with firefox as well and could not see the output.

**Comment by Conengmo** [comment]
One more thing, could you try to export the map as an html file, and open that in your browser? That way we know whether the issue has to do with Jupyter or not.

`m.save('index.html')`

**Comment by samirak93** [comment]
I see a bunch of warning's on Firefox but none on Chrome/Safari. There are no errors as well.

![image](https://user-images.githubusercontent.com/22864480/70255445-ab241780-173b-11ea-8c8d-cb21ced9af8a.png)


I've uploaded the html file here [https://gist.github.com/samirak93/6b2d0f6b9fad93f8c248a8b418926ba1#file-geojson-html](https://gist.github.com/samirak93/6b2d0f6b9fad93f8c248a8b418926ba1#file-geojson-html)

Thank you.

**Comment by Conengmo** [comment]
It seems your input data is incorrect. It seem each geojson feature has the same property `"time": "2287-01-31"`. But the plugin requires each feature to have a property `times`, which should be list containing either unix epoch timestamps in ms or ISO format timestamps. See https://python-visualization.github.io/folium/plugins.html#folium.plugins.TimestampedGeoJson
