### ISSUE TITLE
real time (live) map

### ISSUE THREAD

**Issue by RuikunLi** [python-visualization/folium#1236]
Hi there,

got a question, is it possible to create a live map with folium? For example, I can get streaming gps data from database and visualize it with a moving marker on the map.

best regards,

Ruikun

**Comment by Conengmo** [comment]
Hi @RuikunLi, unfortunately folium is not that well suited for this kind of dynamic webapps. For that you'll have to dive into the [Leaflet](https://leafletjs.com/) Javascript code that folium generates. Have a look at the html+JS output that folium makes.

Alternatively, as a poor man's dynamic webapp, you could make for example a Flask app, have it [generate](https://python-visualization.github.io/folium/flask.html) a folium page, and let the page refresh update every x minutes. For that last bit you'll have to add some custom Javascript.

**Comment by RuikunLi** [comment]
Thanks
