### ISSUE TITLE
href in marker's popup closing the map in flask

### ISSUE THREAD

**Issue by Erafier** [python-visualization/folium#1237]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
        html = """<a href="/galery"> <button type="button" class="btn btn-primary">Small button</button></a>"""
        popup = folium.Popup(html)
        folium.Marker(camera['coordinates'], icon=folium.features.CustomIcon(icon_url, icon_size=(32, 37)),
                      popup=popup).add_to(map)
```
code for /galery
```
@app.route('/galery/')
def galery():
    return render_template('images.html', image_catalog=galery_catalog)

```
#### Problem description

I'm trying to add a link to the popup that will redirect me to another page on the server (Flask)
And when you click on the link, the map disappears.

#### Output of ``folium.__version__``
0.10.1

**Comment by fullonic** [comment]
@Erafier , I'm not sure if it's the source of your problem, but you're not providing the correct href for your flask route.
It should be: href="{{ url_for('galery') }}"
So, your html variable would be:
html = """<a href="{{ url_for('galery') }}"> <button type="button" class="btn btn-primary">Small button</button></a>"""

**Comment by Erafier** [comment]
@fullonic, thx for help

> Otherwise you need to provide the full URL path for your gallery route. For instance, if your flask app is running in your localhost with port 5000, it would be `href="http://localhost:5000/gallery"`

It works, great, but link opens in that place, there was a map, there you can also open the link and do it recursively. It seems that the contents of the map simply do not know the links of the flask.

> So, your html variable would be:
> `html = """<a href="{{ url_for('galery') }}"> <button type="button" class="btn btn-primary">Small button</button></a>"""`

This does not seem to work for the same reason

`  File "<template>", line 5, in top-level template code
jinja2.exceptions.UndefinedError: 'url_for' is undefined`

**Comment by fullonic** [comment]
@Erafier that happens because you didn't set the target attribute in the <a> tag. The list of possibilities: https://www.w3schools.com/tags/att_a_target.asp

**Comment by Conengmo** [comment]
This doesn't seem like something that's actionable for folium, so I'm closing the issue. Feel free to continue discussing the original problem here. We can reopen if warranted.
