### ISSUE TITLE
Vega-lite visualization with folium

### ISSUE THREAD

**Issue by mnobeidat13** [python-visualization/folium#1242]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
chart = alt.Chart(cars).mark_bar().encode(
    alt.X('area:Q',bin=True),
    y='average(price)',
#     color='beds:N',
).add_selection(
    slider_selection
).transform_filter(
    slider_selection
).add_selection(
    slider_selection2
).transform_filter(
    slider_selection2
)
```
```python
folium.Marker(
    location=[25.2048, 55.2708],
    popup=folium.Popup(max_width=450).add_child(
        folium.Vega(chart.to_json(), width=450, height=250))
).add_to(m)
```
#### Problem description

I tried to add a visualization created by altair to folium.Marker object but it is not working.
Altair produces Vega-Lite visualization which I guess is not compatible with folium.
Is there any way to convert vega-lite to vega? or anything that can resolve this issue.

folium 0.10.1

**Comment by ocefpaf** [comment]
`altair` is a `vegalite` objecy, please see cell [6] from this example: https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Features.ipynb
