### ISSUE TITLE
when screenshotting with selenium, open popups are only captured if selenium window is active/in focus?

### ISSUE THREAD

**Issue by jwhendy** [python-visualization/folium#1246]
I don't know if this is a `folium` issue or not, but found it really weird! Here is an example:

```
import folium
import os
import time
from selenium import webdriver


def map_to_png(m, fname, path=None):
    browser = webdriver.Firefox()
    browser.set_window_size(1400, 850)
    if not path:
        path = os.getcwd()
    # save the map, open with selenium, wait for initial load
    m.save('{}/map.html'.format(path))
    browser.get('file://{}/map.html'.format(path))
    time.sleep(5)
    browser.save_screenshot('{}/{}.png'.format(path, fname))
    browser.quit()

m = folium.Map(location=[38, -90], zoom_start=5)
folium.CircleMarker(
    location=[38, -90],
    popup=folium.Popup('foo', sticky=True, show=True),
    radius=6,
    stroke=False,
    fill=True,
    fill_color='#000000',
    fill_opacity=0.75).add_to(m)
m
```

In `jupyter lab`, I see this:

![grab_2020-01-11_133511](https://user-images.githubusercontent.com/379357/72209737-37ca9f80-3477-11ea-8c8a-3f8d97b2eda9.png)

In my actual workflow, I'm prototyping maps, then want to save them out, so I do:

```
map_to_png(m, 'foo')
```

I have a lot of points, and am double tasking so when the `selenium` does it's thing I shift focus to whatever I want to do while it saves out (e.g. `Alt+tab` back to jupyter or perhaps shifting to a new virtual workspace). I was alternating between updating maps/saving and prepping a `.tex` file to include the output graphics and it surprised me to find out my saved images didn't show the popups!

I found that when I shift away from the firefox window, the popups aren't in the saved png, but when I watch, they are!?

Is this known, or might there be an explanation? I found this really weird! In testing opening the .html directly, they definitely are open, it's just not saving unless I have the selenium window in focus during the screenshot operation.

Watching:
![foo](https://user-images.githubusercontent.com/379357/72209778-de16a500-3477-11ea-8b13-6049c89a37d6.png)

Not watching:

![foo](https://user-images.githubusercontent.com/379357/72209774-d0f9b600-3477-11ea-9eca-0ef9483eaf35.png)

**Comment by Conengmo** [comment]
This issue shouldn't occur when you use a headless browser, because then there's no notion of focus. Take a look at `Map._to_png()`.

```
options.add_argument('--headless')
```
