### ISSUE TITLE
Python Folium map

### ISSUE THREAD

**Issue by prashen2019** [python-visualization/folium#1247]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here
for ind in range(0, 10): 
    longX=float(df_incidents['X'][ind])
    longY=float(df_incidents['Y'][ind])
    longCount=df_incidents['Count'][ind]    
    for point in range(0, longCount):
        folium.Marker(location=[longX, longY]).add_to(marker_cluster)
    map3
```
#### Problem description
I have nested for loop and wanted to display the count using marker but map3 does not display anything. It's working fine if I use single for loop. Any idea anyone?
[this should explain **why** the current behavior is a problem and what is the expected output.]

**Comment by Conengmo** [comment]
You posted only a small part of your code, so it's hard to say. If you're on Jupyter, I would say not to display the map inside a loop. Other than that you will probably get better help on Stackoverflow, this issue tracker is meant more for bugs and feature requests than questions.
