### ISSUE TITLE
support WMS parameter cql_filter

### ISSUE THREAD

**Issue by bhogan-mitre** [python-visualization/folium#1248]
Not all WMS parameters are `camelCase`, and the current use of `camelize` by `parseOptions` prevents the proper application of some parameters through `**kwargs`.

```python
import folium

m = folium.Map(
  location=[40, -100],
  zoom_start=4
)
 
states = folium.WmsTileLayer(
  url = "https://ahocevar.com/geoserver/wms",
  layers = "topp:states",
  fmt = "image/png",
  transparent = True,
  cql_filter = "STATE_ABBR IN ('NY','IL')"
)

states.add_to(m)
m
```
![Screen Shot 2020-01-14 at 9 25 30 AM](https://user-images.githubusercontent.com/32336739/72352853-04735500-36b1-11ea-90ee-ea392c2f0ba9.png)

#### Problem description
Leaflet [`TileLayer.WMS`](https://leafletjs.com/reference-1.6.0.html#tilelayer-wms) options state that:
>If any custom options not documented here are used, they will be sent to the WMS server as extra parameters in each request URL. This can be useful for non-standard vendor WMS parameters.

One particularly useful parameter is [`cql_filter`](https://docs.geoserver.org/stable/en/user/services/wms/vendor.html#cql-filter).  The `cql_filter` parameter should be passed through `**kwargs` like any other parameter.  Currently `camelize` is treating that as `cqlFilter` which prevents it from being used.  `format_options` is another parameter that would be impacted by this.

#### Expected Output
`cql_filter` should be applied to limit the set of results from `WmsTileLayer`.

![Screen Shot 2020-01-14 at 9 35 50 AM](https://user-images.githubusercontent.com/32336739/72352996-48fef080-36b1-11ea-8740-e278738001b6.png)

#### Output of ``folium.__version__``
`0.10.1`

**Comment by Conengmo** [comment]
Hi @bhogan-mitre, thanks for reporting this. I'm thinking this may be best solved by making a special case in the `WmsTileLayer` class when unpacking the kwargs. This should be fairly trivial. Maybe you want to make a PR?

**Comment by kirodh** [comment]
Hi there

Was this fixed by any chance?

Kind regards

**Comment by thiagomesUNB** [comment]
> Hi there
> 
> Was this fixed by any chance?
> 
> I got around this by adding in a special case for CQL_FILTER keyword where the kwargs are camelized.
> 
> But its still a hack i suppose and only works for an all caps (CQL_FILTER) keyword.
> 
> Kind regards

Hi, could you show how you added this special case to cql_filter?

**Comment by mritzman-dg** [comment]
Hi @kirodh, how were you able to get around this?  I'm having the same issue where the request becomes cqlFilter instead of cql_filter.  Thanks in advance!

**Comment by kirodh** [comment]
Hi @mritzman-dg 

I am also navigating the space with all this forking and branching etc. But at the time to get stuff to work, i made a copy of the repo with the modification that should work. https://github.com/kirodh/folium-kirodh 

I did the following to the folium repo:

In the folium folder edit the utilities.py file. Right at the bottom you have the parse_options function. use this instead:

`def parse_options(**kwargs):

    """Return a dict with lower-camelcase keys and non-None values.."""

    # changes by Kirodh:
    kwargs_all = {camelize(key): value
            for key, value in kwargs.items()
            if value is not None}
    
    # modification for CQL_FILTER argument from geoserver:
    try:
        kwargs_all["CQL_FILTER"] = kwargs_all["CQLFilter"]
        del kwargs_all["CQLFilter"]
    except Exception as e:
        None

    return kwargs_all`

Sorry my formatting skills, not so great 

This basically checks to see if the CQL_FILTER keyword is there and replaces it with the camel case equivalent.
Hope this helps. 

not sure if this can be added as a patch to the current folium code repo.

Kind regards
Kirodh
