### ISSUE TITLE
Folium BeautifyIcon

### ISSUE THREAD

**Issue by prashen2019** [python-visualization/folium#1249]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here
!conda install -c conda-forge folium=0.7.0 --yes
import folium
from folium.plugins import BeautifyIcon
```
#### Problem description
ImportError: cannot import name 'BeautifyIcon' from 'folium.plugins' 
[this should explain **why** the current behavior is a problem and what is the expected output.]

**Comment by Conengmo** [comment]
That's weird, I suspect something went wrong with your installation. Please try to install folium again. I'll close the ticket because this doesn't seem like something wrong with folium, but feel free to add more comments, we can reopen if needed.

**Comment by prashen2019** [comment]
Thank you for quick suggestion. I have just restarted my system and it's started working.Thank you.

**Comment by Conengmo** [comment]
Good to hear :)
