### ISSUE TITLE
Check the possibility of implementing Leaflet.TimeDimension

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#125]
https://github.com/socib/Leaflet.TimeDimension

**Comment by birdage** [comment]
@ocefpaf i think i prefer this to the other one i was looking at

**Comment by ocefpaf** [comment]
Yeah.  I wanted to discuss that with you before doing anything. (@rsignell-usgs brought that one up yesterday and got me thinking...)

I will see what I can do.

**Comment by themiurgo** [comment]
Yes, this looks nicer. :+1:

**Comment by birdage** [comment]
@ocefpaf i think we/i will do an initial eval of getting it in but there is a larger question of plugins etc

**Comment by ocefpaf** [comment]
Yes, I have been avoiding that...  I tested a few designed and they all failed to be "generic enough" for the majority of the Leaflet plugins.

**Comment by themiurgo** [comment]
@ocefpaf do we have a minimal list of plugins that are diverse enough to cover the different ways they are implemented? Having this list could be helpful to try to come up with a generic solution.

**Comment by ocefpaf** [comment]
Yes and no.  Both @birdage and I have that list in our minds.  I will start an issue listing that so we can proceed.  Thanks!

**Comment by ocefpaf** [comment]
The plugins machinery is being re-invented in #160 and the Leaflet.TimeDimension example is implemented in https://github.com/BibMartin/folium/commit/032537ca35705c5ba876fd8c98c45ec01e643b9a.
