### ISSUE TITLE
folium/examples/FloatImage.ipynb: No such file or directory: 'results/FloatImage.html'

### ISSUE THREAD

**Issue by blasscoc** [python-visualization/folium#1250]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

#code: folium/examples/FloatImage.ipynb

```
import os
import folium

print(folium.__version__)

from folium.plugins import FloatImage

url = ('https://raw.githubusercontent.com/SECOORA/static_assets/'
       'master/maps/img/rose.png')

m = folium.Map([-13, -38.15], zoom_start=10)

FloatImage(url, bottom=40, left=65).add_to(m)

m.save(os.path.join('results', 'FloatImage.html'))

m
```

#### Problem description

---------------------------------------------------------------------------
```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-1461c7156c04> in <module>
      8 FloatImage(url, bottom=40, left=65).add_to(m)
      9 
---> 10 m.save(os.path.join('results', 'FloatImage.html'))
     11 
     12 m

~/.edm/envs/XXX/lib/python3.6/site-packages/branca/element.py in save(self, outfile, close_file, **kwargs)
    162         """
    163         if isinstance(outfile, text_type) or isinstance(outfile, binary_type):
--> 164             fid = open(outfile, 'wb')
    165         else:
    166             fid = outfile

FileNotFoundError: [Errno 2] No such file or directory: 'results/FloatImage.html'

```

#### Expected Output

Don't know, but the error looks to be in the folium code.

#### Output of ``folium.__version__``

0.10.1

**Comment by Conengmo** [comment]
You're trying to save to a file `FloatImage.html` in a folder called `results`. Seems most likely that that folder doesn't exist. Either make sure it does: `os.mkdir('results')`, or do a save in the bare directory: `m.save('FloatImage.html')`. I'm pretty sure that should work, if not we can look further into this.
