### ISSUE TITLE
heatmapwithtime show map only

### ISSUE THREAD

**Issue by Jinghaoma** [python-visualization/folium#1257]
#### Please add a code sample or a nbviewer link, copy-pastable if possible
https://github.com/python-visualization/folium/blob/master/examples/HeatMapWithTime.ipynb

Python 3.6.10

#### Problem description
I tried running the example script in jupyter lab,
Only the map is displayed, the heatmap is not displayed, any suggestions?

Thank you
#### Output of ``folium.__version__``
folium.__version__
'0.10.1'

**Comment by Conengmo** [comment]
We did some fixes recently, can you install folium from the git master branch and try again? I'm pretty sure that should fix your issues. If not we can reopen the issue. In that case please include the output of your browser console.

**Comment by Jinghaoma** [comment]
Yes, according to your suggestions, I can display the heatmap normally after reinstalling from github, thank you very much.

**Comment by Conengmo** [comment]
Good to hear! We'll do a release soon so the changes will be on PyPI.

**Comment by YuanchenZhu2020** [comment]
I have the same problem with the version 0.11.0. And in the example in https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/HeatMapWithTime.ipynb, there is the same problem. Can you give me some advise?
