### ISSUE TITLE
Automatic location / zoom

### ISSUE THREAD

**Issue by themiurgo** [python-visualization/folium#126]
Now that we have `fit_bounds` implemented, we could make the initial `location` parameter optional, and have leaflet automatically figure out an optimal location / zoom to include all the added features (calling fit_bounds on an automatically computed bounding box). This would make plotting some unknown features on iPython notebook quite convenient:

    > fmap = folium.Map()
    > folium.simple_marker(location=...)
       # Here other features get added, and folium keeps track of what's the current bounding box
    > embed(fmap)

Is there any drawback about this behaviour? The only one I can think of, so far, is that it's not so trivial to get the bounding box of a geojson layer.

**Comment by ocefpaf** [comment]
I am :+1: 

I don't see any obvious problems.  @birdage what do think?

**Comment by birdage** [comment]
i like it!

**Comment by ocefpaf** [comment]
And 3 makes a crowd! @themiurgo do you have a PR for that :wink: ?

PS: We should talk about adding you officialy to the project.

**Comment by themiurgo** [comment]
> And 3 makes a crowd! @themiurgo do you have a PR for that :wink: ?

Not yet, but it will come soon. :smile: 

> PS: We should talk about adding you officialy to the project.

Great, hopefully I can be of help!

**Comment by ocefpaf** [comment]
> Great, hopefully I can be of help!

We have only one rule.  Avoid self merges :stuck_out_tongue_winking_eye:

**Comment by themiurgo** [comment]
Makes sense! 2 set of :eyes:  >> 1.
