### ISSUE TITLE
I want to set a marker color base on conditional statement

### ISSUE THREAD

**Issue by muhammadrohailqamar** [python-visualization/folium#1264]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here
 callback = ('function (row) {'
                'var marker = L.marker(new L.LatLng(row[0], row[1]));'
                'var icon = L.AwesomeMarkers.icon({'
                "icon: 'plane',"
                "prefix: 'fa',"
                "var mark_col = (row[2] > 3000) ? 'red' : 'green',"
                "markerColor: mark_col,"
                '});'
```
#### Problem description
It gives does not generate the map.html if i remove the ternary operator then it works fine. But i want to set marker color base on condition How can I achieve it.

[this should explain **why** the current behavior is a problem and what is the expected output.]

**Comment by meenakshi0910** [comment]
hi @muhammadrohailqamar , can  I work on this?

**Comment by Conengmo** [comment]
Need more information to go on here...
