### ISSUE TITLE
Rcolorbrewer no colors for a specific variable

### ISSUE THREAD

**Issue by SaraVerbandt** [python-visualization/folium#1265]
Dear all, 

i have a probably very naive question. I'm trying to make two plots. 1 to color single cell rna data by the variable "CD8new" and the other one to color the cells by the variable "MSI"

```{r}
plot(reducedDims(slingtumsubsetSCE)$UMAP, col = brewer.pal(9,'Set1')[slingtumsubsetSCE$CD8new], pch=16, asp = 1)

plot(reducedDims(slingtumsubsetSCE)$UMAP, col = brewer.pal(9,'Set1')[slingtumsubsetSCE$MSI], pch=16, asp = 1)
```

the first one perfectly colors my CD8 new variable (6 or 7 different factors dependent on the input) whereas the second does not show any colors (2 factors)

Could anyone maybe help?

thanks a lot

**Comment by Conengmo** [comment]
Hi @SaraVerbandt, I'm not sure if you got the right repo... Could you maybe share where you imported those functions from? If I'm not mistake these are not available in `folium`.

**Comment by Conengmo** [comment]
I'm closing the issue since it seems unrelated to folium.
