### ISSUE TITLE
Folium Popup is only displaying the last data retrieve from JSON file.

### ISSUE THREAD

**Issue by linghu258** [python-visualization/folium#1269]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python (SOLUTION)
         m = folium.Map(location=[LAT, LONG], titles="WORLD", zoom_start=17)
        nodeData = os.path.join('exportBuilding.geojson')

       #  Retrieve the data from JSON file and add it into POPUP
        geo_json = folium.GeoJson(nodeData, popup=folium.GeoJsonPopup(fields=['name']))
        geo_json.add_to(m)

```
#### Problem description

In my above codes, it will create a PyQt application with a folium map in it. I am trying to retrieve the "name" from a JSON file such that the popup will display the name of the nodes (buildings). Currently, all nodes(building) when clicked will show a popup of the last data retrieve from JSON file. How do I show the name of the building in the popup respectively ? 

#### SOLUTION
There is a feature in the latest folium called "GeoJsonPopup" where it will retrieve your data form JSON file and display it in pop for each individual node. Hence solving the issue where by all nodes has the same info. See my solution in my main code above.

**Comment by fullonic** [comment]
Hey, what is your folium version?
