### ISSUE TITLE
List of plugins that we would like to see in folium

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#127]
- Leaflet.TimeDimension
- http://esri.github.io/esri-leaflet/
- https://github.com/aparshin/leaflet-GIBS (http://aparshin.github.io/leaflet-GIBS/examples/#2/18.3/13.4)
- https://github.com/heigeo/leaflet.wms
- https://github.com/joergdietrich/Leaflet.Terminator
- https://github.com/perliedman/leaflet-realtime
- http://arthur-e.github.io/Wicket/
- https://github.com/mapbox/leaflet-omnivore
- https://github.com/makinacorpus/Leaflet.FileLayer
- https://github.com/tomaszbrue/leaflet.boatmarker

**Comment by themiurgo** [comment]
Great list, thanks! Isn't wicket redundant, considering Leaflet.Omnivore handles WKT?

**Comment by birdage** [comment]
@ocefpaf ive worked with esri leaflet and wms and i think they would be easy to add, we might need some more functions and classes to support them tho

**Comment by ocefpaf** [comment]
> wicket

I am not a `Wicket` user, but a colleague recommend it to me.  We can probably cross it out.

@birdage Adding just the layer is easy and I do not thing we should support that.  I put it there just remind myself to read the docs and check what else ESRI has to offer.

**Comment by birdage** [comment]
@ocefpaf wicket is great! there are a whole host of esri options that are supported as part of the layer i.e queries.

**Comment by ocefpaf** [comment]
Interesting.  Lets keep it there then!

**Comment by ocefpaf** [comment]
I am closing this for now. I have a lot of work to do already regarding the plugins.
