### ISSUE TITLE
Maximum bins allowed for different color brewer palettes, in choropleth?

### ISSUE THREAD

**Issue by manubhatt3** [python-visualization/folium#1270]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here

```
#### Problem description

Are there maximum no. of bins for different color brewer palettes in choropleth? Because if I am overriding the default 6 bins and setting it to 12, I am getting the message "Check to make sure that it is not a qualitative scheme." with some color brewer palettes.

**Comment by Conengmo** [comment]
Hi, could you share a bit more on what happened please. What was the full error? Can you share a short, self-contained code snippet that produces the same error?
