### ISSUE TITLE
HeatMap doesn't use weights

### ISSUE THREAD

**Issue by ibayer** [python-visualization/folium#1271]
I spend quite some time tracking down this bug. I think it should be fixed or the limitation should be clearly stated in the docs. This is a major time waster and makes a bad impression for this otherwise great package.

This is a major bug coming for the upstream Leaflet.heat project.

- https://github.com/python-visualization/folium/issues/496
- https://github.com/Leaflet/Leaflet.heat/issues/43
- https://github.com/Leaflet/Leaflet.heat/issues/74

#### Problem description

The `plugins.HeatMap` states that the point used to create the heat map can
be weighted.

```
data (list of points of the form [lat, lng] or [lat, lng, weight])
```

However weights are simply ignored. This makes it useless for heatmaps that are based on a few points with different weights.

#### Expected Output

Weight should have impact. Or remove this option from the docs.

**Comment by Conengmo** [comment]
Hi @ibayer , sorry to hear this bug caused you some issues. I opened a PR which applies a patch from the leaflet.heat repo. Can you perhaps help by testing the PR, see if it solves the issue for you?

Alternatively, if we don't get a fix working, we should indeed update the documentation.

**Comment by ibayer** [comment]
@ibayer 

Thanks for looking into this! Sorry, project has moved on and I don't have any code handy to
reproduce / test your fix. When I get the opportunity I'll for sure give folium another shot in the future  but that might take a while.

**Comment by Conengmo** [comment]
No problem, then thanks for the bug report :)

**Comment by MiguelRodriguezAnticona** [comment]
Hi i Have the same problem so far, what is the solution?

**Comment by Conengmo** [comment]
We have a fix pending, I reckon it will be in the next release. In the meantime you could test it out by manually applying it: https://github.com/python-visualization/folium/pull/1282/files

**Comment by MiguelRodriguezAnticona** [comment]
Conengmo this work in R?

**Comment by Conengmo** [comment]
No this is a Python library

**Comment by fcs30** [comment]
Hello! I have the same problem - is the best solution still manually applying it? When is the next released planned for?

**Comment by Conengmo** [comment]
We have a fix pending that I have to finish up. When that's merged you can install folium from the master branch. A new release (v0.12.0) is not yet scheduled, but will follow reasonably soon.

You could help out by testing the fix and reporting if it worked for you: https://github.com/python-visualization/folium/pull/1282

**Comment by rbiele02** [comment]
Still not working correctly. I would expect another output.
Please do try the following code to see the problem:

`m = folium.Map((0.5, 0.5), zoom_start=8, tiles=None)`
`HeatMap( `
`# make five dots with different weights: 1, 2, 3, 4 and 10`
`        data=[(0, 0, 1),`
`            (0.5, 0, 2),`
`            (1.0, 0, 3),`
`            (1.5, 0, 4),`
`            (2.0, 0, 10)] , radius=15).add_to(m)`
`m`

Just on sphere is bigger, there is no continuous gradient between 1 and 10.

**Comment by Conengmo** [comment]
@rbiele02 which folium version are you using?

**Comment by rbiele02** [comment]
Thanks @Conengmo for looking into this!
I am using Version: 0.11.0+19.g46f820e.
Somehow it uses weights, but not correctly. In the attached figure you can see that 4 circles are equally weighted and one has higher intensity. However I would expect something else when choosing the weights 1,2,3,4 and 10.
A similar behaviour can be found for example for weights 0.1, 0.2, 0.3, 0.4, 0.8. The first 4 are equally and only the last has a higher intensity.

<img width="259" alt="Screenshot 2020-08-12 at 14 02 15" src="https://user-images.githubusercontent.com/63854331/90012856-74c47200-dca4-11ea-84db-936c4d5e3060.png">

**Comment by Conengmo** [comment]
Weights in heatmaps can work a bit non-intuitive. I suspect that one value of 10 is so high that the other values are all small relatively. Please try a range where the values are closer together and see how that looks. For example some values between 1 and 2.

We have a test that verifies the behavior when using weights, so I'm fairly sure it's not broken. In it we create four points with weights 1, 1, 1.5 and 2: https://github.com/python-visualization/folium/pull/1282/files#diff-b6e9c94435e2e8e2a966d436a06a52b6R16 The result looks like this: https://github.com/Conengmo/folium/blob/cce48dc1fd46e23fefd84d6011c6a132f08ad006/tests/selenium/test_heat_map_selenium_screenshot.png

**Comment by rbiele02** [comment]
Thanks for the fast response. 
When I use weights of {1, 2, 3, 4, 5} it seems to work.
<img width="486" alt="1_2_3_4_5" src="https://user-images.githubusercontent.com/63854331/90018957-0684ad00-dcae-11ea-8888-e582163d116d.png">

However, when I use {0.1, 0.2, 0.3, 0.4, 0.5} I dont see any effect at all.
<img width="486" alt="0 1_0 2_0 3_0 4_0 5" src="https://user-images.githubusercontent.com/63854331/90018953-05ec1680-dcae-11ea-95ea-6ffc4ed55ae1.png">

Would be nice to know in which range the weights needs to be to see weighting having effect. It might be a good idea to normalise the given weights to the range where it works.

**Comment by Conengmo** [comment]
Can you try {0.5, 1, 1.5} ? Maybe it assumes a minimum weight of 1...

Looking at the plugin documenation it seems to suggest values below 1 are valid: https://github.com/Leaflet/Leaflet.heat

I'm hesitant to do normalization, because I don't think we can determine an optimal range automatically. That depends not only on the weights, but also on the locations of the points, the zoom level and the radius settings.

**Comment by rbiele02** [comment]
{0.5, 1, 1.5} works very well!
{0, 0.5, 1.0} not really. Maybe it needs to be centred around 1? Also {0.8,1.0,1.2} looks reasonable.

I can shift my distribution to have a mean of 1. This might work. 
Thanks a lot!

**Comment by Conengmo** [comment]
I think it's safe to say it assumes a default weight of 1 then.

**Comment by Clemmarchal** [comment]
Hi, I am new to this subject but I've tried playing with the min_opacity and the max_value and this works fine : 

`
m = folium.Map((0.5, 0.5), zoom_start=8, tiles=None)
HeatMap(
# make five dots with different weights: 1, 2, 3, 4 and 10
data=[(0  , 0, 0.1),
      (0.5, 0, 0.2),
      (1.0, 0, 0.3),
      (1.5, 0, 0.4),
      (2.0, 0, 0.5)] , radius=25, blur = 10, min_opacity = 0, max_val = 0.0005).add_to(m)
m
`
It seems that max_value works like a normalisation. So if you want to display value between 1 and 5, you have to put the max_value at 0.005 and so on...

**Comment by Conengmo** [comment]
Note that you're using v0.11.0 and we were talking about the master branch, which contains a fix for heatmaps and changes its behavior slightly. With the fix, `max_val` is deprecated.

**Comment by Clemmarchal** [comment]
Thanks @Conengmo I didn't get it.  Your patch automatically set the max_value depending on the intensity of the data ?
How can I use it ?

**Comment by Conengmo** [comment]
You can install folium with pip from the master branch like this: `pip install git+https://github.com/python-visualization/folium.git`

**Comment by BriceChivu** [comment]
Hello,
As of today (folium 0.12.1), the heatmap is still showing some weird behaviors. Below is an example.
![image](https://user-images.githubusercontent.com/48819468/130003025-315e13e3-66c5-4cb2-a6b9-82736505e0cb.png)
1) Barcelona should be shown "hotter" than Augsburg but they appear to be of the same "heat".
2) NL looks "hotter" than Augsburg and Barcelona even though its weight is only 5 (2+3). My guess is that the importance of the number of locations is overestimated.
![image](https://user-images.githubusercontent.com/48819468/130003276-8696a765-69f3-4712-a2e2-3917a039e7cb.png)

PS: Normalizing the column 'Volume" gives the same results

**Comment by BriceChivu** [comment]
Following my last comment, it seems that there are also different behaviors depending on the zoom of the map (see screenshot below).
![image](https://user-images.githubusercontent.com/48819468/130005245-b9d693d9-139c-4259-8e27-7f905b060e2b.png)
![image](https://user-images.githubusercontent.com/48819468/130005272-c2cae427-c7a2-4b84-a495-71c7447a18a3.png)
![image](https://user-images.githubusercontent.com/48819468/130005293-ba90ef60-9e47-42d3-b5c8-3c5de880e337.png)
![image](https://user-images.githubusercontent.com/48819468/130005352-e9da7a81-bc42-4ecc-8891-271c5e19acd0.png)
