### ISSUE TITLE
TimestampedGeoJson doesn't work with dates before 1970

### ISSUE THREAD

**Issue by SFrinking** [python-visualization/folium#1273]
I'm having a problem with TimeStampedGeoJson not displaying the timeline correctly for dates pre-1970. I get an error "Time not available" when I try it. It does work, however, when I add at least 1 date that is after 1970, but then the scale on the timeline is really fucked up. Does anyone know how to fix this?

**Comment by uli22** [comment]
Can somebody confirm, that TimeStampedGeoJason not works for Dates before 1970 - I have historical dates 1700, 1882 and soon. I want to use them as a Timeslider.

**Comment by erickmattoso** [comment]
Hi guys, any news here? I also have a situation like SFrinking

**Comment by ljhwang** [comment]
We would also like to know if there is a solution or work around?  We get the dates to show up correctly on the timeslider but only dates after 1970 will actually display on the map.

**Comment by sddwt** [comment]
is there any one cares about that :(
I guess I have to do it on my own...

**Comment by Conengmo** [comment]
Duplicate of https://github.com/python-visualization/folium/issues/1205
