### ISSUE TITLE
Issue with folium rendering HTML in notebooks using papermill

### ISSUE THREAD

**Issue by lwasser** [python-visualization/folium#1277]
#### Please add a code sample or a nbviewer link, copy-pastable if possible
Hi Colleagues. 
I'm having some issues with how folium produces html outputs in the JSON of a jupyter notebook.
i posted my issue here in the papermill repo first:

https://github.com/nteract/papermill/issues/482

@mseal suggested that i post here. 

I've been using papermill for a while to execute jupyter notebooks in a CI framework. 

I'm running into an odd (i think?) bug. When i run a notebook with an interactive element that will require an iframe - case in point creating a map using leaflet (folium for python), it seems to be adding some code that makes the output render incorrectly.

I just ran one of my notebooks. Prior to running papermill, the iframe embed looked like this:
The important piece here is that the `src=data:text/html` part is correctly populated in the json.

```
"<div style=\"width:100%;\"><div style=\"position:relative;width:100%;height:0;padding-bottom:60%;\"><iframe src=\"data:text/html;charset=utf-8;base64,

```
So folium renders plots correctly when run in a notebook. HOwever, When I run papermill and execute a notebook using papermill, I get the following below: notice that the src now begins with `about:blank`.

```
"<div style=\"width:100%;\"><div style=\"position:relative;width:100%;height:0;padding-bottom:60%;\"><iframe src=\"about:blank\" style=\"position:absolute;width:100%;height:100%;left:0;top:0;border:none !important;\" data-html=PCFET0NUWVBFIGh0bWw+C
```

@mseal mentioned this could related to something associated with headless execution and browsers. this is a but out of my scope of knowledge but i wondered if you would be willing to help me understand what is happening and what a fix might be?

I am using folium 0.10.1. And am happy to provide any additional information below. I've tried this on mac and linux and get the same results.

Many thanks.
```python
# Your code here

```
#### Problem description

https://github.com/nteract/papermill/issues/482

[this should explain **why** the current behavior is a problem and what is the expected output.]

**Comment by Conengmo** [comment]
Hi @lwasser, this seems related to a change we made fairly recent: https://github.com/python-visualization/branca/pull/66

In short what changed:

Before we would store the map data in iframe `src` field. This lead to issues when map data was large, which affected many users with Chrome.

After the change we store the map data in a data attribute, which are not limited in size. But now we need extra Javascript to load the data.

I don't know about Papermill, but it seems they don't run this part of the code.

A quick fix would be to not use Branca version 0.4.0, but fall back to 0.3.1. And then let's think about what a long term fix could be.

**Comment by lwasser** [comment]
wow @Conengmo THANK YOU for the quick reply. That simple downgrade  fixed our  build (we have a bunch of folium maps failing in various lessons). I think for the time being i'll update our docker container to pin to branca 0.3.1 . And i'll continue to watch this issue for a longer term fix to it.

i'm super appreciative of your help. I was hoping to get some lessons that use folium live by next Wednesday and this fix will do just that for us. I am happy to test any fixes in the future if that would be helpful as well.

**Comment by Conengmo** [comment]
Happy to help :) @MSeal mentioned in the other issue that he might provide some guidance on how we can resolve this, that would be welcome. I'm now thinking we either make rendering with the data attribute work, or we detect that we need to fall back to embedding the data in the `src` parameter.

**Comment by MSeal** [comment]
Ok, so I got a working example going and dug into the topic a bit more. So the content for rendering should all be there, it's just moved as @Conengmo pointed out. The key difference is that the data-html now requires the browser to execute code when rendering to rehydrate the interface with the data extract. If you load a notebook run by papermill with folium outputs and go to File -> Trust Notebook it will reload the page and execute the required extration to render. Before the data was embeded in the html so it didn't need a check to authorize execution.

This was done in Jupyter to prevent malicious javascript injection into your browser by 3rd parties, but it means that rendering a notebook executed in headlesss mode looks like a 3rd party to your browser when it renders the page initially. The same thing occurs for ipywidgets that have javascript components.

It may be worth adding a default html field which says "Click Trust Notebook to render this graph" to help guide people who hit this in the future if the javascript needed is blocked.

**Comment by Conengmo** [comment]
Thanks for looking into this, it's clear now what's going on.

That we now need trust is unfortunate. I don't think we should reverse the change to how we store the map data though. Before it would truncate the data, breaking things unexpectedly.

I do agree we have to inform our users they need to trust the notebooks to be able to see the maps.

- Add this info to our readme or documentation. Is it important enough to show on the readme?

- Add a field at the top of each example notebook. If a user opens one of the example notebooks they currently don't see the output if it's not trusted. Our [nbviewer links](https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/GeoJsonPopupAndTooltip.ipynb) still work fortunately though.

**Comment by Conengmo** [comment]
Or a better idea maybe: change the code where we unpack the data to show a warning if the unpacking failed.

**Comment by MSeal** [comment]
> Or a better idea maybe: change the code where we unpack the data to show a warning if the unpacking failed.

I believe you can output two media types on your display object and make the `plain/text` version say something like "Please make this Notebook Trusted to view: File -> Trust Notebook" might be a nice work-around. Try it out, I think that will work to emit some guidance when the code is not trusted.

**Comment by Conengmo** [comment]
Thanks for helping out with this @MSeal! Much appreciated.

**Comment by lwasser** [comment]
hi there @Conengmo just checking in!! should unpinning the branca version now work given the recent PR? Many thanks!!

**Comment by Conengmo** [comment]
Not yet, we'll first have to make a release. You be notified when that happens by going to the [branca repo](https://github.com/python-visualization/branca) and clicking the 'Watch' button.

Also note that we haven't really solved the issue. Instead we now show a message that the user should click to trust the notebook.

**Comment by lwasser** [comment]
ahhhh ok thank you for the clarification @Conengmo !! i'll watch the branca repo then!! this is all super helpful to know! thanks again!

**Comment by Conengmo** [comment]
For any future readers: we released this in [branca 0.4.1](https://github.com/python-visualization/branca/releases/tag/v0.4.1). You'll need to re-execute your notebooks to see the message.

**Comment by Vishvajitindurkar** [comment]
Map not showing for me. . A message showing "Make this Notebook Trusted to load map: File -> Trust Notebook". Does anyone know where to turn this setting on?

**Comment by lwasser** [comment]
hi there @Conengmo and @MSeal ! i've run  into  this issue  again of  folium maps not rendering and wanted to check in. @MSeal this actually also relates to nbconvert. 

I have a student who created a folium map in a notebook and wants to export to html. I've been showing them to use nbconvert to  export the notebook at the command  line and how to hide code cells and such.

What is happening is that when they save as html from jupyter, the folium map  renders just fine in the output html or  this is  what they told me. When they export to html from the CLI using  nbconvert  directly and the html_embed option to ensure graphics are embedded , we get a Notebook not trusted  message.

What i don't understand about this is that the notebook they showed me  was  "trusted" when viewed in  Jupyter. And they aren't running the  notebook  using papermill which is what i  was originally doing here. 

I can't seem to recreate this issue on my computer but i  saw a screenshare where  it didn't work on theirs. Any ideas how  we  might fix this? pinning branca to the 0.3.1or is there something  else we can  try? many thanks for any ideas.

**Comment by Conengmo** [comment]
I'm not sure about what happened there.

What I do know is that @dstein64 in his original work on the map dehydration talked about using `srcdoc`, which would mean we no longer rely on JS for that part. We didn't use it at the time, because browser support was still spotty. Now we're 1.5 to 2 years later and all current versions of the major browsers do support `srcdoc`. So maybe the time is right to try that out instead.

**Comment by MSeal** [comment]
So the export from the Notebook UI is sending a pre-populated notebook with it's post-javascript results embeded in the output. In the papermill / (sometimes) nbconvert path if you're re-executing the notebook there's no javascript to resolve the JS state into visual outputs if the component relies on JS to finalize rendering. It only populates the data the widget provides for a JS session to rehydrate the component. I'm guessing this difference is the root cause for the rendering differences @lwasser described.

**Comment by lwasser** [comment]
ahhh  ok thank you both @Conengmo and @MSeal i think  i generally understand what you are saying. So if nbconvert is rerunning the notebook  it could cause issues with the JS  state.

The good news is that my student just updated their entire environment and now folium is exporting as expected. So perhaps it was a package version issue. this is all good to know for the future as conversion issues come up. these interactive elements that use JS seem to be a bit tricky when you are exporting to html!

**Comment by dstein64** [comment]
> "What I do know is that @dstein64 in his original work on the map dehydration talked about using srcdoc, which would mean we no longer rely on JS for that part. We didn't use it at the time, because browser support was still spotty. Now we're 1.5 to 2 years later and all current versions of the major browsers do support srcdoc. So maybe the time is right to try that out instead."

@Conengmo, I've opened PR https://github.com/python-visualization/branca/pull/96 that updates `_repr_html_` to use a `srcdoc` attribute for the `iframe`. That was the approach I was originally using for a dashboard prior to submitting PR https://github.com/python-visualization/branca/pull/66, but the dashboard didn't work for one of the users, who was using Edge or IE. Coincidentally, it looks like Edge added support for `srcdoc` in January 2020 (possibly as a result of switching to Chromium for its engine), shortly after that PR was opened.
