### ISSUE TITLE
Mapbox API key showing in LayerControl

### ISSUE THREAD

**Issue by CriticalWill** [python-visualization/folium#1284]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
map = folium.Map(location=[31.35, -92.5], 
    zoom_start=6, tiles='https://api.mapbox.com/styles/v1/criticalwill/ck8rney4s1cv71iou4hb9va24/tiles/256/{z}/{x}/{y}@2x?access_token=_____________________________', 
    attr='<a href=https://www.mapbox.com/about/maps/>© Mapbox</a> | <a href=http://www.openstreetmap.org/about/>© OpenStreetMap</a> | <a href=https://www.mapbox.com/map-feedback/#/-74.5/40/10>Improve this map</a>',)
```
```
```
#### Problem description
My Mapbox api key is being written to the LayerControl and displayed on the map. 

#### Expected Output
I really want a solution that doesn't show the api key in the html file at all, but ESPECIALLY not in the legend.

#### Output of ``folium.__version__``
0.10.1

**Comment by Conengmo** [comment]
Hi @CriticalWill,  there's no way to keep the key out of your html file. But I understand you don't want it showing in the legend.

When you create a `Map`, under the hood it adds a `TileLayer` instance. If you want to do more advanced things, you can skip this step and add a `TileLayer` yourself. You could do that and give a custom name without the key in it:

```
m = Map(tiles=None)
TileLayer(tiles='<url>', name='my tiles without key', attr='my attr').add_to(m)
```

**Comment by CriticalWill** [comment]
Heya @Conengmo, 
Thanks for the response. That solution doesn't appear to work at all. I get a blank base map with only my point features showing.

```
map = folium.Map(location=[31.35, -92.5], zoom_start=6, tiles=None)
TileLayer(tiles='<https://api.mapbox.com/styles/v1/criticalwill/ck8rney4s1cv71iou4hb9va24/tiles/256/{z}/{x}/{y}@2x?access_token=myAPIkey>',name='BaseMap', 
    attr='<a href=https://www.mapbox.com/about/maps/>© Mapbox</a> | <a href=http://www.openstreetmap.org/about/>© OpenStreetMap</a> | <a href=https://www.mapbox.com/map-feedback/#/-74.5/40/10>Improve this map</a>',)
```

**Comment by Conengmo** [comment]
Oh sorry, that url is supposed to be without `<>`. That was confusing. Can you try again?

```
m = Map(tiles=None)
TileLayer(tiles='https://....?accesstoken=mykey', name='my tiles without key', attr='my attr').add_to(m)
```

**Comment by Conengmo** [comment]
Maptiler looks great by the way, thanks for the suggestion. I don't suppose there's anything we have to do in folium to support it?

**Comment by CriticalWill** [comment]
I tried the url both ways with and without tags and neither worked. No, there's nothing folium needs to do to support it. They are leaflet contributors, so as long as the raster tiles api is used it should work fine within the `tiles =' ' `such as the way I used it:
```
map = folium.Map(location=[31.35, -92.5], zoom_start=6, tiles='https://api.maptiler.com/maps/darkmatter/256/{z}/{x}/{y}@2x.png?key=HmFDBGna8Uvh3s7BdfxN',
    attr='<a href=https://www.maptiler.com/copyright/>© MapTiler</a> | <a href=http://www.openstreetmap.org/copyright/>© OpenStreetMap contributors</a>')
```

**Comment by Conengmo** [comment]
Happy to help. Did it maybe not work for you because you didn't add the tilelayer to the map? I'll write it out differently:

```
m = Map(tiles=None)
TileLayer(
    tiles='https://etc...',
    name='my tiles without key',
    attr='my attr'
).add_to(m)
```

**Comment by CriticalWill** [comment]
That very well may be the reason. I'll add that when back at my desk and post in the issue log.

Thanks!

⁣Michael Williams
Consultant
(337) 405-9987

- sent via mobile device​


-------- Original Message --------

**Comment by CriticalWill** [comment]
That fixed it up!! Thanks again for everything. Great work in this module, by the way!! 

If I can ever do anything to help your team, please don't hesitate to reach out!

**Comment by Conengmo** [comment]
Happy to hear that worked :)
