### ISSUE TITLE
 GeoJsonPopup not found

### ISSUE THREAD

**Issue by davidggphy** [python-visualization/folium#1290]
I'm trying to add popups to a map with geojson boundaries, like in this example

https://github.com/python-visualization/folium/blob/master/examples/GeoJsonPopupAndTooltip.ipynb

but I cannot find the class `GeoJsonPopup`, neither in `folium` nor in `folium.features`.

#### Output of ``folium.__version__``

0.10.1

**Comment by jtbaker** [comment]
I'm not sure if a release has been made to PyPI since this feature was merged. Try re-installing from source, like this: `pip install git+https://github.com/python-visualization/folium.git`, and then make sure to restart your kernel if in jupyter.

**Comment by davidggphy** [comment]
it worked! thanks @jtbaker

**Comment by Conengmo** [comment]
Thanks Jason. Indeed this feature hasn't been released yet, it will be in version 0.11.0.
