### ISSUE TITLE
 Problem data visualization! Map crashing.

### ISSUE THREAD

**Issue by lucassantoscorrea** [python-visualization/folium#1293]
I speak little English! Question translated by the google translator. Folium too heavy, problem opening browser too much data. 30 thousand locations.

**Comment by Conengmo** [comment]
Hi, there are three things you can try:

- make sure you have the latest version of folium. Try install it from our it master branch.
- if you're using a Jupyter notebook: save your map as html and load it separately. `m.save('myfilename.html')` and open that file.
- if you're using Chrome, try another browser like Firefox.

Other than that there's not much to do I'm afraid.

**Comment by lucassantoscorrea** [comment]
Ok..
