### ISSUE TITLE
How to draw the wind animation using leaflet-velocity?

### ISSUE THREAD

**Issue by ying951** [python-visualization/folium#1295]
#### Please add a code sample or a nbviewer link, copy-pastable if possible
I want to draw a wind animation like this:
https://github.com/danwild/leaflet-velocity
but I don't know how to do with python/Folium, or other method?
I see on the website below that he wants to do this in python, but he/she didn't give the method. 
https://stackoverflow.com/questions/46699194/leaflet-velocity-cannot-read-property-data-of-null
Maybe someone here can help me?
```python
# Your code here

```
#### Problem description

[this should explain **why** the current behavior is a problem and what is the expected output.]

**Comment by ocefpaf** [comment]
That is a usage question about a feature that is not implemented in `folium`. I'm closing this b/c the issue tracker is only for code issue. We do have a gitter channel for users to exchange experience and examples.
