### ISSUE TITLE
Dual Map 

### ISSUE THREAD

**Issue by nicktsad** [python-visualization/folium#1296]
Is it possible somehow to make independent  m.m1 from m.m2  when using folium.plugins.DualMap ?
For example, when I move m1 map, m2 map is also moving. 

Thanks

**Comment by Conengmo** [comment]
That's kind of the whole point of that plugin, so no there's no way to disable that I'm afraid. If that's what you want you could make two normal `Map` objects and embed both in one html file next to each other.

**Comment by nicktsad** [comment]
Thanks for your quick answer!
