### ISSUE TITLE
Add url to popup

### ISSUE THREAD

**Issue by wandeg** [python-visualization/folium#13]
Is there a way to add a url to the popup so that once the popup is clicked it redirects to the url?

**Comment by parsley3** [comment]
I have the same problem. Any other (new) idea...

**Comment by parsley3** [comment]
> 
> 
> I have the same problem. Any other (new) idea...

I found the solution

> 
> 
> In Leaflet, this could only really be handled by attaching an `onClick` handler to the given markers -- I don't think there's anything bespoke in Leaflet itself to handle this case, and as such your best method will probably be to write your own JS and attach it yourself.
> 
> (This should be relatively trivial, but I'd be more than happy to provide you with some code if you'd like.)

I found the solution and it's not that hard! just a line of html code...

**Comment by fullonic** [comment]
Great @parsley3. May you share your solution, so if in the future someone else have the same issue can see it? Thanks

**Comment by parsley3** [comment]
> 
> 
> Great @parsley3. May you share your solution, so if in the future someone else have the same issue can see it? Thanks

This is the code line:
popup="<a href=https://your web address>your comments </a>"
