### ISSUE TITLE
Add width option to _popup_render for cicle_marker

### ISSUE THREAD

**Issue by foebu** [python-visualization/folium#130]
Hello,
I noticed that the `cirle_marker` is missing the `width` option when calling the `_popup_render` method.  The `simple_marker` has it. It would be a simple addition I suppose, and ti might be useful.

Regards,
Francesco

**Comment by birdage** [comment]
@foebu `circle_marker` uses radius instead see http://nbviewer.ipython.org/github/python-visualization/folium/blob/master/examples/folium_examples.ipynb for an example

**Comment by ocefpaf** [comment]
Thanks for reporting this.   It is a low hanging fruit, but I am away from
my laptop for the next 2 weeks.  I will take a look once I get back.
(Unless you want to send a PR ;-)
Em 18/05/2015 10:32, "foebu" <notifications@github.com> escreveu:

**Comment by ocefpaf** [comment]
Andrew, I believe he means the popup and not the marker. Correct?
Em 18/05/2015 10:34, "Andrew Bird" <notifications@github.com> escreveu:

**Comment by birdage** [comment]
@ocefpaf yes, i re-read the question and adjusted me comment.... :smile_cat:

**Comment by foebu** [comment]
I knew I wasn't messing around with git, I would :)

**Comment by foebu** [comment]
Any update on this guys?

**Comment by ocefpaf** [comment]
@foebu thanks for the nudge.  See #157.
