### ISSUE TITLE
Cannot place search plugin in non-default locations

### ISSUE THREAD

**Issue by jjbenes** [python-visualization/folium#1302]
#### Please add a code sample or a nbviewer link, copy-pastable if possible
See https://nbviewer.jupyter.org/github/jjbenes/covid19/blob/master/jupyter/covid19_jhu_csse.ipynb#Set-up-search-box-for-Folium-maps.

```python
  folium.plugins.Search(
      layer=search_geo,
      position='topright',
      geom_type='Polygon',
      placeholder='Search for a State or a County',
      collapsed=True,
      search_label='Combined_Key',
      weight=1,
  ).add_to(folium_map)
```
#### Problem description
The `position` argument of `plugins.Search` has no effect unless `geom_type == 'Point'`. Not sure why this constraint is needed. I use `geom_type` `Polygon` in my GeoJSON.

See line 57 in `search.py`: https://github.com/python-visualization/folium/blob/v0.10.1/folium/plugins/search.py#L57.

#### Expected Output
Once I moved line 57 (`position:'{{this.position}}',`) out of the if statement and put it right after line 51 (`textPlaceholder: '{{this.placeholder}}',`) , I was able to move the search box to the top-right corner.  Please let me know if this is the right approach.    

![Screen Shot 2020-04-19 at 5 50 09 PM](https://user-images.githubusercontent.com/62985029/79704432-4be81f00-8266-11ea-8201-3488df1a6414.png)

#### Output of ``folium.__version__``
0.10.1

**Comment by Conengmo** [comment]
That's a bug, good find! Seems like it's been that way since the beginning. Do you want to open a PR with your fix?
