### ISSUE TITLE
error in displaying the resultant map in web browser.it seems blank with zoom button and a link for leaflet in the right bottom corner

### ISSUE THREAD

**Issue by rashadkp** [python-visualization/folium#1306]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here
from __future__ import print_function # this line adds compatibility to python 2
import numpy as np  # useful for many scientific computing in Python
import pandas as pd # primary data structure library
from IPython.display import display
import folium
import _json
import json

df_can = pd.read_excel(r'C:\Users\DELL\Desktop\Book1.xlsx',
                     sheet_name='Sheet1')


india_map = folium.Map(zoom_start=2,tiles='Mapbox Bright')
india_geo=r'https://raw.githubusercontent.com/deldersveld/topojson/master/countries/india/india-states.json'
india_map.choropleth(
    geo_data=india_geo,
    data=df_can,
    columns=['STATE', 'COUNT'],
    key_on='feature.properties.name',
    fill_color='YlOrRd',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='COVID COUNT'
)
display(india_map)
india_map.save("mymap1.html")
![folium](https://user-images.githubusercontent.com/63586227/80129208-60088500-85b4-11ea-9aaa-2b996e9c248f.JPG)


```
#### Problem description

[this should explain **why** the current behavior is a problem and what is the expected output.]

**Comment by CriticalWill** [comment]
@rashadkp right away, I can see you are trying to use the Mapbox Bright tile set. That tile set is no longer supported in folium unless you signup with Mapbox for an account. Be advised that your Mapbox api key will be displayed in your html and can be pirated and used by others without your knowledge which you'd be on the hook for paying for. I'd recommend signing up with Maptiler (free) that offers a much larger range of tile sets and gives fairly detailed guidance on using in your code. For how I worked through it, 
For more info on how I worked through a similar issue see #1284. @Conengmo walked me through it and no need to pull them away from other issues that might be pressing.

**Comment by rashadkp** [comment]
this codes helped me to display the map.but it doesnt give me the chloropeth map based on the data.

**Comment by CriticalWill** [comment]
@radumas , glad this helped displaying the tile set. I'm relatively new to python, but happy to help. If you'd like to give a link to your data set or drag/drop in your comment window, I can have a look at the choropleth issue.

**Comment by rashadkp** [comment]
[Book1.xlsx](https://github.com/python-visualization/folium/files/4529417/Book1.xlsx)
@CriticalWill this is the data i needed to plot on chloropleth map.

**Comment by CriticalWill** [comment]
Ok, @rashadkp like I said; I'm no expert with python or folium, but I am pretty handy with geographic/GIS data. Just looking at your excel file and the geojson data, I would think that the two would need to be joined before the choropleth map could be generated. I'm not sure how to do that in python as it beyond my current knowledge base. 
You may try to hit up the [GIS stack exchange](https://gis.stackexchange.com/) and **close this issue** as this looks more like a python coding issue than an issue with folium. I would add that the way I am familiar with adding geodata with folium is with by using the `.GeoJson` class. After you figure out how to join your excel data you should be able to generate the choropleth map using code similar to something like this:
```

geodata = folium.FeatureGroup(name='India Geo')

geodata.add_child(folium.GeoJson(data=open(
            'https://raw.githubusercontent.com/deldersveld/topojson/master/countries/india/india-states.json',
            r, encoding='utf-8-sig').read(),
            style_function=lambda x: {
                'fillColor':'#ffeda0' if x['properties']['COUNT'] < 10
                else '#fed976' if >=10 and < 500
                else '#fd8d3c' if >=500 and < 2000
                else '#e31a1c' if >=2000 and < 4000
                else '#800026' if >=4000
                } 

)))
india_map.add_child(geodata)
india_map.add_child(folium.LayerControl())
display(india_map)
india_map.save("mymap1.html")
![folium](https://user-images.githubusercontent.com/63586227/80129208-60088500-85b4-11ea-9aaa-2b996e9c248f.JPG)
```

**Comment by rashadkp** [comment]
@CriticalWill Thank you for the response
