### ISSUE TITLE
Can't customize name for default layer

### ISSUE THREAD

**Issue by fallish** [python-visualization/folium#1316]
I'd like to customize the name for default layer, and write code as below:

```python
import folium

m = folium.Map(tiles='OpenStreetMap', location=[41, -70], zoom_start=5, name='OSM')


folium.raster_layers.TileLayer(
    tiles='http://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',
    attr='google',
    name='Google Maps',
    max_zoom=20,
    subdomains=['mt0', 'mt1', 'mt2', 'mt3'],
    overlay=False,
    control=True,
).add_to(m)

folium.LayerControl().add_to(m)

m

```
#### Problem description
The default layer name always is  lower case "openstreetmap" , which is not my expected name "OSM". 
![image](https://user-images.githubusercontent.com/1809740/80553893-019d3580-89fe-11ea-8bd6-747665015b44.png)

#### Expected Output
Add the ability to customize name for default layer.

**Comment by Conengmo** [comment]
Hi @fallish , the way to do this is to disable the default layer and only add custom layers.

```
m = Map(tiles=None)
folium.raster_layers.TileLayer(tiles='openstreetmap', name='my name').add_to(m)
```

**Comment by aleks-mariusz** [comment]
as per the refernced comment above, this is not an acceptable solution.. this case should be re-opened to create a proper workflow for those wanting to customize the name (such as the case in issue #1033 where the full url defaults to showing up in the layer control with no way to (properly) fix that)
