### ISSUE TITLE
Searchbar for cities

### ISSUE THREAD

**Issue by WBP20** [python-visualization/folium#1321]
Hi

I displayed on the map an important list of suppliers all over the country (France), I need to search for cities and zoom in in order to see which suppliers are around. 

So beside my list of suppliers I got a json list of all cities of France with names and coordinates, I display them with the search plugin, and add layer control in order to hide the markers.
```

with open('villes.json') as fp:
   points = ``json.load(fp)
       
geojson_obj = folium.GeoJson(points, show=False).add_to(m)
plugins.Search(geojson_obj, geom_type='Point', placeholder="Search", collapsed=True, search_label='Ville', search_zoom=20, position='topleft').add_to(m)
folium.LayerControl().add_to(m)
m.save(map.html)
        
```
But I face two problems :
- As they are about 35k cities, the map takes some much time to load
- We still have the option to show markers in the LayerControl, and if it is activated, this is the end...

Could it be possible to solve both problems ?

Or could it be possible to add external search plugin from Openstreetmaps for instance?

**Comment by Conengmo** [comment]
I don't understand your second question, what do you mean there?

As for the number of points making the search slow, I'm afraid there's not much to do about that in folium. Also I can't really help you with alternative technologies.

**Comment by WBP20** [comment]
Maybe I found a clue.

A kind of plugin exists for Leaflet:
https://github.com/perliedman/leaflet-control-geocoder
démo : https://www.liedman.net/leaflet-control-geocoder/

Could we also add it to Folium ?

**Comment by Conengmo** [comment]
That's a pretty cool plugin. And it seems easy to use. It's a possible candidate for being included in folium. Note that folium is maintained by volunteers, so someone has to make this. Read more about this process here: https://github.com/python-visualization/folium/blob/master/.github/CONTRIBUTING.md#plugin-acceptence-criteria

**Comment by WBP20** [comment]
I wish I could contribute to make this plugin viable for folium, but I have no idea how to do this, my programming level is way too poor. Should I open a PR if I can't contribute by coding? How could I help ?

**Comment by Conengmo** [comment]
You could copy one of our existing plugins and see if you can change it into this one. But if you don't get it to work or you don't have the time don't worry, someone else might pick this up.

**Comment by WBP20** [comment]
https://github.com/WBP20/control-geocoder/blob/master/control-geocoder.py

I just hada  look to other plugins and try to copy has much as I can. But I have mostly not idea of what I am doing.

**Comment by Conengmo** [comment]
That's not bad at all. To get it to work you can remove all the parameters in `__init__(self)` and `parse_options` and just go with the default options for now.

**Comment by WBP20** [comment]
I removed those parameters ands then I added control_geocoder.py to plugins folder and added
`
from folium.plugins.control_geocoder import LocateGeocoder `

to the _init_.py

then In my map.py I used 

```
from folium.plugins import LocateGeocoder
...
 LocateGeocoder().add_to(m)
```

And it actually worked, thank you so much.

I need to settle some options now. What could I do next in order to allow modifying parameters ?

**Comment by Conengmo** [comment]
> And it actually worked

🎉 

For options you were quite right in your first try. Put then in `__init__`, then in `self.options` using `parse_options`.

You don't have to include all the options, for example the `geocoder` option is kind of hard to do so let's skip that one.

Another thing that's useful is to only put the most important options in the `__init__` as named arguments. Then also add `**kwargs` and pass those into `parse_options` as well. That way, power users can put in any option they want, but for more novice users the list of named options is limited to only what they probably need. See for example https://github.com/python-visualization/folium/blob/master/folium/plugins/pattern.py

**Comment by WBP20** [comment]
I wrote all options as in my first try, just removing geocoder one.

I changed template to : 

```
    _template = Template(u"""
        {% macro script(this, kwargs) %}
            L.Control.geocoder({{this.options|tojson }}).on('markgeocode', function(e) { 
         {{this._parent.get_name()}}.setView(e.geocode.center, 11
       ); }).addTo({{this._parent.get_name()}});
        {% endmacro %}
        """)
```

Tried : `LocateGeocoder(placeholder="Rechercher une ville", defaultMarkGeocode=False).add_to(m)`

And it works exactly as I expected. Thank you so much helping me solving my issue !

Corrected file is available here https://github.com/WBP20/control-geocoder/blob/master/control_geocoder.py

Do you want me to create a PR or correct more things ?

**Comment by Conengmo** [comment]
Please open a PR with this. To make it mergable I require some more changes. If it's okay with you I can add these to your branch directly, that's easier than going back and forth.

Side note: we'll have to add some lines about the OSM/Nominatim usage limits and maybe also add it to the map attribution.

**Comment by WBP20** [comment]
Of course you can add it to my branch, should I allow something ? 
Should we make changes before I open the PR ?

**Comment by Conengmo** [comment]
You can open the PR, by default is 'allow editing by maintainers' enabled.

**Comment by Conengmo** [comment]
The PR has been merged. Thanks for your contribution on this one @WBP20!

**Comment by Vsluyters** [comment]
<img width="749" alt="Capture code folium" src="https://user-images.githubusercontent.com/73466405/98368901-62a26780-2038-11eb-9977-bce253a99b21.PNG">
Hey, I've just started coding, so I'm a beginner and I tried to import LocateGeocoder but it doesn't work. Am I doing something wrong ?

**Comment by WBP20** [comment]
Hi Vsluyters,

I guess Conengmo changed plugins' name from "LocateGeocoder" to "Geocoder" whan he merged the PR. 

Try: `from folium.plugins import Geocoder`

**Comment by AusiasMarch** [comment]
Hi everybody,

First, I would like to thank @WBP20 and @Conengmo for their work with this plugin; it is exactly what I need. I've been able to use it with no problem.

I have a doubt about its usage, though. As I understand, the original leaflet plugin has support for the Google Geocoder.

- Does this folium implementation also have support for it?
- If so, how can I use it?
- If it does not have, any pointers on how can I modify it to achieve it?

Many thanks!

**Comment by WBP20** [comment]
Hi,

Don't think it could work like that. 
maybe try first to make it to work on leaflet : 

`L.Control.Geocoder.google('<you API key>', { ... other options ... });`

then, modify the "template" part in 
https://github.com/python-visualization/folium/blob/master/folium/plugins/geocoder.py

To add directly to L.Control.geocoder(({ this.optiontojson })).on...

something like L.Control.geocoder.google('<your API key')(({this.optiontijson})).on...

**Comment by AusiasMarch** [comment]
I'll try that. Thanks!

**Comment by ausiasdribia** [comment]
With a colleague's help, I've managed to alter the Geocoder class in order to use the Google Maps geocoding service. I'll leave the code here just in case someone has the same problem.

```python
class GGeocoder(folium.plugins.Geocoder):
    """A simple geocoder for Leaflet that by default uses OSM/Nominatim.

    Please respect the Nominatim usage policy:
    https://operations.osmfoundation.org/policies/nominatim/

    Parameters
    ----------
    collapsed: bool, default False
        If True, collapses the search box unless hovered/clicked.
    position: str, default 'topright'
        Choose from 'topleft', 'topright', 'bottomleft'
        or 'bottomright'.
    add_marker: bool, default True
        If True, adds a marker on the found location.

    For all options see
        https://github.com/perliedman/leaflet-control-geocoder

    """

    _template = Template(
        """
        {% macro script(this, kwargs) %}
            options = {{ this.options|tojson }}
            options.geocoder = L.Control.Geocoder.google({"apiKey": options.apiKey})
            L.Control.geocoder(
                options
            ).on('markgeocode', function(e) {
                {{ this._parent.get_name() }}.setView(e.geocode.center, 11);
            }).addTo({{ this._parent.get_name() }});

        {% endmacro %}
    """
    )

    def __init__(self, collapsed=False, position="topright", add_marker=True, **kwargs):
        """Init the class."""
        super(GGeocoder, self).__init__()
        self._name = "Geocoder"
        self.options = parse_options(
            collapsed=collapsed,
            position=position,
            defaultMarkGeocode=add_marker,
            apiKey=o_settings.GOOGLE_API_KEY,
            **kwargs,
        )
```

Many thanks for your help!
