### ISSUE TITLE
GeoJsonTooltip: "permanent" option is not supported

### ISSUE THREAD

**Issue by TatianaSnauwaert** [python-visualization/folium#1328]
**Describe the bug**
Following the [documentation](https://python-visualization.github.io/folium/modules.html#folium.features.GeoJsonTooltip) I tried to pass the Leaflet tooltip option **["permanent"](https://leafletjs.com/reference-1.6.0#tooltip-permanent)** using the **kwargs. The error message states:
AssertionError: The `permanent` option does not work with GeoJsonTooltip.

**To Reproduce**

The reproducible code can be found in this [Kaggle kernel](https://www.kaggle.com/tatianasnwrt/tooltip-permanent-option-bug?scriptVersionId=33856028) (including the data to test on). You just need to copy my kernel and you will be able to edit and copy the code.

**Expected behavior**
I was trying to permanently display some text (district number) on the map. I expected that this Leaflet.tooltip option would fix this issue. I couldn't find any other way to permanently display text like that, please let me know if there is one. 

**Environment (please complete the following information):**
 - Browser: Chrome;
 - Kaggle environment;
 - folium version: 0.10.1 (please let me know if it was already implemented in the latest version, on Kaggle I am unable to use it).

**Comment by Conengmo** [comment]
Hi @TatianaSnauwaert, in short: you can't use `permanent` with `GeoJsonTooltip`. That error message is gone in v0.11.0 but the functionality still doesn't work.

PR's are welcome to fix that. Currently we call `bindTooltip` on the GeoJson object, but instead we could call it on each feature like described here: https://stackoverflow.com/questions/44692370/how-to-add-permanent-labels-to-each-feature-in-a-geojson-layer.

**Comment by TatianaSnauwaert** [comment]
Thanks for the reply! I wish I could help but I'm afraid my programming level is insufficient for the task...
Let me know if I can help with anything else but programming here :)
And thanks for your efforts, they are much appreciated!
