### ISSUE TITLE
Draw plugin export button does not work in Microsoft Edge

### ISSUE THREAD

**Issue by and-viceversa** [python-visualization/folium#1329]
**Describe the bug**
Draw plugin export button does not work in Microsoft Edge. When you mouse over the export button, Edge shows you the correct`data:` URL, but nothing happens when you click. No hints populating in the Developer Tools console or debugger.

**To Reproduce**
As far as I can tell, this bug happens in the base case.

```
import folium
from folium.plugins import Draw

m = folium.Map(
    location=[32, -109]
)

d = Draw(
    export=True
).add_to(m)

m.save('index.html')
```

**Expected behavior**
You should get the download prompt, as in other browsers.

**Environment (please complete the following information):**
 - Browser: Microsoft Edge
 - Jupyter Notebook or html files? HTML
 - folium version: 0.10.1

**Additional context**
I think what's going on is related to [this](https://stackoverflow.com/questions/33154646/data-uri-link-a-href-data-doesnt-work-in-microsoft-edge) SO issue. Edge doesn't allow `data:` URLs. See context from Mozilla [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs).

This is the issue in draw.py
```
            {% if this.export %}
            document.getElementById('export').onclick = function(e) {
                var data = drawnItems.toGeoJSON();
                var convertedData = 'text/json;charset=utf-8,'
                    + encodeURIComponent(JSON.stringify(data));
                document.getElementById('export').setAttribute(
                    'href', 'data:' + convertedData                    <-----------
                );
                document.getElementById('export').setAttribute(
                    'download', {{ this.filename|tojson }}
                );
            }
```

From SO:

> The only solution is to link, using a scheme that is supported such as file:// or http://, to some resource that contains the content.

**Possible solutions**
Since the GEOJSON is generated by drawing, I'm not sure how you could link that to existing content using file:// or http://

folium is maintained by volunteers. Can you help making a fix for this issue?
If someone points me to the correct way in Edge, I will try.

**Comment by Conengmo** [comment]
This indeed doesn't work in older version of Edge. The newer, Chromium based version does have this functionality though. As far as I know it will be gradually rolled out. You can already get it here: https://www.microsoft.com/en-us/edge

Since I don't think there's any action we have to take with folium I'm closing the issue.
