### ISSUE TITLE
Raster display: set no data values and colour

### ISSUE THREAD

**Issue by Instatarama** [python-visualization/folium#1332]
I am rendering a raster with valid values between 0-2000, and a no data value of -9999. It would be great if I could set the no data value so that: 
- Folium will not render it, or I can set it to be transparent/a colour. 
- The scale would be between 0-2000 with a no data value of -9999, instead of -9999-2000. 

So far I have been trying to build a new colourmap with a transparent colour for values < 0. This has strange outcomes in Folium such as all valid values rendering white (seen here on cartoDB positron background in off-white).

![image](https://user-images.githubusercontent.com/54163162/82279996-2ec37f00-99d1-11ea-9d4e-7b2c5b6a7879.png)

When I use a matplotlib colourmap no data values render white and valid values are all the same colour, they're compressed into a tight band on the colourmap. 

![image](https://user-images.githubusercontent.com/54163162/82280752-f1f88780-99d2-11ea-8a85-d2eeef84d7d9.png)

Any solutions or updates to address these issues would be greatly appreciated. Folium is such an easy-to-use tool for data vis in Python.

**Comment by Conengmo** [comment]
Can you share a code snippet of what you're doing? I currently don't know what classes you are using or how your data looks like.
