### ISSUE TITLE
Wrap the "Filter Leaflet Maps with a Slider" technique in folium

### ISSUE THREAD

**Issue by Gdsimms** [python-visualization/folium#1334]
**Is your feature request related to a problem? Please describe.**

My (mostly marker-based) data sets contain many LayerControl layers but also have lots of points per layer that I would like to filter by a value range. The value range might be any scalar property of the data, but I'm only interested in doing this for one value at a time, **without altering the existing layers**.

**Describe the solution you'd like**

I found [this javascript "**Filter Leaflet Maps with a Slider**" solution](https://digital-geography.com/filter-leaflet-maps-slider/) but I really need to work in python and folium just wraps leaflet anyway so I don't expect adding this will be too difficult.

I don't have a strong preference about API details, but some way to create and bind the slider to a new kwargs property of fo.CircleMarker, fo.RegularPolygonMarker, etc. and filter before drawing would be great. I would expect the filter to apply to all layers equally. 

Naturally, as one moves the slider, the marker elements should be dynamically drawn and erased from the map as they are included or excluded from the filtered range.

**Describe alternatives you've considered**

I've tried working with TimestampedGeoJson, treating the filtered values as time and selecting a spot on a timeline and changing the duration parameter, but in addition to that awkwardness that puts all the affected data points in the same layer. 

**Additional context**

**Implementation**

I can get by in python, but I'm not great. I'd need some examples of what it means to "wrap" leaflet.js to create usable and robust folium functions, and I really don't know javascript at all.

**Comment by Conengmo** [comment]
Nice tutorial you linked to. I think it's a bit too much to fully include it in folium. If there was a Leaflet plugin with this functionality we could wrap it. Alternatively you could make and host a folium plugin yourself and we could link to it.

I'll give some tips that might help. Note that you can add custom JS and html:

```
from branca.element import Element, JavascriptLink, CssLink

m = folium.Map()
element = Element('alert("hi there");')  # this contains Javascript
figure = m.get_root()
figure.script.add_child(element)

figure.header.add_child(JavascriptLink('https://www.example.com/cdn-js-resource/))
figure.header.add_child(CssLink('https://www.example.com/cdn-css-resource/))
```

You can refer to other Leaflet objects like this:

```
marker = folium.Marker((0, 0)).add_to(m)
element = Element('alert("marker name in JS: {}");'.format(marker.get_name()))
```

I'm closing this issue because though I would be open to wrap it or link to it as a plugin, I don't think we should host this functionality in folium.

**Comment by kerrick-lyft** [comment]
FWIW, there is an existing Leaflet plugin that does this: https://github.com/dwilhelm89/LeafletSlider
