### ISSUE TITLE
plot a graph of the value of an element in the popup.

### ISSUE THREAD

**Issue by LaurianoElmiroDuarte** [python-visualization/folium#1336]
**Is your feature request related to a problem? Please describe.**
insert a graphic in the popup based on dynamic coordinates with just one cell of the dataframe.

**Describe the solution you'd like**
follow the code below:
# load built-in dataset as a pandas DataFrame
graf = col

scatter = Chart(graf).mark_circle().encode(
    x='ResultUnity',
    y='Al',
    color='Al',
)

vega = folium.features.VegaLite(
    scatter,
    width='100%',
    height='100%',
)

qualquercoisa = folium.Map([-23.858017, -46.156517], zoom_start=14)

for counter in range(147):
  marker = folium.CircleMarker(
  location=[data.latitude[counter],data.longitude[counter]],
  tooltip=data['region'][counter],
  radius=2, 
  color='#000000',
  fill=True,
  fill_color='#000000'
  )

  popup = folium.Popup()
  vega.add_to(popup)
  popup.add_to(marker)
  marker.add_to(qualquercoisa)

qualquercoisa

**Describe alternatives you've considered**
implement counters for dataframe values and counters for folium values.Marker ()

**Additional context**
My problem is to have the element value of all coordinates.

**Implementation**
folium is maintained by volunteers. Can you help make a PR if we want to implement this feature?
When I have the solution I will implement that solution.
HELP ME .

**Comment by Conengmo** [comment]
I'm sorry but I don't really understand what you're asking here. Currently you'll have to create the graphs to embed in each popup individually. I don't think having some automatic graph creating using pandas dataframes is within the scope of folium. You can use the Altair library to generate graphs.
