### ISSUE TITLE
Basemaps not showing up by default

### ISSUE THREAD

**Issue by NatalieThurlby** [python-visualization/folium#1340]
Thank you for this package, I'm finding it useful :)

## Problem:
I am having a problem related to this, where I'd like to have 4 different options of base maps which aren't named in folium, and have one of them show by default when the map is loaded.

They all have ugly tile strings. If I load them all using `folium.TileLayer` (similar to [this issue](https://github.com/python-visualization/folium/issues/1189)), then there is no base map by default.

Is there any current way around this?

## How it might work?
It would be good if you could decide with TileLayer if the base map should be shown by default. The `show` attribute seems like the obvious choice. I would guess that it wouldn't cause problems for old versions of the code if it only worked if there wasn't already a base map which is going to be shown, but any way that it could work would be great.

**Comment by NatalieThurlby** [comment]
Sorry, I see that this is already pretty much how it works.

In case this is ever useful to anyone else:
The problem was that I save my map twice (which is a weird thing to do, I know - I was saving it once as index.md so that it will show up on a github pages page, and also as a html file which I can easily open to look at in my browser), which means that the second time I saves it, all the base maps are switched off).

**Comment by NatalieThurlby** [comment]
Sorry, I see that this is already pretty much how it works.

In case this is ever useful to anyone else:
The problem was that I save my map twice (which is a weird thing to do, I know - I was saving it once as index.md so that it will show up on a github pages page, and also as a html file which I can easily open to look at in my browser), which means that the second time I saves it, all the base maps are switched off).

**Comment by wckoeppen** [comment]
Hi @NatalieThurlby I just ran into this same issue (I think). I want to use two basemaps with custom URLs and custom names, but I want one of those be "on" by default. If I set tiles to None and then use the TileLayer to add my two basemaps and then save it to HTML, no basemap is selected by default. I.e., the map looks blank.

Show = True is only supposed to affect overlays, but I left in in there for "show".

Did you end up solving this problem? I don't think I'm saving my map twice, but thought I'd check.

```
m = folium.Map(
    location=[69, -146],
    tiles = None
)

folium.TileLayer(
    tiles = 'https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/{z}/{y}/{x}',
    attr="USGS - The National Map",
    name="USGS - The National Map - Topo",
    show=True
).add_to(m)

folium.TileLayer(
    tiles = 'https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryTopo/MapServer/tile/{z}/{y}/{x}',
    attr="USGS - The National Map",
    name="USGS - The National Map - Imagery+Topo"
).add_to(m)

folium.LayerControl().add_to(m)

m.save('blank_route_map.html')
```

**Comment by wckoeppen** [comment]
OK, it seems this is the real issue, and it is still open:
https://github.com/python-visualization/folium/issues/1199

In my case, I displayed the map in the notebook, then saved the HTML. If saving the HTML without displaying, the saved file is correct.
