### ISSUE TITLE
Feature to clip layer using shapefile

### ISSUE THREAD

**Issue by lathif106** [python-visualization/folium#1350]
Can we have a facility like clipping layers using shapefiles. I often use folium to plot contour from matplotlib and need to limit these contours to land borders. 

I tried to implement this using the existing solutions in matplotlib but nothing turned to be good to plot a transparent color outside shapefile.

**Comment by Conengmo** [comment]
This is outside the scope of folium. folium is for making maps, not for editing data. I'm sure there are other Python libraries that can edit contours.

**Comment by fullonic** [comment]
@lathif106 maybe you can achieve that using psyshp and shapely
