### ISSUE TITLE
Image overlay slight deviation on map

### ISSUE THREAD

**Issue by lathif106** [python-visualization/folium#1356]
**Describe the bug**
I see there is a little deviation when contour is directly placed on folium map using contour_to_geojson library vs image overlay directly added using the image saved using matplotlib. 

**To Reproduce**
Steps I followed:
1. Geneate contour using plotly and saved it as image. Used this image as overlay on folium.
2. Export same contour to json using Contour_to_geojson and added this json as overlay.

If i enabled both layers at a time, I see little deviation in projection.

**Comment by Conengmo** [comment]
What do you want folium to do here? Sounds like it’s an issue with the conversions that you are doing. I’m closing this issue because it’s not actionable for folium devs.
