### ISSUE TITLE
Issue with Choroplet map 

### ISSUE THREAD

**Issue by jbricenot** [python-visualization/folium#1358]
**Describe the bug**
I have been trying to use the choroplet map to display the data that is attached, but i keep having an error " AttributeError: 'NoneType' object has no attribute 'get'".
I have tried to use different sets of key_on loing in the geojson file, but nothing has worked. I don´t know if something else can also cause this error.

**To Reproduce**
import pandas as pd
import numpy as np
from urllib.request import urlopen
import json
import folium
from folium import plugins

#import file
df_continental=pd.read_csv(r'df_continental.csv')

#import the Portugal Json file
with urlopen('https://raw.githubusercontent.com/deldersveld/topojson/master/countries/portugal/portugal-districts.json') as response:
    portugal_geo = json.load(response)

#Get latitude and longitude of Portugal
Portugalcoordinates=(39.399,-8.224)

#Creation of the choropleth
map1 = folium.Map(location=Portugalcoordinates, zoom_start=6)
map1.choropleth(geo_data = portugal_geo, 
                  name='choroplet',
                  data = df_continental,
                  columns = ['Region', 'N° Empresas'],
                  key_on = 'feature.properties.NAME_1',
                  fill_color = 'YlOrRd', 
              fill_opacity = 0.7, 
              line_opacity = 0.2,
              legend_name = 'count by district')
               
#Add pop-up text to each marker on the map
latitudes = list(df_continental.Latitude)
longitudes = list(df_continental.Longitude)
labels = list(df_continental['N° Empresas'])

for lat, lng, label in zip(latitudes, longitudes, labels):
    folium.Marker([lat, lng], popup=label).add_to(map1)

map1     

[ Include a data sample or link to your data if necessary to run the code ]
df_continental
Region,N° Empresas,Percentual(%),Latitude,Longitude
Aveiro,7378,6.515825914935708,40.644,-8.6455
Beja,1004,0.8866751448353822,38.015,-7.865
Braga,10822,9.557368941641938,41.503,-8.42
Bragança,1238,1.093330507277095,41.805,-6.757
Castelo Branco,1499,1.3238307192313126,39.823,-7.491
Coimbra,3854,3.403631482266497,40.205,-8.419
Évora,1356,1.1975413310724885,38.566,-7.9
Faro,7111,6.280026847534266,37.019,-7.932
Guarda,1376,1.2152041825632331,40.537,-7.265
Leiria,5243,4.630316518298714,39.744,-8.807
Lisboa,27189,24.011763459092837,38.716,-9.133
Portalegre,748,0.6605906457538505,39.291,-7.432
Porto,21453,18.946057651547264,41.149,-8.61
Santarém,3549,3.134272997032641,39.135,-8.405
Setúbal,6400,5.652112477038293,38.524,-8.893
Viana do Castelo,2583,2.2811572700296736,41.644,-8.83
Vila Real,1969,1.7389077292638124,41.295,-7.746
Viseu,3127,2.7615868305779285,40.657,-7.914

**Expected behavior**
Choroplet map with display of colors

**Environment (please complete the following information):**
  - Jupyter Notebook 
 - folium version ('0.10.1')

**Comment by Conengmo** [comment]
Your data is not a geojson object, but a topojson object. In that case you must pass an extra parameter to the `Choropleth` class to tell it where to find the data:

```
folium.Choropleth(
    geo_data=portugal_geo,
    topojson='objects.PRT_adm1',                
).add_to(m)
```

Next time when you share an error message it's useful to add a bit more of the stacktrace: the module and the line number in which the error happened. Like this, as an example:

```
>>> m = folium.Map('wrong input')
Traceback (most recent call last):
  File "<ipython-input-18-235f6caf74c7>", line 1, in <module>
    m = folium.Map('wrong input')
  File "C:\Users\Frank\Documents\GitHub\folium\folium\folium.py", line 250, in __init__
    self.location = validate_location(location)
  File "[...]\folium\folium\utilities.py", line 50, in validate_location
    'instead got: {!r}.'.format(location))
ValueError: Expected two (lat, lon) values for location, instead got: 'wrong input'.
```
