### ISSUE TITLE
TemplateNotFound: leaflet-dvf.markers.min.js

### ISSUE THREAD

**Issue by nygeog** [python-visualization/folium#136]
![screen shot 2015-05-21 at 12 23 00 pm](https://cloud.githubusercontent.com/assets/2790599/7753563/3ac7868c-ffb4-11e4-8171-ad65daa8c2e3.png)

I have the leaflet-dvf.markers.min.js in the folder with the ipynb's - not sure why this error is showing up.

**Comment by themiurgo** [comment]
Duplicate of #132 . Closing.
