### ISSUE TITLE
difference in function and argument naming convention from Javascript API

### ISSUE THREAD

**Issue by xuancong84** [python-visualization/folium#1363]
It seems that the naming conventions of both function name and argument name are different from Javascript API.

Using draw-circle function as an example, on function names:

In Javascript API (see https://leafletjs.com/reference-1.6.0.html#circle ), the function is 
`L.circle([50.5, 30.5], {radius: 200}).addTo(map);`
In Python API (see https://python-visualization.github.io/folium/modules.html ), the function is
`folium.vector_layers.Circle(location, radius, popup=None, tooltip=None, **kwargs)`
The difference lies in the leading-character capitalization, i.e., `circle()` vs `Circle()`.

On argument names, e.g., fill opacity for polygons:
In Javascript API, the argument is _fillOpacity_ , (see https://leafletjs.com/reference-1.6.0.html#path below)

Option | Type | Default | Description
-- | -- | -- | --
stroke | Boolean | true | Whether to draw stroke along the path. Set it to false to disable borders on polygons or circles.
color | String | '#3388ff' | Stroke color
weight | Number | 3 | Stroke width in pixels
opacity | Number | 1.0 | Stroke opacity
lineCap | String | 'round' | A string that defines shape to be used at the end of the stroke.
lineJoin | String | 'round' | A string that defines shape to be used at the corners of the stroke.
dashArray | String | null | A string that defines the stroke dash pattern. Doesn't work on Canvas-powered layers in some old browsers.
dashOffset | String | null | A string that defines the distance into the dash pattern to start the dash. Doesn't work on Canvas-powered layers in some old browsers.
fill | Boolean | depends | Whether to fill the path with color. Set it to false to disable filling on polygons or circles.
fillColor | String | * | Fill color. Defaults to the value of the color option
**fillOpacity** | Number | 0.2 | Fill opacity.

The Python API has no documentation, it says "refers to Javascript API"
`**kwargs – Other valid (possibly inherited) options. See: https://leafletjs.com/reference-1.6.0.html#circle`
But I have tested, all those arguments with capital letters do not work. The Python version is in fact underscore followed by lowercase character, e.g., fillOpacity => fill_opacity, lineCap => line_cap, etc.

The difference in naming convention will cause quite a lot of inconvenience and incompatibility when creating interface for both Python and Javascript. May I know is that idea by design and intentional? Thanks!

**Comment by Conengmo** [comment]
You're right Mark, that's exactly it. For our Python interface we chose to use PEP8, so snake_case. When that's put into JS we transform that into lowerCamelCase.

I do see how the docstring is not explicit on this. We could update that. Or, maybe even better, deal with kwargs that are lowerCamelCase. I think that would require `path_options()` to convert any lowerCamelCase kwargs into snake case before processing them. https://github.com/python-visualization/folium/blob/b70efc6fcae19e471eeca63d2faa59981dbbafb4/folium/vector_layers.py#L16

**Comment by Conengmo** [comment]
This is related to https://github.com/python-visualization/folium/issues/1452. I'll close this one.
