### ISSUE TITLE
I want to know how to use the folium package without the Internet, using only the internal network and internal map services,thanks!

### ISSUE THREAD

**Issue by Nightmare520** [python-visualization/folium#1368]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Implementation**
folium is maintained by volunteers. Can you help make a PR if we want to implement this feature?

**Comment by Conengmo** [comment]
folium doesn't deliver an offline feature and it's not within scope at the moment.
