### ISSUE TITLE
"https://code.jquery.com/jquery-1.12.4.min.js" can not be accessed

### ISSUE THREAD

**Issue by CaoHua1203** [python-visualization/folium#1369]
"**https://code.jquery.com/jquery-1.12.4.min.js**" can NOT be accessed, while "https://jquery.com" can be accessed.

Due to missing of "https://code.jquery.com/jquery-1.12.4.min.js", the map can not be correctly shown.

Anything I can do to solve the issue?

Thanks.

**Comment by Nightmare520** [comment]
I have the same problem as you，you can try change https://code.jquery.com/jquery-1.12.4.min.js to  http://code.jquery.com/jquery-1.12.4.min.js in folium.py

**Comment by CaoHua1203** [comment]
@Nightmare520 

So many thanks for your help. It works now. ^_^

**Comment by claustres** [comment]
Both seems to be down now, you can use https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js meanwhile.

**Comment by Conengmo** [comment]
Unfortunately I can't replicate this issue. If there would be an issue with the jquery CDN in certain regions, we can switch over to jsdelivr. But I'd need confirmation first that the jquery CDN is indeed blocked.
