### ISSUE TITLE
Streamlit Folium Component (bi-directional communication)

### ISSUE THREAD

**Issue by juancalvof** [python-visualization/folium#1370]
**INTRODUCTION**
Streamlit is an open-source framework that allows creating machine learning and data science apps in the minimum time possible. Right now, there has been a big push to Components API (https://docs.streamlit.io/en/stable/streamlit_components.html).  It would be so great to connect Folium to Streamlit. @Conengmo, I mention your name as the actual leader in Folium maintenance. I'm aware that Ted Rick has tried to reach you in relation to this objective and to evaluate if you will be interested in collaborating. I am willing to help in whatever is in my hands, but I think it will nice that a person who knows Folium deeply, participates. :)

Of course, this invitation is understood as extensive to anyone who wants to participate. :stuck_out_tongue_winking_eye:

I will send Ted this link so in case you have an interest in the matter, he can add more pertinent links: 
- https://discuss.streamlit.io/t/folium-component-bi-directional-communication-wip/3748
- https://discuss.streamlit.io/t/streamlit-components-launch/4223

:star2: I think it would be a great opportunity to join both technologies and give Folium a push and attract new possible developers to Folium project.

These are some thoughts I throw in the discussion:

**MAIN POINTS STREAMLIT**
Fast Data Apps (this is a game-changer, doing 10 studies/apps, in the time I do 1, from my point of view, opens a new path in data science)
Connection with buttons and external libraries. ( libraries that many people know how to use)
Connection of the buttons, with all the components of different external libraries at the same time. This means, watching results, with the queries of the buttons, in a histogram, boxplot, and map at the same time for example. (I attach some examples that I have developed for getting the idea)
https://juancalvo.carto.com/builder/9ec4eeeb-1ea2-4ef6-8ee5-3e923ffa944e/embed
https://juancalvo.carto.com/builder/aed07e52-72f0-4e4d-b700-a8437a2e158d/embed
https://juancalvo.carto.com/builder/b1b0b61e-acdc-4cc1-b47f-93c4a97b664d/embed

**MAIN POINTS FOLIUM**
Stability and customizing options.
Leaflet.js development.
Easy connection of plugins of Leaflet.js
FastMarkerCluster() and MarkerCluster() to deal with a lot of rows, elements.

**FUTURE LOCATION INTELLIGENCE**
5G and loT maturity. :alien:
Dealing with millions of elements and having the variable time, which makes a lot of snapshots.

**POWER OF STREAMLIT AND FOLIUM**
Join previous advantages of 2 products in 1 product. :dizzy:
Anticipate how to deal with a lot of elements and snapshots.
A must should be to be able to open Folium, once the query is done, to Full-screen mode.
Being able to compare 2 maps, with their graphs, with different time snapshots; would be awesome.
3 examples of how I imagine the future of Location Intelligence:
https://github.com/dabreegster/abstreet/: 1 Its a game, but imagine this with loT.
https://explorer.morphocode.com/ 1 Masking data, which permits dealing with less data, for better user experience.
https://www.glidefinder.com/ 1 Awesome BigQueryGIS project:

**Comment by randyzwitch** [comment]
FWIW, this now exists, so we can probably move any development discussion there. How features get added will be determined by how many people participate/motivated to contribute!

https://github.com/randyzwitch/streamlit-folium

**Comment by Conengmo** [comment]
Sorry to have been away from this topic. Thanks for creating that integration @randyzwitch! I don't have much time to be actively involved, but if there's something to be done on the folium side I'd be happy to help. We'll link out to it in our readme (https://github.com/python-visualization/folium/pull/1659), with that I'll close this issue.
