### ISSUE TITLE
RegularPolygonMarker does not work if prefer_canvas=True

### ISSUE THREAD

**Issue by markhudson42** [python-visualization/folium#1373]
Hello,

This is my first time using github, so I apologise if I make faux pas.

I am using folium version 0.11.0 within a Jupyter Notebook with Python 3.7.7. I have been getting to grips with the way in which the library is used, and learning about what works and what doesn't work with respect to plotting thousands of points and polylines. I have mostly been using ```CircleMarker``` objects for displaying my points because it looks like the ```GeoJsonMarker``` functionality is not yet merged into the master branch. I have also had some success with using ```BeautifyIcon``` for non-circular points.

Recently, however I have been trying to use ```RegularPolygonMarker``` to show points with different numbers of sides to represent different things and I have found that the resulting html contains javascript errors unless I set ```prefer_canvas=False```. My understanding, though, is that ```prefer_canvas=True``` is a good idea when showing a lot of objects.

**Example code**
The following is the code I have used, with ```prefer_canvas=True```, which leads to the problem:

```python
import folium
my_location = (51.5, -0.39)
m =  folium.Map(location = my_location,
               zoom_start = 12,
               prefer_canvas=True)

reg_marker = folium.features.RegularPolygonMarker(location=my_location, number_of_sides=4, radius=10)
m.add_child(reg_marker)

m.save("regular_polygon_test.html")
```

The marker does not appear in the resulting html map because, as far as I can tell, there is a javascript error caused by something in the file ```leaflet-dvf.markers.min.js```:

```
Uncaught TypeError: this._renderer._setPath is not a function
    at i._update (leaflet-dvf.markers.min.js:8)
    at i._reset (leaflet.js:5)
    at i.onAdd (leaflet.js:5)
    at i._layerAdd (leaflet.js:5)
    at i.whenReady (leaflet.js:5)
    at i.addLayer (leaflet.js:5)
    at i.addTo (leaflet.js:5)
    at regular_polygon_test.html:68
```

Is this a bug or just an issue with the leaflet-dvf library itself?

Thanks,

Mark.

**Comment by markhudson42** [comment]
Hello again,

Having done some browsing around the documentation for the RegularPolygonMarker documentation in the leaflet-dvf library, I think that, based on my limited knowledge, the issue is that svg cannot be used with canvas, and since the regular polygons are drawn using svg this means that they cannot be drawn when using canvas. So, this is an issue with the underlying leaflet plugin and not folium, so I will close this issue.

Mark.

**Comment by Conengmo** [comment]
Hi Mark, thanks for reporting back on this 👍
