### ISSUE TITLE
Cusomizing the colorbar tick labels in a folium map (using branca colormap plugin)

### ISSUE THREAD

**Issue by rezafara** [python-visualization/folium#1374]
Hi,

I am using folium map for making a "heat map"-like plot on an Open Street Map. I want to plot some GPS Lat/Lon data on a map, but the color of each point must represent the accuracy estimation of the GPS receiver at the point. For this reason, I use a logarithmic color mapping (using branca plugin) and I add the color map to the folium map using add_child() function. I've almost completed the code but the only problem is that I can't change the tick labels of the colorbar. It shows the indexes that I've used for branca colormap, but I would rather customize the tick labels in another way.

Here is my code:
```python

import folium.plugins
import branca
import branca.colormap as cm

fname = 'test_colorbar.html'
# Load Folium map object, working with Open Street Map and zoom of 17
# Note that 17-zoom is maximum possible zoom
base_lat = 50.682294344
base_lon = 10.939628989
f_map = folium.Map(location=[base_lat,base_lon], tiles="OpenStreetMap", zoom_start=17)

lat_ = [50.6823, 50.6822, 50.6821, 50.6820, 50.6819]
lon_ = [10.9396291, 10.9396279, 10.9396269, 10.9396265, 10.9396261]
acc_ = [11.0,44.5,149.9,319.1,540.0,752.6]

colormap = cm.LinearColormap(colors=['darkblue', 'blue', 'cyan', 'yellow', 'orange', 'red'],
                             index=[0, 25, 62.5, 156.25, 390.6, 1000], vmin=0, vmax=1000,
                             caption='Total Standard deviation at the point[mm]')

fg = folium.FeatureGroup(name=fname.split('.')[0])    

for pt in range(len(lat_)):

    color = colormap(acc_[pt])
    fg.add_child(folium.CircleMarker(location=[lat_[pt],lon_[pt]],
                                     radius=6,
                                     fill=True,
                                     color=color,
                                     fill_color=color))

f_map.add_child(fg)
f_map.add_child(colormap)
# Save the result as an HTML file
print('Saving the map file...')
f_map.save(fname)
```

This code delivers the following result:
![image](https://user-images.githubusercontent.com/5107072/88829313-bd702b80-d1cc-11ea-81c8-5b83d74c3c86.png)

but I want the same colorbar with customized tick labels [0,1,10,100,1000] instead of [0, 25, 62.5, 156.25, 390.6, 1000]. 

Also I am using folium 0.10.0 in Jupyter Notebook on Mac OSX.

**Comment by markhudson42** [comment]
Hello,

This one intrigued me, so I did a bit of digging into the colormap.py code in the `branca` module, being led there by the javascript that is created by `folium` if you save the map to an HTML file.

I found that the underlying javascript template contains code like this to create the x-axis on the coloured rectangle:

```javascript
    color_map_7595581a0f67451b81f69ce0ae8534eb.xAxis = d3.svg.axis()
        .scale(color_map_7595581a0f67451b81f69ce0ae8534eb.x)
        .orient("top")
        .tickSize(1)
        .tickValues([0, 25, 62.5, 156.25, 390.6, 1000]);
```
So, it must be the `.tickValues` property that is setting the values and locations of the tick marks.

What I have found is that you can put these tick marks wherever you want, but they have to always be in the range covered by the colormap. So if your colormap runs from 0 to 1000, you can set the tick marks to be at any points from 0 to 1000 but not outside that range.

I have forked the `branca` module and made some changes to it to have a play around with what sorts of things can be adjusted, in case it is interesting to anyone. So far I have added `tick_labels` as a new property so it can be set by the user, as well as some attributes to allow the width, height and opacity of the colormap rectangle to be adjusted.

I don't know if this is useful enough for a pull request, and I am still new to these things with github, but here is a screenshot of what I was able to create with your example:

![image](https://user-images.githubusercontent.com/17765609/90807753-de80f380-e316-11ea-80d9-f2d6e223e6a2.png)

If you don't need anything quite like this, and I may not get this finished in a form to be included in `branca`, you could create your HTML file and edit the `.tickLabels` javascript manually.

Mark.

**Comment by vjsequi** [comment]
@markhudson42 how can I easily find your fork? I find that quite useful. Thanks.

**Comment by Sorkanius** [comment]
will this ever get merged? The labels could also be strings in order to "classify" zones of the map

**Comment by emskiphoto** [comment]
It would be great to have the nonlinear colorbar feature (ie. 'ticklabels') available per @markhudson42 example.  I need a colorbar for an exponential distribution and can't find a way to get it to look right.

**Comment by kota7** [comment]
Here is a workaround to reproduce the result by @markhudson42.
This allows you to locate the color bar ticks at arbitrary locations.
Note that the ticks must be numeric variables within the range `[vmin, max]`, otherwise they won't be visible or truncated.

In the original code, the `index` parameter determines both the threshold of the colors and the positions of the ticks. This code separate the two roles: if `tick_labels` is given, this is used as the tick positions as-is.

I hope this result could help someone.

```python
import folium
from branca.colormap import ColorMap, LinearColormap
from branca.element import MacroElement
from branca.element import Figure, JavascriptLink
from branca.utilities import legend_scaler

class LinearColormap2(LinearColormap):
    def __init__(self, colors, index=None, vmin=0., vmax=1., caption='', max_labels=10, tick_labels=None):
        super(LinearColormap2, self).__init__(
            colors, index=index, vmin=vmin, vmax=vmax, caption=caption, max_labels=max_labels)
        self.tick_labels = tick_labels
    
    def render(self, **kwargs):
        self.color_domain = [self.vmin + (self.vmax-self.vmin) * k/499. for
                             k in range(500)]
        self.color_range = [self.__call__(x) for x in self.color_domain]
        if self.tick_labels is None:
            self.tick_labels = legend_scaler(self.index, self.max_labels)
        super(ColorMap, self).render(**kwargs)
        
        figure = self.get_root()
        assert isinstance(figure, Figure), ('You cannot render this Element '
                                            'if it is not in a Figure.')
        figure.header.add_child(JavascriptLink("https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"), name='d3')  # noqa
      
colormap = LinearColormap2(["blue", "yellow", "red"], index=[1, 10, 100], vmin=1, vmax=100,
                           tick_labels=[-10, 30, 80, 999])
m = folium.Map(location=[48, -102], zoom_start=3)
colormap.add_to(m)

m
```

![Screenshot_2022-08-15_23-56-15](https://user-images.githubusercontent.com/12293919/184659556-34594242-a05c-4d84-b68b-6057ce4b5157.png)

**Comment by kota7** [comment]
@emskiphoto I figured out one way to create a colorbar with non-linear scaling (never mind if this is not what you wish for). Essentially you can define a color scale using the transformed variable, then modify the label text afterwards using the approach at https://github.com/python-visualization/folium/issues/1419 by @coa-project.  

The code below creates a colorbar in the log scale (colors are located in the log-axis). To do this, I first convert the variable to `log10` and use as the color key. Later, I manipulate the legend text to the power of 10 using the inline javascript. 

```python
import folium
from branca.element import Element
from branca.colormap import LinearColormap

m = folium.Map(location=[48, -102], zoom_start=3)
colormap = LinearColormap(["red", "yellow", "green", "blue"], index=[0, 1, 2, 3], vmin=0, vmax=3)
# [0, 1, 2, 3] = log10([1, 10, 100, 1000])
colormap.add_to(m)

e = Element("""
  var ticks = document.querySelectorAll('div.legend g.tick text')
  for(var i = 0; i < ticks.length; i++) {
    var value = parseFloat(ticks[i].textContent.replace(',', ''))
    var newvalue = Math.pow(10.0, value).toFixed(0).toString()
    ticks[i].textContent = newvalue
  }
""")

html = colormap.get_root()
html.script.get_root().render()
html.script.add_child(e)
m
```

![Screenshot_2022-08-16_01-00-02](https://user-images.githubusercontent.com/12293919/184670985-b0823e08-621f-461d-8040-bfe7cac8228e.png)

To work with `Choropleth` class, find the colormap object at the `color_scale` attribute.

```python
import folium
import numpy as np
import pandas as pd
from branca.element import Element

url = (
    "https://raw.githubusercontent.com/python-visualization/folium/master/examples/data"
)
state_geo = f"{url}/us-states.json"
state_unemployment = f"{url}/US_Unemployment_Oct2012.csv"
state_data = pd.read_csv(state_unemployment)
state_data.Unemployment = np.log10(state_data.Unemployment)
m = folium.Map(location=[48, -102], zoom_start=3)

c = folium.Choropleth(
    geo_data=state_geo,
    name="choropleth",
    data=state_data,
    columns=["State", "Unemployment"],
    key_on="feature.id",
    fill_color="YlGn",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Unemployment Rate (%)",
)
c.add_to(m)

e = Element("""
  var ticks = document.querySelectorAll('div.legend g.tick text')
  for(var i = 0; i < ticks.length; i++) {
    var value = parseFloat(ticks[i].textContent.replace(',', ''))
    var newvalue = Math.pow(10.0, value).toFixed(2).toString()
    ticks[i].textContent = newvalue
  }
""")
colormap = c.color_scale
html = colormap.get_root()
html.script.get_root().render()
html.script.add_child(e)
m
```

![Screenshot_2022-08-15_23-42-43](https://user-images.githubusercontent.com/12293919/184669224-8c412c6e-a63c-4b91-bdc3-b9a1131fc416.png)

I admit this is not elegant, but a better solution would require deep knowledge of the d3.js framework and modification of [color_scale.js](https://github.com/python-visualization/branca/blob/52b10bd969ac25d0b70640b2eee2ea1d8e8690b3/branca/templates/color_scale.js) in the branca library. I even do not know if the d3.js supports the non-linear color scaling. So I end up going with this workaround for now.

**Comment by Conengmo** [comment]
We just merged https://github.com/python-visualization/branca/pull/113, which implements a parameter to set custom tick labels. It will be included in the next branca release, which will be 0.6.0, date yet undefined. Thanks everybody for the input on this topic and @kota7 for the PR.
