### ISSUE TITLE
label markers with number and add these numbers on marker clustering

### ISSUE THREAD

**Issue by athulvingt** [python-visualization/folium#1375]
I would like to cluster (kmeans ) my data and plot the mean coordinate of each cluster. Label each kmean cluster with size of the cluster (count of the data in that kmean cluster). Wile zooming out i would like to get the labels getting added up

**Comment by Conengmo** [comment]
You could check out the `MarkerCluster` class, which will automatically group your markers and show the count.

Otherwise you'll have to add labels manually as extra markers.
