### ISSUE TITLE
clustering a marker with circle

### ISSUE THREAD

**Issue by athulvingt** [python-visualization/folium#1376]
My marker has a circle around it, so when I add these to cluster the size of a cluster get doubled as the circle and marker are counted instead of considering as a same entity. what is the best solution?

Here is my code 
```python
incidents = plugins.MarkerCluster().add_to(map1)
for lat, lng, rad, d,c in zip(rep_points.lat, 
                              rep_points.lon, 
                              rep_points.rad, 
                              rep_points.density, 
                              rep_points.C_count):
    folium.Circle(
        location=[lat, lng],
        radius= rad,
        fill=True,
        color=colormap(d)
    ).add_to(incidents)
    
    folium.Marker(location =[lat, lng], popup=c,icon=folium.Icon(color='blue', icon='ok-sign')).add_to(incidents)
    

    
map1
```

**Comment by ngocmphan** [comment]
Hi! I think I figured it out, you need to add the marker directly to the base map instead of the marker cluster.

incidents = plugins.MarkerCluster().add_to(map1)

for lat, lng, rad, d,c in zip(rep_points.lat, 
                              rep_points.lon, 
                              rep_points.rad, 
                              rep_points.density, 
                              rep_points.C_count):
    folium.Circle(
        location=[lat, lng],
        radius= rad,
        fill=True,
        color=colormap(d)
    ).add_to(incidents)
    
    folium.Marker(location =[lat, lng], popup=c,icon=folium.Icon(color='blue', icon='ok-sign')).add_to(map1)
    

    
map1

I hope it helps.

**Comment by athulvingt** [comment]
Thanks for your response, But this not what i was looking for. I am trying to make a marker and the circle around it as a single entity. So that when i zoom out the circle and marker clusters together (without counting it twice)

**Comment by Conengmo** [comment]
I don't think there's a way to do what you want, assuming I understood what you want to do correctly. There's no magical way to link `Circle` with `Marker` or `MarkerCluster`.
