### ISSUE TITLE
Circle object is not corrected for projects 

### ISSUE THREAD

**Issue by WaqarSM** [python-visualization/folium#1377]
When a circle is drawn, its projection correction is relative to the point where it is drawn. 

To illustrate this I drew a 1e8 meter circle at [0,0] - the result is a perfect circle. However, that is not what would be expected for a projection corrected circle. I have 'manually' drawn what this should look like. 

It is well possible that this feature exists in this wonderful package, however, I have not been able to find it. 

I have really enjoyed using folium so far! 💯 

**To Reproduce**

```python
m2 = folium.Map(location=[0,0],tiles=style, zoom_start=0)
folium.Circle([0,0], 100000e3, color='crimson', fill=True).add_to(m2)
m2
```
![Screen Shot 2020-08-09 at 6 44 24 PM](https://user-images.githubusercontent.com/21031884/89743470-73f7ca00-da71-11ea-9e75-adb9f9451100.png)

**Expected behaviour**
```python
m3 = folium.Map(location=[0,0],tiles=style, zoom_start=1)
for i in range(360):
    folium.Circle([math.sin(math.radians(i))*89,math.cos(math.radians(i))*89]
                  , 1, color='crimson', fill=True).add_to(m3)
m3
```

![Screen Shot 2020-08-09 at 6 45 14 PM](https://user-images.githubusercontent.com/21031884/89743471-7528f700-da71-11ea-9c11-d7020dbd64f6.png)

**Environment:**
 - Browser: Google Chorme Version 83.0.4103.116 (Official Build) (64-bit)
 - Jupyter Lab
 - folium version: 0.11.0

**Comment by Conengmo** [comment]
Hi @WaqarSM, I think this is expected behavior. It's a limitation of Leaflet, the JS library underneath folium, so there's not much we can do on our end. See their documentation here: https://leafletjs.com/reference-1.6.0.html#circle

I did a very short search and did find this Leaflet plugin you could try perhaps: https://github.com/nuclearsecrecy/Leaflet.greatCircle
