### ISSUE TITLE
Switching TimeSliderChoropleth breaks the coloring

### ISSUE THREAD

**Issue by paulsp94** [python-visualization/folium#1379]
**Describe the bug**

When I use the LayerControl and add the TimeSliderChoropleth to it, switching the TimeSliderChoropleth layer on and off brakes the coloring of the polygons and only the below geojson structure is visible. 

This can even be found in this example online:

https://geohackweek.github.io/ghw2018_web_portal_inlandwater_co2/InteractiveTimeSeries.html#Map-Showing-Levels-of-CO2-Concentration-Measured-at-Different-Locations-Over-Time

I ran into the same problem and can provide you with some code to reproduce if necessary, I just thought the example already shows the faulty behavior.

![image](https://user-images.githubusercontent.com/24817172/90442147-7645ce00-e0da-11ea-8c75-5f62598110f4.png)
![image](https://user-images.githubusercontent.com/24817172/90442171-8198f980-e0da-11ea-84c5-f471fb101170.png)

**To Reproduce**

```
can work on a minimal example if deemed necessary.
```

**Expected behavior**

The TimeSliderChoropleth layer shows exactly as it was visible before.

**Environment (please complete the following information):**

 - Browser: Chrome
 - Jupyter Notebook and html file
 - folium version: 0.8.3

**Additional context**
Nothing so far as I could see the problem appearing in example as well.

**Possible solutions**
Perhaps a problem, that the render is not properly called on the layer? 

folium is maintained by volunteers. Can you help making a fix for this issue?

If I get some guidance on the possible solution I could give it a try.

**Comment by Conengmo** [comment]
Can you try installing folium from our master branch, see if maybe it's an issue with the older version?

**Comment by paulsp94** [comment]
Yes I tried it with version `0.11.0+19.g46f820e` directly installed from git with 
`!pip install git+https://github.com/python-visualization/folium.git@master#egg=folium` 
but I still have the same error.

**Comment by Conengmo** [comment]
Okay, thanks for checking that. I don't know what's going on. I do know this plugin is a bit fragile. Anyone interested in investigating this issue is welcome.

**Comment by Conengmo** [comment]
The fix in #1380 has been merged, so this can be closed.
