### ISSUE TITLE
Request: Additional file input

### ISSUE THREAD

**Issue by ColeTownsend** [python-visualization/folium#138]
It would be awesome if you could insert a CSS file when building this to style the page a bit. Or add additional elements to the webpage itself.

This is my workaround for now:

```python
# inset css file post map creation and title it.
            soup = BeautifulSoup(open("map/{}/index.html".format(year)))
            meta = soup.find('meta')
            css = soup.new_tag('link')
            css['rel'] = "stylesheet"
            css['href'] = "../map.css"
            meta.insert_after(css)

            body = soup.find('body')
            h1 = soup.new_tag('h1')
            h1.string = "TDF {} Map".format(year)
            body.insert_after(h1)
```

**Comment by ocefpaf** [comment]
:+1:  for an option for a "full" CSS override in case you do not want to use the default.

:-1:  For supporting additional elements.  That would bring a complexity that is beyond the scope of folium.  And you can always edit the HTML later :wink: 

Is this something you might want to take a stab at?

**Comment by themiurgo** [comment]
At some point we will probably need to define some template areas where we can inject some elements for the plugin feature #18 , for example "headers". Maybe we can make those methods public and allow people to import their own `<script>` or `<style>`.

**Comment by ColeTownsend** [comment]
@ocefpaf Is it beyond the scope? It already creates a map element that is its own HTML page. It wouldn't be a horrible option and would be super useful for titles. As I'm programmatically building multiple maps, I don't want to hand write any of the files. 

One could presumably import the map file into a more robust page. I'm serving them as their own pages individually.

Ex: http://coletownsend.github.io/ben-cole-project/

**Comment by ocefpaf** [comment]
@ColeTownsend I can be convinced otherwise, but right now I am biased towards keeping folium simple and solving some more pressing issues we have.

Still, if you send a PR and some nice arguments, we can keep talking and evolving this idea.  It seems that @themiurgo even has a model for this in his head already :wink: 

So lets keep this issue opened.

**Comment by ocefpaf** [comment]
pinging @BibMartin here.  I would like your opinion on this issue.

**Comment by BibMartin** [comment]
In the plugins machinery, we define 4 places in the template where a plugin can inject code :
* header (for injecting javascript import, or css import)
* css (for injecting just one or two css styles)
* html (for creating you own div, etc)
* javascript (for injecting code into the leaflet script)

So it is quite easy to create a plugin that injects a CSS into folium's template.

If you want conversely to embed a folium map into a larger web page, it seems more complicated with today's state of the code. But if we continue to pluginify things, we may get to the state where the main template looks like:

    {% header %}
    {% css %}
    {% html %}
    {% javascript %}

In that case, you would be able to replace the main template by any html file that contains these 4 tags.

Meanwhile, you still have the possibility to embed several maps in the same page with iframes.

**Comment by BibMartin** [comment]
Please, see https://github.com/BibMartin/folium/commit/5e90c1bf3f2e5e51c062c041393b95c3386710ba for an example.
@ocefpaf : I am continuing of creating plugins. I'll do a PR when I have several of them.

**Comment by ocefpaf** [comment]
@ColeTownsend can you take a look at [CssLink](https://github.com/python-visualization/folium/blob/fcee8393e5ff0533429a42a7cb5976de3c73a9a4/folium/element.py#L139-L162) and see if that is OK for your purpose?

**Comment by ColeTownsend** [comment]
@ocefpaf that looks solid! perfecto.

**Comment by ocefpaf** [comment]
Awesome!  Closing this then.
