### ISSUE TITLE
wrong :super(Map, self).__init__()  TypeError: super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by daihuangliang** [python-visualization/folium#1381]
after upgraded the folium ,run code show :

 super(Map, self).__init__()  
TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by markhudson42** [comment]
Hello,

Could you provide some more detailed information about what the problem is?

For example, could you provide a simple, self-contained example of Python code which reproduces the error message?

Mark.

**Comment by daihuangliang** [comment]
after upgrade ,when I first run my code ,dispaye "[autoreload of folium failed: Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "D:\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 434, in superreload
    module = reload(module)
  File "D:\Anaconda3\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "D:\Anaconda3\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Anaconda3\lib\site-packages\folium\__init__.py", line 20, in <module>
    from folium.features import (
ImportError: cannot import name 'GeoJsonPopup' from 'folium.features' (D:\Anaconda3\lib\site-packages\folium\features.py)
]"

**Comment by daihuangliang** [comment]
Program say  when run code :"folium.Map(location=[20, 0], tiles="http://mt3.google.cn/vt/lyrs=m&hl=zh-CN&gl=cn&x={x}&y={y}&z={z}", attr='default')"    display  the problem. The codes is succeded runing on version 0.9.1

**Comment by daihuangliang** [comment]
I writed a simple code  : 
"
import folium
m = folium.Map(location=[45.5236, -122.6750])
m
"
display the same  problem "
  File "D:\Anaconda3\lib\site-packages\folium\folium.py", line 237, in __init__
    super(Map, self).__init__()

TypeError: super(type, obj): obj must be an instance or subtype of type"

**Comment by Conengmo** [comment]
which Python version are you using? Which folium version? Check it with `print(folium.__version__)`)

We dropped support for Python 2, so that might be the issue.

**Comment by daihuangliang** [comment]
ver：0.9.1
python3.7

**Comment by Conengmo** [comment]
please upgrade folium to the most recent version and try again. You reported two errors and both don't seem like an issue with folium, but something with older versions.

**Comment by daihuangliang** [comment]
Thank you, problem  has solved
