### ISSUE TITLE
program can't connect "https://rawcdn.githack.com/ljagis/leaflet-measure/2.1.7/dist/leaflet-measure.js" ,What can i do?

### ISSUE THREAD

**Issue by daihuangliang** [python-visualization/folium#1383]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Implementation**
folium is maintained by volunteers. Can you help make a PR if we want to implement this feature?

**Comment by Conengmo** [comment]
we moved to a different CDN already. Please install folium from our master branch: `pip install git+https://github.com/python-visualization/folium.git`

**Comment by matkoniecz** [comment]
Is it maybe fixed by https://github.com/python-visualization/folium/releases/tag/v0.12.1  or one of earlier releases?

**Comment by Conengmo** [comment]
Yes I think that's true.
