### ISSUE TITLE
search plugin display multiple places

### ISSUE THREAD

**Issue by uli22** [python-visualization/folium#1384]
**Describe the issue**
I display places where certain historic persons appear at different places on a stamen map. They are coded in geojson. Search works fine: it shows found places in search combo box and I after selecting one value it zooms to that place on the map. 

My question:
Is it possible after search to display not only one found place, but all places where the name was found? 

cheers
Uli

**Comment by Conengmo** [comment]
Looking at the underlying JS plugin we use (https://opengeo.tech/maps/leaflet-search/) that doesn't seem possible.
