### ISSUE TITLE
Folium choropleth  class error 

### ISSUE THREAD

**Issue by Morenagl** [python-visualization/folium#1386]
#### 
#1247 
#1077 
#1367 
#pleas help me with that 
TypeError: __init__() missing 1 required positional argument: 'geo_data'

```python
marseille_map = folium.Map(location = [43.354, 5.4265], zoom_start = 12)
marseille_map.choropleth(geo_str = geo, key_on = "feature.properties.arrondissement",
                 data = df, columns = ["Arrondissement", "Surface"],
                 fill_color = "Spectral")
showData(marseille_map)
```
#### Problem description

[this should explain **why** the current behavior is a problem and what is the expected output.]

#### Expected Output
i expect to have a carte with all my zip code surfaces but I didn't understand the error 
this is my geo["features"][0]['properties']
{'cartodb_id': 1461,
 'insee': '13209',
 'nom': 'Marseille 9e Arrondissement',
 'wikipedia': 'fr:9e arrondissement de Marseille',
 'surf_m2': 63283053,
 'arrondissement': '13009'}
#### Output of ``folium.__version__``

TypeError: __init__() missing 1 required positional argument: 'geo_data'

**Comment by elouayas** [comment]
Use 
folium.Choropleth(geo_data=geo).add_to(marseille_map)
instead
