### ISSUE TITLE
raster ImageOverlay png generation

### ISSUE THREAD

**Issue by crendl** [python-visualization/folium#1389]
Hello,
I am trying to plot a single-band raster `image` as `numpy.ndarray` using `raster_layers.ImageOverlay`.

Here are some `image` characteristics:

```python
metadata:
{'driver': 'GTiff',
 'dtype': 'float32',
 'nodata': -9999.0,
 'width': 219,
 'height': 77,
 'count': 1,
 'crs': CRS.from_epsg(4326),
 'transform': Affine(0.034999999999999996, 0.0, 9.50519700000001,
        0.0, -0.034999999999999996, 49.050352),
 'offset': 0.0,
 'scale': 1.0}
```

My map generation looks like this:
```python
import folium
from matplotlib import cm
print(folium.__version__)
0.11.0
```

```python
m = folium.Map([48, 16], zoom_start=6, tiles='Stamen Toner')

b = src.bounds
bounds = [(b.bottom, b.left), (b.top, b.right)]

folium.raster_layers.ImageOverlay(
    image=image,
    bounds=[[b.bottom, b.left], [b.top, b.right]],
    colormap = cm.jet 
).add_to(m)

m
```
Result:
![image](https://user-images.githubusercontent.com/15796851/93773316-47ae9c00-fc20-11ea-9712-acbe756b9fbc.png)

I'd expect the results to look rather like this, using `matplotlib`
```python
import matplotlib.pyplot as plt
plt.subplots(figsize=(10,10))
plt.axis('off')
plt.imshow(image, cmap = 'jet')
plt.savefig('temp.png', transparent=True, bbox_inches='tight', pad_inches=0)
```
![image](https://user-images.githubusercontent.com/15796851/93776000-5cd8fa00-fc23-11ea-986b-887b8da9d164.png)

I assume the unintended result can be traced back to the geotiff float32 to PNG conversion...?
So, yes, I could create my own png using `mpl` and plot it , but would it be possible to omit this step?

Edit: add attachments, image.tif and austria.geojson
[folium.zip](https://github.com/python-visualization/folium/files/5259838/folium.zip)

**Comment by Conengmo** [comment]
I'm unable to replicate the issue. The attached tiff doesn't give me the same results. I'm not familiar with tiffs, it seems to have values between -9999 and 7.503634e-05, whereas Matplotlib colormaps expect floats between 0 and 1.

I'll close the issue. If somebody wants to provide a fully working code snippet that demonstrates this issue, we can look into it more.
