### ISSUE TITLE
Marker ClusterGroup result changes based on Time scale( like; Timestamped GeoJSON or TimeSliderChoropleth )

### ISSUE THREAD

**Issue by BIJOY-SUST** [python-visualization/folium#1391]
**I'm always frustrated when I want to change Marker Cluster result based on the Time Scale. But unfortunately, I'm unable to find any solution.**
**I have a Marker Cluster it looks like this**:

![Screenshot from 2020-09-28 13-31-16](https://user-images.githubusercontent.com/41442625/94403394-2c4b1000-018f-11eb-83f8-8a1d07174b00.png)

**Here the solution I'd like**

![Screenshot from 2020-09-28 13-43-15](https://user-images.githubusercontent.com/41442625/94404316-9ca66100-0190-11eb-9a93-0e9a1af88e45.png)
![Screenshot from 2020-09-28 13-43-04](https://user-images.githubusercontent.com/41442625/94404327-9fa15180-0190-11eb-8801-2e27c0c30c62.png)

### Can anyone help/guidance me how to I'm able to make this?

**Comment by nalikhanyan** [comment]
I am looking for this too. Any updates on this topic?

**Comment by Conengmo** [comment]
We don't have this functionality in folium at the moment. If somebody wants to make this plugin that's welcome! Though we'd probably invite you to host the plugin yourself, we would then link to it.
