### ISSUE TITLE
search plugin displays result not as expected

### ISSUE THREAD

**Issue by uli22** [python-visualization/folium#1392]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

df2['label1'] = ["<br>".join(sorted(i)) for i in df2['label1']]

![Screenshot 2020-10-03 160842](https://user-images.githubusercontent.com/8950985/94993638-c269a680-0592-11eb-99b4-902d9f9a102e.png)
![Screenshot 2020-10-03 160716](https://user-images.githubusercontent.com/8950985/94993640-c39ad380-0592-11eb-953d-1ef0e9e71a3f.png)

#### Problem description

In my map I search for Names and display the place where they appeared. When I enter a Name the search-tooltip displays the names with linebreaks induced by <br> tags as I expect.
When I select one of these results this is not displayed as exspected. It shows all the Names in one line not acounting for the linebreaks that were shown in the search tooltip. (see scrrenshots attached)

#### Expected Output
see attached screenshots

#### Output of ``folium.__version__`` 
Folium 0.11.0

**Comment by Conengmo** [comment]
I'm afraid I can't help here without having a standalone code snippet that is able to reproduce your issue. See https://stackoverflow.com/help/minimal-reproducible-example
