### ISSUE TITLE
Is it possible to alter Tooltip attributes like size

### ISSUE THREAD

**Issue by ayushjsh** [python-visualization/folium#1393]
**Can I change properties of the tooltip such as its width and height ?**
I have some large text I need to be displayed in a tooltip and it would be great if I can fix the width of the tooltip.

I have seen solutions in leaflet which work by customising the Leaflket css. [https://gis.stackexchange.com/questions/212820/overriding-leaflet-tooltip-style](https://gis.stackexchange.com/questions/212820/overriding-leaflet-tooltip-style)

and another one here which exactly solves my problem, but I am not sure how this can be done in folium.
[https://gis.stackexchange.com/questions/223226/make-tool-tip-wrap-text](https://gis.stackexchange.com/questions/223226/make-tool-tip-wrap-text)

**Comment by FabianRuizF** [comment]
I have the same problem, even if I try to use the style attribute, the only thing I can change is background-color and color, but borders, width, height, and any other attribute does not work.

@ayushjsh  , did you find something to fix it?

**Comment by ayushjsh** [comment]
@FabianRuizF unfortunately not. hopefully someone can help here.

**Comment by Conengmo** [comment]
I was able to set the size of the tooltip with the `style` argument. Here's an example:

```
Marker((0, 0), tooltip=Tooltip(
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    style='width:300px; height:300px; white-space:normal;',
)).add_to(m)
```
