### ISSUE TITLE
plugins.MarkerCluster - markers are not showned when tiles=None

### ISSUE THREAD

**Issue by brunetton** [python-visualization/folium#1395]
**Describe the bug**
When using `MarkerCluster` plugin to add marker to a map, markers are not showned if I add `tiles=None` parameter to `folium.Map()`

**To Reproduce**

```python
import folium
from folium import plugins

coords = [[45.01, 3.05]]
texts = ["hello"]

m = folium.Map([45, 3], tiles=None)
plugins.MarkerCluster(coords, popups=texts).add_to(m)

m
```

**Expected behavior**
I expected to actualy see markers. I actually see markers when I remove `tiles=None`

**Environment (please complete the following information):**
 - Browser: firefox
 - Jupyter Notebook or html files? => Jupyter Notebook 
 - Python version (check it with `import sys; print(sys.version_info)`) => sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
 - folium version (check it with `import folium; print(folium.__version__)`) => 0.11.0
 - branca version (check it with `import branca; print(branca.__version__)`) => 0.4.1

**Possible solutions**
- Removing `tiles=None` from map init, but I didn't need map tiles in that case
- Do not use plugins.MarkerCluster plugin but use folium.Marker directly

folium is maintained by volunteers. Can you help making a fix for this issue? => No, I'm a beginner user

**Comment by HaraldTR** [comment]
I have had the same issue.

**Comment by fernandeslouro** [comment]
I've found the same issue as well. I'll try and look for a way to fix it with my limited knowledge.

**Comment by Conengmo** [comment]
You can get around this by specifying a maximum zoom level. But in this case use camelCase, it's a bit of a hack.

```
import folium
from folium import plugins

coords = [[45.01, 3.05]]
texts = ["hello"]

m = folium.Map([45, 3], tiles=None, maxZoom=10)
plugins.MarkerCluster(coords, popups=texts).add_to(m)

m
```
