### ISSUE TITLE
Documentation needs to be updated

### ISSUE THREAD

**Issue by themiurgo** [python-visualization/folium#140]
Many new features are not documented yet.

**Comment by ocefpaf** [comment]
@themiurgo I can tackle that, but can you help me put a list together:

- [ ] Autobounds
- [ ] ?

**Comment by themiurgo** [comment]
Ok, I'm editing your message only to keep the items in the same place.

**Comment by ocefpaf** [comment]
Thanks!

**Comment by themiurgo** [comment]
It would be great to make sections about additional parameters that apply for several objects. So instead of listing `popup` parameters for each object you can pass them to, have a popup section in the documentation. Same could be done for line / fill options.

**Comment by ocefpaf** [comment]
Makes sense.

(BTW I want to get the docs done for the next release.)

**Comment by BibMartin** [comment]
@ocefpaf @themiurgo 
I guess we can this issue, based on #329, #334, #337, #344 and #347 ...

Release seems so close !

**Comment by ocefpaf** [comment]
I'd say that 99% is done.  So let's close it and open new (and more specific) issues with what needs to be done.  (But do not tag them with `v0.2.0`.  We are done with docs that the next release :wink:)

**Comment by BibMartin** [comment]
:tada:
