### ISSUE TITLE
GeoJson Layer change marker

### ISSUE THREAD

**Issue by ParkvilleData** [python-visualization/folium#1401]
Hi,

Is it possible to change the default marker in a geojson layer?

I am using the popup/tooltip example from the examples.

```
#add the popup
popup = GeoJsonPopup(
    fields=['name','html', "link", "link-text"],
    localize=True,
    labels=False,
    overlay=False,
    highlight=True,
    style="background-color: yellow;",
)

#add the info into the popup
tooltip = GeoJsonTooltip(
    fields=["name", "html", "title"],
    localize=True,
    sticky=False,
    labels=False,
    style="""
        background-color: #F0EFEF;
        border: 2px solid black;
        border-radius: 3px;
        box-shadow: 3px;
    """,
    max_width=800,
)

#create searchable book  
bookgeo = folium.GeoJson(
    geoj,
    name='Books',
    tooltip=tooltip,
    popup=popup,
    show=True
).add_to(m)
```

I am able to add a custom marker as a FeatureGroup, which has a pop up, but I am unable to use the search functionality with it. 
As per the the image
![image1](https://user-images.githubusercontent.com/44953352/96798848-7d2bec80-144d-11eb-927d-28212be71cf7.png)

I tried the "other" way, which is to create a GeoJson layer, which works great with search, but I am unable to change the default marker. I have added Layer Control but I get this "macro_element_****" which I am unable to hide, otherwise, I would be able to just use the FeatureGroup while hiding the geojson layer which allow me to still use the search.

Is there anyway to do this? Any help would be greatly appreciated! Thanks!

![image2](https://user-images.githubusercontent.com/44953352/96798961-c1b78800-144d-11eb-8244-9ec893e198cc.png)

**Comment by ParkvilleData** [comment]
Update: If I uncheck the macro_element it works just as I want it to. 

Is there anyway to uncheck that as default? I am unsure where it's coming from. It's coming somewhere from the code above and not the FeatureGroup, that I am certain.

**Comment by VetalM84** [comment]
show=False is that you are looking for.
folium.FeatureGroup(name="Search", show=False).add_to(map)

**Comment by Conengmo** [comment]
Additionally, you can style the marker of a GeoJSON point geometry with the `marker` argument. Check the docstring of the `GeoJson` class for more info.

Here's also a minimal example:

```
    GeoJson(
        data="""
            {
              "type": "Feature",
              "geometry": {
                "type": "Point",
                "coordinates": [0, 0]
              }
            }
        """,
        marker=Marker(icon=Icon(icon='search')),
    ).add_to(m)
```
