### ISSUE TITLE
Get lat/lng programmatically from a mouse click event 

### ISSUE THREAD

**Issue by giswqs** [python-visualization/folium#1402]
Is it possible to get the lat/lng **programmatically** from a mouse click event on the map? The lat/lng is needed for subsequent computation. Thanks.

**Comment by Conengmo** [comment]
folium is kind of a one way street from Python to Javascript. So in general, no there's no way to get data made from interacting with the map back to Python. Some ideas:

- You could have to brew something on your own.
- You could use the `Draw` plugin to export a geojson file and load that back into Python.
- You could take a look at https://github.com/jupyter-widgets/ipyleaflet which should provide more interactivity, though I don't know if they have your use case.
