### ISSUE TITLE
Plotting Routes

### ISSUE THREAD

**Issue by monkshoody** [python-visualization/folium#1403]
I was wondering if it is possible to plot Lines per day in order to get a route of the Day.
For Example consider the HeatMapWithTime class in the plugins. It expects data as list of list of points of the form [lat, lng] or [lat, lng, weight] and an index for the label of the elements of data. Would it not be possible at this point to implement a transfer parameter (bool) which, if "True", would convert the latitude and longitude of each index into an (e.g.) AntPath Object?
An alternative would be to create several layers, each containing the route of a day. However, when looking at a lot of data, this would lead to the LayerControl object overflowing.
I have attached two files to clarify my idea. In the first picture, the HeatMapWithTime is set to the date 2020-9-24 and shows both the places and the route of the day. The second picture shows the places and the route from 2020-10-1 on the same map.

![2020-9-24_route](https://user-images.githubusercontent.com/73463758/97584719-3d867700-19f0-11eb-812f-b1082b1f6956.png)
![2020-10-1_route](https://user-images.githubusercontent.com/73463758/97584740-4119fe00-19f0-11eb-9372-0a99d7c7c4c3.png)

I guess a route function would help a lot of people.

**Comment by AdnanHodzic** [comment]
I believe I asked the same question in #1372
