### ISSUE TITLE
Folium Map Marker Popup Does Not Work

### ISSUE THREAD

**Issue by madatr** [python-visualization/folium#1405]
Hi,
Thank you all for your great work.

**Describe the bug**
I have noticed that the map marker popup does not work, I tried to implement code on my machine but was unable to do it, checking you guide online, the examples do not work either on my machine or on the online page itself.

**To Reproduce**
Just open the link: https://python-visualization.github.io/folium/quickstart.html
and check if any marker pop up works

`puup = (folium.Popup(str("Test")))
  folium.Marker([32.540533, 35.854179], popup="puup").add_to(mapp)
mapp = folium.Map(location=[32.540533, 35.854179], zoom_start=14, tiles='OpenStreetMap')
mapp.save(root_path + outputs_p + "splitt.html")`

**Expected behavior**
To get a pop up

**Environment: Mac, Windows**
 - Browser: Chrome, Safari
 - Python version: 3.8.2
 - folium version: 0.11.0

**Additional context**
Tried both on windows; chrome and mac; safari, chrome

**Possible solutions**
Unfortunately no clue, hope its something wrong with my set up

**Comment by DPW-vanderHoeven** [comment]
Hi Madatr,

I'm currently experiencing the same issue. The popups used to work on the same machine but now fail to respond, even on the official example you listed. Did you find anything to resolve the issue?

**Comment by Conengmo** [comment]
I can't replicate this issue... If somebody experiences this, please share the content of your browser console that I suspect may display an error.
