### ISSUE TITLE
Choropleth with geojson data of region without fill in data

### ISSUE THREAD

**Issue by cedmfr** [python-visualization/folium#1406]
I would like to show the country regions without displaying any data and of course scale bar on the map, only the regions highlighted on the map (color background and dark frontiers of regions). Is there a possibility just based on choropleth and geojson file ?
Regards,

**Comment by Timood** [comment]
I guess you could try:

```
c = folium.Choropleth(
...
)
c.add_to(m)

m
```

**Comment by fullonic** [comment]
Hey @cedmfr! Maybe you can get some help from this folium [example](https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/GeoJSON_and_choropleth.ipynb)?
