### ISSUE TITLE
Problem with TimeSliderChoropleth with changes on a yearly basis

### ISSUE THREAD

**Issue by kowalik-lukasz** [python-visualization/folium#1415]
I'm trying to visualize changes in some data (GDP to be precise) that occur yearly. When I run my script the data is correctly assigned and visualized in accordance with years but the slider does not show the data in a chronological way. Instead there seems to be random jumping around the years, sometimes it's a few years from the 60s, sometimes it's the latest decade and then suddenly back to the 70s. Out of curiosity I mapped my yearly data to be presented as a daily change just to see if the chronology is there and it was.
I'm using folium 0.11.0

For reproduction:
- styledict I used: https://github.com/kowalik-lukasz/map-viz/blob/master/src/data/styledict.json
- geojson I used: https://github.com/kowalik-lukasz/map-viz/blob/master/src/data/data.json

**Comment by Conengmo** [comment]
Not sure about this, but I hope it's solved by https://github.com/python-visualization/folium/pull/1503. If not please open a new issue, including a code snippet to reproduce the issue.
