### ISSUE TITLE
Scientific notation format in the colormap 

### ISSUE THREAD

**Issue by odadoun** [python-visualization/folium#1419]
**Is your feature request related to a problem? Please describe.**
Adding scientific notation in the LinearColormap format should be appreciated to avoid
overlapping digit in the colormap scale  (when number are huge)

**Describe the solution you'd like**
For instance a TickFormatter with format in argument such as :TickFormatter(format="%4.2e")

**Comment by coa-project** [comment]
Finally I have decided to hack the folium htlm. Here the piece of my code, hope it can help 
```
colormap = branca.colormap.linear.RdPu_09.scale(min_col,max_col)
colormap.add_to(mapa)
my_js = """
        var div = document.getElementById('legend');
        var ticks = document.getElementsByClassName('tick')
        for(var i = 0; i < ticks.length; i++){
        var values = ticks[i].textContent.replace(',','')
        val = parseFloat(values).toExponential(2).toString()
        if(parseFloat(ticks[i].textContent) == 0) val = 0.
        div.innerHTML = div.innerHTML.replace(ticks[i].textContent,val);
        }
        """  
e = Element(my_js)
html = colormap.get_root()
html.script.get_root().render()
html.script._children[e.get_name()] = e
````
it seems that hacking the labels of the colormap folium  is recurrent stuff (see https://github.com/python-visualization/folium/issues/1374)

**Comment by kota7** [comment]
@coa-project Thank for your comment. On my end, however, the `replace` method sometimes misses some ticks and they remain unchanged. Perhaps this is because it is targeting the whole legend div, and the target letters may appear somewhere else.  I find the code below is safer.

```python
import folium
import branca
from branca.element import Element

m = folium.Map(location=[48, -102], zoom_start=3)
colormap = branca.colormap.linear.RdPu_09.scale(1, 100)
colormap.add_to(m)

my_js = """
  var ticks = document.querySelectorAll('div.legend g.tick text')
  for(var i = 0; i < ticks.length; i++) {
    var value = parseFloat(ticks[i].textContent.replace(',', ''))
    var newvalue = value.toExponential(2).toString()
    if(value == 0) newvalue = 0
    ticks[i].textContent = newvalue
  }
"""  
e = Element(my_js)
html = colormap.get_root()
html.script.get_root().render()
html.script._children[e.get_name()] = e
m
```

**Comment by Conengmo** [comment]
We merged https://github.com/python-visualization/branca/pull/113, which implements a parameter to set custom tick labels. It will be included in the next branca release, which will be 0.6.0, date yet undefined.
