### ISSUE TITLE
only one location ,others disappear

### ISSUE THREAD

**Issue by nerocm** [python-visualization/folium#1420]
**Describe the bug**

**To Reproduce**

```
[ Include a code snippet that produces your bug. Make it standalone, we should be able to run it. ]

[ Include a data sample or link to your data if necessary to run the code ]

```

**Expected behavior**

**Environment (please complete the following information):**
 - Browser [e.g. chrome, firefox]
 - Jupyter Notebook or html files?
 - Python version (check it with `import sys; print(sys.version_info)`)
 - folium version (check it with `import folium; print(folium.__version__)`)
 - branca version (check it with `import branca; print(branca.__version__)`)

**Additional context**

**Possible solutions**
List any solutions you may have come up with.

folium is maintained by volunteers. Can you help making a fix for this issue?

**Comment by Conengmo** [comment]
This issue only includes a title, we can’t do anything with that.
