### ISSUE TITLE
CustomIcons using TimestampedGeoJson

### ISSUE THREAD

**Issue by carluqcor** [python-visualization/folium#1422]
**Describe the bug**
I'm using folium maps with TimestampedGeoJson plugin and just realize that custom icons is not working on it ?

**To Reproduce**
Use TimestampedGeoJson example trying to use Custom Icons for markers. 

**Expected behavior**
Plot CustomIcons over maps using TimestampedGeoJson :).

**Environment (please complete the following information):**
 - Firefox
 - Jupyter Notebook
- Python 3.8.3
 - folium  0.11.0
 - branca 0.4.1

**Possible solutions**
Add possibility for using CustomIcons :)

**Comment by PHoltzman** [comment]
I also would like this ability to use custom icons with TimestampedGeoJson.

**Comment by filmkorn** [comment]
There might be a way - take a look at this example setting the `iconstyle` property of the features: https://enhold2.com/coronavirus-propagation-visualization-part-1-history-of-coronavirus/

**Comment by Conengmo** [comment]
I'll close the issue. If somebody has other insights to share on this topic, please share them here!

**Comment by IvanC-Gambit** [comment]
> There might be a way - take a look at this example setting the `iconstyle` property of the features: https://enhold2.com/coronavirus-propagation-visualization-part-1-history-of-coronavirus/

Link doesn't work & solution not really explained. Is this still not working properly?

**Comment by filmkorn** [comment]
> Link doesn't work & solution not really explained

I'm sorry I should have copied over some details. 

It seems that the official examples now include an example of a custom icon:
https://python-visualization.github.io/folium/latest/user_guide/plugins/timestamped_geojson.html#Example-2

**Comment by IvanC-Gambit** [comment]
Thank you. Was able to get custom icons working by hosting on URL but couldn't get local images to work using `file:///` convention.
