### ISSUE TITLE
I'd like to have the generated index.html be dynamic, instead of hardcoding marker values. 

### ISSUE THREAD

**Issue by fpolignano** [python-visualization/folium#1423]
**Is your feature request related to a problem? Please describe.**
I'm building a map based on the results of a response from a REST API. The data that gets returned from the API is dynamic. When I initially created the index.html, I assumed that the JavaScript inserted into the index.html would be dynamic as well, meaning it would make the fetch request to the REST API. However, I recently noticed that the index.html has all the Markers hardcoded, so it's sort of a snapshot of how it looked when I ran the Folium script. 

**Describe the solution you'd like**
I'd like the generated JavaScript to mirror what I'm doing in Python. So for example if in Python I make a request to an API using the requests library, I'd like the generated JavaScript to also make a request to the API. Basically I'd like the code to be a 1:1 translation. 

**Describe alternatives you've considered**
I've done my workflow using just Javascript/Leaflet.

**Comment by Conengmo** [comment]
This is currently not possible with folium. If there's a light-weight plugin we can include to make this possible, we can consider it. Read the contributing guidelines for plugin acceptance criteria. There are no plans to support this in the main library. To do more dynamic stuff you're probably better of doing this in Javascript with Leaflet directly.

**Comment by fpolignano** [comment]
Understood. Thank you
