### ISSUE TITLE
Highlight `__geo_interface__` support in Documentation

### ISSUE THREAD

**Issue by kai-tub** [python-visualization/folium#1424]
**Is your feature request related to a problem? Please describe.**
I was not really aware that `folium` supports to display objects with a `__geo_interface__` protocol until today.
I am relatively new to working with geographic data, so maybe it is obvious for other people,
but I was surprised that it worked without any issues. 

**Describe the solution you'd like**
A note in the documentation that the `__geo_interface__` protocol is supported with `folium.features.GeoJson`, which allows for extensive interoperability with various other Python libraries.

**Implementation**
I am not sure where the best place would be to highlight this feature. Maybe as a note in `Quickstart` with example usage of `GeoPandas`? And a note in the `GeoJson` documentation?

It is an awesome feature, but I feel like it could be easily overlooked (at least from my point of view as a beginner).

PS: Thanks for maintaining this awesome project! 👍

**Comment by Conengmo** [comment]
I think the docstring of `GeoJson` might be a good place for this: https://github.com/python-visualization/folium/blob/master/folium/features.py#L314

Do you want to make a PR?

**Comment by kai-tub** [comment]
I would be happy to :)

**Comment by kai-tub** [comment]
Should we also add an example?
Like loading from shapely or geopandas? 
These seem to be the most prominent `__geo_interface__` libraries that could be frequently combined for analysis with `folium`. (Again from a perspective of a newcomer to this field)

**Comment by Conengmo** [comment]
We already have this example notebook, would this be similar to what you are proposing: https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Geopandas_and_geo_interface.ipynb

**Comment by kai-tub** [comment]
Oh, I missed that example.
Ok, then I will only update the docstring

**Comment by kai-tub** [comment]
As a side-note:
I think that these examples should be more prominently displayed.
I was always looking at the documentation page and not the GitHub Readme and I feel like a link at the end of the *Quickstart* section can be easily overlooked. Maybe we could add an extra section to the tables of content, where there are links to all current examples? Then new users could more easily find starting points for their problems?

Just my 2cts :)

**Comment by Conengmo** [comment]
that's also a good idea. It has bothered me for a while that the example notebooks are not well ordered and have sometimes cryptic names. But I don't want to change the names, because there may be incoming links to them. Linking to them from the documentation sounds like a good way around this.

**Comment by kai-tub** [comment]
Sure. :)
I will open both PRs later today.

**Comment by Conengmo** [comment]
Merged in https://github.com/python-visualization/folium/pull/1425
