### ISSUE TITLE
ImageOverlay does not accept data uris as valid and treats them as file name instead

### ISSUE THREAD

**Issue by Kirill888** [python-visualization/folium#1427]
**Describe the bug**

Supplying a data URI as image parameter to ImageOverlay raise FileNotFound error.

**To Reproduce**

```python
from folium.raster_layers import ImageOverlay
img_url = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="
ImageOverlay(img_url, bounds=[[0,0], [1,1]])
```

**Expected behavior**
Image url is passed into output as is.

**Environment (please complete the following information):**
 - Browser firefox
 - Jupyter Notebook or html files -- jupyter lab?
 - Python version 3.8
 - folium version 0.11.0
 - branca version 0.3.1

**Possible solutions**

Problem is due to `data` scheme being absent from the allow list here:

https://github.com/python-visualization/folium/blob/ae12f975277085e4727f0bd094ad907e3ef11901/folium/utilities.py#L22-L23

Patching it at run time solves the problem, i.e. this works as expected
```python
import folium.utilities
folium.utilities._VALID_URLS.add('data')

from folium.raster_layers import ImageOverlay
img_url = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="
ImageOverlay(img_url, bounds=[[0,0], [1,1]])
```

**Comment by Conengmo** [comment]
Good find! Do you want to open a PR with your fix? Add in a test case to verify behavior?

**Comment by Kirill888** [comment]
Sure, will do, soonish
