### ISSUE TITLE
Choropleth map stopped working?

### ISSUE THREAD

**Issue by psychemedia** [python-visualization/folium#143]
~~I used to be able to key into geojson files using constructions of the form `key_on='feature.properties.KEYVAL'` but this seems to have stopped working?~~  <- still works if data.json is provided...

In particular, it seems that the `data.json` file is not being created (my use case also employs a construction of the form `key_on='feature.properties.KEYVAL'`)? [In particular have some legacy code that appears to have stopped working in respect of `data.json` no longer being created for some reason?]

The official example (which uses `feature.id`) still works in creating the `data.json` file though.

**Comment by ocefpaf** [comment]
@psychemedia  Can you provide a [SSCCE](http://sscce.org/) to help me investigate this further?

(Sorry for the delay to answer!  I was away for a while.)

**Comment by ocefpaf** [comment]
Without an example it is hard to debug this...  Feel free to re-open it if you can provide one.
