### ISSUE TITLE
Double click zoom (GeoJson)

### ISSUE THREAD

**Issue by timurkanaz** [python-visualization/folium#1436]
**Double click** on geometry(GeoJSON) also cause zooming.Can I adjust it?

I have the newest version and new "click_on_zoom" parameter does not change this situation.

**Comment by Conengmo** [comment]
What would be the use-case for disabling zoom on double click?

**Comment by timurkanaz** [comment]
So,I attached GIF.

I made a map and set the max_zoom and min_zoom to the same number so it does not zoom during the double click or just one click. I also want to restrict dragging.However, when I click twice on polygons located on the edge, map is moving.So,if I restricted dragging,user would not be able to return the map in the starting position.
![ezgif-3-a9aee7c131a5](https://user-images.githubusercontent.com/64957540/104165200-1b569f80-540a-11eb-91d6-0ce4690359bf.gif)

**Comment by Conengmo** [comment]
Alright, that's clear.

So first of all the double click is not a GeoJson thing, but a general Leaflet Map thing. https://leafletjs.com/reference-1.7.1.html#map-doubleclickzoom

The good news is the folium `Map` class accepts arbitrary keyword arguments. So you can pass that double click zoom option already. Haven't tried it myself, but can you try (in addition to what you were already doing):

```
m = folium.Map(double_click_zoom=False)
```

**Comment by timurkanaz** [comment]
Shame on me,I have not noticed this keyword in documentation.Now everything works as expected. Thank you!

**Comment by Conengmo** [comment]
Great!

> I have not noticed this keyword in documentation

It's not in the documentation :) It's a `**kwarg` keyword argument.
