### ISSUE TITLE
Folium popup image

### ISSUE THREAD

**Issue by ELEGER** [python-visualization/folium#1437]
Hi thanks for your folium developments.
I'm trying to display a png/jpeg image in a popup.

I spent time trying to figure out what are the different possible code associated with versions, notably, #1387 . Reading the doc, I understood that the direct html reading was [possible]( https://python-visualization.github.io/folium/quickstart.html#Markers). 
My folium version:
print(folium.__version__)
0.11.0

My code, gdf is a simple geopandas frame and row is just a row of this gdf with coordinate.
### Code 

```python
bo=gdf.total_bounds
center=(bo[1] + bo[3])/2, (bo[0] + bo[2])/2
m = folium.Map(center, zoom_start=17,tiles='OpenStreetMap')

html="""
       <p>
           <figure>
             <img src="./data/Pics-1.png" alt="Img" >
             <figcaption><h1>Pics</h1></figcaption>
           </figure>
       </p>
       """

test = folium.Html(html, script=True)
iframe = branca.element.IFrame(html=html, width=500, height=300)
popup  = folium.Popup(html=iframe,max_width=500)
icon = folium.Icon(color='blue', icon='ok')
folium.Marker([row.geometry.y,row.geometry.x],popup=popup,icon=folium.Icon(color=listounet[index])).add_to(m)
m


```
#### Problem description
The icon is here, at correct coordinate, the popup display only the text. I tried with and without iframe, just using test variable. I can see the text interpreted as HTML, but not the image.
 The path is correct, there is a file called Pics1.png in the folder ./data. I tried as well with encoded and base 64 as #1387 and other mentionned. Did not even print the html text.
#### Expected Output
The image in the ifram popup.
#### Output of ``folium.__version__``
```python
print(folium.__version__)
0.11.0
```

**Comment by dambrosbruno** [comment]
I have a similar problem as well

**Comment by Conengmo** [comment]
You can solve this by specifying it's a file. And to be sure I used an absolute path as well:

```

**Comment by Conengmo** [comment]
You can solve this by specifying it's a file using `file://`. And to be sure I used an absolute path as well:

```
    html = r"""<img src="file://C:\Users\myuser\test.png" >"""
    iframe = IFrame(html=html, width=500, height=300)
    popup = Popup(html=iframe, max_width=500)
    Marker(coords, popup=popup).add_to(m)
```
