### ISSUE TITLE
Curious folium version 0.0.0 messes up checks for version requirements

### ISSUE THREAD

**Issue by niklasbohn** [python-visualization/folium#1438]
When executing software tests on azure I run into trouble when checking for the installed folium version. If a package requires a particular folium version I get an error message like that:

`+ pip check`
`arosics 1.2.4 has requirement folium>=0.6.0, but you have folium 0.0.0.`

I just checked the folium [release history on PyPi](https://pypi.org/project/folium/#history) and it indicates that you uploaded folium version 0.12.0 to PyPi on Jan 6, 2021. But if I scroll down to the bottom of the release history, I recognize that the curious folium version 0.0.0 was also uploaded to PyPi on Jan 6, 2021. Would it be possible that you just misleadingly uploaded a folium version 0.0.0? If yes, could you check that and clean up if necessary?

Thanks in advance for any help!

**Comment by Conengmo** [comment]
Thanks for the report! That doesn't look right indeed. @ocefpaf can you see what happened?

**Comment by ocefpaf** [comment]
Probably a mistake in the release :-(

Working on it...

**Comment by ocefpaf** [comment]
Looks like the wheel is fine:

```
> pip install folium
Collecting folium
  Downloading folium-0.12.0-py2.py3-none-any.whl (94 kB)

> python -c "import folium; print(folium.__version__)"0.12.0

```

But the sdist is not:

```
> pip install folium --no-binary :all:                                                                                                                                                                             ⏎
Collecting folium
  Downloading folium-0.12.0.tar.gz (92 kB)
     |████████████████████████████████| 92 kB 382 kB/s 
ERROR: Requested folium from https://files.pythonhosted.org/packages/17/fb/a36b985ccc1c1a7dbd2b92e82578bfeb7627622f986c8d8232df090c5075/folium-0.12.0.tar.gz#sha256=d45ace0a813ae65f202ce0356eb29c40a5e8fde071e4d6b5be0a89587ebaeab2 has different version in metadata: '0.0.0'
```

It is probably some change in setuptools_scm, maybe we need to add the version.py file in the sdist now.

**Comment by niklasbohn** [comment]
@ocefpaf Thanks for dealing with this issue! However, the folium release history on PyPi hasn't changed after pull request #1439 and I still get the same error message as before on azure. I guess you would have to delete the curious version 0.0.0 on PyPi or alternatively, upload a new version so that there aren't two versions released on the same date anymore.

**Comment by ocefpaf** [comment]
We'll issue a bugfix release later today. Stay tuned.

**Comment by Conengmo** [comment]
let me know if there's something I can do to help

**Comment by ocefpaf** [comment]
Installing from the downloaded sdist from PyPI:

```
> pip install folium-0.12.1.tar.gz
Processing ./folium-0.12.1.tar.gz
Collecting branca>=0.3.0
  Using cached branca-0.4.2-py3-none-any.whl (24 kB)
Collecting jinja2>=2.9
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp39-cp39-linux_x86_64.whl
Collecting numpy
  Using cached numpy-1.19.5-cp39-cp39-manylinux2010_x86_64.whl (14.9 MB)
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: certifi>=2017.4.17 in /home/filipe/miniconda3/envs/FOLIUM/lib/python3.9/site-packages (from requests->folium==0.0.0) (2020.12.5)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Building wheels for collected packages: folium
  Building wheel for folium (setup.py) ... done
  Created wheel for folium: filename=folium-0.0.0-py2.py3-none-any.whl size=94907 sha256=c25e26417c2da72d5f796807d40d772cd3ae7fbfb3a09df15bb862f4a369d53d
  Stored in directory: /home/filipe/.cache/pip/wheels/18/aa/79/f67face8f8d26885a26c56f9b74c23fcc6272e88827e25b14c
Successfully built folium
Installing collected packages: MarkupSafe, urllib3, jinja2, idna, chardet, requests, numpy, branca, folium
python -cSuccessfully installed MarkupSafe-1.1.1 branca-0.4.2 chardet-4.0.0 folium-0.0.0 idna-2.10 jinja2-2.11.2 numpy-1.19.5 requests-2.25.1 urllib3-1.26.2
(FOLIUM) 
[filipe@asus 0  ~/Dropbox/pymodules/01-forks/gridgeo/dist] (master) ≀ 
> python -c "import folium; print(folium.__version__)"
0.12.1
```

We get the right version. Now installing directly from PyPI:

```
> pip install folium --no-binary :all:                                                                                                                                                      
Collecting folium
  Using cached folium-0.12.1.tar.gz (93 kB)
ERROR: Requested folium from https://files.pythonhosted.org/packages/54/77/284cfe145e423da3dec84e29a3d544f4d32504107a1eacbfa36ec8d51230/folium-0.12.1.tar.gz#sha256=14063280a0ea448f46e1c3ae1853909ee02bbee7702f3a1e8f0267b353c31183 has different version in metadata: '0.0.0'
```

Not sure what changed in latest pip that is causing this :-( Still investigating.

**Comment by ocefpaf** [comment]
According to this comment this is not fixed and we should use only the binary release for now :-(

https://github.com/psf/black/issues/1847#issuecomment-756446281

I'll remove the sdist and revisit the problem in the near future.

**Comment by danschef** [comment]
Setting the 0.0.0 release on PyPi to "yanked" did not solve the issue on our side (see [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=267394&view=logs&j=bfad34a8-2c6a-5ec9-815d-d056b1a51431&t=c837df70-a669-565a-cdc4-645a9ac0dd32)). However, the 0.12.1 release is still missing on conda-forge. I guess, this would help.

**Comment by Conengmo** [comment]
It seems this is no longer an issue.
