### ISSUE TITLE
Folium Map not rendering on nbviewer.

### ISSUE THREAD

**Issue by navido89** [python-visualization/folium#1444]
**Describe the bug**
Hi there. I have an issue when it comes to displaying my two folium plots inside nbviewer. It was rendering back in December but isn't now for some reason. The plots work perfectly fine when I run it on jupyter notebook, but when I paste my link to nbviewer it doesn't render anymore. I would appreciate any feedback. Please see below the link of my nbviewer and the pictures of the plots:

https://nbviewer.jupyter.org/github/navido89/DS-Job-Market-Analysis/blob/master/Indeed-DS-Jobs-Final.ipynb?flush_cache=True

![F1](https://user-images.githubusercontent.com/40181248/105329315-df4bd900-5b85-11eb-823a-cb6b5410bf26.png)
![F2](https://user-images.githubusercontent.com/40181248/105329324-e246c980-5b85-11eb-90ff-fbc8a2be5101.png)

**To Reproduce**

[ Include a code snippet that produces your bug. Make it standalone, we should be able to run it. ]

![F1-Bug](https://user-images.githubusercontent.com/40181248/105405670-4302f000-5be0-11eb-9c6f-4090560d18f4.png)
![F2-Bug](https://user-images.githubusercontent.com/40181248/105405705-4e561b80-5be0-11eb-8b4f-12952a0c60aa.png)

[ Include a data sample or link to your data if necessary to run the code ]
Please read in the pickle file before the first Seaborn plot in the jupyter notebook. Call the variable df and you can run all the plots. 
https://github.com/navido89/DS-Job-Market-Analysis/blob/master/Data%20Files/indeed_job_ca_clean2.pkl

**Expected behavior**
Folium plots should display which it does. However, it doesn't render in nbviewer. 

**Environment (please complete the following information):**
 - Browser: Chrome
 - Jupyter Notebook or html files?
 - python==3.8.2
 - folium==0.11.0

**Additional context**
Again not worried about the file not running in jupyter notebook. The issue is when rendering it in nbviewer. I add the ipynb link from my GitHub repo. 

This is the link I posted: https://nbviewer.jupyter.org/github/navido89/DS-Job-Market-Analysis/blob/master/Indeed-DS-Jobs-Final.ipynb?flush_cache=True

Could it be because of the line ?flish_cache=True ???

Interesting fact. All my other projects with a folium map render perfectly fine on nbviewer. Also, I had an issue rendering the same plot on google colab with the same tile. Not sure what the issue here. Could it be the tile? 

folium is maintained by volunteers. Can you help making a fix for this issue?

**Comment by Conengmo** [comment]
Please complete the issue template. Which versions are you using? Can you try the latest folium version?

**Comment by navido89** [comment]
@Conengmo I just completed the template. I am using the following Folium version. folium==0.11.0

**Comment by Conengmo** [comment]
Looking at the JS console I see this error: `09:54:04.793 Blocked loading mixed active content "http://unpkg.com/leaflet@1.3.1/dist/leaflet.js"`

folium is currently using Leaflet 1.6.0, and 1.5.* a year ago. We don't reference 1.3.1 in our code anywhere. Neither do we use unpkg.com to load Leaflet. I checked the Javascript for marker cluster and it also doesn't reference that.

By the way, the most recent folium version is 0.12, could you try it with that? Make sure the whole notebook is updated? Another thing to try is to only include the folium map, so we can make sure where that error is coming from.

**Comment by navido89** [comment]
So I just updated folium to 0.12, but it didn't solve the problem, unfortunately. I created a jupyter notebook file with just the map, so you can have a closer look at it. The pickle file that I read in first is on the repo in the Data folder. 

If you click on the repo link below, I noticed that under the map it says: Make this Notebook Trusted to load map: File -> Trust Notebook. I haven't seen this before. I think this could be the issue. I tried fixing the problem but wasn't able to. I followed the docs. 

See doc link here: https://jupyter-notebook.readthedocs.io/en/latest/notebook.html?highlight=trust#signing-notebooks

See the link of the repo with just the folium map as you requested: https://github.com/navido89/DS-Job-Market-Analysis/blob/master/CA-Analysis-Folium-Maps-Notebook.ipynb

Here is the nbviewer link of it: https://nbviewer.jupyter.org/github/navido89/DS-Job-Market-Analysis/blob/master/CA-Analysis-Folium-Maps-Notebook.ipynb

**Comment by navido89** [comment]
Also just for reference. In my jupyter notebook the file is trusted and the plots work fine. Please see attached screenshots.

![Screen Shot 2021-01-22 at 1 03 13 PM](https://user-images.githubusercontent.com/40181248/105546774-a65d5280-5cb2-11eb-84c6-8531307d79d4.png)
![Screen Shot 2021-01-22 at 1 03 39 PM](https://user-images.githubusercontent.com/40181248/105546778-a8271600-5cb2-11eb-8819-9f1e914075c2.png)
![Screen Shot 2021-01-22 at 1 03 45 PM](https://user-images.githubusercontent.com/40181248/105546798-ac533380-5cb2-11eb-8ba5-698f25ddbbd2.png)

**Comment by Conengmo** [comment]
I hope this was solved. If somebody encounters this again, please open a new issue.
