### ISSUE TITLE
Please publish 0.12.1 sdist to PyPI

### ISSUE THREAD

**Issue by sunpoet** [python-visualization/folium#1448]
sdist (folium-0.12.1.tar.gz) is missing on https://pypi.org/project/folium/#files. Would you please publish sdist (folium-0.12.1.tar.gz) to PyPI?

**Comment by ocefpaf** [comment]
It was yanked b/c of a problem in the sdist.  Closing this as a duplicate of https://github.com/python-visualization/folium/issues/1438
