### ISSUE TITLE
Please provide a source dist for the latest release

### ISSUE THREAD

**Issue by sscherfke** [python-visualization/folium#1449]
**Describe the bug**
Folium 0.12.1 no longer as a source dist published alongside the wheel.

**To Reproduce**
–

**Expected behavior**
There is an sdist alongside the wheel

**Environment (please complete the following information):**
 - folium 0.12.1

**Additional context**
Source distributions are needed to repackage folium for conda, rpm, deb etc. 

**Possible solutions**
Create an sdist and upload it ;-)

**Comment by ocefpaf** [comment]
Please see #1438
