### ISSUE TITLE
Implementing a good way to handle plugins

### ISSUE THREAD

**Issue by BibMartin** [python-visualization/folium#145]
Following the discussion with @themiurgo and @ocefpaf in PR https://github.com/python-visualization/folium/pull/144.

@themiurgo has set the question :
> [This also shows the importance of implementing soon a good way to handle plugins. That way we might have a generic add_plugin(plugin_object) for all the plugins and extra functionalities like this, and no need to make changes to the core object Map and its interface]

**Comment by BibMartin** [comment]
I imagine a plugin object can have 3 or 4 methods :
* `render_css` where one can define plugin-specific styles
* `render_html` where one defines new DOM objects
* `render_js` where one defines how the plugin interacts with the maps
* eventually `render_header` where one can define external javascript imports ; yet this could be done into the HTML part (is it ugly?).

You can see examples of this mindset in https://github.com/BibMartin/folium/commit/5238fb98585c1b5482b6a485ee78049838ff33bd or in https://github.com/BibMartin/folium/commit/1a0469266a22ac421e9e40cb5f68a20fc748f8ae.

Maybe the plugins may inherit from a common object that implments these methods so that you don't have to create the 3-4 methods if the plugin does not require it.

**Comment by themiurgo** [comment]
Thanks a lot! This is great, some other help with to lift the plugin effort. :)

Do you think these 3/4 methods are enough to implement all the plugins shown in #127 . If so, we might have a candidate PR from your concepts commits and then iterate from that.

**Comment by themiurgo** [comment]
Also, I like a lot BibMartin@1a04692 . Did you choose the MarkerCluster example on purpose or randomly? MarkerCluster is already present in the folium base template, along with other functionalities that pollute the template. It would be great to handle it as a plugin instead, and keep the base template for the Leaflet  core functionalities.

**Comment by BibMartin** [comment]
> Do you think these 3/4 methods are enough to implement all the plugins shown in #127 ?

I was having a look at them. For some (like esri, terminator, etc) I think this shall be quite easy provided that the generate code follows the scheme `header-stylesheet-body-script`. I'm not sure for all of them now, but we can start with the easiest ones and adapt the scheme when needed, don't you think so ?

> Did you choose the MarkerCluster example on purpose or randomly?

I did not know that it was already present but it looked like a good example on "how to develop a plugin".

**Comment by themiurgo** [comment]
Ok, I'd say let's start a "plugin" branch here, starting from your commits, and collaborate on that. Main goals:
- perfection the plugin skeleton;
- implement as many plugins as possible from #127 ;
- remove as many plugins as possible from `fol_template`.

Once the branch is mature we'll merge back to master.

@ocefpaf, @birdage, any thoughts?

**Comment by themiurgo** [comment]
Instead of having multiple methods to inject code in the template we can leverage Jinja's advanced features (http://jinja.pocoo.org/docs/dev/templates/#template-inheritance), in particular blocks.

Each plugin would only consist of a template file (html) and an (optional) class/function to set up any variables inside the template.

A base template file for all folium maps would define injection points and plugin templates would rely on those. A step towards that is #147 .

**Comment by themiurgo** [comment]
(from the other discussion)
> I cannot figure out how the code would behave if I wanted to combine several plugins. Like for example:

It's not yet clear to me how we can use Jinja for the plugins, but I think we should find a way to avoid writing html in the plugin class.

**Comment by ocefpaf** [comment]
> Also, I like a lot BibMartin@1a04692 . Did you choose the MarkerCluster example on purpose or randomly? MarkerCluster is already present in the folium base template, along with other functionalities that pollute the template. It would be great to handle it as a plugin instead, and keep the base template clean, for the Leaflet core functionalities.

YES!!!!  I will at a look at this with special care once I get back.  @BibMartin Do not worry about perfection, this is a great start!

**Comment by BibMartin** [comment]
A few thoughts from this weekend:

* @themiurgo : We can imagine a way of designing plugins using Jinja templates, and then create the plugin object based on the template's content. A draft of it is in https://github.com/BibMartin/folium/commit/475007a172ff33179e80a7f2d7b760de2dd5b91c.

* I've tried to implement a few plugins mentionned in #127, and came to the conclusion that plugins (as I had it in mind at least) are two things : First, they are *imports* of javascript functions and css definitions. Second, they are *definitions* of new objects shown on the map. In some cases (for `boat_markers` for example), one may be willing to *define* several objects from the same plugin ; we shall not do the *import* step twice. A way to handle this could be https://github.com/BibMartin/folium/commit/0c11b04a03da272cd4d05c2959b6cc4a3e7806ea.

* As for plugins like omnivore or Wicket that enables to read different data formats, I don't really know whether we shall let javascript parse any kind of input, or if we shall create python methods for accepting that kind of input.

**Comment by themiurgo** [comment]
> I've tried to implement a few plugins mentionned in #127, and came to the conclusion that plugins (as I had it in mind at least) are two things : First, they are imports of javascript functions and css definitions. Second, they are definitions of new objects shown on the map. In some cases (for boat_markers for example), one may be willing to define several objects from the same plugin ; we shall not do the import step twice. A way to handle this could be BibMartin@0c11b04.

I've thought of a more general solution. It would be advisable to have each plugin access the map object it is attached to, mainly for two reasons.
- Ensuring maximum compatibility with virtually any plugin. If each plugin has complete visibility of map object, it can know data and the operations that have been performed on it, as long as they modified the object. (Think of a plugin that has to know the number of markers that have been drawn on the map, for example).
- The plugin itself could actually call designated methods on the map object and modify it to its liking.

Another thought. Although Jinja is not strictly needed to implement a plugin, it would be advisable to use it. Folium already relies on such a mechanism to draw objects in the map, for instance here's a snippet from `folium.Map.circle_marker()`.

```python

        circle_temp = self.env.get_template('circle_marker.js')

        circle = circle_temp.render({'circle': 'circle_' + str(count),
                                     'radius': radius,
                                     'lat': location[0], 'lon': location[1],
                                     'line_color': line_color,
                                     'fill_color': fill_color,
                                     'fill_opacity': fill_opacity})

        popup_out = self._popup_render(popup=popup, mk_name='circle_',
                                       count=count)

        add_mark = 'map.addLayer(circle_{0})'.format(count)

        self.template_vars.setdefault('markers', []).append((circle,
                                                             popup_out,
                                                             add_mark))
```

**Comment by BibMartin** [comment]
> Ensuring maximum compatibility with virtually any plugin. If each plugin has complete visibility of map object, it can know data and the operations that have been performed on it, as long as they modified the object.

I do agree with you. We can easily replace the method `Map.add_plugin` by a `Plugin.add_to_map` (and thus be closer to Leaflet's syntax). To ensure maximal compatibility/liberty, the plugin shall be able to access the map information when it is created (in the `add_to_map` method), but also when it is displayed (in a `render` method), the `render`being called when the map html is generated. I think of 

* a plguin that would need to alter others like changing other plugin's popup, or color).

* a plugin that needs to access the final state of the map (the nb of markers finally created, for example ; not only the markers that existed when the plugin was added).

I have no time for prototyping this today, but will try in the coming days.

**Comment by themiurgo** [comment]
There is another problem that I see down the road, that might make some plugins harder to implement. At the moment each folium operation directly and immediately changes the template variables (for example, the list of markers), rather than storing it in a "model" and generating the template variables / the html at the end, all things considered. If a plugin is added and this plugin needs to access all the markers ever created in the map, not only those created up tho that point, it needs to be rendered at the end, not when the `add_plugin`/`add_to_map` is called. This is also problematic if a marker/feature/... needs to access data that is later added to the map (for example other markers, plugins, ...).

There are solutions to this but they seem complicated to implement on top of the existing codebase, and these issues are not urgent. However, it's good to keep in mind we have this limitation.

**Comment by BibMartin** [comment]
You're true. Based on #148, we have *traditional* objects (markers/layers, etc) that are directly stored in the template variable `map.template_vars`, and we have plugins that are stored as objects in the dict `map.plugins`, and that have *render* methods for generating the html/css/js at the end.
And finally, everything is rendered at the same time with

    self.HTML = html_templ.render(self.template_vars, plugins=self.plugins)

In other words, `template_vars` stores objects that are rendered when they are inserted, and `plugins` stores objects that are rendered "at the end". We may progressively move *traditional* objects from `template_vars` to `plugins` (or whatever it's name) to reach a solution to your problem.

I would imagine 2 rules to avoid a terrible mess :

* When a plugin is inserted with `add_plugin/add_to_map`, it can read AND ALTER the map object (other plugins/marker/...)
* When a plugin is rendered with `render_html` and so on, it can only read the map object.

This will let us not bother about the rendering order of plugins ; but this will force the user to think about the order of insertions. For example, a plugin that sets all markers color to blue will only affect marker that were defined before it's insertion. While a plugin that counts the markers would eventually be able to count also the markers inserted after it's definition.

**Comment by themiurgo** [comment]
I would be more in favour of having only one interface to add plugin ("there should be one--and only one-- way to do it") and then let the plugin code itself decide when it wants to act, putting itself in a special list `map.plugin_delayed` if it wants its rendering to happen at the end. We already have some operations that can be achieved in too many ways (like ipython notebook embedding) and it looks messy.

Anyways, let's not overengineer this in advance, we might not need all of this. But it's good to be aware.

**Comment by ocefpaf** [comment]
> Anyways, let's not overengineer this in advance, we might not need all of this. But it's good to be aware.

Indeed.  Remember that the plugin list is not a "must," it is just a list I put together based on things I like.

> I would be more in favour of having only one way to add plugins

True.  Aim for simplicity.  All I saw so far is already better than what we have.  BTW,  we have to tag a release before this!  Since the API will change I plan to bump to 0.2.0 after the merge.

@BibMartin and @themiurgo I am late to this, but I believe folium could not be in better hands.  I really like how you two are handling this.  @themiurgo After this trial-by-fire I think we should @BibMartin to the devs and let him press the merge button on this :wink:

**Comment by themiurgo** [comment]
> @themiurgo After this trial-by-fire I think we should @BibMartin to the devs and let him press the merge button on this 

Agreed!

**Comment by BibMartin** [comment]
Thank you @themiurgo and @ocefpaf  ; I'm honnored and will contribute with pleasure.
But I still feel like a begginner and will need your help.

**Comment by ocefpaf** [comment]
> But I still feel like a beginner and will need your help.

@BibMartin just watch [this](https://www.youtube.com/watch?v=hIJdFxYlEKE) and we'll be OK :stuck_out_tongue_winking_eye:

**Comment by ocefpaf** [comment]
@BibMartin with the merge of #148 and #151 I think we can close this, right?
