### ISSUE TITLE
Vector path options don't accept camelCase

### ISSUE THREAD

**Issue by nwpulver** [python-visualization/folium#1452]
**Describe the bug**
According to documentation, fill opacity is controlled by leaflet kwargs; at least for 'folium.Circle'. The link to the leaflet page suggests the correct arg to change opacity is 'fillOpcatiy'. Using 'fillOpacity' does not throw any error, but it also does not do anything. After searching around online I found someones code snippet where they use 'fill_opacity' instead and that works fine. 

**To Reproduce**

```
m = folium.Map()
folium.Circle(
            location=(34.05,-118) ,
            radius=1,
            fill=True,
            color='red',
            weight = 1,
            fillOpacity=.7
            ).add_to(m)

```

**Expected behavior**
Change the opacity of the fill in a circle marker.

**Environment (please complete the following information):**
- Firefox
- Jupyter
 - Python version: 3.7.6
 - folium version: 0.11.0
 - branca version: 0.3.1

**Possible solutions**
Change Documentation to reflect correct usage. I suspect this issue may be repeated elsewhere with other markers and other options that are not 'fill_opacity'.

**Comment by Conengmo** [comment]
We should accept the camelCase version of the arguments as well.

**Comment by ocefpaf** [comment]
> We should accept the camelCase version of the arguments as well.

I'm on the fence here. I don't like to JS-isfy the Python world but folks reading leaflet docs will be confused. I do like the solution in #1672. Maybe we could just not write exemples using the camelCase to avoid promoting that syntax. (Kind of the problem matplotlib has today, tons of ways to do the same thing just for compatibility with non-python stuff, turns out, it is more confusing in the long term.)

**Comment by ocefpaf** [comment]
> Oops already merged before reading your comment. I agree, let's promote one way of doing things: PEP8.

That was was good for merging regardless. My opinion is that we should support but not promote that kind of syntax.

> But linking to Leaflet docs here and there is quite convenient, I assume you don't mean we should remove those links.

Exactly. We should link to leaflet docs IMO. They are super useful. 

> We should silently accept the camelCase version of the arguments as well.

Perfect!
