### ISSUE TITLE
Add option to remove markers for previous timestamps as we move with time TimestampedGeoJson 

### ISSUE THREAD

**Issue by infinity911911** [python-visualization/folium#1455]
Hello! 
I am working with TimestampedGeoJson to plot markers and their changing through time. 
I am trying to show the changes through time( daily basis)
The main problem that at each timestamp the markers are added above the previous markers added. 
Is there any possibility to only show the markers of the timestamp on the slider?

I can see that someone managed to do some modification on the timestamped_geo_json.py to make it work but he does not share the method. 
https://stackoverflow.com/questions/60909832/folium-timeslider-doesnt-remove-previous-added-marker-in-the-map

Thank you!

**Comment by Conengmo** [comment]
`TimestampedGeoJson` has a `duration` parameter that should help with what you're trying to do.
