### ISSUE TITLE
Clarify in readme what Folium can do

### ISSUE THREAD

**Issue by matkoniecz** [python-visualization/folium#1462]
Is it generator of leaflet-based websites? Something else?

(I am looking for way to create simple GUI in Python that would allow selecting specific map area - and returning it to python code for further processing, and after reading through Readme I have no idea is Folium a proper tool for that job)

**Comment by Conengmo** [comment]
> Is it generator of leaflet-based websites?

Yes.

The readme links to a quickstart that should give you a better understanding. Then there are several example notebooks, also linked to from the readme, that paint a fuller picture. 

I don't think we want to turn the readme in a full documentation, but if you or anyone else sees ways to improve the readme, or other documentation for that matter, PR's are welcome.

**Comment by ocefpaf** [comment]
> I don't think we want to turn the readme in a full documentation,

Agreed! READMEs are not docs and should not hold the answer to every possible user application at all.
Docs on the other hand could use a PR if you want to add examples or FAQ about that.
