### ISSUE TITLE
Map with grey spots or completely grey

### ISSUE THREAD

**Issue by gg-bt** [python-visualization/folium#1463]
**Describe the bug**
It's been a week that I am not able to render anymore my map in my python application, before I was able to see with no issue at all. Now I see grey areas in the map when loaded or when the zoom is applied. 

<img width="324" alt="bug" src="https://user-images.githubusercontent.com/79518966/113501497-878efe00-9536-11eb-8acc-d1b9bad76c3a.PNG">
<img width="1033" alt="bug2" src="https://user-images.githubusercontent.com/79518966/113501533-e94f6800-9536-11eb-9082-617a06c2b086.PNG">

**To Reproduce**
```
import folium
import io
import sys
from PyQt5 import QtWidgets, QtWebEngineWidgets

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)

#view the dataset
    view = QtWebEngineWidgets.QWebEngineView()
    center = [-0.023559, 37.9061928]
    map_kenya = folium.Map(location=center, zoom_start=8)

# save map to html file
    data = io.BytesIO()
    map_kenya.save(data, close_file=False)
    view.setHtml(data.getvalue().decode())
    view.show()
    app.exec()
```

**Expected behavior**
I would expect to be able to load the map with no issue, being able to zoom in and out without having big grey areas.

**Environment (please complete the following information):**
This is basically a standalone map, not relying on any browser.

 - Python version 3.9.2
 - folium version 0.12.1
 - branca version 0.4.2

**Comment by kkangy** [comment]
I have same problem.
The only way to operate the folium on the qtwebengine of pyqt5 that I have tested so far is to add tails="cartodb positron" option now.

**Comment by MStillman** [comment]
Had the same issue, it looks like the only maps working are the German openstreetmap and some of the others , Opentopomap and the cartodb positron, work as well but the .org maps dont. Not checked anymore

**Comment by gg-bt** [comment]
Guys, I am currently using the tile Stamen Terrain and works fine! Never tried again the default one...

**Comment by pstatonwx** [comment]
Super late answer, but to fix this, you may or may not need a MapBox API key. 

Check out some examples how to put them in here: http://leaflet-extras.github.io/leaflet-providers/preview/

For example (no key needed):
```
folium.TileLayer(
            name="White Basemap",
            tiles="https://tiles.stadiamaps.com/tiles/alidade_smooth/{z}/{x}/{y}{r}.png",
            attr="'&copy; <a href='https://stadiamaps.com/'>Stadia Maps</a>, &copy; <a 
            href='https://openmaptiles.org/'>OpenMapTiles</a> &copy; <a href='http://openstreetmap.org'>OpenStreetMap</a> 
            contributors",
            detect_retina=True,
        ).add_to(<your folium map name here>)
```

**Comment by Conengmo** [comment]
Unfortunately this is very likely not something we can help with. Tile images are retrieved from an external server, in case of the OP from OpenStreetMap. If something goes wrong in that connection, you will get grey squares.

If somebody has more insight, please share it here.
