### ISSUE TITLE
Display Markers within the given radius in Folium Maps

### ISSUE THREAD

**Issue by Jainu-s** [python-visualization/folium#1464]
I have created a circle with a certain radius and few markers were available within given radius. Now I want to display only those markers within radius. These feature should work dynamically.

**Comment by meenakshi0910** [comment]
hi @Jainu-s ,Can I work on this?

**Comment by Conengmo** [comment]
Unfortunately that sounds a bit too complex for standard folium. If you have a plugin that does this, we'd be happy to link out to it.
