### ISSUE TITLE
Colorbar for HeatMapWithTime 

### ISSUE THREAD

**Issue by saulomeirelles** [python-visualization/folium#1467]
Hi all, I am wondering whether it is possible to add a colorbar using HeatMapWithTime. I have a xarray dataset with dimensions (lon,lat,time) and I wanted to have a series of overlay images on a Folium map. Is there any option to include a colorbar using HeatMapWithTime?

**Comment by ocefpaf** [comment]
The curated list of plugins is in https://leafletjs.com/plugins.html#heatmaps

At a first glance I could not find any that would allow a colorbar too. I guess that the dynamic nature of the heatmap would make it quite hard b/c it would have to be recomputed for every zoom trigger, position, change, and time!

If you can find one on GH we can probably wrap it here.

@Conengmo is that something you saw before?

**Comment by Conengmo** [comment]
not that I recall. It's what you said, the dynamic nature makes it tricky.

**Comment by Conengmo** [comment]
Related to https://github.com/python-visualization/folium/issues/1550. I'll close this one, since it's unlikely we'll get this done.
