### ISSUE TITLE
AttributeError: module 'folium' has no attribute 'Circle'

### ISSUE THREAD

**Issue by pauloo23** [python-visualization/folium#1475]
When i try to run this code from documentation, it gives me an error. I am using Jupyter Notebook.
Code that i am running: 

import folium
m = folium.Map(location=[45.5236, -122.6750], tiles="Stamen Toner", zoom_start=13)
folium.Circle(
    radius=100,
    location=[45.5244, -122.6699],
    popup="The Waterfront",
    color="crimson",
    fill=False,
).add_to(m)
folium.Circlemarker(
    location=[45.5215, -122.6261],
    radius=50,
    popup="Laurelhurst Park",
    color="#3186cc",
    fill=True,
    fill_color="#3186cc",
).add_to(m)

Error: AttributeError: module 'folium' has no attribute 'Circle'

--Resul from pip list command --- 

![6](https://user-images.githubusercontent.com/28958644/117489002-f6f87300-af64-11eb-9e42-fd4ab665c0f3.PNG)
![5](https://user-images.githubusercontent.com/28958644/117489003-f7910980-af64-11eb-9860-6f275b6b37ee.PNG)
![4](https://user-images.githubusercontent.com/28958644/117489004-f829a000-af64-11eb-8127-1a80c219a004.png)
![3](https://user-images.githubusercontent.com/28958644/117489005-f829a000-af64-11eb-9997-5aaf11a2ce40.PNG)
![2](https://user-images.githubusercontent.com/28958644/117489007-f829a000-af64-11eb-8785-cba9051ddbf1.PNG)
![1](https://user-images.githubusercontent.com/28958644/117489008-f8c23680-af64-11eb-97d7-de42efdad21d.PNG)

**Comment by matkoniecz** [comment]
>  Code that i am running:

Can you format it by putting \`\`\` at line before and after the last line?

```
              it
     preserves
                   whitespace
```

**Comment by Conengmo** [comment]
Unfortunately I can't reproduce this issue. I suspect it has to do with your local installation.
