### ISSUE TITLE
Update Bootstrap 3 to Bootstrap 4

### ISSUE THREAD

**Issue by axohua** [python-visualization/folium#1479]
It is not a problem really, but Bootstrap 4 or 5 implementation instead of Bootstrap 3 can enhance the appearance of the content in popups.

**Comment by ocefpaf** [comment]
It is kind of a low hanging fruit. It can be accomplished by editing this file:

https://github.com/python-visualization/folium/blob/c25c84c888415a8f242e133c97242e26c3070fe6/folium/folium.py#L34

Do you want to send a PR to do it?

**Comment by Conengmo** [comment]
We upgraded to Bootstrap 5: https://github.com/python-visualization/folium/pull/1650. This will be in the upcoming 0.14.0 release.
