### ISSUE TITLE
encoding problems with geojson file

### ISSUE THREAD

**Issue by zoza99** [python-visualization/folium#1483]
Describe the bug
i'm use folium in django framework and i have a problems with encoding geojson file when use features.GeoJsonPopup()

To Reproduce
![image](https://user-images.githubusercontent.com/86885431/124385806-f586c500-dcdf-11eb-92de-9cab740799f2.png)

Code:
import folium
from django.shortcuts import render

def show_map(request):

    m = folium.Map(location=[55.17, 51.00], tiles='OpenStreetMap', name="Light Map",
                       zoom_start=6, attr="My Data attribution")
    folium.features.GeoJson(data= "all_id.geojson"
                            , name="States", popup=folium.features.GeoJsonPopup(fields=["rname", "id"],
                                                                                  aliases=["region_name",
                                                                                           "region_id"])).add_to(m)
    m = m._repr_html_()
    context = {'my_map': m}

    return render(request, 'map/map_render.html', context) 

Environment :

  - Python version (3.8.6)
 - folium version (0.12.1)
 - branca version (0.3.1 (if you use the latest version, a bug appears
 "make this notebook trusted to load map: trust notebook" when loading map))

**Comment by Conengmo** [comment]
Without seeing the data I'm afraid I can't help you.
