### ISSUE TITLE
Markercluster, disable cluster at zoomlevel

### ISSUE THREAD

**Issue by whitedear** [python-visualization/folium#1485]
**Is your feature request related to a problem? Please describe.**
I am frustrated that i cannot seem to find a solution to decluster my Circle(s) at a specific zoom level. The reason i want to cluster is performance and an initial grouping of a lot of circles for overview, but i would still like to see a reasonable amount of my circles on the map when zooming in.

**Describe the solution you'd like**
An option in MarkerCluster to set zoom level at which clustering will not happen. I understand the standard is a zoom level = 2, which for my case is far to low. I have tried different things with MarkerCluster class and the icon_create_function to achieve this, but i lack javascript skills.

**Describe alternatives you've considered**
I found a solution describing the javascript code, but i would like it in python (Folium).
https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld-maxzoom.388.html

**Comment by KarenChen9999** [comment]
I come across this same issue. Has this option been added to MarkerCluster? Or is there way we can do that in python (Folium)?

**Comment by Conengmo** [comment]
@KarenChen9999 thanks for sharing your solution here: https://github.com/python-visualization/folium/issues/1583#issuecomment-1092515316
