### ISSUE TITLE
can't open folium(folium.folium.Map object at 0x000002039034E460)

### ISSUE THREAD

**Issue by hackerdd123** [python-visualization/folium#1486]
**Describe the bug**
can't open folium
![image](https://user-images.githubusercontent.com/26730426/125217783-18266880-e2f4-11eb-87c0-891f163a7ea3.png)

**To Reproduce**

```
[ Include a code snippet that produces your bug. Make it standalone, we should be able to run it. ]

[ Include a data sample or link to your data if necessary to run the code ]

```

**Expected behavior**

**Environment (please complete the following information):**
 - Browser [e.g. chrome, firefox]
 - Jupyter Notebook or html files?
 - Python version (check it with `import sys; print(sys.version_info)`)
 - folium version (check it with `import folium; print(folium.__version__)`)
 - branca version (check it with `import branca; print(branca.__version__)`)

**Additional context**

**Possible solutions**
List any solutions you may have come up with.

folium is maintained by volunteers. Can you help making a fix for this issue?

**Comment by Conengmo** [comment]
Please read the documentation and see the example notebooks for how to use folium: https://github.com/python-visualization/folium
