### ISSUE TITLE
Empty features

### ISSUE THREAD

**Issue by damiles** [python-visualization/folium#1487]
If an empty geojson is added with empty features like:

```
{"type":"FeatureCollection","features":[]}
```
an error is reach:

```
    566         they are functions returning dictionaries.
    567         """
--> 568         test_feature = self.data['features'][0]
    569         if not callable(func) or not isinstance(func(test_feature), dict):
    570             raise ValueError('{} should be a function that accepts items from '

IndexError: list index out of range
```

A simple check will avoid this issue.

https://github.com/python-visualization/folium/blob/ab77557675ee418a07fec4c19456fbfd002df8be/folium/features.py#L571

**Comment by Conengmo** [comment]
Looks like currently an empty features is not allowed. I don't see the point of allowing those. The error message could be better though.

**Comment by Conengmo** [comment]
This was fixed in https://github.com/python-visualization/folium/pull/1213. And this issue is a duplicate of https://github.com/python-visualization/folium/issues/1212.
