### ISSUE TITLE
Any method for custom TimestampedGeoJson features?

### ISSUE THREAD

**Issue by WenbinBAI** [python-visualization/folium#1489]
I trying to do a ship's trajectory animation. Every ship data has a timestamp, and I want to use TimestampedGeoJson to make an animation of the ship moving with the timestamp. 
But it seems like the TimestampedGeoJson contains only features of types LineString, MultiPoint, MultiLineString, Polygon, and MultiPolygon. So I want to ask are there any methods to custom the features or other ways to make animation with a time slider?

For now, I can only draw static images every minute.
The following fig is the result：
![image](https://user-images.githubusercontent.com/77138767/125610262-284f2370-c306-4911-830c-e19a02072f20.png)
![image](https://user-images.githubusercontent.com/77138767/125610502-adbb091a-e2b3-48ee-900c-768c29dd60ee.png)

There are 6 parameters for each ship: (Timestamp, Longitude, Latitude, Course, Speed, Length)
And 3 elements for each ship pattern: 
1, Circle：Representative ship size (radius=length/2);
2, PolyLine: Representative ship predicted position (Indicates heading);
3, RegularPolygonMarker(triangle): Indicates heading.

If there is anything unclear, please comment.
I would be very appreciated.

**Comment by HAKUXX** [comment]
Here is my code
`
import folium
from folium import plugins
import os
import pandas as pd
import numpy as np
from datetime import datetime
import math
import webbrowser as wb
import ipywidgets as widgets
from IPython.display import display
#from folium import plugins

#DEGREE AND RAD
toRAD = math.pi / 180
toDEG = 180.0 / math.pi
#MILE AND 
toMILE = 1/1852
toKm = 1852

        
#set GUI
hourslider=widgets.IntSlider(value=12,min=0,max=23,step=1,description='Time:',disabled=False,orientation='horizontal',readout=True,readout_format='d')
minuteslider=widgets.IntSlider(value=28,min=0,max=59,step=1,description='Minute:',disabled=False,continuous_update=True,orientation='horizontal',readout=True,readout_format='d')       
btnup=widgets.Button(description = "up")
btndown=widgets.Button(description = "down")
btn = widgets.Button(description = "load") 

display(hourslider,minuteslider)
box = widgets.Box([btnup,btndown,btn])
display(box)

btn.on_click(btn_click )
btnup.on_click(btnup_click )
btndown.on_click(btndown_click)


# BASELAT,LON
baselat = 35.15
baselon = 139.8
# Create map and display it
m = folium.Map(location=[baselat,baselon],zoom_start=11,width = '60%',attr= ('map'))#control_scale=True

def btnup_click(sender):
    minuteslider.value+=1
def btndown_click(sender):
    minuteslider.value-=1
def btn_click(sender):
    #define the fpath
    hour=hourslider.value
    minute=minuteslider.value
    if hour<10:
        hour='0'+str(hour)
    else:
        hour=str(hour)
    if minute<10:
        minute='0'+str(minute)
    else:
        minute=str(minute)
    currenttime=hour+minute
    fpath=R"Minute Data/2018-1-1-"+hour+minute+".csv"
    #print(fpath)
    
    draw_ship(fpath)
    m.save(currenttime+'.html')
    wb.open(currenttime+'.html') 
`

`
def draw_ship(fpath):
    #Read csv data
    data = pd.read_csv(fpath,encoding="utf-8", names=['Time', 'lat','lon', 'course','length','mmsi','spd','name'])
    #Data deduplication
    df = data.drop_duplicates('name')
    #count ship on the map
    count=df.count()
    count=0
    for Time,lat,lon,course,spd,length,name in zip(df['Time'],df['lat'],df['lon'],df['course'],df['spd'],df['length'],df['name']):
        #draw ship marker
        marker= folium.RegularPolygonMarker([lat,lon],number_of_sides=3, 
                                        rotation=28.5+course, 
                                        radius=12, 
                                        fill=True,
                                        fill_color='blue'
                                       ).add_to(m)
        #draw ship radius
        folium.Circle(  radius=length/2,
                    location=[lat,lon],
                    color='red',
                    popup=(Time,name,length,course,spd),
                    fill=True,
                     ).add_to(m)
        #pposition
        plat = spd*math.cos(course*toRAD)/60 + lat
        plon = spd*math.sin(course*toRAD)/60/math.cos(lat*toRAD) + lon
        #draw course
        folium.PolyLine(locations=[[lat,lon],[plat,plon]],color='blue',popup=(plat,plon),weight=1).add_to(m)
        count+=1
    print(count)
`
Here are a few sample files:
[2018-1-1-1220.xls](https://github.com/python-visualization/folium/files/6815565/2018-1-1-1220.xls)
[2018-1-1-1225.xls](https://github.com/python-visualization/folium/files/6815566/2018-1-1-1225.xls)
[2018-1-1-1224.xls](https://github.com/python-visualization/folium/files/6815567/2018-1-1-1224.xls)
[2018-1-1-1222.xls](https://github.com/python-visualization/folium/files/6815568/2018-1-1-1222.xls)
[2018-1-1-1221.xls](https://github.com/python-visualization/folium/files/6815569/2018-1-1-1221.xls)

**Comment by Conengmo** [comment]
Possibly related to https://github.com/python-visualization/folium/issues/718?

I'm afraid this is a bit more advanced than what I can easily help you with. I'll close the issue since this is probably a bit too specific and complex to include in the folium library. If somebody wants to prove me wrong I'd be happy to see it!
