### ISSUE TITLE
Display of raster data

### ISSUE THREAD

**Issue by andrewgiessel** [python-visualization/folium#149]
I would like to take generate a numpy array and display it as a semi-transparent layer on a leaflet map via folium.  What is the best way to do this?  I recognize that this simple sounding request could actually be quite challenging, but I'm willing to make the effort.

Can anyone point me in the right direction?  Do I really need to generate a full blown tile set using a separate webserver like TileCache?

**Comment by ocefpaf** [comment]
@andrewgiessel I am unsure about the best course to implement something like this.  However, if your image is small enough, you can try `imshow`+`mplleaflet`

**Comment by ocefpaf** [comment]
OK, I tried my own advice and found out it does not work.  `mplleaflet` uses `mplexporter` under the hood, and `mplexporter` does not transform images (yet).

I went ahead and hacked a simple "image overlay" that could be easily added to folium's API:

https://ocefpaf.github.io/python4oceanographers/blog/2015/07/13/interactive_geo/

Do you want to try to implement that?

**Comment by andrewgiessel** [comment]
Wow, this is great!  Sorry I didn't respond earlier.  I am going to try to re-implement this locally and then probably take a crack at a PR.  One thing I was wondering was about transparency and that's possible!  My only question is how this might perform on a large scale (global) since it's basically not tiles.  This is very encouraging, though, thank you for the effort and I'll report back.

Including this for reference:
http://leafletjs.com/reference.html#imageoverlay

**Comment by ocefpaf** [comment]
> My only question is how this might perform on a large scale (global) since it's basically not tiles.

That will depend on the image.  However, if you can set a WMS up you can easily add that layer in a folium instance.

**Comment by andrewgiessel** [comment]
I might be forced to do that, but would like this for rapid visualization of geospatial fields, so if i can get it working with something simple for local purposes (even if it's not performant) that'd be great.

So, I got your example to work!  However, it doesn't seem to work with local files.  As far as I can tell [here](https://github.com/Leaflet/Leaflet/blob/master/src/layer/ImageOverlay.js#L114), Leaflet just makes an <img> in the DOM.  I thought that this should work with a file:// url, but no luck yet.  Ideas?

**Comment by andrewgiessel** [comment]
This is a slightly separate issue, but when I try to open the generated html in another tab, I get a ton of errors because all the external javascript and css references don't start with `http:`.  Shouldn't this be changed?  I can open a PR for that, later.

**Comment by ocefpaf** [comment]
> This is a slightly separate issue, but when I try to open the generated html in another tab, I get a ton of errors because all the external javascript and css references don't start with http:.

This is already on master.  I need to issue a new release (which I thought I did :flushed:)

> I thought that this should work with a file:// url, but no luck yet. Ideas?

Relatives paths "should" work, but I only tested them locally.  The example I uploaded I used a URL.

**Comment by andrewgiessel** [comment]
I am using 0.1.4.  I'll upgrade to master here and see if that changes anything.

**Comment by andrewgiessel** [comment]
First, I upgraded to master (0.1.5) and the relative path thing in the generated file is fine.

I have this working with a local file but there were two small wrinkles:

1) you aren't allowed to load any local file with an absolute path in Chrome.  
2) If you use a path relative to the current notebook URL (NOT the current python path!), it is ok.  Embedding the map.html file assumes the same thing.  The underlying issue is that the `iframe` uses a `src` attribute, which works in the context of the URL.  I'm not sure if there is a clean way around this, other than not supporting inline maps in any other directory other than the one that the kernel started in, and anyway it's a more distal problem.

I think the path forward is pretty clear.  I think the method would be something like `imageOverlay()` and would take a string of a file name (relative to current URL path) OR a 2d numpy array, which should be rendered as a temporary .jpg via MPL, PIL or ImageIO's export (this filename would then be passed on).  It should also take opacity and extent options.  Handling the export well is the hardest part of this.

@ocefpaf Thoughts?

**Comment by andrewgiessel** [comment]
My notebook building off your work, for locally generated arrays.  http://nbviewer.ipython.org/99af788cf7e83b5fdcc6

this should work locally, except for the map.  Here is a screen cap:

![image](https://cloud.githubusercontent.com/assets/1160997/8756730/67e4eefa-2ca2-11e5-952d-a66dc523fcf6.png)

**Comment by andrewgiessel** [comment]
I'll note one last thing about using this:  If you make a large image and have the extent cover the whole globe, then if you zoom in, at a certain level the browser cuts out the layer.  It is a known problem with a workaround (evidently) in the CSS, see [here](https://github.com/Leaflet/Leaflet/issues/2282).   I haven't tested it, because folium uses a CDN version of 0.7.3 for the .css file.

After I implement this I might try the fix, pointing it to a github hosted custom version of the css.

Now I just need to crank out a PR so we can drop this into the html file directly.

**Comment by ocefpaf** [comment]
> I don't know how you feel about adding a dependency, but ImageIO does the job perfectly. I'll post a notebook in a second...

As long as we document this feature with a note with "Need optional dependency X" I am OK.  We already have a couple of features that are like that.

**Comment by andrewgiessel** [comment]
closing!
