### ISSUE TITLE
Beginner question - How to plot boundaries from shapefile

### ISSUE THREAD

**Issue by Alcampopiano** [python-visualization/folium#1495]
Hello,

I'm getting back into Folium after a few years. Love this library. I am trying to plot the boundaries in the data but my map doesn't show any of them when rendered.

I downloaded the [Canadian census boundary files](https://www12.statcan.gc.ca/census-recensement/alternative_alternatif.cfm?l=eng&dispext=zip&teng=lct_000b16a_e.zip&k=%20%20%20%20%208247&loc=http://www12.statcan.gc.ca/census-recensement/2011/geo/bound-limit/files-fichiers/2016/lct_000b16a_e.zip), which is a folder containing files with these file extensions:
- .shx
- .shp
- .prj
- .dbf

Based on [this Folium example](http://python-visualization.github.io/folium/quickstart.html#Choropleth-maps), I converted my data to a GeoJSON file and then used the Choropleth method to try and see the boundaries:

```python
df_geo=geopandas.read_file('census_shape_file.shp')
df_geo.to_file("canada_census.geojson", driver='GeoJSON')

m = folium.Map(location=[48, -102], zoom_start=3)

folium.Choropleth(
    geo_data='canada_census.geojson',
    name="choropleth",
).add_to(m)

folium.LayerControl().add_to(m)

m
```

The map shows up but there are no bondaries plotted in Canada. It's been a while since I used Folium or geographical data. Could anyone point me in the right direction?

**Comment by Conengmo** [comment]
I'm afraid I cannot help you fully here, but I do want to point out that maybe you can use the `GeoJson` class instead, since you're only plotting a geojson, not adding numerical data to it.

**Comment by Alcampopiano** [comment]
Thanks Frank. I will certainly try. My thinking was that, since the example in the docs using US states still works without adding numerical data, then I should be fine with my example too. I'm sure I'm doing something wrong.

Is there a Folium community/Slack I can join to learn more?

**Comment by Conengmo** [comment]
Possibly Stackoverflow is your best bet. There's Gitter, but I haven't seen many answers on there. If there's another community, I don't know about it, but to be fair I'm not that involved in that.

**Comment by Alcampopiano** [comment]
Success! Turns out my polygons were not projected to the right coordinate system. This solved it:

```python
my_geo_data['geometry'] = my_geo_data['geometry'].to_crs(epsg=4326)
```
