### ISSUE TITLE
Export timestampedgeojson movie to mpeg or similar

### ISSUE THREAD

**Issue by SpacelySpaceSprockets** [python-visualization/folium#1499]
I've been using the timestampedgeojson plugin to generate movies of things moving around on a map.  I'd really like to be able to export them to a format that I can easily share with others, like an mpeg video or similar

Maybe there's a way to do this and I'm just being thick headed?

**Comment by Conengmo** [comment]
Folium doesn't have something for that. I'm thinking your best bet is to use something to record your screen. Loads of options for that. Then share a video of you operating the map.
