### ISSUE TITLE
Reducing folium width/height produces white space on the borders

### ISSUE THREAD

**Issue by GitHunter0** [python-visualization/folium#1501]
This issue is based on this stackoverflow question: https://stackoverflow.com/questions/64792041/white-gap-between-python-folium-map-and-jupyter-notebook-cell

Reducing folium width/height produces white space on the borders:
```
import folium
m = folium.Map(width='70%', height='50%')
m
```

The workaround is to use branca.element.Figure class:
```
from branca.element import Figure
fig = Figure(width='70%', height='50%')
m = folium.Map()
fig.add_child(m)
```

Thank you

**Comment by Conengmo** [comment]
Perfect, thanks for sharing this!
