### ISSUE TITLE
plugins.TimeSliderChoropleth() time slider bar out of order for date range that spans '2001-09-09'

### ISSUE THREAD

**Issue by Ade-StapleHill** [python-visualization/folium#1502]
folium.plugins.TimeSliderChoropleth()  creates a time slider bar with dates earlier than 
2001-09-09 coming after later dates.

For example,  the following code creates an ordered date sequence for  ['2001-08-31', '2001-09-30', '2001-10-31']:
    dt_index = pd.date_range('2001-08-1', periods=3, freq='M').strftime('%s')

However, the html time slider generated is in order ['2001-09-30', '2001-10-31',  '2001-08-31'], notice  '2001-08-31' is last and should be first. 

This is an annoying bug when you have time records that span multiple decades before and after year 2001.

The problem is due to the plugin performing an alphabetic string sort of dates (where '9' is  greater  '100') when it should be doing a numerical. The threshold date of 2001-09-09 02:46:40 has a timestamp = '1000000000' seconds.

I have a fix with a test case and  I will create a PR

**Comment by Conengmo** [comment]
This should be fixed with https://github.com/python-visualization/folium/pull/1503, which will be in the upcoming 0.14.0 release.
