### ISSUE TITLE
FeatureGroup is displaying the markers using show=False, control=False

### ISSUE THREAD

**Issue by juanxo90** [python-visualization/folium#1506]
I was trying to use folium.FeatureGroup(show=False, control=False) (i did the same with polygons and work), nevertheless while I am using msrkers I got this problem.

I can find a solution could be the use of transparent marker, but how can I do it a format of transparent marker?

Does anyone have some solution...

Cheers

**Comment by Conengmo** [comment]
Indeed if you use both `show=False` and `control=False` on a FeatureGroup, it will show the underlying content. You could say that's a bug, but I don't see the use case for creating a permanently hidden feature group. So we are probably not going to fix this. If there is a use case for this I'd be curious to hear about it!
