### ISSUE TITLE
Need some help with creating a map with folium using an ecxel import

### ISSUE THREAD

**Issue by stefanbose** [python-visualization/folium#1512]
Hi there,

I would need some help! By now i used this short code to design a map with folium:
[pyton_folium_test.txt](https://github.com/python-visualization/folium/files/7111729/pyton_folium_test.txt)

The next step for me is to learn how to import positions like this from an excel file, but here i got stuck the last two days. I tried to do the import with pandas, xlrd and also OPENPYXL, but i dont fit to the end. Am i right here to find help for it? can someone help me with that?

Excel below will be an example file to import and the screenshot is how the result should look like.
[Eingabe_Python.xlsx](https://github.com/python-visualization/folium/files/7111732/Eingabe_Python.xlsx)
![Screenshot 2021-09-05 160541](https://user-images.githubusercontent.com/90141684/132129829-884ebdf5-7b06-4ab7-867d-f080654c39b4.png)

**Comment by Conengmo** [comment]
Hi @stefanbose, you probably won't get the help you need on this issue tracker. Maybe try Stackoverflow?

**Comment by stefanbose** [comment]
okay thank u i try it there then :)
