### ISSUE TITLE
Is it possible to modify follium generated map with javascript?

### ISSUE THREAD

**Issue by tomlinguist** [python-visualization/folium#1514]
I would like to add a marker once a follium map is generated with javascript.

How would I find the map object from leafletjs part?

**Comment by Conengmo** [comment]
When you look at the rendered html + JS, you should be able to pick out the map object. It looks like this: `var map_b7ea3c68e98f8843c73c5b57a10e1c3d = L.map(`. Though the variable name is different every time.
