### ISSUE TITLE
fit_bounds does not properly work with zoom options. 

### ISSUE THREAD

**Issue by nick9arcia** [python-visualization/folium#1515]
I have been plotting 30k+ coordinates on a map using folium and according to the documentation, the fit_bound function takes the outter most points and creates a bounding box around it. The only issue is that there is so much white space (map where there are no plots) shown on the map (html). Is there a way around this?

**Comment by Conengmo** [comment]
Not sure what we can do about it. Maybe group your features in feature groups, then call fit bounds on the feature group you want to focus on?
