### ISSUE TITLE
Is it possible to use a dict as a geojson file?

### ISSUE THREAD

**Issue by AndrewMarines** [python-visualization/folium#1517]
Just asking before trying. 
I have a lot of towns as objects in a dictionary. 
I'd like to import that dictionary into the geojson function but I can't export and import it everytime cause it's a really big file. Tips?

**Comment by pmains** [comment]
Yes, you can pass the GeoJSON dictionary dictionary directly to the GeoJson constructor. Try the following in a Jupyter Notebook to confirm.

```
url = (
    "https://raw.githubusercontent.com/python-visualization/folium/main/examples/data"
)
us_states = f"{url}/us-states.json"

geo_json_data = json.loads(requests.get(us_states).text)

m = folium.Map(location=[38, -96], zoom_start=4)
folium.GeoJson(data=geo_json_data).add_to(m)
m
```
