### ISSUE TITLE
How to disable javascript alert

### ISSUE THREAD

**Issue by seghier** [python-visualization/folium#1518]
Hello
I used custom java script and when it is in use a message appear with title : javascript alert
How i can use the data without see this message?

![image](https://user-images.githubusercontent.com/6026588/137037195-755c9cab-05c0-452a-b15d-177f78c264ea.png)

**Comment by Conengmo** [comment]
Agreed that it's a bit weird to have that hard-coded. We could at least offer the option to turn that off.
