### ISSUE TITLE
behavior at low zoom levels bug

### ISSUE THREAD

**Issue by JunUmeda1988** [python-visualization/folium#1526]
When using the polylineoffset plugin, there is an error that the line is rounded if the ZOOM level is low.
https://github.com/bbecquet/Leaflet.PolylineOffset/pull/21
The leaflet has been modified, so please take action as well.

**Comment by Conengmo** [comment]
If there's a new version of that plugin, you can open a PR for folium to use that new version: https://github.com/python-visualization/folium/blob/master/folium/plugins/polyline_offset.py#L44. Other than that this is not something that can be fixed in folium.
