### ISSUE TITLE
More customisable colors for Markers and/or adding missing colors

### ISSUE THREAD

**Issue by Timelessprod** [python-visualization/folium#1531]
Hi,

There's something I dont really understand in markers colors : Why can't we use something more customisable like hexadecimal values or RGB channels, and at least, why is there lacking colors such as yellow ? If I wanna make a gradient of colors on my markers according to the temperature at those locations, I would have a hard break between green and orange :/

Thanks

**Comment by dambrosbruno** [comment]
That's the one million dollar question! I'd like to know it as well.

**Comment by Conengmo** [comment]
Our default markers use a fixed set of images, so you can't choose any color you like. You can use a `DivIcon` for that. For example:

```
Marker((0. 0), icon=DivIcon(html='<span style="color:red">hi</span>'))
```

**Comment by Conengmo** [comment]
Related to https://github.com/python-visualization/folium/issues/1466
