### ISSUE TITLE
Adding support for FontAwesome Beta 6.0

### ISSUE THREAD

**Issue by Timelessprod** [python-visualization/folium#1532]
Hi !

FontAwesome has released the Beta 6.0 of their icons since a year and a half now (June 2020). This update added a bunch of needed icons that were missing on version 5 (that is currently used by Folium). Thus, can you please consider upgrading to the Beta 6.0 please ?

Thanks

**Comment by Timelessprod** [comment]
Or at least add support for Font Awesome v5.25 please. There's almost nothing in V4

**Comment by junghosub** [comment]
I really agree with you 😢
