### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#1534]
@Conengmo I believe it is about time we do that here. Are you OK with the change? Do you mind if I start to put it in motion?

**Comment by Conengmo** [comment]
Sounds good! Go ahead

**Comment by ocefpaf** [comment]
Done! GH recommends we do issue the following commands:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

I also renamed it on my fork BTW to make it simple. But we push the new main and delete the old master as well. Both works.
