### ISSUE TITLE
Source distribution for 0.12.1?

### ISSUE THREAD

**Issue by dopplershift** [python-visualization/folium#1536]
Unlike previous releases, the 0.12.1 release on PyPI only has a single wheel file, no `.tar.gz` source distribution. Would it be possible to get a source distribution uploaded?

**Comment by ocefpaf** [comment]
> Unlike previous releases, the 0.12.1 release on PyPI only has a single wheel file, no `.tar.gz` source distribution. Would it be possible to get a source distribution uploaded?

I the irony! I always give folks who do that a hard time but now I'm on the other side :smile: 

I'll work on it but if I recall we yanked it b/c of a versioning issue. I should fix that first.

**Comment by ocefpaf** [comment]
B/c we yanked v0.12.1 I had to do a v0.12.1.post1 instead. See https://pypi.org/project/folium/0.12.1.post1/
