### ISSUE TITLE
In `_to_png`, it'll be nicer to use `driver.fullscreen_window()` instead of using `driver.maximize_window()`.

### ISSUE THREAD

**Issue by liusida** [python-visualization/folium#1539]
Thank you for providing such a great tool. I was using folium to export some PNG images, and concatenating them into a video. However, the dimension of the exported PNG image is a little bit smaller than common dimensions like 1366x768.
I digged into the source code a bit and discovered that in function `_to_png()`, `driver.maximize_window()` was used. If I change this to `driver.fullscreen_window()`, the dimension of the exported PNG will be the resolution of the (imaginary) screen, like 1366x768.

https://github.com/python-visualization/folium/blob/d697154c0fe6c2551889cbfc535b1e4bfb8a3be1/folium/folium.py#L325

This could be a minor improvement. 

And btw, does anyone know how to control the (imaginary) screen resolution? Thanks.

**Comment by kburchfiel** [comment]
I don't have much familiarity with to_png(), but in the meantime, I am using Selenium to create very large screenshots of my maps. Feel free to use the Selenium code near the bottom of this file (starting with "# Finally, the function uses the Selenium library to create a screenshot"): https://github.com/kburchfiel/census_folium_tutorial/blob/master/census_folium_viewer.py
