### ISSUE TITLE
folium 0.12.1.post1 does not have a wheel

### ISSUE THREAD

**Issue by bollwyvl** [python-visualization/folium#1540]
Hi folks! It looks like the most recent release of folium is _only_ a `.tar.gz`, and not a `.whl`. This is in contrast to historical releases that only contain `.whl` files.

I guess it would be lovely to have _both_ for each release.

Motivation: we offer `folium` for use in-browser with `jupyterlite`, which at present only supports `(py2.)py3-none-any.whl` files.

**Comment by ocefpaf** [comment]
Done. See https://pypi.org/project/folium/#files

Thanks for letting us know! This post release is virtually the same for the wheel, we only fixed a minor metadata issue with the sdist. But it makes sense to release it anyway to avoid breakages like that.

**Comment by bollwyvl** [comment]
Great! I worked around it with --prefer-binary, so can't promise I'll catch
future issues!
