### ISSUE TITLE
examples on nbviewer returns 404

### ISSUE THREAD

**Issue by clausmichele** [python-visualization/folium#1541]
**Describe the bug**
The link to the example notebooks is broken: https://nbviewer.org/github/python-visualization/folium/tree/master/examples/

**Comment by ocefpaf** [comment]
> **Describe the bug** The link to the example notebooks is broken: https://nbviewer.org/github/python-visualization/folium/tree/master/examples/

We should update it to reflect the master to main move. Try https://nbviewer.org/github/python-visualization/folium/tree/main/examples/, it should work.
