### ISSUE TITLE
Support style_function for TimestampedGeoJson

### ISSUE THREAD

**Issue by janikmu** [python-visualization/folium#1548]
**Is your feature request related to a problem? Please describe.**
It is possible to use the style_function parameter to pass a style function to GeoJson layers and manipulate e.g. line color. Currently this is not possible for TimestampedGeoJson layers, and consequently all features look the same, without the ability to manipulate appearence. This is especially frustrating when features need to be distinguished in the map.

**Describe the solution you'd like**
Giving the user the ability to provide a style_function similar to what is alread implemented in GeoJson would be nice.

**Describe alternatives you've considered**
No alternative seems possible because styling properties cannot be directly written into the GeoJson - it is ignored by leaflet.

**Additional context**

**Implementation**
Can't help, not versed with leaflet and folium.

**Comment by Conengmo** [comment]
You can already style each feature. `TimestampedGeoJson` contains this line:

```
style: function (feature) {
                        return feature.properties.style;
                    },
```
 
Meaning any styling defined in `feature.properties.style` will be applied to the feature. This is also shown in the plugins example notebook: https://nbviewer.org/github/python-visualization/folium/blob/main/examples/Plugins.ipynb#Timestamped-GeoJSON
