### ISSUE TITLE
Load existing html file generated by folium

### ISSUE THREAD

**Issue by wuvapour** [python-visualization/folium#1549]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here

```
#### Problem description

I want to know how to load an existing html file generated by folium so that I can edit it.

**Comment by mcworkaholic** [comment]
I don't know what environment you're using, but I use pycharm or vscode.

I use `m.save("map.html")` in map_generation.py

to save the generated map's html file within the project folder. You can then move this to wherever, like vscode to view and edit as you please.
