### ISSUE TITLE
Handling external and internal dependencies

### ISSUE THREAD

**Issue by BibMartin** [python-visualization/folium#155]
Folium generates a web page that depends on several objects (css,js,json, data...). These objects may be :
* provided by an external web page or web service
* stored on the disk
* embeded into the HTML file

I wonder how folium shall handle that dependencies. Depending on what you need, on how you serve your web page, etc, you may be willing to have everything embeded into a single html, or to have things loaded on the fly.
It becomes tricky when trying to implement plugins that depends on libraries that are only served on HTTP (or only HTTPS).

One could:
* Have every dependency downloaded when installing Folium
* Have everything downloaded when generating the map
* Have everything linked into the html ; so that they are downloaded by the client directly
* Provide a choice between the former strategies

**Comment by themiurgo** [comment]
I'm not sure I understand this. I see two potential problems:
- plugins/resources served only on HTTP/HTTPS.
- resources available only locally (like a json file);

On the other hand I don't understand what you mean by "have every dependency downloaded when installing Folium"? If Library X is not served online, how would you install it? Please provide an example.

**Comment by BibMartin** [comment]
If library X is served only on HTTP and I serve my map over HTTPS, then I can :
* Download it when I install folium (for example have `urllib` downloading it into `setup.py`, or have it in the project's requirements), though it's probably not the best solution to me.
* Donwload it when generating the map.

And once I have downloaded it ; I have the choice between
* Serve it and link to it
* Embed it into the main HTML.

Antoher potential problem (I have face recently with Leaflet-terminator) is :
* plugins/ressources whose url changes.

**Comment by ocefpaf** [comment]
> plugins/resources whose url changes.

Yep, that sucks... We have to face that we just cannot keep track of all URL resources.

We still have some objects that might be either stored on the disk or embedded into the HTML file.  I am one the fence here.  On one hand "embedding" would return a stand alone HTML file, while storing on disk would be "cleaner" (people keeping their HTML under version control like that).

But I digress... I think your concern are the only the plugins, right?

In that case I would avoid downloading and installing non-served dependencies.  We should keep it simple and rely on served (hopefully stable and preferably over HTTPS scheme) libraries.

**Comment by themiurgo** [comment]
Ok, I now see what you mean.

I would make a few simplifying assumptions to avoid covering all scenarios:
- the plugin resources are available over HTTPS (for example, for Leaflet Terminator you can use https://rawgit.com/joergdietrich/Leaflet.Terminator/master/L.Terminator.js)
- resource URLs do not change (often).

It is much easier to find/ask/provide a HTTPs URL for all the plugin resources than to fix this in folium.

**Comment by ocefpaf** [comment]
> It is much easier to find/ask/provide a HTTPs URL for all the plugin resources than to fix this in folium.

:+1:

**Comment by ocefpaf** [comment]
@BibMartin are you OK with this?  Or do you still think there is advantage in downloading stuff?  Can we close this?

**Comment by ocefpaf** [comment]
Ping!
