### ISSUE TITLE
trouble getting FloatImage to work with locally stored .png and .svg files

### ISSUE THREAD

**Issue by kburchfiel** [python-visualization/folium#1562]
**Describe the bug**

It seems more likely that this is related to an error on my end than to a bug, but I'm having trouble getting FloatImage to display images on maps that are stored locally on my computer. I would like to get this feature working in order to plot custom map legends

**To Reproduce**

```
import folium
from folium.plugins import FloatImage
import base64
import matplotlib.pyplot as plt

# Creating image data
test_svg = plt.plot([0, 1], [0, 1])
plt.savefig('test_fig.png')
plt.savefig('test_svg.svg')

m = folium.Map([40, -100], zoom_start = 5)

# Trying out three different image import methods
# Method 1: Read the image files using b64encode
base64_png = base64.b64encode(open('test_fig.png', 'rb').read()) 
# Based on https://nbviewer.org/gist/ocefpaf/20aa2e74e11db30da2ff07c45cd74816
base64_svg = base64.b64encode(open('test_svg.svg', 'rb').read())

# Method 2: Read the image files using b64encode, then decode them
decoded_base64_png = base64.b64encode(open('test_fig.png', 'rb').read()).decode() 
# Based on https://stackoverflow.com/questions/58227034/png-image-not-being-displayed-on-folium-map
decoded_base64_svg = base64.b64encode(open('test_svg.svg', 'rb').read()).decode() 

# Method 3 (see below) involves directly adding the image path to FloatImage

# Now attempting to plot the images on the map
FloatImage(base64_png, bottom = 10, left = 10).add_to(m)
FloatImage(base64_svg, bottom = 20, left = 20).add_to(m)
FloatImage(decoded_base64_png, bottom = 30, left = 30).add_to(m)
FloatImage(decoded_base64_svg, bottom = 40, left = 40).add_to(m)
FloatImage('test_fig.png', bottom = 50, left = 50).add_to(m)
FloatImage('test_svg.svg', bottom = 60, left = 60).add_to(m)

m

```
The map output by this code displays 6 different 'float_image' text strings with a broken image window next to each, which suggests that I am not importing the images correctly.

**Expected behavior**

I was expecting at least one of these 6 methods to display an image on the map.

**Environment (please complete the following information):**
 - Browser [e.g. chrome, firefox]: N/A--editing within Visual Studio Code
 - Jupyter Notebook or html files? Jupyter Notebook
 - Python version (check it with `import sys; print(sys.version_info)`) 3.9.5 From printout: (major=3, minor=9, micro=5, releaselevel='final', serial=0)
 - folium version (check it with `import folium; print(folium.__version__)`) 0.12.1.post1
 - branca version (check it with `import branca; print(branca.__version__)`): 0.4.2

**Additional context**

I based the above approaches off other issue reports and StackOverflow posts but haven't yet found a solution. 

**Possible solutions**
List any solutions you may have come up with.

folium is maintained by volunteers. Can you help making a fix for this issue?

**Comment by kburchfiel** [comment]
Aha! Although the images don't display correctly within my Jupyter notebook, when I save the map (e.g. m.save('test_map.html')) and then open it within a web browser, the maps produced by the following two methods (but not the others) do indeed work:

FloatImage('test_fig.png', bottom = 50, left = 50).add_to(m)
FloatImage('test_svg.svg', bottom = 60, left = 60).add_to(m)

**Comment by Conengmo** [comment]
In a Jupyter Notebook a couple things worked as well for me.

Using local files worked:

```
FloatImage(r'test_fig.png', bottom = 50, left = 50).add_to(m)
FloatImage('test_svg.svg', bottom = 60, left = 60).add_to(m)
```

Using the base64 encoded image worked if you specify the file format:

```
FloatImage('data:image/png;base64,' + decoded_base64_png, bottom=30, left=30).add_to(m)
```
