### ISSUE TITLE
Incomplete map display

### ISSUE THREAD

**Issue by pythonLiNM** [python-visualization/folium#1566]
Incomplete map display, missing buildings

![微信图片_20220123223059](https://user-images.githubusercontent.com/50547107/150683503-db00fbac-f583-4b95-9433-86df284caefb.png)

![微信图片编辑_20220123222949](https://user-images.githubusercontent.com/50547107/150683520-4ec592cf-af1a-45c2-b65e-48eeba98a0ea.jpg)

The basemap data is displayed normally, and the information is lost after Folium is generated

**Comment by pmains** [comment]
Do you have specific instructions on how to reproduce this error? I see that some information is redacted. An un-redacted example would be helpful.

**Comment by Conengmo** [comment]
Indeed this is not enough to go on...
