### ISSUE TITLE
Cannot use `fit_bounds` multiple times on the same map

### ISSUE THREAD

**Issue by alessioarena** [python-visualization/folium#1569]
**Describe the bug**
Calling `fit_bounds` on a generated map more than once has no effect

In the example below I generated a map centered on the data (South coast of Australia).
Then I try to use `fit_bounds` again centered in Rome, Italy, but I get back the previous RoI
![image](https://user-images.githubusercontent.com/33886395/152713876-2e528e9a-3f11-42d5-8808-6007c2dcade8.png)

**To Reproduce**
I am experiencing this with a rather complicated map.
Currently I could not reproduce it with a minimum example.

I checked creating a simple map and using the following operations:
 - fit_bounds twice with no data
 - fit_bounds twice with simple data
 - fit_bounds twice with initial location defined
 - fit_bounds twice with `keep_in_front` option
In all those cases I could not reproduce it, so I'm running short of idea. 

**Expected behavior**
Calling `fit_bounds` many times will result in a map zoomed using the bounds provided in the last call

**Environment (please complete the following information):**
 - Firefox
 - Jupyter lab 3.2.4
 - Python version 3.8.12
 - folium version 0.12.1.post1
 - branca version 0.4.2

**additional context**
I also tried to explicitly delete the previous child `fit_bounds` from the `Map._children` attribute, but did not work

**Possible solutions**
Generating a new map and apply the new bounds works

**Comment by alessioarena** [comment]
it seems this issue is related to this https://github.com/python-visualization/branca/issues/107.
Basically I'm trying to delete a child from a Map by modifying the `Map._children` attribute, but that still causes the rendered JavaScript code to include the snippets specified in the deleted Element.

I feel there is something important I'm missing (and that there should be a `remove_child` method)

**Comment by Conengmo** [comment]
Great description, indeed this doesn't work currently. This is not an easy thing to achieve, because we'd have to delve into how branca works. I'll close this issue because of that. Help or work on it is still welcome though.

In the meantime I'd advise to create separate Map objects.
