### ISSUE TITLE
After a Loop Folium doesn't show up map

### ISSUE THREAD

**Issue by renzocaceresrossiv** [python-visualization/folium#1575]
I' m working with Jupyter Notebook and RMarkdown, when I run the following code in Jupyter works fine, but in RMkardown runs but doesn't show up the map
import folium as fl

import pandas as pd

puntos = pd.read_csv('F:\DISCO3\Documents\python_folium\puntos.txt')

puntos

points = puntos.loc[0]

palacio_gobierno = fl.Map(location=[-12.0458318974237, -77.03052679284455],zoom_start=16)

for _,points in puntos.iterrows():
    fl.Marker(location=[points['latitud'],points['longitud']]
    ,icon=fl.Icon(color=points['color'],icon=points['simbolo'])).add_to(palacio_gobierno)

palacio_gobierno

**Comment by Conengmo** [comment]
I'm afraid this is a bit too little to go on...
