### ISSUE TITLE
Vector tiles support

### ISSUE THREAD

**Issue by gtitov** [python-visualization/folium#1577]
**Is your feature request related to a problem? Please describe.**
I'm always sad when I can't use vector tiles.

**Describe the solution you'd like**
Vector tiles support via for example https://github.com/Leaflet/Leaflet.VectorGrid

**Describe alternatives you've considered**
I don't know any Python module that supports interactive mapping with vector tiles (will be happy to know!).

**Additional context**
The issue was mentioned in #563 #937. There is even a PR #943. But it seems like the process stalled three years ago.

**Implementation**
I haven't got qualification to make the PR

---

I'm not sure if it is a common problem. But I'm interested are there any plans to implement this feature?

**Comment by Conengmo** [comment]
We merged https://github.com/python-visualization/folium/pull/1576 in May 2022. It was included in the 0.13.0 release on October 7th.

It looks like our docs are not updated yet, but you can read the docstring here: https://github.com/python-visualization/folium/blob/main/folium/plugins/vectorgrid_protobuf.py. Or check out the example notebook here: https://nbviewer.org/github/python-visualization/folium/blob/main/examples/plugin-vector-tiles.ipynb

I hope that satisfies this issue, so we can close it.
