### ISSUE TITLE
Folium Maps fail to load from Malaysia

### ISSUE THREAD

**Issue by nabilersyad** [python-visualization/folium#1582]
**Describe the bug**
Any PC in Malaysia connected to the local ISP could will somehow fail or take too long to load any Folium Maps on the browser. I noticed this is a problem only on Malaysian internet connected PCs because when I load the same maps on VPN and changing the region to the US or Singapore, it would load just fine.

**To Reproduce**
1. If you are not in Malaysia, use a VPN to change your region to Malaysia
2. Try loading any Folium Maps. The examples where I encountered this problem are below
https://share.streamlit.io/randyzwitch/streamlit-folium/examples/streamlit_app.py
https://share.streamlit.io/nabilersyad/train-stations-isochrones/webapp/webapp.py
https://www.kaggle.com/code/alexisbcook/interactive-maps
3. You'll notice that either the maps will take almost a minute to load or the prompt 'Trust this Notebook' will appear
4. Repeat by changing the region to any other than Malaysia and use try the same maps. You'll notice that the maps load just fine.
5. Note that if you have already loaded a Folium map in a region outside Malaysia and then switching to Malaysia, you will temporarily still be able to load the map normally.

**Expected behavior**
I expect that Folium Maps would load almost instantly in under 5 seconds.

**Environment (please complete the following information):**
 - Browser [e.g. chrome, Brave]
 - Jupyter Notebook, Kaggle notebook and Streamlit Webapps.
 - python ==3.8
 - folium==0.12.1

**Additional context**

**Possible solutions**
It is possibly a backend or a firewall problem? I'm not really sure.

folium is maintained by volunteers. Can you help making a fix for this issue?
I've tried workarounds but none of them work.

**Comment by Conengmo** [comment]
That is a weird problem. Could you check your browser developer settings, look at the 'network' tab, see what resources are failing to load specifically?

**Comment by nabilersyad** [comment]
It says several bootstrap files and some analytics js.
![image](https://user-images.githubusercontent.com/33039075/162554190-2215bd68-d5ef-4b95-9e0b-cc7d19e9ae5b.png)
![image](https://user-images.githubusercontent.com/33039075/162554239-18afb908-1ffd-42f1-8093-d022421aed53.png)

The console also showed several failed GET requests
![image](https://user-images.githubusercontent.com/33039075/162554260-5aba1fe8-6b9b-459b-8dd6-8e4ae36382f4.png)

**Comment by Conengmo** [comment]
Looks like the Bootstrap CDN is not well available in Malaysia. We did switch to a different CDN for those that should be better. This change is now on the main branch and will be included in the upcoming 0.14.0 release. I'll close the issue for now. Please reach out if there are still resources that fail to load going forward.

**Comment by GreenPatrick2** [comment]
Hi - great that this is closed. To add a comment, this is not only Malaysia. The MaxCDN is being deprecated worldwide as of January 1st and already we are seeing service degradation. Therefore all customers will soon be impacted, thus some urgency to releasing 0.14.0.

https://www.stackpath.com/blog/maxcdn-and-securecdn-are-retiring-heres-what-it-means-for-you

**Comment by Conengmo** [comment]
Thanks for the notification! In that case more urgency to release 0.14.0 indeed. Current planning is to do it first week of December.
