### ISSUE TITLE
Markercluster, disable cluster at zoomlevel

### ISSUE THREAD

**Issue by KarenChen9999** [python-visualization/folium#1583]
This issue was rasied by another person last year. But it seems to be no answer. I come aross the same issue and wonder if this can be done Markercluster or folium

[https://github.com/python-visualization/folium/issues/1485]

**Comment by Conengmo** [comment]
since there is an open issue about the same thing, no need to open a new issue

**Comment by KarenChen9999** [comment]
just figured out this by passing disableClusteringAtZoom directly.
mc = folium.plugins.MarkerCluster(control=True, 
                                  name="Exposure Cluster",
                                  disableClusteringAtZoom=14
                                 )   # Marker Cluster, hidden in controls
