### ISSUE TITLE
https://cdn.jsdelivr.net/npm/leaflet@1.6.0/dist/leaflet.js can not be accessed

### ISSUE THREAD

**Issue by delcompan** [python-visualization/folium#1593]
https://cdn.jsdelivr.net/npm/leaflet@1.6.0/dist/leaflet.js
https://cdn.jsdelivr.net/gh/python-visualization/folium/folium/templates/leaflet.awesome.rotate.min.css
https://cdn.jsdelivr.net/npm/leaflet@1.6.0/dist/leaflet.css

all can not be accessed

**Comment by Conengmo** [comment]
What country or location do you access these from? Could you look in your browser developer tools, under Network, see what kind of status you get?

**Comment by delcompan** [comment]
China

replace:
https://unpkg.com/leaflet@1.6.0/dist/leaflet.js
https://unpkg.com/leaflet@1.6.0/dist/leaflet.css
done!
but https://cdn.jsdelivr.net/gh/python-visualization/folium/folium/templates/leaflet.awesome.rotate.min.css
 I have not found a replacement
