### ISSUE TITLE
Recently, the map does not render, only can see the blank map

### ISSUE THREAD

**Issue by Black-Chocolate** [python-visualization/folium#1594]
Recently, the map does not render, only can see the blank map.

Not only me, none of my colleagues can show the map.

![image](https://user-images.githubusercontent.com/31764885/169461758-60217318-c6c8-46ed-9959-547a8f34301a.png)

**Comment by Conengmo** [comment]
Could you open your browser developer tools, look at the Console? You can usually do this by pressing F12. Please share if you see any errors there.

**Comment by Black-Chocolate** [comment]
Thank you!!!, it looks like that leafeat.js load error!
![image](https://user-images.githubusercontent.com/31764885/169690908-cd5d870b-906c-49a8-ad9b-2a2ba1c642cf.png)

**Comment by Black-Chocolate** [comment]
Thank you~ I have solved this problem, the cause of the problem is that access to the cdn.jsdelivr.net is banned in China。

The solution is to use fastly.jsdelivr.net replace cdn.jsdelivr.net
