### ISSUE TITLE
Formatted popups or tooltips with variable strings?

### ISSUE THREAD

**Issue by amca01** [python-visualization/folium#1596]
I'm using Python 3.10.4 and the most recent version of folium.  My needs are simple: to create popups or tooltips on a map showing the name of the location and some information.  I am fetching the results from a pandas dataframe, over which I'm iterating with iterrows.  The salient code currently is this:

    tooltip = row["place"] + ", Population: "+str(row["population"])

which produces a single line, like

Crumbletown, Population: 4.5

But what I want is for the text to be formatted, so it looks for example like this:

**Crumbletown**
Population: 4.5

maybe with a larger font for the heading.  I know formatting can be done with html (as per the popup.ipynb example notebook).  But what I don't know is how to include a string variable in the html code, and whether this issue is a Python issue, an html issue, or something else.  Note that I am a folium beginner, so forgive me if this is a trivial question.   Many thanks!

**Comment by Conengmo** [comment]
Yes you can add html to a popup or tooltip. That can also be a template string. For example:

```
Marker(
    (0, 0),
    popup=f'<b>{row.place}</b>{row.population}'
)
```
