### ISSUE TITLE
HTML cannot display content

### ISSUE THREAD

**Issue by Jurvis26** [python-visualization/folium#1597]
**Describe the bug**
Hello, due to the recent cleaning of the browser, found that the generated HTML could not be opened

**Environment (please complete the following information):**
 - chrome/Microsoft Edge
 - html 
 - Python version sys.version_info(major=3, minor=7, micro=12, releaselevel='final', serial=0)
 - folium version (0.12.1.post1)
 - branca version (0.5.0)

**Comment by Conengmo** [comment]
I'm sorry but I can't help you with this little amount of info.
