### ISSUE TITLE
Retrieve data added with a folium Draw plugin

### ISSUE THREAD

**Issue by Cimeliere** [python-visualization/folium#1601]
Hello,

This is not an issue but a question.
I didn't found a better place to ask...

I use a folium.plugins.Draw and I would like to get the objects interactively added on the map (rectangles for example)
Something like "Draw.drawnItems" but folium says : "'Draw' object has no attribute 'drawnItems'" and I didn't found any code example 

Could you help me ?

**Comment by Conengmo** [comment]
I'm not sure I understand your question. If you look at the second example in the notebook, you can see there's an option to add an 'export' button, which allows you to download your drawing: https://nbviewer.org/github/python-visualization/folium/blob/main/examples/plugin-Draw.ipynb

If you want to do more, you will have to edit that class yourself.
