### ISSUE TITLE
How can I limit the start value of the y-axis, like plt.ylim() in matplotlib?

### ISSUE THREAD

**Issue by zhangch-ss** [python-visualization/folium#1602]
How can I limit the start value of the y-axis, like plt.ylim() in matplotlib?

**Comment by ocefpaf** [comment]
> How can I limit the start value of the y-axis, like plt.ylim() in matplotlib?

You can use `fit_bounds`, see https://python-visualization.github.io/folium/modules.html#folium.folium.Map.fit_bounds.

Note that is inherited from leaflet and there is not a way to set only x or y, only the 4 corners.
