### ISSUE TITLE
Chloropleth map created; no colors

### ISSUE THREAD

**Issue by sejal234** [python-visualization/folium#1603]
This is what my dataframe looks like:
<img width="592" alt="image" src="https://user-images.githubusercontent.com/90943744/175779563-6feb98ea-8e91-4226-8abb-edb51e5faabc.png">
<img width="548" alt="image" src="https://user-images.githubusercontent.com/90943744/175779573-bd443bec-decc-4f50-8821-a5676075883b.png">

The oy_count (at the far right, second screenshot) are integers and they align with their zipcodes

```python
m = folium.Choropleth(
            geo_data=r'/Users/sejalgupta/Downloads/Zip_Codes.geojson',
            data=df_final,
            columns=['ZIPCODE', 'oy_count'],
            key_on='feature.properties.ZIP_CODE', 
            fill_color='YlGn',
            nan_fill_color="White", 
            fill_opacity=0.7,
            line_opacity=0.2,
            legend_name='Num of OY', 
            highlight=True,
            line_color='black')
m.add_to(htx_map) 
folium.LayerControl().add_to(htx_map)
htx_map
```
#### Problem description

The map overlays with the Houston map and the zipcode boundaries are created, but the map does not actually show the colors based off the counts.

#### Output of ``folium.__version__``
<img width="679" alt="image" src="https://user-images.githubusercontent.com/90943744/175779495-2ee05179-2d42-4c8e-add7-1a29cfa90a7d.png">

**Comment by prathikshetty2002** [comment]
Hi @sejal234 i think the issue here might be similar to #917 issue. The problem might be in your .geojson file. Hope it would be helpful. You should try checking it until the maintainer responds to the query.

**Comment by Conengmo** [comment]
That's probably the case here, the zipcodes being a string in one data source and an integer in the other.
