### ISSUE TITLE
Leaflet.js error iterating markers being displayed while using the folium maps

### ISSUE THREAD

**Issue by prathikshetty2002** [python-visualization/folium#1604]
**Describe the bug**
I was working on a project that uses folium for geospatial analysis . Folium maps are used to display regionwise crime distribution in chicago in my project. I have used streamlit to build the web app and have hosted it on heroku. But while using the maps i am getting an iterative sequence of folium markers being displayed on my app interface. Somehow i got to know that it is due to issue with leaflet.js, it displays these markers. I want to remove them since it doesn't look good. But not able to find a way to do that. 

**To Reproduce**

You can find the app.py code here : 

https://gist.github.com/prathikshetty2002/ace8cf26510ced40939704f9fa4630eb

**Expected behavior**

Wanted a clean running environment with only folium maps but got an interface with along unwanted markers. 

Some snippets of my app that doesn't looks good i want to remove those  <markers>

My app link : https://crimedekho.herokuapp.com/    

![issue1](https://user-images.githubusercontent.com/63772910/176043906-eca4de10-7e9f-4fbe-88d5-90ed8bc1ff4f.png)

![issue3](https://user-images.githubusercontent.com/63772910/176043926-944a8c32-efcd-4cb9-9e5a-7e2bb382aca4.png)

**Environment (please complete the following information):**
 - Browser : chrome 100+
 - Python version : 3.10
 - folium version : 0.12.1
 - streamlit version : 1.10.0

**Comment by Conengmo** [comment]
I'm afraid I can't really help you with this, since it's not a folium issue. folium shouldn't print those things on the command line by itself.

One thing I noticed is that on some of the lines you call `f.Marker` it contains a trailing comma, why is that? Maybe it's related?

You should make sure the marker you create is not being 'returned'. Sometimes adding a semicolon helps.
