### ISSUE TITLE
Use Folium with locally stored files in jupyter notebook

### ISSUE THREAD

**Issue by fbardos** [python-visualization/folium#1607]
**Is your feature request related to a problem? Please describe.**
I have a big image (graph of a tags network, 500 MB) and want to display it on a jupyter notebook.
I wondered, if it is possible to display this image (as locally stored tiles) in Leaflet, with folium.

For this, I have generated the the tiles with [commenthol/gdal2tiles-leaflet](https://github.com/commenthol/gdal2tiles-leaflet).

I now have a directory structure which looks like this:
```text
workdir/
├─ notebook.ipynb
├─ tiles/
│  ├─ 0/
│  │  ├─ 0/
│  │  │  ├─ 0.png/
│  ├─ ...
```
I tried to used a local path as variable for `folium.Map.tiles` as in this example:
```python
import folium

m = folium.Map(crs='Simple', tiles='tiles/{z}/{x}/{y}.png', attr='CKAN Tag network', min_zoom=0, max_zoom=5)
m
```
Unfortunately, this gives me an empty Leaflet map, which looks like this:
![image](https://user-images.githubusercontent.com/15113366/177056872-255dacba-484d-47bf-8043-a15726823ed7.png)

I also tried `file://tiles/{z}/{x}/{y}.png` as url, but this didn't work either.

When starting a simple webserver on my workdir with `python3 -m http.server 8000`, the tiles get displayed:
![image](https://user-images.githubusercontent.com/15113366/177411148-f767905f-f077-41bb-94d1-ca02d989fbbc.png)
 
Is there a way, I can use a local directory for the gathering of tiles, without starting a webservice?

Thank you very much.

**Comment by Conengmo** [comment]
I haven't tried that before, so I can't really help you. This is more of a Leaflet question. See for example https://gis.stackexchange.com/a/88223.

One thing I can say is that if running a local webservice works, why not just use that? If you can run a Jupyter server, why not also run a server for the tiles.

**Comment by fbardos** [comment]
> One thing I can say is that if running a local webservice works, why not just use that?

I was searching for a solution to use Folium without owning a public webserver.
But I found a solution: When pushing the tiles into a public github repo, it works perfectly.
