### ISSUE TITLE
blank output rather than 3D map

### ISSUE THREAD

**Issue by jonschull** [python-visualization/folium#1609]
**Describe the bug**
I get no visualization (white output cell) when I run this example:
https://github.com/python-visualization/folium/blob/d2c495b871c09dac656b4fc4f8b153e36f1eed14/examples/Hacking_folium_3D_globe.ipynb

**To Reproduce**
try on google colab or in jupyter notebook
```
[ Include a code snippet that produces your bug. Make it standalone, we should be able to run it. ]

[ Include a data sample or link to your data if necessary to run the code ]

```

**Expected behavior**
I expected to see a 3D globe

**Environment (please complete the following information):**
 - Browser [e.g. chrome, firefox]
 - Jupyter Notebook or html files?
 - Python version (check it with `import sys; print(sys.version_info)`)
 - folium version (check it with `import folium; print(folium.__version__)`)
0.12.1.post1
 - branca version (check it with `import branca; print(branca.__version__)`)
0.5.0

**Additional context**

**Possible solutions**
List any solutions you may have come up with.

folium is maintained by volunteers. Can you help making a fix for this issue?

**Comment by Conengmo** [comment]
Where did you get that link from? I don't think we've had that example in our repo for a while now. As far as we have people to give support, I'm afraid we definitely cannot support deprecated stuff.
