### ISSUE TITLE
Folium Map not loading with large quantities of markers

### ISSUE THREAD

**Issue by ConfusedPrimates** [python-visualization/folium#1612]
I'm a student working with folium to visualize data for routes taken by electric vehicles. I've been parsing data from CSV files that include the latitude and longitude of routes and markers for points of interest along the route. I've created a GUI using PyQt5 to run the python scripts that parse the CSV data. The GUI then creates a new window with an embedded map. 

When I parse a large quantity of points of interest data the map does not render anything, only a blank white layout with the option to reset the map when right clicking. I'm unsure of why this is occurring due to seeing other people creating thousands of markers and not having their maps break like this.

**To Reproduce**
To reproduce create a bunch of markers for a POI layer and add them to a map. 
`
 buffer = io.BytesIO()
        map.save(buffer, False)

        map_view = QtWebEngineWidgets.QWebEngineView()
        map_view.setHtml(buffer.getvalue().decode())
        map_view.resize(960, 720)

        self.map_window = QWidget()
        map_layout = QVBoxLayout()
        map_layout.addWidget(map_view)
        self.map_window.setLayout(map_layout)
        self.map_window.setWindowTitle("Map View")
        self.map_window.show()
`

This creates the embedded map in PyQt

**Expected behavior**
When I create the map with a moderate amount of lines and markers drawn it will load the map properly without any issues. However, with a large quantity of markers, I'm counting about 381 markers and a drawn route it will only load a white screen. There are no error messages and the map does not eventually load. 

**Environment (please complete the following information):**
import folium
from PyQt5.QtWidgets import *
from folium.vector_layers import PolyLine

Here is an image of the error output
![image](https://user-images.githubusercontent.com/78619728/183154351-8018a0dc-9053-43d4-8b76-c802fcef721f.png)
This is what I am expecting but with a mass of POI markers
![image](https://user-images.githubusercontent.com/78619728/183154733-7cecb57b-42ab-41db-a2d7-8f6aa5bc579a.png)

Is there any way to fix this so that the map loads properly?

**Comment by Conengmo** [comment]
I haven't used folium in Qt before, but I suspect that has something to do with it, probably related to the many lines, not the markers. Does the map work when you export it as html and open that in your browser?

```
m = folium.Map()
m.save('map.html')
```

I'm afraid I can't really help you with the Qt stuff.

**Comment by sktnknix** [comment]
No, it's not about QT. I have a regular py file, with over 2000 markers, the html size is 30MB. No browser can open such html.

**Comment by sktnknix** [comment]
Add a MarkerCluster to the map, the html size will remain about the same, but the map will not try to draw all at once and will open successfully.
