### ISSUE TITLE
Is there a way to add a custom text box in the map?

### ISSUE THREAD

**Issue by GabeNicholson** [python-visualization/folium#1614]
I'm wondering if there is a way to add a custom block of text that looks like a legend. For example, something as simple as displaying this dictionary {'Chicago':500, 'NYC': 200, 'LA':100}, in a legend type format.

I was thinking this might be implemented as a custom legend but I am not sure how to do that from the documentation alone. Preferably it could be added as a Feature Group so it could be toggled to be on and off. 

Any advice would be great!
Thank you

**Comment by Conengmo** [comment]
Take a look at this comment, hope it helps: https://github.com/python-visualization/folium/issues/528#issuecomment-421445303
