### ISSUE TITLE
ClickForLatLng() is not implemented even if PR #1530

### ISSUE THREAD

**Issue by eabase** [python-visualization/folium#1616]
**Describe the bug**
The `folium.ClickForLatLng()` functionality seem to be missing.

**`AttributeError: module 'folium' has no attribute 'ClickForLatLng'. Did you mean: 'ClickForMarker'?`**

**To Reproduce**

```python
# ...
m = folium.Map(MC, zoom_start=15, max_zoom=21, control_scale=True, tiles='cartodb positron')
folium.ClickForLatLng().add_to(m)
```

**Expected behavior**
expect it to copy to clipboard

**Environment (please complete the following information):**
```powershell
# python.exe -c "import folium; print(folium.__version__)"
0.12.1.post1
# python.exe -c "import branca; print(branca.__version__)"
0.5.0
# python.exe -c "import sys; print(sys.version_info)"
sys.version_info(major=3, minor=10, micro=3, releaselevel='final', serial=0)
```

**Other**

Should be working from PR #1530.

**Comment by Conengmo** [comment]
Seems like that PR forgot to add the import to `__init__.py`, simple mistake. As a temporary workaround you can do `from folium.features import ClickForLatLng`.

In the meantime a PR to add it to the import and `__all__` statement in `__init__.py` is welcome.

**Comment by amrutha1098** [comment]
Hi, can i work on this issue ?

**Comment by amrutha1098** [comment]
Hi @Conengmo , I have submitted PR . ( https://github.com/python-visualization/folium/pull/1627 )
Please let me know if any other changes are required.
Thanks!
