### ISSUE TITLE
popup - click latlong information and copy to clipboard

### ISSUE THREAD

**Issue by drmlbrt** [python-visualization/folium#1617]
**Is your feature request related to a problem? Please describe.**
I'm creating a solution for a beekeepers  team tracking asian hornet sightings. I use the click on map popup with geo data. Now they copy the information by selecting it and press ctrl+c.
Can't it be dynamic? if you click on the presented data "lat,long" that it is saved to the clipboard?

Alternative:
add url solution to point to a flask endpoint and present the data as a json {"lat":lat, "long":long}

Thank you

**Comment by Conengmo** [comment]
If you are using the `ClickForLatLng` class, the coordinates should already be saved to the clipboard.

Adding support for dynamic web applications is unfortunately out of scope for folium. Though you could probably do it yourself by making a custom version of the `ClickForLatLng` class and in the onclick event add a backend call to a Flask endpoint.
