### ISSUE TITLE
Support continent/country/city names

### ISSUE THREAD

**Issue by shampa-dutta** [python-visualization/folium#1619]
**Is your feature request related to a problem? Please describe.**
It is not related to any problem. It just occurred to me while experimenting that there could could be something like this where we dont have to take the lat and long instead we could just type in the place name and show the map for that place.

**Describe the solution you'd like**
write a code in the package that can extract the lat and long from any website and we can just call the city/country, etc  to draw the map.

**Describe alternatives you've considered**
We could also store a dataset in any repository and pull the information from there itself which is one way to do it.

**Comment by Conengmo** [comment]
We already support this functionality, check out the Geocoder plugin:

https://python-visualization.github.io/folium/plugins.html#folium.plugins.Geocoder

https://nbviewer.org/github/python-visualization/folium/blob/main/examples/Plugins.ipynb#Geocoder
