### ISSUE TITLE
Gitter for folium

### ISSUE THREAD

**Issue by andrewgiessel** [python-visualization/folium#162]
Any interest?  @ocefpaf @themiurgo @BibMartin ?

https://gitter.im/

**Comment by ocefpaf** [comment]
I am not a big fan of gitter, but I do not see the harm of having one.

**Comment by andrewgiessel** [comment]
I don't see a big advantage over slack/irc/hipchat, but it is free, simple
and easy for people to join.  I'd just like a higher bandwidth place to
talk with you guys, because I'm interested in continuing to contribute...

**Comment by ocefpaf** [comment]
Sure.  I see people are already using it, but here it goes:

https://gitter.im/python-visualization/folium
