### ISSUE TITLE
Embed on markdown page

### ISSUE THREAD

**Issue by JZhou3083** [python-visualization/folium#1621]
**Is your feature request related to a problem? Please describe.**
I am trying to embed the saved map(.html) on my markdown page. May I ask if there is any way to do that or any alternative way? 

**Describe the solution you'd like**

**Describe alternatives you've considered**
iframe，not working 

**Additional context**

**Implementation**
folium is maintained by volunteers. Can you help make a PR if we want to implement this feature?

**Comment by Conengmo** [comment]
This is not something Markdown supports as far as I know. You can include an image of a map, and a link to that map.

**Comment by ocefpaf** [comment]
Indeed. However, note that there are tons of Markdown flavors and implementations. Some allow you to include HTML files, like this one: https://bookdown.org/yihui/rmarkdown-cookbook/include-html.html

Still, there is nothing we can do on folium's side.

**Comment by JZhou3083** [comment]
Thanks for the advices. I embedded the figures instead.
