### ISSUE TITLE
Add document about how it works of the heatmap 

### ISSUE THREAD

**Issue by wybert** [python-visualization/folium#1639]
I have been using the [heatmap plugin](https://python-visualization.github.io/folium/plugins.html#folium.plugins.HeatMap), but I can't find any details about how it works in the document.

**Comment by Conengmo** [comment]
We have an example notebook: https://nbviewer.org/github/python-visualization/folium/blob/main/examples/Heatmap.ipynb

To read more about the parameters, check out the Javascript package this plugin uses: https://github.com/Leaflet/Leaflet.heat

If you find the example notebook too brief, consider expanding it and opening a PR!

**Comment by wybert** [comment]
It is clear how to use it. But none of the links refer to the algorithm it uses, although you can read the code. I also check it out the [Leaflet.heat](https://github.com/Leaflet/Leaflet.heat) and the links it refers too.
