### ISSUE TITLE
Couldn't import groundlayercontrol from the plugins

### ISSUE THREAD

**Issue by Waeara** [python-visualization/folium#1643]
While trying to produce the plugin-GroupedLayerControl.ipynb example, I got:
`ImportError: cannot import name 'groupedlayercontrol' from 'folium. plugins'`

Have folium 0.13.0 installed.

Any idea why is that?

**Comment by Conengmo** [comment]
I'm not sure what plugin you are referring to, can you give a link to that example notebook?

**Comment by Waeara** [comment]
[This one](https://github.com/python-visualization/folium/blob/ae60699c55dcbd8e69bd747e4ebd45794c76d4f3/examples/plugin-GroupedLayerControl.ipynb)

**Comment by Conengmo** [comment]
This feature hasn't been released yet. It's in an open PR: https://github.com/python-visualization/folium/pull/1592. We strive to go through all the open PRs this month.

If you want to use it, you could use folium from the branch that user was developing that feature on: https://github.com/chansooligans/folium/tree/plugins-groupedlayercontrol
