### ISSUE TITLE
How does folium choropleth tune the legend of map

### ISSUE THREAD

**Issue by dongrixinyu** [python-visualization/folium#1649]
- I just wanna ask how to change the legend of the folium-generated map to a correct scale and color?

```
state_data = pd.read_csv(r'D:\BaiduNetdiskDownload\US_folium\china-population.csv')

max_value = state_data['population'].max()
state_data['population'] /= max_value
bins = list(state_data['population'].quantile([i/10 for i in range(0, 11)]))


m = folium.Map(location=[37, 108], zoom_start=4)

folium.Choropleth(
    geo_data=r'D:\BaiduNetdiskDownload\US_folium\china-counties.json',
    data=state_data,
    columns=["county", "population"],
    key_on="feature.id",
    fill_color="BuPu",
    fill_opacity=0.7,
    line_opacity=0.1,
    legend_name="人口数量",
    bins=bins,
    reset=True,
).add_to(m)
```

and the `state_data['population']` ranges from 2300 ~12042384 with length of 2300.

when I execute the code above , I get the legend of the map like below:

![image](https://user-images.githubusercontent.com/27001062/201876081-b2bd482b-19aa-4885-89a8-75b27e069161.png)

### So how to correct the legend of the map with a right ratio

**Comment by Conengmo** [comment]
One thing that might help is to use the `tick_labels` variable that's now available. For example:

```
choropleth = Choropleth()
choropleth.color_scale.tick_labels = [0, 0.5, 1]
choropleth.add_to(m)
```
