### ISSUE TITLE
Not able to add multiple markers on the Map

### ISSUE THREAD

**Issue by Crimson-Zero** [python-visualization/folium#1661]
**Describe the bug**
For some reason the folium. Marker only creates one marker it should make multiple markers if it is inside the For loop I have tried multiple variations of code saving index.html inside the for loop used the code add_to(map) created a feature group and have the markers be added to the group but none works
**To Reproduce**

```
[ Include a code snippet that produces your bug. Make it standalone, we should be able to run it. ]
import folium 
import pandas as pd

read_file = pd.read_csv ('Volcanoes.txt')

Latitude = read_file["LAT"]
Longitde = read_file["LON"]
State = read_file["LOCATION"]

Latitude_list = Latitude.to_list()
Longitude_list = Longitde.to_list()
state_list = State.to_list()

print(Latitude_list)
print(Longitude_list)
print(state_list)
m = folium.Map(location=[Latitude_list[0],Longitude_list[0]])

fg = folium.FeatureGroup(name="US MAP")    
m.save("index.html")

tooltip = "Click me!"

for lat,lon, st in zip(Latitude_list,Longitude_list,state_list):
    
    fg.add_child(folium.Marker([lat,lon], popup=st,tooltip=tooltip))

m.add_child(fg)
m.save("index.html")
```

[ Include a data sample or link to your data if necessary to run the code ]

OLCANX020,NUMBER,NAME,LOCATION,STATUS,ELEV,TYPE,TIMEFRAME,LAT,LON
509.000000000000000,1201-01=,Baker,US-Washington,Historical,3285.000000000000000,Stratovolcanoes,D3,48.7767982,-121.8109970
511.000000000000000,1201-02-,Glacier Peak,US-Washington,Tephrochronology,3213.000000000000000,Stratovolcano,D4,48.1118011,-121.1110001
513.000000000000000,1201-03-,Rainier,US-Washington,Dendrochronology,4392.000000000000000,Stratovolcano,D3,46.8698006,-121.7509995
515.000000000000000,1201-05-,St. Helens,US-Washington,Historical,2549.000000000000000,Stratovolcano,D1,46.1997986,-122.1809998
516.000000000000000,1201-04-,Adams,US-Washington,Tephrochronology,3742.000000000000000,Stratovolcano,D6,46.2057991,-121.4909973
517.000000000000000,1201-06-,West Crater,US-Washington,Radiocarbon,1329.000000000000000,Volcanic field,D7,45.8797989,-122.0810013
518.000000000000000,1201-07-,Indian Heaven,US-Washington,Radiocarbon,1806.000000000000000,Shield volcanoes,D7,45.9297981,-121.8209991
519.000000000000000,1202-01-,Hood,US-Oregon,Historical,3426.000000000000000,Stratovolcano,D3,45.3737984,-121.6910019```

**Expected behavior**
As explained
**Environment (please complete the following information):**
 - Browser [e.g. chrome, firefox] Chrome
 - Jupyter Notebook or html files? Jupyter Notebook and also HTML file
 - Python version (check it with `import sys; print(sys.version_info)`)   Python 3.8.10
 - folium version (check it with `import folium; print(folium.__version__)`)folium  0.13.0
 - branca version (check it with `import branca; print(branca.__version__)`) Branca 0.6.0

**Additional context**

**Possible solutions**
List any solutions you may have come up with.

folium is maintained by volunteers. Can you help making a fix for this issue?

**Comment by Conengmo** [comment]
Unfortunately I'm not able to reproduce your issue.
