### ISSUE TITLE
FloatImage not working in folium v0.13.0

### ISSUE THREAD

**Issue by giswqs** [python-visualization/folium#1667]
**Describe the bug**
FloatImage does not work properly in folium v0.13.0. The image appears to be enlarged many times. 

**To Reproduce**

```python
import folium
from folium.plugins import FloatImage
import base64

m = folium.Map()
image = 'LmTETPX.png'  # downloaded from 'https://i.imgur.com/LmTETPX.png'
with open(image, "rb") as lf:
    b64_content = base64.b64encode(lf.read()).decode("utf-8")
    widget = FloatImage(
        "data:image/png;base64,{}".format(b64_content),
        bottom=50,
        left=75,
    )
widget.add_to(m)
m
```
![image](https://user-images.githubusercontent.com/5016453/204154274-bd948b56-dcf3-46b7-bac8-ca3b619cef6f.png)

Directly passing the image path does not work either.

```python
m = folium.Map()
image = 'LmTETPX.png'  # downloaded from 'https://i.imgur.com/LmTETPX.png'
FloatImage(image, bottom=50, left=75).add_to(m)
m
```
![image](https://user-images.githubusercontent.com/5016453/204154518-f024d9ee-f739-42d7-b72c-3bfc625bdb3b.png)

**Expected behavior**

It works as expected in folium v0.12.1.post1

![image](https://user-images.githubusercontent.com/5016453/204154213-27bdefbd-29d2-4b02-b301-68a5ae983327.png)

**Environment (please complete the following information):**
 - Browser: chrome
 - Jupyter Notebook
 - Python version: 3.9
 - folium version: 0.13.0
 - branca version: 0.4.2

**Comment by Conengmo** [comment]
Thanks for the report! I can confirm the issue. This is very likely because of https://github.com/python-visualization/folium/pull/1570. I think the fix is simple: make `width` an optional parameter.
