### ISSUE TITLE
TagFilterButton not compatible with LayerControl

### ISSUE THREAD

**Issue by eatPizza311** [python-visualization/folium#1670]
**Describe the bug**
I'm trying to do things similar to #1331 and found it was solved by #1343, so I download the source code from this repo.
The problem is if I try to add `TagFilterButton` and `LayerControl` to the map, then both features won't show on the map.

**To Reproduce**

```python
import os
import random

import folium
from folium import plugins
import pandas as pd
import numpy as np

# Generate base data
data_df = pd.DataFrame(np.random.normal(size=(100, 2)) * np.array([[1, 1]]) + np.array([[48, 5]]),
                       columns=['longitude', 'latitude'])

# Generate the data to segment by (levels of another pandas column in practical usage)
categories = ['category{}'.format(i+1) for i in range(5)]
category_column = [random.choice(categories) for i in range(len(data_df))]
data_df['category'] = category_column

# Split data into 2 groups
data_df_gp1 = data_df.loc[:len(data_df)/2, :]
data_df_gp2 = data_df.loc[len(data_df)/2:, :]

# Base map
m = folium.Map([48., 5.], tiles=None, zoom_start=7)

# Create 2 featuregroup
fg1 = folium.FeatureGroup(name="Group1", overlay=False).add_to(m)
fg2 = folium.FeatureGroup(name="Group2", overlay=False).add_to(m)

# Plot on feature group 1
folium.TileLayer().add_to(fg1)
for name, row in data_df_gp1.iterrows():
    category = row['category']
    folium.Marker(
        tuple([row['longitude'], row['latitude']]),
        tags=[category]
    ).add_to(fg1)
    
# Plot on feature group 2
folium.TileLayer().add_to(fg2)
for name, row in data_df_gp2.iterrows():
    category = row['category']
    folium.Marker(
        tuple([row['longitude'], row['latitude']]),
        tags=[category]
    ).add_to(fg2)

# Add LayerControl
folium.LayerControl(collapsed=False).add_to(m)

# Add TagFilterButton
plugins.TagFilterButton(categories).add_to(m)

# show map
m
```
![image](https://user-images.githubusercontent.com/43287234/204428393-e7163355-ffa4-4840-9ed9-83907dfc9fc7.png)

But if I use either one of these two features, it will work perfectly.
`TagFilterButton` only:
![image](https://user-images.githubusercontent.com/43287234/204428772-26d4d170-9293-4ffe-8167-0221823f5999.png)
`LayerControl` only:
![image](https://user-images.githubusercontent.com/43287234/204428824-50773b34-4bec-489a-8637-965dc74c35d2.png)

Maybe I am doing something wrong?

**Expected behavior**
Both features show on the map.

**Environment (please complete the following information):**
 - Browser: Chrome
 - Jupyter Notebook or html files? Jupyter Notebook and HTML files.
 - Python version: 3.8.13
 - folium version: 0.13.0
 - branca version: 0.6.0

**Possible solutions**
For now, I have to manually delete all the code inside the `overlays` block (sample code shown below), and everything works as expected.
But I need to keep the filter popup on or changing the layer won't refresh the filter result.
```javascript
var layer_control_ea51e36de8ef711027e74c3a99c3339e = {
                base_layers : {
                    "Group1" : feature_group_6def29078e0c0dbddf058c49d51d890e,
                    "Group2" : feature_group_aa7d6178c2d2c447655393713282a49f,
                },
                overlays :  {
                    "macro_element_8ed8ca2c508cc55a847c43978cd530e8" : tag_filter_button_8ed8ca2c508cc55a847c43978cd530e8,
                },
            };
```

![image](https://user-images.githubusercontent.com/43287234/204437808-890e84a8-704b-4224-be01-7d55e3d841e1.gif)

**Comment by Conengmo** [comment]
Thanks for your report, good catch! I think the issue here is that `TagFilterButton` is added to the layer control, but this is not possible. If I use `plugins.TagFilterButton(categories, control=False)` I don't have issues.

I'll make a fix that permanently disables control for `TagFilterButton`.

**Comment by Conengmo** [comment]
@eatPizza311 I made a fix in https://github.com/python-visualization/folium/pull/1671. Maybe if you have a moment you can test it?

**Comment by eatPizza311** [comment]
@Conengmo Thanks for the help! It works perfectly now.
