### ISSUE TITLE
LayerControl causes tile_layer not defined error inside a docker

### ISSUE THREAD

**Issue by rafa-guedes** [python-visualization/folium#1681]
**Describe the bug**
Map is failing to render with folium/streamlit when running inside a Docker container. Only a narrow strip of the map is rendered and an `Uncaught ReferenceError: tile_layer_08bf7f7235f2ecdd0ca980d0d472c30f is not defined` error is thrown in the browser (please see screenshot at the bottom). The map renders okay when running locally outside the docker container. I am not sure if this is an issue with folium, streamlit or st_folium however it seems related to https://github.com/python-visualization/folium/issues/1340 and https://github.com/python-visualization/folium/issues/1199.

**To Reproduce**
The app below works ok locally but fails when executed inside a docker built from ubuntu:22.04 image

Directory structure:
```
.
├── app.py
└── Dockerfile
```

*app.py*
```
import folium
from streamlit_folium import st_folium

m = folium.Map()
folium.TileLayer("OpenStreetMap").add_to(m)
folium.TileLayer("CartoDB positron").add_to(m)
folium.LayerControl().add_to(m)
st_data = st_folium(m)
```

*Dockerfile*
```
FROM ubuntu:22.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt update && apt install -y python3-dev python3-pip
RUN pip3 install streamlit folium streamlit-folium
ADD . /src
WORKDIR /src
EXPOSE 8501
ENTRYPOINT ["streamlit", "run", "app.py"]
```

Build and run the docker:
```
docker build . -t mydocker
docker run mydocker
```

**Expected behavior**
Folium map rendered with a LayerControl available to choose between layers.

**Additional context**

App run from the docker:
![Screenshot from 2022-12-15 23-47-49](https://user-images.githubusercontent.com/7799184/207840114-a71544db-4971-4a1f-b175-f8cba64a1754.png)

App run locally:
![Screenshot from 2022-12-15 23-49-37](https://user-images.githubusercontent.com/7799184/207840471-2b8a27f2-bead-4912-9615-28eeef4a5f9b.png)

**Comment by Conengmo** [comment]
Same issue as https://github.com/randyzwitch/streamlit-folium/issues/102? The issues linked in the issue description are not related.

I'm not familiar with Streamlit unfortunately, so I can't help debug this. But if there's something to fix on the folium side I can help. But maybe the fix lies in https://github.com/randyzwitch/streamlit-folium.

**Comment by rafa-guedes** [comment]
Hi @Conengmo apologies if the issue was open in the wrong place. There are 3 layers of abstraction and I wasn't sure where the problem could be coming from. Thanks for pointing that other issue in streamlit_folium.

**Comment by Conengmo** [comment]
No worries, thanks for helping out!
