### ISSUE TITLE
Select all/Deselect All for Feature Group

### ISSUE THREAD

**Issue by tgiang2840** [python-visualization/folium#1689]
![image](https://user-images.githubusercontent.com/91417185/210536466-0e8a4834-b2a9-44eb-a210-05986b6f0cff.png)
I am doing a school project and I need to create an interactive map for displaying the output network. 
Can I add the select all and deselect all buttons to the layer control? Can we do it by injecting JS code inside the function?
Thank you

**Comment by Conengmo** [comment]
You can use the existing FeatureGroupSubGroup plugin for this: https://nbviewer.org/github/python-visualization/folium/blob/main/examples/Plugins.ipynb#FeatureGroupSubGroup

**Comment by tgiang2840** [comment]
Can we do something to uncheck all the subgroups when the feature group is unchecked?
