### ISSUE TITLE
Avoid code duplication in div marker

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#169]
As @themiurgo pointed out PR #166 can be incorporate into markers.

> This is what Leaflet does with divicons, it doesn't use a separate method / code, it just leverages marker.  (See http://jsfiddle.net/erictheise/k6ckm/)

**Comment by themiurgo** [comment]
@shankari since you were the author of that PR would you be interested in fixing this, so that folium API stays as clean as possible?

**Comment by shankari** [comment]
I did consider making this a part of marker (a different kind of icon), but I didn't do it for two reasons.
- Leaflet doesn't actually include this as part of marker, it makes it a different kind of icon. But the folium API combines the marker and the icon into same call. Adding support for a different kind of icon in the marker API seemed like it would make it too complex - there are already 3 parameters dealing with icon (`marker-icon`, `clustered_marker` and `icon_angle`) and adding more would turn the API into something out of `matplotlib` :)
- I could have restructured this to more closely mirror the leaflet API - to have a `simple_icon` constructor which would be passed in to a `simple_marker`, but I wasn't sure how that would fit in with your architecture. You don't seem to do that anywhere else.
- It also seemed to me that the main use of the div icon (bunch of little boxes with not much decoration) would be if there are a lot of them in close proximity. So I optimized the API for that. Note that unlike `simple_marker`, it doesn't not take a single location, but instead, a list of locations and popups.

**Comment by themiurgo** [comment]
> there are already 3 parameters dealing with icon (marker-icon, clustered_marker and icon_angle) and adding more would turn the API into something out of matplotlib :)

Agreed, but adding more data types/methods also has a cost: makes it harder to maintain them. :smile: In the end what you want to plot on this map is two things: a line, and a list of styled markers along that line. Also, I agree that clustered marker should be refactored somehow, again, to follow as much as possible Leaflet.

> I could have restructured this to more closely mirror the leaflet API - to have a simple_icon constructor which would be passed in to a simple_marker, but I wasn't sure how that would fit in with your architecture. You don't seem to do that anywhere else.

True, it's not done anywhere else. At the moment is under heavy restructuring, it's trying to find its soul. Since it's entirely based on Leaflet, refactoring and following as much as possible the API will make it easier to develop new features. We can't change (easily) what's been made in the past but we can think better for future features.

> It also seemed to me that the main use of the div icon (bunch of little boxes with not much decoration) would be if there are a lot of them in close proximity. So I optimized the API for that. Note that unlike simple_marker, it doesn't not take a single location, but instead, a list of locations and popups.

This is a big assumption you are making, base on how you use that feature type. It might be a correct assumption, but to me it looks having a `divmarkers` adding many object at a time is inconsistent with all the other methods of folium (line, marker, ...) that add only one feature at a time.

**Comment by themiurgo** [comment]
In the end I don't know, but let's see what the others think @ocefpaf @shankari about these issues. Having more eyes on something is never a bad idea. :)

**Comment by ocefpaf** [comment]
>> adding more would turn the API into something out of matplotlib :)

It could be worse (`pandas.read_csv` ;-)

> adding more data types/methods also has a cost: makes it harder to maintain them.

Indeed!  But that is how we were doing things until now.  (I am not saying this is how we should proceed!)

> True, it's not done anywhere else. At the moment is under heavy restructuring, it's trying to find its soul. Since it's entirely based on Leaflet, refactoring and following as much as possible the API will make it easier to develop new features. We can't change (easily) what's been made in the past but we can think better for future features.

That pretty much sums up how I see folium's current state.  Once the dust settles we will re-visit the idiosyncrasies I added along the way and make re-write them to agree with the new logic.  (I know that @BibMartin is already tackling some of those.)

> adding many object at a time is inconsistent with all the other methods of folium (line, marker, ...) that add only one feature at a time.

That escaped my entirely!  It should be consistent with the rest of folium.  My pet peeves with folium are the fact that I have to write loops to add an array of features, and the alphabetic order for location (lat, lon) instead of **the correct** :wink:  order (lon, lat).  Still... we should keep following those for consistency.

**Comment by ocefpaf** [comment]
This is fixed in master.  Let's keep`v0.1.6` as is for now.
