### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by wyfSunflower** [python-visualization/folium#1691]
**Describe the bug**
install successfully with pip, but throw error while import folium
install failed with pip3
ubuntu
**To Reproduce**

```
[ Include a code snippet that produces your bug. Make it standalone, we should be able to run it. ]

[ Include a data sample or link to your data if necessary to run the code ]

```

**Expected behavior**

**Environment (please complete the following information):**
 - Browser [e.g. chrome, firefox]
 - Jupyter Notebook or html files?
 - Python version (check it with `import sys; print(sys.version_info)`) 2.7.17
 - folium version (check it with `import folium; print(folium.__version__)`) 0.8.3
 - branca version (check it with `import branca; print(branca.__version__)`) 0.4.1

**Additional context**

**Possible solutions**
List any solutions you may have come up with.

folium is maintained by volunteers. Can you help making a fix for this issue?

**Comment by Conengmo** [comment]
folium 0.8.3 does support Python 2. But branca 0.4 doesn’t. Try downgrading to branca==0.3.1. But you might run into issues with other dependencies as well, you’ll have to make sure you are using versions that are Python 2 compatible.

Better to upgrade to Python 3 if possible indeed.

**Comment by wyfSunflower** [comment]
failed to install on python 3.6.9 by pip3
