### ISSUE TITLE
Is there any way to make the map load faster ？

### ISSUE THREAD

**Issue by Winky678** [python-visualization/folium#1692]
![image](https://user-images.githubusercontent.com/41333749/211142944-16cdbb81-324d-4592-9715-7b3302f271c5.png)

Is there any way to make the map load faster ？

**Comment by Winky678** [comment]
I have an idea, download the source js and css under the local static folder, and script reference, but I don’t know where to download

**Comment by Conengmo** [comment]
Please follow the issue template and include code and possibly data if you want help.
