### ISSUE TITLE
On click circle radius changes not available

### ISSUE THREAD

**Issue by Krukarius** [python-visualization/folium#1701]
**Is your feature request related to a problem? Please describe.**

After adding the folium.Circle feature to the map I just get circles defined by radius. Having them several, they overlap each other when close enough and it seems like there is no option for switching them on/off by clicking on the marker too, which the circle has been appended. 

The issue in detail has been raised here:

https://stackoverflow.com/questions/74520790/python-folium-circle-not-working-along-with-popup

and here

https://stackoverflow.com/questions/75096366/python-folium-clickformarker-2-functions-dont-collaborate-with-each-other

**Describe the solution you'd like**
I would like to have an option that would allow me to control the folium.Circle appearance is based on the click feature keeping them invisible when the cursor is out of the circle range.

**Describe alternatives you've considered**
Tried to apply class Circle(folium.ClickForMarker): 
It doesn't work correctly. Despite if statement it appears for all the cases at once. Moreover, it remains in conflict with other classes ClickForOneMarker(folium.ClickForMarker): making it completely unusable.

**Additional context**
Provided in the link above

**Implementation**
The way of implementation should be creating a new option allowing using the on-click operation for folium.Circle feature.

**Comment by Conengmo** [comment]
I see the value of providing better on-click support in folium. But right now it's not in scope, and we don't have the developer capacity to work on that. If somebody comes along who wants to think about this topic, they are welcome to do so! But let's discuss in a new issue then. For now I'll close this one since it's not in scope.
