### ISSUE TITLE
Add coordinate units (lat/lon) on the map

### ISSUE THREAD

**Issue by adaatii** [python-visualization/folium#1702]
I would like to make a map containing the information of the coordinate units (lat/lon) with the gridline in a folium map similar to the image below.

![map_lat_lon](https://user-images.githubusercontent.com/80161447/212391574-ac2a385a-0154-4ed3-aa62-435890c71986.jpg)

I looked in the documentation but couldn't find it. Is this possible in folium currently in any way?

**Comment by Conengmo** [comment]
Nice idea! This is not possible with Folium currently. You could search for a Leaflet plugin that does this. If that exists, you could integrate that plugin with Folium.

I'll close this issue since there's not much to do here. If you do find that Leaflet plugin please do report back here!
