### ISSUE TITLE
add a menu at draw marker?

### ISSUE THREAD

**Issue by VictorCubas** [python-visualization/folium#1705]
I just add a menu onche you clic on the draw maker in draw.py toolbar
I modified the html of the map using this code

```
{{ this._parent.get_name() }}.on('draw:drawstart', function(e){
      var type = e.layerType,
          layer = e.layer;
      if (type === 'marker') {
          console.log('drawing starting...  ' + e.layer) 
          // Do marker specific actions
          
          var html = "<br><li class=''><a class='' title='Ubicacion de mujeres'>Ubicacion de mujeres</a></li><br>" + 
                  "<li class=''><a class='' title='Zona de Violencia'>Zona de Violencia</a></li><br>" +
                  "<li class=''><a class='' title='Poblaciones diversas'>Poblaciones diversas</a></li><br>";
          
          document.querySelector(".leaflet-draw-actions").innerHTML += html;
      }
  });
```
What i'm trying to do is to add a menu so the user can create a marker depending on what type of layer you choose previously
![current menu](https://user-images.githubusercontent.com/5679527/213692213-039979bc-3994-411a-ab90-4df4b615e09d.jpg)

When i do this, the "cancel operation" does not work anymore and dont know how to change the color of the marker draggable that it is displayed.

Any idea will be so helpful
Thank you and regards!

**Comment by Conengmo** [comment]
Hi Victor, nice to see that you are building cool things. Unfortunately this is a bit too far away from the typical folium use case to help you with here. I'd recommend you try Stackoverflow instead. And maybe instead of asking about folium, try looking more into Leaflet, since it seems like you are more working with Leaflet directly. Good luck!

**Comment by VictorCubas** [comment]
Thank you so much for taking your time and replyed me, I'll keep looking the way to develop this functionality and check more carefully about Leaflet. Good luck for you too!
