### ISSUE TITLE
Basic feature list - GeoJSON conversion

### ISSUE THREAD

**Issue by themiurgo** [python-visualization/folium#171]
In light of #169 , I think it's important to establish a list of core features that folium is able to support and should provide in the API.

Following Leaflet, it seems the fundamental types should be:

- [x] Marker
- [ ] Path: abstract
- [x] Polyline: this needs name change to Polyline
- [ ] MultiPolyline
- [ ] Polygon: at the moment we only have RegularPolygon
- [ ] MultiPolygon
- [ ] Rectangle
- [ ] Circle: not sure if we should include this.
- [x] CircleMarker.

We should also support:
- [ ] LayerGroup
- [x] FeatureGroup
- [ ] GeoJSON: I would say this is half done.

I think that everything else, like divicons ( #169 ) is only style-oriented and can't have it's own method.

Also, two thoughts for the feature:
- we might convert each of these feature to a class and have a generic folium.add_feature, to keep code a bit tidier.
- we might associate to each feature a Geojson representation. This would make straightforward to output the *data* associated to a map and make it visualisable in other platform (e.g. GitHub)

**Comment by ocefpaf** [comment]
@themiurgo can you parse this list against in the light of the latest changes?  I guess we are getting close.

**Comment by themiurgo** [comment]
I just did. :+1:

**Comment by ocefpaf** [comment]
Thanks!

**Comment by ocefpaf** [comment]
I believe most of this is already done. Either way we would need a new and refreshed issue to track what if someone was left out.
