### ISSUE TITLE
The Search plugin doesn't pick up csv files

### ISSUE THREAD

**Issue by Krukarius** [python-visualization/folium#1711]
**Is your feature request related to a problem? Please describe.**
The Python folium Search plugin can search just within .geojson files. Can it collaborate with Pandas and do the same for .csv files?

**Describe the solution you'd like**
I would like to extend the functionality of this plugin by .csv files, which can be read by Pandas library and next populated to the Folium map.

**Describe alternatives you've considered**
Turning CSV files into .geojson files that's the only option for now.

**Additional context**

**Implementation**
I wish I could if I learn Python more

**Comment by Conengmo** [comment]
Hi Krukarius, I think you already found the best solution: turn whatever form your data has into a geojson. Alternatively, the Search plugin should also work with a featuregroup with markers, though I haven't tried that myself. Other than that we have no plans to expand upon the Search plugin.

Just for your understanding, note that a csv file is a very flexible file format, so it's quite hard to have specific functionality for it. Much easier if you process your csv file yourself and fit it into a format that's easier to understand for folium, like geojson or directly creating markers and featuregroups.
