### ISSUE TITLE
0.1.5 / 2.0 release?

### ISSUE THREAD

**Issue by ianozsvald** [python-visualization/folium#172]
I'd love to be able to use the new tiles in public demos of folium (I'll be doing a lightning talk to 200+ at PyDataLondon next month). Is there any chance that there's going to be a post-0.1.4 release between now and then?

**Comment by ocefpaf** [comment]
I am pro [RERO](https://en.wikipedia.org/wiki/Release_early,_release_often), but we **really** need to polish the docs before a new release.  Maybe in a week (or 2).

**Comment by ianozsvald** [comment]
Cool! Thanks @ocefpaf

**Comment by ocefpaf** [comment]
Lets leave this open as a reminder...

**Comment by ocefpaf** [comment]
@ianozsvald done in https://github.com/python-visualization/folium/releases/tag/v0.1.5 and https://pypi.python.org/pypi/folium/0.1.5

Let me know how that works for you!

**Comment by ianozsvald** [comment]
Agreed that stamenwatercolor tiles now work, cheers :-) I've noted a bug in 0.1.5 though https://github.com/wrobstory/vincent/issues/142
Cheers!
