### ISSUE TITLE
🛠️ GroupedLayerControl plugin not working with raster tiles and GEE layers?

### ISSUE THREAD

**Issue by IndigoWizard** [python-visualization/folium#1720]
#### Main gist
[GroupedLayerControl](https://nbviewer.org/github/chansooligans/folium/blob/plugins-groupedlayercontrol/examples/plugin-GroupedLayerControl.ipynb) plugin don't seem to work with Folium raster tiles and raster layers as well as Earth Engine (GEE) raster layers (satellite imagery, environemental index (NDVI) raster layers... etc)

#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
import ee
from ee import image
import folium
from folium import features
from folium.plugins import GroupedLayerControl
import os
import webbrowser

# Triggering authentification to earth engine services
# Run in terminal: earthengine authenticate

# initializing the earth engine library (always keep this on)
ee.Initialize()

# ##### Define a method for displaying Earth Engine image tiles to folium map
def add_ee_layer(self, ee_image_object, vis_params, name):
  map_id_dict = ee.Image(ee_image_object).getMapId(vis_params)
  folium.raster_layers.TileLayer(
      tiles = map_id_dict['tile_fetcher'].url_format,
      attr = 'Map Data &copy; <a href="https://earthengine.google.com/">Google Earth Engine</a>',
      name = name,
      overlay = True,
      control = True
  ).add_to(self)

# Add EE drawing method to folium.
folium.Map.add_ee_layer = add_ee_layer

# Buffer/Circular AOI
aoi = ee.Geometry.Point([2.28, 36.615]).buffer(8000)

# Working with specific satellite imagery ID (sentinel-2)
image_satellite1 = ee.Image('COPERNICUS/S2_SR/20220218T102949_20220218T103126_T31SDA')
image_satellite2 = ee.Image('COPERNICUS/S2_SR/20230107T104329_20230107T104329_T31SDA')

# clipping satellite images to an Area Of Interest (a buffer circle in this case)
image_satellite1 = image_satellite1.clip(aoi).divide(10000)
image_satellite2 = image_satellite2.clip(aoi).divide(10000)

# Sattelite image visual parameters
image_params = {
  'bands': ['B4',  'B3',  'B2'],
  'min': 0,
  'max': 0.35,
  'gamma': 0.9
}

#################### MAIN MAP ####################
# setting up the main map for the project
m = folium.Map(location = [36.62, 2.3], tiles=None, zoom_start = 12, control_scale = True)

# ########## Primary basemaps (Victor data):
basemap1 = folium.TileLayer('cartodbdark_matter', name='Dark Matter').add_to(m)
basemap2 = folium.TileLayer('openstreetmap', name='Open Street Map').add_to(m)

#################### SPATIAL FEATURES LAYERS ####################

# #### MARKERS features layers
blue_marker_group = folium.FeatureGroup(
  name='Blue Marker',
  overlay=True,
  control=True,
  show=True
).add_to(m)

# Individual merkers (Not from a geojson file)
BLUE_MARKER = folium.Marker(
  location=[36.63, 2.26],
  popup= None,
  tooltip="<h4>Blue Marker.</h4>"
).add_to(blue_marker_group)

#################### GEE RASTER LAYERS ####################
# adding the satellite images as layers and display them on the map + on layer panel
m.add_ee_layer(image_satellite1, image_params, 'Image Satellite 1')
m.add_ee_layer(image_satellite2, image_params, 'Image Satellite 2')

#################### Layer controller ####################
folium.LayerControl(collapsed=False).add_to(m)

#################### LAYER GROUPS ####################
GroupedLayerControl(
    groups={
      '--------MARKERS LAYER--------': [blue_marker_group],
      #I want image_satellite1 & image_satellite2 to go in the bellow group here but it doesn't work
      #'--GOOLE EARTH ENGINE LAYERS--': [image_satellite1, image_satellite2]
    },
    exclusive_groups=False,
    collapsed=False
).add_to(m)

# save map as html file
m.save('map.html')
# Opening the map file in default browser on execution
webbrowser.open('map.html')

```
#### Problem description

[this should explain **why** the current behavior is a problem and what is the expected output.]

`Traceback (most recent call last):`
`  File "C:\Users\DELL\Documents\GitHub\Test-Projects\foliumtest\port\map.py", line 82, in <module>`
`    GroupedLayerControl(`
`File "D:\SnakePit\Anaconda3\envs\geoenv\lib\site-packages\folium\plugins\groupedlayercontrol.py", line 82, in __init__
    ] = element.get_name()`
`AttributeError: 'Image' object has no attribute 'get_name'`

![image](https://user-images.githubusercontent.com/43890965/217104096-2a964efd-9d53-41be-86c2-03d2f8e1181a.png)

#### Expected Output
|Current result |Wanted Results|
|--|--|
|![image](https://user-images.githubusercontent.com/43890965/217094605-8c0a588d-221a-43e6-a4d4-95e6965489e1.png)|![image](https://user-images.githubusercontent.com/43890965/217094523-e232fe5e-9312-42d2-84d1-326a76ec0dfe.png)|
|This result is when the code line 86: <br>`'--GOOLE EARTH ENGINE LAYERS--': [image_satellite1, image_satellite2]` is commented.<br>Otherwise it sends the error cited above:<br>`AttributeError: 'Image' object has no attribute 'get_name'` |I used in-browser element inspector and modified the Layer Control Panel just to give an understandable visual example of what It should look like.|

#### Output of ``folium.__version__``
Folium version: `0.14.0`

**Comment by jtmiclat** [comment]
@IndigoWizard I haven't had a chance to run your code but I think I know the Issue. `GroupedLayerControl` takes in folium layers and not gee Images. Here are small edits to your code

For `add_ee_layer` we want it to return a layer. 

```python
def add_ee_layer(self, ee_image_object, vis_params, name):
  map_id_dict = ee.Image(ee_image_object).getMapId(vis_params)
  layer = folium.raster_layers.TileLayer(
      tiles = map_id_dict['tile_fetcher'].url_format,
      attr = 'Map Data &copy; <a href="https://earthengine.google.com/">Google Earth Engine</a>',
      name = name,
      overlay = True,
      control = True
  )
  layer.add_to(self)
  return layer
  
folium.Map.add_ee_layer = add_ee_layer
``` 

Then we want to keep track of these layers in variables when we create them

```python
image_sat_1_layer = m.add_ee_layer(image_satellite1, image_params, 'Image Satellite 1')
image_sat_2_layer = m.add_ee_layer(image_satellite2, image_params, 'Image Satellite 2')
```

and these layers are what we pass to `GroupedLayerControl`
```python
GroupedLayerControl(
    groups={
      '--------MARKERS LAYER--------': [blue_marker_group],
      '--GOOLE EARTH ENGINE LAYERS--': [image_sat_1_layer, image_sat_2_layer]
    },
    exclusive_groups=False,
    collapsed=False
).add_to(m)
```

**Comment by IndigoWizard** [comment]
### Solution works perfectly ✔️ 
@jtmiclat Thank you for your answer, it works perfectly and as expected!
I knew I had to keep the layers as variables to add to groups but that wasn enough, I didn't know how to handle the GEE 'add_ee_layer' drawing method to get a proper layer. Your explanation makes sense.

### Preview
Result of the applied solution:
![image](https://user-images.githubusercontent.com/43890965/218288005-4bcb7fc8-6414-42af-b431-04ba87face87.png)

I even applied the solution to my main project and now it looks a bit more neat (with some CSS customization here and there):
|Before|After (with this solution)|
|--|--|
|![image](https://user-images.githubusercontent.com/43890965/218288109-47ae3cb0-3b75-486d-82f4-b9d1363c1c75.png)|![image](https://user-images.githubusercontent.com/43890965/218288072-c89bca48-95d6-48f3-9f83-6d414f8b42df.png)|

**NOTE:** Only little problem is that I can not use  the mouse wheel to scroll on the layer panel, only click & grab scrollbar works. Instead, using mouse wheel zooms in/out on the map even if I'm hovering on the grouped layer panel. I can even grab the map on top of the grouped panel. 
I may open a new issue for this because it applies to the GroupedLayerControl plugin whenever there's a scrollbar but I added here this note in case you may have a suggestion.

Here's the project link: 
- GitHub Repo: https://github.com/IndigoWizard/mega-port-environment
- GitHub Page: https://indigowizard.github.io/mega-port-environment/webmap.html (still haven't pushed the new changes to "develop" branch at the moment, checkout "feature/UI" branch.)

**Comment by jtmiclat** [comment]
@IndigoWizard Cool project! I think the scrollbar would be a separate issue but it might be tied to the underlying leaflet plugin foliumn is using

**Comment by IndigoWizard** [comment]
Very well, I'll open a separate issue for GroupedLayerControl scrolling issue.
For now, this issue #1720 has been solved and is now closed as complete. ✔️

**Comment by IndigoWizard** [comment]
Very well, I'll open a separate issue for GroupedLayerControl scrolling issue.
For now, this issue https://github.com/python-visualization/folium/issues/1720 has been solved and is now closed as complete. ✔️
