### ISSUE TITLE
Allow setting Marker IDs to allow for javascript manipulation at the frontend

### ISSUE THREAD

**Issue by jemm88** [python-visualization/folium#1724]
**Is your feature request related to a problem? Please describe.**
I've been trying to figure out how to set ids to the markers generated by folium so that I can link those markers to on-click events in the frontend.

**Describe the solution you'd like**
Something like:
folium.Marker([latitude,longitude],id="abc123").add_to(map) would be best, but at this stage I'll make do with anything.

**Describe alternatives you've considered**
I've looked through the folium, branca and the leaflet JS documentation and found this so far. But it dosen't seem to work with folium.
https://stackoverflow.com/questions/25683871/assign-id-to-marker-in-leaflet.
Granted, my JS is not great so I might not be doing stuff right.

**Additional context**

**Implementation**
folium is maintained by volunteers. Can you help make a PR if we want to implement this feature?

**Comment by Conengmo** [comment]
Hi @jemm88, the JS variable names are available in Python with the `get_name`method:

```
>>> marker = folium.Marker().add_to(m)
... print(marker.get_name())
marker_b76022bec70151160d875e0178758552
```

If you look at the generated html, you'll see something like this:

```
            var marker_b76022bec70151160d875e0178758552 = L.marker(
                [52.1, 5.0],
                {}
            ).addTo(feature_group_8124340aa1df4262ea6dfefb2caee77d);
```

Hope that answers your question!

**Comment by jemm88** [comment]
Hi Conengmo! Thanks for responding so quickly! It's really appreciated.
I saw the get_name() variable names but from what I notice, I'm unable to access them as the script is generated within an iFrame. What i'm hoping is to be able to assign the IDs at generation to the markers.

![image](https://user-images.githubusercontent.com/17311074/220016996-2a7c15c4-ba82-4f2e-833c-429b71ce6066.png)

Is that possible?

I've tried playing around to see if I could access the markers in the generated HTML but honestly it dosen't seem to work for me.  

Just using the console to see if i could access:
![image](https://user-images.githubusercontent.com/17311074/220017608-041ff4d9-1546-4294-adca-e2b8b91488fc.png)

It's based on a list of map names generated:
![image](https://user-images.githubusercontent.com/17311074/220017701-2a1fb027-5e4f-49bf-b0db-9e610c2a66b8.png)

**Comment by Conengmo** [comment]
ah I guess you are in a Jupyter Notebook. Would have been useful to include in your issue. Indeed an iframe is used there. You can access the marker through the iframe. For example:

```
iframe = document.getElementsByTagName('iframe')[0]
iframe.contentWindow.marker_39630f4fc77851a2e008ee9941636a97
```

**Comment by jemm88** [comment]
Ahh okay got it! Thank you very much this is appreciated.
