### ISSUE TITLE
Position of Colorscale

### ISSUE THREAD

**Issue by gutjuri** [python-visualization/folium#1725]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
geom = ... # some GeoDataFrame
style_func = ... # some style function


import braca
colorscale = braca.colormap.LinearColormap(["yellow", "red"]).scale(0, 30)
m = folium.Map(location=[48.7758459, 9.1829321], zoom_start=8, perfer_canvas=True)
g = folium.GeoJson(data=geom, style_function=style_func, name="Colours").add_to(m)
m.add_child(colorscale)
```
#### Problem description

On the generated map, the colorscale is always in the top-right corner.
However, i'd like to position the colorscale at some coordinates in the map, such that the colorscale moves when I pan the map.
Is this possible in folium? 
I'd appreciate any help :)

#### Output of ``folium.__version__``

`0.13.0`

**Comment by Conengmo** [comment]
That's not currently possible, and not something we are planning to support.

(Link to https://github.com/python-visualization/folium/issues/1605 for a slightly related issue)
