### ISSUE TITLE
🐞 GroupedLayerControl plugin layer panel is "clickthrough" / click propagation bug

### ISSUE THREAD

**Issue by IndigoWizard** [python-visualization/folium#1726]
**Describe the bug**
The secondary layer panel created by the [GroupedLayerControl](https://nbviewer.org/github/chansooligans/folium/blob/plugins-groupedlayercontrol/examples/plugin-GroupedLayerControl.ipynb) is buggy in a way that we can drag the map and zoom in/out of the map over that secondary layer panel.

**To Reproduce**
The bug/behavior can even be experienced in the official folium plugin nbviewer: [GroupedLayerControl](https://nbviewer.org/github/chansooligans/folium/blob/plugins-groupedlayercontrol/examples/plugin-GroupedLayerControl.ipynb) . Hover mouse cursor over the secondary layer control panel and:
- Zoom in/out (using the mouse wheel).
- Grab the map and navigate it straight through the panel as it is clickthrough.

**Code:**
Link to notebook nbviewer (same issue apply in html file):
[🐞 GroupedLayerControl plugin clickthrough / click propagation bug nbviewer](https://nbviewer.org/gist/IndigoWizard/cfa98f35138371daab4ac829196b4a95)

**Additionally**
This is not necessary for the issue but can be useful to check the bug in the main project where I'm using the plugin in : 
- GitHub Repo: https://github.com/IndigoWizard/mega-port-environment
- GitHub Page: https://indigowizard.github.io/mega-port-environment/webmap.html (the map is based off new changes push to the "feature/UI" branch unlike the preview bellow that's on "develop" branch.)

**Preview:**
<video src="https://user-images.githubusercontent.com/43890965/218621937-7136c88e-afbe-4f65-907d-3129c798d79e.mp4">

**Expected behavior**
- The layer panel generated by the plugin shouldn't be clickthrough.
- You should be able to scroll up/down using the mouse wheel by hovering over the grouped layer panel.
- You shouldn't be able to grab and drag the map and zomm in/out through the grouped layer panel.
- You should only be able to check/uncheck layer checkboxes.

**Environment (please complete the following information):**
 - Browser FireFox 109.0.1 (64-bit)
 - Jupyter Notebook or html: Both
 - Python version 3.10.8
 - folium version 0.14.0
 - branca version 0.6.0

**Additional context**
It makes it difficult to navigate the grouped layer panel when we have many layers and I have to use a scrollbar. Scrolling the panel using the mouse wheel is impossible and instead zooms in/out which is not comfortable for user experience.

**Possible solutions**
No idea.

folium is maintained by volunteers. Can you help making a fix for this issue?
No.

**Comment by Conengmo** [comment]
Great issue report, thank you. I agree with it, though unfortunately there's not much we can do in folium. These issues lie in the upstream JS package we use. We provide these "as-is" and can't take responsibility for fixing them, since we have enough work with just folium already!

I see there's an open issue in the upstream package for the scrolling at least: https://github.com/ismyrnow/leaflet-groupedlayercontrol/issues/61. There's an open PR as well, but it seems unlikely to get merged.

I'll close this issue since there's not much we can do here.
