### ISSUE TITLE
Embed html image into Folium Popup

### ISSUE THREAD

**Issue by zach2348** [python-visualization/folium#1731]
#### Code used to ATTEMPT to display html image into popup
```python
html1 = '<iframe src="data:text/html;base64,{}"></iframe>'.format
encoded = base64.b64encode(open('Erie_fig.html', 'rb').read()).decode()

marker = folium.Marker(
    location=(df_beet_20.Lat[i], df_beet_20.Long[i]),
    icon=folium.Icon(icon=i_dict['Beetus'], color=c_dict['Beetus'])).add_to(beetus_20)

from folium import IFrame
iframe = IFrame(html1(encoded), width=200+20, height=200+20)
folium.Popup(iframe, max_width=1000).add_to(marker)
```

How can I embed an HTML image into a Folium Popup? I am able to place a png image into my Folium Popup with no issue, however, when I try to use the same logic with an HTML image (more specifically a plotly figure) my popup is just a blank white box.

#### Bad output
![image](https://user-images.githubusercontent.com/95710524/220682953-bd07bcd3-43df-497a-906c-78e6fc47d00f.png)

####  Code used to display png image into popup
```python
html1 ='<iframe src="data:image/png;base64,{}"\>'.format
encoded = base64.b64encode(open('example.png', 'rb').read()).decode()
iframe = IFrame(html1(encoded), width=200+20, height=200+20)
 
folium.Marker(
location = (df_beet_20.Lat[i], df_beet_20.Long[i]),
popup = folium.Popup(iframe, max_width=1000),
icon = folium.Icon(
icon = i_dict['Beetus'], color = c_dict['Beetus'])).add_to(beetus_20)
```

The code above is what I have used to display a png image into my popup, an it works just fine. However, when I attempt to place an html image into the popup I get returned a blank white box in my popup.

#### Expected Output
I am attempting to have the html image (plotly figure) appear in the popup just as I was able to have the png appear.

#### Version
folium==0.14.0

**Comment by jtmiclat** [comment]
Hi @zach2348  html is not an image so you dont have to encode it the same way you do with with a png. You might be able to get away with just reading an html as a string and passing it to the Popup as an folium.Html or folium.IFrame. 

```python
import folium 
import base64


m = folium.Map(location=[45.5236, -122.6750])
with open("index.html") as f:
    html = f.read()

marker = folium.Marker(location=(45.5236, -122.6750))

pop_up = folium.Popup(folium.Html(html, script=True), max_width=1000).add_to(marker)
marker.add_to(m)
m
```

and if you want to use iframe which might be needed for very complex html files
```python
import folium 
import base64


m = folium.Map(location=[45.5236, -122.6750])
with open("index.html") as f:
    html = f.read()

marker = folium.Marker(location=(45.5236, -122.6750))

pop_up = folium.Popup(folium.IFrame(html, width=200+20, height=200+20), max_width=1000).add_to(marker)
marker.add_to(m)
```

**Comment by zach2348** [comment]
Hey @jtmiclat, thanks for the reply! 

If I try the first option you provided I get returned my html without the map with text at the bottom. I have a snipit screenshot below. The second option returns to me the same blank pop-up I was getting before. I'm unsure if I am doing something completely wrong or perhaps its an issue with the version of folium I am using? Are you able to produce the contents of an HTML file in a folium popup?

**Screenshot of me attempting the second option you provided**
![image](https://user-images.githubusercontent.com/95710524/221943469-5588bf56-0b05-444b-9a87-caec617539e9.png)

Thanks!

**Comment by jtmiclat** [comment]
@zach2348 I only tested it with a very simple html file.


I looked into poltly and was able to get it to work using the following code to generate a plot.ly diagram. Notice on the export i had to set `inlclued_plotlyjs='cdn'`  . My hunch was there was some file size limitation when embedding the entire plot.ly library to the the iframe
```python
# Generate plotly diagram
import plotly.express as px

fig =px.scatter(x=range(10), y=range(10))
fig.write_html("plotly.html", include_plotlyjs='cdn') # I had to set include_plotlyjs to get it to work

# Plot it within the map
import folium 

m = folium.Map(location=[45.5236, -122.6750])
with open("plotly.html") as f:
    html = f.read()

marker = folium.Marker(location=(45.5236, -122.6750))

pop_up = folium.Popup(folium.IFrame(html, width=300+20, height=300+20), max_width=1000).add_to(marker)
marker.add_to(m)
```

![example](https://user-images.githubusercontent.com/30991698/222197508-2785eaa5-d0e5-4a14-abed-b6dd1e7fba4b.PNG)

**Comment by zach2348** [comment]
@jtmiclat Thank you so much! This worked like a charm! You've been a tremendous help
