### ISSUE TITLE
Cannot import the Map from folium package 

### ISSUE THREAD

**Issue by haniyrasul** [python-visualization/folium#1733]
**Description**
I have imported the folium package, when I tried to access the Map from folium, it returns AttributeError: module 'folium' has no attribute 'map'

**To Reproduce**

```
import folium
folium.Map()
![image](https://user-images.githubusercontent.com/81812457/222940266-3d197251-3076-4a33-8901-a97c2c9550aa.png)


```

**Expected behavior**

**Environment:**
 - Microsoft Edge
 - Jupyter Notebook
 - Python version: Python 3.9.7
 - folium version: folium 0.14.0
 - branca version: Not Installed

folium is maintained by volunteers. Can you help making a fix for this issue? Yes

**Comment by ocefpaf** [comment]
Do you have a file named folium.py in your path? You may be importing that instead.

**Comment by haniyrasul** [comment]
Yeah thanks, After the deletion of the file, it shows No Module named
'folium'; can you please help me with that?

Regards,
Rasul. MAH
[image: image.png]

**Comment by ocefpaf** [comment]
You will have to install it. If you are using pip you can do:

pip install folium

If you are a conda user you can try:


conda install -c conda-forge folium

**Comment by haniyrasul** [comment]
Yeah, I've installed using pip in this virtual environment, and when I
check the list it's already there, but I still got the same error

**Comment by ocefpaf** [comment]
I'd recommend removing that env and trying again. This is not a problem with folium but your environment.

**Comment by haniyrasul** [comment]
That really worked out well. I had to remove the environment, and now it's
working perfectly. Thanks!
