### ISSUE TITLE
TypeError received while trying to create Folium Colorline

### ISSUE THREAD

**Issue by Grim97** [python-visualization/folium#1741]
**Creating a ColorLine results in TypeError **
Internally code hits the *class LinearColormap*of colormap.py Ln 235, where vmin and vmax are holding string value of color(red, green etc). But we are doing '-' and here it is not supported with string type and error is raised.
```
# sample.py
import folium
from folium import features
map_object = folium.Map(location=[15.235683, 75.167737], zoom_control=True, zoom_start = 10, control_scale=True)
color=['red','green','blue']  # should be of length len(coordinates) -1
line = features.ColorLine(coordinates,colors = color , weight= 10)
# line2 = folium.ColorLine(coordinates,colors = color , weight= 10)
line.add_to(map_object)
```
Output in the console:
```
Traceback (most recent call last):
  File "<xxx>\Interactive maps\main.py", line 12, in <module>       
    line = features.ColorLine(coordinates,colors = color , weight= 10)
  File "<xxx>\Python39\lib\site-packages\folium\features.py", line 1892, in __init__
    if colormap is None:
  File "<xxx>\Python39\lib\site-packages\branca\colormap.py", line 235, in __init__
    self.index = [vmin + (vmax-vmin)*i*1./(n-1) for i in range(n)]
  File "<xxx>\Python39\lib\site-packages\branca\colormap.py", line 235, in <listcomp>
    self.index = [vmin + (vmax-vmin)*i*1./(n-1) for i in range(n)]
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

**Expected behavior**
In the class documentation, 
```
colors : list-like object with at least two colors.
        The set of colors to be used for interpolation.
        .... .... ....
        *** a color name or shortcut (e.g: `"y"` or `"yellow"`)**
```
string value is also supported. So expected it to get handled

**Environment (please complete the following information):**
 - Browser Google Chrome(causes no impact on the observed issue)
 - Generated HTML file.
 - Python version (check it with `import sys; print(sys.version_info)`)
    => Python 3.9.4. sys.version_info(major=3, minor=9, micro=4, releaselevel='final', serial=0)
 - folium version (check it with `import folium; print(folium.__version__)`)
    => 0.14.0
 - branca version (check it with `import branca; print(branca.__version__)`)
    => 0.6.0 

**Possible solutions**
Thought about cross refering the hex code of vmin and vmax with the colors attribute and then convert it into float type.

folium is maintained by volunteers. Can you help making a fix for this issue?
Yes.

**Comment by Conengmo** [comment]
Though the docstring of `ColorLine` could be better, it does specify `color` should be floats: https://github.com/python-visualization/folium/blob/main/folium/features.py#L1875

It's maybe confusing, but `color are actually number values that are mapped to colors using `colormap`. See the first example here: https://nbviewer.org/github/python-visualization/folium/blob/main/examples/Features.ipynb
