### ISSUE TITLE
Choropleth key_on doesn't allow for traversing an array

### ISSUE THREAD

**Issue by rye761** [python-visualization/folium#1742]
**Is your feature request related to a problem? Please describe.**
Can't match based on a property which hides the property you need in an array. Such as the following in a geojson for Canadian provinces I want to use:

```json
"properties":{
   "geo_point_2d":{
      "lon":-114.51101438986483,
      "lat":55.16890299842028
   },
   "year":"2021",
   "prov_code":[
      "48"
   ],
   "prov_name_en":[
      "Alberta"
   ],
   "prov_area_code":"CAN",
   "prov_type":"province",
   "prov_name_fr":"Alberta"
}
```

I'm not sure why this hides the English province name in an array, but if I've run into this I'm sure it could be an issue for someone else at some point too.

**Describe the solution you'd like**

Either `feature.properties.prov_name_en.0` or `feature.properties.prov_name_en[0]` should work.

**Describe alternatives you've considered**

Alternatives above, short of implementation I must modify the file for now.

**Additional context**

**Implementation**
folium is maintained by volunteers. Can you help make a PR if we want to implement this feature?

I would consider helping with PR if given guidance on preferred implementation.

**Comment by Conengmo** [comment]
Hi @rye761, I think I see your problem! You're right this currently doesn't work in Folium. To be honest changing your data does seem like the easiest solution :)

But if you are inclined to make a PR, you could look at the `get_by_key` function that's defined inside the `GeoJson` class. This function tries to use the Javascript object path to index the Python data. Currently it assumes each key in the path is a string, so it just does `obj.get(key, None)`. We could alter it to check whether `key` is an integer-as-string, and if that's the case do indexing instead. I'm thinking something like:

```
if key.isdigit():
    obj[int(key)]
else:
    obj.get(key, None)
```

Ideally this function `get_by_key` should become a private method on `GeoJson` so we can also have some test cases added.

**Comment by amrutharajashekar** [comment]
Hi @Conengmo , I have submitted PR . ( https://github.com/python-visualization/folium/pull/1772 )
Please let me know if any other changes are required.
Thanks!
