### ISSUE TITLE
multiple TimeSliderChoropleth fails

### ISSUE THREAD

**Issue by Sponka** [python-visualization/folium#1744]
**Describe the bug**

I was trying to visualise multiple time series in one map using TimeSliderChoropleth. I tried multiple variations of the code you can see on the screenshot, but every time it returned a map with blue patches. I would like to ask if there is any solution to this issue. 

![Screenshot from 2023-04-03 18-30-39](https://user-images.githubusercontent.com/37693099/229572457-5ea63ee4-568b-4234-986c-4922d4a72011.png)

**To Reproduce**

```
wales = folium.Map([52.395180, -3.511841],zoom_start=7.5)
ts1 = TimeSliderChoropleth(area_sites,name = 'A', styledict=sd_p,
                     overlay=True, show=False)
ts2 = TimeSliderChoropleth(area_sites,name = 'B', styledict=sd_m,control=True,
                     overlay=True, show=False)
ts1.add_to(wales)
ts2.add_to(wales)

folium.LayerControl().add_to(wales)
wales#.save("testmap.html")
```

**Expected behavior**
Would it be possible to add multiple TimeSliderChoropleth?

**Environment (please complete the following information):**
 - Browser Chrome
 - Jupyter Notebook
 - Python version sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)
 - folium version 0.14.0
 - branca version 0.6.0

**Comment by Conengmo** [comment]
Hi @Sponka, unfortunately the `TimesliderChoropleth` plugin currently doesn't work when you add multiple to a single map. You could work around this by creating one map for each choropleth you want to make.

There's no easy fix for this. If someone feels called to work on the `TimeSliderChoropleth` plugin, you are welcome to. Though please get in touch about what you are planning to do first.

**Comment by Conengmo** [comment]
Update: worked on this for a little bit, made it so that we can have multiple instances of `TimeSliderChoropleth` on a single map.

@Sponka could you maybe give it a try? https://github.com/python-visualization/folium/pull/1749 Love to hear if it works for you, and whether you encounter any unexpected behavior. That will help determine if we can merge this into the main branch.

**Comment by Sponka** [comment]
Hi!

Thank you very much for your quick response and changes. I tried it today with five different TimeSliderChoropleth, and it worked without issues. I will try some more variations and let you know if I encounter any problems.
