### ISSUE TITLE
Map doesn't get updated when creating multiple maps in Jupiter notebook

### ISSUE THREAD

**Issue by phuphan13** [python-visualization/folium#1747]
Hi everyone,

I have a minor issue when creating a multiple heatmap within a same Jupiter notebook, but it seems the map somehow doesnt get updated until I tried to click on each map and zoom in zoom out several times. 

In short, I have created a function named createHeatmap as follows:

def showHeatmap(df, criteria):
    mapObj = folium.Map(location=['-33.8568','151.2153'], zoom_start=8, control_scale=True)
    map_data = list(zip(df['Latitude'], df['Longitude'],df[criteria]))
    heatMap = HeatMap(data=map_data, min_opacity = 0.6, blur=20, radius=15, overlay=True)
    heatMap.add_to(mapObj)
    return mapObj

Then call this function several times as follows:

showHeatmap(df,'Score 1')
showHeatmap(df,'Score 2')
showHeatmap(df,'Score 3')

Three maps are show but at the beginning they are identical until I jumped into each map, tried to zoom in and out several times, then each map will reflect the right density. 

So may I ask is it an error or something else? thanks million

**Comment by Conengmo** [comment]
I'm sorry, I can't really help you with the issue you've written. Maybe you can try Stackoverflow? And apart from the code include maybe some screenshots to show the problem you're having.
