### ISSUE TITLE
How to make a python folium interactive map with draggable legend and clickable items to zoom into the corresponding locations

### ISSUE THREAD

**Issue by xiaozheshen** [python-visualization/folium#1753]
**Is your feature request related to a problem? Please describe.**
I am trying to create an interactive map using python folium package. The feature I am looking for is, for a given list of locations, there are icons on the map, and a draggable legend (so that one can reposition the legend by dragging it using the mouse) for each of the locations, and one can click on one of the items in the legend to zoom into the corresponding location on the map.

Could you show me a minimum script (say for two locations, New York and Boston) so that I can get started?

Many thanks! 

Sam

This is what I have so far
`import folium

\# create map object centered at New York City
m = folium.Map(location=[40.7128, -74.0060], zoom_start=10)

\# add marker for New York City with icon
folium.Marker(
    location=[40.7128, -74.0060],
    popup='New York City',
    icon=folium.Icon(icon='star')
).add_to(m)

\# add marker for Boston with icon
folium.Marker(
    location=[42.3601, -71.0589],
    popup='Boston',
    icon=folium.Icon(icon='cloud')
).add_to(m)

\# create legend and add to map, it seems the preview function is not compatible with html script here, so it does not display the full script. If you can look at the raw script you can see clearer. But basically here is to add html for the legend. 
legend_html = \"""
     <div style='position: fixed; 
                 bottom: 50px; left: 50px; width: 150px; height: 90px; 
                 border:2px solid grey; z-index:9999; font-size:14px;
                 background-color:white; padding: 10px;'>
         <b>Legend</b><br>
         <i class='fa fa-star fa-2x' style='color:blue'></i> New York City<br>
         <i class='fa fa-cloud fa-2x' style='color:green'></i> Boston
     </div>
\""" 

m.get_root().html.add_child(folium.Element(legend_html))`

**Describe the solution you'd like**
I am not familiar with the API, and I searched over the internet, but did not get useful information to get started. So I am asking if someone can give a minimum example to give me a jump start.

**Describe alternatives you've considered**
Not yet.

**Additional context**
N/A

**Implementation**
If there is convenient function to implement the features I asked for, I definitely would be happy to write a PR for it.

**Comment by Conengmo** [comment]
Hi Sam, the Folium documentation and examples should be enough to get you started:

- https://python-visualization.github.io/folium/
- https://nbviewer.jupyter.org/github/python-visualization/folium/tree/main/examples/

You're probably looking to group your markers in a `FeatureGroup`, then using `LayerControl`  to be able to select which groups to show. 

Note that moving the control around is not supported. But it's pretty simple, so I'll open a PR for it.
