### ISSUE TITLE
Where 'map.save' code is?

### ISSUE THREAD

**Issue by banderlog** [python-visualization/folium#1759]
Where 'map.save' code is? I want to convert all to html and transfer it without saving locally, but I am even unable to find relevant part of code with searching "save" in repo

**Comment by Conengmo** [comment]
Correct, the `save` method is not part of Folium, but of its parent package Branca. All Folium classes inherit from Branca's `Element` class, which contains a `save` method. See https://github.com/python-visualization/branca/blob/main/branca/element.py#L175.

But if you want to get just the html of the map, you can use this:

```
m = Map()
html = m.get_root().render()
```

Hope that helps!
