### ISSUE TITLE
Cannot inline a map that binds features to data

### ISSUE THREAD

**Issue by papajohn** [python-visualization/folium#176]
Below, I've written a minimal program that ideally would run inside a Jupyter Notebook and generate the colored map from http://bl.ocks.org/wrobstory/5609830 . Unfortunately, the map does not render because `_build_map` creates HTML that depends on a `data.json` file (generated in `create_map`, which I never call). 

Instead of requiring File IO in order to create a map that binds features to data (by hard-coding `data.json` as the data path), would you consider adding the option of passing data to `_build_map` and inlining it into the HTML? That way, rendering the result in a Jupyter notebook would be straightforward.

The data files in this example are taken from http://bl.ocks.org/wrobstory/5609830
Example:

```python
import json
import pandas
import folium
from IPython.core.display import HTML

data = pandas.read_csv('tests/us-unemployment.csv')
map = folium.Map(location=[48, -102], zoom_start=3)
geo_path = 'tests/us-states.json'
geo = json.load(open(geo_path, 'r'))
map.geo_json(
    geo_path=json.dumps(geo), 
    data=data, 
    columns=['State', 'Unemployment'], 
    fill_color='YlGn', 
    key_on='feature.id',
)

def inline(m, width, height):
    """Returns an embedded iframe of a folium.map."""
    m._build_map()
    src = m.HTML.replace('"', '&quot;')
    style = "width: {}px; height: {}px".format(width, height)
    return '<iframe srcdoc="{}" style="{}"; border: none"></iframe>'.format(src, style)

HTML(inline(map, 900, 500))
```

Result:

![screen shot 2015-08-13 at 11 04 33 am](https://cloud.githubusercontent.com/assets/320145/9257571/2675d204-41ab-11e5-8722-b8ead9cbeecc.png)

**Comment by papajohn** [comment]
By the way, this hack makes the map display correctly in the notebook by inlining the JSON data.

```
html = inline(map, 900, 500)
for name, data in map.json_data.items():
    html = html.replace('d3.json, ' + repr(name), 'function(callback){callback(null, JSON.parse('+ repr(json.dumps(data).replace('"', '&quot;')) + '))}')
HTML(html)
```

**Comment by ocefpaf** [comment]
We are working on a better integration with IPython/Jupyter notebooks.  Good to know that the JSON in-lining works.  I am pretty sure a lot of people will use that until we actually fix this. Thanks @papajohn!

**Comment by ocefpaf** [comment]
I just noted that in your code you are dumping the GeoJSON like this `geo_path=json.dumps(geo)`.  I don't think that will inline the JSON for you.  Folium takes a file name as an argument there.

**Comment by papajohn** [comment]
@ocefpaf Changed `geo_path` to `geo_str` in my comment.

**Comment by ocefpaf** [comment]
OK.  We are always between elegance (saving the data to files and serving them alongside the HTML) or practicality (in-lining/embedding  everything).  Maybe we should add a keyword "stand-alone" somewhere...  Not sure what is the best solution, but the problem is arising way too often.

Meanwhile we have your JSON in-lining hack or the function below (note that it dumps the JSON data to a file):

```python
def inline_map(m, width=750, height=500):
    if isinstance(m, Map):
        m._build_map()
        if m.json_data:
            for path, data in m.json_data.items():
                with open(path, 'w') as g:
                    json.dump(data, g)

        srcdoc = m.HTML.replace('"', '&quot;')
        embed = HTML('<iframe srcdoc="{srcdoc}" '
                     'style="width: 100%; height: 500px; '
                     'border: none"></iframe>'.format(srcdoc=srcdoc))
    elif isinstance(m, str):
        embed = IFrame(m, width=width, height=height)
    return embed
```

**Comment by BibMartin** [comment]
@ocefpaf 
> Maybe we should add a keyword "stand-alone" somewhere...

I guess this could be a keyword argument int the `render` method of each `figure/map/plugin/template`.
Don't you think so ?

**Comment by ocefpaf** [comment]
> I guess this could be a keyword argument int the `render` method of each `figure/map/plugin/template`.
Don't you think so ?

I think that it would work.

The main problem relate to this that arises quite often  is displaying the map on Jupyter/IPython notebooks (and gist-ing them).  In that case I guess we could not give the user an option and always inline everything.  It is ugly but it works!  And people looking for elegance could just save the HTML and serve everything on their own.

**Comment by BibMartin** [comment]
Yes, exactly. It would give something like:
```python
class Map(object):
    def render(self, output="https", **kwargs):
        ...
    def _repr_html_(self, **kwargs):
        ...
        self.render(output='inline')
        ... # some iframe trick
        ...
```

**Comment by ocefpaf** [comment]
@BibMartin I am trying to implement something for the `v0.1.6` that could help us later to implement your idea.  I just want to get out of the way first.
