### ISSUE TITLE
matplotlib colormap for Choropleth(fill_color=map) and HeatMap()

### ISSUE THREAD

**Issue by FlorinAndrei** [python-visualization/folium#1762]
**Is your feature request related to a problem? Please describe.**
See the maps on this demo:

https://www.kaggle.com/code/alexisbcook/interactive-maps

It looks okay with `Choropleth(fill_color='YlGnBu')` but it would look better with a proper perceptually uniform colormap.

Same for `HeatMap()`.

**Describe the solution you'd like**
I would like to plug `matplotlib.cm.viridis` into the color arguments for these functions.

**Describe alternatives you've considered**
I've tried to build a Python function that would give Choropleth the color format it needs, but it looks like it only accepts a narrow and rigid scheme of colors.

**Comment by Conengmo** [comment]
See this example notebook for how you can do more with colormaps: https://nbviewer.org/github/python-visualization/folium/blob/main/examples/Colormaps.ipynb. And this guide on how to build custom choropleths: https://nbviewer.org/github/python-visualization/folium/blob/main/examples/GeoJSON_and_choropleth.ipynb.

As for `HeatMap`, it already provides an argument to set the colors, see the `gradient` argument: https://python-visualization.github.io/folium/plugins.html#folium.plugins.HeatMap
