### ISSUE TITLE
Documentation Page is down

### ISSUE THREAD

**Issue by JimSting** [python-visualization/folium#1771]
**Describe the bug**
The link for https://python-visualization.github.io/folium/ 

It's available in Wayback Machine on April 5, 2023

**To Reproduce**

1. Think of something you need to research in Folium
2. Click https://python-visualization.github.io/folium/ 
3. Frustrate, then go to Wayback machine or ask ChatGPT (With limited success)

**Expected behavior**
The page loads

**Environment (please complete the following information):**
 - Chrome and Safari
 - Google link

**Additional context**
Thanks in advance for the great docs that are out there, I'd love to see them live again. 

**Possible solutions**
Fix the link

folium is maintained by volunteers. Can you help making a fix for this issue?

Sure, with access

**Comment by Conengmo** [comment]
Hmm that’s weird, the link you shared does seem to include https. Both http and https work for me. I can’t see that image, can you try again? What do you see if you click the lock icon left of the address bar if your browser?

https://python-visualization.github.io/folium/

**Comment by JimSting** [comment]
![image](https://github.com/python-visualization/folium/assets/122387361/9476fe34-9511-41c5-b7a7-3c0d44b54ddd)

Ah, I responded by email before and attached it, I guess it didn't work.

**Comment by ocefpaf** [comment]
@JimSting you may have a problem with your SSL certificates. How do other HTTPS sites fair for your? Like another GitHub document webpage say, https://teos-10.github.io/GSW-Python/, for example?

If that doesn't work I would recommend you to check your browser and/or local SSL certificates.

**Comment by ocefpaf** [comment]
> I got the content I need, but am happy to help continue troubleshooting. If you can think of anything I can do with my certs. Maybe I'm missing a root one that you have and I don't. I checked all of mine, and they're valid. A missing one would make sense.

I'm not an expert on the topic, it may be even your Internet Service Provider's  (ISP) fault there. If you can try your laptop/browser on another connection and it works you can probably blame it on your ISP. Anyway, this is not a problem with folium or something we can fix. I'm closing the issue.

I hope you figure out what is going on with your system. Good luck!
