### ISSUE TITLE
Geocoder with own locations

### ISSUE THREAD

**Issue by JohnyCarrot** [python-visualization/folium#1786]
Greetings, i slightly edited geocoder such that it can now accept your own places. 

https://github.com/JohnyCarrot/folium-geocoder-own-locations

Hope someone find it usefull.

**Comment by Conengmo** [comment]
Cool Johny, thanks for sharing! I'll keep this issue open to remind me to add this to our list of external plugins.

**Comment by hansthen** [comment]
@Conengmo Is the list of external plugins the one in `README.rst`? If so, I can add it.

**Comment by Conengmo** [comment]
That's right!

**Comment by Conengmo** [comment]
Added to the readme in https://github.com/python-visualization/folium/pull/1927
