### ISSUE TITLE
Update jquery

### ISSUE THREAD

**Issue by hottwaj** [python-visualization/folium#1787]
The default version of jquery used by folium is from 12 years ago and has several known vulnerabilities that make it unsuitable for use in production websites

https://security.snyk.io/package/npm/jquery/1.12.4

**Comment by Conengmo** [comment]
- see where we use jquery
- see if there are breaking changes that affect us going from v1 to v3
- test
- merge

**Comment by hottwaj** [comment]
I think that the main place jquery is used is `folium.Map.default_js`

I've had no issues (so far) replacing the jquery element in that list with e.g. 3.6.0 i.e.

```
default_js = [
        k for k in folium.Map.default_js if k[0] != 'jquery'
    ] + [("jquery", "https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js")]
```

I was just looking into whether Leaflet itself uses jQuery, but did not find an obvious reference/import of it...
Thanks!

**Comment by Conengmo** [comment]
Thanks @hottwaj for helping with this!

Looks like we do use jquery in multiple places, so we can't just drop it: https://github.com/search?q=repo%3Apython-visualization%2Ffolium+%24+path%3A%2F%5Efolium%5C%2F%2F&type=code

Doesn't look like we use any fancy functions or anything, so hopefully just upgrading to v3 will work without issue. But it'll be good to check the features that use jquery to verify they still work:

- [ ] `Popup`
- [ ] `TimeSliderChoropleth`
- [ ] `GeoJson` with a url as data
- [ ] `Map.keep_in_front()`
