### ISSUE TITLE
How to get TimeStampedGeoJson slider value while playing 

### ISSUE THREAD

**Issue by saipuligandla** [python-visualization/folium#1790]
I want to print dynamic default time slider values while time slider moving in timestampedGeoJson  plyugin to map those values in other slider using PyQt5.

Kindly help me out to resolve this issue.

Thank you.
`        self.timestamped_geojson = TimestampedGeoJson(
            {
                "type": "FeatureCollection",
                "features": features,
            },
            duration='PT0M',
            period="PT1M",
            auto_play=self.auto_play,
        ).add_to(map)  `

**Comment by Conengmo** [comment]
I’m afraid I can’t help you with that. That class, like folium in general, is a one way street from Python to JavaScript. In general there are no built in ways to get stuff back to JavaScript. You’ll have to make a webserver yourself and make callbacks. Or use another package that provides more dynamicness.

**Comment by saipuligandla** [comment]
Hi @Conengmo,

Thank you for your prompt response. I appreciate your assistance in this matter.

Given that I'm relatively new to working on these types of tasks, could you kindly recommend an alternative library that might be better suited for my requirements using python? Any guidance you can provide would be greatly valued.

Your help is invaluable to me. Thank you once again for your time and support.
