### ISSUE TITLE
Stamen tiles are deprecated

### ISSUE THREAD

**Issue by martinfleis** [python-visualization/folium#1803]
We include built-in support for Stamen tiles, but Stamen is deprecating them and moving under Stadia, which requires an API key. See https://stamen.com/here-comes-the-future-of-stamen-maps/

The URLs we include will not work anymore. `leaflet-providers` moved Stamen tiles under their Stadia provider in https://github.com/leaflet-extras/leaflet-providers/pull/520. The question is what we do in folium. We can't just use the new Stadia URL as that will not work without an API key. And we cannot provide one because the free account has a limit that we would immediately exceed given the popularity of folium. I'm afraid that we will have to remove them without a replacement.

**Comment by jilljenn** [comment]
https://github.com/CooperHewittCollection/watercolor_examples
```python
folium.Map(
    location=(48.8330293, 2.3618845),
    tiles='https://watercolormaps.collection.cooperhewitt.org/tile/watercolor/{z}/{x}/{y}.jpg',
    attr='Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under CC BY SA.',
    zoom_start=5
)
```
You may want to put Stamen Watercolor shortcut back?
![Screenshot 2023-11-05 at 12-24-41 XCPC - Jupyter Notebook](https://github.com/python-visualization/folium/assets/1729581/6e768542-2c92-439a-ae79-87cea44d2878)

**Comment by martinfleis** [comment]
@jilljenn If these are alive from other source now, I would suggest adding them to https://github.com/leaflet-extras/leaflet-providers. They will then propagate to folium via xyzservices and the whole ecosystem will benefit from the addition, not just folium.
