### ISSUE TITLE
 Regression with 0.1.5 using vincent line chart

### ISSUE THREAD

**Issue by ianozsvald** [python-visualization/folium#181]
I've just upgraded from folium 0.1.4 to 0.1.5 (https://github.com/python-visualization/folium/issues/172), I think I have a regression. I've attached two pictures, the first is a folium map with a vincent line chart (random data) attached to London, in 0.1.4 the line chart's popup box encompasses the chart, with 0.1.5 it is clipped.

In both cases folium is using vincent 0.4.4. I've switched folium versions and the bug is consistent.

I'm using Linux Mint 17.1 (Ubuntu 14.04) with Python 3.4. The bug manifests in both Firefox and Chrome.

Is there a quick fix I can make to the demo code below? Or is this a bug that needs fixing?

folium 0.1.4 with the line chart:
![vincent_linechart_using_folium014](https://cloud.githubusercontent.com/assets/273210/9277453/105a4a66-42a2-11e5-8fca-9550e1b0dabc.png)

folium 0.1.5 with exactly the same code:
![vincent_linechart_using_folium015](https://cloud.githubusercontent.com/assets/273210/9277449/0c5c495a-42a2-11e5-9a29-acafc4fdf6d2.png)

Sample self-contained code to generate this:
```
import pandas as pd
import numpy as np
import folium
import vincent

# using folium 1.4
# python -m http.server  # must serve up as json, can't use file-open

sales = folium.Map(location=[51.5, 0], zoom_start=7, tiles='stamentoner')


def make_hex_color(mn, mx, value):
    """Make a black->red hex colour"""
    assert mn <= value
    assert value <= mx
    percent = (1/(mx-mn)) * (value-mn)
    red_in_hex_range = int(255 * percent)
    # make a HTML color code e.g. #ff0000
    color = "#{:02x}0000".format(red_in_hex_range)
    return color


# make some random sales data
prices = np.random.uniform(low=100000, high=10000000, size=12).astype(np.int_)
df = pd.DataFrame({'price': prices})

# make a vincent Line from the dataframe
bar = vincent.Line(df['price'], width=200, height=150)
bar.axis_titles(x='Month', y='')
bar_json = bar.to_json()
# export the data to a file as per vincent's requirement
with open('bar.json', 'w') as f:
    f.write(bar_json)

# make a marker that'll host the line chart
sales.circle_marker(location=[51.521282, -0.115279], radius=5000,
                    line_color='#ff0000',
                    fill_color=make_hex_color(0, 1000000, 1000000),
                    popup=(bar, "bar.json"))

sales.create_map(path='sales_map.html')
```

**Comment by ocefpaf** [comment]
This is kind if bug is hard to test since it demands visual inspection!  Thanks for reporting.  I will to my best to fix that for 0.1.6. (Which should be out this weekend.)

**Comment by ocefpaf** [comment]
Jeez.  The `max_width` is limited to the map with and the default map width is now a relative size (100%), so it is passing `100 px` to the popup rendering function!  (Guess who made this mess?  Me!)

A workaround is to specify the map `width` yourself.  And make sure that `width` is more than the vincent plot width.  I am fixing this now...

**Comment by ocefpaf** [comment]
Fixed in #183

**Comment by ianozsvald** [comment]
@ocefpaf Hi Filipe, I agree that this is fixed, many thanks. If a 0.1.6 release were possible, it would be much appreciated (I can link to it from my tutorial).

**Comment by ocefpaf** [comment]
I really want to get a `v0.1.6` out as soon as possible, but we want to make sure it has the new `image_overlay()` method and some fixes for displaying maps in notebooks.  So it may that a while :unamused: 

Stay tuned!
