### ISSUE TITLE
Loading of folium with many markers makes a Django app slow

### ISSUE THREAD

**Issue by mehrdadscomputer** [python-visualization/folium#1814]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
folium_map = folium.Map(location=[64, 3], zoom_start=4)
marker_cluster = MarkerCluster().add_to(folium_map)
  for location in locations:
      folium.Marker(
          location=[location["lati"], location["long"]],
      ).add_to(marker_cluster)
folium_map = folium_map._repr_html_()

```
#### Problem description

When trying to load 10,000 marker points on folium map, the user cpu time is more than 30 seconds. Is there any way to decrease user cpu time? I mean any optimization that we can do on the map or on the markers to make this possible?

**Comment by Conengmo** [comment]
Hi @mehrdadscomputer, that's expected behavior. There are some plugins you can use instead:

MarkerCluster and FastMarkerCluster, see https://python-visualization.github.io/folium/latest/user_guide/plugins/marker_cluster.html
-
