### ISSUE TITLE
Add LeaFlet Control-Credits plugin

### ISSUE THREAD

**Issue by carlosign** [python-visualization/folium#1821]
Hello, i ported the leaflet control credits plugin to folium, i dont know if its worth adding it to folium but it may be helpful for someone. 

The plugin adds an image (credits) that works like a button and displays some text, it works with fullscreen plugin, i think its an alternative to ImagePlugin.
https://github.com/GreenInfo-Network/Leaflet-Control-Credits Original plugin

Ported plugin to folium: 
https://github.com/carlosign/Folium.ControlCredits-Plugin

Thanks to all.

**Comment by Conengmo** [comment]
Hi @carlosign, thanks for sharing! We'll add it to our list of Folium add-ons. I'll leave this ticket open to remind me to do that.

**Comment by Conengmo** [comment]
Just added it to the readme. Again, thanks for sharing!
