### ISSUE TITLE
map fit size of virtual screen of selenium

### ISSUE THREAD

**Issue by dobefore** [python-visualization/folium#1822]
Hi! I want to screenshot the map using selenium with high definition like 4k.Unfortunately my computer is only720p.

I tried to set window size of the selenium driver to 4k,yet the map doesn't fit.Hope to get suggestions from you guys!

![mmexport1698656138306.png](https://github.com/python-visualization/folium/assets/46564102/e07d44f3-bda7-49bc-be8b-fec3605807f5)

**Comment by Conengmo** [comment]
I'm afraid this is more of a Selenium question. The Folium map should stretch to 100 % automatically. I can't really help you further, so I suggest looking into the Selenium documentation. Or try Stackoverflow. Good luck!

**Comment by dobefore** [comment]
Thanks for the reply!
I nearly made it!By setting the window size of selenium to 2K and setting zoom_start=3 ,it fits nearly perfect.
```
options = webdriver.EdgeOptions()
    options.add_argument("--headless")
    driver = webdriver.Edge(options=options)
    # driver.set_window_size(4300,2900)
    driver.set_window_size(2560,1440)
    m = folium.Map(location=(50,5),max_zoom=1,zoom_start=3, control_scale=True,
                    prefer_canvas=True,zoom_control=False,tiles=folium.TileLayer('https://{s}.tile.thunderforest.com/mobile-atlas/{z}/{x}/{y}.png?apikey={apikey}',
                          attr='&copy; <a href="http://www.thunderforest.com/">Thunderforest</a>, &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
                          apikey='pk.eyJ1IjoiZGluZ3diIiwiYSI6ImNsY3doNmluazBmd2Qzb29lbzVrYXltdjYifQ.H8sWvLIDzRD7hbZDYlbUCQ',maxZoom=24,overlay=True))
    # Maybe another column should be added,such as current country
```
![1](https://github.com/python-visualization/folium/assets/46564102/5c6f60e4-ff35-42e0-aeb6-f42f24c6b7f3)

**Comment by Conengmo** [comment]
Thanks for reporting back! Useful for other users. I redacted your API key by the way, better not post these on the internet.

**Comment by dobefore** [comment]
It's kind of you!I will notice it,thanks.
