### ISSUE TITLE
Confine a marker(flag picture) into a specific area(territory)

### ISSUE THREAD

**Issue by dobefore** [python-visualization/folium#1828]
Hi! Is it possible for us to create a custom marker that draws a country flag(or with a flag file) whose size fits perfectly in a country's territory?

**Comment by Conengmo** [comment]
I don’t think Folium has anything to show flag colors as a background in polygons.

I tried a quick search but seems Leaflet doesn’t have it either.

maybe check out this blog post for inspiration: https://dev.to/haideralipunjabi/flag-colours-visualisation-from-geopandas-to-leaflet-and-back-4ohk
