### ISSUE TITLE
Stamen Map Tiles No Longer Work: Migrating to New Hosting Service?

### ISSUE THREAD

**Issue by pdeitel** [python-visualization/folium#1830]
It appears the Stamen map tiles have been migrated to a new service that requires an API key, so none of the Stamen map tiles display in folium anymore. Even maps I saved previously in HTML documents do not render Stamen tiles. 

See https://maps.stamen.com/stadia-partnership/ for info about the migration.

Will you be updating folium so we can continue using Stamen map tiles? Is this something that I should submit to Leaflet.js?

**Comment by Conengmo** [comment]
Unfortunately we can’t provide access to the Stamen tiles anymore. I recommend you choose a new tileset from https://leaflet-extras.github.io/leaflet-providers/preview/

Alternatively, you could make an account with Stadia, get an API key for yourself, and use Folium with a custom url with API key. Folium and Leaflet won’t be providing these; we are open source projects and don’t have funds for that.

**Comment by pdeitel** [comment]
Thanks for the fast response! I did make a Stadia account, so I'll try that.
