### ISSUE TITLE
folium.plugins.MeasureControl   is not working

### ISSUE THREAD

**Issue by AlineGobbi** [python-visualization/folium#1832]
when i copy this code on jupyter, https://python-visualization.github.io/folium/latest/user_guide/plugins/measure_control.html    does not work, i can't make two clicks, and when i do in my project is the same 

my version of folium is 0.14.0
my python version is 3.9.13

**Comment by ocefpaf** [comment]
Can you upgrade to `folium 0.15.0`?  I just tested against it and it seems to be working as expected. I could reproduce the problem with 0.14.0 BTW but it is not worth for us to issue a patch release there just to fix this.

**Comment by AlineGobbi** [comment]
Now it works, thank you very much
