### ISSUE TITLE
There is a roadmap to return coordinates updated from marker

### ISSUE THREAD

**Issue by dmtzs** [python-visualization/folium#1837]
there is an option which is draggable to move the marker but i think is useless if is not possible to return the new coordinates from that marker so there are some plans or something to make available that feature to return the new coordinates? if not then I dont know why is the part of draggable in the options

**Comment by Conengmo** [comment]
Folium has a couple classes that do things with coordinates of markers you add: https://python-visualization.github.io/folium/latest/user_guide/features/click_related_classes.html

The Draw plugin can also be interesting.

if you need more dynamicness, you’ll probably need to make your own server. See https://python-visualization.github.io/folium/latest/advanced_guide/flask.html for a starting point.

If you have ideas for better functionality please try to be constructive. We’re all volunteers here.
