### ISSUE TITLE
Negative values in legend and threshold scale for choropleth

### ISSUE THREAD

**Issue by roosje** [python-visualization/folium#184]
when making a choropleth of increase or decrease of values I would like to be able to use and see the negative values in the legend. The map itself is okay, but the legend can't adjust.

![negative choro](https://cloud.githubusercontent.com/assets/7208589/9288941/82758e4a-435f-11e5-9dcc-c3a0deda55df.png)

**Comment by ocefpaf** [comment]
Hi @roosje, thanks for the bug report.  I am unfamiliar with this part of Folium code, but I am taking a look at it.  If you can provide a [SSCCE](http://sscce.org) it you help!

**Comment by roosje** [comment]
hope this helps, but with this code I didn't even get the red color for negative numbers:

```python
import folium
import pandas as pd
import numpy as np

state_geo = 'data/us-states.json'
state_unemployment = 'data/US_Unemployment_Oct2012.csv'

state_data = pd.read_csv(state_unemployment)
#to create negative numbers
state_data['Unemployment'] = state_data['Unemployment'] - 
                                                pd.Series(np.random.random_integers(12, size=len(state_data)))

map = folium.Map(location=[48, -102], zoom_start=3)
map.geo_json(geo_path=state_geo, data=state_data,
             columns=['State', 'Unemployment'],
             key_on='feature.id',
             fill_color='RdYlGn', 
             fill_opacity=0.7, 
             line_opacity=0.2,
             legend_name='Unemployment Rate (%)')
```

**Comment by ocefpaf** [comment]
Thanks.  I found the culprit and we are trying to create a proper fix.  Keep an eye on #188.

**Comment by roosje** [comment]
Awesome! Thanx and good luck :)

**Comment by ocefpaf** [comment]
@BibMartin I tested this in master and it seems OK.  Closing this, but please re-open if I am mistaken.
