### ISSUE TITLE
change color MarkerCluster

### ISSUE THREAD

**Issue by AlineGobbi** [python-visualization/folium#1847]
can i change the color of the cluster ? default always make green, i want blue 

i do this, but don't change 

MarkerCluster(locations=locations,
              color = "blue",
              popups=popups,
              icons=[folium.Icon(color="lightgreen"), folium.Icon(color="lightgreen")],
              minimun_cluster_size=20, max_cluster_radius=20).add_to(medico)

![Captura de tela 2023-12-14 091236](https://github.com/python-visualization/folium/assets/95905428/f707a4eb-5255-4003-8c3a-24e9293bfc9f)

**Comment by ocefpaf** [comment]
I don't think we implemented easy ways to customize this in folium itself. The leaflet plugin do allow for some customization via CSS. See https://github.com/Leaflet/Leaflet.markercluster?tab=readme-ov-file#customising-the-clustered-markers. However, note that green is the first class, higher aggregation values will be colored from orange to red if I recall correctly. You will probably need to change the color and the classes.

**Comment by Conengmo** [comment]
Here's an example of how to use custom CSS to style the group colors:

```
    marker_cluster = MarkerCluster().add_to(m)
    for k in range(1000):
        marker_cluster.add_child(
            Marker(location=(random.uniform(0, 50), random.uniform(0, 50)))
        )

    Element("""
        <style>
            .marker-cluster-small {
                background-color: rgba(100, 0, 0, 0.6) !important;
            }
            .marker-cluster-small div {
                background-color: rgba(255, 0, 0, 0.6) !important;
            }
            .marker-cluster-medium {
                background-color: rgba(0, 100, 0, 0.6) !important;
            }
            .marker-cluster-medium div {
                background-color: rgba(0, 255, 0, 0.6) !important;
            }
            .marker-cluster-large {
                background-color: rgba(0, 0, 100, 0.6) !important;
            }
            .marker-cluster-large div {
                background-color: rgba(0, 0, 255, 0.6) !important;
            }
        </style>
    """).add_to(m._parent.header)
```

We assume here `m` is a `Map` object.

Note how each group (small, medium and large) has two colors: one for the inner circle and one for the outer circle.

Hope that solves your issue!
