### ISSUE TITLE
Geocoder can be generalized to work with non-Nominatim providers

### ISSUE THREAD

**Issue by prusswan** [python-visualization/folium#1851]
**Is your feature request related to a problem? Please describe.**
The Geocoder plugin for folium is built on top of of the Javascript geocoder (https://github.com/perliedman/leaflet-control-geocoder) but does not expose all functionality to folium users (e.g. it defaults to Nominatim provider with no option to change) 

**Describe the solution you'd like**
Expanding the Geocoder plugin to support all providers listed at: https://github.com/perliedman/leaflet-control-geocoder#leaflet-control-geocoder-- and possibly user-defined providers

**Describe alternatives you've considered**

N/A

**Additional context**

**Implementation**
folium is maintained by volunteers. Can you help make a PR if we want to implement this feature?

Yes. I have some related work done but would need help to make sure the implementation is generalized and fit with folium design.

**Comment by Conengmo** [comment]
Hi Prusswan,

Is this a usecase you need? I'm open to expanding the `Geocoder` class to provide more of the underlying options. I do hope we can do that in a sane and minimal way though, so we don't take on too much extra maintenance load. If you have already related work done, could you show what you have in mind? Just open a PR if you like, I can take a look.

**Comment by prusswan** [comment]
@Conengmo thanks. See #1851, I have tested with 4 providers including Nominatim

**Comment by Conengmo** [comment]
Thanks @prusswan! I took a look, and will continue the discussion here. I'll make a judgement call and say that this is too much custom Javascript code to accept in Folium. Meaning we cannot take on that maintenance burden.

Though it is cool work that you did! I suggest you host it as a Folium plugin yourself, and when you do we can link to it. We have done this with others before, see https://github.com/python-visualization/folium#packages-and-plugins.

Is this acceptable to you? Or do you have other thoughts or ideas? Love to hear them.

**Comment by prusswan** [comment]
@Conengmo I understand your reasoning, but I don't think I would want to maintain a plugin like this when 1) it is effectively a single class, expanded replacement of the "official" Geocoder 2) part of the functionality should have been supported by the Geocoder (as raised in this issue) 3) custom Javascript is unavoidable given the nature of the plugin (to be executed on client-side), and yet folium is designed with enough flexibility (a good thing) to accommodate such changes (I tried something similar with ipyleaflet, but could not see an "easy" way due to its design)

One way to reduce the custom Javascript is to exclude the functionality for user-defined geocoding providers and just allow the option to use non-Nominatim providers (and to make maintenance more manageable, just mention the providers that have been tested specifically in the docs, leaving the rest "open")

**Comment by Conengmo** [comment]
Thanks for your response, that sounds like a very reasonable compromise. Since the custom template is most of the new code, that does reduce the maintenance load significantly. Let's continue with that PR then based on your suggestion. I'll also add some comments there so you can possibly address everything in one go.

**Comment by Conengmo** [comment]
Since https://github.com/python-visualization/folium/pull/1852 was merged I'll close this issue.
