### ISSUE TITLE
Improve the Plugins documentation by including a one-liner for each available plugin

### ISSUE THREAD

**Issue by achieveordie** [python-visualization/folium#1887]
**Is your feature request related to a problem? Please describe.**
Upon visiting the [`user_guide/plugins`](https://python-visualization.github.io/folium/latest/user_guide/plugins.html) page, I found myself with a bunch of hyperlinks to different plugins available within folium. While the name suggests what the plugin does, as a user, I will find an accompanying one-liner summary very useful.

**Describe the solution you'd like**
A table with two columns: `Plugin` and `Description` where the former contains the hyperlinked names and the latter should have a one-liner description.

**Describe alternatives you've considered**
`user_guide/plugins` is kept as it is and [a more verbose] description is added in their respective pages.

**Additional context**
None

**Implementation**
Absolutely

**Comment by Conengmo** [comment]
Great suggestion! PRs are very welcome!

currently we use a generated table of contents as that list. But probably something like you describe is possible as well.
