### ISSUE TITLE
raise Value Error('Custom files must have an attribution') in folium

### ISSUE THREAD

**Issue by kananep** [python-visualization/folium#1900]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behavior is a problem and what is the expected output.]

**Comment by Conengmo** [comment]
Dupe of https://github.com/python-visualization/folium/issues/1900

**Comment by kananep** [comment]
> Dupe of #1900

Alright. Thank you
