### ISSUE TITLE
Add ability to add a dynamic text/title per frame when using TimestampedGeoJson

### ISSUE THREAD

**Issue by Celtics33** [python-visualization/folium#1910]
**Is your feature request related to a problem? Please describe.**
Add ability to add a dynamic text/title per frame when using TimestampedGeoJson such as the date/year

**Describe the solution you'd like**
When playing a visualization using TimestampedGeoJson, the ability to update the text dynamically

**Describe alternatives you've considered**
I havent seen a real alternative

**Additional context**
https://community.plotly.com/t/dynamic-animation-title-annotation/38747

**Implementation**
folium is maintained by volunteers. Can you help make a PR if we want to implement this feature?

**Comment by Conengmo** [comment]
I'm afraid this is a bit too vague to make this into an actual change. Also, `TimestampedGeoJson` is a plugin and enhancing its feature set is out of scope for me as core maintainer. If somebody is interested in working on this, I'm happy to see what is possible. For now I'll close this issue.

**Comment by Celtics33** [comment]
maybe this issue is better off in leaflet then, and work it through javascript
