### ISSUE TITLE
Bootstrap Theme conflict

### ISSUE THREAD

**Issue by amitbend** [python-visualization/folium#192]
Hi,
I'm using a custom bootstrap css theme for all of my project,
and including a folium map in one of my pages.

it cause a conflict, and it shows the bootstrap default theme.

is there a way to remove those line not manually?

**Comment by BibMartin** [comment]
Hi @amitbend ,
can you prodive a sample of code, and show what lines are in conflict, please ?

**Comment by amitbend** [comment]
Sure!

this is what i see in the html file created by folium

```html
<head>
....
   <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
   <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</code>
```

and this the map config and creation
```python
map_1 = folium.Map(location=def_loc, zoom_start=12, tiles='Stamen Toner', width=960, height=500)


map_1.create_map(path=map.html')
```

i'm using django so i included with this  ```{% include 'map.html' %} ``` tag

**Comment by polypmer** [comment]
Hi, I have the same issue with Flask

**Comment by ocefpaf** [comment]
@BibMartin I am clueless when it comes to css and styling. Do you think this is easily fixed?  If not let's tag `v0.2.1` and start addressing this creating a test using @amitbend https://github.com/python-visualization/folium/issues/192#issuecomment-132736473

**Comment by BibMartin** [comment]
I guess this is resolved by `v0.2.0` because you can update yourself the version of bootstrap (or any other folium lib) in doing:

    folium_map = folium.Map()
    folium_figure = m.get_root()
    folium_figure.header._children['bootstrap'] = folium.element.JavascriptLink(
        '{{another url of your choice}}')

Note that I know few about Flask and Django. But if you want to ensure there's no interaction between Javascript inside and outside the map, I would include the map as an iframe. I guess you can use directly :

    <html>
        ... whatever your template ...
        {{ folium_map._repr_html_() }}
    </html>

@amitbend , can you tell me whether this works ; I guess @ocefpaf is in the mood of closing issues :ghost: .

**Comment by ocefpaf** [comment]
> I guess @ocefpaf is in the mood of closing issues :ghost:

At least tagging them :grin:

**Comment by ocefpaf** [comment]
Closing this.  If `v0.2.0` still have that problem please re-open.
