### ISSUE TITLE
Geocoder plugin not working in Google Chrome

### ISSUE THREAD

**Issue by joeyoey17** [python-visualization/folium#1949]
**Describe the bug**
Hello!  Recently I've noted that the Geocoder plugin isn't working in Google Chrome when you use Chrome to open a saved Folium html file.  I've noticed the plugin is working in Microsoft Edge, just not Chrome.  In Google Chrome, the Geocoder search bar appears but anything you search in it will inevitably come up with "Nothing found".  Is this a new bug?

Example of code I'm running to generate an html file that I open in Chrome:

```
from folium.plugins import Geocoder
Geocoder().add_to(m)
m.save ('test.html')
```

**Comment by hansthen** [comment]
I cannot confirm this behavior. I tested this with google-chrome-stable 120.0.6099.109 on Ubuntu 22.04.03 LTS.

**Comment by hansthen** [comment]
@joeyoey17 is this still an issue for you? If so, can you add more information for us so we can try to reproduce the error?

**Comment by hansthen** [comment]
I will close this issue as there is insufficient information to reproduce the error.
