### ISSUE TITLE
Raster/vector image overlay and legend

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#195]
(Summarizing a discussion from #193)

We nee to refactor the `geo_json` (and the legend),  `image_overlay` methods.

~~Possible names: `overlay_raster`, `overlay_vector`, `add_legend`;~~

- [X] "Plugnify" these methods;
- [X] Legend default should be a free scale
- [ ] Legend should have a `quants` with 'auto' or user defined quantiles. (See #255)
- [ ]  See PySAL for many ways to computed this and lets create some examples. (See #255)

**Comment by ocefpaf** [comment]
The these overlay should also have a popup option (see https://github.com/python-visualization/folium/issues/6).

For the GeoJSON case see we need to support external data as popup (see https://github.com/python-visualization/folium/pull/102).

**Comment by koldunovn** [comment]
Are there any plans to actually use data from the GeoJSON file itself (from 'properties'), not only from pandas?

**Comment by ocefpaf** [comment]
Like this: http://nbviewer.ipython.org/github/ocefpaf/folium_notebooks/blob/master/test_geojson_popup.ipynb

**Comment by ocefpaf** [comment]
@koldunovn's https://github.com/python-visualization/folium/issues/195#issuecomment-133105426 deserves another issue, but I think we should avoid adding non-standard ((simple-spec) ) geojson features by default.
