### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Conengmo** [python-visualization/folium#1956]
See https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project on how to do this.

We can use the default template, since I suspect we don't have any special needs on this topic. We can also lift some ideas from Geopandas for example.

**Comment by ocefpaf** [comment]
I like this one and use it in other projects: https://www.contributor-covenant.org/
