### ISSUE TITLE
Using HeatMapWithTime together with TimestampedGeoJson

### ISSUE THREAD

**Issue by WilliamZhao1999Disit** [python-visualization/folium#1966]
Is it possible to use HeatMapWithTime together with TimestampedGeoJson?

For example, when time goes forward, it simultaneously shows markers or polygons with a single time slider.

**Comment by hansthen** [comment]
Not at the moment.

**Comment by Conengmo** [comment]
That's right, plugins in general are standalone and combining them is not supported.
