### ISSUE TITLE
Release v0.17.0

### ISSUE THREAD

**Issue by Conengmo** [python-visualization/folium#1972]
@ocefpaf @hansthen I made a draft v0.17.0 release, could one of you take a look and confirm it's good to go? https://github.com/python-visualization/folium/releases/tag/untagged-e0bf7b3657db6e3b9050

I want to make this release because we've accrued quite some changes 😄  and @merschformann requested it (https://github.com/python-visualization/folium/issues/1946#issuecomment-2168714027)

**Comment by Conengmo** [comment]
I also made a draft v0.8.0 release for Branca: https://github.com/python-visualization/branca/releases/tag/untagged-1d04153af2434a0636f3. Let's release this as well, as it includes two nice improvements.

**Comment by hansthen** [comment]
@conengmo Do you need any special verification before a release? Otherwise, based on the releases it seems good to go.

**Comment by Conengmo** [comment]
Great! No special verification needed, just wanted to have a second pair of eyes on it. I'll go ahead and publish them.
