### ISSUE TITLE
Add zoomSnap parameter

### ISSUE THREAD

**Issue by Chris-airseed** [python-visualization/folium#1986]
I use folium to render maps for automatically generating figures but the lack of zoom granularity makes it difficult to generate nice figures that contain the bounds of the region of interest. 

Add a parameter to folium.Map() to edit zoomSnap value
https://leafletjs.com/reference.html#map-zoomsnap

**Comment by Conengmo** [comment]
The `Map` class allows arbitrary keyword arguments, so you could already use this parameter. For example:

```
Map(location=(0, 0), tiles="openstreetmap", zoom_snap=0.5)
```

I don't think we will add this as a named parameter, so I'll close the ticket.

**Comment by Chris-airseed** [comment]
Thanks Conengmo
