### ISSUE TITLE
Folium decline to import in python

### ISSUE THREAD

**Issue by Dox-dx** [python-visualization/folium#1987]
>>> import folium                                 Traceback (most recent call last):                  File "/root/myenv/lib/python3.11/site-packages/numpy/core/__init__.py", line 23, in <module>          from . import multiarray                        File "/root/myenv/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides                         File "/root/myenv/lib/python3.11/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (    ImportError: libatlas.so.3: cannot enable executable stack as shared object requires: Permission denied
                                                  During handling of the above exception, another exception occurred:                                 
Traceback (most recent call last):                  File "<stdin>", line 1, in <module>
  File "/root/myenv/lib/python3.11/site-packages/folium/__init__.py", line 15, in <module>              from folium.features import (                   File "/root/myenv/lib/python3.11/site-packages/folium/features.py", line 12, in <module>              import numpy as np                              File "/root/myenv/lib/python3.11/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/root/myenv/lib/python3.11/site-packages/numpy/core/__init__.py", line 49, in <module>          raise ImportError(msg)                        ImportError:
                                                  IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!                                                                                    Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.                                                                                          We have compiled some common reasons and troubleshooting tips at:                                                                                         https://numpy.org/devdocs/user/troubleshooting-importerror.html
                                                  Please note and check the following:
                                                    * The Python version is: Python3.11 from "/root/myenv/bin/python"                                   * The NumPy version is: "1.24.4"                
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
                                                  Original error was: libatlas.so.3: cannot enable executable stack as shared object requires: Permission denied
                                                  >>>

**Comment by Conengmo** [comment]
Folium imports Numpy, which failed to load in your case. So this is an issue with your Numoy installation, not Folium. Please read the secondhand of your error message carefully for hints how to resolve this.
