### ISSUE TITLE
Get coordinates from folium.plugins.LocateControl

### ISSUE THREAD

**Issue by allexstorm** [python-visualization/folium#1998]
Hello. I have following code which adds locate me button on map to autozoom to user's device location.

map = folium.Map()
LocateControl(auto_start=True).add_to(map)
map.save("map.html")

Please advice how can I get coordinates of this location? I think there should be something on click locate me button event.
Thanks.

**Comment by hansthen** [comment]
I checked the code of the plugin and the underlying leaflet control. I could not see an easy way to do this using the `click` event. However you could look at the `mouse_position` control. This will show the coordinates of the mouse over the map. You could use it to determine the location of the marker.

**Comment by allexstorm** [comment]
> I checked the code of the plugin and the underlying leaflet control. I could not see an easy way to do this using the `click` event. However you could look at the `mouse_position` control. This will show the coordinates of the mouse over the map. You could use it to determine the location of the marker. 

Hello.
I don't want mouse control for now. I'm making app mainly using on phones and after clicking locate me button and auto zooming to user location I want to set marker to it, so I need coordinates anyway for marker. I thought there should be elegant decision, I don't want to build bicycle.

**Comment by hansthen** [comment]
In general `Folium` is just a thin layer over the underlying `Leaflet` library and plugins. If it cannot be done in the plugin, we will probably not add it. You are probably better off asking your question here: `https://github.com/domoritz/leaflet-locatecontrol`.

**Comment by allexstorm** [comment]
Okay, I'll get info from js and handle it in python folium, I hope it's possible.
