### ISSUE TITLE
Docs are failing b/c altair is not py313 ready yet

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#2016]
xref.: https://github.com/vega/altair/issues/3620

**Comment by Conengmo** [comment]
Weird that the workflow didn't fail on the py313 PR https://github.com/python-visualization/folium/pull/2013...

**Comment by Conengmo** [comment]
I'll build the latest release docs manually, since we now passed that window.

**Comment by Conengmo** [comment]
I tried to make a temporary fix https://github.com/python-visualization/folium/pull/2017

**Comment by Conengmo** [comment]
ooh okay, so we should actually pin to an exact version there, that's more robust!

**Comment by ocefpaf** [comment]
> ooh okay, so we should actually pin to an exact version there, that's more robust!

It should not matter in an ideal world but... Yeah, probably safer b/c we do depend on dozens of libs in our docs and demos.
