### ISSUE TITLE
map.geo_json geo_path parameter does not work on relative paths

### ISSUE THREAD

**Issue by franciscovargas** [python-visualization/folium#204]
Say if I had the following from the cloropleth examples:
```python
import folium
import pandas as pd

state_geo = r'us-states.json'
state_unemployment = r'US_Unemployment_Oct2012.csv'

state_data = pd.read_csv(state_unemployment)

#Let Folium determine the scale
map = folium.Map(location=[48, -102], zoom_start=3)
map.geo_json(geo_path=state_geo, data=state_data,
             columns=['State', 'Unemployment'],
             key_on='feature.id',
             fill_color='YlGn', fill_opacity=0.7, line_opacity=0.2,
             legend_name='Unemployment Rate (%)')
map.create_map(path='us_states.html')
```

it would work fine. But if my state_geo is something like ```r'../data/us-states.json``` it wont work at all nor through any errors only a java script one when you open the html in the browser. This seems to be a bug worth looking in to.

**Comment by ocefpaf** [comment]
Are you serving your HTML and JSON file or just opening the HTML file?  Note that relative paths are tricky and the HTML file must be able to find the JSON file online.

One way around this is to use `geo_str` instead of `geo_path`.  Let me know if that works for you.

(See http://nbviewer.ipython.org/github/ocefpaf/folium_notebooks/blob/master/test_choropleth_geostr.ipynb for an example.)

**Comment by franciscovargas** [comment]
So I just open the json file with open(path, 'r').read() as a string and
pass it as geo_str ? cause it is still failing.

**Comment by franciscovargas** [comment]
SyntaxError: unterminated string literal

**Comment by ocefpaf** [comment]
Can you answer my question above and provide some more information like the version number.

**Comment by franciscovargas** [comment]
I am just opening the html file on the browser using python3.3
folium==0.1.5.

**Comment by ocefpaf** [comment]
Please see: https://github.com/python-visualization/folium/issues/72

PS: Next version of folium will allow for non-served HTML, since people seems to be doing that a lot.
