### ISSUE TITLE
Popup sticky stays True in version>=0.19.0

### ISSUE THREAD

**Issue by Itaxhix** [python-visualization/folium#2047]
Not much to say here, 0.18.0 and 0.17.0 working just fine (for me)

Same thing happens when I jump in between versions in [official user guide](https://python-visualization.github.io/folium/dev/user_guide/ui_elements/popups.html)

Opened HTML in browser [tested in both chrome and firefox on two computers]

Starting to think that this is intended(?)

**Comment by Conengmo** [comment]
Thanks for the bug report @Itaxhix, very useful! We'll get a fix out asap.
