### ISSUE TITLE
Small Output in Ipython Notebook (3.2)

### ISSUE THREAD

**Issue by roblem** [python-visualization/folium#205]
Following the discussion in [Issue 90](https://github.com/python-visualization/folium/issues/90), I have tried running some of the test files from http://nbviewer.ipython.org/github/ocefpaf/folium_notebooks/tree/master/

Running test_chloreopath.ipynb (I had to add the line `mapa.create_map())` leads to this output:
![folium_map_inline](https://cloud.githubusercontent.com/assets/1871086/9630227/e675daa4-5146-11e5-9a18-55b861fbee7b.png)

The small map in the Jupyter Notebook is full interactive: I can zoom and scroll and the chloreopaths are shaded correctly.  It is just too small.

Had to use this to display the map correctly:
```
def inline_map(map):
    """
    Embeds the HTML source of the map directly into the IPython notebook.
    
    This method will not work if the map depends on any files (json data). Also this uses
    the HTML5 srcdoc attribute, which may not be supported in all browsers.
    """
    map._build_map()
    return HTML('<iframe srcdoc="{srcdoc}" style="width: 100%; height: 510px; border: none"></iframe>'.format(srcdoc=map.HTML.replace('"', '&quot;')))

inline_map(mapa)
```
I am running:

/home/username/anaconda/lib/python2.7/site-packages/folium/__init__.pyc
Folium Version 0.1.5
Python Version: Python 2.7.10 |Anaconda 2.3.0 (64-bit)
Ipython Version: IPython 3.2.0

Note: I got the same result using the system python (Python 2.7 Fedora 22) and in Chrome/Firefox, so I don't think this is an Anaconda or Browser problem.

**Comment by BibMartin** [comment]
Hi @roblem . Thanks for this feedback.
You can workaround this in specifying explicitly the width and height you want :

    mapa = folium.Map(location=[48, -102], zoom_start=3,
                  width=800, height=600)

@ocefpaf : It seems this is due to https://github.com/python-visualization/folium/commit/dcaf5752d41ed29c581c3ca6a84817c0a9fc55dc that does not store `width_type` and ` height_type` in the object. Thus, the default arguments `width="100%", height="100%"` are translated into `width="100px", height="100px"` in the iframe rendering.

**Comment by ocefpaf** [comment]
> @ocefpaf : It seems this is due to https://github.com/python-visualization/folium/commit/dcaf5752d41ed29c581c3ca6a84817c0a9fc55dc that does not store `width_type` and ` height_type` in the object. Thus, the default arguments `width="100%", height="100%"` are translated into `width="100px", height="100px"` in the iframe rendering.


I am not sure... This sounds like something on the IPython side (or with `initialize_notebook()`).  The HTML is OK and if you `print(mapa._repr_html_())` you will get:

```html
      html, body {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
      }
```

The new `_hrml_repr_` in `v0.1.6` seem to does the right thing because it bypass the HTML creation and `initialize_notebook()`.  I just need some spare time to get it out.

**Comment by BibMartin** [comment]
@ocefpaf 
I've got a bugfix for this in https://github.com/BibMartin/folium/commit/b25514cf4fa3347eb5674e31e03de1de5e58ee6a ; but I don't know if it is clean to bugfix a release (nor how).

**Comment by ocefpaf** [comment]
You were faster than me.  Indeed the culprit is the old `_repr_html_`.

In `v0.1.6` I used `width: 100%` and `height: 500px` as defaults.  Maybe you could port your fix there.

**Comment by roblem** [comment]
Thanks, adding height and width works for the test_chloreopaths.ipynb workbook.

Tried running `test_popups.ipynb`, and get blank output (of seemingly the correct size) using the height and size method that worked for the chloreopaths.  From the first example (with slight modifications):

![point_problem](https://cloud.githubusercontent.com/assets/1871086/9634887/a60945b2-5161-11e5-8957-66a2bb7e965b.png)

**Comment by BibMartin** [comment]
You shall add `mapa.render_iframe = True` before (or after)  `mapa.create_map()`.
In fact, you're actually playing examples that were designed to illustrate `v0.1.6`. I guess using this branch will help you.

**Comment by roblem** [comment]
Apologies.  Yes, this worked in 0.1.5.

**Comment by ocefpaf** [comment]
I guess this one is fixed.  Closing this.
