### ISSUE TITLE
Heatmap gradient color in folium.plugins.HeatMap is not documented.

### ISSUE THREAD

**Issue by defending1** [python-visualization/folium#2051]
**Describe the bug**

The documentation for [folium.plugins.HeatMap](https://python-visualization.github.io/folium/latest/reference.html#folium.plugins.HeatMap) mentions that default gradient is None, but I found that Folium seems using the standard gradient color from leaflet, which from the source code is defined as (see leaflet_heat.min.js, or the dependency simpleheat.js):
```js
defaultGradient:{.4:"blue",.6:"cyan",.7:"lime",.8:"yellow",1:"red"}
```
To me is also not clear from the js code which colors the gradient uses before 0.4. I tried to understand it looking at [simpleheat.js](https://github.com/mourner/simpleheat/blob/gh-pages/simpleheat.js) ```function (grad)```, since the minified version should come from here. One comment in this function says "create a 256x1 gradient that we'll use to turn a grayscale heatmap into a colored one". So should I assume that the gradient in 0 starts from black?

**Additional context**

Like user from issue #1579, I was trying to replicate the default gradient to build a colormap for the heatmap plot, and it was not obvious to figure out that the gradient color used could be defined in the leaflet.js file.

**Possible solutions**

Passing defaultGradient as object for folium.plugins.HeatMap, even if it will do nothing because the default is still defined in the leaflet.js code, it could be useful for future users.

**Comment by Conengmo** [comment]
Thanks for reporting this missing information! I understand you would like to be able to know the default gradient without having to dive into the underlying Javascript code.

The simplest thing would be to just add that default gradient to the docstring. We already have an example there, we can replace it with the default gradient. 

I wouldn't want to do it as a default argument to the class, because mutable types are not recommended as default arguments.

**Comment by Conengmo** [comment]
@defending1 maybe you can check out https://github.com/python-visualization/folium/pull/2052/files see if this addresses your issue?

**Comment by defending1** [comment]
Yes good idea. This solves, thanks.

**Comment by Conengmo** [comment]
Great, thanks!
