### ISSUE TITLE
Opacity Accumulated with TimestampedGeoJson

### ISSUE THREAD

**Issue by ghojez** [python-visualization/folium#2059]
Hi,

just want to ask if this is actually the expected output with TimestampedGeoJson. The `fillopacity` feature accumulates over time instead of _refreshing_ or _updating_ the fillOpacity to correspond with the `local_date_time`? I attached a picture of comparison of `fillOpacity` in a specific polygon between dates. It's clear that TimestampedGeoJson _accumulates_ the `fillOpacity` feature so it got darker over time.

```
    feature = {
        "type": "Feature",
        "geometry": mapping(r["geometry"]),
        "properties": {
            "time": r["local_date_time"].isoformat(),
            "style": {
                "fillColor": colormap(r["trx"]),
                "color": "blue",
                "weight": 0.8,
                "fillOpacity": r['opacity'],
```

Is that a known limitation or is there anything I could try to prevent the `fillOpacity` from accumulating?

Thank you

![TimestampedGeoJson](https://github.com/user-attachments/assets/1826c08b-6807-4cce-a1a1-f0d493e27028)

**Comment by hansthen** [comment]
I am not sure what you mean. Can you give a more complete code example?

**Comment by ghojez** [comment]
Hi, this is the example:

```
dx = {
    "local_date_time": ["2024-12-01 10:00", "2024-12-02 10:00"],
    "city": ["Jakarta", "Jakarta"],
    "transaction": [150, 80],
    "rate": [32, 39],
    "geometry": [
        Polygon([(106.8, -6.2), (106.85, -6.2), (106.85, -6.25), (106.8, -6.25), (106.8, -6.2)]),
        Polygon([(106.8, -6.2), (106.85, -6.2), (106.85, -6.25), (106.8, -6.25), (106.8, -6.2)]),
    ],
}

df = pd.DataFrame(dx)
df['local_date_time'] = pd.to_datetime(df['local_date_time'])
df = gpd.GeoDataFrame(df, geometry='geometry')


df['opacity'] = (df["transaction"] - df['transaction'].min()) / (df['transaction'].max() - df['transaction'].min()) * 0.5 + 0.1
colormap = branca.colormap.LinearColormap(
    colors=['blue','blue'],
    vmin=df['rate'].min(),
    vmax=df['rate'].max(),
    caption='Rate Scale'
)

base_template = []
for _, r in df.iterrows():

    feature = {
        "type": "Feature",
        "geometry": mapping(r["geometry"]),
        "properties": {
            "time": r["local_date_time"].isoformat(),
            "tooltip": f"Total Transaction: {r['transaction']}<br>Polygon: {r['geometry']}",
            "style": {
                "fillColor": colormap(r["rate"]),
                "color": "blue",
                "weight": 0.8,
                "fillOpacity": r['opacity'],  # Set opacity based on the calculated value
            },
        },
    }
    base_template.append(feature)

geojson = {
    "type": "FeatureCollection",
    "features": base_template}

# Initialize the map
m = folium.Map(location=[0, 0], zoom_start=10, tiles="CartoDB positron")

# Add the time slider
TimestampedGeoJson(
    geojson,
    #transition_time=500,  # Milliseconds between frames
    add_last_point=False,
    period='P1D',
    loop=False,
).add_to(m)

colormap.add_to(m)
m
```

for the sake of clarity (reproduce the issue), color scale between `df['rate'].min()` and `df['rate'].max()` is blue

**Comment by hansthen** [comment]
I see the issue. The `TimestampedGeoJson` plugin has a `duration` parameter which determines how long a feature will be displayed on the map. If you keep the default each feature will be displayed until the end of times. You could experiment with that. If you have features that have very strict begin and end times, you could also have a look at the `Timeline` plugin, which also provides a GeoJson with time feature, but has specific `start` and `end` times for each feature.

**Comment by ghojez** [comment]
> I see the issue. The `TimestampedGeoJson` plugin has a `duration` parameter which determines how long a feature will be displayed on the map. If you keep the default each feature will be displayed until the end of times. You could experiment with that. If you have features that have very strict begin and end times, you could also have a look at the `Timeline` plugin, which also provides a GeoJson with time feature, but has specific `start` and `end` times for each feature.

ah so that's what duration do. Thank you so much Sir, it's really spot on. Now it's working as expected after I added duration

```
TimestampedGeoJson(
    geojson,
    transition_time=500,  # Milliseconds between frames
    add_last_point=False,
    period='P7D',
    duration='PT1H',
    loop=True,
).add_to(m)
```
