### ISSUE TITLE
Retina Maps

### ISSUE THREAD

**Issue by francisbautista** [python-visualization/folium#206]
Will there be plans for supporting Retina OSM maps for Folium? I'm having meter-pixel issues with screens that are Retina and non-retina.

**Comment by ocefpaf** [comment]
Never thought about that but it shouldn't be hard to implement it for the tiles.  I will leave [this](http://leafletjs.com/reference.html#tilelayer-detectretina) for reference.

**Comment by BibMartin** [comment]
See #222

**Comment by themiurgo** [comment]
Can this be closed?

**Comment by BibMartin** [comment]
Sure ; it's solved by #222
