### ISSUE TITLE
How to make interactive map with time factor

### ISSUE THREAD

**Issue by hunan0121** [python-visualization/folium#208]
Hi guys, I like using folium for visualising data on maps in ipython notebook. Just wonder how can I make an interactive map by including a time slider bar to display different sets of data on the map corresponding to time change? Thanks for advising.

**Comment by BibMartin** [comment]
Hi @hunan0121 
This is something we are working on today.
There's a first possibility using today's `master` ; you can look at <a href="https://github.com/python-visualization/folium/blob/master/folium/plugins/timestamped_geo_json.py">this</a> and use it in taking inspiration from <a href="https://github.com/python-visualization/folium/blob/master/examples/plugins_examples.ipynb">there</a>.
But it's not stable, you may need to hack a bit, and we are going to break everything in the coming weeks.

I let this issue open until we have a better answer.

**Comment by hunan0121** [comment]
@BibMartin Thanks for your advise and prompt reply. Look forward to more awesome features coming with the next version of Folium :+1: Thank you so much.

**Comment by BibMartin** [comment]
Your welcome @hunan0121. I ping you when this is stabilized.

**Comment by ocefpaf** [comment]
Hi @hunan0121 I am closing this because this is a feature that is currently under development.

Stay tuned for the next version of folium and please re-open this issue if necessary.
