### ISSUE TITLE
Stamen tiles not working (looks like URL of tiles changed)

### ISSUE THREAD

**Issue by SamLau95** [python-visualization/folium#209]
It appears that the URLs for Stamen tiles has changed.

Running
```python
import folium
map_osm = folium.Map(location=[45.5236, -122.6750], tiles='Stamen Toner')
map_osm.create_map(path='osm.html')
```

And then opening the `osm.html` file in the browser shows these errors in the Javascript console:

```
Failed to load resource: https://stamen-tiles-c.a.ssl.fastly.net/toner/10/161/366.jpg
the server responded with a status of 404 (Not Found)
```

Opening https://stamen-tiles-c.a.ssl.fastly.net/toner/10/161/366.jpg in the browser shows that the link is broken. However, https://stamen-tiles-c.a.ssl.fastly.net/toner/#10/161/366.jpg appears to work. Perhaps the Stamen server changed the format of its URLs.

**Comment by ocefpaf** [comment]
I believe this is already fixed in #199.

Note to self: I need to put `v0.1.6` out as soon as possible!
