### ISSUE TITLE
Heatmaps on Folium

### ISSUE THREAD

**Issue by francisbautista** [python-visualization/folium#213]
Is there a way to use heatmaps on folium w/o going back to Leaflet.js and its heatmap plugin set?

**Comment by ocefpaf** [comment]
@francisbautista that would be a nice addition.  Folium right now is low in manpower.  PRs are welcome :wink:

**Comment by ocefpaf** [comment]
Hi @francisbautista,

@BibMartin did an awesome job implementing a plugin system for folium.  He just used that system to add the `leaflet-heat.js`.  Feedback is appreciated!  (And if you produce a cool map consider sending it to https://github.com/ocefpaf/folium_notebooks.  I am putting a gallery together.)

(See #224)
