### ISSUE TITLE
How can I add permanent text on a folium map?

### ISSUE THREAD

**Issue by raidoz** [python-visualization/folium#214]
I would like to permanently show some text(IDs) on or near circle markers? How can I do this?

**Comment by BibMartin** [comment]
As suggested in #210, it may be possible to implement something looking like http://leaflet.github.io/Leaflet.label/

It's not available yet, but would it fit your need ?

**Comment by raidoz** [comment]
This could work. Ideally I would still like to be able to get a separate pop-up with additional info. It's just that I need a way to identify the markers without clicking them.

**Comment by themiurgo** [comment]
Closing this, duplicate of #210.

**Comment by guyarad** [comment]
#340
