### ISSUE TITLE
Markers not showing up when I use clustered_marker = True

### ISSUE THREAD

**Issue by ginobili0** [python-visualization/folium#215]
I created a notebook to analyse the NYC Motor Vehicle Collision data. You can see the notebook here: https://github.com/ginobili0/NYC_Collisions/blob/master/NYC_Collisions.ipynb. As demonstrated in the notebook, when I set clustered_marker = True, I just get a blank map. Without setting clustered_marker, I get markers, but I can't seem to get more than 17. What's going wrong?

**Comment by andrewgiessel** [comment]
Quick question without having looked at the ipynb carefully:  have any NaNs
in your data (in particular, in lon/lat)? Try dropping those first.

ag

**Comment by ginobili0** [comment]
Ah yes. Removing NaNs worked. Silly me.
