### ISSUE TITLE
Stamen Toner doesn't works

### ISSUE THREAD

**Issue by marcobra** [python-visualization/folium#216]
The Stamen Toner doesn't works in sample:

http://bl.ocks.org/wrobstory/5609747

and in folium generated code.

Working Leaftlet providers:
https://leaflet-extras.github.io/leaflet-providers/preview/

Thanks
Marco

**Comment by ocefpaf** [comment]
Hi @marcobra, this issue is fixed in the dev version. (See https://github.com/python-visualization/folium/pull/199/files.)

I am in the process of issuing a new release.
