### ISSUE TITLE
key_on='features.properties.key' seems to be broken

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#223]
When passing the `key_on=` option the docs mentioned that `key_on='features.properties.key'` is valid syntax, but that is not working.

**Comment by BibMartin** [comment]
When using the `master`, it seems to work.
Isn't this a typo ; need `featue.properties.key` instead of `features.properties.key` ?

![capture du 2015-11-01 19 48 16](https://cloud.githubusercontent.com/assets/4586863/10872871/8b7a00e0-810b-11e5-92a1-2d29ccc1100d.png)

**Comment by ocefpaf** [comment]
It **is** a typo in the docs!

http://folium.readthedocs.org/en/latest/#binding-data

Argh, what a difference an `s` makes when copying and pasting!

Let's leave this issue open and I will fix the docs.
