### ISSUE TITLE
Improve plugin tests

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#225]
We can do a better in doing the same thing as `test_folium.py`: compare the output of `.render()` with code generated from a validation template.

**Comment by BibMartin** [comment]
Just a question of organisation : where should be stored each plugin components (code, test code, template, eventual data files) ?

An approach would be to host everything in the plugin folder with something like this:

    folium/plugins
        ./image_overlay
            ./__init__.py
            ./somecode.py
            ./test.py
            ./image_overlay.template
            ./some_data.json

then we would just have to import all the tests in `folium/tests/test_plugins.py`

**Comment by ocefpaf** [comment]
I am not OK with that pattern.  Mainly because it is uncommon and not because I see a problem right away.  I'd rather have the code for the tests inside a `test/plugin` folder.  We can do a file for each plugin.

**Comment by BibMartin** [comment]
ok. To sum up :

* The code is in `folium/plugins/image_overlay.py` (or a submodule)
* The test code is in `tests/plugins/test_image_overlay.py`
* The test data are in `tests/plugins`
* The test templates are inline, or in `tests/plugins`

**Comment by ocefpaf** [comment]
I like that.  We can put the test data and templates in `tests/plugins/{data,templates}` if you think it will be better organized that way.  Ideally we could try to make the data and template light enough to be inside the `test_{plugin}.py` file to make each test file self-contained.

**Comment by BibMartin** [comment]
pre {display: block;font-family: Helvetica Neue, Helvetica, Arial, sans-serif;white-space: pre-wrap;margin: 1em 0;}> we could try to make the data and template light enough to be inside thetest_{plugin}.py file to make each test file self-contained.

:+1:

Envoyé depuis AndroidFilipe --- [Marketing Mail] Re: [folium] Improve plugin tests (#225) --- De :"Filipe" <notifications@github.com>A :"python-visualization/folium" <folium@noreply.github.com>Cc :"Martin Journois" <martin.journois@fr.michelin-solutions.com>Date :mer., 16 déc. 2015 14:55Objet :[Marketing Mail] Re: [folium] Improve plugin tests (#225)I like that.  We can put the test data and templates in tests/plugins/{data,templates} if you think it will be better organized that way.  Ideally we could try to make the data and template light enough to be inside the test_{plugin}.py file to make each test file self-contained.

**Comment by BibMartin** [comment]
See #304

**Comment by BibMartin** [comment]
@ocefpaf
Can we close this ?

**Comment by ocefpaf** [comment]
Yep.
