### ISSUE TITLE
Create markers with custom icons

### ISSUE THREAD

**Issue by foodstamps** [python-visualization/folium#228]
The one thing barring me from using Folium is the lack of support for markers using custom icons, through the use of user-provided .png files. This functionality is offered with Leaflet - http://leafletjs.com/examples/custom-icons.html

According to the text, "Marker icons in Leaflet are defined by L.Icon objects, which are passed as an option when creating markers."

For me personally, the option of including a shadow icon, as offered by Leaflet, is unnecessary, but I don't want to speak on behalf of everyone who desires this functionality.

I don't think I have the coding chops to actually add this functionality on my own. I'm eager to learn, but for the time being, if someone's willing to take this on, it would be enormously appreciated.

**Comment by ocefpaf** [comment]
That is an important addition and, as part of the folium team, I am ashamed to point you to [this hack](https://github.com/ocefpaf/secoora_assets_map/blob/gh-pages/assets_map.ipynb)  I used to produce [this map](http://ocefpaf.github.io/secoora_assets_map/secoora_assets.html).

**Comment by BibMartin** [comment]
See #230

**Comment by foodstamps** [comment]
Excellent! Thank you both! I'm excited to try this one out.

**Comment by themiurgo** [comment]
This looks solved, closing.

**Comment by ocefpaf** [comment]
Yep.  We forgot to close it.  Thanks @themiurgo!
