### ISSUE TITLE
Jupyter/IPython _html_repr_ iframe is not re-sizing to map size

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#229]
See http://nbviewer.ipython.org/gist/ocefpaf/24711838a07b4bad2f9d

**Comment by ocefpaf** [comment]
@BibMartin the map is properly re-sized, but the iframe is not.

Is this a Jupyter thing?  Should I tag `v0.2.1`?

**Comment by BibMartin** [comment]
This is because you change the `Map`'s size, instead of changing the `Figure` size.

Try

    f = folium.element.Figure(width=width, height=height)
    folium.Map(location=[lat, lon], tiles="OpenStreetMap",
               zoom_start=zoom_start).add_to(f)
    f

I guess this needs to be changed, but my idea when coding this was to separate the `Map` object and the `Figure`, so that you can put several maps in the same Figure, or a Map and one/several `Div`...

**Comment by ocefpaf** [comment]
Now I realize where the width and height is coming from in the iframe.

I am on the fence.  On one side I think most people will only create maps and want to display them in the notebook.  However, the current implementation is more generic and [very powerful](http://nbviewer.ipython.org/github/bibmartin/folium/blob/crossfilter/examples/Crossfilter%20example.ipynb).

Not sure if we should leave this as is or if we should try to be smart about this and use the Map width and height for the figure when the user does not specify them.

**Comment by BibMartin** [comment]
Yes, I'd be in favor of keeping things *structured* ; but provided 

> most people will only create maps and want to display them in the notebook

, maybe we can do an exception for this and add a `figsize` parameter in the `Map` object.
(and a `set_figsize` method)

**Comment by ocefpaf** [comment]
> maybe we can do an exception for this and add a figsize parameter in the Map object.
(and a set_figsize method)

Nope.  Let's avoid adding complexity.  People who wants to show different sized maps should know what they are doing and dive in the `Figure`.

Let's keep it as is.

**Comment by ocefpaf** [comment]
Thanks for the clarifications @BibMartin!

**Comment by BibMartin** [comment]
I think we may keep in mind this issue's nb ; we'll have to link to it from duplicates.

**Comment by ocefpaf** [comment]
This notebook, http://nbviewer.ipython.org/gist/ocefpaf/99a390dbe5a1cb8cf4a6, describes the current state of the Figure/Map size.  We can address some of those points later in `v0.2.1`.

**Comment by ocefpaf** [comment]
For future reference here is how to get the previous behavior:

```python
width, height = 480, 350

fig = folium.element.Figure(width=width, height=height)

m = folium.Map(location=[lat, lon], tiles="OpenStreetMap",
               width='100%', height='100%', zoom_start=zoom_start)

fig.add_children(m)
fig
```
