### ISSUE TITLE
Generic GeoJsonStyle

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#231]
@BibMartin correct me if I am wrong, but `GeoJsonStyle` is only for color scale, right?

PS: I am creating more examples in an effort to accumulate material to write the new version of the docs.

**Comment by BibMartin** [comment]
Yes. I've tried to make the object structure look like Leaflet's.

**Comment by ocefpaf** [comment]
I get that.  Maybe renaming is not the right title for this issue.  But what if someone wants to style something else than a color scale?  Maybe that functionality is already in there and I am missing the point here...

Right now `color_domain` and `color_code` are mandatory and the `color_range` is created from those two.  That triggers the creation of a `d3.scale.threshold`.

Later on, in the template, we have `setStyle` with the other styling options that people might want to use in Polygons, etc.

So I guess that what I mean is. How can I style, for example,  a polygon?

```python
GeoJson(polygon.geojson).add_children(geo_json_style)
```

Where the `geo_json_style` would be line width, color, etc.  With some defaults taken from #120.

**Comment by ocefpaf** [comment]
@BibMartin I renamed this issue to `Generic GeoJsonStyle` to reflect the problem better.

**Comment by ocefpaf** [comment]
See #266

**Comment by BibMartin** [comment]
@ocefpaf 
Can we close this, as #266 is merged ?

**Comment by ocefpaf** [comment]
Yep!  #266 was an issue killer :stuck_out_tongue_winking_eye:
