### ISSUE TITLE
Create multipoint feature

### ISSUE THREAD

**Issue by jelmelk** [python-visualization/folium#238]
Given a dataframe with multiple lat/long coordinates, there doesn't seem to be a way to plot them as multiple markers. Does the data need to be entered differently?

```csv
               X,Y
     -122.425892,37.774599
     -122.425892,37.774599
     -122.424363,37.800414
     -122.426995,37.800873
     -122.438738,37.771541
     -122.403252,37.713431
     -122.423327,37.725138
     -122.371274,37.727564
     -122.508194,37.776601
     -122.419088,37.807802
```

The following code provides blank html.

```python
    import folium
    import pandas as pd
    import numpy as np
    
    df = pd.read_csv('train.csv')
    
    map_osm = folium.Map(location=[37.7622, -122.4356], zoom_start=13)
    map_osm.geo_json(data=tr_df, columns=['X','Y'], fill_color='BuGn', key_on='feature.multipoint')
    map_osm.create_map(path='osm.html')
```

**Comment by ocefpaf** [comment]
Hi @jelmelk,

I am not sure what `tr_df`is, but the `geo_json` method expects a [GeoJSON](http://geojson.org/geojson-spec.html) file or string.

Note that in your example we cannot see what you are trying to do with the points in the dataframe (`df`).

But you can plot the `df` using markers (for example: `simple_marker([45.3288, -121.6625])`). Our docs are a little bit outdated but they have a few more examples that can help you.

http://folium.readthedocs.org/en/latest/

I also keep a repository with a "gallery" of [notebook](https://github.com/ocefpaf/folium_notebooks) that might help get you started.

**Comment by BibMartin** [comment]
@jelmelk 
You can do

    geojson = {
                "type": "Feature",
                "geometry": {
                    "type": "MultiPoint",
                    "coordinates": df[['lat','lon']].values.tolist(),
                    },
                "properties": {"prop0": "value0"}
                }
    m = folium.Map(...)
    m.add_children(folium.features.GeoJson(geojson))

@ocefpaf 
The doc example is supposed to be http://nbviewer.ipython.org/github/python-visualization/folium/blob/master/examples/Features.ipynb but it's not up to date with today's API.

**Comment by ocefpaf** [comment]
I just did not want to confuse @jelmelk with the latest (and unreleased) folium.  But I guess that is just an incentive to get that out of the door as soon as possible :wink:

**Comment by jelmelk** [comment]
@ocefpaf `tr_df` is the dataframe for the `X,Y` data, sorry if that wasn't clear. I realized it had to be in GeoJSON, but wasn't sure if the conversion happens internally or must be specificed. The confusion for me was this part of the doc for  the`geo_json` function:

        If data is passed as a Pandas dataframe, the "columns" and "key-on"
        keywords must be included, the first to indicate which DataFrame
        columns to use, the second to indicate the layer in the GeoJSON
        on which to key the data. The 'columns' keyword does not need to be
        passed for a Pandas series.

@BibMartin, you mean those examples are in upcoming releases, correct?

Thank you both for the set of examples, the progress is very exciting.

**Comment by BibMartin** [comment]
@ocefpaf 
> I just did not want to confuse @jelmelk with the latest (and unreleased) folium. But I guess that is just an incentive to get that out of the door as soon as possible

You're true ; sorry. It's rather an incentive to use the `master` and contribute :wink: 

@jelmelk 
> you mean those examples are in upcoming releases, correct?

This very example runs with the `master`. But if you're using `v0.1.5` or upcoming `v0.1.6` , I guess you just need to replace the last line by

    m.geojson(geojson)

**Comment by ocefpaf** [comment]
@jelmelk The old (current!) `geo_json` is a convenience method that plots geojson with some extra kwargs to help create choropleths.  The "data" that is mentioned in the docs is the data used for choropleth only.

If you want to plot points in the current released version of folium you can use markers (like `simple_marker`) or create a GeoJSON string on the fly like @BibMartin showed you.

**Comment by jelmelk** [comment]
@ocefpaf, thank you for the clarification on that.

@BibMartin, did you mean `m.geo_json(geojson) `? Because `geojson` isn't available in `v0.1.5`. I tried the following example, but `osm.html` file is still blank.

    import folium

    geojson = {
        "type": "Feature",
        "geometry": {
            "type": "MultiPoint",
            "coordinates": [[37.7745985956747, -122.425891675136], [37.7745985956747, -122.425891675136]],
        },
        "properties": {"prop0": "value0"}
    }
    
    map_osm.geo_json(geojson)
    map_osm.create_map(path='osm.html')

**Comment by BibMartin** [comment]
I have gone too fast ; and did not try my hint. Here is something working with `v0.1.5`.

    import folium
    import json

    geojson = {
        "type": "Feature",
        "geometry": {
            "type": "MultiPoint",
            "coordinates": [[-122., 37.], [-122., 38.]],
        },
        "properties": {"prop0": "value0"}
    }

    map_osm = folium.Map(location=[37.5,-122], zoom_start=6)
    map_osm.geo_json(geo_str=json.dumps(geojson))

    map_osm.create_map(path='/tmp/map.html')

Beware that geo_json coordinates are `lonlat` while they are `latlon` in `folium.Map`

**Comment by ocefpaf** [comment]
> Beware that geo_json coordinates are `lonlat` while they are `latlon` in `folium.Map`

[:unamused: ] `* np.exp(np.inf)`

**Comment by jelmelk** [comment]
Great, thank you both.
