### ISSUE TITLE
Autobounds not working

### ISSUE THREAD

**Issue by themiurgo** [python-visualization/folium#244]
Since 95a8c0f281f2e28c135288ca0a8d5c48eb9819c0 automatic bounds are not working (the method `_auto_bounds` was commented out and never reintroduced).

**Comment by ocefpaf** [comment]
Reviewer :gun: 

Oh no wait!! I was the Reviewer!!!

**Comment by themiurgo** [comment]
:v:

**Comment by themiurgo** [comment]
@BibMartin Any particilar reason for this or you just forgot? :)

**Comment by BibMartin** [comment]
No reason for this ; I hope there's no other *collateral effect* of the refactoring.
@themiurgo thanks for having noticed this.

**Comment by themiurgo** [comment]
It's alright, if not I'll just reimplement it or fix it. Just wondering if I had to be aware of any particular reason why this might not work. :smile:

**Comment by ocefpaf** [comment]
See #305
