### ISSUE TITLE
Bringing folium closer to Leaflet

### ISSUE THREAD

**Issue by themiurgo** [python-visualization/folium#245]
After the great refactoring work done by @BibMartin and, we finally have a coherent way to add new features to the map.

I understand at the moment the suggested way to add features to the map, as the documentation suggests, is the following:

```Python
map.add_children(marker),
```

I propose that we change that to:

```Python
marker.add_to(map),
```

to mirror closely Leaflet API (http://leafletjs.com/reference.html#marker).

Also, we should probably change the name from `add_children` to `add_child`, as the method accepts a single element, and not a list of elements. Hope it's not too late for that, before 0.2.0 final comes out. :smile:

**Comment by BibMartin** [comment]
> Also, we should probably change the name from add_children to add_child, as the method accepts a single element, and not a list of elements.

Obviously yes. It's originally a mistake in my imperfect English.

> I propose that we change that to: `marker.add_to(map),`

I had originally created a method like 

    def add_to(self, element):
        element.add_children(self)

(see discussion with @andrewgiessel in https://github.com/python-visualization/folium/pull/203#issuecomment-135877399)

I would at least add the `add_to` method ; and eventually change `add_children` for it accepts lists of elements. In other words, the API would be :

    map.add_children([marker1, marker2])

equivalent to

    marker1.add_to(map)
    marker2.add_to(map)

**Comment by themiurgo** [comment]
> I had originally created a method like

Yes @BibMartin, the method is already there and works perfecty. You were foreseeing this. :+1: 

I'm just proposing that we change the current `add_children` to `add_child` and that in the deprecation message we advise using the `add_to`, to mirror Leaflet.

**Comment by BibMartin** [comment]
> We can also have a real add_children that adds multiple features at once.

:+1: We just need to revert the mechanic, so that `add_children` calls `add_to` ; then a small `for` loop. I try to do in ASAP.

Question : provided we're only on `master`, do we need to raise a deprecation warning ?

**Comment by themiurgo** [comment]
> Question : provided we're only on master, do we need to raise a deprecation warning ?

I don't think we need a deprecation warning advising not to use `add_children`. I think we need to change the deprecation warnings that are already there and have them advise `add_to`. I can take care of it in the PR #246 .

**Comment by ocefpaf** [comment]
> Question : provided we're only on master, do we need to raise a deprecation warning ?

I agree with @themiurgo.  No need for a new deprecation warning.  Actually, this is why I am not in a hurry for `v0.2.0`. (Which we my be bold and start calling `v1.0.0` at some point :wink:)

We will have more discussions like this and we need more opinions on the table.
Thanks @themiurgo for bringing that up!

**Comment by ocefpaf** [comment]
It looks like this one was taken care of, right?

**Comment by ocefpaf** [comment]
@BibMartin  and @themiurgo can we close this one?

**Comment by themiurgo** [comment]
I don't think so, the codebase is still full of `add_children` rather than `add_child`.

**Comment by ocefpaf** [comment]
This was partially addressed in https://github.com/BibMartin/folium/commit/2d6590dbe9b30b0fcfb256db1ccb16684152db54.

(We could use a hand to get `v0.2.0` out of the door.)

**Comment by themiurgo** [comment]
(would love to help, but busy "as if there's no tomorrow" until February, thesis submission time!)

**Comment by ocefpaf** [comment]
> thesis submission time!

:scream: I am thankful that I am out of the university door :wink:

Good luck with your thesis!

**Comment by themiurgo** [comment]
Thanks, can't wait to be done! :wink:

**Comment by BibMartin** [comment]
> I don't think so, the codebase is still full of add_children rather than add_child.

:+1:

> :scream: I am thankful that I am out of the university door :wink:
Good luck with your thesis!

:+1:

**Comment by ocefpaf** [comment]
Argh.  This one fell under the cracks.  I guess we should solve this before the release.

@BibMartin What do you think?  I can assign myself and solve this first tomorrow.

**Comment by BibMartin** [comment]
I have done a part of the job in creating `add_child` beside `add_children`.
But it's still needed to replace all calls to `add_children` by `add_child`.

**Comment by ocefpaf** [comment]
> I have done a part of the job in creating add_child beside add_children.

Saw that, but do we need both?  I guess that, since we never released this API (yet), we can just change it now. Or am I missing something?

**Comment by BibMartin** [comment]
This will be unpleasant for those who are working on master for months (me).
But maybe it's the best solution. This `add_children` method is nonesense.

**Comment by ocefpaf** [comment]
> This will be unpleasant for those who are working on master for months (me).

Me too :unamused:, but I was going to bite the bullet.  I guess that we (I) delayed `v0.2.0` so much that keeping both and deprecating is probably the way to go...

**Comment by ocefpaf** [comment]
With that said I will make the release and add this goal to `v0.3.0`.

**Comment by ocefpaf** [comment]
I think we replaced all the calls. Closing this but feel free to re-open if I missed anything.
