### ISSUE TITLE
Masking map areas without overlay

### ISSUE THREAD

**Issue by methodds** [python-visualization/folium#249]
The possibility to use JSON data for map overlays is easily the best feature of folium. For many visualizations, non-overlay parts of a map are not important and disturb viewers from focusing on the main information.  Masking map areas (e.g. to white, black, or transparent) without overlay would be a very nice addition to folium, so that in combination with #210, one can create maps like this: 

![alt image](http://ichef.bbci.co.uk/news/660/cpsprodpb/F429/production/_85450526_asylum_seekers_germany_624v.png)

**Comment by themiurgo** [comment]
Great suggestion! :+1: 

Would you like to contribute this enhancement by writing it yourself? It would mean a lot to the rest of the folium users. :smile:

**Comment by methodds** [comment]
I would love to contribute to folium but unfortunately have no free time left in 2015 :disappointed: . If this enhancement and #210 won't be implemented by the beginning of the next year, I will try to write them.

**Comment by ocefpaf** [comment]
It turns out that implement this was relatively easy.  See #330

http://nbviewer.ipython.org/gist/ocefpaf/a502162cf7a472577033

**Comment by ocefpaf** [comment]
@methodds I am guessing #210 is also a low hanging fruit.  Want to try :wink:

**Comment by nurmians** [comment]
nbviewer links are broken, I'm looking for a way to mask map areas without overlay?

**Comment by Conengmo** [comment]
The suggested approach here is to not include any tileset, only your data visualization.

```
m = Map(tiles=None)
# add whatever Choropleth or something you want to add
Choropleth(...).add_to(m)
```
