### ISSUE TITLE
Popups that contain a quote don't work

### ISSUE THREAD

**Issue by themiurgo** [python-visualization/folium#252]
To reproduce:

```Python
mmap = Map()
marker = Marker((40,40))
Popup("Let's try").add_to(marker)
marker.add_to(mmap)
```

**Comment by themiurgo** [comment]
Also `\r` within the text breaks the output. We should strengthen the tests and find out if other symbols break Popups.

**Comment by ocefpaf** [comment]
> We should strengthen the tests and find out if other symbols break Popups.

Indeed.  Our tests are our Achilles heel at the moment.  I am labeling issues like with a "Add Test" label so we close this only once we have it fixed and with a new test to prevent it from re-surfacing.

**Comment by themiurgo** [comment]
No pressure at all, but if this could be fixed before Thursday (pushed to pip) it would be great as I'm introducing folium to Geography students with a notebook tutorial. :smile:

**Comment by ocefpaf** [comment]
Fixing?  Maybe.  Pushing a new release? I am not so sure...  I wanted to take `v0.2.0` slow, there are more corners to cut.

Any chance of pip-installing from `master` for your tutorial?  Or maybe a conda package targeting latest `master`?

PS: If that is an open course I'd love to see a link for the slides/notebooks in our README

**Comment by themiurgo** [comment]
They are not experienced at all with sys stuff or programming and they have to install folium themselves, so that's why I wanted to avoid long commands that they have to type. I'll solve somehow.

And I'll share my notebook, but this course is really basic so don't expect anything too exciting.

**Comment by ocefpaf** [comment]
> They are not experienced at all with sys stuff or programming and they have to install folium themselves, so that's why I wanted to avoid long commands that they have to type. I'll solve somehow.

I was thinking something like:
`pip install https://github.com/python-visualization/folium/archive/master.zip`

And if they have conda I can prepare a package and put it on the ioos channel so they can:
`conda install -c ioos folium`

> And I'll share my notebook, but this course is really basic so don't expect anything too exciting.

Seeing folium being used with Geography students **is** exciting enough for me!

**Comment by BibMartin** [comment]
Or we can just add a tag (no delivery on pypi) ; so that you can 

    pip install git+https://github.com/python-visualization/folium.git@tag000

(or something like this)

**Comment by themiurgo** [comment]
For some reason also after #253 `\r` breaks the popup.

**Comment by ocefpaf** [comment]
@BibMartin do you think that the `\r`is easily addressed by a small change in the template, like for the quotes?  If not let's close this issue and open a new one tagged `v0.2.1`.

**Comment by ocefpaf** [comment]
Let's close this issue and open a new one for the escape sequences.
