### ISSUE TITLE
How about we kill the current way to do choropleth?

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#255]
And add this plugin: https://github.com/timwis/leaflet-choropleth

**Comment by BibMartin** [comment]
:+1: :+1: today's choropleth (`geo_json` in fact) method is rather heavy and involves several elements.
I guess this plugin can let things be simpler.

:-1: yet another javascript dependency

**Comment by ocefpaf** [comment]
So are on the same page to add a new `choropleth` method, but not on using that plugin.

What do you suggest?  Maybe we can just re-factor what we have and make it simpler?

**Comment by themiurgo** [comment]
I'm very much in favour of changing the way choropleths are made. :+1: 

map.geojson should be only an easy way to import/export basic features (like Markers, PolyLines and such), in a way similar to what geojson.io does. The attributes `columns`, `key_on`, `threshold_scale`, ... which are currently present in geojson and such are very choropleth related and not at all geojson-related.

**Comment by foodstamps** [comment]
Is the intent to completely mirror the plugin? This would eliminate the option of specifying breakpoints. It would be preferable to have both options available - default breaks, as well as breaks set by the user. 

Also, the current way to assign the value field used for coloring is a bit confusing. I'm still not 100 percent clear if I can use one of the geojson keys as the field input, or if it must come from a second source (as seen in the example in the doc page with the csv file).

**Comment by ocefpaf** [comment]
Hi @foodstamps.  This issue is being addressed by #266.  We won't be using the plugin for now.

**Comment by foodstamps** [comment]
Thanks @ocefpaf!

**Comment by BibMartin** [comment]
@ocefpaf 
Can we close this, or do we want to keep track of the plugin ?

**Comment by ocefpaf** [comment]
Safe to close.  I guess the plugin bring no advantage to our current implementation.
