### ISSUE TITLE
The `.geo_json()` method is broken in master

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#263]
See http://nbviewer.ipython.org/gist/ocefpaf/18ceaf7f76279966d54e

Before fixing this we need to discuss:

- [ ] Adding a new choropleth method. See #255 
- [ ] Improve the `GeoJsonStyle` class. See #231, #198, and #120.
- [ ] Remove the default legend `[-1, 1]` when styling GeoJSONs that do not need a legend.

The goal the to replace current `.geo_json()` with a `choropleth.()` and the `GeoJson`+`GeoJsonStyle` class

**Comment by themiurgo** [comment]
Yes, this is crucial. I've already mentioned my opinion on how we should structure the API in #255 and #266.

**Comment by ocefpaf** [comment]
See #266

**Comment by BibMartin** [comment]
#266 merged.
