### ISSUE TITLE
Control scale on map

### ISSUE THREAD

**Issue by stleon** [python-visualization/folium#268]
Hi, I want to add on map control scale, that shows km and miles.

In **js** I use:
```
L.control.scale().addTo(map); 
```

But in **Folium** I can't find any parameter for map ([code](https://github.com/python-visualization/folium/blob/master/folium/map.py#L20)), that can build control scale. 

Pull request needed)

**Comment by ocefpaf** [comment]
Implemented in #355

**Comment by stleon** [comment]
Cool work) thanks
