### ISSUE TITLE
line and multiline deprecation warning

### ISSUE THREAD

**Issue by jelmelk** [python-visualization/folium#269]
[`line`](https://github.com/python-visualization/folium/blob/master/folium/folium.py#L129) and [`multiline`](https://github.com/python-visualization/folium/blob/master/folium/folium.py#L175) don't have the usual deprecation warning. 

Can I pull a PR for that?

**Comment by ocefpaf** [comment]
> [`line`](https://github.com/python-visualization/folium/blob/master/folium/folium.py#L129) and [`multiline`](https://github.com/python-visualization/folium/blob/master/folium/folium.py#L175) don't have the usual deprecation warning.

We missed that.

> Can I pull a PR for that?

Please!
