### ISSUE TITLE
A discussion about using `runipy` or something similar

### ISSUE THREAD

**Issue by BibMartin** [python-visualization/folium#272]
To continue discussion started in #271 

@ocefpaf wrote:
> I used runipy in the past to test notebook output, but the problem, in this case, that the changes will be hard to make sense (like diffs of base64 encoded PNGs).

> I think we can do an OK job by strengthening our tests as they are and improve the HTML comparisons. I am sure that the `_repr_html_`, in that case, has a flaw that we can test.

> Or maybe (crazy idea alert) we can add runipy, generate HTMLs, publish them, and inspect them before merging a PR.

We have two levels of validation :
* Ensure that python code works without error
* Ensure that the rendered HTML+JS has the desired output

Ensuring the second level is complicated because we have to test the Javascript and the HTML rendering (and your crazy idea is interesting BTW).

But what I mean is still in the first level. We run the example notebooks, to ensure that everyone can re-run them with the master version of the code. It won't ensure that the output is ok ; but it will avoid to have example notebooks that are 2-3 version late wrt the code.

**Comment by BibMartin** [comment]
> Or maybe (crazy idea alert) we can add runipy, generate HTMLs, publish them, and inspect them before merging a PR.

For that purpose, we may have a huge (single) notebook to generate and check before each PR.
A drawback : in every PR, we will have this NB committed with many changes to handle.

**Comment by ocefpaf** [comment]
> For that purpose, we may have a huge (single) notebook to generate and check before each PR.

Note necessarily.  We can clone a "gallery" notebook repository, `runipy` on them, and get them publish as a `gh-pages`.  All automated in Travis. I will take a stab at this next weekend.

**Comment by BibMartin** [comment]
> Note necessarily. We can clone a "gallery" notebook repository, runipy on them, and get them publish as a gh-pages.

Anyway, I guess we won't eye-check evrything in a *gallery* for every PR ; while scrolling in a notebook seems lighter to me.
 
> All automated in Travis.

An advantage of being ignorant : I see magics everywhere.

> I will take a stab at this next weekend.

:+1:, please

**Comment by ocefpaf** [comment]
> Anyway, I guess we won't eye-check evrything in a gallery for every PR ; while scrolling in a notebook seems lighter to me.

Let's see the challenges to implement this first and then we can decide on a model.  I envision an index.html with links to each notebook.  The scrolling might be a convenience that we won't have in that model, but that way we can simply keep adding notebooks instead of editing the same one.

**Comment by BibMartin** [comment]
:+1:

**Comment by ocefpaf** [comment]
We have a nice setup now that tests the notebooks as py.test and even check for PEP8 compliance.

One last thing would be to convert them to HTML and publish them for visual inspection. But I am leaving this for another issue.

Thanks @BibMartin for doing most of the work!
