### ISSUE TITLE
Broken _repr_html_

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#273]
I mentioned in #271 a problem with the `_repr_html_`.  NB this is not related to `line` and `multiline` as I mentioned in #271.  It is a problem introduce in the recent PRs :unamused: 

@BibMartin This really urges for #272 

See http://nbviewer.ipython.org/gist/ocefpaf/931066a4402320cf872b

**Comment by BibMartin** [comment]
@ocefpaf 
I can't reproduce the bug.
Can you post the commit nb, and the browser version you use, please ?

**Comment by ocefpaf** [comment]
I see this in both `Firefox 42.0` and `Chromium 46.0.2490.86`.

A bisect shows that I introduced this in 11fc66d5e2d4b6ad484969335303a4cd8050178a

See http://nbviewer.ipython.org/gist/ocefpaf/a05c60ffa264126629b8

**Comment by ocefpaf** [comment]
I believe I found the problem.  I will prepare a PR shortly.
