### ISSUE TITLE
Simplify the GeoJSON parsing

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#284]
We have this in the choropleth:

``` python
        # Create GeoJson object.
        if geo_path:
            geo_data = open(geo_path)
        elif geo_str:
            geo_data = geo_str
        else:
            geo_data = {}
```

However, `geo_path` no longer makes sense since we are always embedding the data.

**Comment by BibMartin** [comment]
@ocefpaf 
I would keep it like this in `v0.2.0` to keep backward compatibility with `geo_json` method.
And when we kill `geo_json` in `v0.2.1`, we can change `choropleth` API then, don't you think so ?

**Comment by ocefpaf** [comment]
:+1:

**Comment by ocefpaf** [comment]
> I would keep it like this in `v0.2.0` to keep backward compatibility with `geo_json` method.

I just killed all the backward compatible functions that were deprecated. So it is time to re-visit this.
