### ISSUE TITLE
Loading data for the GeoJson

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#285]
The [`GeoJson()`](https://github.com/python-visualization/folium/blob/master/folium/features.py#L228-L234) can be instantiated with a `file-object`, a JSON string, or a JSON-like python dict.

```python
        if 'read' in dir(data):
            self.data = json.load(data)
        elif type(data) is dict:
            self.data = data
        else:
            self.data = json.loads(data)
```

However, we lost the ability to load it by passing a path string and to not embed the data in the HTML. The former can be addressed by adding an extra logic there. The latter needs some thinking:

- To embed or not the data should be an option.
- Few people would want to not embed the JSON data, so that should not be default.
- It should be explicit in the docstring that by embedding is required to properly display standalone maps, like a notebook on nbviewer.

PS: Here is the code I imagine to start addressing this.

```python
if embed:
    if not os.path.isfile(data):
        msg = 'Cannot find file {}'.format
        raise IOError(msg(data))
    self.data = data  # We probably need to change more things downstream.
else:
    if isinstance(data, dict):
        self.data = data
    elif hasattr(f, 'read'):
        self.data = json.load(f)
    elif os.path.isfile(data):
        with open(data) as f:
            self.data = json.load(f)
    else:
        self.data = json.loads(data)
```

**Comment by BibMartin** [comment]
Fixed by #290. Closing this
