### ISSUE TITLE
Fix Marker docstring example

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#287]
See https://github.com/python-visualization/folium/blob/master/folium/map.py#L357-L381

**Comment by BibMartin** [comment]
@ocefpaf Isn't that fixed by 50ac6c95fba7acc97cb8ca516a19c3fb0e9acedf ?

**Comment by ocefpaf** [comment]
I guess so.  The link above points to `master`, so it no longer makes sense anyway.
