### ISSUE TITLE
We have a bug in `mercator_transform`

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#291]
See cell [5]: http://nbviewer.ipython.org/gist/ocefpaf/2c35a679f333c57ecd1d

**Comment by andrewgiessel** [comment]
Not sure what is going on here, because the nbviewer link isn't working well.  When I go to the gist and run it locally, the "bad" cell looks right and the "good" cell looks wrong.  I'll dig into it more

**Comment by ocefpaf** [comment]
@andrewgiessel nbviewer is back online.

The **Bad** (`cell [4]`) you can see the wave north of the US (wrong).

The **Good** (`cell [5]`) shows the bug, but the results should be like those from `cell [6]` (compare with the image on `cell [7]`).

**Comment by BibMartin** [comment]
Can we close this one ?

**Comment by ocefpaf** [comment]
Yep.
