### ISSUE TITLE
Scan the code for `Layer`s and `control`

### ISSUE THREAD

**Issue by BibMartin** [python-visualization/folium#295]
In PR #293 , we introduce a `Layer` object that enables to define whether a Feature shall appear in layer_controls (with the optional argument `control`).

This needs to be generalized to all features (`Marker`, ...)

**Comment by Conengmo** [comment]
I think this issue can be closed. The current way of layers and features seems good to me. If we want to do something different in this aspect, a new proposal would be best I think.
