### ISSUE TITLE
1.6 pb in geojson_style.js

### ISSUE THREAD

**Issue by netchose** [python-visualization/folium#298]
hi,

when i replace : ```function {{ style }}(feature) { ```# js error

by :```` function {{ style }}(features) { ```` # it works

my test ( geojson file from https://github.com/gregoiredavid/france-geojson ) : 
import folium
import pandas as pd

d = {'region' : pd.Series(["Corse","Champagne-Ardenne","Picardie"]), 'valeur': pd.Series([10,50,30])}

df=pd.DataFrame(d)

map= folium.Map(location=[47.701656, 2.345868],tiles='Mapbox Bright', zoom_start=6)
map.geo_json(geo_path='regions.geojson'
             ,data=df,
             columns=['region', 'valeur'],
             fill_color='YlGn', fill_opacity=0.7, line_opacity=0.2,
             key_on="features.properties.nom",
             legend_name='test')
map.create_map(path='test.html')

thanks a lot !

**Comment by BibMartin** [comment]
What if you replace `key_on="features.properties.nom",` by `key_on="feature.properties.nom",` in your test ?
 I think there have been a typo in the documentation and `feature` is the good syntax.

**Comment by netchose** [comment]
Indeed, it works. thank you for these clarifications.
Bravo for this beautiful project

**Comment by ocefpaf** [comment]
> @ocefpaf I cannot find the issue you had set on this topic. I imagine it's closed in v0.2.0, isn't it ?

Yep.  Closing this one too.
