### ISSUE TITLE
Impossible to click on circle markers when geo_json is called

### ISSUE THREAD

**Issue by rgiot** [python-visualization/folium#30]
When both markers and geo_json methods are called, we cannot click in the markers in order to see their popup (at least on firefox).

It seems that it is because the html code to manage the geojson is called after the javascript code which manages the markers.

The issue appears even if the geo_json python method is called in first.

Manually modifing the html code in order to call  L.geoJson before L.circle solves the issue

**Comment by JBaldachino** [comment]
Leaflet allows explicit z-index settings for objects, perhaps it would be a good idea to provide some access to these settings via the API?  That would be very helpful for my use case and probably be a good solution to this issue.

http://stackoverflow.com/questions/12848812/layer-ordering-in-leaflet-js

**Comment by ocefpaf** [comment]
The original issue reported by  @silentttone and @rgiot cannot be resolved by `setZIndex`.  If I understood the docs correctly `setZIndex` is available only to tweak tile layers.   I agree that this is a bug and, when GeoJSON is used, all markers should be on top.
