### ISSUE TITLE
Unable to display more than 708 markers with clustering

### ISSUE THREAD

**Issue by mhassell** [python-visualization/folium#301]
I've found that if I used simple markers and set clustered_marker=True, I can display up to 708 markers.  If I take more than 708 markers, no markers appear anywhere on the map.  I'm using Philadelphia crime statistics for 2015.  Here's a working example

import pandas as pd
import folium

table = pd.read_csv('police_inct.csv')
crime_map = folium.Map(location=[39.9522, -75.1639], zoom_start=12)
for j in table.index[50000:50709]: 
     crime_map.simple_marker(location=[table['POINT_Y'][j],table['POINT_X'][j]], clustered_marker=True)
crime_map.create_map(path='crime.html')

I'm sorry if this isn't a bug (or isn't the correct way to submit a big report).  This is my first bug report submitted on GitHub.

**Comment by ocefpaf** [comment]
> I'm sorry if this isn't a bug

It might be.  Let's check it out.

> or isn't the correct way to submit a big report

That is the right way :wink: 

> This is my first bug report submitted on GitHub.

Thanks for the report!


In this [1] example I use 1000 markers and they are displayed just fine. Can you share your data so we can take a look?  I am guessing you might have a problem at your 708th point.

http://nbviewer.ipython.org/github/ocefpaf/folium_notebooks/blob/master/test_clustered_markes.ipynb

**Comment by mhassell** [comment]
Thanks for the reply!  I wasn't scrubbing NaNs from my data, and that was messing it up.  I just closed the issue.  Is there anything else I need to do?

**Comment by ocefpaf** [comment]
> Is there anything else I need to do?

Nope.  Thanks for the report!

**Comment by andrewgiessel** [comment]
Just a suggestion:  make sure you don't have any NaNs in your data!
