### ISSUE TITLE
Centering and Auto-zooming Choropleth maps

### ISSUE THREAD

**Issue by psychemedia** [python-visualization/folium#302]
Is there a recognised way of centering a choropleth map based on a bounding box around the extent of boundaries included in a geoJSON file?

I didn't have time to look around to see if there is a polished boundary box detector routine anywhere, so I used the following quick script:

    import json
    jf=open(GEOJSON_FILE,'r').read()
    jj=json.loads(jf)
    
    acc={'minlat':999,'maxlat':-999,'minlon':999,'maxlon':-999}
    for feature in jj['features']:
        for c in feature['geometry']['coordinates']:
            for cc in c:
            #My testfile had lest of co-ords in co-ord list? Should check them rather than ignore them..
                if type(cc[0]) is list:break
                if acc['maxlat']<cc[1]: acc['maxlat']=cc[1]
                if acc['maxlon']<cc[0]: acc['maxlon']=cc[0]
                if acc['minlat']<cc[1]: acc['minlat']=cc[1]
                if acc['minlon']<cc[0]: acc['minlon']=cc[0]
    centre_lat=acc['minlat']+(acc['maxlat']-acc['minlat'])/2
    centre_lon=acc['minlon']+(acc['maxlon']-acc['minlon'])/2

I'm not sure how to set the zoom though? A heuristic based on the height/width of the bounding box?

**Comment by ocefpaf** [comment]
We [had](https://github.com/python-visualization/folium/issues/244) the [fit_bounds](http://nbviewer.ipython.org/github/ocefpaf/folium_notebooks/blob/5deac48727f7f695817061d7de3f0d58665a9677/test_fit_bounds.ipynb) and we should implement it back as soon as possible.

Getting the bounds from the features was never implemented though (as far as I can remember).

PS: If you read you GeoJSON with shapely (or geopandas) you can get the center for free with `shapely_object.centroid.xy`.

**Comment by psychemedia** [comment]
@ocefpaf great - thanks...

**Comment by ocefpaf** [comment]
> I notice `fiona` gives bounds too.

Oh yes.  I forgot about that.
