### ISSUE TITLE
'module' object has no attribute 'Map'

### ISSUE THREAD

**Issue by pannous** [python-visualization/folium#306]
whY?

**Comment by ocefpaf** [comment]
Can you be a little bit more specific?  Version, what 'module' are you talking about?  Maybe even provide a [SSCCE](http://sscce.org/)?

**Comment by pannous** [comment]
solution:
mv folium.py test_folium.py

**Comment by milindk** [comment]
When I try to create map = folium.Map(...)

I get an error as module 'folium' has no attribute 'map'. How can I fix this?

**Comment by ocefpaf** [comment]
@milindk same as https://github.com/python-visualization/folium/issues/306#issuecomment-166983690

**Comment by milindk** [comment]
Using Python 3.6.1
I've cloned the folium using GitBash.
For the CourseWork DSE200x EdX for Python for Data Science 5th week assignment Folium Example I'm trying to set it up

Code snippet is as below

![python_folium](https://user-images.githubusercontent.com/1352171/29773548-9b2aec30-8c1b-11e7-9212-3e5d4e890cac.PNG)

**Comment by ocefpaf** [comment]
> I've cloned the folium using GitBash

I recommend you to `pip` install the latest version instead. Using the latest code from source if not recommended.

I cannot reproduce that error. It is most likely due to your installation and/or the name of the scripts you have on your folder. To try to debug it you can do:

```python
import folium
print(folium.__file__)
print(folium.__version__)
```

**Comment by aster28** [comment]
for name, row in airports.iterrows():
    if row[name] != "South Pole station":
        airports_map.simple_marker(location=[row["Long"], row["Lat"]], popup=row[name]) 
AttributeError                            Traceback (most recent call last)
<ipython-input-28-29f32a590c9d> in <module>()
      1 for name, row in airports.iterrows():
      2     if row[name] != "South Pole station":
----> 3         airports_map.simple_marker(location=[row["Long"], row["Lat"]], popup=row[name])

AttributeError: 'Map' object has no attribute 'simple_marker'

**Comment by aster28** [comment]
I used pip to install folium
