### ISSUE TITLE
Use __geo_interface__ on GeoJson

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#309]
We can check if the object has `__geo_interface__` and just use that.  This would make `folium` more friendly to many objects that follow: https://gist.github.com/sgillies/2217756

**Comment by BibMartin** [comment]
That's a nice idea ; and nice to have that common attribute.
But this protocol does not guarantee that data are in the good EPSG projection. We need to know the projection to plot data in folium. For example, see how we handle `geopandas` in https://github.com/python-visualization/folium/blob/master/folium/features.py#L243-L245

I don't know how we can handle it. We can use `__geo_interface__` and let the user be responsible for projection,or have a `source_projection` kwarg and embed `pyproj`...

**Comment by ocefpaf** [comment]
> For example, see how we handle `geopandas` in https://github.com/python-visualization/folium/blob/master/folium/features.py#L243-L245

It was your `geopandas` implementation that inspired this idea :wink: 

> let the user be responsible for projection

I'd rather leave it for the user.  (We could add a `kw` and convert if an optional dependency, `pyproj`, is available... But I think that would add an extra complexity layer.)

**Comment by pelson** [comment]
Just to add a little more info: GeoJSON is [epsg:3857 only](https://github.com/geojson/draft-geojson/pull/6#issue-5767942). This suggests that the ```__geo_interface__``` is ``epsg:3857`` only. From that, I'd say that ``__geo_interface__`` is a very reasonable interface for the ``GeoJson`` object to handle.

It is plausible that one-day, that will change and that ``__geo_interface__`` will gain a ``crs`` attribute, but that is something that can be handled if/when that occurs IMO.

**Comment by ocefpaf** [comment]
>  This suggests that the `__geo_interface__` is epsg:3857

My guess is that most `__geo_interface__` implementations just outputs whatever crs the data is in, no? That would still force us to convert it before sending to `leaflet`.
