### ISSUE TITLE
Using only the last style_function params when adding a sequence of GeoJSONs

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#318]
@BibMartin I might be misusing the new `style_function` syntax, but I am not sure what is going on.

I am adding a series of 4 features (LineStrings), reading the color from the GeoJSON, creating the `style_function`, and adding them to the map.

The color in the `style_data` seems correct, but the last color seems to propagate back to all the features.

See: http://nbviewer.ipython.org/urls/gist.githubusercontent.com/ocefpaf/e7fe2f2aa0705fcf060c/raw/689fb2a497de1ca2576c7bda2d5c9680772291fe/color_bug.ipynb

**Comment by BibMartin** [comment]
As far as I understand, this is a python phenomenon that happens when using global variables in function.
When you write

    style_function = lambda feature: dict(color=color, weight=2, opacity=0.6)

the `color` value is a global/external variable.

In that case, python uses the value of `color` **at the moment when the function is evaluated** (not when the function is created).
An illustration:

    color = 'green'
    stylefunction = lambda x: color
    print(stylefunction(12))
    color = 'red'
    print(stylefunction(12))

prints

    >> 'green'
    >> 'red'

I'm not really comfortable with that kind of phenomenon. So in short, I try to avoid global variables.

I would recommend you do:

    style_function = lambda feature : dict(
        color=feature['properties']['color'],
        weight=2,
        opacity=0.6)
    for feature in tracks['features']:
        color = feature['properties']['color']
        gj = folium.GeoJson(feature, style_function=style_function)
        gj.add_to(mapa)
        print(color)
        assert color == json.loads(gj.style_data())['features'][0]['properties']['style']['color']

Or (if you like `lambda` complications) :

    style_function = lambda color : (lambda feature: dict(color=color, weight=2, opacity=0.6))
    for feature in tracks['features']:
        color = feature['properties']['color']
        gj = folium.GeoJson(feature, style_function=style_function(color))
        gj.add_to(mapa)
        print(color)
        assert color == json.loads(gj.style_data())['features'][0]['properties']['style']['color']

**Comment by ocefpaf** [comment]
> As far as I understand, this is a python phenomenon that happens when using global variables in function.

You are right.  (I actually was just reading about that when your answer arrived ;-)

I will add a note on the docs.  Users that, like myself are so used to style things via `kargs` created in a loop, will be confused often.

Thanks!

**Comment by BibMartin** [comment]
BTW, I had never understood this python phenomenon before.

I guess this article can be useful:


https://en.wikipedia.org/wiki/Evaluation_strategy#Call_by_sharing

**Comment by ocefpaf** [comment]
Thanks!  I don't get it either, but I should've know.  I have been bitten by that before.
