### ISSUE TITLE
Factor out of folium what's not map specific.

### ISSUE THREAD

**Issue by BibMartin** [python-visualization/folium#320]
Based on the discussion we've had with @ocefpaf @themiurgo @andrewgiessel in #300, it worth factoring a piece of the code out of folium, because it's not map-specific.

2 questions remain open then:

* What has to be externalized ? At least a bit of `colormap.py` but maybe also `element.py` and so on.

* Who / where will it be maintained ? In *python-visualization* organization, or another repo ? If another, which one ?

**Comment by ocefpaf** [comment]
> * What has to be externalized ? At least a bit of `colormap.py` but maybe also `element.py` and so on.

Yes to the former and a very coward maybe to the latter.

> * Who / where will it be maintained ? In *python-visualization* organization, or another repo ? If another, which one ?

Where: I would prefer if that could stay in *python-visualization*, but you are the sole author of virtually all that.  So... You are the boss of that!

Who: Not me :stuck_out_tongue_closed_eyes:

**Comment by ocefpaf** [comment]
@BibMartin now that we have `branca` as a dependency I believe this is complete. Please correct me if I am wrong and re-open it.
