### ISSUE TITLE
Add the period option to TimestampedGeoJson (and/or fix the timestamps?)

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#325]
Even when providing an array of times (in milliseconds) it seems that TimestampedGeoJson is defaulting to show the data daily. (I believe that the default is `period: "P1D"`).

I thought the `period` would be used only if `times` was `null`.  So maybe this is the sign of a deeper problem.

**Comment by BibMartin** [comment]
Hi @ocefpaf 
See #326
