### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#327]
Right now we cannot pass RGB(A)s  (int or float) to the color arguments, like CircleMarker for example.  Most arguments expects HTML color codes only. (And they are failing silently :scream:)

With the new colormap stuff that @BibMartin created we can be more permissive with colors.
See my hack on cells [8] and [9], where I stole part of @BibMartin colormap machinery, here:

http://nbviewer.ipython.org/gist/ocefpaf/60ae6dd499381b107dcc?flush_cache=true

I guess we can just parse all colors in any format.  Anyone against it?

**Comment by montrealks** [comment]
The only html colors I can get working are 'green' 'red' and 'purple'

**Comment by mahnunchik** [comment]
What about hex colors `#00ff00` for icons?

**Comment by ocefpaf** [comment]
This functionality has moved to `branca`. Will open an issue there.
