### ISSUE TITLE
Layered Choropleths

### ISSUE THREAD

**Issue by alexandercbooth** [python-visualization/folium#331]
Hi All, 
I apologize if this is not the appropriate channel to ask this, but how might one go about implementing layered choropleths (each with data bound to them) on the same map in folium? For example, having something like a state choropleth layer, zip choropleth layer and county choropleth layer all in one map, instead of having three separate maps.  
Thanks!

**Comment by BibMartin** [comment]
@alexandercbooth 
> I apologize if this is not the appropriate channel to ask this

This is alright. We are about to release `v0.2` and I took the occasion to add this feature (it's not possible yet).

You can see http://nbviewer.ipython.org/gist/BibMartin/affe53e6e577167d8de2 to see how it would work if PR #329 is accepted.

@ocefpaf 
Sorry for the mess I doing here, but it seems to be a useful enhancement.

**Comment by ocefpaf** [comment]
> Sorry for the mess I doing here

No problem.  I was going to suggest `folium.FeatureGroup`, but it would require more boilerplate code and I like this way better.

However, both ways suffer from the same issue (I think I reported somewhere)  All layers are active by default.  That will lead to an ugly visualization in the case above or unnecessary downloads when adding many optional tiles.

**Comment by alexandercbooth** [comment]
Hi @BibMartin,
That looks great (and in so few lines!), but is it possible to also bind external data to those geojson and topojson instances, like with the Map.choropleth?
Thanks again!

**Comment by BibMartin** [comment]
Sure. I did not play on the styling in the example above.

All about new styling stuff is described in http://nbviewer.ipython.org/github/python-visualization/folium/blob/master/examples/GeoJSON%20and%20choropleth.ipynb

**Comment by alexandercbooth** [comment]
Perfect, this was exactly what I was looking for. 
Thanks so much!!
