### ISSUE TITLE
Popup text with escape sequences

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#332]
Do we want to support escape sequences like new line ('\n') and carriage return ('\r')?

It would be nice to get all python text as is into the popup, but maybe some workarounds are not worth pursuing.  What do you say @BibMartin?

We can workaround this issue by creating IFrames (see below), but manually choosing the width and height is a bummer.

http://nbviewer.ipython.org/gist/ocefpaf/154a9ded80cc11b7e57b

(See #252)

**Comment by raidoz** [comment]
Previously I was using <BR> for new lines, but it does not seem to work anymore in 0.2.0. Is it possible to have a newline in popup text with 0.2.0?

**Comment by ocefpaf** [comment]
Hi @raidoz. This is duplicated of #360.  Take a look there and see if that answer your question.
