### ISSUE TITLE
Docs are outdated (currently 1.2)

### ISSUE THREAD

**Issue by rrshaban** [python-visualization/folium#333]
The [latest docs](http://folium.readthedocs.org/en/latest/) encourage use of `.simple_marker`, which results in a deprecation notice. Similar code is on the Readme for the Github page. There doesn't seem to be any mention of `add_children` in the docs or the Readme. 

I've run into a couple other differences between the online docs and the code, which have presented a series of hurdles trying to use folium.

**Comment by ocefpaf** [comment]
Thanks for the report @rrshaban.  If you are using the latest release the docs should be outdated but OK.  If you are using master you'll have to wait until the bread is out of the oven :wink: 

(Closing this.  Duplicated of #140)
