### ISSUE TITLE
Support Leaflet Global Switches

### ISSUE THREAD

**Issue by sgvandijk** [python-visualization/folium#335]
Leaflet provides a few global switches that can be set before including it on the page:

http://leafletjs.com/reference.html#global

It would be great if those are supported by Folium. For instance, `L_PREFER_CANVAS` can make a big difference when rendering many items, especially in Firefox.

**Comment by BibMartin** [comment]
@sgvandijk 
Thanks for the idea ; it's quite easy to plug on today's `master` and would be of great benefit.

If you feel like doing a PR for that... you'd be welcome.

**Comment by sgvandijk** [comment]
OK happy to work on that, not sure how soon I'll be able to, so don't have to block 0.2 for it ;)

**Comment by ocefpaf** [comment]
Done in #424. Thanks @sgvandijk!
