### ISSUE TITLE
Support GeoPandas

### ISSUE THREAD

**Issue by barryrowlingson** [python-visualization/folium#34]
Its possible to use Folium to map using data and geometry from a GeoPandas object, but it requires writing the GeoPanda geometry to geojson (using the .to_json method);

something like, for gp being a geopandas obejct:

```
open("geom.json","w").write(gp.to_json())
```
and then you can map a column 'q' in the GeoPandas object:

```
map.geo_json("geom.json", data=gp, columns=["name", "q"], key_on='feature.properties.name', ...etc)
```

It should be possible to remove the steps of writing the json and the keying for a GeoPandas frame. Something like:

```
map_osm.geo_json(gp, column="q",....etc...)
```

**Comment by ocefpaf** [comment]
@barryrowlingson the main problem that is the name "`geo_json`", that implies a `GeoJSON` and not a `GeoPandas` object.  We could either introduce a new method that is more "duck type friendly."  This method could take a `GeoPandas`, `GeoJSON`, `Shapely`, `GPX` and other similar objects and files.

We could then convert everything to `GeoJSON` and add the layer or we could look into the Leaflet plugins that do that for us and, in same cases, preserve the data format.

Suggestions?

**Comment by BibMartin** [comment]
We can easily imagine a plugin doing that. It would look like:

    map_osm.add_plugin(GeoPandas(gp))

But maybe we shall think about having a python object for storing geospatial data into folium. Something that would have methods like `from_geojson`, `from_gpx`, ... and methods like `to_geojson`, `to_leaflet`, etc. Not reinventing the wheel ; it may inherit from `shapely` or `geopandas`. What do you think ?

**Comment by ocefpaf** [comment]
I am inclined towards `from_geojson`, `from_gpx`, and `to_geojson`, `to_leaflet`... But we already have `geo_json`.  Maybe we should break the API in a future version...

**Comment by wrobstory** [comment]
Ugh, I hate that I ever wrote the `geo_json` method. Terrible API design. 

Food for thought: If I Were To Rewrite This Today:
* That method would be called `data_overlay`, to follow the `image_overlay` convention.
* `data_overlay`s could be GeoJSON, TopoJSON, GeoPandas object, whatever. 
* When `overlay` is called, a `FoliumDataSource` is created. This class would be the translation layer between the various file formats and GeoJSON, which would be used to build the map. No matter what data source is backing your `FoliumDataSource`, and API to access GeoJSON from it will be the same. This is the API that `data_overlay` will interact with. 
* Any given Folium map can have as many overlays as you want. Folium should be keeping track of all overlays (image and data) via something more robust than `mark_cnt`, and the user should be able to easily remove overlays from their map.

**Comment by ocefpaf** [comment]
> Ugh, I hate that I ever wrote the geo_json method. Terrible API design.

So we just got a license to kill :wink: 

:+1: to all that.  The `_overlay` makes more sense.  I have a problem with `data_` and `image_` though, I prefer `vector_overlay` and `raster_overlay`.

**Comment by wrobstory** [comment]
Yeah, totally agree on vector and raster. That's much better. 

One thing you might want to do is leave the `geo_json` method with a depreciation warning (see: https://github.com/pydata/pandas/blob/master/pandas/util/decorators.py#L8), and then have it call out to the `vector_overlay` method for at least a couple more releases.

**Comment by ocefpaf** [comment]
> method with a depreciation warning

Kill it slowly and make it suffer.  Got it!

**Comment by BibMartin** [comment]
@wrobstory it sound good, and similar to what I had in mind when putting the hand in the plugins.

If you're okay, a way of moving to this can be to have a plugin `FoliumDataSource`, and then to move it to the core.

**Comment by wrobstory** [comment]
Yeah, that's fine. Feel free to make major structural changes without my ok- if it feels like the existing structure is holding you back, by all means break it up. Just need to make sure that the test suite is robust enough to catch everything during a major refactor.

**Comment by BibMartin** [comment]
Can we close this one ?

**Comment by ocefpaf** [comment]
Yes.  We have some integration with GeoPandas now.  any additional functionality deserves a new issue.
