### ISSUE TITLE
Apostrophe on geojson breaks .geo_json

### ISSUE THREAD

**Issue by huevosabio** [python-visualization/folium#342]
I have a geojson that I would like to map, namely [this one](https://raw.githubusercontent.com/codeforamerica/click_that_hood/master/public/data/manhattan.geojson). When I plot it using 

```python
manhattan.geo_json(geo_path = path_to_geojson)
```
it works; however, if I try to read it into a GeoDataFrame and spit out the geojson string or plainly feed the string from openning the fail it will fail:

```python
manhattan.geo_json(geo_str = geojson_str)
```

I've narrowed down my main suspect to an apostrophe in the geojson:
```javascript
... {"cartodb_id":131,"name":"Hell's Kitchen" ...
```

which breaks the script that folium produces. 

FYI: I'm trying this in Jupyter/IPython.

**Comment by ocefpaf** [comment]
@huevosabio I am guessing you are using folium <= v0.1.6, right?  Can you try that with latest master?

**Comment by huevosabio** [comment]
@ocefpaf , yes, I am using folium==v0.1.6,

I'll give it a try with the latest master.

**Comment by ocefpaf** [comment]
My tests cannot confim that.  Closing this.  Please re-open if you cannot make this work with the latest version.
