### ISSUE TITLE
how to use mapbox 

### ISSUE THREAD

**Issue by xiaofeima1990** [python-visualization/folium#345]
Dear everyone:
I am sorry for this silly question. But I very really frustrated with the command:
`custom = folium.Map(location=[45.5236, -122.6750], tiles='Mapbox',
                    API_key='wrobstory.map-12345678')`
I can not get any map from my mapbox style. I was wondering what kinds of info should I filling in the **tiles** and **API_key** 
Is mapbox **token** and **map id** useful to folium? 

Also, when I use the command :
```python
tileset = r'https://api.mapbox.com/v4/xiaofeima.p37fkfk1/0/0/0.png?access_token=pk.eyJ1IjoieGlhb2ZlaW1hIiwiYSI6ImNpa2I2dTRudDBtNnV2dWtwbXh6Njg2NmcifQ.7E2eCTrl2aY5dCtTJJwX
custom2 = folium.Map(location=[45.372, -121.6972], zoom_start=1,
                 tiles=tileset, attr='My Data Attribution')

```
I got very strange picture. Can anyone explain this to me? 

Thank you very much!

**Comment by xiaofeima1990** [comment]
I found that when I use 
```python

tileset = r'https://api.mapbox.com/v4/xiaofeima.p37fkfk1/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoieGlhb2ZlaW1hIiwiYSI6ImNpa2I2dTRudDBtNnV2dWtwbXh6Njg2NmcifQ.7E2eCTrl2aY5dCtTJJwXtw'
custom2 = folium.Map(location=[45.372, -121.6972], zoom_start=2,
                 tiles=tileset, attr='My Data Attribution')
```
I got the right picture

**Comment by ocefpaf** [comment]
@xiaofeima1990 using your the tile URL + the access token, like you did, is probably your best bet for now.

**Comment by ocefpaf** [comment]
Oops.  I guess we can close this.
