### ISSUE TITLE
Folium Choropleth map marker is not working?

### ISSUE THREAD

**Issue by Kiminaka** [python-visualization/folium#346]
Hi first of all, thanks for building the cool interactive visualization library :)
Just a question (not a bug report).

I'm a newbie and am trying to follow the blog post from Domino lab, Creating interactive crime maps with Folium(http://blog.dominodatalab.com/creating-interactive-crime-maps-with-folium/). And I found that the code is probably too old to run the Folium's Choropleth map marker. I found that out because although the older version Ipython notebook on Domino platform seems working (2015), the latest Ipython notebook doesn't work (https://app.dominodatalab.com/r00sj3/crimemaps/view/crimemap.ipynb?commitId=deb6c12365406957e4011c1762d1bf37baf99658). So I'm guessing Folium changed something on Choropleth map marker? 

Thanks!

**Comment by ocefpaf** [comment]
I believe that Domino lab used the released version of folium (`v0.1.6`) available at PyPI.  If you are using the `master` branch you'll notice that a lot has changed (and the `choropleth` mechanism was completely re-written).

You will have to dig the new `docstrings` for the new syntax until we get this release out of the door.  If reading docs is not your forte take a look at the example gallery.

http://nbviewer.jupyter.org/github/ocefpaf/folium_notebooks/tree/master/
