### ISSUE TITLE
Split folium ?

### ISSUE THREAD

**Issue by BibMartin** [python-visualization/folium#349]
I'm doing several things mixing folium with crossfilters and nvd3 these days.

As discussed in #300, it may worth externalizing things from folium for it to focus on Leaflet integration.

I would propose to split folium into:

* `folium` = the leaflet part
* `branca` = the `element + colormap` part

(any other name suggestion is welcome ; I think about branca because it means "branch" in latin and folium would be attached to it.)

`branca` would be a dependency of `folium` but they would both be maintained in `python-visualization` community.

A good timing for this split would be just after `v0.2` release ; provided we have few open PR.

**Comment by ocefpaf** [comment]
> any other name suggestion is welcome ; I think about branca because it means "branch" in latin and folium would be attached to it.

:+1: 

> `branca` would be a dependency of `folium` but they would both be maintained in `python-visualization` community.

I am fine with that.  I imagine that `branca` would depend only on `Jinja2` and standard library, right?

**Comment by ispmarin** [comment]
The geo elements (line, polyline, etc) that are equivalent to OGC geographical operations? Like [shapely](http://toblerity.org/shapely/manual.html#general-attributes-and-methods) operations?

**Comment by ocefpaf** [comment]
@BibMartin can we close this?

**Comment by ispmarin** [comment]
Is it decided?

**Comment by ocefpaf** [comment]
> Is it decided?

Branca has already started.  Nothing should change to `folium` users though.
