### ISSUE TITLE
Save image

### ISSUE THREAD

**Issue by achourasia** [python-visualization/folium#35]
Is there a way to save the image as PDF or PNG?
I am hoping to batch a set of datasets to create a set of image sequence for creating a video.

**Comment by psychemedia** [comment]
I've just come up with a recipe for doing this using selenium. For a folium map, `m`:

    import os
    import time
    from selenium import webdriver

    delay=5
    fn='testmap.html'
    tmpurl='file://{path}/{mapfile}'.format(path=os.getcwd(),mapfile=fn)
    m.save(fn)
    
    browser = webdriver.Firefox()
    browser.get(tmpurl)
    #Give the map tiles some time to load
    time.sleep(delay)
    browser.save_screenshot('map.png')
    browser.quit()

**Comment by ocefpaf** [comment]
@psychemedia that is very cool.  It is also giving me some crazy ideas about continuous integration testing of maps.

**Comment by chengjun** [comment]
1. Open the generated html with chrome
2. Print  to save it as pdf, 
3. Open the pdf and export it as png or the other formats.

**Comment by carolinux** [comment]
This is how I did it within python (ie calling subprocess):
```
    map.save("tmp.html")
    url = "file://{}/tmp.html".format(os.getcwd())
    outfn = os.path.join(outdir,"outfig.png")
    subprocess.check_call(["cutycapt","--url={}".format(url), "--out={}".format(outfn)])
```
To save anybody else reading this some time: It wouldn't work if I passed the url as 'tmp.html', it needs to be a full path with file in front.

**Comment by xapple** [comment]
In my experience cutycapt will render the map, but not any markers you have placed on it. Folium really needs a PDF or PNG output option.

**Comment by sergiolucero** [comment]
I am using folium to generate a series of maps that need to end up in a PDF
or Word file. Find myself having to launch selenium to simulate a browser,
then save a screenshot. Works well but it's a cumbersome solution.

**Comment by ocefpaf** [comment]
@sergiolucero do you fancy sending a PR to add that functionality to `folium`?

**Comment by oscarechobravo** [comment]
@sergiolucero @ocefpaf Did a PR come from this? Trying to make comparable maps as  subfigures, via an elegant solution for exporting to PDF or PNG.

**Comment by ocefpaf** [comment]
@oscarechobravo no PR yet. Do you want to try it?

**Comment by ocefpaf** [comment]
Finally done in #634 

It is still experimental and feedback is welcome. Note that you'll  need `phantomjs` installed to make it work.

**Comment by psychemedia** [comment]
This looks like it could be handy for screenshotting, though again it uses a (Chrome) browser to grab the map image: https://github.com/wbkd/leaflet-mapshot

**Comment by laxatives** [comment]
Could you please provide an example of usage instead of pointing to the raw PR? You're asking all of your users to read your code when there should just be documentation provided.

**Comment by SatvikNema** [comment]
> Finally done in #634
> 
> It is still experimental and feedback is welcome. Note that you'll need `phantomjs` installed to make it work.

@ocefpaf the notebook mentioned inside that pr doesn't exist anymore. Can you explain how this feature works?

**Comment by RanTalbott** [comment]
> I've just come up with a recipe for doing this using selenium. For a folium map, `m`:

Thanks for posting this.

I have over 50 GPX tracks that I wanted to plot on maps. gpxplotter did a great job of making folium html files, but I didn't want to do the manual capturing and renaming of screenshots to get PNGs.

The selenium hack enabled me to automate the screenshots, too. Since I'm fairly new to Python, and hadn't heard of selenium, I never would have thought of it, myself.

Thanks again.
