### ISSUE TITLE
Plot lines with start coordinates and end coordinates

### ISSUE THREAD

**Issue by ispmarin** [python-visualization/folium#350]
Hi there,

I was wondering if there is a way to plot lines and add to a map using folium. It seems that there is something implemented but not documented:

https://github.com/jwass/folium/commit/865eda47ddcec937ab22fa39503cebb11a754a69#commitcomment-6469995

Any ideas?

**Comment by ocefpaf** [comment]
Take a look at this example:

http://nbviewer.jupyter.org/github/ocefpaf/folium_notebooks/blob/master/test_lines.ipynb

New docs are coming...
