### ISSUE TITLE
HTML in Popup text

### ISSUE THREAD

**Issue by themiurgo** [python-visualization/folium#360]
HTML in popups is not recognised. How do I show fancy bold and italic text? :)

**Comment by ocefpaf** [comment]
That one fell under the radar...

The latest changes no longer allow for pushing HTML strings and get them rendered. @BibMartin can comment on the details of the implementation.  The alternative is to wrap the HTML in an IFrame. See https://github.com/python-visualization/folium/pull/294

PS: It would be a good addition to get the old functionality back without changing the current API.  Not sure if that is possible though.
