### ISSUE TITLE
Links broken in the docs (quickstart.html)

### ISSUE THREAD

**Issue by BibMartin** [python-visualization/folium#361]
In the docs, links inside the quickstart notebook are broken.
For example in the end of the file, we read:

*For more choropleth example, please visit GeoJSON and choropleth.ipynb*

We can fix it in putting a full-url ; or in compiling the other example notebooks in the docs.

**Comment by ocefpaf** [comment]
OK. That needs to be fixed before uploading the new release to PyPI.  I am on it.
