### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Map'

### ISSUE THREAD

**Issue by brkygur** [python-visualization/folium#365]
Hello. 
Seriously sorry about flooding with the same problem.
As I have explained before using folium.Map gives the following result.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/Berkay/Desktop/untitled1.py", line 1, in <module>
    import folium
  File "folium.py", line 14, in <module>
    bna = folium.Map(location=[39, 35],
AttributeError: 'module' object has no attribute 'Map'
```
I have tried:

> python -c "import folium; print(dir(folium.Map))"

With the result:

> ['class', 'delattr', 'dict', 'doc', 'format', 'getattribute', 'hash', 'init', 'module', 'new', 'reduce', 'reduce_ex', 'repr', 'setattr', 'sizeof', 'str', 'subclasshook', 'weakref', 'auto_bounds', '_build_map', '_popup_render', '_repr_html', 'add_layers_to_map', 'add_tile_layer', 'add_wms_layer', 'circle_marker', 'click_for_marker', 'create_map', 'fit_bounds', 'geo_json', 'image_overlay', 'lat_lng_popover', 'line', 'multiline', 'polygon_marker', 'simple_marker']

You have said that it would have something to do with the Spyder IDE that I am using. Upon that I have used Sublime Text 3 and IDLE both giving the same result.

What would you recommend?
If it has something to do with the Python (x,y) that I am using. Could you recommend an another python distribution that I can use in it's place.  I can't stress enough that I have been using the same preferences yesterday. Now it has decided to act up.

Thank you beforehand,
Berkay Gür

**Comment by ocefpaf** [comment]
Please don't open new issue.  You can re-open that one.

> If it has something to do with the Python (x,y) that I am using. 

Probably. I can only guess about your setup and think you have more than one python installation there.

> Could you recommend an another python distribution that I can use in it's place.

Anaconda/miniconda.  [These](https://github.com/ioos/conda-recipes/wiki/Setting-up-the-IOOS-Python-Environment-for-Win64) instructions might help you set your environment up.

Closing this as it is not a folium issue.  But you can ask for help here even with the issue closed :wink:

**Comment by ocefpaf** [comment]
Here is something that might help you debug this.  Try

```shell
python -c "import sys; print(sys.prefix)"
```

At the command line and in your IDLEs.  Compare the results and see if you are calling the same Python.  If they are different you either have to find a way to install folium in your IDLE Python or call the same Python you have on the command line path.

**Comment by brkygur** [comment]
Hello,
First off thank you for your help. The problem is solved. But I have a question.

I'm using folium 0.2.0 with Spyder with the [IOOS](https://github.com/ioos/conda-recipes/wiki/Setting-up-the-IOOS-Python-Environment-for-Win64) environment of Anaconda. I am trying the create a folium choropleth map and have used the given code.

```
import json
import folium
import pandas as pd

df = pd.read_csv(r'C:/Users/Berkay/Desktop/Python/Project/layers/ghi.csv')
jsonData=json.load(open('C:/Users/Berkay/Desktop/Python/Project/layers/tr.json'))


mapa = folium.Map(location=[-15.80, -47.88],
                  tiles="Mapbox Bright",
                  zoom_start=3)

mapa.choropleth(geo_str=jsonData,
                data=df,
                columns=['NAME', 'GHI_ORT_10'],
                fill_color='OrRd',
                key_on='feature.id')
mapa.save('yxz.html')

```
The .json file is attached as a txt file.
[tr.txt](https://github.com/python-visualization/folium/files/131330/tr.txt)

Same for the .csv, attached as a .txt

[ghi.txt](https://github.com/python-visualization/folium/files/131332/ghi.txt)


Is there something wrong with the code I have created or is there an issue with the folium.

Thank you beforehand,

**Comment by ocefpaf** [comment]
> First off thank you for your help. The problem is solved. But I have a question.

Glad it is solved.

> I'm using folium 0.2.0 with Spyder with the IOOS environment of Anaconda. 

:+1: 

> Is there something wrong with the code I have created or is there an issue with the folium.

What is the problem? (Bare in mind that the devs here are all volunteer and all the information you can provide will help us. We want to avoid wasting time with copying/pasting/downloading/running code just to check what is going on.)

**Comment by brkygur** [comment]
God. I was sure I had copied it also. Seems not the case. Anyways here is the error
```

C:\Users\Berkay\Desktop\csvdeneme.py:23: FutureWarning: 'threshold_scale' default behavior has changed. Now you get a linear scale between the 'min' and the 'max' of your data. To get former behavior, use folium.utilities.split_six.
  key_on='feature.id')
Traceback (most recent call last):
  File "C:\Users\Berkay\Desktop\csvdeneme.py", line 24, in <module>
    mapa.save('yxz.html')
  File "C:\Users\Berkay\Anaconda2\envs\IOOS\lib\site-packages\folium\element.py", line 129, in save
    html = root.render(**kwargs)
  File "C:\Users\Berkay\Anaconda2\envs\IOOS\lib\site-packages\folium\element.py", line 330, in render
    child.render(**kwargs)
  File "C:\Users\Berkay\Anaconda2\envs\IOOS\lib\site-packages\folium\element.py", line 593, in render
    element.render(**kwargs)
  File "C:\Users\Berkay\Anaconda2\envs\IOOS\lib\site-packages\folium\element.py", line 589, in render
    figure.script.add_children(Element(script(self, kwargs)),
  File "C:\Users\Berkay\Anaconda2\envs\IOOS\lib\site-packages\jinja2\runtime.py", line 436, in __call__
    return self._func(*arguments)
  File "<template>", line 19, in macro
  File "C:\Users\Berkay\Anaconda2\envs\IOOS\lib\site-packages\jinja2\runtime.py", line 196, in call
    return __obj(*args, **kwargs)
  File "C:\Users\Berkay\Anaconda2\envs\IOOS\lib\site-packages\folium\features.py", line 278, in style_data
    self.style_function(feature))
  File "C:\Users\Berkay\Anaconda2\envs\IOOS\lib\site-packages\folium\folium.py", line 609, in <lambda>
    "fillColor" : color_scale_fun(x)
  File "C:\Users\Berkay\Anaconda2\envs\IOOS\lib\site-packages\folium\folium.py", line 600, in <lambda>
    if u<=color_data[get_by_key(x,key_on)]])]
KeyError: None
```

**Comment by ocefpaf** [comment]
That happens because you JSON does not have a `feature.id` structure. Your's is `feature.properties.NAME`.
