### ISSUE TITLE
Request default color instead of KeyError

### ISSUE THREAD

**Issue by napjon** [python-visualization/folium#367]
For example, If I'm using this code snippet to build choropleth,

```Python
map = folium.Map(location=[48, -102], zoom_start=3)
map.geo_json(geo_path=state_geo, data=state_data,
             columns=['State', 'Unemployment'],
             key_on='feature.id',
             fill_color='YlGn', fill_opacity=0.7, line_opacity=0.2,
             legend_name='Unemployment Rate (%)')
```

if one of the state missing in the state_data, it will return KeyError. Probably because folium doesn't know what color to fill. What if it just return blank/white color?

**Comment by ocefpaf** [comment]
> What if it just return blank/white color?

Guessing a color is not recommend.  What if white (or the "blank grey") is part of the colormap?

I recommend adding that entry to you data or using the latest `folium` and the `style_function` kw.

See some example at:

http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/GeoJSON%20and%20choropleth.ipynb
