### ISSUE TITLE
Map Resizing

### ISSUE THREAD

**Issue by silentttone** [python-visualization/folium#37]
I'm kinda new to folium, so I may have just missed something obvious, but I haven't been able to find a folium feature to resize the map. 
I could change the javascript for the map, but as I've got about 10 different maps (and more to come) that are all being generated automatically using python, this doesn't seem like a good solution. 
I'd ideally want the map to dynamically respond based on the window size. 

Is this already possible without changing the javascript? If not, it'd be a great feature.

**Comment by ocefpaf** [comment]
@birdage I am closing this.  @silentttone issue seems to be unrelated to the notebook display like yours.  We need to pass relative size (in %) for that  (See #23).

(And I am working on your issue tight now :wink:, see #90)

**Comment by datamany** [comment]
You should use this:
f = folium.Figure(width=1000, height=500)
m = folium.Map(location= initial_location, tiles="openstreetmap",
zoom_start=zoom_start_defined, min_zoom = min_zoom_defined).add_to(f)


If you set it in folium.Map - it reshapes the map itself, but window map is the same (at least that is so for Jupyter Notebook)

source:
https://stackoverflow.com/questions/48789751/set-map-boundary-and-stop-endless-panning-in-a-loop-of-folium-map

**Comment by Singh1106** [comment]
> You should use this:
> f = folium.Figure(width=1000, height=500)
> m = folium.Map(location= initial_location, tiles="openstreetmap",
> zoom_start=zoom_start_defined, min_zoom = min_zoom_defined).add_to(f)
> 
> If you set it in folium.Map - it reshapes the map itself, but window map is the same (at least that is so for Jupyter Notebook)
> 
> source:
> https://stackoverflow.com/questions/48789751/set-map-boundary-and-stop-endless-panning-in-a-loop-of-folium-map

Had the exact same issue as @silentttone , this worked perfectly. Thank you.

**Comment by sahanaraguram2000** [comment]
this worked for me @Singh1106 ! thank you :)

**Comment by mejl** [comment]
How can I fit the map on mobile devices?

**Comment by KingSand08** [comment]
I know I'm late to the party, but if you wanted to add your exact monitor size as the width as seen on this forum post:
[https://stackoverflow.com/questions/3129322/how-do-i-get-monitor-resolution-in-python](https://stackoverflow.com/questions/3129322/how-do-i-get-monitor-resolution-in-python)

As an example:
```python
import folium, pandas
from screeninfo import get_monitors

m = get_monitors()
m_width = m[0].width
m_height = m[0].height

map = folium.Map(width = m_width, height = m_height, location=[37.33528976604971, -121.88103394908227], 
zoom_start = 4, min_zoom = 2, max_bounds=True, tiles = "Cartodb Positron");
```
I'm not going to be using this for a frame, rather a full page, so I don't need that part, but please modify your code to make sure it is included if you need it.
