### ISSUE TITLE
Support specifying a page title when saving to an HTML file

### ISSUE THREAD

**Issue by mairsbw** [python-visualization/folium#370]
Right now no <TITLE/> attribute is being specified for a saved HTML file. I'd like to specify one so that it's easy to see what dataset I've been plotting.

**Comment by BibMartin** [comment]
Hi @mairsbw ,
can you give an example or more details, please ?
In fact I cannot understand what you'd like to do.

**Comment by andrewgiessel** [comment]
I think he just wants to put a <title> tag in the generated html file

**Comment by BibMartin** [comment]
In that case, you can embed arbitrary HTML in a Figure using for example:

```python
f = folium.element.Figure()
f.html.add_child(folium.element.Element("<h1>This is a title</h1>"))

m = folium.Map(height=500)
f.add_child(m)

f
```

**Comment by mairsbw** [comment]
That's a very complicated way to have to change the title, but since it's possible, I don't see a need to push this issue further.

**Comment by BibMartin** [comment]
We can imagine having a method `f.title("This is a title")`.
But this will now happen in *branca* ; see https://github.com/python-visualization/branca/issues/10

**Comment by Addi78Hannoi** [comment]
module 'folium' has no attribute 'element'
