### ISSUE TITLE
FeatureGroup name argument ignored?

### ISSUE THREAD

**Issue by brwst** [python-visualization/folium#371]
Hello everyone,

I am trying to set a ``FeatureGroup`` name for a set of ``PolyLine``s, but the name I give to the ``FeatureGroup`` isn't sticking in the map layer control menu.  Instead, a ``macro_element_...`` is returned.

I've set up an [example Jupyter Notebook](http://nbviewer.jupyter.org/github/brwst/folium/blob/master/FeatureGroup_name.ipynb). (in the style of pull request #242) showing this behavior.  Should this be expected?

**Comment by BibMartin** [comment]
Hi @brwst. You're true there's a bug here.

This is due to `__init__` method of `FeatureGroup` that starts with

```python
    def __init__(self, name=None, overlay=True, control=True):
        super(FeatureGroup, self).__init__(overlay=overlay, control=control)
        ...
```

while it should be


```python
    def __init__(self, name=None, overlay=True, control=True):
        super(FeatureGroup, self).__init__(overlay=overlay, control=control, name=name)
        ...
```

A short term workaround is to add in your code:

```python
feature_group.layer_name = 'My feature group'
```

**Comment by brwst** [comment]
Thanks for your help @BibMartin -- the workaround works fine on my end.

**Comment by pjandrews** [comment]
I just installed folium today (8/5) and am seeing this issue.

Here is the version I'm using:
>>> import folium
>>> folium.__version__
'0.2.1'

**Comment by brwst** [comment]
Hello @pjandrews 

I'm not able to replicate your problem -- folium 0.2.1 seems to fix this issue for me.  Do you still see the `FeatureGroup` naming issue when using [this example notebook](https://nbviewer.jupyter.org/github/brwst/folium/blob/master/FeatureGroup_name-0.2.1.ipynb)?

**Comment by ocefpaf** [comment]
I cannot reproduce it either :confused:

**Comment by pjandrews** [comment]
@brwst, I don't see the issue when I use the example notebook you provided.

The strange thing is that I have two computers, both with 0.2.1 and when I run the same code the error is happening on one, but not the other. Here is my code if it helps...

def LDM(df,adb):
    global map_  
   
    #create a DataFrame
    df_ldm = df_ld[(df_ld['Lat'] > -200)&(df_ld['Lat'] < 200)&(df_ld['Lat'] != -1)]

    #change the colors based on the data
    def popup(lc,st,rat,tp):
        date = lc.split()[0]    
        try:
            rat = rat.split('_')[2]
        except:
            pass        
        output = str(date) +", "+ str(st) +", RAT: "+ str(rat) + ", Throuput\(kbps\): "+str(tp)    
        return output    
    
    def color(status):
        if status == 'SUCCESS':
            col = 'green'
        else:    
            col = 'red'
        return col
    
    def fill_color(rat):
        if rat == 'NETWORK_TYPE_LTE':
            colf = 'blue'
        elif 'HSPA' in rat:
            colf = 'orange'
        else:
            colf = 'pink'
        return colf
    
    #create and name the layer
    fgLD=folium.FeatureGroup(name=adb+'_Large Download')
   #this is the workaround
    #fgLD.layer_name = adb+'_Large Download'    
    
    for lat,lon,status,lc,st,rat,tp in zip(df_ldm['Lat'],df_ldm['Lon'],df_ldm['STATUS'],df_ldm['date'],\
                                              df_ldm['START_TIME'],df_ldm['RAT Start'],\
                                              df_ldm['Throughput']):

        folium.CircleMarker([lat,lon], radius=150, color=color(status), fill_color=fill_color(rat),popup=popup(lc,st,rat,tp)).add_to(fgLD)    
    
    map_.add_child(fgLD)

LDM(dfadb,adb)
map_.add_child(folium.LayerControl())
map_.save(wloc+'\\'+loc+'_'+build+'_'+op+'.html')
