### ISSUE TITLE
Adding value to Marker

### ISSUE THREAD

**Issue by edublancas** [python-visualization/folium#379]
Hi, I've using folium for a project and it's great!

I want to visualize a numeric value, so right now I'm passing it as the `popup` parameter in `Marker`. However, I would like to see that value without having to click in the Marker.

The objective of my map is to easily visualize the spatial distribution for that value. Is there any way to do this?

Thanks!

**Comment by ocefpaf** [comment]
Can you be more specific when you say

> I want to visualize a numeric value

I am not sure if you some kind of plot/layer or just the text of the number.  If the latter take a look at:

http://nbviewer.jupyter.org/gist/BibMartin/ec2a96034043a7d5035b

**Comment by edublancas** [comment]
For every point, I have a score that I want to display. So basically show that number in every marker. Is that possible?

**Comment by ocefpaf** [comment]
If you do want the marker than that feature is not implemented.  We have an issue for that #210. PRs welcome :wink:

**Comment by edublancas** [comment]
Ok, thanks for the answer! I may have some time to work on that.

**Comment by cgarciaf** [comment]
Any code example i can use to implement this with folium? seem fixed.
