### ISSUE TITLE
v0.2.1

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#388]
- [X] update `Changelog` on `master` (See #390);
- [X] cherry-pick #391 
- [X] cherry-pick #393
- [X] cherry-pick #404
- [X] address #408
- [ ] release!

**Comment by ocefpaf** [comment]
@BibMartin can you review and merge

https://github.com/python-visualization/folium/pull/391
https://github.com/python-visualization/folium/pull/404
https://github.com/python-visualization/folium/pull/406
https://github.com/python-visualization/folium/pull/405

**Comment by BibMartin** [comment]
Done. Thanks @ocefpaf for the 4 PRs, and for the (coming soon) release !!

**Comment by ocefpaf** [comment]
The new release is out https://github.com/python-visualization/folium/releases/tag/v0.2.1

(PyPI and conda packages coming soon...)
