### ISSUE TITLE
Markers from github problem

### ISSUE THREAD

**Issue by psychemedia** [python-visualization/folium#392]
Some of the baked in _leaflet.awesome-markers_ etc links on rawgit are being throttled/blocked, or otherwise broken?

http://rawgit.com/lvoogdt/Leaflet.awesome-markers/2.0/develop/dist/leaflet.awesome-markers.css?ver=4.4.2
http://rawgit.com/lvoogdt/Leaflet.awesome-markers/2.0/develop/dist/leaflet.awesome-markers.js?ver=2.0
http://rawgit.com/lvoogdt/Leaflet.awesome-markers/2.0/develop/dist/leaflet.awesome-markers.css?ver=4.4.2

I notice the links are not to the rawgit CDN for production use, which might also be causing issues?

**Comment by BibMartin** [comment]
You're true @psychemedia , I've noticed it almost at the same time.
See fix in #393 .

**Comment by ocefpaf** [comment]
Fixed in #393
