### ISSUE TITLE
Multiple Vincent graphs in the same Marker Popup

### ISSUE THREAD

**Issue by guillaumedaniel** [python-visualization/folium#400]
Add a marker on a map, at the location corresponding to my real sensor location.
By clicking on the marker I would like a popup to appear , and show all data channels delivered by this sensor, typically more than 3 and less than 10…
I feel like using the Vincent/Vega functionalities of folium (e.g. folium.Vega() methods) is the way to go.
(cf. your “Vincent/Vega Markers” example at page https://folium.readthedocs.org/en/latest/quickstart.html#markers , but now imagine I would like to have several graphs like the “Dominant wave Period (s)” , one above the other, on the same popup… )
 
I have the impression that adding several Vincent.Line visualization on the same popup is not currently feasible…
Note that using the Vincent.line in the “multiline” mode is NOT an option as my different signals have different timestamps (time reference) and sampling frequency…
 Thank you.

**Comment by ocefpaf** [comment]
@guillaumedaniel vincent seems to be unsupported for a while now and I guess you'll have better look with another library. I recommend you take a look at Bokeh, but bare in mind that you can also create static figures and use them as popups.

**Comment by guillaumedaniel** [comment]
Thank you for your feedback. I will investigate other solutions.

Best.
G.



Guillaume DANIEL, Ph.D., R&D Scientist
Magnitude LLC, A Baker-Hughes/CGG joint venture

On 23 mars 2016, at 17:50, Filipe <notifications@github.com<mailto:notifications@github.com>> wrote:


@guillaumedaniel<https://github.com/guillaumedaniel> vincent seems to be unsupported for a while now and I guess you'll have better look with another library. I recommend you take a look at Bokeh, but bare in mind that you can also create static figures and use them as popups.
