### ISSUE TITLE
Any idea to support curvilinear line of the PolyLine function?

### ISSUE THREAD

**Issue by chengjun** [python-visualization/folium#401]
Folium is very cool for visualizing networks on the map. I wanna to know is there any idea to support curvilinear line of the PolyLine function? The straight line looks a bit dumb in the current form. Thank you.

**Comment by ocefpaf** [comment]
I am not sure if leaflet PolyLine provides curved lines. Maybe a plugin does. If you can come up with an example we can try to implement that.

**Comment by ocefpaf** [comment]
I guess that there is no such plugin.
