### ISSUE TITLE
Create maps with Bing Maps

### ISSUE THREAD

**Issue by kimiandj** [python-visualization/folium#407]
Hi everyone,

I've been using Folium for a week and managed to create very easily cool interactive maps with OSM, MapQuest and MapBox – great tool! 
However I wonder if it is possible or not to create interactive maps with Folium using Bing Maps. The Leaflet.js library enables us to do so but I don't know how to achieve this with Folium. Any idea?

**Comment by ocefpaf** [comment]
Bing is not in the default tiles but you can add it as custom tiles if you know the URL. The syntax is `tiles=http://{s}.custom_tiles.org/{z}/{x}/{y}.png` when creating the map.
