### ISSUE TITLE
Vega popup

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#408]
@BibMartin I am trying to run all the notebooks in the collection before preping the next release and I am having trouble with the Vega pop example. Can you take a quick look?

https://gist.github.com/ocefpaf/1dd1bb2f118c37d9362d9df7bf3fd520

**Comment by BibMartin** [comment]
Sorry @ocefpaf I have few time these days.

It seems you shall replace the line 

```python
popup = folium.Popup(vega, max_width=300)
```

by

```python
popup = folium.Popup(max_width=300).add_child(vega)
```

for some (probably bad) reason to be investigated later.

**Comment by ocefpaf** [comment]
No need to be sorry. I guess we can consider that a small bug since vincent is no longer developed. I will prep the release and we can point people here as a reference.
