### ISSUE TITLE
vincent popups fails on same marker after clicking off the marker

### ISSUE THREAD

**Issue by birdage** [python-visualization/folium#41]
creating a marker with vincent popups is great but at the minute when you click a marker and view the popup and plot/data, close the popup and try to view it again nothing is shown

**Comment by ocefpaf** [comment]
This is fixed for HTML/text popups.  The problem remains with vincent popups, but that will be addressed once we get a new vincent release.

**Comment by wrobstory** [comment]
`new vincent release`

:grimacing:

**Comment by ocefpaf** [comment]
It is easier to pass the ball than to try to score a goal :wink:
