### ISSUE TITLE
Project images with affine transforms in ImageOverlay plugin

### ISSUE THREAD

**Issue by wbierbower** [python-visualization/folium#413]
Hi, first of all, thanks to everyone involved with the folium project for working on such a cool library.

I was looking into the ImageOverlay feature, and I was wondering if there's been any discussion about the feasibility and interest in adding support for projecting images with affine transforms.  Does anyone know?

Thanks!

**Comment by ocefpaf** [comment]
That should be feasible and there is interest. I Don't have enough experience with `affine` transformations. Do you want to give that a go?

Note that the `affine` must be an optional dependency.

**Comment by bakerbd** [comment]
I think gdal.py and rasterio should be used to handle things like that

**Comment by wbierbower** [comment]
@bakerbd I know that rasterio is a great wrapper around GDAL for data processing, but I don't think it has any visualization capabilities

@ocefpaf I don't have too much experience either, but I'd be interested in giving it a shot after some discussion.

Right now the function call is like this:

```python
a  # numpy.ndarray
bounds = {
        'min_lat': lat-width/2,
        'max_lat': lat+width/2,
        'min_lon': lon-width/2,
        'max_lon': lon+width/2
}
m.image_overlay(a, **bounds)
```

My thought is that there could either be a keyword argument in [`Map.image_overlay`](https://github.com/python-visualization/folium/blob/master/folium/folium.py#L695) such as `affine`, that could be passed into the array and superscede the `bounds` argument.  Or the `bounds` argument could be generalized to accept affine objects.

```python
from affine import Affine
aff = Affine.identity()

m.image_overlay(a, None, affine=aff)
```

It looks like Leaflet only has built-in support for affine transformations of geometries, though.

A couple resources that might be helpful:

leaflet transformation utility function: http://leafletjs.com/reference.html#transformation
custom leaflet layer for affine images: https://github.com/fedealconada/Leaflet.AffineImage
affine library for python: https://github.com/sgillies/affine

I welcome any comments or suggestions or resources that might help us get this feature added to folium.  Thanks!

**Comment by ocefpaf** [comment]
@wbierbower sounds like a nice idea, but we don't have the time to develop it. (Day jobs are always in the way of fun coding.)

**Comment by wbierbower** [comment]
@ocefpaf you bet.  If you don't mind, I'll keep this issue open for now to help gauge interest and see if anyone has other ideas.

**Comment by avantikab** [comment]
Hey! I am facing a bit of alignment problem with ImageOverlay plugin of folium. 
I have created an image using Basemap and saved the plot after trimming it. After providing the coordinate boundaries for the image, the image gets skewed. 
I then manually adjust the latitudes and longitudes; but even after such adjustments the two are not perfectly aligned. 
I was curious if I could rotate the image anticlockwise for a few degrees; since that would solve the issue?

It would be great if I could get some help regarding the same! Thank you!

**Comment by Conengmo** [comment]
I'll close the issue, since 6 years later it seems unlikely we'll get this in folium. If somebody wants to discuss further, feel free to do so here. We can re-open the issue if necessary.
