### ISSUE TITLE
Mapscale on the map

### ISSUE THREAD

**Issue by qingkaikong** [python-visualization/folium#414]
I try to make a map with the scale bar show at the bottom, i.e. a scale for distance on the map. But it seems I can not find functions to add the scale bar? Can you point me to if there's any? Or do you have any plan to add one? Thanks.

**Comment by qingkaikong** [comment]
Sorry, I found it. By adding a control_bar, the scale will show on the map.

**Comment by sangyh** [comment]
can you explain how you solved this?

**Comment by qingkaikong** [comment]
When you create the map, just set the control_scale = True, then you will have the simple map scale at the bottom. It is not perfect, but enough for my need. 

Example:
map_1 = folium.Map(location=[lat, lon], zoom_start=8,control_scale = True)

**Comment by sangyh** [comment]
Great. thanks. Do you know if I could also add a search box? There's that option for leaflet but havent found anything for Folium.

**Comment by ocefpaf** [comment]
> There's that option for leaflet but havent found anything for Folium.

Can you open a separated issue for that feature request? There is no search box yet, but that is possible. (BTW PRs are welcomed :wink: )

**Comment by sangyh** [comment]
Okay will do. Sorry, I am a new member on here, and just beginning to learn programming.
