### ISSUE TITLE
Plot a circle with fixed distance as radius

### ISSUE THREAD

**Issue by qingkaikong** [python-visualization/folium#415]
Sorry to bother. 

If I want to make a circlemarker with fixed distance as radius, say, 10 km. How can I convert the distance to pixel for the radius argument for each zoom in level.  Thanks.

**Comment by chdean** [comment]
You actually don't need to convert the distance to pixels.  folium.CircleMarker() takes a radius in meters.

See the example in the quickstart docs: https://folium.readthedocs.org/en/latest/quickstart.html

**Comment by qingkaikong** [comment]
Ok, now I see, it seems CircleMaker is bounding to leaflet.circle which radius is in unit of meters right now, see issue #339

**Comment by existeundelta** [comment]
I think its open in dev version
