### ISSUE TITLE
Add a script version of MarkerCluster to speedup creating many markers. 

### ISSUE THREAD

**Issue by ruoyu0088** [python-visualization/folium#416]
For example following code costs 5 seconds to add 1000 markers:

```
import folium
import numpy as np
from folium.plugins import MarkerCluster
N = 1000
fig = folium.element.Figure()
map_ = folium.Map(location=[20, 50], zoom_start=3)
cluster = MarkerCluster(np.random.uniform(0, 90, (N, 2))).add_to(map_)
map_.add_to(fig)
```

and the output html contains code for 1000 markers.

I  tried a Javascript version to speedup this:

```
class MarkerClusterScript(MarkerCluster):
    def __init__(self, data, callback):
        from jinja2 import Template
        super(MarkerClusterScript, self).__init__([])
        self._name = 'Script'
        self._data = data
        if callable(callback):
            from flexx.pyscript import py2js
            self._callback =  py2js(callback, new_name="callback")
        else:
            self._callback = "var callback = {};".format(_callback)

        self._template = Template(u"""
{% macro script(this, kwargs) %}
(function(){
    var data = {{this._data}};
    var map = {{this._parent.get_name()}};
    var cluster = L.markerClusterGroup();
    {{this._callback}}

    for (var i = 0; i < data.length; i++) {
        var row = data[i];
        var marker = callback(row);
        marker.addTo(cluster);
    }

    cluster.addTo(map);
})();
{% endmacro %}
            """)
```

and then create the map by

```
import pandas as pd
N = 1000
df = pd.DataFrame(np.random.uniform(0, 90, (N, 2)), columns=list("xy"))
df["color"] = np.random.choice(["red", "green", "blue"], N)

fig = folium.element.Figure()
map_ = folium.Map(location=[20, 50], zoom_start=3)

def create_marker(row):
    icon = L.AwesomeMarkers.icon({markerColor: row.color})    
    marker = L.marker(L.LatLng(row.x, row.y))
    marker.setIcon(icon)
    return marker

MarkerClusterScript(df.to_json(orient="records"), callback=create_marker).add_to(map_)
map_.add_to(fig)
```

It only takes 0.3 seconds. All the data are saved in a javascript array, and the for-loop for creating markers occured in web brower. 

I suggest to add this kind of Classes for speedup.

**Comment by ocefpaf** [comment]
@ruoyu0088 thanks for the suggestion! Feel free to send a PR addressing that. Right now we are focusing on fixing bugs and cleaning the code for a new release. Optimizations are not high priority.

**Comment by eddies** [comment]
@ruoyu0088 that would be brilliant. I only just realized last week when trying to plot > 5000 markers how slow it could be.

**Comment by BibMartin** [comment]
### generalities

I'm okay with @ocefpaf on: 
> Optimizations are not high priority.

In fact, folum's goal is to provide a simple way of creating maps. For that, we need to introduce a kind of modularity that often prevent optimisations.

People asking for optimisation have to take the effort of going into javascript, or write their custom class (as you did).

### in that particular case

In the particular case of `MarkerCluster` we've chosen the current implementation because it enables you to tune the markers when adding them one after the other. I can (for example) do a MarkerCluster combining different markers, with different shapes/colors/popups, etc.

**But I agree this does not address everyone's need and it would worth having a second MarkerCluster object** for people who wants to go faster. So **please make a PR**.

Instead of `MarkerClusterScript`, I would suggest to name it `FastMarkerCluster`.

btw : I really like the way you've implemented it (with the callback).

**Comment by JamesGardiner** [comment]
@ruoyu0088 your class was incredibly useful for plotting 25,000+ points globally http://nbviewer.jupyter.org/gist/anonymous/33f38b09ad3bfa277e2d9c06e4bb588c

**Comment by ocefpaf** [comment]
Cool use case @JamesGardiner. If @ruoyu0088 does not mind maybe you could send the `FastMarkerCluster` PR suggested in https://github.com/python-visualization/folium/issues/416#issuecomment-209361066. (With the proper credits to @ruoyu0088 of course!)

**Comment by HFulcher** [comment]
Relating to this issue I have approx 147k points I want to add to a map. I realise this is a very large amount but it would be useful if I could have an update on whether there is an efficient way of placing these markers on the map as clusters. Currently the standard way takes a long time (understandably). Thanks

**Comment by ryanbaumann** [comment]
@hamesgardiner the geojson-vt utility in Mapbox gl-js is pretty powerful.  I'm starting work to add Folium support for GL maps - in the meantime have a look at the Mapbox GL JS SDK!

**Comment by JamesGardiner** [comment]
Have had a chance to look at this recently - I've got the FasterMarkerCluster script suggested by @ruoyu0088 working but need to make a few more changes. I'd like to avoid depending on [flexx.pyscript.py2js](http://flexx.readthedocs.io/en/stable/pyscript/api.html#flexx.pyscript.py2js) (which itself depends on Tornado) and construct the callback using Jinja alone. Should be easily done though. Hope to issue a pull request this weekend.

**Comment by leblancfg** [comment]
Sorry for referencing a closed issue, but this is way above my Javascript capacities. Would there be an easy way at all for markers created using FastMarkerClusters to have popups as well?

**Comment by bukowa** [comment]
@leblancfg did you find the solution?

**Comment by leblancfg** [comment]
I ended up following what @JamesGardiner had done in the [notebook he linked to previously](http://nbviewer.jupyter.org/gist/anonymous/33f38b09ad3bfa277e2d9c06e4bb588c):

```python
# nan values throw the JS script
# Popups with name strings
popups = df.name[df.lng.notnull()].values

# Latitude and longitude dataframe with no nan values
locations = [list(a) for a in zip(lat, lng, popups)]
df_locations = pd.DataFrame(locations, columns=['lat', 'lng', 'names'])

fig = folium.element.Figure()
map_orgs = folium.Map(location=[56, -3], zoom_start=5)
MarkerClusterScript(df_locations.to_json(orient="records"), callback=create_marker).add_to(map_orgs)
map_orgs.add_to(fig)
```

The main dataset I work with has ~8k locations, and it works all right.

**Comment by pieterjoanUvA** [comment]
I created an ugly hack to the FastMarkerCluster, it has serious oddities,
but now I can create custom popups for all my markers,
BUT if you don't supply the extra list, a coordinate will be the label.
The JSparser has something I do not fully grasp. 
(also tried the code above, and that does not function in folium 0.7 )

`# -*- coding: utf-8 -*-

from __future__ import (absolute_import, division, print_function)

from folium.plugins.marker_cluster import MarkerCluster
from folium.utilities import _validate_coordinates

from jinja2 import Template


class FasterMarkerCluster(MarkerCluster):
    """
    Add marker clusters to a map using in-browser rendering.
    Using FastMarkerCluster it is possible to render 000's of
    points far quicker than the MarkerCluster class.
    Be aware that the FastMarkerCluster class passes an empty
    list to the parent class' __init__ method during initialisation.
    This means that the add_child method is never called, and
    no reference to any marker data are retained. Methods such
    as get_bounds() are therefore not available when using it.
    Parameters
    ----------
    data: list
        List of list of shape [[], []]. Data points should be of
        the form [[lat, lng]].
    callback: string, default None
        A string representation of a valid Javascript function
        that will be passed a lat, lon coordinate pair. See the
        FasterMarkerCluster for an example of a custom callback.
    name : string, default None
        The name of the Layer, as it will appear in LayerControls.
    overlay : bool, default True
        Adds the layer as an optional overlay (True) or the base layer (False).
    control : bool, default True
        Whether the Layer will be included in LayerControls.
    show: bool, default True
        Whether the layer will be shown on opening (only for overlays).
    options : dict, default None
        A dictionary with options for Leaflet.markercluster. See
        https://github.com/Leaflet/Leaflet.markercluster for options.
    """
    _template = Template(u"""
            {% macro script(this, kwargs) %}
            var {{ this.get_name() }} = (function(){
                {{this._callback}}
                var data = {{ this._data }};
                var popup = {{ this._popup }};
                var cluster = L.markerClusterGroup({{ this.options }});
                for (var i = 0; i < popup.length; i++) {
                    var row = data[i];
                    var marker = callback(row);
                    var row2 = popup[i];
                    marker.bindPopup("<h4>"+popup[i]+ "<h4> ");
                    marker.addTo(cluster);
                }
                cluster.addTo({{ this._parent.get_name() }});
                return cluster;
            })();
            {% endmacro %}""")

    def __init__(self, data, callback=None, options=None,
                 name=None, overlay=True, control=True, show=True):
        
        super(FasterMarkerCluster, self).__init__(name=name, overlay=overlay,
                                                control=control, show=show,
                                                options=options)
        namesrow = data[:]
        data = [row[0:2] for row in data]
        self._name = 'FasterMarkerCluster'
        self._data = _validate_coordinates(data)
        self._popup = namesrow
        #print(self._popup)
        #data = namesrow[:]
        if callback is None:
            self._callback = """
                var callback = function (row) {
                    var icon = L.AwesomeMarkers.icon();
                    var marker = L.marker(new L.LatLng(row[0], row[1]));
                    marker.setIcon(icon);
                    return marker;
                };"""
        else:
            self._callback = 'var callback = {};'.format(callback)`

with the finlist and call to this class:  

`finlist = []
for label,label2,dayname,timeofday in zip(df1['Incident Subcategory']\
                                 ,df1['Incident Description'], df1['Incident Datetime'].dt.day_name()\
                                , df1['timeofday']):

    labelfinal ='<h4>'+ label+'</h4><h6>'+label2+'</h6>on a  : <i>'+dayname+'</i> during <b>'+timeofday+'</b>'
    finlist.append(labelfinal)

    
FasterMarkerCluster(data=list(zip(df1.Latitude, df1.Longitude, finlist)),
                 #callback=callback  
                 ).add_to(sanfran_map)`

just my try to fix this. and it works for my purposes .... :-)

**Comment by SamPse** [comment]
is it possible to use a custom icon as a parameter in the function 
`def create_marker(row):
    icon = L.AwesomeMarkers.icon({markerColor: row.color})    
    marker = L.marker(L.LatLng(row.x, row.y))
    marker.setIcon(icon)
    return marker

MarkerClusterScript(df.to_json(orient="records"), callback=create_marker).add_to(map_)
map_.add_to(fig)`
thank you
