### ISSUE TITLE
Continuous colorscale for choropleth

### ISSUE THREAD

**Issue by blauwepiet** [python-visualization/folium#418]
Hey folium devs, first off, thanks for this awesome and easy to use Leaflet wrapper.

One thing I miss though is a continuous colorscale for Choropleths. Is there a reason why the colorscales have only 6 color values instead of a continuous range? and is there a plan to implement it?

Kind regards,

Casper

**Comment by BibMartin** [comment]
Good point @blauwepiet !
In fact we have been working on it and have a solution combinig folium and [branca](https://github.com/python-visualization/branca), but it's not released yet.

You can checkout an example [**here**](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Colormaps.ipynb).

**Comment by BibMartin** [comment]
Sorry, I am wrong.

In fact you can already use `colormap` with folium `v0.2.1`. See [**here**](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/v0.2.1/examples/Colormaps.ipynb).

**Comment by blauwepiet** [comment]
ah, excellent, exactly what i needed!

Thanks for the examples!

**Comment by kevinmangold** [comment]
All of these examples use GeoJson, not Choropleth. How do you use continuous coloring for Choropleths?

**Comment by FilippoMB** [comment]
it seems there is an argument "bins" that accepts either a list of bins or an integer that specifies the number of bins:

m = folium.Map(tiles="Mapbox Control Room")
folium.Choropleth(
    geo_data=country_shapes,
    name='choropleth',
    data=df_clust,
    columns=['Country', 'Cluster'],
    key_on='feature.properties.name',
    fill_color='Paired',
    nan_fill_color='white',
    **bins=11,**
).add_to(m)
