### ISSUE TITLE
Remove the embedded IFrame's ugly border

### ISSUE THREAD

**Issue by deelaka** [python-visualization/folium#423]
For [example ](http://nbviewer.jupyter.org/github/bibmartin/folium/blob/issue288/examples/Popups.ipynb#Fancy-HTML-popup) when opening a popup with html, There is a ugly border around the html wrapped in the IFrame. How to remove this for the time being? 

In the meantime I suggest a method to add styling to the `IFrame` element. Furthermore in my opinion, custom html should not even be wrapped in a IFrame in the first place...

**Comment by erccarls** [comment]
Seconded.... This looks terrible, but the rest looks soooo good!

**Comment by ocefpaf** [comment]
The `IFrame` is part of [branca](https://github.com/python-visualization/branca) now. You should open an issue there.

Or better yet open a PR to fix it :smile:

I believe [this](https://github.com/python-visualization/branca/blob/1096b917755ddbfa1e0a379217fa63c5bb0e8b52/branca/element.py#L314-L330) is the relevant code part.
