### ISSUE TITLE
Choropleth slivers at low zoom levels

### ISSUE THREAD

**Issue by JamesGardiner** [python-visualization/folium#427]
When using the `Map.choropleth` method my output has slivers present between features. See http://nbviewer.jupyter.org/gist/anonymous/1b85bccb47ea6a418591ef27c3f2bc5e for an example.

I've put this down to Leaflet applying a smoothing algorithm to the features as per http://gis.stackexchange.com/questions/143449/geojson-rendering-in-leaflet.

Adding `{smoothFactor: 0}` (a `PolyLine` option) to `L.geoJson` removes these from the map at all zoom levels. I can't see a way to use this with the current `Map.choropleth` method. Am I missing something? 

From what I can see, I could accomplish this using the `GeoJson` class and a style function as a workaround for now.

**Comment by ocefpaf** [comment]
>  I can't see a way to use this with the current Map.choropleth method. Am I missing something?

That can probably be added as an extra option in the `GeoJson` method. Are you interested in sending a PR for that?

**Comment by JamesGardiner** [comment]
@ocefpaf yep, happy to look into it; I'll send a PR across when I get chance.

**Comment by ocefpaf** [comment]
Closed by #428
