### ISSUE TITLE
Nested Feature Groups

### ISSUE THREAD

**Issue by mrichar1** [python-visualization/folium#429]
I'm currently investigating whether or not it would be possible to create nested feature groups, for example to place markers on a map divided by year, and then divided again by month.

I've tried experimenting with something like:

``` python

year = folium.FeatureGroup(name='2015')
month = folium.FeatureGroup(name='Jan')
month.add_child(folium.Marker([x, y])
year.add_child(month)
map.add_child(year)
map.add_child(folium.map.LayerControl())
```

But this doesn't seem to work - you only get the year on the layer control, though it does contain the marker associated with the month.

Is there a different way of doing this, or is it just not possible with Feature Groups?

EDIT: I've just realised I should have looked at leaflet.js first, and it appears that their featuregroup implementation doesn't support this... feel free to just close this issue if I should bump it up to Leaflet.js. (unless of course you know of an alternative way to achieve this!)

**Comment by ocefpaf** [comment]
> (unless of course you know of an alternative way to achieve this!)

Sorry. No ideas on how to work around to implement this.
