### ISSUE TITLE
CircleMarker line_color not recognised

### ISSUE THREAD

**Issue by JoshuaC3** [python-visualization/folium#430]
It seems since the change from a the function (circlemarker) to a class def (CircleMarker) it has dropped the line_color attribute.

**Comment by AmandaOlson** [comment]
Looks like the issue still hasn't been fixed.

**Comment by ocefpaf** [comment]
I won't be able to look at this within 1-2 weeks. But I can review a PR if any of you are interested into fixing it.

**Comment by ocefpaf** [comment]
Closing as duplicated of the more general #524 (A possible solution is #683)
