### ISSUE TITLE
Plot matplotlib object on folium

### ISSUE THREAD

**Issue by qingkaikong** [python-visualization/folium#432]
Is there any way I can plot matplotlib object on folium. The problem is, I usually plot objects on Basemap, since now I am using more and more folium, I am wandering if there's an easy way I can plot that on folium. An example is from [Here](http://docs.obspy.org/tutorial/code_snippets/basemap_plot_with_beachballs.html), the beachball is the circle with shade on some part of it, I can save them first to png, and then add them as an icon on the folium map, but this usually make things relatively complicate, so if there's way to plot directly on folium map, it will be really great!

Thanks.

**Comment by ocefpaf** [comment]
You can try `mplleaflet` to convert the `matplotlib` objects to `JSON` or `SVG`. Note that `mplleaft` already generate a slippy map for you, but you can save the object in the middle and use it in `folium` too.

Here is an example: https://ocefpaf.github.io/python4oceanographers/blog/2015/11/16/folium_quiver/

**Comment by qingkaikong** [comment]
Great, thanks for the tips!
