### ISSUE TITLE
ImageOverlay moves with higher zoom level

### ISSUE THREAD

**Issue by mccarthyryanc** [python-visualization/folium#433]
At a really high zoom level, the image with change position. Behavior is visible in examples:
http://nbviewer.jupyter.org/github/ocefpaf/folium_notebooks/blob/master/test_image_overlay_gulf_stream.ipynb

Easiest to see the behavior when zooming into the coastline in the first map.

**Comment by ocefpaf** [comment]
I am not sure there is anything we can do to solve that. Ideally we should re-project new image at every-level, like the tiles, but that is unfeasible for such a simple method.  Thanks for the report but I am, sadly, closing this as a won't fix.

**Comment by mccarthyryanc** [comment]
Understood. I am new to Leaflet/folium and after some reading I completely agree. However, if anyone manages to stumble onto this issue, I managed to get what I wanted by using the [Leaflet.ImageOverlay.Rotated](https://github.com/IvanSanchez/Leaflet.ImageOverlay.Rotated) plugin. It might be a bit overkill as I didn't need the rotation feature, but it worked.

**Comment by ocefpaf** [comment]
Cool. Are you interested in add that plugin to `folium` :wink: ? Take a look at some of the [current](https://github.com/python-visualization/folium/blob/master/folium/plugins/terminator.py) plugins as a starter point.
