### ISSUE TITLE
timestamped_geojson won't work in chrome

### ISSUE THREAD

**Issue by sanga** [python-visualization/folium#434]
I get this:

`Refused to execute script from 'https://raw.githubusercontent.com/nezasa/iso8601-js-period/master/iso8601.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`

Which seems kinda reasonable to me. Would it not be safer to vendor the minified js into folium?

**Comment by ocefpaf** [comment]
Thanks for the report. I will take a look at some alternatives.

**Comment by sanga** [comment]
I haven't tested, but I'm guessing that "chrome" probably means any modern browser, as, from what I read, github is now passing a header that causes modern browsers to not load a file with mimetype text as js.

**Comment by sanga** [comment]
https://github.com/python-visualization/folium/pull/440 Fixed this
