### ISSUE TITLE
undeclared dependency on branca?

### ISSUE THREAD

**Issue by sanga** [python-visualization/folium#435]
I cloned master to fix a bug but installing a local version of folium didn't work for me. It rather complained that branca wasn't installed. And actually I can't see where the dependency on branca is declared...

I'd have expected branca to appear in either setup.py or requirements.txt, but I don't see it there. Having said that installing from pypi works. What's going on here?

**Comment by ocefpaf** [comment]
> Having said that installing from pypi works. What's going on here?

Master is a dev version and PyPI a stable release. So things like that are expected to happen in master, but if they happen on a release it is a must-fix-right-away bug :wink:

We don't even have a branca official release BTW. (Ping/nudge @BibMartin :grin:)

**Comment by sanga** [comment]
Perhaps I misunderstand but there is a branca release right?

https://pypi.python.org/pypi/branca/0.1.1

The thing that seems to be missing to me, is that folium master doesn't say it depends on branca

**Comment by ocefpaf** [comment]
Yeah. I forgot that one. Still, we don't have an official release of folium that uses that. If you wish to run master you will run into this sort of issues. Your best bet us to check our travis config to figure out the best way to run master. (or send A PR updating the req file ;-)

**Comment by michaeljs1990** [comment]
What is an official release? I am using your 0.2.1 tag and still have this issue. Do your tagged releases not represent stable versions?

**Comment by ocefpaf** [comment]
>
> What is an official release(what branch/tag)?
>
All those that are versioned.

> I am using your 0.2.1 tag and still have this issue.
>
Let's see.

```shell
wget https://github.com/python-visualization/folium/archive/v0.2.1.tar.gz
extract v0.2.1.tar.gz
find . -type f -name "*.py" -exec grep "branca" '{}' \; -print
```

Nope. I cannot see any use of branca in that release. Can you point me to
what branch you are using?

> Do your tagged releases not represent stable versions?
>

They do.

**Comment by ocefpaf** [comment]
OK. I guess Michael Schuett deleted the original message. Maybe the issue was resolved while I wrote the answer :smile:

**Comment by michaeljs1990** [comment]
Yeah it was just my confusion when I was running the software. I thought I had a tag checked out when I didn't. Sorry about that.
