### ISSUE TITLE
MarkerCluster with Layers

### ISSUE THREAD

**Issue by yeffel** [python-visualization/folium#438]
I wanted to see if someone had an example of leaflet markers that are Clustered and also layered.

For example.  A map with 1000 points clusters, but a layer to turn on and off a FeatureGroup.

So I guess asked another way can one Cluster a Feature Group?

**Comment by ocefpaf** [comment]
@yeffel take a look at this example: https://ocefpaf.github.io/python4oceanographers/blog/2015/12/14/geopandas_folium/

**Comment by yeffel** [comment]
Great this did the trick.

My follow up question, and sorry if this is not the correct forum to ask.

I'm using a Mapbox map.  And the LayerControl includes the long URL to my Mapbox tileset.

I looked at the LayerControl code: and wanted to see if there is a way to change the long URL to just mapbox?


 {% macro script(this,kwargs) %}
            var {{this.get_name()}} = {
                base_layers : { {% for key,val in this.base_layers.items() %}"{{key}}" : {{val}},{% endfor %} },
    
                overlays : { {% for key,val in this.overlays.items() %}"{{key}}" : {{val}},{% endfor %} }
                };
            L.control.layers(
                {{this.get_name()}}.base_layers,
                {{this.get_name()}}.overlays
                ).addTo({{this._parent.get_name()}});
        {% endmacro %}

**Comment by ocefpaf** [comment]
> Great this did the trick.

:+1: 

> My follow up question, and sorry if this is not the correct forum to ask.

It is. We don't really have a forum/mailing list (and we are slow to respond), but GitHub and [gitter](https://gitter.im/python-visualization/folium) are the right places to ask.

> I looked at the LayerControl code: and wanted to see if there is a way to change the long URL to just mapbox?

Not sure what you mean by tileset... Is that the layer name? We can certainly improve that part of the code. (I believe we have a standing bug on changing the layer name BTW that needs to be addressed. Are you interested in sending a PR? :wink: )
