### ISSUE TITLE
PolyLine problem when take the longitude negative

### ISSUE THREAD

**Issue by qingkaikong** [python-visualization/folium#439]
I try to plot the tectonic plate boundary on the folium map using the PolyLine, but it seems folium doesn't handle the longitude well at -180 degree and 180 degree, see the following examples, it plot a direct line across the whole map. 

<img width="852" alt="example" src="https://cloud.githubusercontent.com/assets/1621324/15659552/59a8404c-2681-11e6-95c1-2551344bf5d5.png">

**Comment by ocefpaf** [comment]
That is a leaflet issue that folium does not fix. There are a few tricks to prepare your data before plotting to avoid it. See http://nbviewer.jupyter.org/github/ocefpaf/folium_notebooks/blob/master/test_lines.ipynb

PS: If you can find an elegant and simple way to circumvent that problem please send a PR our way :wink:

**Comment by qingkaikong** [comment]
Yeah, it is a problem, but seems Cartopy handles this problem very well:
![plate_boundary](https://cloud.githubusercontent.com/assets/1621324/15660434/51d41f7a-2691-11e6-8aa1-9ff9db1e4fe6.png)

import cartopy.crs as ccrs
import cartopy.feature as cfeature

fig, ax = plt.subplots(figsize=(10, 8), subplot_kw=dict(projection=ccrs.Robinson()))
ax.set_global()
ax.coastlines(resolution='110m', color='k')
ax.add_feature(cfeature.LAND, facecolor='0.75')

lat = coordinates[:, 0]
lon = coordinates[:, 1]
_ = ax.plot(lon, lat, transform=ccrs.Geodetic(), color = 'b')
plt.show()

Need see if I can come up with some better ways in folium to plot it.

**Comment by ocefpaf** [comment]
Closing this as this must be fixed in leaflet. :unamused:

**Comment by rutgerhofste** [comment]
https://github.com/Fragger/Leaflet.Geodesic
