### ISSUE TITLE
Heatmap with Time Dimension

### ISSUE THREAD

**Issue by FlorianHoevelmann** [python-visualization/folium#441]
Hey, 

I'm currently trying to create a Heatmap with a time dimension as shown in this [example](http://apps.socib.es/Leaflet.TimeDimension/examples/example12.html).
I managed to create a Heatmap with different Layers for each day as a workaround but it would be awesome to have a time bar rather than selecting each day manually.
I know that you already implemented the TimestampedGeoJson function but i wasn't able to use it with Heatmaps instead of just points on the map.  

Thanks for your help and by the way folium is a very helpfull python package.

Regards, 

Florian

**Comment by ocefpaf** [comment]
@FlorianHoevelmann folium needs a lot of work to wrap of the functionalities in `Leaflet.TimeDimension`. I don't think what you want to do is possible yet. I will leave this issue open in case someone wants to implement this.

**Comment by Padarn** [comment]
@ocefpaf I'd be interested in helping to add this, partly because I want it, and partly because I want to learn the library better. Is there someone on the team I could get in contact with to get an outline of what needs doing so I have a bit of direction as I dig in?

**Comment by ocefpaf** [comment]
> @ocefpaf I'd be interested in helping to add this, partly because I want it, and partly because I want to learn the library better.

Awesome!

>  Is there someone on the team I could get in contact with to get an outline of what needs doing so I have a bit of direction as I dig in?

The best guy would be @BibMartin, but he is quite busy with his day job.

I would start by reading the docs and examples from https://github.com/socib/Leaflet.TimeDimension

We usually do the inverse approach. First we set a minimum HTML example and then code the Python part that produces it.

**Comment by Padarn** [comment]
Thanks. I've been digging around the code/docs already, but it is always good to have some goal in mind too :-)

> We usually do the inverse approach. First we set a minimum HTML example and then code the Python part that produces it.

You mean directly using Leaflet right? This seems sensible, do you have any examples of 'minimum HTML' you've used in the past? (just as a guide to complexity)

**Comment by BibMartin** [comment]
> @ocefpaf I'd be interested in helping to add this

Great ! Thanks @Padarn for future efforts.

I have tried to work with `Leaflet.Timesdimension` and must admit it's not that easy.
I'll try to investigate also on how we could do this.

A few hints:

* We have a plugin (almost working) to draw features with timedimension : [timestamped_geo_json plugin](https://github.com/python-visualization/folium/blob/master/folium/plugins/timestamped_geo_json.py)
* It's use is illustrated in an [old gist](http://nbviewer.jupyter.org/gist/BibMartin/df0e61615e9dec1e55c9b1eff9bcb1a4)
* I would suggest an API like :

```python
data = [
    [[40, 3], [41, 3], [42, 3], [44, 3]],  # data for time 0
    [[40, 4], [41, 4], [42, 4], [44, 4]],  # data for time 1
    [[40, 5], [41, 5], [42, 5], [44, 5]],  # data for time 2
    ]
index = ["2016-01-01", "2016-02-01", "2016-03-01"]

folium.plugins.TDHeatmap(data, index=index).add_to(map)
```

**Comment by Padarn** [comment]
Thanks for the tips @BibMartin. Hopefully I haven't bitten off more than I can chew for a first go, but I'll see where I get to.

**Comment by BibMartin** [comment]
Hi @Padarn 

I finally found a way to use Timedimension offline, in a way that seem to be *foliumizable*.

Here is the [gist](https://gist.github.com/BibMartin/2c042c777e4bcd3f3445225f0257e901) and here is the [demo](http://bl.ocks.org/bibmartin/raw/2c042c777e4bcd3f3445225f0257e901/)

Do you want to go on creating the plugin that binds this code into python ?

**Comment by Padarn** [comment]
@BibMartin great! Yes I'll go ahead and try to make the plugin - this makes my first contribution much less painful :-)

**Comment by Padarn** [comment]
I've started on this, initial PR here:

https://github.com/python-visualization/folium/pull/567

I've included a small example (but it doesn't render in github)

https://github.com/Padarn/folium/blob/HeatMapWithTime/examples/HeatMapWithTime%20example.ipynb

Still plenty of cleaning up to add, and making the options a bit more sensible etc, but any initial feedback appreciated.

**Comment by ocefpaf** [comment]
@Padarn Awesome work. I will try to review it soon. BTW you can use nbviewer for a rendered version that works: http://nbviewer.jupyter.org/github/Padarn/folium/blob/HeatMapWithTime/examples/HeatMapWithTime%20example.ipynb

**Comment by easherma** [comment]
This looks really promising, any updates?

**Comment by ocefpaf** [comment]
Implemented in #567

**Comment by mas-dse-greina** [comment]
I'm having trouble seeing anything at all in the current version. When I do a normal heatmap it shows up just fine, but the heatmap with time doesn't show any points at all.

```
from folium.plugins import HeatMap, HeatMapWithTime

m = folium.Map([35., -118.5], tiles='stamentoner', zoom_start=5)

#HeatMap(data).add_to(m)

HeatMapWithTime(data, index=list(dfMerged["Year"].values)).add_to(m)
m.save('Heatmap.html')

m

```

**Comment by mingmaocity** [comment]
In HeatMapWithTime, how can display the difference between the points which have different numbers,such as Point A with 1000 and Point B with 5000?

**Comment by mingmaocity** [comment]
In HeatMapWithTime,how can display the difference between the points which have different numbers,such as Point A with 1000 and Point B with 5000?
