### ISSUE TITLE
Problem rendering IFrame on popups

### ISSUE THREAD

**Issue by LuiCotias** [python-visualization/folium#443]
Hi guys! Thank you so much for Folium! It's amazing! I'm trying the HTML Popup example from Popup notebook on master examples, but all that i get is an empty popup. 
![popup_example](https://cloud.githubusercontent.com/assets/5043220/15834477/10ac046a-2c02-11e6-83a9-3b0e2bcf4b7b.png)

<code>branca.__version__</code>
           '0.1.1'

Any idea? I already tried the downgrade to Folium 0.2.0, as in the example uses, but it didn't work anyway.
I'm using Python 3.4.2,  Debian Jessie 8.4.

Thanks for your attention!

**Comment by ocefpaf** [comment]
`folium 0.2.1` (which is the latest one available at PyPI) does not use `branca`! Branca will be used in `folium 0.3` (which is no released).

See a working version of your example [here](http://nbviewer.jupyter.org/gist/ocefpaf/cc24553055569783c9c813ced6b93018).

**Comment by jboynyc** [comment]
I had the same issue. This is confusing, because the 0.2.x docs [link to](https://folium.readthedocs.io/en/latest/examples.html) the examples that only work with the new 0.3.x branch. It would be helpful to put a big fat warning in the documentation.
