### ISSUE TITLE
Could you add a time slider function on Folium

### ISSUE THREAD

**Issue by xhx509** [python-visualization/folium#444]
Hi:
I am considering Folium for a while. I hope to show tracks on the map with time slider, so I can figure out where I am at specified time. 

That is very important to me. Could you add a time slider function to  Folium?

Thanks a lot!

Xavier

**Comment by ocefpaf** [comment]
A time slider would be an awesome addition. Unfortunately all of our devs are volunteers who try to improve folium during their spare time, so don't hold your breath waiting for it. (Unless you want to send a PR :wink:)

**Comment by ocefpaf** [comment]
That supported in a way via the Time Stamped GeoJSON and WMS. Closing this b/c a general time slider is not something easy to implement and we should address it on a case-by-case basis. Take a look at the time stamped functionality we have an let me know if that works for you.

**Comment by xhx509** [comment]
That's  great!

Thank you.

Xavier
