### ISSUE TITLE
Feature request: add simple markers to map

### ISSUE THREAD

**Issue by tomderuijter** [python-visualization/folium#445]
Folium is one of the best libraries out there for no-nonsense plotting of geospatial data in Python. A feature my colleagues and I are currently missing very much is the option to plot a simple coloured marker on a map. Example:

[<img src="http://s33.postimg.org/nwwe9rfnz/Screen_Shot_2016_06_09_at_12_42_36.png">](http://www.gpsvisualizer.com/examples/hawaii_earthquakes_20061015.html)

The current option for markers don't suffice as they are large, poorly customisable and plotting more than 100 at a time clutters the map and makes the plotting window grind to a halt.

**Comment by ocefpaf** [comment]
There is no direct support for that in `folium` b/c `folium` tries to be a `leaflet` wrapper. You have to options:

1) find a `leaflet` plugin that does that and implement it on `folium`
2) create a GeoJSON with that as a feature and plot in `folium`

To create the GeoJSON you can use `mplleaflet` and, if the scatter plot is all you want, you don't even need `folium`, but if you need some extra features just save the GeoJSON from `mplleaflet` and re-plot it on `folium`. Here is an example:

https://ocefpaf.github.io/python4oceanographers/blog/2015/11/16/folium_quiver/

(Warning: some GeoJSON hacking might be required.)

**Comment by BibMartin** [comment]
@tomderuijter Here is an [example on how to do it.](http://nbviewer.jupyter.org/github/bibmartin/folium_notebooks/blob/feature%2Fscatter_plot/test_scatter_plot.ipynb)

If you find something to simplify, please feel free to suggest an improvement.

**Comment by ocefpaf** [comment]
Ah ha! Forgot about CircleMarker!! Awesome example @BibMartin!!!

**Comment by tomderuijter** [comment]
Thanks all. I didn't directly link scatter plots to map markers.
