### ISSUE TITLE
Add FeatureGroups to LayerControl without adding to map / remove elements

### ISSUE THREAD

**Issue by omrihar** [python-visualization/folium#453]
First of all, I'd like to say I really really like what you're doing with `folium`. It really feels like magic, especially when working with it in Jupyter. 
What I didn't really find a way to do is the following: I'm adding multiple Markers (actually Circles) to a map which correspond to different times. I want to have an easy way of only showing one layer at a time. What I currently do is add a layer for each time point and use a LayerControl. The problem is that I can't seem to find a way to add the FeatureGroups to a layer control without adding it to the map first, so that the initial map will only show one of these FeatureGroups and then let the user be able to tick whichever they want to see.

Alternatively (perhaps preferably) I could use the interactive html widget in Jupyter. The problem is that while it is possible to add a marker in multiple ways, I couldn't find any way to interactively _remove_ a marker. I also looked through the branca code where there is only add_child / add_to but no remove. I even tried deleting directly from _children but it seems to have no effect on the drawn map.

I would appreciate any help - perhaps I missed something basic in how this works...

**Comment by BibMartin** [comment]
In fact `folium` lets you create a web page (HTML+CSS+JS) based on python ; but you cannot interact with that webpage through python. You have to do Javascript to make your map interactive.

At the moment, there a two track I can suggest to you:

* [**TimestampedGeoJson**](http://nbviewer.jupyter.org/gist/BibMartin/df0e61615e9dec1e55c9b1eff9bcb1a4) that is a (buggy) plugin of folium, but can give you some results after a few hacks. (it seems to work only with firefox).

* [**crossfolium**](https://github.com/bibmartin/crossfolium) that is a separate library (and very prototype).

I hope it will help :wink:

**Comment by omrihar** [comment]
Thanks! I was actually thinking quite a lot about using `crossfilter` with python projects, especially together with `dc.js`. Your `crossfolium` does indeed look very nice! 
I have been trying to implement the time dependence of my map layers in javascript within Jupyter (using `%%javascript` cells and `require.js` to load `d3` and `leaflet`) but came across some bugs (one of the map tiles in leaflet was not well aligned with all the rest) so I dropped it and decided to keep using `folium`.

An unrelated question but I hope you might be willing to help me with that - do you know of a canonical way (or project / widget / magic) to load javascript and css into a jupyter `%%javascript` cell easily. Ideally a cell would look something like this:

```javascript
%%javscript

// load libraries
load_css(['path to first css file', 'path to second css file', ...]);
load_js(['path to library 1', 'path to library 2', ...]);
```

and the css files  will simply be loaded into the head and the javascript files will be loaded and bound to the global scope (if not yet loaded)?

Thanks again,
Omri
