### ISSUE TITLE
Legend for categorical data

### ISSUE THREAD

**Issue by lalessan** [python-visualization/folium#454]
Hi, 

Thank you a lot for your work.
I am working with categorical data and I created a choropleth using a self-defined style-function. Is there a way to have a colorbar (or an other type of legend) where ticks are not floats but strings?

Thank you, 
Laura

**Comment by ocefpaf** [comment]
I am afraid there is no easy way to do that right now. (Glad to be proven wrong with a PR :wink:)

**Comment by simogeo** [comment]
I have no time to work on that, but would be happy to contribute in a way with the tiny geostats library I coded : https://github.com/simogeo/geostats/

Samples available on : http://www.intermezzo-coop.eu/mapping/geostats/

**Comment by lalessan** [comment]
Thank you. I'll try that!

**Comment by ocefpaf** [comment]
Closing this as stale. We would still take a PR to easily add legends but that is not a priority at the moment.
