### ISSUE TITLE
Map not displaying

### ISSUE THREAD

**Issue by kitman0804** [python-visualization/folium#455]
The map does not display in the browser, instead it return

`<folium.folium.Map object at 0x000002556A104080>`

To display the map, I need to save and open it manually. Is it normal?

**Comment by ocefpaf** [comment]
Hi @kitman0804 that is the object as expected, if you are in a Jupyter Notebook you should see the map via its rich display. If you are not on Jupyter you need to save the HTML and serve it to browser the map.

**Comment by Demetrio92** [comment]
I have a quick and dirty solution here: https://github.com/python-visualization/folium/issues/946#issuecomment-417272388
