### ISSUE TITLE
change map location after creating?

### ISSUE THREAD

**Issue by tom-spalding** [python-visualization/folium#46]
Steps: create a map with location, add a few markers, but then take the center of all the markers, and recenter the map?

```
map = folium.Map(location=[lat,lon],zoom_start=15)
#do this a few times
map.circle_marker(location=[lat,lon],radius=acc,popup=creature,line_color='#3186cc',fill_color='#3186cc')
lat_mid = (lat_min+lat_max)/2
lon_mid = (lon_min+lon_max)/2
print('{0},{1}'.format(lat_mid,lon_mid))
#set to middle point
#how do i reset the location?
#map_rr ____?____(location=[lat_mid,lon_mid],zoom_start=14)
```

**Comment by themiurgo** [comment]
Leaflet has a fitBounds method to accomplish this. It would be great to integrate it into folium, so that the map is redrawn to include every object or a group of them.

**Comment by birdage** [comment]
@themiurgo i agree, i thought there was a method to reset the location? ive always know the location when ive created the map, but it would be helpful not having to do that, and to just call a function to do it for you!

**Comment by Cahitisleyen** [comment]
hello how do i find my  now location

**Comment by sunshinejnjn** [comment]
> hello how do i find my now location

you can set or get Map.location using a point (such as (lat, lon))
