### ISSUE TITLE
Add {collapsed:false} from Leaflet to folium.LayerControl()

### ISSUE THREAD

**Issue by Seraf69** [python-visualization/folium#462]
Hopefully, this one has escaped me?
I cannot find out how to switch on the equivalent of Leaflet's  {collapsed:false}
 in folium.LayerControl() so as to show all the layers unpacked by default (rather than having to hover/click on the layer control icon (top right)
Thanks.

**Comment by sangyh** [comment]
I have been trying to do this too. Will follow this thread and update if I find anything.

**Comment by qingkaikong** [comment]
Ok, let me try to add this option into the LayerControl, wait for my update.

**Comment by qingkaikong** [comment]
Ok, I just create a pull request with all the new options: {position, collapsed, autoZIndex}, once it get merged, you can use these options.

**Comment by ocefpaf** [comment]
@Seraf69 thanks to @qingkaikong that option was added in `folium`. I try to get a new release out in the next few weeks or so.
