### ISSUE TITLE
MapQuest Open tiles discontinued

### ISSUE THREAD

**Issue by sarajcev** [python-visualization/folium#463]
If I understood correctly, as of July 11, 2016. MapQuest has discontinued direct tile access (http://goo.gl/xB0xXt). This broke folium maps which have used MapQuest Open tiles. Is there a workaround to this problem? Do you recommend using MapQuest with folium? Thanks in advance.

**Comment by ocefpaf** [comment]
> If I understood correctly, as of July 11, 2016. MapQuest has discontinued direct tile access 

You are correct. I haven't look into alternatives yet

> Do you recommend using MapQuest with folium? 

I usually go for the open street maps, but there are many other sources for tiles builtin in `folium`. You can also add any external source via a URL.

**Comment by BibMartin** [comment]
Note that there's [**this awesome website**](http://leaflet-extras.github.io/leaflet-providers/preview/) for choosing your tiles.

**Comment by ocefpaf** [comment]
> Note that there's [**this awesome website**](http://leaflet-extras.github.io/leaflet-providers/preview/) for choosing your tiles.

We could add that to the docs.
