### ISSUE TITLE
Add Search Box on Folium map

### ISSUE THREAD

**Issue by sangyh** [python-visualization/folium#464]
Can anybody point me towards how to add a Search box on Folium? 
I know Leaflet has this functionality but couldn't find any documentation on Folium.
Thanks in advance.

**Comment by ocefpaf** [comment]
There is no search box on `folium`. One could add a plugin for the https://github.com/stefanocudini/leaflet-search and implement it.

PRs welcome :smile:

**Comment by ghandic** [comment]
@sangyh

I have started to work on the leaflet-search plugin, it is awaiting a Pull Request, if you're still interested in this plugin a peer review would be great.

**Comment by morteza3000** [comment]
@ocefpaf 
can you please help more about mentioned plugin, how to install or add to a folium project?

**Comment by ghandic** [comment]
I have made an example notebook, did you look at that?

Sent from my iPhone

On 17 Oct 2017, at 06:00, morteza3000 <notifications@github.com<mailto:notifications@github.com>> wrote:


@ocefpaf<https://github.com/ocefpaf>
can you please help more about mentioned plugin, how to install or add to a folium project?

**Comment by morteza3000** [comment]
No I didn't, can you please give me the name of that example notebook?

**Comment by ghandic** [comment]
Plugins-search.ipynb

I think it should be there, I’ll check on my laptop when I get a chance if not.

Sent from my iPhone

On 17 Oct 2017, at 14:35, morteza3000 <notifications@github.com<mailto:notifications@github.com>> wrote:


No I didn't, can you please give me the name of that example notebook?

**Comment by morteza3000** [comment]
I'll really appreciate if you can share it.

**Comment by ghandic** [comment]
https://github.com/ghandic/folium/blob/search-features/examples/Plugins-Search.ipynb

**Comment by ocefpaf** [comment]
I'm away from office with limited connection. I'll check it as soon as I
get back.

**Comment by morteza3000** [comment]
@ghandic 
Thanks a lot but I faced with below error when I wanted to run notebook.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-b245dbd8b4f1> in <module>()
      9 )
     10 
---> 11 plugins.Search(states, search_zoom=6, geom_type="Polygon").add_to(m)
     12 
     13 m.save(os.path.join('results', 'Plugins_search_polygon.html'))

AttributeError: 'module' object has no attribute 'Search'

**Comment by ghandic** [comment]
Did you pip install from my search-feature branch? It’s not been accepted into the master branch of Folium yet.

Sent from my iPhone

On 18 Oct 2017, at 05:54, morteza3000 <notifications@github.com<mailto:notifications@github.com>> wrote:


@ghandic<https://github.com/ghandic>
Thanks a lot but I faced with below error when I wanted to run notebook.

________________________________

AttributeError Traceback (most recent call last)
in ()
9 )
10
---> 11 plugins.Search(states, search_zoom=6, geom_type="Polygon").add_to(m)
12
13 m.save(os.path.join('results', 'Plugins_search_polygon.html'))

AttributeError: 'module' object has no attribute 'Search'

**Comment by morteza3000** [comment]
sorry I'm totally new to folium, I've just install folium by pip and add your search.py file to "C:\ProgramData\Anaconda2\Lib\site-packages\folium\plugins". is it write?
can you help what to do step by step?

**Comment by ghandic** [comment]
run this:

`pip uninstall -y folium`
`pip install git+https://github.com/ghandic/folium.git@search-features`

You will then have the latest development that has not been merged into master.

**Comment by morteza3000** [comment]
for second command I got below error:

C:\Windows\system32>pip install git+https://github.com/ghandic/folium.git@search
-features
Collecting git+https://github.com/ghandic/folium.git@search-features
  Cloning https://github.com/ghandic/folium.git (to search-features) to c:\users
\morteza.has\appdata\local\temp\pip-ktrr6c-build
  Error [Error 2] The system cannot find the file specified while executing comm
and git clone -q https://github.com/ghandic/folium.git c:\users\morteza.has\appd
ata\local\temp\pip-ktrr6c-build
Cannot find command 'git'

**Comment by ghandic** [comment]
Install git...

**Comment by morteza3000** [comment]
Thanks a lot, it works now. :)

![image](https://user-images.githubusercontent.com/32860763/31718989-d01ea2e4-b41e-11e7-8f1e-b5074d02b9b9.png)

**Comment by morteza3000** [comment]
I want to search based on popup labels, is it possible?
here is my code:
-----------------------------------------------------------------------
import folium
from folium import plugins

coordinates = [
    [42.3581, -71.0636],
    [42.82995815, -74.78991444],
    [39.17929819, -78.56603306]]

m = folium.Map(location=[41.9, -97.3], zoom_start=4, tiles="cartodbpositron")
my_Circle1 = folium.CircleMarker(location=[42.3581, -71.0636], radius= 6, popup=str("one"), color='red', fill_opacity=0.7)
my_Circle2 = folium.CircleMarker(location=[42.82995815, -74.78991444], radius= 6, popup=str("two"), color='red', fill_opacity=0.7)
my_Circle3 = folium.CircleMarker(location=[39.17929819, -78.56603306], radius= 6, popup=str("three"), color='red', fill_opacity=0.7)
plugins.Search(coordinates, search_zoom=6, geom_type="Polygon").add_to(m)

m.add_child(my_Circle1)
m.add_child(my_Circle2)
m.add_child(my_Circle3)

m.save('example.html')

**Comment by ghandic** [comment]
This is how it was meant to be done:

points = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "la Bottega del caffe'"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [-71.0636, 42.3581]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Marani"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [-74.78991444, 42.82995815]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Il Faraone"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [-78.56603306, 39.17929819]
      }
    }
  ]
}

m = folium.Map(
    location=[42.82995815, -74.78991444],
    tiles = 'cartodbpositron',
    zoom_start=4
)

plugins.Search(points, search_zoom=20, ).add_to(m) 

m.save('example.html')

**Comment by ghandic** [comment]
It needs a layer to search through and you haven't supplied it by just passing coordinates. This will be added in with assertations into the next commit - as well as being able to use GeoJsonCss to add popups and styling rather than the default marker

**Comment by ghandic** [comment]
@morteza3000 I have implemented GeoJsonCss now, so re install folium as you did before if you want to use it

Here is your example with popups and a custom Icon:

points = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "One"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [-71.0636, 42.3581]
      },
      "style": {
            "icon": {
                "iconUrl": "http://downloadicons.net/sites/default/files/small-house-with-a-chimney-icon-70053.png",
                "iconSize": [32, 32],
                "iconAnchor": [16, 16]
            }
      },
      "popupTemplate": "<strong>{name}</strong>"
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Two"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [-74.78991444, 42.82995815]
      },
      "style": {
            "icon": {
                "iconUrl": "http://downloadicons.net/sites/default/files/small-house-with-a-chimney-icon-70053.png",
                "iconSize": [32, 32],
                "iconAnchor": [16, 16]
            }
      },
      "popupTemplate": "<strong>{name}</strong>"
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Three"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [-78.56603306, 39.17929819]
      },
      "style": {
            "icon": {
                "iconUrl": "http://downloadicons.net/sites/default/files/small-house-with-a-chimney-icon-70053.png",
                "iconSize": [32, 32],
                "iconAnchor": [16, 16]
            }
      },
      "popupTemplate": "<strong>{name}</strong>"
    }
  ]
}

m = folium.Map(
    location=[42.82995815, -74.78991444],
    tiles = 'cartodbpositron',
    zoom_start=4
)

plugins.Search(points, search_zoom=20).add_to(m) 

m.save('example.html')

**Comment by morteza3000** [comment]
I installed new one and it is working perfectly, Thanks.

**Comment by morteza3000** [comment]
@ghandic can you please help me with another issue? I want to have name as plain text instead of icon, is it possible?

**Comment by ghandic** [comment]
It is, I don’t think it’s integrated within folium yet but you can hack around it by using an image with the text in it, might be better with a png since you can have a transparent background.

Sent from my iPhone

On 12 Nov 2017, at 06:24, Morteza Hasan Abadi <notifications@github.com<mailto:notifications@github.com>> wrote:


@ghandic<https://github.com/ghandic> can you please help me with another issue? I want to have name as plain text instead of icon, is it possible?

**Comment by sonerss** [comment]
Hi @ghandic, How can I install git? Can you help me?

**Comment by HSAG-2018** [comment]
Hi i could not run this

pip install git+https://github.com/ghandic/folium.git@search-features

can you send an updated link please

thxs

**Comment by HSAG-2018** [comment]
ok i see
however i got this error: AttributeError: module 'folium.plugins' has no attribute 'Search' 
when using this command
plugins.Search(en_sid, search_zoom=6, geom_type='Polygon').add_to(map)
any idea what i have missed? thx

**Comment by ghandic** [comment]
What version of folium are you using?

**Comment by HSAG-2018** [comment]
0.5.0

**Comment by ghandic** [comment]
Ok that was last updated 4 months ago you can install from this git repo’s master branch, I’m on my phone atm so can’t check the pip install command 

@ocefpaf how are we managing the Pypi repo?

**Comment by HSAG-2018** [comment]
you mean here? https://github.com/python-visualization/folium/tree/master/folium/plugins

**Comment by ghandic** [comment]
`pip install git+https://github.com/python-visualization/folium.git`

**Comment by HSAG-2018** [comment]
still not working not sure if from server side or my laptop...
C:\UseCase3>pip install git+https://github.com/python-visualization/folium.git
Collecting git+https://github.com/python-visualization/folium.git
  Cloning https://github.com/python-visualization/folium.git to c:\users\h\appdata\local\temp\pip-iqccyg6z-build
fatal: unable to access 'https://github.com/python-visualization/folium.git/': SSL certificate problem: unable to get local issuer certificate Command "git clone -q https://github.com/python-visualization/folium.git C:\Users\h\AppData\Local\Temp\pip-iqccyg6z-build" failed with error code 128 in None

**Comment by ghandic** [comment]
Ok try cloning the repo first then run the setup.py

Sent from my iPhone

On 17 Jan 2018, at 20:19, HSAG-2018 <notifications@github.com<mailto:notifications@github.com>> wrote:


still not working not sure if from server side or my laptop...
C:\UseCase3>pip install git+https://github.com/python-visualization/folium.git
Collecting git+https://github.com/python-visualization/folium.git
Cloning https://github.com/python-visualization/folium.git to c:\users\h\appdata\local\temp\pip-iqccyg6z-build
fatal: unable to access 'https://github.com/python-visualization/folium.git/': SSL certificate problem: unable to get local issuer certificate Command "git clone -q https://github.com/python-visualization/folium.git C:\Users\h\AppData\Local\Temp\pip-iqccyg6z-build" failed with error code 128 in None

**Comment by HSAG-2018** [comment]
the cloning does not work so i tried to download the zip save it locally then run setup.py but this has no effect...shld replacing the whole existing folium directory with the new dowloaded one work? thxs

**Comment by ocefpaf** [comment]
> @ocefpaf how are we managing the Pypi repo?

There will be a new release once I can allocate some time to review and merge the open PRs.

**Comment by javaUtilScammer** [comment]
@ghandic Hello sorry to bother. I also want to add search functionality on a group of markers and display a pop up so I tried running the sample code with GeoJsonCss implemented which you provided above but it doesn't seem to be working. To be more specific, I can't get the pop ups to appear.

I've pip installed from the git (pip install git+https://github.com/python-visualization/folium.git) and am running on python 3.6.3.

Hope I can get it to work soon :) Thanks!

![image](https://user-images.githubusercontent.com/8697309/37011420-02d4cad2-212b-11e8-82e6-91d54fd3112e.png)

**Comment by ghandic** [comment]
Hi @javaUtilScammer can you add your source code? I’ll take a look at this this morning if you can

**Comment by javaUtilScammer** [comment]
Hi @ghandic , didn't expect you to reply so fast but big thank you :) I wanted to implement the search functionality on another map I made using Folium a while back but I can't get the popups to appear on a sample.

It's pretty much the code you commented a while back plus imports. Thanks!

import folium
from folium import plugins
from folium import GeoJson

points = {
	"type": "FeatureCollection",
	"features": [
		{
			"type": "Feature",
			"properties": {
				"name": "One"
			},
			"geometry": {
				"type": "Point",
				"coordinates": [-71.0636, 42.3581]
			},
			"style": {
				"icon": {
					"iconUrl": "http://downloadicons.net/sites/default/files/small-house-with-a-chimney-icon-70053.png",
					"iconSize": [32, 32],
					"iconAnchor": [16, 16]
				}
			},
			"popupTemplate": "{name}"
		},
		{
			"type": "Feature",
			"properties": {
				"name": "Two"
			},
			"geometry": {
				"type": "Point",
				"coordinates": [-74.78991444, 42.82995815]
			},
			"style": {
				"icon": {
					"iconUrl": "http://downloadicons.net/sites/default/files/small-house-with-a-chimney-icon-70053.png",
					"iconSize": [32, 32],
					"iconAnchor": [16, 16]
				}
			},
			"popupTemplate": "{name}"
		},
		{
			"type": "Feature",
			"properties": {
				"name": "Three"
			},
			"geometry": {
				"type": "Point",
				"coordinates": [-78.56603306, 39.17929819]
			},
			"style": {
				"icon": {
					"iconUrl": "http://downloadicons.net/sites/default/files/small-house-with-a-chimney-icon-70053.png",
					"iconSize": [32, 32],
					"iconAnchor": [16, 16]
				}
			},
			"popupTemplate": "{name}"
		}
	]
}

m = folium.Map(
location=[42.82995815, -74.78991444],
tiles = 'cartodbpositron',
zoom_start=4
)

plugins.Search(data=points, search_zoom=20,position="topright").add_to(m)
m.save('example.html')

**Comment by ghandic** [comment]
@javaUtilScammer the GeoJsonCss part has not been merged into master on this repo, I just had a look at my fork vs this repo. @ocefpaf was there some problems with the GeoJsonCSS?

**Comment by ocefpaf** [comment]
> @ocefpaf was there some problems with the GeoJsonCSS?

My time to finish reviewing it. I do recall some issues when testing against the notebook gallery, but I cannot get back to that this month :unamused:

**Comment by ghandic** [comment]
No problem @ocefpaf I saw some of the modifications you did and it simplifies it a lot, I'm happy to test some of those notebooks out. 

Meanwhile @javaUtilScammer if you really need this purely as an output and not for long term you could use my forked repo https://github.com/ghandic/folium.git 

Check back soon and I'm sure we'll be a few steps closer to having this up and running!

**Comment by ocefpaf** [comment]
> No problem @ocefpaf I saw some of the modifications you did and it simplifies it a lot, I'm happy to test some of those notebooks out.

Our testing is a little time consuming, we need to run all the notebooks from example folder and inspect them visually. If you could do that and fix the remaining issues that would be awesome!

**Comment by ghandic** [comment]
@ocefpaf  Just found a great little package which speeds that up, called **nbmerge**

```bash
# cd into the project folder
pip install nbmerge
# Merges all of the notebooks into one inside examples/_merged.ipynb
nbmerge --recursive -i -p ".*" -o examples/_merged.ipynb
```

**Comment by javaUtilScammer** [comment]
> Meanwhile @javaUtilScammer if you really need this purely as an output and not for long term you could use my forked repo https://github.com/ghandic/folium.git

@ghandic will do that for now but will definitely come back when the merge is complete! Big thanks goes to you and @ocefpaf for the quick action :)

**Comment by ghandic** [comment]
@ocefpaf 

I spun up a docker container running jupyter notebook, cloned the repo and installed folium from your last commit hash on the pull request for #762 

Then I merged all the notebooks and ran all cells, all of which seems to work perfectly. I haven't done any other testing than that, just checked the outputs and nothing errored

Docker-compose.yml
-----------

```YAML
version: "2"
services:
  jupyter-notebook:
    build: .
    image: challisa/folium-notebook
    container_name: folium-notebook
    ports:
      - "8888:8888"
    volumes:
      - ~:/home/jovyan/work
    entrypoint: start-notebook.sh --NotebookApp.token='' --NotebookApp.iopub_data_rate_limit=1000000000000000 

```


Dockerfile
-----------

```Dockerfile
FROM jupyter/minimal-notebook

MAINTAINER Jupyter Project <jupyter@googlegroups.com>

USER root

# libav-tools for matplotlib anim
RUN apt-get update && \
    apt-get install -y --no-install-recommends libav-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Cartopy
RUN conda install --yes -c conda-forge cartopy

USER $NB_USER

RUN pip install  \
    'matplotlib' \
    'mplleaflet' \
    'geographiclib' \
    'gpxpy' \
    'altair' \
    'vincent' \
    'geopandas' \
    'pandas' \
    'widgetsnbextension' && \
    # Activate ipywidgets extension in the environment that runs the notebook server
    jupyter nbextension enable --py widgetsnbextension --sys-prefix 

USER $NB_USER
```

**Comment by Alcampopiano** [comment]
@ghandic Hi Andy, am I right that the popup functionality has not yet been merged with master?

**Comment by ms77grz** [comment]
Hi guys! Can anyone help me with search function?
from folium import plugins, Map, Marker, FeatureGroup, Popup, LayerControl
import webbrowser

m = Map(location=[43.25, 45.83333 ], zoom_start=10, zoom_control=False)

fg = FeatureGroup(name='VTK')

g1 = plugins.FeatureGroupSubGroup(fg, 'FTTB')
g2 = plugins.FeatureGroupSubGroup(fg, 'FTTH')
g3 = plugins.FeatureGroupSubGroup(fg, 'GPON')
Marker([43.119749, 45.562305], popup=Popup('one')).add_to(g1)
Marker([43.143048, 45.534987], popup=Popup('two')).add_to(g2)
Marker([43.131022, 45.546844], popup=Popup('three')).add_to(g3)
m.add_child(fg)
m.add_child(g1)
m.add_child(g2)
m.add_child(g3)

m.add_child(plugins.Search(fg))
m.add_child(LayerControl(collapsed=False))
m.save('test_map2.html')
webbrowser.open('test_map2.html')

**Comment by morteza3000** [comment]
> @HSAG-2018
> pip install folium
> as it is now in the master branch :)

@ghandic , when I install it with (> pip install folium) below error appears for same examples.
can you please help?

AssertionError: Search can only index FeatureGroup, MarkerCluster, GeoJson, and TopoJson layers at this time.

**Comment by ghandic** [comment]
I believe they have refactored the code since I made my pull request. Maybe check in the example notebooks?

Sent from my iPhone

On 6 Apr 2019, at 21:46, Morteza Hasan Abadi <notifications@github.com<mailto:notifications@github.com>> wrote:


@HSAG-2018<https://github.com/HSAG-2018>
pip install folium
as it is now in the master branch :)

@ghandic<https://github.com/ghandic> , when I install it with (> pip install folium) below error appears for same examples.
can you please help?

AssertionError: Search can only index FeatureGroup, MarkerCluster, GeoJson, and TopoJson layers at this time.

**Comment by morteza3000** [comment]
Yes, your example notebooks also don't work with provided data.

**Comment by ghandic** [comment]
I haven’t updated the pull request. Someone else made changes, I will have a look if I get chance. Maybe check who made the updates.

Sent from my iPhone

On 7 Apr 2019, at 16:07, Morteza Hasan Abadi <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, your example notebooks also don't work with provided data.

**Comment by Conengmo** [comment]
@morteza3000 please open a new issue for your problem and include:

- a stand-alone code snippet that results in the error message
- the full error message
- your folium version: `print(folium.__version__)`

**Comment by morteza3000** [comment]
@Conengmo , please be informed that below issue has been raised.
Problem with Folium search plugin (loading Geojosn Data) #1125

**Comment by chillinshunsui** [comment]
> Thanks a lot, it works now. :)
> 
> ![image](https://user-images.githubusercontent.com/32860763/31718989-d01ea2e4-b41e-11e7-8f1e-b5074d02b9b9.png)

hey, can you share the code

**Comment by ghandic** [comment]
Check out the example notebooks https://github.com/python-visualization/folium/blob/master/examples/plugin-Search.ipynb

**Comment by GinoVillalpando** [comment]
is there a search plugin that works for FastMarkerCluster? I can't use MarkerCluster because it hinders the load performance because I'm using over 11,000 markers.

**Comment by morteza3000** [comment]
> Check out the example notebooks https://github.com/python-visualization/folium/blob/master/examples/plugin-Search.ipynb

@ghandic , How we can style points in your example?

citygeo = folium.GeoJson(
    pop_ranked_cities,
    name='US Cities',
    tooltip=folium.GeoJsonTooltip(
        fields=['nameascii','pop_max'],
        aliases=['','Population Max'],
        localize=True)
).add_to(m)

how to add style_function to this in order to change points color or use custom icon?

**Comment by zoesn89** [comment]
Hey everyone,

as the docs say, the search plugin can index FeatureGroup, MarkerCluster, GeoJson and TopoJson layers.
It only worked for me on GeoJson layers so far.

Could you please provide an example for FeatureGroup or MarkerCluster without GeoJson?

Thanks in advance ;)

**Comment by PhilippMDoerner** [comment]
Search is currently only implemented for GeoJson and TopoJson. I'm not entirely sure as to why the documentation states that it also implements the search for FeatureGroup and MarkerClusters. Maybe there were/are plans down the line for it (?)

**Comment by asemrbehat** [comment]
> > Check out the example notebooks https://github.com/python-visualization/folium/blob/master/examples/plugin-Search.ipynb
> 
> @ghandic , How we can style points in your example?
> 
> citygeo = folium.GeoJson(
> pop_ranked_cities,
> name='US Cities',
> tooltip=folium.GeoJsonTooltip(
> fields=['nameascii','pop_max'],
> aliases=['','Population Max'],
> localize=True)
> ).add_to(m)
> 
> how to add style_function to this in order to change points color or use custom icon?

Hi, is there any way to do it by HTML ? 
I cant add link the search box with the markers in order to search for them </>

**Comment by AtharvaShekatkar** [comment]
@ghandic hey, could you help me with using the search plugin for FeatureGroup layers? I've not been able to find a working solution for that anywhere.
