### ISSUE TITLE
Can not load Vincent plot in the popup

### ISSUE THREAD

**Issue by qingkaikong** [python-visualization/folium#466]
The Vincent/Vega Markers example in the folium_examples.ipynb in the examples folder have trouble to load the Vincent plot. I got the error on Chrome on a mac:
**An embedded page on this webpage says: 
[Vega Err] [object XMLHttpRequest]**

This seems a browser protocol issue, may need take care in the future.

**Comment by ocefpaf** [comment]
@BibMartin I saw this with @qingkaikong here on a OS X machine using safari. Chrome works, but I haven't test firefox yet.

**Comment by qingkaikong** [comment]
Actually on my mac, it is not working on Chrome, Safari, and firefox. But Chrome and Safari gave me the popup error message, firefox didn't give me any error message.

**Comment by ocefpaf** [comment]
Good to know. We need to track down if we still are loading something from an `http` endpoint.

**Comment by ocefpaf** [comment]
We are abandoning `Vincent`/`Vega` a possible alternative is under discussion in #488.
