### ISSUE TITLE
Could you tell me how to make a newline on Marker Popup

### ISSUE THREAD

**Issue by xhx509** [python-visualization/folium#469]
Hi 

I tried to put "\n" and "br<>" to make a newline on Marker Popup. But they are not working. The letters are still in one line.
Could you tell me how to make a newline?

Thank you

**Comment by qingkaikong** [comment]
If put popup = 'First Line <br> Second Line', it seems folium convert the text to First Line &lt;br&gt; Second Line, and pass it to leaflet. Therefore the leaflet can not recognize it. (leaflet do recognize <br> as newline).

A simple walk around for now: after you generate the html file, find the line of this popup text, and change the &lt;br&gt; to <br>, this should work to separate the lines in the popup. You can find the attached html file I generated, and I changed line 78. 

[mthood.html.zip](https://github.com/python-visualization/folium/files/375144/mthood.html.zip)

Let me see if I can make some changes to it for long term solution.

**Comment by qingkaikong** [comment]
It does seem there's a better solution discussed before in #332, using IFrame. 

You can check out the following notebook made by @BibMartin:
http://nbviewer.jupyter.org/github/bibmartin/folium/blob/issue288/examples/Popups.ipynb

**Comment by xhx509** [comment]
Hi Qingkai:

Your help are very useful to me, I would like to make a Html as @BibMartin
<https://github.com/BibMartin>:'s example.

My issue is solved

Thanks a lot .


Sincerely
Huanxin(Xavier)

**Comment by ocefpaf** [comment]
Thanks @qingkaikong!

**Comment by qingkaikong** [comment]
You are welcome, and glad to help!

**Comment by disarticulate** [comment]
Although iFrame solves this problem, the lack of HTML formatting for a popup is annoying. An iframe can't to relative source linking, AFAIK. Here's a solution someone could add to folium if they cared:

```
from jinja2 import Template
popup_template = Template(u"""
            var {{this.get_name()}} = L.popup({maxWidth: '{{this.max_width}}'});
            {% for name, element in this.html._children.items() %}
                var raw_html = String.raw`{{element.render(**kwargs).replace('\\n',' ')}}`
                var {{name}} = $('<div/>').html(raw_html).text()
                {{this.get_name()}}.setContent({{name}});
            {% endfor %}
            {{this._parent.get_name()}}.bindPopup({{this.get_name()}});
            {% for name, element in this.script._children.items() %}
                {{element.render()}}
            {% endfor %}""") # noqa
html = """
            <img width="{width}" height="{height}" src="{href}"><a href="{href}" target="_new">{href}</a>"""
popup = folium.Popup(html)
popup._template = popup_template
```
If someone takes this up, they should also add a class variable which store the raw string put into the jinja2 Template function

**Comment by ocefpaf** [comment]
> Here's a solution someone could add to folium if they cared:

We all care. However, `folium` is maintained by volunteers on their spare time, day jobs are always keeping us away from fun coding :wink: 

Would you care to send a PR yourself?

**Comment by disarticulate** [comment]
@ocefpaf I appreciate all the work here. But you've closed all the issues mentioned here, which suggests these arn't problems. When I review the organization of this library, I don't find anything comfortable enough to suggest anything other than overrides and workarounds. I left the above so that anyone else google searching finds a more satisfying option than an iframe.

As the code I posited simply replaces the functionality that appears broken because, there's clearly an upstream issue waiting to be reviewed. 

I suspect it's broken as the keyword "html" suggests you can input html, but in actuallity, it only takes raw strings. That's broken, is it not?

**Comment by ocefpaf** [comment]
> That's broken, is it not?

Only if you expect it to be `HTML` :wink: 

The author of that code designed it to be raw strings, and the use of `HTML` via the `IFrame`. Hence the closed issue. I understand that it is convenient to add `HTML` directly, but I believe @BibMartin had a reason to do it this way.

Again, if you send a PR, we ca review and check how that goes with the rest of the functionality.

**Comment by ulvic** [comment]
Hi guys,
I try to accomplish something like that in popup,
`popup = ('Time: '+ row.name.strftime('%H:%M')+ ' \nSpeed: '+ str(round(row['spd'],2))+' km/h'))`
which doesnt work, and I cannot come up with idea how to insert variables into html = """...""" to use its <br>.
Is there a way to get it done?

**Comment by BibMartin** [comment]
You can try something like:
```python
popup = (
    "Time: {time}<br>"
    "Speed: {speed} km/h<br>"
   ).format(time=row.name.strftime('%H:%M'),
             speed=str(round(row['spd'],2)),
             )
```

**Comment by ulvic** [comment]
Thanks @BibMartin, that solved it!

**Comment by spsanderson** [comment]
using the .format() method did not work for me, for some reason, the <br> is being ignored.

**Comment by Conengmo** [comment]
It seems you're not adding the Popup to Marker. Also, is `fg` a feature group? You only have to add it to map once.

```
for lt, ln, el, nm in zip(lat, lon, elev, volname):
    fg.add_child(folium.Marker(location=[lat, lon],
        popup = (
            "Elevation: {elev}</br>"
            "Name: {volname}<br>"
        ).format(elev=str(el), volname=str(nm))))
map.add_child(fg)
```

**Comment by spsanderson** [comment]
Hi @Conengmo I am making a feature group (fg), I do have the popup inside of the `folium.Marker` code, thank you for letting me know I can take the `map.add_child(fg)` out of the loop
