### ISSUE TITLE
why I can't set more than two markers in map 

### ISSUE THREAD

**Issue by hkjournalist** [python-visualization/folium#470]
Dear author ：Please forgive my poorly english ability.
I want to know why I can't set more than two ‘Marker' in 'map' when I set popup = 'sth'

```python
import folium
map= folium.Map(location=[29.606789,106.241882],tiles='Stamen Toner',zoom_start=13)

folium.Marker([29.800519,106.08983],
                 popup='test1',
                 icon=folium.Icon(icon='cloud')
                 ).add_to(map)

folium.Marker([29.606789,106.241882],
                 popup='test2',
                 icon=folium.Icon(icon='cloud')
                 ).add_to(map)
map.save('test233.html')
```

**Comment by ocefpaf** [comment]
> Dear author ：Please forgive my poorly english ability.

That is never a problem in GitHub issue :smile: 

I just tested your code and it seems fine:

http://nbviewer.jupyter.org/gist/ocefpaf/0c34a265627c758aa9e27ffc6786fcb7

Note that your points are really close together, so you will need to zoom in to tell them apart.
