### ISSUE TITLE
How to measure distance?

### ISSUE THREAD

**Issue by kcnwogu** [python-visualization/folium#472]
Is there a way to enable the measure feature of Leaflet with Folium?
![image](https://cloud.githubusercontent.com/assets/7269633/17035067/1ad68ef8-4f4b-11e6-9cb9-e10640982107.png)

**Comment by BibMartin** [comment]
It seem easy to do with https://github.com/jtreml/leaflet.measure

Any volunteer to create a plugin ?

**Comment by ocefpaf** [comment]
Does it work with leaflet `1.x`? It seems that the latest test was against `leaflet v0.6.4`.

**Comment by BibMartin** [comment]
@ocefpaf 
> Does it work with leaflet 1.x? It seems that the latest test was against leaflet v0.6.4.

You're true. It work not perfectly. ([See here](http://nbviewer.jupyter.org/gist/BibMartin/477acdc4f228779c94f7a02bf7693438))
I may be able to suggest a PR there to fix things.
What should we do ? Wait for the PR to be okay or implement the plugin anyway ?

**Comment by ocefpaf** [comment]
> What should we do ? Wait for the PR to be okay or implement the plugin anyway ?

I would say let's go for it. It is not that bad. The first click gets computed and display before waiting for the second.

**Comment by ocefpaf** [comment]
Implemented in #669
