### ISSUE TITLE
Add sub-layers to layer control

### ISSUE THREAD

**Issue by pjandrews** [python-visualization/folium#475]
Here is an example of what I mean by sub-layers. Let's say that I was trying to track a group of dogs and a group of cats like this:

Dogs
-Fido
-Spot
-Rex

Cats
-Wiskers
-Garfield
-Tom

On the top layer I could select all the dogs or all the cats. In the sub-layer I could select any of the individual dogs or cats.

**Comment by pjandrews** [comment]
Are there any plans to implement this feature?

**Comment by ocefpaf** [comment]
Plans? Yes. Manpower to do so? No.

**Comment by Conengmo** [comment]
This functionality is not available in Leaflet. [This stackoverflow entry](https://stackoverflow.com/questions/17817911/leaflet-layer-control-select-layer-inside-layer-group) asks the same question, they mention [this Leaflet plugin](https://github.com/ismyrnow/leaflet-groupedlayercontrol) that adds grouping in layer control, but doesn't add hierarchy. So actual sub-layers seem difficult to achieve.

**Comment by Conengmo** [comment]
We now have this behavior with the `FeatureGroupSubGroup` plugin. Check out an example here:

https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Plugins.ipynb#Sub-categories
