### ISSUE TITLE
min width and max height in popup

### ISSUE THREAD

**Issue by lightening0907** [python-visualization/folium#476]
HI everyone,
 Is there any way to adjust the min width and max height for the pop up window? I put two image in the html iframe for the popup, without adjusting the min width and max height of the pop up window, the popup will not function properly (height exceed the browser, popup will not show). I saw in http://leafletjs.com/reference.html#popup-minwidth, it support these options, is it possible to do it with folium?
  Thank you!

**Comment by peporiz0r** [comment]
Here's an example of the popups with vega graphs:
`folium.RegularPolygonMarker(
    [47.3489, -124.708],
    fill_color='#43d9de',
    radius=12,
    popup=folium.Popup(max_width=450).add_child(
        folium.Vega(json.load(open('vis1.json')), width=450, height=250))
    ).add_to(buoy_map)
`
does this help you? I had problems with the popup size too.

**Comment by ocefpaf** [comment]
Thanks @wAuner! Take a look at the new Vega-Lite feature. See [this notebook](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/033e10a1e0c828581c30296f2ddda56f24ca0393/examples/Features.ipynb) cell [9].  That is the direction we want to go. Let me know if your have any feedback.
