### ISSUE TITLE
folium Icon

### ISSUE THREAD

**Issue by kcnwogu** [python-visualization/folium#477]
Do you know why some icons are not displayed? An example is "fa-bicycle"

```python
map_1 = folium.Map(location=[45.372, -121.6972],
                   zoom_start=12,
                   tiles='Stamen Terrain')
folium.Marker([45.3300, -121.6823],
              popup='Some Other Location',
              icon=folium.Icon(color='red',icon='bicycle', prefix='fa')
              ).add_to(map_1)

print folium.__version__
0.2.1
```

**Comment by ocefpaf** [comment]
@kcnwogu I haven't kept the pace with the `fa` fonts updates. We are using https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css and maybe that the bicycle is not available in this version.

We should make it more flexible so people can use the icon and change the URL though. PRs welcomed :grimacing:

**Comment by kcnwogu** [comment]
@ocefpaf thanks for the update.

**Comment by ocefpaf** [comment]
BTW let me know which version of `fa` you are using and maybe we can try to update it in `folium` before the next release.

**Comment by kcnwogu** [comment]
I am using version 4.3.

**Comment by ocefpaf** [comment]
Alright. This one was easy enough to get me from my laziness and send a PR :stuck_out_tongue_winking_eye: 

Here is the result: http://nbviewer.jupyter.org/gist/ocefpaf/e2b828a773c6588a02614a274803daec

**Comment by kcnwogu** [comment]
Right on! Thanks a lot.
