### ISSUE TITLE
HTML popup - Unicode

### ISSUE THREAD

**Issue by tlinhart** [python-visualization/folium#479]
Hi,

when using the HTML popup for markers, Unicode characters are not shown correctly. Consider this sample code with Czech characters:

<pre>map = folium.Map(location=(50, 14))

html = u'<b>Text:</b> {0}'.format(u'ěščřžýáíé')
iframe = folium.element.IFrame(html=html, width=200, height=100)
popup = folium.Popup(iframe)
folium.Marker((50, 14), popup=popup).add_to(map)

map</pre>

I'm using Folium 0.2.1.

**Comment by ocefpaf** [comment]
@tlinhart this was fixed in `branca`. See https://github.com/python-visualization/branca/pull/14#issuecomment-237171417 and will be part of `folium`'s next release.

**Comment by tlinhart** [comment]
Great, thanks a lot.
