### ISSUE TITLE
Vega graphs with Altair - Vincent discontinued

### ISSUE THREAD

**Issue by peporiz0r** [python-visualization/folium#480]
Hi, is there a way to create the graphs for the popups with altair, since vincent won't be continued? I tried to implement it, but failed. I couldn't find a `.to_json()`method in altair. Is it a problem that altair uses vega-lite?I'm obviously not an expert ;)

**Comment by ocefpaf** [comment]
@peporiz0r switching from `vincent` to `altair` is in the cards, but I haven't looked into `altair` yet and it may take some time.

Note that you can always save a `PNG` and display in the popup as a workaround:

http://nbviewer.jupyter.org/github/ocefpaf/folium_notebooks/blob/master/test_png_mpld3_vega_popup.ipynb

**Comment by ocefpaf** [comment]
Let's move this discussion to #488
