### ISSUE TITLE
Impossible to draw GeoJSON that has crs other than 4326

### ISSUE THREAD

**Issue by AlexArcPy** [python-visualization/folium#481]
I have two GeoJSON files that are identical in their structure except one has 

`Islands3857.geojson`

`{"crs": {"type": "name", "properties": {"name": "EPSG:3857"}}`

and another has 

`Islands4326.geojson`

`{"crs": {"type": "name", "properties": {"name": "EPSG:4326"}}`

I am able to draw on the map only GeoJSON file with coordinates defined in 4326 (decimal degrees). 

Is there support for GeoJSON in other coordinate system or one has to re-project the coordinates to decimal degrees (4326) to be able to draw the features on the map?

The code I run:
```
import folium

data = r"C:\GIS\Islands3857.geojson" #Islands4326.geojson
m = folium.Map([40.7,20], zoom_start=3, tiles='cartodbpositron',crs='EPSG3857')
folium.GeoJson(open(data)).add_to(m)
m
```
I get features drawn only when supplying the geojson with coordinates defined in `crs 4326`.

I am on `0.2.1                    py27_0    conda-forge` on Anaconda.

PS. I am able to plot a `geopandas GeoDataFrame` by importing the geojson file with web mercator (3857) coordinates, so there is nothing wrong with my geojson file.

**Comment by ocefpaf** [comment]
`Geopandas` has the notion of `crs` but, as far I can remember, we never implemented much functionality towards better support for projections.

@BibMartin did implement a nice support for [`geopandas`](https://github.com/python-visualization/folium/blob/7d8e7c5f74e0c23c08c428b6daabe7f7478ecffa/folium/features.py#L321) though that may help as it uses `geopandas` to re-project before drawing.

**Comment by AlexArcPy** [comment]
@ocefpaf , ok, thank you. Did I understand right that if I have a geojson file with coordinates defined and stored not in WGS84 (epsg 4326) decimal degrees, I won't be able to draw the geojson directly? In other words, I do need to reproject the coordinates before I will be able to draw them with folium?

**Comment by ocefpaf** [comment]
I haven't test this yet but if you provide the a `geopandas` `GeoDataFrame` or `GeoSeries` the re-projection should be done automatic for you:

```python
        elif data.__class__.__name__ in ['GeoDataFrame', 'GeoSeries']:
            self.embed = True
            if hasattr(data, '__geo_interface__'):
                # We have a GeoPandas 0.2 object.
                self.data = json.loads(json.dumps(data.to_crs(epsg='4326').__geo_interface__))  # noqa
```

PS: the `GeoJson` does not mention this in the `docstring` and that is a doc bug we need to fix!

**Comment by AlexArcPy** [comment]
@ocefpaf , no worries. I am casting the `GeoDataFrame` into another crs like this:
```
import geopandas as gpd
df = gpd.read_file(data)
df = df.to_crs(epsg='4326')
js = df.to_json()
```

I just wanted to understand if this was necessary. If not doing this, providing a `GeoDataFrame` or geoJSON in another crs than 4326 would not draw. Not a big deal to use the `geopandas to_crs()`, I am OK with that :)
