### ISSUE TITLE
endless/continuous map

### ISSUE THREAD

**Issue by peporiz0r** [python-visualization/folium#482]
is there a parameter for setting the map to be continuous?
so that i can come back to my starting point on the map just by "walking" in the same direction.

the reason for that is the following: I placed a marker with a popup on Japan. Since I can't move any more to right, the handling of popup can get really ugly and it partly disappears.

**Comment by ocefpaf** [comment]
@peporiz0r the problem is the automatic settings of `maxBounds` in `folium`. In theory the default map is already "endless." You can probably see that when trying to navigate, but it goes back to the bounds once you release the mouse.

I will see a nice way to circumvent that.

**Comment by ocefpaf** [comment]
@peporiz0r I have a prototype ready: http://nbviewer.jupyter.org/gist/ocefpaf/e47845727e92088757b4d0c77ed90046

Let me know if that is what you have in mind. I am polishing it to prepare a PR.

**Comment by thatneat** [comment]
I was just running in to this same issue. Your solution works quite well, though maybe there should be a way to maintain the 'bounce' functionality in the North/South direction? As it is, it's easy to scroll off the top or bottom and get lost.

**Comment by peporiz0r** [comment]
Yes @ocefpaf , that's what i was looking for. And i agree with @thatneat , an upper bound would be useful. But that bound should start a little above or below the map, so that popup can still be displayed on the top/bottom of the map.
Your solution also leads sometimes to strange behavior while "crossing the line", e.g. jumping on the map. But other than that, it's great

**Comment by ocefpaf** [comment]
> Your solution also leads sometimes to strange behavior while "crossing the line", e.g. jumping on the map. But other than that, it's great

That is a leaflet "feature."

> But that bound should start a little above or below the map

You have control over the bounds with `min_`/`max_` `lon`/`lat` already. The only issue was that the bounds were set by default.

**Comment by peporiz0r** [comment]
Great, thanks!

**Comment by ocefpaf** [comment]
@peporiz0r I will leave this opened until we merge the functionality otherwise I will forget it. (I haven't even send the PR yet :flushed:)

**Comment by Vishal-Pandey-git** [comment]
@ocefpaf your notebook at [http://nbviewer.jupyter.org/gist/ocefpaf/e47845727e92088757b4d0c77ed90046](url) is not available anymore, It would be very helpful if you share again. Thanks
