### ISSUE TITLE
Distances / Routes

### ISSUE THREAD

**Issue by wAuner** [python-visualization/folium#484]
Is there a way to create paths with distances or measuring distances between points?
This project has so much potential, I really like it.
Wish it would be easier to involve charts/image on the map though.

**Comment by ocefpaf** [comment]
> Is there a way to create paths with distances or measuring distances between points?

There is no convenient way to do it. If you find a `leaflet` plugin with such functionality we can try to wrap like into a `folium` plugin.

> Wish it would be easier to involve charts/image on the map though.

Take at the image overlay plugin:

http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/ImageOverlay.ipynb

**Comment by ocefpaf** [comment]
Done in #669
