### ISSUE TITLE
Broken again: Geojson popup content not showing up 

### ISSUE THREAD

**Issue by achourasia** [python-visualization/folium#486]
For release 0.2.1 the popup content is broken again
Original issue
https://github.com/python-visualization/folium/issues/100

**Comment by cloud05** [comment]
Same here. Pop ups are not showing even with 'popupContent' in my geojson 'properties'.

**Comment by ocefpaf** [comment]
Closing this as it is duplicate of https://github.com/python-visualization/folium/issues/198
