### ISSUE TITLE
Vega-lite?

### ISSUE THREAD

**Issue by rornor** [python-visualization/folium#488]
I'm trying to pass vega-lite dict (from altair) to `folium.Vega()` but it does not render.
Is vega-lite supported, or do you know some easy way to transform vega-lite to vega?

**Comment by ocefpaf** [comment]
The `Vega` pluging wrapps only `vincent` plot and that will be deprecated soon.

It would be nice to get `Vega-lite` support via `altair`. Are you interested in send a PR?

**Comment by rornor** [comment]
Sure, np, I'll try in the next couple of days, and report back.

**Comment by ocefpaf** [comment]
BTW here is the altair project that may help: https://github.com/ellisonbg/altair

**Comment by rornor** [comment]
Hi,

I quickly browsed through the code. So it seems to me you have template for rendering `vega` json data, and you expect passed Python data to have `.to_json()` method. However, `altair` objects have `.to_dict()` method, and creating `.to_json()` from there seems trivial. OTOH, we can use current `vega` renderer, as `vega-lite` package seems to provide "compiler" to deduce `vega` spec from `vega-lite` spec: https://vega.github.io/vega-lite/usage/compile.html

As I'm not familiar with the workflow here, please suggest the route

**Comment by ocefpaf** [comment]
> As I'm not familiar with the workflow here, please suggest the route

To be honest I need to think and test this too to suggest a route. I also have not played with `altair` yet.

In general terms I would:

- kill the `vincent` plugin
- test what would take to parse a `vega-lite` `JSON` without worrying about how we are going to create that `JSON` yet
- if that seems doable than we should create a `plugin` that may (or may not) use `altair` to easy the `JSON` creation

Does that makes sense? I am swamped with my day job lately but I will get back here to try and help more next week.

**Comment by rornor** [comment]
Ok. I'm not sure what role Vincent plays in Folium, as I would guess that it just gives object with `.to_json()` method that results in valid Vega object, which is then rendered through Vega js?

From what I can see it seems that creating Vegalite class (similarly to Vega class in `features.py`) would be much the same as creating a separate plugin. Again I didn't study Folium code, so maybe I talk nonsense...

**Comment by mbmilligan** [comment]
Hi, popping in to ask if anyone has managed to make progress on this? If not I should be able to devote some time to helping out, since we do want this functionality at my day job.

**Comment by ocefpaf** [comment]
@mbmilligan no one is working on this right now. A PR would be greatly appreciated!

**Comment by ocefpaf** [comment]
Closed in #643
