### ISSUE TITLE
IFrame support for  IE and Edge

### ISSUE THREAD

**Issue by rornor** [python-visualization/folium#489]
IE and Edge does not support IFrame with data uri as src attribute. Instead both support only explicit paths for src attribute. 

So folium IFrames does not show on Windows browsers.

**Comment by ocefpaf** [comment]
> So folium IFrames does not show on Windows browsers.

This statement if not true. Many people use `folium` in Windows browser. However, I do understand that it would be nice to support more browsers like IE and Edge. PRs welcome :smile:

**Comment by rornor** [comment]
Only option I see is to serve IFrame content is separate file(s). 
Although it works - I can see it in IE/Edge I don't like this option very much :(

**Comment by ocefpaf** [comment]
> Although it works - I can see it in IE/Edge I don't like this option very much :(

Neither do I. I'll research a little bit about this to see if we can do better.

To be honest I would like to support more browsers but as long as firefox and chromium/chrome are OK I am happy.

**Comment by rornor** [comment]
Sure, I use Chrome and Edge in parallel and I believe Firefox wont give much in future, but if you want to deliver leaflet to Windows guy w/o insisting for specific browsers it would be great.

**Comment by ocefpaf** [comment]
Folium devs don't really have the energy to focus on a specific browser so I am closing this issue. However, I would be happy to review a PR.
