### ISSUE TITLE
CircleMarker pixel size

### ISSUE THREAD

**Issue by rornor** [python-visualization/folium#491]
If I add CircleMarker, it has fixed size (in geo units). Zooming it makes it too large, while zooming out makes it too small. This does not make sense to me for a Map Marker.

Is there anything I can do to make it in fixed pixel size?

**Comment by rornor** [comment]
This exists in master - Circle and CircleMarker are separated.
It works as expected.

**Comment by ocefpaf** [comment]
Thanks following on this @rornor!
