### ISSUE TITLE
Add legend to map

### ISSUE THREAD

**Issue by klonuo** [python-visualization/folium#492]
This is easy in leaflet JS, but for me impossible to frustration with folium.

I created DIV element as expected legend by leaflet, then tried to add it into map through `folium.map.Html` - nothing shows. Browsing the repo does not reveal anything related to legend except 'legend_name' argument to choropleth map.

I then looked at `branca` but found nothing except iframe, which of course did nothing for my legend.

I can not even inject literal HTML code, as map has to be rendered.

This floats alone too: http://stackoverflow.com/questions/37466683/create-a-legend-on-a-folium-map

Any tips?

**Comment by klonuo** [comment]
Well, I'm still interested in this and would let you close the issue.

In the meantime I generated DIV element and I put it in the script section of generated map. It works nice. I probably can automate this insertion, but I'm sure that there is (or should be) better way to add legend to a map.

**Comment by ocefpaf** [comment]
@klonuo a PR would be most welcomed. We do not have the man power to implement this.

> In the meantime I generated DIV element and I put it in the script section of generated map

That is a fair strategy for prototyping (and I recommend you sending that to the SO question) but for folium it would be nice to have that implemented as a plugin.

**Comment by ocefpaf** [comment]
Closing this as stale. Adding legends to maps is still an interesting feature to have but not a priority at the moment.
