### ISSUE TITLE
How do i customize my own jinja template?

### ISSUE THREAD

**Issue by afidegnum** [python-visualization/folium#494]
by default only plain maps are generated, i would like to create a custom jinja template on which the map will be rendered.

any idea?

**Comment by kolewu** [comment]
Unfortunately there is no interface for this and since the templates are now embedded they cannot be easily overwritten.

But you can monkey patch the Figure class that is used internally as parent for the map:

```python
import os.path
from jinja2 import Template
from folium.element import Figure

tmplfname = "/path/to/your/jinja/template.j2"
if os.path.isfile(tmplfname):
    with open(tmplfname) as fo:
        tmpldata = fo.read()
else:
    tmpldata = u"""\
<!DOCTYPE html>
<!-- monkey patched Figure template -->
<head>
    {{this.header.render(**kwargs)}}
</head>
<body>
    {{this.html.render(**kwargs)}}
<script>
    {{this.script.render(**kwargs)}}
</script>
</body>
</html>
"""

Figure._mytemplate = Template(tmpldata)
def myFigureInit(self, *args, **kwargs):
    self.__init_orig__(*args, **kwargs)
    self._template = self._mytemplate
Figure.__init_orig__ = Figure.__init__
Figure.__init__ = myFigureInit
```

But beware: the map-div may interact badly with your template, especially when you are not using bootstrap.

This monkey patch works for the current stable version 0.2.1.

**Comment by ocefpaf** [comment]
I would be open to a PR that implements that "officially." Such PR should target the `branca` module. More specifically https://github.com/python-visualization/branca/blob/master/branca/element.py#L230-L284

**Comment by rl-utility-man** [comment]
what would be involved in invoking the branca figure.to_dict() function on a Folium map?  if we could do so, would that return a dictionary that would make it straight forward and reasonably safe to insert folium map(s) into an appropriately designed custom jinja template of the form:

```
<!DOCTYPE html>
<html>
<head>
<!--custom header components-->
{{ head }}
</head>
<body>
<h1>Map!</h1>
{{ html }}
<p>And here's some text after the graph.</p>
</body>
<script>
{{ script }}
</script>
</html>
```
