### ISSUE TITLE
Adding Colormap to a map yields an assertion error

### ISSUE THREAD

**Issue by adamkgoldfarb** [python-visualization/folium#495]
Hi! Great work all. I love this package. 

After creating and implementing a colormap, when I do:

`m.add_children(colormap)`

I'm getting the same error as is displayed at the end of [this folium example notebook.](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Colormaps.ipynb)

`AssertionError: You cannot render this Element if it's not in a Figure.`

Not sure if this is upstream to be committed to conda, but I've tried a number of workarounds thus far, so if there's one extant I'm happy to use that as well.

Thanks,

Adam

**Comment by adamkgoldfarb** [comment]
Hello,

Happy to try to fix this in a PR if someone could point me to a way to bind a colormap Element to a figure beyond the add_children method.

Thanks,

Adam

**Comment by ocefpaf** [comment]
@adamkgoldfarb I could not reproduce that problem with latest `master` so maybe this is fixed or it is another problem I cannot reproduce here. Can you try it with the `dev` version and re-open this if the problem still exists?

I am working on a new release soon btw.

**Comment by kirtanp** [comment]
Might be useful for others. I had the precisely the same problem. I was importing colormap from branca. Once I  imported colormap from folium instead, it worked.
