### ISSUE TITLE
Using geopandas DataFrames in Choropleth Maps

### ISSUE THREAD

**Issue by psychemedia** [python-visualization/folium#499]
In passing, I noted that it's possible use geopandas in the context of `.choropleth()` by calling something like:

```
m.choropleth(
    #geodata is a geopandas geodataframe
    geo_str=geodata.to_json(),
    ...
)
```

which may feel more natural to some users.

If this is a widely used way of calling `.choropleth()`, adding a `geo_df` attribute to allow `geo_df = geodata` could make sense, but if it's an edge case it runs the risk of overcomplicating the interface to `.choropleth()` unnecessarily? 

One advantage of using `geopandas` dataframes is that it makes it easy to merge data from several geojson files that share a similar model.

```
import geopandas as gpd
import pandas as pd

#Not sure if there's another way of merging geopandas geodataframes?
#via http://gis.stackexchange.com/a/162661
geodata = gpd.GeoDataFrame( pd.concat( [gpd.read_file(f) for f in geojsonFiles], ignore_index=True) )

centre_lat,centre_lon=((geodata.bounds['minx'].min()+geodata.bounds['maxx'].max())/2,
                           (geodata.bounds['miny'].min()+geodata.bounds['maxy'].max())/2)
```

So if a list of geojson URLs was passed into `geo_path` they could be merged together? (This came up as a use case for me where I was trying to plot maps for an arbitrary number of administrative regions, each with their own geojson file.)

Adding in something to automatically set an appropriate zoom level based on bounds might also be handy?

**Comment by ocefpaf** [comment]
The `GeoJson` class can take a geopandas object. See http://nbviewer.jupyter.org/github/python-visualization/folium/blob/e7f9c831b5df20918ee5c58aaccabc56a5bff163/examples/GeoPandas.ipynb

So it is a matter of passing the geopandas object directly in https://github.com/python-visualization/folium/blob/f6c2d9fff9ca95d2eaee715b39dd058a584afd2a/folium/folium.py#L689-L690

**Comment by psychemedia** [comment]
@ocefpaf GeoJson can but `.choropleth()` doesn't.

**Comment by ocefpaf** [comment]
> @ocefpaf GeoJson can but .choropleth() doesn't.

That is why I said:

> So it is a matter of passing the geopandas object directly in https://github.com/python-visualization/folium/blob/f6c2d9fff9ca95d2eaee715b39dd058a584afd2a/folium/folium.py#L689-L690

Do you want to try sending a PR to add that functionality?

**Comment by psychemedia** [comment]
As I mentioned in original post, I'm not sure if something like a `geo_df` attribute adds too much clutter to the API, not least because it's too focused on `geopandas`, or whether the geopandas `.to_json()` route into `geo_str` is just something that should be documented?

If adding a `geo_df` attribute *is* a sensible way forward, how should it be handled? Simply as a conversion using `.to_json()` and then follow the `geo_str` route? Or more along the lines of however `GeoJson` works?

Also, should it accept one or more `geopandas` dataframes and try to merge them? eg should it be able to handle something like:

````
if isinstance(geo_df,list):
    geo_df=gpd.GeoDataFrame( pd.concat( geo_df, ignore_index=True) )
````
If so, then how should we go about testing that the geodataframes *can* be concatenated? eg what happens if the dataframes actually come from *geojson* files with different metadata?

**Comment by ocefpaf** [comment]
> As I mentioned in original comment, I'm not sure if something like a `geo_df` attribute adds too much clutter to the API, not least because it's too focused on `geopandas`, and if so whether the geopandas `.to_json()` route into `geo_str` is just something that should be documented?

The `.to_json()` should definitely be documented as that would work virtually with any object that has a `to_json` like method.

> If adding a `geo_df` attribute *is* a sensible way forward, how should it be handled? Simply as a conversion using `.to_json()` and then follow the `geo_str` route? Or more along the lines of however `GeoJson` works?

In fact nothing should change in the `choropleth` call. We should only update the docs mentioning that it can take a `GeoDataFrame` and then add a if-clause that passes this object to `GeoJson`. `GeoJson` will do the work later on. (I am not reading the code while I write this so it may not be as simple as I think it is.)

> Also, should it accept one or more `geopandas` dataframes and try to merge them? eg should it be able to handle something like:

I do not think it should take a list of `GeoDataFrames`. It is up to the user to concatenate them first. That will keep the code simple and any concatenation issues are up to the user.

**Comment by ocefpaf** [comment]
Partially address in #703 

(I am on the fence if we should write a thin wrapper to simplify the passing the data columns or not.)
