### ISSUE TITLE
TemplateNotFound: tiles/openstreetmap/tiles.txt

### ISSUE THREAD

**Issue by psychemedia** [python-visualization/folium#50]
Installing from git using Py 3.4:

`pip3 install git+https://github.com/wrobstory/folium.git`

 and running in IPython notebook:

```
import folium
folium.initialize_notebook()

map = folium.Map(location=[40, -99], zoom_start=4)
map.simple_marker([40.67, -73.94], popup='Add <b>popup</b> text here.')
map
```

I get the following error:

```
---------------------------------------------------------------------------
TemplateNotFound                          Traceback (most recent call last)
<ipython-input-2-4f6f4e763ad5> in <module>()
----> 1 map = folium.Map(location=[40, -99], zoom_start=4)
      2 map.simple_marker([40.67, -73.94], popup='Add <b>popup</b> text here.')
      3 map

/usr/local/lib/python3.4/dist-packages/folium/folium.py in __init__(self, location, width, height, tiles, API_key, max_zoom, zoom_start, attr)
    160             join_tile_path = functools.partial(os.path.join, 'tiles', tile)
    161             self.tile_types[tile] = {
--> 162                 'templ': self.env.get_template(join_tile_path('tiles.txt')),
    163                 'attr': self.env.get_template(join_tile_path('attr.txt')),
    164             }

/usr/local/lib/python3.4/dist-packages/jinja2/environment.py in get_template(self, name, parent, globals)
    789         if parent is not None:
    790             name = self.join_path(name, parent)
--> 791         return self._load_template(name, self.make_globals(globals))
    792 
    793     @internalcode

/usr/local/lib/python3.4/dist-packages/jinja2/environment.py in _load_template(self, name, globals)
    763                                          template.is_up_to_date):
    764                 return template
--> 765         template = self.loader.load(self, name, globals)
    766         if self.cache is not None:
    767             self.cache[name] = template

/usr/local/lib/python3.4/dist-packages/jinja2/loaders.py in load(self, environment, name, globals)
    111         # first we try to get the source for this template together
    112         # with the filename and the uptodate function.
--> 113         source, filename, uptodate = self.get_source(environment, name)
    114 
    115         # try to load the code from the bytecode cache if there is a

/usr/local/lib/python3.4/dist-packages/jinja2/loaders.py in get_source(self, environment, template)
    223         p = '/'.join((self.package_path,) + tuple(pieces))
    224         if not self.provider.has_resource(p):
--> 225             raise TemplateNotFound(template)
    226 
    227         filename = uptodate = None

TemplateNotFound: tiles/openstreetmap/tiles.txt
```

**Comment by eriknylander99** [comment]
I'm still having this issue with pip install folium. Any chance of pushing out an update?

**Comment by ocefpaf** [comment]
@eriknylander99 we are due for a new release!  @birdage and @wrobstory I am preparing 0.14 today unless you have any objections.

**Comment by wrobstory** [comment]
Nope, go for it! I'll keep an eye out, so I can advertise the release on the twitters.

**Comment by ocefpaf** [comment]
@eriknylander99 here it is:

https://github.com/python-visualization/folium/releases/tag/v0.1.4

and PyPI:

https://pypi.python.org/pypi/folium

Let me know if your problems do with the Templates go away with this update.

**Comment by eriknylander99** [comment]
Filipe,
It works perfectly! Thank you so much for going ahead and pushing the
release out.

**Comment by ocefpaf** [comment]
No problem @eriknylander99 we need a little nudge every now-and-then to get things done :wink:

**Comment by bag189** [comment]
this is absolutely still an issue with python 2.7.  Any help would be much appreciated. 

---------------------------------------------------------------------------
TemplateNotFound                          Traceback (most recent call last)
<ipython-input-270-2632ee40708a> in <module>()
      4 # create empty map zoomed in on US
      5 folium_map = folium.Map(location=usa_center,
----> 6                         zoom_start=3,tiles='openstreetmap')
      7 
      8 # add a marker for every record in the filtered data, use a clustered view

C:\Users\name\Anaconda\lib\site-packages\folium\folium.pyc in __init__(self, location, width, height, tiles, API_key, max_zoom, min_zoom, zoom_start, attr, min_lat, max_lat, min_lon, max_lon)
    184 {% endmacro %}
    185 
--> 186 {% macro script(this, kwargs) %}
    187     {% if this.max_bounds %}
    188         var southWest = L.latLng({{ this.min_lat }}, {{ this.min_lon }});

C:\Users\name\Anaconda\lib\site-packages\jinja2\environment.pyc in get_template(self, name, parent, globals)
    810     def get_template(self, name, parent=None, globals=None):
    811         """Load a template from the loader.  If a loader is configured this
--> 812         method asks the loader for the template and returns a :class:`Template`.
    813         If the `parent` parameter is not `None`, :meth:`join_path` is called
    814         to get the real template name before loading.

C:\Users\name\Anaconda\lib\site-packages\jinja2\environment.pyc in _load_template(self, name, globals)
    772         if _make_traceback is None:
    773             from jinja2.debug import make_traceback as _make_traceback
--> 774         traceback = _make_traceback(exc_info, source_hint)
    775         if rendered and self.exception_formatter is not None:
    776             return self.exception_formatter(traceback)

C:\Users\name\Anaconda\lib\site-packages\jinja2\loaders.pyc in get_source(self, environment, template)
    233         p = '/'.join((self.package_path,) + tuple(pieces))
    234         if not self.provider.has_resource(p):
--> 235             raise TemplateNotFound(template)
    236 
    237         filename = uptodate = None

TemplateNotFound: tiles/mapquestopen/tiles.txt"
