### ISSUE TITLE
Python 3.4: AttributeError: 'Series' object has no attribute 'levels'

### ISSUE THREAD

**Issue by YasminFathy** [python-visualization/folium#500]
The line: **ws_binned = pd.value_counts(cuts).reindex(cuts.levels)** 
in (folium/examples/folium_vincent_markers.py) has an error which is "AttributeError: 'Series' object has no attribute 'levels'". 

This has been tested in python 3.4

To solve it, the line has to be replaced by:
**ws_binned = pd.value_counts(cuts).reindex(cuts.values.levels)**

**Comment by ocefpaf** [comment]
Thanks for the report @YasminFathy! There is a chance that the Vincent plugin will be remove in the next release. Still, if you want to send a pull request fixing that example it would be very welcomed!

**Comment by YasminFathy** [comment]
@ocefpaf I will send request to fix it. Another comment. If the line is replaced by:
**ws_binned = pd.value_counts(cuts).reindex(cuts.values.levels)**

There will be a warning which is **" FutureWarning: Accessing 'levels' is deprecated, use 'categories' ws_binned = pd.value_counts(cuts).reindex(cuts.values.levels)"**

Replacing levels by categories solves this warning:
**ws_binned = pd.value_counts(cuts).reindex(cuts.values.categories)**

**Comment by ocefpaf** [comment]
Fixed in #502.

Thanks @YasminFathy!
