### ISSUE TITLE
Python 3.4: AttributeError: 'Element' object has no attribute 'html'

### ISSUE THREAD

**Issue by YasminFathy** [python-visualization/folium#501]
This has been tested in python 3.4

The line: **buoy_map.save(outfile='NOAA_buoys.html')**
in (folium/examples/folium_vincent_markers.py) causes an error which is "AttributeError: 'Element' object has no attribute 'html'". I tried to debug; it seems that the line: **root.render(**kwargs)**
in save method (in element.py) causes the error. However, replacing the line:  **buoy_map.save(outfile='NOAA_buoys.html')** by **buoy_map.save('NOAA_buoys.html')** solves the problem, but I can't figure out the reason.

**Comment by ocefpaf** [comment]
@YasminFathy haven't update the examples in the last few releases (and we are moving towards notebook examples). Do you want to send a PR fixing that? Maybe even convert that one to notebook altogether?

**Comment by YasminFathy** [comment]
@ocefpaf I have figured out the problem. The line **buoy_map.save(outfile='NOAA_buoys.html')** is correct. However, the problem is that **polygon_marker** should be replaced by **folium.RegularPolygonMarker** popup should be folium.Popup (similar to this example http://github.com/python-visualization/folium#vincentvega-markers). Please check pull request #502 for more details.

**Comment by ocefpaf** [comment]
Yeah. We changed the syntax but never updated the examples. Thanks for tackling that!

**Comment by ocefpaf** [comment]
This was fixed in #502. Closing it.

Thanks @YasminFathy!
