### ISSUE TITLE
Can Folium overlay geotiff images on a base map? It would be nice.

### ISSUE THREAD

**Issue by zhang01GA** [python-visualization/folium#517]
overly a satellite image on to base maps?

**Comment by ryanbaumann** [comment]
@zhang01GA Lot's of options, but the first one that comes to mind is to create a [Mapbox style with your geoTiff](https://www.mapbox.com/help/import-imagery/), and add your Mapbox style as your Folium raster base map.

**Comment by ocefpaf** [comment]
@zhang01GA what @ryanbaumann said above is one way. Another one is to use the `ImageOverlay` plugin in `folium`. Check the examples below.

http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/ImageOverlay.ipynb

http://nbviewer.jupyter.org/github/ocefpaf/folium_notebooks/blob/master/test_image_overlay_gulf_stream.ipynb
