### ISSUE TITLE
Additional parameters for CircleMarker

### ISSUE THREAD

**Issue by carderne** [python-visualization/folium#524]
I just started using Folium and it's blowing me away. I spent ages googling looking for Python mapping packages, but don't know JS at all so avoided that end and somehow never found this project.

I have quite a strange use-case, that is plotting hundreds of circles on an even grid. How they look is then quite important. How easy is it to add some further parameters for CircleMarker? For my application I'm trying to control the stroke (or remove it). But also to add customised click/hover actions.

I tried to go through your code, but I'm not sure where exactly the border between folium and leaflet is, so I don't know how simple this is to implement. I'm also interested what if any communication there is between folium and ipyleaflet?

**Comment by olibchr** [comment]
Check out my issue request #523

**Comment by carderne** [comment]
Great! Could you share your new features.py or should I just wait for it to merge?

**Comment by ocefpaf** [comment]
Just implemented that in #683
