### ISSUE TITLE
Trying to "freeze" a script with folium

### ISSUE THREAD

**Issue by aricl86** [python-visualization/folium#529]
Hi,
I've written a wx GUI script in Python 2.7 with folium 0.2.1 as its mapping module.
I'm using cx_freeze, and everything compiles, except for folium - which throws the following message when I'm trying to open the .exe file (attached as an image).

Any ideas?

Regards,
![error_cx_freeze](https://cloud.githubusercontent.com/assets/22939511/19525571/136f282a-962a-11e6-835d-494eb961da25.jpg)

**Comment by ocefpaf** [comment]
I am unfamiliar with `cx_freeze`. Can you check if the file `folium/templates/color_scale.js` is in your distribution? How are you installing `folium`? I can see that file in the `PyPI` source btw.

Note that the next version of `folium` will use [`branca`](https://github.com/python-visualization/branca) and the `colormap` functionally lives there. So, unless you want to send a bugfix PR to the `v0.2.1` branch there is nothing we can do in `folium`. But feel free to raise it in `branca`.
