### ISSUE TITLE
Clean ups

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#533]
Revise the files in `folium/templates`.

**Comment by naman** [comment]
What exactly needs to be done in this issue?

**Comment by ocefpaf** [comment]
I should have been more specific. In the old days `folium` relied on. Many templates to render the HTML. Some are still used in the testing phase but some are probably not used at all since @BibMartin introduced the plugin-like classes. So should find those that are not used, remove them. Find those that are used only for the testing and re-write the test in a way that they are no longer needed.

Maybe this is not a good issue for a beginner, even though it is a low hanging fruit it will requite some knowledge of `folium` internals.

**Comment by ocefpaf** [comment]
Closing this b/c I already started to implement it, but it seems to be a never ending task :smile:
