### ISSUE TITLE
color legend example breaks in examples/GeoJSON_and_choropleth.ipynb 

### ISSUE THREAD

**Issue by LiamHe** [python-visualization/folium#538]
In a cell which contains 

    colormap.caption = 'Unemployment color scale'
    colormap.add_to(m)
    m

whenever I try to evaluate it,  there will be an assertion error:

AssertionError                            Traceback (most recent call last)
/usr/local/lib/python3.5/site-packages/IPython/core/formatters.py in __call__(self, obj)
    341             method = _safe_get_formatter_method(obj, self.print_method)
    342             if method is not None:
--> 343                 return method()
    344             return None
    345         else:

/usr/local/lib/python3.5/site-packages/folium/map.py in _repr_html_(self, **kwargs)
    177             self._parent = None
    178         else:
--> 179             out = self._parent._repr_html_(**kwargs)
    180         return out
    181 

/usr/local/lib/python3.5/site-packages/folium/element.py in _repr_html_(self, **kwargs)
    367 
    368         """
--> 369         html = self.render(**kwargs)
    370         html = "data:text/html;base64," + base64.b64encode(html.encode('utf8')).decode('utf8')  # noqa
    371 

/usr/local/lib/python3.5/site-packages/folium/element.py in render(self, **kwargs)
    357         """Renders the HTML representation of the element."""
    358         for name, child in self._children.items():
--> 359             child.render(**kwargs)
    360         return self._template.render(this=self, kwargs=kwargs)
    361 

/usr/local/lib/python3.5/site-packages/folium/element.py in render(self, **kwargs)
    665 
    666         for name, element in self._children.items():
--> 667             element.render(**kwargs)

/usr/local/lib/python3.5/site-packages/branca/colormap.py in render(self, **kwargs)
    290         self.tick_labels = legend_scaler(self.index)
    291 
--> 292         super(ColorMap, self).render(**kwargs)
    293 
    294         figure = self.get_root()

/usr/local/lib/python3.5/site-packages/branca/element.py in render(self, **kwargs)
    588         """Renders the HTML representation of the element."""
    589         figure = self.get_root()
--> 590         assert isinstance(figure, Figure), ("You cannot render this Element "
    591                                             "if it's not in a Figure.")
    592 

AssertionError: You cannot render this Element if it's not in a Figure.

------
My folium version is 0.2.1

**Comment by LiamHe** [comment]
Problem solved when I update to new version via source.

**Comment by ocefpaf** [comment]
Thanks for reporting this @LiamHe! Bare in mind that latest `master` is unstable and you may find more trouble, like #534, down the road. I hope do issue a new release soon.
