### ISSUE TITLE
Programmatic layer display in folium

### ISSUE THREAD

**Issue by cloud05** [python-visualization/folium#543]
Good day! I would like to ask whether the feature to show/hide specific layers is already in folium? Here's a link to have an idea of what I'm talking about. Thank you for everybody's hard work! [http://rstudio.github.io/leaflet/showhide.html](url)

**Comment by ocefpaf** [comment]
Check the `FeatureGroup` example:

http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/FeatureGroup.ipynb

Feel free to improve it to use layers, lines, and JSONs like the one you posted above :smile:
