### ISSUE TITLE
Add tiles notebook example/test

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#556]
https://github.com/ocefpaf/folium_notebooks/blob/master/test_tiles.ipynb

**Comment by HashCode55** [comment]
Do I like just need to port that file in this repository or am I getting it wrong?

**Comment by ocefpaf** [comment]
> Do I like just need to port that file in this repository or am I getting it wrong?

Kind of. Make sure the notebook runs and the tiles are properly display. Feel free to improve the text too :smile: 

I believe that MapQuest tiles needs addressing to. Not sure if there is a similar source for it or if we need to just remove it from the list.

**Comment by jsignell** [comment]
What functionality was MapQuest supposed to provide that was different or better than OpenStreetMap

**Comment by ocefpaf** [comment]
No functionality just a different "look." Some people liked it I guess... I actually never used it!

**Comment by ocefpaf** [comment]
Now that I think about it let's just remove the `MapQuest` options/code everywhere. See https://github.com/python-visualization/folium/issues/559

**Comment by ocefpaf** [comment]
Done in #560.

@HashCode55 #559 is a low hanging fruit. Do you want to try that one?

**Comment by HashCode55** [comment]
yeah I'll take that one
