### ISSUE TITLE
Removed MapQuest

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#559]
MapQuest tiles are no longer available. We should remove them from `folium`.

**Comment by ocefpaf** [comment]
@HashCode55  here is the gist of the changes needed:

Remove folder:
- https://github.com/python-visualization/folium/tree/master/folium/templates/tiles/mapquestopenaerial
- https://github.com/python-visualization/folium/tree/master/folium/templates/tiles/mapquestopen

Remove MapQuest references:
- https://github.com/python-visualization/folium/blob/master/folium/folium.py#L27-L28
- https://github.com/python-visualization/folium/blob/master/folium/map.py#L68-L69
- https://github.com/python-visualization/folium/blob/master/folium/map.py#L351-L352

Change to OpenStreetMaps:
- https://github.com/python-visualization/folium/blob/master/tests/test_folium.py#L414-L422

The README probably needs updating too.

**Comment by HashCode55** [comment]
I already removed them :). Just one thing though... should I just replace the tile used for testing in `test_folium.py` with any arbitary tile?

**Comment by ocefpaf** [comment]
> I already removed them :)

Awesome!

> should I just replace the tile used for testing in `test_folium.py` with any arbitrary tile?

Let's use `OpenStreetMaps` as that is probably more stable.
