### ISSUE TITLE
Support for Leaflet VectorGrid

### ISSUE THREAD

**Issue by adamkgoldfarb** [python-visualization/folium#563]
Hello! This is more of a question or feature request than an issue, but are there plans to eventually support [VectorGrid](https://github.com/Leaflet/Leaflet.VectorGrid)? 

I'm happy to work on an implementation if @BibMartin or @ocefpaf have suggestions for where to start.

Thanks!

**Comment by ocefpaf** [comment]
There are no plans but that would be an awesome addition!

> I'm happy to work on an implementation if @BibMartin or @ocefpaf have suggestions for where to start.

Take a look at the plugins and `GeoJSON` implementations. I will investigate this further next week to give you more than just that :grimacing:

**Comment by adamkgoldfarb** [comment]
Thanks, will do!

**Comment by adamkgoldfarb** [comment]
Circling back to this and hope to take a look this weekend, and just a note-- THANKFUL FOR @ocefpaf @BibMartin and the rest of the dev team! Happy Thanksgiving!

**Comment by ocefpaf** [comment]
> THANKFUL FOR @ocefpaf @BibMartin and the rest of the dev team! Happy Thanksgiving!

We all the devs are thankful for all folium users Issues and PRs. Happy :turkey: day!

**Comment by ocefpaf** [comment]
PR https://github.com/python-visualization/folium/pull/943 took a stab at it and it seems to be working. I would welcomed it as an external plugin but I'm not sure that should be in the core `folium` though.
