### ISSUE TITLE
Adding GPX-files

### ISSUE THREAD

**Issue by Damorck** [python-visualization/folium#566]
I´m considering working on the capability to add GPX-layers easy to the leaflet map by Folium by adding this one https://github.com/mapbox/leaflet-omnivore . And do you have a discussion board for dev on Folium? Thx for the good work.

**Comment by ocefpaf** [comment]
> And do you have a discussion board for dev on Folium?

We have a gitter channel but I'd rather discuss here as issues.

BTW `omnivore` would make a great `folium` plugin.

**Comment by ocefpaf** [comment]
Closing this as stale. The `mapbox/leaflet-omnivore` is a good candidate for an external plugin but maybe not something that should be in the core `folium`.
