### ISSUE TITLE
Map only displays data with FeatureGroups if LayerControl is the last thing added

### ISSUE THREAD

**Issue by ispmarin** [python-visualization/folium#570]
Hi, 

I´m working with simple layers with feature groups and noticed that if the call `m.add_child(folium.LayerControl())` is not the last one made before plotting the map, the data on the feature groups is not shown. 

For example, 

    m = folium.Map(location=[-23.66, -55.32])
    coords = [[-23.12, -46.2],[-23.87,-45.65],[-23.44,-46.11]]
    feat_group = folium.FeatureGroup()
    feat_group.add_child(plugins.HeatMap(coords))
    m.add_child(feat_group)
    m.add_child(folium.LayerControl()) # this call must be the last one
    m

things work fine, but if

    m = folium.Map(location=[-23.66, -55.32])
    coords = [[-23.12, -46.2],[-23.87,-45.65],[-23.44,-46.11]]
    m.add_child(folium.LayerControl()) # this call no is made here
    feat_group = folium.FeatureGroup()
    feat_group.add_child(plugins.HeatMap(coords))
    m.add_child(feat_group)
    m

no data is displayed. The same happens if the `Map` is defined as the return value of a function:

    def gen_map():
        map_line = folium.Map(location=[-23.66, -55.32])
        map_line.add_child(folium.LayerControl())
        return map_line

    m = gen_map()
    coords = [[-23.12, -46.2],[-23.87,-45.65],[-23.44,-46.11]]
    feat_group = folium.FeatureGroup()
    feat_group.add_child(plugins.HeatMap(coords))
    m.add_child(feat_group)
    #m.add_child(folium.LayerControl()) #doesn´t matter if this is called here or not, the data is not displayed
    m

Is is a bug?

**Comment by ocefpaf** [comment]
Adding it last is necessary because the class does not know about its childern until then. We could delay/refresh the rendering to allow that. PRs welcomed :wink:
