### ISSUE TITLE
Select visible layer from a feature group

### ISSUE THREAD

**Issue by ispmarin** [python-visualization/folium#571]
I´m using `FeatureGroup` and `LayerControl` to set a bunch of layers. When the map is drawn all layers are visible. Is there a way to show only one layer on rendering and keep `overlay == True`? 

The problem with using `overlay==False` is when more than one tile server is added: all options are the same, and now both the feature groups and the tile servers are options.

**Comment by ocefpaf** [comment]
I am not sure I follow. Can you try to put that as an example, or better yet, a PR :wink:

**Comment by battez** [comment]
Hi seconding this. A way to do it in Leaflet is given here:
[Toggle Initial Layer Visibiliity](http://stackoverflow.com/questions/27056581/how-to-toggle-initial-layer-visibility-in-leaflet-js
)
`var map = L.map('map').setView([52.814172, -2.079479], 9);

L.tileLayer('http://{s}.tile.stamen.com/toner/{z}/{x}/{y}.jpg', {
maxZoom: 18,
attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://creativecommons.org/licenses/by-sa/3.0">CC BY SA</a>.'
}).addTo(map);

// Left out layer-declarations, they are HUGE

anti_soc.addTo(map); // here it is

var overlayMaps = {
    "Anti-social behaviour" :anti_soc,
    "Criminal damage and arson": crim_dam,
    "Burglary": burg, 
    "Violence and sexual offences": viol,
    "Other theft": other_theft,
    "Vehicle crime": veh_crime,
    "Shoplifting": shoplift,
    "Public order": pub_ord, 
    "Robbery": robb,
    "Bicycle theft": bikes,
    "Drugs": drugs,
    "Theft from the person": theft_person,
    "Other crime": other_crime,
    "Possession of weapons": weap
};

L.control.layers(null,overlayMaps).addTo(map);`

**Comment by Conengmo** [comment]
This has been added in #772
