### ISSUE TITLE
How to draw a line on map?

### ISSUE THREAD

**Issue by 0x01Brain** [python-visualization/folium#573]
I have a dataset which is located on here for evacuation routes:
http://www.saintjohn.ca/en/home/cityhall/financeadmin/informationtechnology/opendata_catalogue/dataset_evacuationroutes.aspx

I am looking for a way to plot the line features using folium how can I do that?
How can I draw a line using you API?

**Comment by ocefpaf** [comment]
Check the [MultiPolyline](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/MultiPolyline.ipynb) and [Polyline_text_path](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Polyline_text_path.ipynb) out.
