### ISSUE TITLE
Popup encoding issue with Jupyter

### ISSUE THREAD

**Issue by nbonnotte** [python-visualization/folium#575]
Hi,

The string `u'Construction de mur ext\xe9rieur'` is displayed in a popup as `Construction de mur extÃ©rieur` inside a Jupyter Notebook. 

If I save the map in an HTML file, the problem disappear.

I'm using Python 2.7.9 with the following packages versions, among others:
```
folium==0.2.1
ipykernel==4.5.1
ipython==5.1.0
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.0
nbconvert==4.2.0
notebook==4.2.3
```

This issue seems related to the PR #95 and #135 ?

BTW, it is nonetheless a wonderful project! Thank you so much for it!

**Comment by ocefpaf** [comment]
I cannot reproduce that with the latest version. See my example and package version list here: http://nbviewer.jupyter.org/gist/ocefpaf/c9e6d0dc644c6d8a8bb777cdd57373fb

Let me know if that is fixed for you too.
