### ISSUE TITLE
Marker Cluster Color

### ISSUE THREAD

**Issue by jgoad** [python-visualization/folium#577]
Is there a way to color the Marker Cluster independent of how many markers are clustered into it? I have two marker cluster elements representing two separate category of locations. Even though they go into separate clusters as desired, the fact that they are colored by density make it impossible to differentiate between the two groups.

Thanks.

**Comment by ocefpaf** [comment]
Folium wraps this plugin: https://github.com/Leaflet/Leaflet.markercluster

I guess you should ask this question there.

**Comment by jgoad** [comment]
Thanks. I reviewed the issue below, and it seems that in order for this to be possible folium would have to allow for an Icon Create function to be passed when you create the cluster. 

https://github.com/Leaflet/Leaflet.markercluster/issues/255

**Comment by ocefpaf** [comment]
Do you want to send a PR for that? Seems feasible.

**Comment by Schweboo** [comment]
This is an excellent idea. I want to be able to show different coloured cluster markers for different cluster groups for RED and GREEN markers respectively. I would not mind if the clusters did. To change colour as you zoomed into the map. I could not see if a PR was raised for this....
