### ISSUE TITLE
Polyline as a circle to draw zones

### ISSUE THREAD

**Issue by Tuisto59** [python-visualization/folium#578]
Hello, I'm a simple french user of folium, I use it to make a travelling map of my ancestor for genealogical data.
(see more at http://peregrination.jimdo.com/)
I wrote to ocepaf and he said to me to post that to an Issue and someone else can make a PR and an example 
"""
Sending a PR (https://help.github.com/articles/about-pull-requests/) might be complicate for newcomers. So I recommend you to open an issue with your code and ask for help.
Others might do the PR for you.

Best,

-Filipe
"""

I see something I never seen before in folium, or maybe it's already exist and I just don't see.

When you create a polyline, and when the coordinate x1y1 and x2y2 are identical, you create a circle, and this circle don't change size with the zoom.

For me It's amazing, and I want to share this example, because it's really what I needed for my map.

Context :

For example, if in you're familly tree , your ancestors stay in a town during lot of generations, it's can be interesting to see what are these generation, and how many, because sometime you have lot of familly are gone from old ages, and lot of them stay in this town (it's called also "root town".

So with Basemap, Matplotlib and some tricks, I get this map. You can see the concentric circle, each are superimposed, and each color represents a generation. Also this is the same with the vector in the map.

http://peregrination.jimdo.com/galerie/

By error I create polyline with exact start - end x, y coordinate and I observe a Circle !

So I make this code to show you the same interest.

```
import folium

my_map = folium.Map(location=[0,0],tiles='Stamen Terrain',zoom_start=6)
folium.PolyLine([(0,0),(0,0)], color='red', weight=100, opacity=1).add_to(my_map)
folium.PolyLine([(0,0),(0,0)], color='blue', weight=75, opacity=1).add_to(my_map)
folium.PolyLine([(0,0),(0,0)], color='green', weight=50, opacity=1).add_to(my_map)
folium.PolyLine([(0,0),(0,0)], color='yellow', weight=25, opacity=1).add_to(my_map)
folium.PolyLine([(0,0),(0,0)], color='cyan', weight=5, opacity=1).add_to(my_map)
my_map.save('test_circle_color.html')
```

of course, the bigger size do to be draw in first to avoid the overlap of the smaller size (and so the smaller circle ;) )

Regards

**Comment by ocefpaf** [comment]
If someone wants to add an example like that to the gallery please send a PR to https://github.com/python-visualization/folium_contrib

Thanks @Tuisto59

**Comment by ocefpaf** [comment]
Closing this for now. I will add an example to the gallery soon.
