### ISSUE TITLE
Events when zooming

### ISSUE THREAD

**Issue by jsundram** [python-visualization/folium#580]
I'd like to draw CircleMarkers with a radius in meters (not pixels). I can compute (roughly) the # of pixels in a meter at a combination of zoom level and latitude via: 

```python
def meters_per_pixel(zoom, lat):
    """
    ground resolution = cos(latitude * pi/180) * earth circumference / map width
    via: https://gist.github.com/perrygeo/4478844
    """
    return (math.cos(lat * math.pi/180.0) * 2 * math.pi * 6378137) / (256 * 2**zoom)
```

However, since this is zoom-dependent, I'd like a way to redraw the circles when zoom level is changed. As far as I can see, there isn't an event that I can catch for this.

**Comment by ocefpaf** [comment]
Do you know of any leaflet plugin that implements this? I don't see an easy way to update the map from the python side due to the JS nature of the zoom.
