### ISSUE TITLE
Is there anyway to return the HTML as an image so it can display when a Jupyter Notebook hosted by GitHub

### ISSUE THREAD

**Issue by palewire** [python-visualization/folium#583]
Right now my HTML maps do not show up on GitHub. It would be cool if they could. Could an image work?

**Comment by ocefpaf** [comment]
GitHub scrubs off the JS from the HTML. The best option is to use `nbviewer` links because it preserves the one-to-one correspondence with the code on `GitHub` and keeps the interactivity. If you really need a static image take a look at https://github.com/python-visualization/folium/issues/35

**Comment by palewire** [comment]
Thanks for the tip. I'll try it out.
