### ISSUE TITLE
Request about zoomslider

### ISSUE THREAD

**Issue by osk4** [python-visualization/folium#588]
Hi, I want to use the zoomslider in the map.
I request the function of zoomslider in folium.

In case of leaflet
`var map = L.map('map',{ zoomsliderControl: true,zoomControl: false}).setView([lat, lng], 14);`

cf. http://www.jurigis.me/2015/03/23/zoomslider-in-leaflet/
I appreciate it.

**Comment by ocefpaf** [comment]
Looks like a nice addition. Unfortunately we do not have the cycles for that anytime soon. Care to try a PR?

**Comment by osk4** [comment]
If possible, I want to try it.
Thank you in advance.

**Comment by ocefpaf** [comment]
@osk4 I took a look at this and it is not complicated to implemente. However, `leaflet` already has the `+/-` buttons, the touch and mouse wheel interface to zoom. I am not sure we need another one. I consider this only extra aesthetics so I am closing this. (I am not against implementing it but I won't do it myself nor keep it here as a goal for folium devs. I would gladly review a PR :wink:)
