### ISSUE TITLE
can folium support just show map without the names of locations?

### ISSUE THREAD

**Issue by Michael728** [python-visualization/folium#591]
It's glad to find the cool tool to get maps. Now I want hide the names of locations because of some reasons, how do i realize the function?
Thanks

**Comment by ocefpaf** [comment]
You need to find tiles that do not have the names. See https://leaflet-extras.github.io/leaflet-providers/preview/ for a list of possible tiles.

**Comment by Michael728** [comment]
Thanks a lot
