### ISSUE TITLE
HOW can I set the map to always show popup?

### ISSUE THREAD

**Issue by Michael728** [python-visualization/folium#593]
I want to see the popup to know every name of the point, how to show them?

**Comment by ocefpaf** [comment]
This was not implemented yet. I am closing as a duplicate of https://github.com/python-visualization/folium/issues/210

**Comment by tshuangteng** [comment]
you can use the following code, with tooltip
```
tooltip = folium.Tooltip(permanent=True, text='<b style="white-space: nowrap">text content......</b>')
```
