### ISSUE TITLE
Question about boundingbox

### ISSUE THREAD

**Issue by jmbertoncelli** [python-visualization/folium#594]
Is it possible to now what is the current bounding box coordinate of the map object?
I would like to be able to use this information to issue a geo-spatial query  to retrieve data point within the current bounding box an possibly load them as markers.

thanks for your support and great work!

JM

**Comment by ocefpaf** [comment]
We can get bounds from features and other map objects. See http://nbviewer.jupyter.org/gist/ocefpaf/815b267199a1c1d4ac43f37cf8b8d4a8 for an example.

We could try to implement something for the map but it would be tricky to get a feedback of the zoom level. However, you can start a map with known bounds and use that.
