### ISSUE TITLE
Data size limit for displaying Feature Groups as Layers

### ISSUE THREAD

**Issue by pjandrews** [python-visualization/folium#599]
I'm creating a map with layers. If I filter the dataset to be small I noticed that layers are displayed but if I don't filter it then the layers are not displayed. I there was a way around this limitation?

Here's how I'm creating the map (df is a dataframe from pandas). The layers are being created by analyzing the unique values in the "opp" column.

```python
ddfg = defaultdict()
for opp in df['opp'].unique():
    ddfg[opp] = folium.FeatureGroup(name=opp)

mymap = folium.Map(location=[lat_mean, lon_mean], zoom_start=10, tiles='Stamen Toner')
for lat,lon,dts,opp,status in zip(df['lat'],df['lon'],df['Start_time'],df['opp'],df['status']):
    fill_color = ddcolor[opp]
    color = color_status(status)
    ddfg[opp].add_child((folium.CircleMarker([lat,lon],radius=75,popup=dts+' '+opp,color=color,fill_color=fill_color)))

for fg in ddfg.values():    
    mymap.add_child(fg)

mymap.add_child(folium.LayerControl())
mymap.save(r'c:\temp\mymap.html')
```

**Comment by ocefpaf** [comment]
If you can provide a minimum dataset that reproduces this I can investigate it for you. (Be aware that NaNs may interfere! Try to remove NaNs first.)

**Comment by pjandrews** [comment]
Thanks ocefpaf! The NaNs were the problem. Sorry for the misdiagnosis.

**Comment by ocefpaf** [comment]
No problem. We should catch those and issue an error. (PRs welcome :stuck_out_tongue_winking_eye: )
