### ISSUE TITLE
Describe Marker by GeoJSON/TopoJSON

### ISSUE THREAD

**Issue by NigelCleland** [python-visualization/folium#6]
# Marker Shapes and Locations

Currently Folium has the ability to create markers using simple shapes, e.g. generic Leaflet, Polygon, Circle markers.
One great aspect of these is the ability to easily bind Vincent visualisations to the map enabling greater detail at popup locations.

However, when working with a Chloropleth map the addition of these markers can obscure additional detail.
For example, a map similar to the one below could be significantly enhanced by binding Vincent visualisations to each particular location.

![nz_spot_price_map](https://f.cloud.github.com/assets/2712782/640509/cf6a906a-d2fa-11e2-9822-fb63d971abad.png)

That is a user could click on a particular location and be given additional info (e.g. Time Series).
Ideally this could be accomplished by binding regions to keys in a similar way to the chloropleth creation.
Except instead of data what the developer is binding is popup vincent visualisations.
I'm not entirely sure on the best way to undertake this and I feel as though it may be beyond my ability.
However all that may be required is the creation of markers as described by geographical data.

Unrelated note: Folium and Vincent are both very cool!

**Comment by timhowcroft** [comment]
I was wondering if this ever got implemented? It would be super useful for the project I'm working on.

**Comment by ocefpaf** [comment]
Folium underwent a major re-factor and we are re-visiting old issues.  That is some we all want to see implemented, but time is scarce.

With that said we need to generalize `onEachFeature` to take external Popups or to read data from the GeoJSON itself.

@BibMartin `onEachFeature` was removed on the re-factor.  Do you have any plans?

**Comment by BibMartin** [comment]
I guess this is part of the `simple-style` move we discussed in #198 and #266.
The Popup and Icons will have to be read from the GeoJson.

I'd suggest to keep all that in #198 to have centralized tracking.

**Comment by ocefpaf** [comment]
Referenced [here](https://github.com/python-visualization/folium/issues/198#issuecomment-161996012).  closing this to avoid duplication.
