### ISSUE TITLE
anaconda2 Python 2.7 ImportError cannot import name Map

### ISSUE THREAD

**Issue by bears34egc** [python-visualization/folium#611]
I have tried to upgrade after using pip to install.
`Requirement already up-to-date: folium in ./lib/python2.7/site-packages`

But I continue to get this when I try to import folium?
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/anaconda2/lib/python2.7/site-packages/folium/__init__.py", line 10, in <module>
    from .folium import Map
  File "/home/username/anaconda2/lib/python2.7/site-packages/folium/folium/__init__.py", line 10, in <module>
    from folium.folium import Map, initialize_notebook, CircleMarker
ImportError: cannot import name Map
```

**Comment by ocefpaf** [comment]
You have a mix of `pip` inside `anaconda` which may be hard to debug.

Try this:

```shell
conda create --yes -n TEST python=2.7 folium -c conda-forge
source activate TEST
> python -c 'import folium; print(folium.__version__)'
```

Thanks should show you that `folium` is working and the problem is probably your installation.

**Comment by bears34egc** [comment]
Ok. Thanks. I just did a pip uninstall, conda uninstall and then I installed from my ./anaconda2/lib/python2.7/site-packages directory
