### ISSUE TITLE
ClickForMarker - should it add markers to the map?

### ISSUE THREAD

**Issue by psychemedia** [python-visualization/folium#614]
I've just been having a quick play with `ClickForMarker()` [here](https://gist.github.com/psychemedia/5782feef6bef48fd27de8ed9475b2e45#file-simplemapdemo-ipynb) and it seems that the markers are added dynamically to the rendered map rather than the `folium` map object HTML.

Which makes me wonder what the use case? (E.g. I was imagining it might be used to help create and save a map with markers interactively with the user.)

**Comment by ocefpaf** [comment]
> Which makes me wonder what the use case? 

I guess that the original use case was to let people interact with the markers on a `Jupyter` notebook.
Updating the HTML with that information is quite challenging and I am not sure it is worth it. However, I would gladly merge a PR for that. Do you want to try?

**Comment by pepeto** [comment]
Please, if you have a solution for this, let me know
https://stackoverflow.com/questions/63366600/how-to-add-a-marker-manually-or-with-draw-plugin-folium-python-and-be-able-t
