### ISSUE TITLE
Polygon support

### ISSUE THREAD

**Issue by jagill** [python-visualization/folium#615]
I've implemented Polygon support on my local checkout of folium; now I can add polygon layers to my map.

Is this something you'd want a PR of?  If so, I've currently just copied the PolyLine class and modified it appropriately.  The leaflet polygon is itself a subset of polyline; would you rather I reflect that by inheriting from PolyLine?

**Comment by ocefpaf** [comment]
Please take a look at the `PolygonMarker` in the features module. That implements `L.polygon` and it seems to be the same you are talking about.

Maybe we should rename it... I don't really recall why we ended up with `PolygonMarker` install of `Polygon`.
