### ISSUE TITLE
add href to marker?

### ISSUE THREAD

**Issue by Nyahua** [python-visualization/folium#616]
Is it possible to add href to the marker's popup property so when I click it I can go to another web page/file?

**Comment by collinreinking** [comment]
popup = folium.Popup('<a href=" [URL GOES HERE] "target="_blank"> [text for link goes here]' </a>')

you can see an example of this in a notebook I am just now working on putting together:
https://github.com/collinreinking/longitude_latitude_dot_plots_in_python_with_folium/

**Comment by ocefpaf** [comment]
Thanks @collinreinking that is a good answer. Closing this as resolved.

**Comment by parsley3** [comment]
Hi @collinreinking : I used your line of code but the link is addressed to a local file rather than an online website. Can you explain more?
