### ISSUE TITLE
Complete official documentation missing?

### ISSUE THREAD

**Issue by ddcamiu** [python-visualization/folium#619]
I really likes the functionality of folium, but so far I cannot find a good documentation, especially for the advanced features. Each time I have to either google to some random blog or dig into source codes.

So far the best documentation I find is https://folium.readthedocs.io/en/latest/. However, all module description is empty there.

Appreciate your work! It will be good to know if a good documentation is available somewhere.

Thanks!

**Comment by ocefpaf** [comment]
Indeed the docs are lacking, but it has been a while that we dropped readthedocs. They are hosted here now: http://python-visualization.github.io/folium/

Still there is plenty of work to do there. PRs welcomed :wink:
