### ISSUE TITLE
Fullscreen in iframe

### ISSUE THREAD

**Issue by osk4** [python-visualization/folium#621]
The function of fullscreen is usefull, but if the webpage is in iframe, the button of fullscreen is invalid.
I want to use the button in iframe.

I appreciate it.

**Comment by ocefpaf** [comment]
I am not sure what you mean? The map HTML is in the iframe? Or are creating a page, pasting the map there , and that page is an iframe? The former should work b/c that is the same thing we do in the Jupyter notebooks. The latter I have no idea how to implement in a clean way and I don't think it is `folium`'s role to do it. If you can find a way to do it PRs are welcomed 😄

**Comment by osk4** [comment]
I think it's former. In iframe, the map is called by URL. (It's not pasted to other web page.)

If I push fullscreen butten in iframe , it's invalid. But I push fullscreen butten in other, it's valid.

**Comment by ocefpaf** [comment]
Can you put a [sscce](sscce.org) together?

**Comment by ikatza** [comment]
You need to pass the `allowfullscreen` atribute to the iframe in order to allow it to go fullscreen.

`                       
 <iframe id="Map"
               title="Map"
                allowfullscreen
                src="map.html" frameborder="1" height="60%" width="90%">
  </iframe>
`

**Comment by ocefpaf** [comment]
It seems that @ikatza nailed it!
