### ISSUE TITLE
Set map, markers, polylines id or class?

### ISSUE THREAD

**Issue by havardl** [python-visualization/folium#622]
Hi, 

I was wondering if it's possible to define a id or class for map, markers or polylines? I'm currently adding some code after generating the map, to be able to add custom events for the different elements on the map, which would be a lot easier if I could reference specific ids or classes. 

Is this currently possible?

**Comment by ocefpaf** [comment]
Everything is a `branca` element and all elements have a unique id. See https://github.com/python-visualization/branca/blob/master/branca/element.py#L41

Would that help you? But if I understood what you want to do you don't really need that. Keeping track of the objects in your script should be enough.

**Comment by havardl** [comment]
I actually need to define classes for multiple markers and polylines, to be able to select them as groups to for example show/hide them based on user input in the generated map. Is this possible?

**Comment by ocefpaf** [comment]
Take a look at http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/FeatureGroup.ipynb
