### ISSUE TITLE
Linear colormaps using .choropleth and pandas

### ISSUE THREAD

**Issue by andy-carter-encraft** [python-visualization/folium#628]
Is it possible to use a linear colormap when building a choropleth from pandas using the map.choropleth method? I've read the documentation and and the jupyter notebook docs, which explain how to use a linear colour map when building from a GeoJSON, but not when using the key_on and columns keywords.

Is there a way to replace the threshold_scale and fill_color args in my code and get an equivalent linear colour scale without breaks?

```python
import folium

#Let Folium determine the scale
map = folium.Map(location=[53, -1], zoom_start=7)
map.choropleth(geo_path='./updated-file2.json',
               threshold_scale=[50,55,60,65,70,75],
               data=master, key_on='feature.properties.lad16nm', 
               legend_name='Average SAP Rating by region',
               fill_color='PRGn',columns=['NewName', 'SAPRatingAve'], highlight=True)
map.save('epcmap.html')`
```

**Comment by andy-carter-encraft** [comment]
I decided to build piecewise by feature as per the example and have it working fine. Enjoying working with new found layer and layer control things!

Is the .choropleth method to be depreciated?

**Comment by ocefpaf** [comment]
> Is the .choropleth method to be depreciated?

In a way yes. I guess it will be there for a while as a legacy method.
