### ISSUE TITLE
Folium not working in Jupyter Notebook with Microsoft Edge (Windows 10, python 3.6.0)

### ISSUE THREAD

**Issue by JonathanJHull** [python-visualization/folium#629]
I get nothing but a blank screen area when running the following example from the May 18, 2017 folium.pdf in Jupyter Notebook with Microsoft Edge:

import os
import numpy as np
import pandas as pd
import folium

map_osm = folium.Map(location=[45.5236, -122.6750])
map_osm.save('osm.html')
map_osm

It works in Firefox, so I guess I'll just use it instead of Edge.  That's not a big deal, but I wanted to pass this info on in case it saves someone else an hour out of their lives in debugging :).

**Comment by ocefpaf** [comment]
It is a known bug but we don't aim to support edge at the moment. Sorry.
