### ISSUE TITLE
Ability to rotate custom markers

### ISSUE THREAD

**Issue by wlei6277** [python-visualization/folium#632]
Hi, how would I go about rotating a custom marker?

I want to rotate pointed arrows to show the direction of ocean swell but also want to use a custom image not the standard folium Icon 

Thanks :)

**Comment by ocefpaf** [comment]
Take a look at http://nbviewer.jupyter.org/github/python-visualization/folium/blob/d2c495b871c09dac656b4fc4f8b153e36f1eed14/examples/CustomIcon.ipynb and http://nbviewer.jupyter.org/github/python-visualization/folium/blob/d2c495b871c09dac656b4fc4f8b153e36f1eed14/examples/Rotate_icon.ipynb

BTW this is not an issue, but a use question. Please use the gitter channel for that next time.

**Comment by Conengmo** [comment]
Yes that’s right, they are different, the custom icon class doesn’t have a rotate option.

**Comment by xslittlegrass** [comment]
@Conengmo Thanks, but is there a way to achieve the that, without recreating different icons for different angles?

**Comment by Conengmo** [comment]
The regular folium Icon class uses this plugin under the hood:
https://github.com/python-visualization/Leaflet.awesome-markers

I don't see an option there to provide a custom image.

The custom icon class in folium uses the regular icon class from Leaflet. I don't see a rotate option there. If you search for 'leaflet icon rotate' you can find some jQuery/JS stuff to rotate the icons manually, so you'll have to hack it.
