### ISSUE TITLE
Cannot move a marker to the center when it is on the edge of the map

### ISSUE THREAD

**Issue by rdd9999** [python-visualization/folium#640]
When a marker is placed on the edge of the map, 
I can't move it to the center by drag-and-drop the map.
The map automatically goes back when I drop the mouse key.
I tried using FitBounds but it didn't help.
The sample code is as follows.

```
import folium

m = folium.Map(location=[56.66, 196.63], zoom_start=5)
folium.Marker(location=[56.66, 196.63]).add_to(m)
m.save('map.html')
```

**Comment by ocefpaf** [comment]
Did you try using longitudes in the range of -180..180 instead? According to [this](https://stackoverflow.com/questions/38820724/how-to-display-leaflet-markers-near-the-180-meridian) the 0..360 should work but I got the desired behavior with:

```python
import folium


m = folium.Map(
    location=[56.66, -163.37],
    zoom_start=5,
)

folium.Marker(location=[56.66, -163.37]).add_to(m)

m
```

**Comment by rdd9999** [comment]
It works. Thank you.
Another solution I found is to edit the generated .html file and delete the settings related to maxBounds.
Maybe the restriction is a default feature but I hope there is an option that I can disable it to avoid converting some data.

**Comment by ocefpaf** [comment]
> Another solution I found is to set `max_bounds = False` when initializing a map.

For some reason I though that was the `default` :confused: 

Do you fancy sending a PR to change that? (I am planning a new that will break some of the API anyways :smile:)

**Comment by rdd9999** [comment]
I haven't sent a pull request before...
Do I need fork it and then edit the corresponding source file?
