### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by QuLogic** [python-visualization/folium#642]
On https://python-visualization.github.io/folium/, the footer says it's 0.2.0 documentation, when 0.3.0 is the latest release.

**Comment by matsavage** [comment]
That link points to a 404 error at the moment, 

also https://folium.readthedocs.io/en/latest/ has no content for the ModuleDescriptions 

Is there any documentation on #643 ?

**Comment by ocefpaf** [comment]
> That link points to a 404 error at the moment, 
> also https://folium.readthedocs.io/en/latest/ has no content for the ModuleDescriptions

@matsavage the docs are under construction. PRs welcomed btw :wink: 

> Is there any documentation on #643 ?

The [docstring](https://github.com/python-visualization/folium/blob/73fcad735875ab7b31e683411eaf4dadd5d7368d/folium/features.py#L324-L352) and [this](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Features.ipynb) example (cells 6-7).

**Comment by matsavage** [comment]
@ocefpaf many thanks! This really is a great project.

**Comment by ocefpaf** [comment]
The docs are up, but still need some love:

http://python-visualization.github.io/folium/docs-v0.4.0/

Note that as a maintainer I do not have access to readthedocs. So I'll be publishing them as gh-pages for now on.
