### ISSUE TITLE
Enable multiple popups for one GeoJson, one fore each polygon in a GeoJson object

### ISSUE THREAD

**Issue by tmthyjames** [python-visualization/folium#645]
It's relatively easy to do it in leaflet but I can't figure out how to do it in Folium. Is this currently possible without creating multiple GeoJson objects?

For example, I can get it to work fine doing this:

```
gj = [
    folium.GeoJson(
        data={
            "type": "Polygon",
            "coordinates": [
                [list(j)[::-1] for j in eval(i.shape)]
            ],
            "properties": {
                'median_home_value': i.median_home_value,
                'county': i.county
            }
        }
    ) for i in DATA
]

[i.add_child(folium.Popup(i.data['properties']['county'] + " " + str(i.data['properties']['median_home_value']))) for i in gj]
[i.add_to(m) for i in gj]
m
```

But this is inefficient as it creates a new GeoJson object for every polygon.

*EDIT*: Possible duplicate of [497](https://github.com/python-visualization/folium/issues/497)

**Comment by ocefpaf** [comment]
> Possible duplicate of 497

Yep. Closing to keep the discussion there. (PRs welcome :wink:)

**Comment by pivosak** [comment]
I guess this is not solved - enable multiple popups for each polygon in GeoJson/GeoDataFrame

**Comment by Conengmo** [comment]
Hi @pivosak, anybody can contribute to folium, so if you need this feature you're welcome to create a pull request. Or help others creating it by providing ideas on how this could be done. But maybe do that in #497, since this issue is a duplicate.
