### ISSUE TITLE
Matplotlib ColorMaps?

### ISSUE THREAD

**Issue by jzf2101** [python-visualization/folium#646]
I'm trying to use matplotlib's colormaps and it looks like I'd have to a little bit of legwork to make it happen:

See: https://github.com/python-visualization/folium/issues/299

Could this be a feature as well?

**Comment by ocefpaf** [comment]
> I'm trying to use matplotlib's colormaps

What do you mean by `matplotlib`'s `colormaps`? Do you want a raster image as your colormap?

> and it looks like I'd have to a little bit of legwork to make it happen:

PRs to make that easier are always welcome :smile: 

Here is the current implementation of `colormaps`, maybe that helps you:

http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Colormaps.ipynb
