### ISSUE TITLE
Use local tiles downloaded with gMapCatcher

### ISSUE THREAD

**Issue by p3p1** [python-visualization/folium#647]
Hi, I downloaded offline tiles with gMapCatcher in a directory /home/pi/tiles
The gMapCatcher tiles use a different coordinates system as explained [here](https://stackoverflow.com/questions/18695623/leaflet-gmapcatcher-change-zxy-template). 
Hence, for example I have to point at this URL: `file:///home/pi/tiles/z0/x0/x1/y0/y1.png` 

Where z0, x0, x1, y0, y1 are calculated as shown in aforementioned link from my current location. 

The problem is that each tile has size of 256x256, and result is shown in attached screenshot. 
![screenshot_2017-08-01_16-33-09](https://user-images.githubusercontent.com/6834053/28876683-4784557a-779a-11e7-9b71-c1b9f77320ee.png)

Is there a way to select more than one tile to have a complete map greater than 256x256 size?

**Comment by ocefpaf** [comment]
I guess that the only solution is to limit the `max_zoom` to the tile you downloaded. Not sure if there is a leaflet option to not concatenate the tile when going over the size :-/
