### ISSUE TITLE
Map border

### ISSUE THREAD

**Issue by mengjade** [python-visualization/folium#648]
Is it possible to use (min_lat, max_lat, min_lon, max_lon) to set the boundaries of the map?
This is my current code:

```python
m = folium.Map(location=[43, -79], tiles="Cartodb Positron", zoom_start=12, min_zoom = 11)
```

**Comment by bokkenka** [comment]
You can use m.fit_bounds(bounds).  I don't think it sets the exact boundary, but it will zoom the map to fit what bounds you give it.  The bounds can be points, lines, polygons, whatever you want to give it.  So you could create you map m and use m.fit_bounds((max_lat, max_lon), (min_lat, min_lon)).

Open https://github.com/python-visualization/folium/blob/master/folium/map.py#L750 to see what options there are.

**Comment by ocefpaf** [comment]
Thanks @bokkenka! That is one way to do it. Another way is via the min, max limits. See http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/MinMaxLimits.ipynb
