### ISSUE TITLE
Missing styling documentation

### ISSUE THREAD

**Issue by deeplook** [python-visualization/folium#649]
1. `Folium` rocks! Thx so much for working on it!

2. I'm exploring it now, and trying to style some GeoJSON was much harder than expected, largely because I couldn't find any documentation on expected property names (for `folium`, I know there aren't for GeoJSON). After a while I've sniffed into the code, and saw that e.g. `fillColor` should work. But then `strokeColor` doesn't (`color` does). I'm not sure this is very consistent and it's totally unclear to me which convention or standard is expected here?

3. I found I had to ask explicitly for styling the data using `folium.GeoJson(... styl_func=my_func).style_data()` or the `style_function` parameter would not be called, which was also a surprise and seemed not to be documented anywhere.

4.  `Folium`still  rocks!

**Comment by ocefpaf** [comment]
We are lacking behind the docs for a long while now. But `folium` is maintained by volunteers on their spare time, so I don't expect that to be solved anytime soon. (PRs welcomed :wink:)

**Comment by deeplook** [comment]
Cool. Is there any chat room to ask people, then, like IRC or slack?

**Comment by ocefpaf** [comment]
We have a gitter channel: https://gitter.im/python-visualization/folium

**Comment by ghandic** [comment]
PR #748 should help with this clarification.

Once the GeoJsonCss object is accepted I will more than happily add more documentation for a plethora of different styling options.

**Comment by Conengmo** [comment]
We currently do have some examples on GeoJSON styling: https://nbviewer.org/github/python-visualization/folium/blob/main/examples/GeoJSON_and_choropleth.ipynb#Styling

> I found I had to ask explicitly for styling the data using folium.GeoJson(... styl_func=my_func).style_data()

I don't think that's true anymore.
