### ISSUE TITLE
How to see several markers at exactly same coordinates ?

### ISSUE THREAD

**Issue by yguel** [python-visualization/folium#650]
Dear all,
I used a centimetric GPS in a data gathering campaign. We record at the same place several data (GPS receiver fixed) and in some case, the exact same coordinates are recorded. 

I plot markers for each data with folium on a map and I would like to be able to circle on all the markers exactly at the same place. Is-there a way to do that ? A keyboard shortcut when clicking maybe ?

Maybe, it is not an existing feature ?

Thanks in advance for the info.

**Comment by ocefpaf** [comment]
I am not sure about what you want to do exactly but take a look the [`MarkerCluster`](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/1000_MarkerCluster.ipynb) example.

**Comment by yguel** [comment]
MarkerCluster does not make the job, since I do not know in advance that several points will have the exact same coordinates.

**Comment by ocefpaf** [comment]
> MarkerCluster does not make the job

Oh yes. I am not sure what is the best strategy for you there.

I would ask that question in https://gis.stackexchange.com/ and leaflet keywords. (If `leaflet` or its plugins can do `folium` can wrap it :wink:)

**Comment by yguel** [comment]
Thanks a lot for the idea, I will post my question on that forum you mention.
- all the best.

**Comment by ocefpaf** [comment]
Thanks and sorry for not being able to help much. Feel free to xref the post there with the issue here.
