### ISSUE TITLE
Popup Cant Display On Folium Map Python3.6 Anaconda sypder

### ISSUE THREAD

**Issue by Maggie1216** [python-visualization/folium#651]
Hi

I just replaced Python2&Pythonxy with Python3.6&Anaconda and I'm trying a simple visualization.
Here is the code:

```python
a=folium.Map()
folium.Marker([40,116],popup='hi').add_to(a)
```

Problem is, I should see a marker and if clicked see a popup message 'hi'.
But I can only see the marker without message.
Also, cannot use the Laglong_popup (something like this) feature as well, for the popup message cannot be triggered.
Does anybody know why?
BTW, it works fine yesterday when I was a Python2&Pythonxy user!
Thanks much fellows!

**Comment by Maggie1216** [comment]
folium 0.3.0 version

**Comment by ocefpaf** [comment]
There is nothing wrong with your code and that works just fine for me. See http://nbviewer.jupyter.org/gist/ocefpaf/a2ddeb9ec726b015466edd65306c823a

I am not a `spyder` user to debug what is going on under the hood there. Sorry. 
Maybe you should ask that question in a `spyder` forum or something.
