### ISSUE TITLE
MarkerCluster as normal layer

### ISSUE THREAD

**Issue by ulemanstreaming** [python-visualization/folium#652]
Is it possible to treat a MarkerCluster as a normal (overlay) layer?

- Give it a name (the _name_ parameter listed in 0.2.0 docs is not supported in 0.3.0)
- Have it show up in the layer control (adding LayerControl to a map with a MarkerCluster does nothing)
- Configure color and styling of markers and cluster indicators
- Support multiple MarkerCluster layers on a single map (when I add three MarkerClusters to the same map I actually get three separate world maps)

I don't know if any of the above is already possible but assume that most of this would be feature requests that would take a bit of work.

Or maybe there's another way to get one or more layers containing point markers in a clustered view onto a map?

**Comment by ocefpaf** [comment]
I believe that you want something like [this](https://ocefpaf.github.io/python4oceanographers/blog/2015/12/14/geopandas_folium/). That is an old example but should help you get started.

**Comment by ulemanstreaming** [comment]
Thank you @ocefpaf ! Works perfectly. (Trivial changes to the API since you wrote that were easily fixed.)

**Comment by ocefpaf** [comment]
Glad that was useful. If you have a nice example consider sending to https://github.com/python-visualization/folium_contrib

**Comment by ulemanstreaming** [comment]
I will have to replace my proprietary data with some made-up stuff and simplify the code a bit, and will do.

Meanwhile, I do have a follow-on question. Your example and my code address three of the four bullets I listed above. The one thing I cannot figure out is how to set the marker icon and color for each of my featuregroups, and also the color/styling of the cluster indicators (if that's even possible). So far, the only approach I've seen is to explicitly loop through each dataframe and add individual markers. I'm trying to avoid such loops, especially since in this case the marker style would be the same for an entire featuregroup.

For reference, here's my (somewhat anonymized) code. I'm just trying to plot three point data sets on one map (clustered), distinguishing the three by their marker styles. (Obviously, the fact that my data is in pyspark DataFrames is not relevant to the mapping aspect.)

```python
import folium
from folium.plugins import MarkerCluster

m = folium.Map(location=[40, -100],
                 zoom_start=2,
                 control_scale=True
                )
c = folium.FeatureGroup(name='C')
a = folium.FeatureGroup(name='A')
p = folium.FeatureGroup(name='P')

# df_gc_* are pyspark DataFrames, geocoded.
c_loc = df_gc_c.select('latitude', 'longitude').collect()
c_lbl = (df_gc_c.select(concat_ws('\n', 'name', 'site').alias('label'))
                .toPandas()['label'].values.tolist())
a_loc = df_gc_a.select('latitude', 'longitude').collect()
a_lbl = (df_gc_a.select(concat_ws('\n', 'name', 'site').alias('label'))
                .toPandas()['label'].values.tolist())
p_loc = df_gc_p.select('latitude', 'longitude').collect()
p_lbl = (df_gc_p.select(concat_ws('\n', 'company', 'city').alias('label'))
                .toPandas()['label'].values.tolist())

_ = c.add_child(MarkerCluster(locations=c_loc, popups=c_lbl)).add_to(m)
_ = a.add_child(MarkerCluster(locations=a_loc, popups=a_lbl)).add_to(m)
_ = p.add_child(MarkerCluster(locations=p_loc, popups=p_lbl)).add_to(m)
_ = folium.LayerControl().add_to(m)
_ = folium.plugins.Fullscreen().add_to(m)
m
```

**Comment by ulemanstreaming** [comment]
I discovered the `icons` parameter to the MarkerCluster constructor. But I can't seem to make it work. When I add a list of Icon specifications to one of the feature groups, the map loses all data and only shows a single standard marker at the map center, with no popup. And no layer control.

I modified the code above as follows:
```
# I inserted this line:
c_icons = [folium.Icon(icon='cloud', color='red')] * len(c_lbl)

# I added the icons parameter:
_ = c.add_child(MarkerCluster(locations=c_loc, popups=c_lbl, icons=c_icons)).add_to(m)
```
