### ISSUE TITLE
security issue: external source code?

### ISSUE THREAD

**Issue by bioprog** [python-visualization/folium#664]
When I check out the .html that folium creates, I see a ton of `<script>` and `<link>`
 tags that refer to websites that I have never even heard of.

Isn't this a huge security issue of the library if I dynamically access/execute source code from unknown sources on the internet every time that I open the .html that folium has created?
I mean someone could easily alter the source code that I'm accessing / executing dynamically, right?

**Comment by ocefpaf** [comment]
> When I check out the .html that folium creates, I see a ton of `<script>` and `<link>`
 tags that refer to websites that I have never even heard of.

Folium is built on top os JS libraries and those are JS links for the various libraries and plugins that `folium`, including `leaflet` itself. Most of them are quite well known in the mobile mapping world.

> Isn't this a huge security issue of the library if I dynamically access/execute source code from unknown sources on the internet every time that I open the .html that folium has created?

That is no different than browsing the web nowadays.

> I mean someone could easily alter the source code that I'm accessing / executing dynamically, right?

I am no JS security expert to comment on that. If you doubt the code there you can always use extensions like [noscript](https://noscript.net/) and investigate them before letting them run.

**Comment by bioprog** [comment]
When I reboot my computer (to circumvent any caching or whatever), turn off the wifi and open the .html file, I get the map. While loading (it's a big map) I see several messages appearing in the bottom left corner of the browser like e.g. "reading rawgit.com" among others.
But since there's no connection to the internet (I cannot visit any website in the browser since I've turned off the wifi), how does he access those libraries? Was I wrong to assume that he reads those "unknown internet sources" every time that I open the .html?

**Comment by ocefpaf** [comment]
> When I reboot my computer (to circumvent any caching or whatever)

As you already found out rebooting does not clear the browsing cache :smile: 

> From there on every time that a website demands the CDN resource, it is loaded from the cache (even after a reboot as my test has shown). Very interesting, I didn't know that. I was reading this link:
http://radar.oreilly.com/2015/04/how-to-leverage-the-browser-cache-with-a-cdn.html
(the section "Why use both?" was very useful to me)

:+1:
