### ISSUE TITLE
Missing Washington DC geo code in us-states.json

### ISSUE THREAD

**Issue by NoGoldFish** [python-visualization/folium#667]
Hi,

I am wondering whether I can get the geo code for District of Columbia just as the other states' in us-state.json file. 

thank you!

**Comment by ocefpaf** [comment]
All the JSONs used in out examples can be found [here](https://github.com/python-visualization/folium/tree/master/examples/data).

**Comment by NoGoldFish** [comment]
yeah, I downloaded the us-state.json from the example, and it is missing DC's geo code. :)

**Comment by ocefpaf** [comment]
That is all we have. This repo's goal is not to serve that, only `folium`. I am sure you can find more accurate data online.
