### ISSUE TITLE
Popup hyperlink to local file

### ISSUE THREAD

**Issue by EllRob** [python-visualization/folium#698]
Hi, 

Using the following lines of code,  I can create popups containing hyperlinks to local files. I'm using this as an offline file navigator for numerous files relating to different geographical locations:

`html = '<a href="file://C:\\Users\\(full file path etc)\\foo.pdf">foo</a>'`
`iframe = IFrame(html, width=width, height=height)`
`popup = folium.Popup(iframe, max_width=1000)`

However this uses an absolute filepath reference. Ideally I would replace this with a relative reference so that anyone with a different folder structure could still access the file (if I pass a zipped folder with the map and relevant files to them). 

Is this possible? 
If so, how should the relative path be written in the html line?

**Comment by ocefpaf** [comment]
This is not really a `folium` issue but a usage question regarding the final HTML generated. I recommend asking that in the gitter channel. (Let's reserve the issue tracker for software issue :smile:)

PS: if the files are on a server the usual URL relate path should work.

**Comment by EllRob** [comment]
Apologies, I figured this was enough along the lines of "is this possible in Folium?" (the relative filepath reference to a local file), which seems to be a somewhat common theme throughout the issue tracker! 
Thanks for suggesting the Gitter channel, I will investigate.

**Comment by ocefpaf** [comment]
> seems to be a somewhat common theme throughout the issue tracker!

Yep, and that is why I am ending it :wink: 

No mean to throw you off the issue tracker, but there are no paid devs here and I am trying to optimize the devs volunteer time by leaving the issue tracker lean and with things we can act on.
