### ISSUE TITLE
Mapbox Bright not available at higher zoom levels?

### ISSUE THREAD

**Issue by rutgerhofste** [python-visualization/folium#699]
`m = folium.Map(location=[lat, lon], tiles="Mapbox Bright", zoom_start=zoom_start)` 
`m`

returns a blank map when I set the zoom_start > 11

This is probably because of the availability of Mapbox Bright but maybe flag this is the documentation?

**Comment by ocefpaf** [comment]
Yep, that is expected. See this line from the docs:

https://github.com/python-visualization/folium/blob/89e5a0a566d58e4025e41c7e597af1f40d0a35f2/folium/map.py#L73
