### ISSUE TITLE
Visualizing data at the zip code level

### ISSUE THREAD

**Issue by ribonoous** [python-visualization/folium#71]
First and foremost, congrats for an extremely useful package! I just started playing with it, and I *love* it.

I am trying to visualize data at the zip code level (US zip codes), but don't know how to proceed. 

Say for example that I have:

```
 zip code     value
    02138       0.8
    30005       0.9
    98104       0.3
...
```

Is there any way to visualize this data in Folium? Do I need to create a Geo or Topo JSON with arcs for those zip codes?  Is such data perhaps available already somewhere?

If creating a Geo or Topo JSON file at the zip code level is unfeasible for some reason (or too much data to visualize), does anyone have recommendations about how to proceed about mapping zip codes to US counties? ( I could try to plot the average value above within each county)

**Comment by birdage** [comment]
i might suggest geojson, suggest looking at this [link](https://github.com/python-visualization/folium#geojsontopojson-overlays), and a quick google search got me the boundaries [here](https://github.com/ssoper/zip-code-boundaries)

**Comment by ocefpaf** [comment]
@ribonoous That is a great question.  However, that kind of question should be in a mailing list and not as an issue here.  Issues are eventually closed and the question is lost.

This is our fault!  We do not have a mailing.

For now I recommend you to post your question in the "http://gis.stackexchange.com/" and tag both folium and this issue URL.

Thanks.
