### ISSUE TITLE
Can't load file with GeoJson anymore

### ISSUE THREAD

**Issue by Brynnvincible** [python-visualization/folium#710]
If you try the following code on the current build you now get an error:

`folium.GeoJson(data=open("somefile.json"))`

This results in the error:
`ValueError: Unhandled object <_io.TextIOWrapper...`

Looking at the __init__ function for GeoJson there is no code path that deals with this scenario anymore. But the comments for the class indicate that this is still supported, and the documentation examples use the class this way.

This can still be worked around by passing in a string or a dict, but it could break existing code for people if they update.

**Comment by ocefpaf** [comment]
@Brynnvincible I shipped before I fixed the docs. Reading from buffer won't be supported in future versions. Please see #709 for more info on why.
