### ISSUE TITLE
No support for drawing a circle based on meters

### ISSUE THREAD

**Issue by mikedplace** [python-visualization/folium#711]
The documentation for CircleMarker indicates we should use "Circle" for drawing a radius based on meters, however there is no support for a "Circle" function in version 0.3.0.

**Comment by ocefpaf** [comment]
> The documentation for CircleMarker indicates we should use "Circle" for drawing a radius based on meters, however there is no support for a "Circle" function in version 0.3.0. 

Not sure what you mean. `Circle` and  `CircleMarker` are features classes. You can use them with

```python
from folium.features import CircleMarker, Circle
```
