### ISSUE TITLE
For icons why can we only choose a marker color from a set list and not use a html color code?

### ISSUE THREAD

**Issue by kindjacket** [python-visualization/folium#712]
Yet it is possible to change the color of the icon in the marker to anything.

```
class Icon(MacroElement):
    """
    Creates an Icon object that will be rendered
    using Leaflet.awesome-markers.

    Parameters
    ----------
    color : str, default 'blue'
        The color of the marker. You can use:

            ['red', 'blue', 'green', 'purple', 'orange', 'darkred',
             'lightred', 'beige', 'darkblue', 'darkgreen', 'cadetblue',
             'darkpurple', 'white', 'pink', 'lightblue', 'lightgreen',
             'gray', 'black', 'lightgray']

    icon_color : str, default 'white'
        The color of the drawing on the marker. You can use colors above,
        or an html color code.

**Comment by ocefpaf** [comment]
Feel free to submit a PR to improve the situation. I'll close b/c there is no real answer to "why?" That was not really by design, just convenience at the time of implementation.

**Comment by kindjacket** [comment]
@ocefpaf 
It's how it is because of how https://github.com/lvoogdt/Leaflet.awesome-markers is built. I'll see if I can change it there.

**Comment by Sti2nd** [comment]
I found de way! From Folium 0.6.0 there exists a BeautifyIcon in the plugins module https://python-visualization.github.io/folium/docs-v0.6.0/plugins.html

If you do 
`from folium import plugins`
you can use it!
