### ISSUE TITLE
Choropleth with time slider

### ISSUE THREAD

**Issue by halfdanrump** [python-visualization/folium#722]
Hi there. 

I think it'd be nice to have a class for easily creating choropleth maps with time sliders like this: http://bl.ocks.org/darrenjaworski/5397202

I've made a crude implementation, and I'd be happy to brush up the code and submit a pull request if there's interest :).

**Comment by ocefpaf** [comment]
Looks really nice. I'd gladly review a PR with that. Maybe you should take a plugin approach.

**Comment by halfdanrump** [comment]
@ocefpaf Thank you! I actually did just that, made a plugin. I use D3 directly to do some stuff, like creating and modifying the slider. Is that OK, or should I stick to pure leaftlet? 

PS. Just to be clear, the link I was referencing above is not my work. I simply used it to illustrate what I meant, as I haven't committed the code anywhere yet :).

**Comment by ocefpaf** [comment]
> Is that OK, or should I stick to pure leaftlet?

To be honest I'd have to look at the code first. It does sound useful, but we have to make it integrate with folium's API.

With that said, I am planning to factor `choropleth` out and make it a plugin. (It has been a while that we are planning to kill the `choropleth` method.)

**Comment by halfdanrump** [comment]
@ocefpaf I just created PR with the code as a plugin :)

https://github.com/python-visualization/folium/pull/736

**Comment by Conengmo** [comment]
This functionality has been added in #736/#741, so this issue can be closed.
