### ISSUE TITLE
Numbers in map marker in Folium

### ISSUE THREAD

**Issue by shubham039** [python-visualization/folium#734]
i want to display some geo locations on map, but i want the map-pin icon to display numbers instead of the default map pin.
Is there any way to do that?

I checked in font awesome icons but it didn't work.

Below is my code:

    import folium
    m = folium.Map(
        location=[45.3288, -121.6625],
        zoom_start=12,
        #tiles='Mapbox Bright'
    )

    folium.Marker([45.3288, -121.6625], popup='<i>Mt. Hood Meadows</i>').add_to(m)
    folium.Marker([45.3311, -121.7113], popup='<b>Timberline Lodge</b>',icon=folium.Icon(color='red')).add_to(m)
    m

[![enter image description here][1]][1]

What i want is instead of this default map marker i want to include numbers in my marker instead of `info-sign`

Something like this:

[![enter image description here][2]][2]

i couldn't find the answer anywhere. Any leads on this?

display number 1 to 9 inside map marker pin

  [1]: https://i.stack.imgur.com/lnfgf.png
  [2]: https://i.stack.imgur.com/uBhsf.png

**Comment by ocefpaf** [comment]
I don't think any of the markers we have can do that, You'll probably need https://github.com/coryasilva/Leaflet.ExtraMarkers or https://github.com/marslan390/BeautifyMarker

Do you want to send a PR to add them?

**Comment by shubham039** [comment]
@ocefpaf It would be useful if added

**Comment by shubham039** [comment]
@ocefpaf 
IN folium.Marker there is an attribute called icon, with properties
icon=folium.Icon(color='red',icon='thumbs-up')

There are many other icons available, apart from thumbs up, default being 'info-sign' , is there any icon in Font Awesome website which can display number in my map pin ?

**Comment by shubham039** [comment]
@ocefpaf Hello Sir, any update on feature request?

**Comment by ocefpaf** [comment]
@shubham039 folium is developed by people of their spare time from the day job. So no updates and no one will work on this anytime soon, unless you are willing to send a PR :wink:

**Comment by shubham039** [comment]
@ocefpaf Ohh! Okay Sir, i'll wait.
I have actually found a work around on this.

`icon_url = url_of_a_map_pin.png`
`icon = folium.features.CustomIcon(icon_url,icon_size=(24, 24))`

`folium.Marker(location=[45.3288, -121.6625],icon=icon).add_to(m)`

By the way, how do I send a PR ?

**Comment by ocefpaf** [comment]
> I have actually found a work around on this.

Yep. Custom icons are always an option.

> By the way, how do I send a PR ?

You can start with https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

**Comment by arthuralvim** [comment]
I'm working on this.
https://github.com/python-visualization/folium/pull/776

**Comment by Conengmo** [comment]
An edit of #776 is pending in #819

**Comment by Conengmo** [comment]
#819 has been merged.
