### ISSUE TITLE
Plugins ideas for a sprint

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#735]
- [ ] https://github.com/turban/Leaflet.Graticule
- [ ] https://github.com/cloudybay/leaflet.latlng-graticule
- [ ] https://github.com/marslan390/BeautifyMarker
- [ ] https://github.com/coryasilva/Leaflet.ExtraMarkers
- [ ] https://github.com/calvinmetcalf/leaflet-ajax
- [ ] https://github.com/stuartmatthews/leaflet-geotiff
- [ ] https://github.com/IHCantabria/Leaflet.CanvasLayer.Field
- [ ] https://github.com/aparshin/leaflet-GIBS
- [ ] https://github.com/turban/Leaflet.Zoomify
- [ ] https://github.com/commenthol/leaflet-rastercoords
- [ ] https://github.com/commenthol/gdal2tiles-leaflet
- [ ] https://github.com/makinacorpus/Leaflet.FileLayer
- [ ] https://github.com/mapbox/leaflet-omnivore
- [ ] https://github.com/Flexberry/Leaflet-WFST
- [ ] https://github.com/daniellsu/leaflet-betterscale
- [ ] https://github.com/perliedman/leaflet-realtime
- [ ] https://github.com/makinacorpus/Leaflet.LineExtremities
- [ ] https://github.com/teastman/Leaflet.pattern
- [ ] https://github.com/albburtsev/Leaflet.geojsonCSS

**Comment by AndyChallis1** [comment]
Just looked at https://github.com/albburtsev/Leaflet.geojsonCSS - looks similar to what I have just submitted for a pull request but in the TimestampedGeoJson Plugin. Happy to implement this wider using their layout

**Comment by ocefpaf** [comment]
@ghandic That would be nice! Do you want to submit in the same PR or do you want to close that and send a new one?

**Comment by ghandic** [comment]
I’ll do it in another pull request, also looking into the leaflet-search, I’m trying to maintain short branches so will do these in separate PR’s

Sent from my iPhone

On 13 Oct 2017, at 17:49, Filipe <notifications@github.com<mailto:notifications@github.com>> wrote:


@ghandic<https://github.com/ghandic> That would be nice! Do you want to submit in the same PR or do you want to close that and send a new one?

**Comment by ocefpaf** [comment]
Awesome!

**Comment by ghandic** [comment]
I'm going to look into https://github.com/albburtsev/Leaflet.geojsonCSS this week, should this be implemented as standard rather than a plugin?

**Comment by ghandic** [comment]
Thinking of incorporating BeafutifyMarker, ExtraMarkers into the Marker class rather than having two new classes.

I feel like I'm putting in too many PR! Haha, what do you think @ocefpaf

**Comment by ocefpaf** [comment]
There is no such a thing as too many PRs ;-p

I'm away from office though and I'll only be able to review than next week.

On Oct 18, 2017 9:16 AM, "Andy Challis" <notifications@github.com> wrote:

Thinking of incorporating BeafutifyMarker, ExtraMarkers into the Marker
class rather than having two new classes.

I feel like I'm putting in too many PR! Haha, what do you think @ocefpaf
<https://github.com/ocefpaf>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/python-visualization/folium/issues/735#issuecomment-337571335>,
or mute the thread

**Comment by prusswan** [comment]
What is needed to integrate plugins into folium? I wish it could work with arbitrary plugins (something like Plunker etc)

**Comment by ocefpaf** [comment]
Closing this for now. The list of plugin is still interesting but many of those can be implemented as external plugins.
