### ISSUE TITLE
Folium Cheatsheet

### ISSUE THREAD

**Issue by ghandic** [python-visualization/folium#750]
Idea for documentation - create a cheatsheet similar to the leaflet R library:

https://github.com/rstudio/cheatsheets/raw/master/leaflet.pdf

Also how do we get involved in the web documentation/design?

**Comment by ocefpaf** [comment]
> Also how do we get involved in the web documentation/design?

We use sphinx and a mix of ReST and notebooks to create the docs.

A cheatsheet  like that would be awesome, but I have no idea how to start the design of something like that.

**Comment by ghandic** [comment]
I’d happily take it on as a small project! It’ll get me away from all the PR’s I’ve put in 😉

Sent from my iPhone

On 25 Oct 2017, at 22:47, Filipe <notifications@github.com<mailto:notifications@github.com>> wrote:


Also how do we get involved in the web documentation/design?

We use sphinx and a mix of ReST and notebooks to create the docs.

A cheatsheet like that would be awesome, but I have no idea how to start the design of something like that.

**Comment by ghandic** [comment]
Check it out! http://www.andrewchallis.co.uk/category/python/python-a-folium-cheatsheet/

**Comment by sergiolucero** [comment]
Extraordinary work, Andy!

**Comment by ocefpaf** [comment]
This look awesome @ghandic! The only thing I would change, if possible, is to add syntax highlight to the code parts.

I would like to add a link to that to our docs. Do you want to send a PR for that? Something like:

    [Here](link) is a cheatsheet made by <your full name>.

probably in the beginning of the quick start section. (The quick start is auto-generated from [this notebook](https://github.com/python-visualization/folium/blob/master/examples/Quickstart.ipynb).)

**Comment by Conengmo** [comment]
Though I still love the cheatsheet, it's time to close this issue since it's quite stale. I'd love to have an overview like this in our documentation, but I think it should be part of it, not an external pdf.
