### ISSUE TITLE
How to use custom JS

### ISSUE THREAD

**Issue by mikie22** [python-visualization/folium#765]
How to build html file with FlyTo(leaflet) animation (How to add custom Java Script?)

**Comment by ocefpaf** [comment]
If you want to inject some `js` code that is hosted in a cdn you can use `JavascriptLink`.

However, `FlyTo` looks like a method we never implemented and should be part of the `map` object.
Do you fancy a PR to add that?

**Comment by mikie22** [comment]
Thx for response. 
I already found how to inject custom js into document. 
I've built a simple plugin which implement this and do some kind of fly to animation on the set of coordinates.

**Comment by ocefpaf** [comment]
Nice! Do you want to send a PR with that?

**Comment by ocefpaf** [comment]
Closing this as solved.
