### ISSUE TITLE
maintain the layer order (z level) when using the check boxes in layer control dropdown

### ISSUE THREAD

**Issue by Alcampopiano** [python-visualization/folium#767]
Thank you for this amazing tool. Being able to create these types of visualizations in python is a game changer for me at work. Quick question:

I am able to create layers of polygons on the map using the GeoJson method. However, when I toggle the checkbox from "unchecked" to "checked"  in the dropdown menu, the recently "checked" layer is placed on top of all other layers. So if there is a layer with popup properties (e.g.,  a set of markers), they can become covered up by the topmost polygon, and are then unclickable. 

Is there a way to maintain the layer ordering so that the layers are always placed in the order that they were added to the map during creation? I'm sure this is possible, but I haven't been able to figure it out. Any tip would be appreciated.

Sincerely,
Allan

**Comment by Alcampopiano** [comment]
Here is a simple example and screenshot. This issue is that I cannot seem to get the geoJson layer to stay on the bottom so that the markers/heat stays on top:

```
m = folium.Map(location=[43.45,-79.75], tiles='OpenStreetMap', zoom_start=12)

# geoJson layer
folium.GeoJson(
    geo_data,
    control=False,
    style_function=lambda feature: {
        'fillColor': colormap(some_dict[int(feature['id'])]),
    }
).add_to(m)

# Another layer
HeatMap(lats_lons, blur=1, gradient= {0.4: 'red', 0.65: 'red', 1: 'red'}, name='my_heatmap').add_to(m)

folium.LayerControl().add_to(m)
m
```

![heatmap_underneath_geojson](https://user-images.githubusercontent.com/4624246/32740526-3ccef9c8-c871-11e7-82b1-46558033aa0a.png)

**Comment by Alcampopiano** [comment]
Hi guys,
Any hints about keeping the heat map above the choropleth?

**Comment by Conengmo** [comment]
I think it has to do with Leaflet, not Folium. I tested combining a heatmap with a geojson polygon layer. The order in which you add them to the map does not matter. `autoZIndex` also does not seem to do anything. I wonder in what cases that option does work.

 If you look in the html, both are in the overlay pane. The heatmap is a canvas and gets a z-index of 100, while the geojson layer is a svg and gets a z-index of 200. This seems fixed in the leaflet css file. So to fix this you would need to look at leaflet, or maybe the [leaflet.heat](https://github.com/Leaflet/Leaflet.heat) plugin that Folium uses for the heatmaps.

A quick dirty fix is to append the following to your html file: `<style>.leaflet-heatmap-layer{z-index:300 !important}</style>` Any z-index higher than 200 does the trick. You can add it to a custom template as described in #86.

**Comment by ocefpaf** [comment]
@Conengmo you are correct. I'll keep this open in case we can come up with an easier zorder for all objects in `folium`, without relying on `leaflet`. Not sure what would take to implement that in a sane way though :smile:

**Comment by Alcampopiano** [comment]
Fantastic guys. Thanks very much for the info.

**Comment by Conengmo** [comment]
We have a `keep_in_front` method in `Map` that can be used to define which object should stay in front and in what order. See #840. I think that solves this issue. Feel free to add other info, we can reopen if needed.

**Comment by devtycoon** [comment]
keep_in_front is not working for me

Am I implementing it wrong?  

```python

```python
shp1 = folium.GeoJson(pipeline1, name='pipeline1', show=False).add_to(hmap)
shp2 = folium.GeoJson(pipeline1, name='pipeline2', show=False).add_to(hmap)

hmap_wide = HeatMap(rows,
                    min_opacity=0.2,
                    max_val=500,
                    radius=10, 
                    blur=15, 
                    max_zoom=1,
                    name='Inventory > 100')




hmap.keep_in_front(shp1, shp2, hmap.add_child(hmap_wide))


folium.LayerControl().add_to(hmap)
```
# with CSS hack
![with_hack](https://user-images.githubusercontent.com/16538715/49251304-681fbd80-f3de-11e8-86c2-937b95205bca.PNG)

# without CSS hack
![with_out_hack](https://user-images.githubusercontent.com/16538715/49251314-6eae3500-f3de-11e8-9b16-7a811a276582.PNG)

**Comment by JavierParada** [comment]
How can we solve this same issue with HeatMapWithTime instead of HeatMap?
