### ISSUE TITLE
Folium displays nothing if number of overlaid images > 80 on Chrome

### ISSUE THREAD

**Issue by duckworthd** [python-visualization/folium#768]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
import numpy as np
import folium
import folium.plugins

print folium.__version__

num_images = 80
images = np.random.rand(100, 100, num_images)
map = folium.Map()
for i in range(num_images):
    folium.plugins.ImageOverlay(
        image=images[..., i],
        bounds=[(10.0+i, 10.0+i), (11.0+i, 11.0+i)],
    ).add_to(map)
map
```
#### Problem description

Folium displays a blank map if the number of overlaid images exceeds 80. Note: this works fine with Firefox 57, but fails on Chrome 62.0.3202.62.

#### Expected Output

A map with 80 overlaid images.

#### Output of ``folium.__version__``
0.5.0

**Comment by zneu** [comment]
Similar issue. Large datasets do not render in a Jupyter Notebook in Chrome 65.0.3325.181, but render in Firefox 59.0.2 (64-bit), for Folium 0.5.0.

**Comment by Conengmo** [comment]
I don't know why it would work in Firefox but not in Chrome. I tried the code snippet and had no problem in Firefox (I don't have Chrome on this pc).

We've had an issue before about the limits of Notebooks. You can read about it in #787. 

Do you see any error messages in the Jupyter terminal?

Maybe you can try to save the map as html and open that file instead of displaying it in a Notebook. If  Jupyter is the problem, opening the separate html file should work.
`m.save('map.html')`

**Comment by Conengmo** [comment]
Related to #812

**Comment by lukalong** [comment]
Switching to Firefox also worked for me. Same issue as znue - imageOverlay of a single large raster dataset with Folium running in a Jupyter notebook gave a blank map in Chrome 68.0.3440.106. Renders fine in Firefox 61.0.2 (64-bit).

**Comment by ocefpaf** [comment]
Also related to https://github.com/python-visualization/folium/issues/860

I'm not sure there is anything we can do on `folium` to fix that. Not embedding everything could help but ideally we should always have a choice of self-contained (fully embed everything) and link all the content externally. That would mean a major overhaul on `folium`.

@Conengmo we should close this one or #812 to reduce the noise and help us address this in the future.

**Comment by robmarkcole** [comment]
I'm getting this behaviour for the [ImageOverlay ](https://github.com/python-visualization/folium/blob/master/examples/ImageOverlay.ipynb)example, [screenshot ](https://imgur.com/a/Br6gT1D)

**Comment by Conengmo** [comment]
> @Conengmo we should close this one or #812 to reduce the noise and help us address this in the future.

You're right, lets close this one and keep #812 since it has more links and comments.

**Comment by dstein64** [comment]
I believe this issue is related to Chrome's 2MB data URI limit. I've posted details in https://github.com/python-visualization/folium/issues/812#issuecomment-549532489.
