### ISSUE TITLE
error while importing IFrame

### ISSUE THREAD

**Issue by rawwar** [python-visualization/folium#774]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here
from folium.element import IFrame
```
#### Problem description

getting an error "ModuleNotFoundError: No module named 'folium.element'"

#### Output of ``folium.__version__``
folium.__version__
Out[11]: u'0.5.0'

**Comment by ocefpaf** [comment]
It should be from `folium import IFrame`.

**Comment by TheOther-Guy** [comment]
this worked for me in 2021, and I wonder why examples of notebooks have from folium.element import IFrame
when it is not working, while this one does, sorry new to coding here but took me 3 hours to find this link in google
