### ISSUE TITLE
 Unable to adjust width of the vega-lite chart in popup

### ISSUE THREAD

**Issue by Alcampopiano** [python-visualization/folium#775]
Hi Guys,

Wondering if you know how to increase the width of the vega-lite figure inside the popup. The options,

```
vega = folium.features.VegaLite(
bar,
width='100%',
height='100%')
```

control the size of the white canvas, but not the figure inside. When using Altair to configure the dimensions,

`bar.configure_cell(height=1000, width=1000)`

the height is adjusted, but not the width. Here is a screen shot:

![fig](https://user-images.githubusercontent.com/4624246/33213531-ee9b8dec-d0f5-11e7-9d79-8835034284d7.png)

Any ideas?

**Comment by Conengmo** [comment]
I have used the Vega charts in Folium, but didn't use Altair. Can you maybe give a short code snippet that creates the faulty barchart? I'll check if I have the same issue.

**Comment by ocefpaf** [comment]
My guess is that is an issue with altair/vega-lite and not `folium`. How does the graph looks like in altair? If it is the same ratio there is nothing we can do.

**Comment by Alcampopiano** [comment]
Morning guys,

@ocefpaf you are correct. In Altair, I cannot affect the width using
`bar.configure_cell(height=100, width=100)`

I'll check with the Altair people about that. 

In Vega Lite (and Folium), width and height specifications work as expected via top level properties as follows:

{
  "width": 200,
  "height": 200,
  "data": {"url": "data/cars.json"},
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "Origin",
      "type": "nominal",
      "scale": {"rangeStep": null}
    },
    "y": {
      "aggregate": "count",
      "type": "quantitative"
    }
  }
}

Thanks for the help,
Allan

**Comment by ocefpaf** [comment]
Thanks for checking that @Alcampopiano!
