### ISSUE TITLE
setting color scheme in using vegalite

### ISSUE THREAD

**Issue by Alcampopiano** [python-visualization/folium#777]
Hi Guys,

Any idea why the following snippet shows the correct color scheme in a vega-lite editor, but when passing the snippet into folium.features.VegaLite, only the green color scheme is used?

## screenshots below

```
{
  "data": {
    "values": [
      {"value": 38,"variables": "median income"},
      {"value": 43,"variables": "education"},
      {"value": 16,"variables": "lone parent"},
      {"value": 27,"variables": "unemployment rate"},
      {
        "value": 6,
        "variables": "non speaking (eng or french)"
      }
    ]
  },
  "description": "A simple bar chart with embedded data",
  "encoding": {
    "color": {
      "field": "value",
      "scale": {"domain": [1,55],"scheme": "yelloworangered"},
      "type": "quantitative"
    },
    "x": {"field": "variables","type": "nominal"},
    "y": {
      "field": "value",
      "type": "quantitative",
      "scale": {"domain": [0,55]}
    }
  },
  "mark": "bar"
}
```
## In a vega-lite editor:
![vg](https://user-images.githubusercontent.com/4624246/33223689-eacdede2-d12f-11e7-8173-41378d4ecdde.png)

## In folium,

```
vega = folium.features.VegaLite(snippet)
marker=folium.RegularPolygonMarker(ll)
popup = folium.Popup()
vega.add_to(popup)
popup.add_to(marker)
marker.add_to(m)
m
```
shows this:
![fo](https://user-images.githubusercontent.com/4624246/33223656-7da17c8e-d12f-11e7-90b8-2c9a640c938c.png)

**Comment by Conengmo** [comment]
I think it has to do with the Vega Lite version. In an [online Vega Lite editor](http://vega.github.io/vega-editor/?mode=vega-lite) I also got green bars, unlike you did. This uses Vega Lite version 1. Folium uses Vega Lite 1.3.1, which also results in green bars. If you try your code in an [online editor](https://vega.github.io/editor) with Vega Lite 2.0 you do get the orange and yellow bars.

So I think you have to change your chart specification to work with Vega Lite 1. Or create support for Vega Lite 2.

**Comment by Alcampopiano** [comment]
That makes sense. So what you are saying is that, I can achieve the color scheme I'm looking for, so long as the JSON is arranged in the way Vega Lite 1 expects? 

Thanks for getting back, I appreciate it.

**Comment by Conengmo** [comment]
I think that's right. If it works here: http://vega.github.io/vega-editor/?mode=vega-lite it should also work in Folium. Good luck :)

**Comment by ocefpaf** [comment]
This is a vegalite question and not folium. I am closing it b/c it is not actionable by our devs. Feel free to continue the discussion here though.

**Comment by Alcampopiano** [comment]
@Conengmo Thanks Frank. You are correct. Setting the colour scheme works perfectly if I'm using Vega Lite 1 vernacular. For those who need it, here is an example:

```
{
  "config": {
    "mark": {"filled": true,"orient": "vertical","opacity": ".5"},
    "axis": {
      "properties": {
        "title": {
          "font": {"value": "Helvetica"},
          "fontSize": {"value": 50}
        },
        "labels": {
          "font": {"value": "Helvetica"},
          "fontSize": {"value": 10}
        }
      }
    }
  },
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28},
      {"a": "B","b": 55},
      {"a": "C","b": 43},
      {"a": "D","b": 91},
      {"a": "E","b": 81},
      {"a": "F","b": 53},
      {"a": "G","b": 19},
      {"a": "H","b": 87},
      {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "a",
      "type": "nominal",
      "fontsize": 40,
      "axis": {"labelAngle": 45}
      
    },
    "y": {"field": "b","type": "quantitative"},
    "color": {
      "field": "b",
      "type": "quantitative",
      "legend": null,
      "scale": {"domain": [0,100],"range": ["yellow","red"]}
    }
  }
}
```
