### ISSUE TITLE
[choropleth, color_brewer] about branca changes

### ISSUE THREAD

**Issue by RiptideBo** [python-visualization/folium#779]
First of all , really thank **folium**, it is a powerful tool and helps me a lot.

and recently , I notice that the color_brewer  of **branca** has been  changed for supporting more Quantitative colors (like set_12)

so length of certain color scales are beyond 6 (now) and **branca** use a json file for supporting color. 

I wonder those code in **folium.choropleth** like following  would change or not soon?  
although **branca** has not released the newest changes. 

        if threshold_scale and len(threshold_scale) > 6:
            raise ValueError
        if data is not None and not color_brewer(fill_color):
            raise ValueError('Please pass a valid color brewer code to '
                             'fill_local. See docstring for valid codes.')

**Comment by ocefpaf** [comment]
We do need a new release of branca, however, you can create a "choropleth"  manually with the GeoJson class and a custom color scheme.

Regarding changing the default, I don't really want to do b/c the current choropleth implementation, limiting to 6 colors, aims to avoid complex maps and produce simple and meaningful visualization. Anything beyond 6 should be created manually by the user.

Maybe what we need is a simple copy-n-pastle example on how to do that with the GeoJson class.

**Comment by RiptideBo** [comment]
Using  style function of GeoJson class with customized color scheme is also a wonderful choice and already fix my problem, Really Thank you.

**Comment by ocefpaf** [comment]
Awesome. That was the idea behind the re-factor in GeoJson, to empower users to do whatever they need :wink:
