### ISSUE TITLE
Embedding folium map in ipywidget

### ISSUE THREAD

**Issue by digsci** [python-visualization/folium#780]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
import folium
import ipyleaflet
from ipywidgets import VBox,Label, Layout

map = folium.Map(location=[54.008603, -2.790598])
#map =  ipyleaflet.Map(center=[54.008603, -2.790598])
label = Label(value="Lancaster Map")
VBox([map, label])

```
#### Problem description

I'd like to embed a  folium map inside a Jupyter ipywidget - this seems straight forward using ipyleaflet (see commented out code above), but I think I'm not understanding how to use the folium map object in this context as I don't get the map out output. I've also tried map.render() and map.to_json(().

Any advice please?

#### Expected Output
Map embedded in a Jupyter ipywidget.

#### Output of ``folium.__version__``
0.5.0

**Comment by ocefpaf** [comment]
Folium is not a widget to be used like that. You'll need to use `ipyleaflet` or workaround it by using `interact`. We do have some example on how to do it in out contrib repository. See http://nbviewer.jupyter.org/github/python-visualization/folium_contrib/blob/master/notebooks/HereMapsApiExplorer_no_creds.ipynb
