### ISSUE TITLE
Heatmap error when using lat,lng coordinates stored in numpy array with shape (n,2)

### ISSUE THREAD

**Issue by Jollyhrothgar** [python-visualization/folium#782]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

https://alysivji.github.io/getting-started-with-folium.html

Error is reproducible by following the tutorial:

https://alysivji.github.io/getting-started-with-folium.html

conda version 4.3.30
jupyter version 4.4.0
numpy version 1.12.1
pandas version 0.21.0

Operating system: OSX 10.12.6

#### Problem description

Following the brief tutorial, at the step of generating the heat-map, folium throws an unhandled exception relating to a failed 'NaN' check which percolates up to a TypeError. 

Full Stack Trace:

Giving a numpy array with lat lng coordinates in the proper shape creates an unhandled exception:
<pre>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-125-0fe7d9d566c3> in <module>()
     18 
     19 # plot heatmap
---> 20 m.add_children(plugins.HeatMap(charge_locs, radius=15))
     21 
     22 m

~/anaconda3/lib/python3.6/site-packages/folium/plugins/heat_map.py in __init__(self, data, name, min_opacity, max_zoom, max_val, radius, blur, gradient, overlay)
     43                  max_val=1.0, radius=25, blur=15, gradient=None, overlay=True):
     44         super(TileLayer, self).__init__(name=name)
---> 45         if _isnan(data):
     46             raise ValueError('data cannot contain NaNs, '
     47                              'got:\n{!r}'.format(data))

~/anaconda3/lib/python3.6/site-packages/folium/utilities.py in _isnan(values)
     70 def _isnan(values):
     71     """Check if there are NaNs values in the iterable."""
---> 72     return any(math.isnan(value) for value in _flatten(values))
     73 
     74 

~/anaconda3/lib/python3.6/site-packages/folium/utilities.py in <genexpr>(.0)
     70 def _isnan(values):
     71     """Check if there are NaNs values in the iterable."""
---> 72     return any(math.isnan(value) for value in _flatten(values))
     73 
     74 

TypeError: only length-1 arrays can be converted to Python scalars
</pre>
#### Problem Hotfix

Converting the array of lat-lng  coordinates to a list-of-lists with the same shape works fine (n,2).  I would expect folium library to 'just work' with numpy. Maybe this is not a supported feature?

#### Expected Output

I would expect to see output in the form of a heatmap.

#### Output of ``folium.__version__``

0.5.0

**Comment by Conengmo** [comment]
This seems to be the same problem as #749, which was fixed in #758. It's not in version 0.5.0 though, so good that you can work around it by using a list of lists.

**Comment by Jollyhrothgar** [comment]
Sorry to miss the fix. Thanks for responding!

**Comment by Conengmo** [comment]
No problem, good job on the excellent issue report.

**Comment by quincymac** [comment]
Jollyhrothgar any chance you could share your list of lists workaround?

**Comment by Conengmo** [comment]
You need to convert your Numpy array to a list:
```
>>> a = np.array([[1, 6],  [2, 7], [3, 8], [4, 9]])
>>> a.tolist()
[[1, 6], [2, 7], [3, 8], [4, 9]]
```

**Comment by quincymac** [comment]
Thanks I did try that. I wonder if it timed out. I was plotting 100k points on my heatmap

**Comment by quincymac** [comment]
I did some further testing and 66K points was the maximum that I could use to create a heatmap. I tried to add the data to the map in chunks without success.

Has anyone else identified this issue?

**Comment by MalithDis** [comment]
I try your code. but I get this error message again and again "only length-1 arrays can be converted to Python scalars". please can you tell how to fix it. thanks
