### ISSUE TITLE
Add time slider test 

### ISSUE THREAD

**Issue by birdage** [python-visualization/folium#79]
id like to see a time slider widget added to the map interface for makers that move, id like to see this also applied to data layers so a user can step through time.

something like this:

http://recallfx.github.io/LeafletPlayback/examples/example_2.html#
![screen shot 2015-01-26 at 11 12 59 am](https://cloud.githubusercontent.com/assets/547228/5902897/5d6fba28-a54c-11e4-963c-1d7a5fb19890.png)

http://recallfx.github.io/LeafletPlayback/examples/example_0.html
![screen shot 2015-01-26 at 11 13 11 am](https://cloud.githubusercontent.com/assets/547228/5902898/628ef212-a54c-11e4-8502-18ed50482388.png)

**Comment by jboynyc** [comment]
+1 That would be great.

**Comment by ocefpaf** [comment]
We went for the `Leaflet.Timedimension` instead, but `LeafletPlayback` could be implemented as well using the new plugin machinery.  Feel free to re-open this id `Leaflet.Timedimension` is not enough for you purposes.
