### ISSUE TITLE
Toggling zoom controls

### ISSUE THREAD

**Issue by mdmadhu** [python-visualization/folium#795]
Is there some way of toggling the zoom controls on and off? There seems to be [a way of doing this with Leaflet.js](http://leafletjs.com/reference-1.2.0.html#control-zoom) while initialising a map. Any help would be appreciated. Thank you!

**Comment by Conengmo** [comment]
Hi Madhu,
There is no way to disable the zoom controls in Folium. But you can easily add it to your map by opening the HTML file and adding `zoomControl: false` to the options of the map declaration. Like this:

```
var map_6fcc8872cdb4448898b820db694a35fb = L.map(
                                  'map_6fcc8872cdb4448898b820db694a35fb',
                                  {center: [0,0],
                                  zoom: 1,
                                  maxBounds: bounds,
                                  layers: [],
                                  worldCopyJump: false,
                                  crs: L.CRS.EPSG3857,
                                  zoomControl: false
                                 });
```

This could be implemented in Folium, but it would further clutter the `Map` options. What is the use-case for wanting to hide the zoom controls?

**Comment by mdmadhu** [comment]
Thanks! Very helpful!

My use case may not be all that common. I was rendering a series of custom tile layers from a remote sensing analysis in folium, capturing screenshots of each map (via headless browser) and putting them together in a video animation, where the zoom control was a distraction. :-)

**Comment by Conengmo** [comment]
Thanks for specifying Madhu! I can imagine for making screenshots you'd want to remove the zoom controls. I'll leave it up to the maintainers if they think it's worth adding.

**Comment by Conengmo** [comment]
This has been added in PR #899.
