### ISSUE TITLE
IPython Magic Based on folium

### ISSUE THREAD

**Issue by psychemedia** [python-visualization/folium#798]
I've started experimenting with some IPython magic to make it easier for non-programmers to embed maps in Jupyter notebooks. It uses `folium` to to generate the maps.

Code here: https://github.com/psychemedia/ipython_magic_folium

**Comment by psychemedia** [comment]
To cope with users who might struggle with identifying keys in geojson files etc, I started exploring crude methods for autodetecting whether cols in dataframe may be a good match for properties in a geojson file: https://github.com/psychemedia/ipython_magic_folium/commit/d97dde5333de388afdd073c2785dcfca039beaee#diff-7fd167d37d40db12c466ca01a4fa882d

Next up to add simple magics that just explain, or suggest, possible matches.

Likely to be v flakey, but a start on trying to make something that tries to render whatever is thrown at it...

What I really need to do is add some sort of disclaimer panel to the map saying what was guessed at.

**Comment by ocefpaf** [comment]
@psychemedia that is awesome! Thanks for doing this.

If you want to integrate that into `folium` itself let me know.

**Comment by psychemedia** [comment]
@ocefpaf Thanks; if you want to grab any of the code or ideas, please feel free to, or use ideas as a starting point for some official `folium` magic.

All my repos tend to be a bit unstable and experimental (personal exploration) and the code quality can be a bit off, if not completely broken! I'd be happy to contribute as / how I can if you wanted a formal branch.

**Comment by ocefpaf** [comment]
> All my repos tend to be a bit unstable and experimental (personal exploration) and the code quality can be a bit off, if not completely broken!

I understand (and I usually do the same :smile:)

I think about it and I'll ping you if I ever get to it. Thanks for the extension. Very useful!

**Comment by Conengmo** [comment]
My thoughts at the moment are that we don't want to include this in folium, since it would mean maintaining and documenting a second API. Therefore I'll close the issue. Though we might link out to this repo if it's still functional.
