### ISSUE TITLE
Fancy HTML does not display from inside a for loop

### ISSUE THREAD

**Issue by pjandrews** [python-visualization/folium#799]
The following code will only display the first marker of "geo_list" and the html popup will also not be displayed. If I remove the for loop and then the popup is displayed.

Code: 

import folium
import pandas as pd
print(folium.__file__)
print(folium.__version__)

m = folium.Map(zoom_start=6,tiles='Stamen Toner')

html="""
    <h1> This is a big popup</h1>
    """

geo_list = [(40.712783700000003, -74.005941299999989),
 (34.052234200000001, -118.24368490000002),
 (41.878113599999999, -87.62979820000001)]

popup = folium.Popup(html=html,max_width=2650)

for lat,lon in geo_list:
    print(lat,lon)
    folium.Marker([lat,lon], popup=popup).add_to(m)
m

Output:
C:\Program Files\Anaconda3\lib\site-packages\folium\__init__.py
0.5.0
40.7127837 -74.00594129999999
34.0522342 -118.24368490000002
41.8781136 -87.62979820000001

**Comment by Conengmo** [comment]
Each marker should have its own popup. Like this:
```
for lat, lon in geo_list:
    popup = folium.Popup(html=html)
    folium.Marker([lat, lon], popup=popup).add_to(m)
```

In Leaflet this is not necessary, but I don't see an easy way to reuse a Popup object in rendering. When adding a Marker with a Popup to a Map, should we raise an exception if the Popup object already exists? (@ocefpaf )

About opening popups on load, that functionality is coming soon. It's in PR #778.

**Comment by pjandrews** [comment]
Thanks a lot for your help @Conengmo
