### ISSUE TITLE
Markers on layers

### ISSUE THREAD

**Issue by jboynyc** [python-visualization/folium#80]
Enhancement request: It would be great to have an option added to the various `_marker` functions to add markers to specific layers that can then be shown or hidden on the final map ([like this](http://leafletjs.com/examples/layers-control.html)).

**Comment by birdage** [comment]
@jboynyc yeah this would actually be pretty kool. :+1:

**Comment by psychemedia** [comment]
+1 Being able to place markers onto separate layers based on a categorical column value in a pandas dataframe would also be handy. So eg a column `df['layercol'].unique() -> ['layer1','layer2']` that is then used to place corresponding markers onto an appropriate layer?

**Comment by themiurgo** [comment]
@psychemedia Nice suggestion. AFAIK at the moment folium does not support direct import of markers from a pandas dataframe (unless it's geojson, maybe, haven't tried that). So for that to happen we would need to implement pandas importing first.

**Comment by ocefpaf** [comment]
At @psychemedia indeed it will be nice to have a better integration between folium and pandas.  However, I would like to keep pandas as an optional dependency.  So when we implement this lets keep that in mind.

**Comment by BibMartin** [comment]
Can we close this ? it's solved by #242

**Comment by ocefpaf** [comment]
@BibMartin yep.  We missed this one.  Closing this.
