### ISSUE TITLE
Popup on polygon geojson features

### ISSUE THREAD

**Issue by orkun** [python-visualization/folium#802]
I am not clear on "Popup on polygon geojson features". How can I construct a popup with polygon features. 
Where can I find a good example?
Regards

**Comment by Conengmo** [comment]
Hi,
There is a notebook with [geojson examples here](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/GeoJSON_and_choropleth.ipynb), and one with [popup examples here](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Popups.ipynb).

In short, you create elements and add them to each other. For example:
```
geojson = folium.GeoJson(some_geojson_data)
popup = folium.Popup('Hi')
popup.add_to(geojson)
geojson.add_to(m)
```

If you want to have a popup for each feature in a geojson dataset, I think you would have to make a `folium.Geojson` object for each feature.

**Comment by Maxoz99** [comment]
Hi,
I'm trying to do a popup for each feature in a geojson set in a form like this:
```
geo_json_data = json.load(open("MyFile.geojson",encoding = "utf-8"))

for feature in geo_json_data['features']:
    geojson = folium.GeoJson(feature["geometry"]["coordinates"])
    popup = folium.Popup('I am a Popup).add_to(geojson)
    geojson.add_to(m)    
```
However it raises a 

> ValueError: Unhandled object

and Google only gives me [https://gis.stackexchange.com/questions/257802/understanding-valueerror-from-folium](url) which is not really helping me. I'm quite new to Folium so please point out if I'm doing something really wrong here.

**Comment by linghu258** [comment]
> Hi,
> There is a notebook with [geojson examples here](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/GeoJSON_and_choropleth.ipynb), and one with [popup examples here](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Popups.ipynb).
> 
> In short, you create elements and add them to each other. For example:
> 
> ```
> geojson = folium.GeoJson(some_geojson_data)
> popup = folium.Popup('Hi')
> popup.add_to(geojson)
> geojson.add_to(m)
> ```
> 
> If you want to have a popup for each feature in a geojson dataset, I think you would have to make a `folium.Geojson` object for each feature.

Hi, by any chance could you show a sample code to have a popup for each feature ? Currently my popup is displaying only the data in the last feature, so all nodes have the same information. It is not showing the information that is respective to the node

**Comment by fullonic** [comment]
Hey, what is your folium version? Because now, at least the with master version, you can use the new feature GeoJsonPopup.
https://github.com/python-visualization/folium/blob/4affacb6acf45f38ec8d6361dcb86e2b49137abd/folium/features.py#L968

It works similar to the GeoJsonTooltip. With this way you can pass your popup data at the same time you create you geojson layer.
`GeoJson(geojson_data, popup=folium.GeoJsonPopup(fields=['NAME']))`

`fields` should be a key from your ["feature"]["properties"]["key_name"]

Is necessary to update the geojson examples to reflect this new feature. I could do that during the coming week

**Comment by linghu258** [comment]
I am not sure what is my folium version, but I think is the latest version ? Currently my code below, for some reason, the popup are all showing the same information on each node. 

`# reading JSON file
with open('exportBuilding.geojson') as access_json:
    read_content = json.load(access_json)

feature_access = read_content['features']

# Creating Folium Map
m = folium.Map(location=[1.400150, 103.910172], titles="Punggol", zoom_start=17)
nodeData = os.path.join('exportBuilding.geojson')
geo_json = folium.GeoJson(nodeData)

# retrieve all names and store in popup
for feature_data in feature_access:
    property_data = feature_data['properties']
    geo_json.add_child(folium.Popup(property_data['name'))

geo_json.add_to(m)`

**Comment by fullonic** [comment]
I don't have now access to a computer, therefore I can't test your code. I checked the last release and it doesn't contain the geojson popup. The best I can suggest right now is install folium from the master branch and give a try to this new feature so you can move further. Also, using this feature you don't need to open your file before, pull all data and loop over it to produce the popup. It can be done now with one line. 

Let me know if it works.

**Comment by linghu258** [comment]
sorry can I ask what do you mean by install folium from master branch ? Currently, my pycharm is using anaconda interpreter. Do I uninstll my folium and reinstall again using "$ conda install -c conda-forge folium" ?

**Comment by fullonic** [comment]
I don't use conda, but I believe is the same as pip.
I mean `pip install https://github.com/python-visualization/folium/archive/master.zip`
I would suggest do it in virtual environment, so you don't need remove your actual folium version. But it's up to you.

**Comment by linghu258** [comment]
Thanks, I have tried installing folium from the master branch. However, I notice the codes under GeoJsonPopup(GeoJsonDetail) is commented. and even after installing from the master branch, the GeoJsonPopup is not an option when I was typing the codes.

**Comment by fullonic** [comment]
`from folium.features import GeoJsonPopup` is not available?

**Comment by linghu258** [comment]
is not available

**Comment by linghu258** [comment]
0.10.1

**Comment by fullonic** [comment]
you're still using your old folium and not the master version. 10.0.1 is the current released version with don't contains the geojson popup. If you installed the master version in a virtual env you must activate it. 

Can you post a sample code of your geojson feature?

**Comment by linghu258** [comment]
This my geojson code

` # Creating Folium Map
        m = folium.Map(location=[1.400150, 103.910172], titles="Punggol", zoom_start=17)
        nodeData = os.path.join('exportBuilding.geojson')

        print(folium.__version__)
        geo_json = folium.GeoJson(nodeData, popup=folium.GeoJsonPopup(["feature"]["properties"]["name"]))

        geo_json.add_to(m)
        data = io.BytesIO()
        m.save(data, close_file=False)
        self.view.setHtml(data.getvalue().decode())`

**Comment by fullonic** [comment]
Sorry, I mean, your geojson/json data file, not your code. Otherwise is harder to understand your error. Also, are you sure that you copied everything necessary to have the geojson popup working in your folium v10.0.1?

**Comment by linghu258** [comment]
Oh this is my sample Geojson file

`{
  "type": "FeatureCollection",
  "generator": "overpass-ide",
  "copyright": "The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.",
  "timestamp": "2020-03-07T08:26:01Z",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "@id": "way/768461439",
        "building": "train_station",
        "layer": "1",
        "name": "Damai LRT",
        "wikidata": "Q7313275",
        "wikipedia": "en:Damai LRT station"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              103.9085471,
              1.4053643
            ],
            [
              103.9085315,
              1.4053718
            ],
            [
              103.9085143,
              1.4053742
            ],
            [
              103.9084972,
              1.4053713
            ],
            [
              103.9084817,
              1.4053634
            ],
            [
              103.9084694,
              1.4053511
            ],
            [
              103.9084613,
              1.4053354
            ],
            [
              103.9084584,
              1.4053178
            ],
            [
              103.9084611,
              1.4053003
            ],
            [
              103.9084691,
              1.4052845
            ],
            [
              103.9084816,
              1.4052719
            ],
            [
              103.9086706,
              1.4051364
            ],
            [
              103.9086857,
              1.4051292
            ],
            [
              103.9087023,
              1.405127
            ],
            [
              103.9087187,
              1.4051298
            ],
            [
              103.9087335,
              1.4051376
            ],
            [
              103.9087453,
              1.4051494
            ],
            [
              103.9087532,
              1.4051649
            ],
            [
              103.9087557,
              1.405182
            ],
            [
              103.9087528,
              1.4051991
            ],
            [
              103.9087447,
              1.4052144
            ],
            [
              103.9087321,
              1.4052263
            ],
            [
              103.9085471,
              1.4053643
            ]
          ]
        ]
      },
      "id": "way/768461439"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "way/768461440",
        "building": "train_station",
        "layer": "1",
        "name": "Oasis LRT",
        "wikidata": "Q7074425",
        "wikipedia": "en:Oasis LRT station"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              103.9126812,
              1.4023984
            ],
            [
              103.9126655,
              1.4024057
            ],
            [
              103.9126483,
              1.402408
            ],
            [
              103.9126312,
              1.4024049
            ],
            [
              103.9126158,
              1.4023968
            ],
            [
              103.9126037,
              1.4023844
            ],
            [
              103.9125957,
              1.4023685
            ],
            [
              103.912593,
              1.402351
            ],
            [
              103.9125959,
              1.4023335
            ],
            [
              103.912604,
              1.4023177
            ],
            [
              103.9126167,
              1.4023053
            ],
            [
              103.9128071,
              1.4021718
            ],
            [
              103.9128223,
              1.4021648
            ],
            [
              103.9128388,
              1.4021627
            ],
            [
              103.9128553,
              1.4021658
            ],
            [
              103.91287,
              1.4021736
            ],
            [
              103.9128817,
              1.4021856
            ],
            [
              103.9128893,
              1.4022012
            ],
            [
              103.9128917,
              1.4022183
            ],
            [
              103.9128886,
              1.4022354
            ],
            [
              103.9128803,
              1.4022506
            ],
            [
              103.9128677,
              1.4022624
            ],
            [
              103.9126812,
              1.4023984
            ]
          ]
        ]
      },
      "id": "way/768461440"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "way/768464808",
        "building": "train_station",
        "layer": "1",
        "name": "Kadaloor LRT",
        "wikidata": "Q6345023",
        "wikipedia": "en:Kadaloor LRT station"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              103.9164457,
              1.399683
            ],
            [
              103.91643,
              1.3996905
            ],
            [
              103.9164129,
              1.3996929
            ],
            [
              103.9163957,
              1.39969
            ],
            [
              103.9163803,
              1.3996821
            ],
            [
              103.916368,
              1.3996698
            ],
            [
              103.9163599,
              1.3996541
            ],
            [
              103.916357,
              1.3996366
            ],
            [
              103.9163597,
              1.399619
            ],
            [
              103.9163676,
              1.3996032
            ],
            [
              103.9163801,
              1.3995906
            ],
            [
              103.916569,
              1.399455
            ],
            [
              103.9165841,
              1.3994478
            ],
            [
              103.9166007,
              1.3994456
            ],
            [
              103.9166172,
              1.3994484
            ],
            [
              103.916632,
              1.3994561
            ],
            [
              103.9166438,
              1.399468
            ],
            [
              103.9166516,
              1.3994834
            ],
            [
              103.9166542,
              1.3995005
            ],
            [
              103.9166513,
              1.3995176
            ],
            [
              103.9166432,
              1.3995329
            ],
            [
              103.9166306,
              1.3995449
            ],
            [
              103.9164457,
              1.399683
            ]
          ]
        ]
      },
      "id": "way/768464808"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "way/768464809",
        "building": "train_station",
        "layer": "1",
        "name": "Riviera LRT",
        "wikidata": "Q7338869",
      `

**Comment by fullonic** [comment]
great! It should with `GeoJsonPopup(fields=['name'])`.

**Comment by linghu258** [comment]
OMG thanks so much it finally work after so much time debugging

**Comment by fullonic** [comment]
Great to hear that!! I saw that you opened an issue about this topic, #1269. May your post there your workaround so it can be visible to others please. Maybe sooner we will have another folium release with this new geojson popup feature.

**Comment by linghu258** [comment]
Sure will do. Thanks alot, really appreciate it

**Comment by linghu258** [comment]
@fullonic Sorry err what if I wanted to retrieve more than 1 info ? E.g. building and name ? Apparently I can't just add popup=folium.GeoJsonPopup(fields=['name']['building']).

**Comment by fullonic** [comment]
fields accepts a single list of keys, so would be `fields=["name", "building"]`.

Sorry but I don't understand your second question. But if you want to have two different layers of data, you can create two layer, one with each node, and control them using `folium.LayerControl()`

**Comment by linghu258** [comment]
Thanks again for the first question.

For the second question. Currently, I am creating a pathfinding application using folium map which is integrated into PyQt. So my question is if there is a way to use the PyQt checkbox to show the polygon marker of the building when user check on the checkbox, and disable the polygon marker when user uncheck the checkbox

**Comment by fullonic** [comment]
Hmmm, ok. You are trying to use folium outside it's scope. You will need to hack and create something like LayerControl plugin in JavaScript and connect to your pyqt app. I don't have experience with pyqt.

**Comment by linghu258** [comment]
oh okay, I understand. Thanks so much for all of your assistant

**Comment by fullonic** [comment]
you welcome :)

**Comment by zoesn89** [comment]
Hey,

I updated folium to v0.11.0, but GeoJsonPopup doesn't work.
My code:
`
data = geopandas.read_file('output.json', driver='GeoJSON')

stationen = folium.GeoJson(
    data,
    name='Stationen',
    popup = folium.GeoJsonPopup(
        fields=['shortname', 'voltage_level'],
        aliases=['Name', 'Spannungsebene']
    )
).add_to(m)
`
In the developer tools I get the following error:
`Uncaught TypeError: e.target.getBounds is not a function
    at i.click (geojson_test.html:85)
    at i.fire (leaflet.js:5)
    at i._fireDOMEvent (leaflet.js:5)
    at i._handleDOMEvent (leaflet.js:5)
    at HTMLDivElement.s (leaflet.js:5)`

**Comment by Conengmo** [comment]
@zoesn89 please open a new issue and include a data snippet so we can reproduce your error.

**Comment by Ajala111** [comment]
Please what if I want to pop up all the entire data in the GeoJson properties. I mean if I am giving the user the chance to upload his/her own geojson

**Comment by Ajala111** [comment]
@fullonic  Yes. I solved the problem by extracting the propertes (key-value pairs), and obtain only the keys 

# Here is the snippet 
m = folium.Map(location=[initial_location[1], initial_location[0]], zoom_start=15)
all_data = data['features'][0]['properties']     // get the properties of the first features 
all_data_keys = list(all_data.keys())

folium.GeoJson("_/copied-file.json_", name="geojson", popup=folium.GeoJsonPopup(fields=all_data_keys)).add_to(m)

folium.LayerControl().add_to(m)

Thank you

**Comment by msw17002** [comment]
Hello, 

It sounds like I have a similar issue.

I have multiple, overlapping polygons on a folium map. I'd like to click one location <lon,lat> and view metadata from all overlapping polygons at that one location (similar to what QGIS and ArcMAP does). Is this possible?

I attached an example of what I'd like to (ideally) script:
![Capture](https://user-images.githubusercontent.com/42711140/231845406-ce6ed136-7c2e-4fcb-a5ad-4e834896b3e1.JPG)

**Comment by lamineniang10** [comment]
Good morning. excuse me for having opened a topic that dates back a long time but I encounter the same problem today, the popup does not work on my polygons
here un extract of my geojson object
{"type": "FeatureCollection", "crs": {"type": "name", "properties": {"name": "EPSG:4326"}}, "features": [{"type": "Feature", "id": "SN02321", "properties": {"nom": "ADEANE"}, "geometry": {"type": "Polygon", "coordinates": [[[-15.998456946953608, 12.65652961744222], [-15.998157046724351, 12.656392171378137], [-15.99815587814272, 12.656399011286753], [-15.9971052385781, 12.655943229262467], [-15.994370677039567, 12.654398465290068], [-15.991854293218129, 12.652565782758137], [-15.985425870942365, 12.648451951075455], [-15.98341734645673, 12.647166546257246], [-15.975118160501559, 12.636476966380984], [-15.975088833397235, 12.636439190393393], [-15.974897895161627, 12.636193242447673], [-15.971477233328246, 12.632250581481317], [-15.971312869575662, 12.632085624916535], [-15.967685730422858, 12.627539325100258], [-15.966546993610695, 12.626124303490041], [-15.966468082027061, 12.625174316668124], [-15.966490149781263, 12.625152757954414], [-15.96625398858632, 12.621116261173546], [-15.965351193296396, 12.618028162527121], [-15.964609967509192, 12.614021807924955], [-15.963969233148537, 12.612272902000717], [-15.963357901239505, 12.61058291270352], [-15.962532061801227, 12.608349990213211], [-15.96232548313043, 12.60778609945332], [-15.961893103932084, 12.606605842523086], [-15.961693450959677, 12.606252387255111], [-15.961245783812247, 12.605459856676063], [-15.960101133669363, 12.601578838428681], [-15.960022379188796, 12.599231163022582], [-15.95994283553885, 12.597003354844384], [-15.9599424214415, 12.596991769216947], 
the code
  gdf = serialize("geojson", Commune.objects.all(), geometry_field="geometry", fields = ['nom'])
map_osm = folium.Map(location = [14.705442, -17.45537], zoom_start = 10)
    geo = folium.features.GeoJson(
        gdf,
        name = 'geo',
        popup = folium.GeoJsonPopup(fields = ['nom'])
        
    ).add_to(map_osm)

try: 
        map_osm = map_osm._repr_html_()
    except TypeError:
        pass
    
context = {
        'map': gdf

    }

    return render(request, 'carte/maps.html', context)

**Comment by lamineniang10** [comment]
context ={
'map': map_osm
}

**Comment by lamineniang10** [comment]
without the popup the map is displayed but with the popup nothing is displayed
