### ISSUE TITLE
HeatMapWithTime change gradient color

### ISSUE THREAD

**Issue by sararl** [python-visualization/folium#804]
I have created a HeatMapWithTime using folium and would like to adjust the gradient/color of the heatmap, but I don't know how to do that. It is possible to change colors working with the simple heatmap (parameter gradient) . Thank you.

**Comment by Conengmo** [comment]
`HeatMapWithTime` currently doesn't expose an option to set the colors. I believe this should be possible with the `gradient` argument, just like in the `HeatMap` plugin. Based on [this documentation](https://www.patrick-wied.at/static/heatmapjs/docs.html) we can add a `gradient` option somewhere in the options.

If somebody wants to work on this, a PR is welcome!

**Comment by Conengmo** [comment]
The `gradient` arguments has been added in PR #925.
