### ISSUE TITLE
Conda installation failed

### ISSUE THREAD

**Issue by naveenkumarmarri** [python-visualization/folium#805]
```python
conda install folium

```
#### Problem description

Unable to install folium using anaconda on Ubuntu 16.04, However I was able to install using pip.

#### Output of ``folium.__version__ = 0.5.0
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - folium

Current channels:

  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch

``

**Comment by ocefpaf** [comment]
`folium` is not available in those channels. You can contact `anaconda`, formerly known as continuum, to remedy that or you can install it with `pip` or from a third party channel like `conda-forge`.

Closing this b/c it is not a `folium` issue.

**Comment by rommelmax** [comment]
I solved it in the following way:

conda config --add channels conda-forge
