### ISSUE TITLE
input checkbox in popup iframe

### ISSUE THREAD

**Issue by orkun** [python-visualization/folium#806]
Hi
I put a checkbox into popup iframe. I want to control whether it checked or not. if
it is clicked and checked. I going to perform certain action such as opening the another map.

How can I do that?

**Comment by Conengmo** [comment]
I'm not sure I understand your question. Can you provide a code snippet of what your trying to do?

If you're looking for callbacks based on clicks on the map, you'd have to dive in the javascript generated by folium for that. As far as I know folium doesn't have options for that. If you can make it with Leaflet in javascript/html, you could then implement it in folium.

**Comment by toknowjoyman** [comment]
I used QtWebChannel in pyQt to connect the folium/leaflet HTML to the rest of a the running program

**Comment by orkun** [comment]
I solved the problem usinf websocket from iframe.
