### ISSUE TITLE
Circle marker creation is slow

### ISSUE THREAD

**Issue by psarka** [python-visualization/folium#807]
#### The code sample

```python
import folium

map_ = folium.Map()

for i in range(1000):
    folium.features.Circle([i, i],
                           radius=3,
                           color='blue',
                           fill_color='blue',
                           fill_opacity=1,
                           fill=True).add_to(map_)
```
#### Problem description

Circle creation proceeds roughly at the order of 100 per second, which is quite slow. Creating a map with thousands of circle markers (which is handled easily by the browser) becomes slightly annoying. 

#### Expected Output

I would expect above code to run 10-1000 times faster.

#### Output of ``folium.__version__``
0.5.0

#### Extras
I tried to quickly check what is the bottleneck, and it's the jinja template compilation, which is executed 4133 times.

![circle](https://user-images.githubusercontent.com/1212244/34559260-7993ee10-f141-11e7-90ad-111e0fe01bca.png)

**Comment by psarka** [comment]
OK, this is actually easy to fix. I'll open a PR in the coming days.

**Comment by Conengmo** [comment]
I checked out your branch, interesting idea to move the templates out of `__init__`! It does indeed give more speed, I did a quick timing and saw a factor 2 -- 2.5 increase. But it becomes tricky when an ancestor sets the template in `__init__`. So this would need edits in Branca as well.

I have another idea for you, folium has a `fast_marker_cluster` plugin that can create many markers by doing the work in javascript. I made a test and this way can also be used for other marker types such as circles. I'll link to this issue from my branch.

**Comment by psarka** [comment]
I would guess that your solution will even render faster in browser, as there will be less javascript to parse, right? It seems great! :+1: 

Moving _template from the instance variable to class variable could still make sense, hare are my observations for your consideration:

1. From a "nice" code standpoint class variable seems more appropriate, as these templates never change.

2. The speedup I get is x100 in the case of the thousand circle markers (7.45 s -> 74.8 ms) and x200 in the case of plain `Circle([1, 1], 1)` (9.55 ms -> 58.4 µs) (measured with %timeit from the notebook).

3. In the case of thousand circles, jinja2 compilation is called 6137 times. With templates moved to class attributes 37 times

4. Import time decreases from 2.6 seconds to .8 seconds (measured with `time python -c "import folium"`), although I'm not 100% sure about the representativeness of this. With pip installed version I was getting .4 seconds.

All above were run on bleeding edge branca and folium.

The move from instance attributes to the class attributes is trivial, and should not impact downstream users, if there's anyone extending classes. On the other hand it has to be sync'd between folium and branca. This is still easy, but I was a bit thrown off by two failing folium tests and the fact that bleeding edge folium does not work with bleeding edge branca (something with colormaps is broken). 

Should you think that push for class attributes is worthwhile, I will finish and open PR's both on folium and branca (despite the failing tests), otherwise I will leave it at this.

**Comment by Conengmo** [comment]
I tried to confirm your timings by making a map, adding 1000 circles and timing the adding of the circles and the rendering. Not with %timeit but by just printing the time :)

In regular folium and branca circle creation took 9.7 s and rendering took 0.8 s.

With the `_template` attribute outside of `__init__` for the `Element`, `MacroElement`, `Marker` and `Circle` classes (all the parents of `Circle`) circle creation took 0.1 s and rendering took 0.8 s.

So I agree with your factor 100 speedup. But I didn't see a change in rendering.

**Comment by psarka** [comment]
Cool. As for the rendering, there shouldn't be any changes there, as the generated code is the same.

**Comment by Conengmo** [comment]
Given this speedup it does make sense to put `_template` outside `__init__`. But really this is something for the maintainers to decide. I don't see a reason why not. The only thing I can think of is that the inheritance would get screwed up, but it seems fine when all the `_template` declarations are moved.

**Comment by psarka** [comment]
OK, I'll open the PRs then.

**Comment by BasilBibi** [comment]
Hi guys any forecast on this being rolled out?

**Comment by ocefpaf** [comment]
@psarka and @Conengmo I believe I merged both PRs.  Closing this but please re-open if I missed something. (Planning on a new release soon as soon as I sort out #860 and some pending PRs.)

**Comment by Juanlu001** [comment]
@psarka sorry for the noise: what did you use for the plot above? it looks richer and fancier than pycallgraph.

**Comment by psarka** [comment]
Unfortunately the answer is not very interesting: its profiling output by Pycharm :)
