### ISSUE TITLE
One line to change behaviour

### ISSUE THREAD

**Issue by fitoprincipe** [python-visualization/folium#810]
Hello, I think this line should be changed. I'd (I did in my fork) make this Figure an optional parameter, and only create this empty Figure if the user doesn't pass it.

https://github.com/python-visualization/folium/blob/5739244acb9868d001032df288500a047b232857/folium/folium.py#L193

What do you think?

**Comment by Conengmo** [comment]
What is the use-case for letting a user provide a Figure object? I can't think of anything I would want to do with a `Figure` object before calling `map()`, instead of doing it on a `Map` object.

**Comment by fitoprincipe** [comment]
I'm using folium, an specially branca, to build a web page. In that case I think is useful to replace that line. You may think *'why don't you write your own HTML5, CSS and JS?'*.. but I think it is very handy to build the webpage using a framework like branca. The `Figure` object holds all html's structure, and if I want it to be a custom one, and just include the map as an extra element, I have to make this change.

**Comment by Conengmo** [comment]
Technically it's not hard to add a `figure` argument to `Map`, but the argument list of `Map` is already very crowded so I don't think we should add stuff easily.

Have you considered loading the `Figure` of `Map` in an iframe? Like what happens in Jupyter notebooks. That iframe could be added to any page, `Figure` or template you're brewing. Check out the `_repr_html_` method of `Element`. Just an idea, I haven't tried this myself.

**Comment by fitoprincipe** [comment]
I have already twisted it to make it work, I just wanted to contribute so the project can aim to web development, but I understand it may not be the wanted path. May be, it could be a branca plugin, simplier but useful. How do I contribute with plugins to branca? Do I make a clean repo with just the plugins? or a forked branca with the plugins?

**Comment by fitoprincipe** [comment]
You are right @Conengmo ! :smiley:
`child._parent = self`
That's why I first ask.

I can't show you now because my site is not online and I have no repo yet, but basically: I've been working a lot to implement an algorithm in Google Earth Engine using the python API, so I decided to implement it online using Google App Engine. Of course, as I had made my code in python, I use it as my backend (webapp2). As my backend code generates a tile layer, I needed to put it on a map, and to handle that I used folium (maybe I could've made it without it, but why?).. but of course the map is just a part of my webpage. As I need a form to set some params, I created a `SimpleForm` plugin for branca, and as I need to use Ajax to add responses to the map, I created a `Ajax` plugin too. Again, I could've made all without it, but I think branca is interesting framework. As the repo says: *It may become a HTML+JS generation library in the future*... maybe this is the future :smile:

**Comment by Conengmo** [comment]
I'm closing this issue since we're not going to add a `figure` argument to `Map`. But of course ideas and discussion about how folium could be better suited for web development are welcome. New issues can be opened for them, or even better yet, PR's which show the idea.
