### ISSUE TITLE
Usage of popup with a string value

### ISSUE THREAD

**Issue by muticansel** [python-visualization/folium#813]
This is my code sample;

```python
import folium
import pandas

data = pandas.read_csv("volcanoes.txt")

lat = list(data["LAT"])
longt = list(data["LON"])
names = list(data["NAME"])

map = folium.Map(location=[38.58, -99.09], zoom_start=6, tiles="Mapbox Bright")

fg = folium.FeatureGroup(name="My Map")

for lt, ln, name in zip(lat, longt, names):
    **fg.add_child(folium.Marker(location=[lt, ln], popup=str(name), icon=folium.Icon(color='green')))**

map.add_child(fg)

map.save("Map4.html")
```

![python](https://user-images.githubusercontent.com/32303129/34918609-427bbc3c-f966-11e7-89c1-c73f48a6b79e.JPG)

#### Problem description

I have a code sample like that but in popup if I assing like popup='Sample' it runs, but if I assign popup=str(name) like in my sample code(line 15) it doesn't run.

How Should I use that with a string?

Thank you

**Comment by sergiolucero** [comment]
«Doesn't run» is not informative. Can you provide the full error?

**Comment by muticansel** [comment]
If I use like this, I get an empty Map4.html file like as follows

![map4](https://user-images.githubusercontent.com/32303129/34933041-765e328e-f9e6-11e7-841b-35d3c5cfe7d2.JPG)

**Comment by muticansel** [comment]
This is my volcanoes.txt file, if it helps

[volcanoes.txt](https://github.com/python-visualization/folium/files/1630840/volcanoes.txt)

**Comment by paulochf** [comment]
Hey @muticansel, could you try to remove any single or double quotes from your volcano names and try it again?

In your `for` loop, do something like `popup=str(name.replace("'", "").replace('"', ""))`.

**Comment by ocefpaf** [comment]
If you have special characters in your popup text you must parse it as HTML.
See http://nbviewer.jupyter.org/gist/ocefpaf/76f228951d264d0e4dcb091f9e7435fa

**Comment by paulochf** [comment]
I would prefer to remove the chars, so one can use HTML with it.
