### ISSUE TITLE
Layer control and Fullscreen disappear after adding another layer

### ISSUE THREAD

**Issue by TichyProgs** [python-visualization/folium#816]
#### Here is the first part of the code where I create a map with many layers 

```python
mapa_keys = folium.Map(width=1000, height=1000, zoom_start=11,
                  location=[53.132489, 23.16884], tiles='cartodbpositron')

for key in list(locations_dict.keys()):
    HeatMap(locations_dict[key], name=key, radius = 20).add_to(mapa_keys)  

folium.LayerControl().add_to(mapa_keys)
plugins.Fullscreen(
    position='topright',
    title='rozwiń na pełny ekran',
    title_cancel='wyłącz tryb pełnego ekranu',
    force_separate_button=True).add_to(mapa_keys)
mapa_keys.save("static_per_type.html")

```
Explanations: structure of the `locations_dict` is just like 
`{"something": [[lat,lon], [lat,lon]... ] ... }`
#### Then I decided to add a different heat map that is not included in the dictionary I've mentioned
```
others_hm = HeatMap(locs, name="others", radius=20)
kibice_hm.add_to(mapa_others)
kibice_hm.add_to(mapa_keys)
folium.LayerControl().add_to(mapa_keys)
mapa_keys.save("static_extended.html")
```
#### Problem description

The HeatMap object alone works – on a the `mapa_others` everything looks fine.
__The problem is with the bigger map.__  I'd like to have the heat map just as a another layer on the working map I created earlier but instead I get the layer added but LayerControl and Fullscreen button disappear so that I can't chose the layer.
__The buttons are simply not showing up after adding another HeatMap layer__

**Comment by Conengmo** [comment]
I'm assuming your input data is not correct, since the map will not finish loading if there is an error in the heatmap part. What is the structure of your `locs` variable?

Next time try to include [a self contained code snippet](http://sscce.org/), so we don't have to guess about your variables. If I copy your code example I should be able to run it and see the same problem you have.

**Comment by Conengmo** [comment]
I'm closing this issue since there is no update on it. Feel free to add additional info, we can reopen if needed.

**Comment by jakobgager** [comment]
There seems to be a problem with the ordering of the individual entities.
If you take the following code snippet:

``` python
m1 = folium.Map(location=[51.4646341, 7.0022209], zoom_start=14)
f1 = folium.FeatureGroup(name='F1').add_to(m1)
# f2 = folium.FeatureGroup(name='F2').add_to(m1)  # ---> works fine (2)

folium.PolyLine([[51.4646341, 7.0022209],[51.4666341, 7.0022209]]).add_to(f1)
folium.LayerControl().add_to(m1)   # ---> when moved to the end, everything is working again

f2 = folium.FeatureGroup(name='F2').add_to(m1)   # ---> not working (1)
folium.PolyLine([[51.4646341, 7.0022209],[51.4646341, 7.0042209]], color='red').add_to(f2)
```

There are two cases considered here:
(1) if the second feature group is added to the map after the layer control is added, there is a rendering error
(2) if the second feature group is added to the map before the layer control is added, it works fine.

Is there a possibility to reorder the children of the map and force a rerendering?
I tried to modify m1._children appropriately, but this had no impact on the resulting html code.

**Comment by DipanshuShukla** [comment]
Did anyone find any solution to this issue?

**Comment by Conengmo** [comment]
Both folium and Leaflet require the LayerControl to be added last: otherwise it doesn't know what layers there are.
