### ISSUE TITLE
Use highlight_function not to change choropleth connected things

### ISSUE THREAD

**Issue by TichyProgs** [python-visualization/folium#817]
Now using highlight_function in the `folium.GeoJson` feature looks something like this
```python
highlight_function = lambda feature:  {
        "fillColor":  colourmap(val_dictionary[feature["properties"]["name"]]),
        "fillOpacity": 1,
    },
```
with `val_dictionary` being a dictionary with values connected to each feature ie. name. 
But I'd like to have something like this
```python
highlife_function = lambda feature: print(feature["properties"]["name"])
```
but of course that is not possible. I'd just like to have some kind of a callback function for the highlight event that wouldn't involve changing choropleth connected thing like colour and so on but rather make it possible for me to create a marker with some property of the feature. Literally anything but to don't use the dictionary because if you now try to do something like this than you get a message that None type object is not iterable
Is there possible to do in any other way or is it something yet impossible?
Cheers
``folium.__version__`` outputs ``0.5.0``

**Comment by Conengmo** [comment]
The behavior you're describing sounds like a tooltip. We're actually working on this in PR #883. Since there is already a discussion on this feature in issue #867 I'm closing this one.
