### ISSUE TITLE
When folium 0.6.0 in pip?

### ISSUE THREAD

**Issue by paulochf** [python-visualization/folium#818]
I'm using folium here, and I realized that the master version has https://github.com/python-visualization/folium/pull/723 already, but I could not install if because it's not in pip yet.

**Comment by ocefpaf** [comment]
Soon.

**Comment by paulochf** [comment]
Thank you!

**Comment by pjandrews** [comment]
Any update on when 0.6.0 will be available? Or if I can access it a little early :). I'm excited to start using the search plugin. 

Thanks so much for making this great tool!

**Comment by Conengmo** [comment]
I hope we can publish a new version once we've processed the pending merge requests. In the mean time if you want to use the most recent version you can [pip install folium from git](https://pip.pypa.io/en/stable/reference/pip_install/#git) directly. I haven't tried this yet, but these links should work:

```
git://github.com/python-visualization/folium.git@master#egg=folium
git://github.com/python-visualization/branca.git@master#egg=branca
```
