### ISSUE TITLE
Value Error from utilities _isnan

### ISSUE THREAD

**Issue by johnfwhitesell** [python-visualization/folium#820]
Around line 70 of the folium\utilities file is:
```
def _flatten(container):
    for i in container:
        if isinstance(i, (list, tuple)):
            for j in _flatten(i):
                yield j
        else:
            yield i

def _isnan(values):
    """Check if there are NaNs values in the iterable."""
    return any(math.isnan(value) for value in _flatten(values))
```

This threw an exception for me saying that a scalar needed to be size=1.  However switching the second function over to:
```
def _isnan(values):
    """Check if there are NaNs values in the iterable."""
    return any(math.isnan(value) for value in np.ndarray.flatten(values))
```

seemed to fix my problem.

**Comment by Conengmo** [comment]
Thanks for reporting this. I'm guessing it's the same as #782, which has been fixed already in PR #758. This has not been released yet though. You already have a work around so that's good. You could also install the version from the master branch.
