### ISSUE TITLE
**kwargs in folium.features.WmsTileLayer not passed on

### ISSUE THREAD

**Issue by kmunve** [python-visualization/folium#823]
```python
lat, lon, zs = 69.6, 19.4, 13#9

m = folium.Map(location=[lat, lon], zoom_start=zs, tiles="OpenStreetMap")

topo4 = folium.features.WmsTileLayer(url="http://openwms.statkart.no/skwms1/wms.topo4?",
                                         layers="topo4_WMS", transparent=True, fmt="image/jpeg",
                                         name="Topo4", minZoom="10")
topo4.add_to(m)

# minZoom is not passed on to leaflet - works when set manually in the .html file

m.save('test.html')

```
#### Problem description

I try to set the minZoom attribute of L.tileLayer.wms using **kwargs in folium.features.WmsTileLayer.
No error is produced, but the attribute is not set in the resulting html document.

#### Output of ``folium.__version__``
0.5.0

**Comment by Conengmo** [comment]
It seems that the minZoom attribute is not defined. The **kwargs are only specific options for the WMS tile layer. There are seven options, as listed here:
http://leafletjs.com/reference-1.2.0.html#tilelayer-wms

The 'regular' TileLayer class does accept the minZoom argument. I reckon you expect WMSTileLayer to accept the same arguments as TileLayer? Or what would you suggest?

**Comment by kmunve** [comment]
Hi, yes in Leaflet the WMSTileLayer is a sub-class of TileLayer and inherits its attributes/methods. So in Leaflet I can set the "minZoom" attribute for a WMSTileLayer. Would be great if it would be possible to pass on all inherited attributes directly from folium as well.

**Comment by Conengmo** [comment]
Good suggestion, this could use some work in Folium. In TileLayer the Leaflet options are directly parsed in the init, in WMSTileLayer a separate `_parse_wms()` function is used. 

My first thought is to have TileLayer and WMSTileLayer each have their options as explicit arguments. Then WMSTileLayer also accepting **kwargs which may contain TileLayer options. Something like this:

```
class TileLayer(Layer):
    def __init__(self, tl_opt1, tl_opt2):
        options = self.parse_options(tl_opt1=tl_opt1, tl_opt2=tl_opt2)
        self.options = jsonify(options)

    def parse_options(self, **kwargs):
        return {'tl_opt1': kwargs.pop('tl_opt1'), 'tl_opt2': kwargs.pop('tl_opt2')}


class WMSTileLayer(Layer):
    def __init__(self, wms_opt1, wms_opt2, **kwargs):
        options = self.parse_options(wms_opt1=wms_opt1, wms_opt2=wms_opt2)
        options.update(TileLayer.parse_options(**kwargs))
        self.options = jsonify(options)

    def parse_options(self, **kwargs):
        return {'wms_opt1': kwargs.pop('wms_opt1'), 'wms_opt2': kwargs.pop('wms_opt2')}
```

Another idea is to wait with jsonifying the options until rendering. That way a user can add things to a `self.options` dictionary.

I'm not sure what the best solution would be here. Any other thoughts?

**Comment by kmunve** [comment]
Hi, 
I haven't look much into the implementation - so I am afraid I am not much help in finding the best solution at the moment. If I understand it correctly, WMSTileLayer and TileLayer are currently independent in Folium, right? Would it be an option to make WMSTileLayer a child of TileLayer in folium?

**Comment by Conengmo** [comment]
This has been done in #838.
