### ISSUE TITLE
HeatMap colors not rendered

### ISSUE THREAD

**Issue by rmania** [python-visualization/folium#827]
I'm running the code as in https://github.com/alysivji/divvy-station-heatmap-folium/blob/master/1-create-divvy-station-heatmap.ipynb but the Heatmap is not rendered with the right colors: all circles are blue. The only difference is that I'm running it in folium.__version__ == '0.5.0'  and the example code is with folium_version__ == ' 0.2.1' 

Code (identical) but see screenshot of the map. Q:) How to fix this? I would love to start using the Heatmap Plugin functionality of Folium.

Code:
```
# for reproducability:
#!wget "https://s3.amazonaws.com/divvy-data/tripdata/Divvy_Trips_2016_Q3Q4.zip"
#!mkdir data
#!mv Divvy_Trips_2016_Q3Q4.zip data/Divvy_Trips_2016_Q3Q4.zip
#!unzip data/Divvy_Trips_2016_Q3Q4.zip -d data/Divvy_Trips_2016_Q3Q4

divvyStations_q3 = pd.read_csv('data_test/Divvy_Trips_2016_Q3Q4/Divvy_Stations_2016_Q3.csv')
divvyStations_q4 = pd.read_csv('data_test/Divvy_Trips_2016_Q3Q4/Divvy_Stations_2016_Q4.csv')

# combine and keep the first instance of id
divvyStations = pd.concat([divvyStations_q3, divvyStations_q4], axis=0).drop_duplicates(subset=['id'])

# convert to (n, 2) nd-array format for heatmap
stationArr = divvyStations[['latitude', 'longitude']].as_matrix().tolist()

m = folium.Map([41.8781, -87.6298], zoom_start=11)

# mark each station as a point
for index, row in divvyStations.iterrows():
    folium.CircleMarker([row['latitude'], row['longitude']],
                        radius=15,
                        popup=row['name'],
                        fill_color="#3db7e4", # divvy color
                       ).add_to(m)

m.add_child(plugins.HeatMap(stationArr, radius=15))
m
```

screenshot: 

![screenshot_heatmap_folium](https://user-images.githubusercontent.com/8605612/36730933-66279ca2-1bc9-11e8-9b2f-7e4b304dcad6.png)

zooming in:

![screenshot_zoom_heatmap_folium](https://user-images.githubusercontent.com/8605612/36731172-3447558c-1bca-11e8-9d98-42edfbb377ff.png)

**Comment by parambidja** [comment]
Were you able to solve this issue? I'm having the same problem.

**Comment by Conengmo** [comment]
You can try to change the `radius` option. If you set it larger, the circles will overlap more and the 'heat' will increase, so the color will change.

**Comment by Dhanesh-raj** [comment]
/home/dhaneshraj/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  # This is added back by InteractiveShellApp.init_path()
