### ISSUE TITLE
Graph on map 

### ISSUE THREAD

**Issue by RiptideBo** [python-visualization/folium#829]
#### Problem description

I wonder is there a efficient way to **draw a graph** (or network) on map ? 
especially **complex network** with large nodes and edges !

data format maybe like:

[[lat_1, lon_1, lat_2, lon_2], 
[ ... ]
[ ...]]
and maybe with edge weight for edge color.

#### folium 
I use **polyline** for the edges, but the output is not satisfied ! 
#### geoplotlib
I try the **graph  in geoplotlib**, the color of edges cannot be changed ! 

anyone could give me some suggestion??

**Comment by Conengmo** [comment]
You're opening an issue on folium, so let us know what's wrong. Why is the output not satisfying? 

If you want suggestions on other libraries, I think this is not the right place for that. Maybe try Stackoverflow? You should open an issue here if you have a problem or suggestion for folium.

**Comment by RiptideBo** [comment]
Sorry about it, no offense。 I **appreciate** folium and It helps a lot!

### My problem
What I did:  I use geojson libaray to make my geojson data, then pass it to Folioum.Geojson

The geojson contains only lines But **Large numbers of lines**, so the saved html file would be really **big**，maybe more than 100M, while the chrome cannot open it.

**Comment by Conengmo** [comment]
If there is that much data, it may be that there is no way to make it more efficient. But I can't really tell without knowing the data and benchmarking different approaches. 

I'll share some thoughts, maybe it helps:

- Can you reduce your data? Maybe reduce the resolution by using less points per line. Or drop less important lines.
- Try to find the best way to make your map in [Leaflet](http://leafletjs.com). folium is 'just' a wrapper for Leaflet, so if you know what the best way in Leaflet is, you know what the best way in folium is. You can use a fiddle like [this one](http://jsfiddle.net/jsanz/Pe5xU/) as a starting point.
- Use the developer tools in your browser to find out which parts are making loading your map in Chrome slow.

My guess would be that providing your edges as a single array to PolyLine should be efficient, not considering edge weight.
```
# create a multipolyline from an array of arrays of LatLng points
PolyLine([
    [[45.51, -122.68],
     [37.77, -122.43],
     [34.04, -118.2]],
    [[40.78, -73.91],
     [41.83, -87.62],
     [32.76, -96.72]]
])
```

**Comment by RiptideBo** [comment]
Thanks a lot. I took your advice as following:

1. changing the directed edges to undirected ones which reduce maybe 40% number of edges. (There still are 144,018 non-duplicate edges ) 

2. Using multi-polyline. Actually this is really tough work to combine the lines to possible multi-polyline，It costs much time to do this. But it still reduce some of the geometry. 


#### Here is my testing:
Edges: 40000

- test 1:
 Using geojson.FeatureCollection() and pass it to folium.Geojson()， 
 html size: 2,33MB
- test2: 
  Using Folium.PolyLine() once for all multi-lines.
  html size:  893 KB

**Polyline** is much better than **Geojson** in this way. 

code as following:
Note that in geojson.Polyline() the location is like **(lng,lat)** while folium.Polyline() is **(lat, lng)**

```Python

import folium
import geojson

map_1 = folium.Map(location= [38, 119])
map_2 = folium.Map(location= [38, 119])

# data format
lines = [
    [[38,119],[39,120],[40,119]],
    ...
    [[38,119],[39,120],[40,119]]]

# map_1
feature_all = []
for i, each in enumerate(lines):
    polygon_i = geojson.Polygon(tuple([each, ]))
    property_i = {'Idx': str(i)}
    feature_i = geojson.Feature(id=str(i),
                                geometry=polygon_i,
                                properties=property_i)
    feature_all.append(feature_i)

feature_all = geojson.FeatureCollection(feature_all)
folium.GeoJson(feature_all,style_function=lambda feature:
               {'fillColor': None,'weight': 0.8,'line_opacity': 0.8, }).add_to(map_1)
# map_2
folium.PolyLine(lines,weight=0.8,line_opacity=0.8).add_to(map_2)
```

**Comment by Conengmo** [comment]
Interesting comparison, thanks for sharing your results!

Based on this, do you have any suggestions for changes or features for folium? Otherwise can this issue be closed?

**Comment by RiptideBo** [comment]
Folium works very well, no other questions for now. Thanks again.
