### ISSUE TITLE
Check if we can make all href protocol agnostic

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#83]
folium maps do not work properly when hosted in a https protocol:

`https://ocefpaf.github.io/python4oceanographers/blog/2015/02/02/cartopy_folium_shapefile`

`http://ocefpaf.github.io/python4oceanographers/blog/2015/02/02/cartopy_folium_shapefile`

**Comment by birdage** [comment]
@ocefpaf can confirm i have the same issue

**Comment by wrobstory** [comment]
Can prooooooobably just take out any hardcoded `http` and replace with `//`, like in this PR: https://github.com/wrobstory/vincent/pull/133

**Comment by ocefpaf** [comment]
Tried that and I either missed one or felt into the probability tail :grimacing:  I will have a PR later today.

**Comment by ocefpaf** [comment]
Here is what I learned so far:

- I missed a few "http" in my first try (everything inside `folium/templates/tiles/`) and now basic maps work with https (e.g: [mapa.html](https://dl.dropboxusercontent.com/u/4411725/mapa.html) and [mapa2.html](https://dl.dropboxusercontent.com/u/4411725/mapa2.html)).  I had to browse to https://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js and manually authorize the bad certificate.

- d3js.org is http only, so I changed `<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>`
to `<script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.3/d3.min.js" charset="utf-8"></script>`

- Still that is not enough to get geojson working because I could not find a https cdn server for 
"http://d3js.org/queue.v1.min.js"

**Comment by ocefpaf** [comment]
PR #93 fix this for all the JavaScript.  Checking for the tile URLs now (#98).
