### ISSUE TITLE
ImportError: cannot import name 'TimeSliderChoropleth'

### ISSUE THREAD

**Issue by timrovers** [python-visualization/folium#831]
#### I'm trying to create a time slider on a map with Folium using the TimeSliderChoropleth function, but I'm getting import error issues:

```python
from folium.plugins import TimeSliderChoropleth
```
#### Which returns:
```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-db71c7b4091c> in <module>()
----> 1 from folium.plugins import TimeSliderChoropleth

ImportError: cannot import name 'TimeSliderChoropleth'
```

I'm following this example: http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/TimeSliderChoropleth.ipynb
One thing I noted was that the example uses a different version of folium, namely: 0.5.0+77.g9682778.dirty, which I don't see as a possibility to install from pip install. Is the function removed in folium 0.5.0 ?

#### Output of ``folium.__version__``
0.5.0

**Comment by olavrel** [comment]
I guess this will be available in the upcoming 0.6.0 release. Checking the [source ](https://github.com/python-visualization/folium/commit/4601883ac8312cf5552ce8e7db5a585a9ea61ef8#diff-177b7c45e1ed2b6ffc502140e0e0ab6d)it seems that it is based on `TimestampedGeoJson `in the `plugins `module which is available in 0.5.0. However the functionality might be different for all I know.

**Comment by timrovers** [comment]
**Thanks for the answer. We tried it again installing it via the source, but now get a different error. After entering this block of code (also from the example)**

```
m = folium.Map([0, 0], tiles='Stamen Toner', zoom_start=2)

g = TimeSliderChoropleth(
    gdf.to_json(),
    styledict=styledict,

).add_to(m)

m.save(os.path.join('results', 'TimeSliderChoropleth.html'))

m
```


 **Which returns**

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-ba12f19efd00> in <module>()
      5 g = TimeSliderChoropleth(
      6     gdf.to_json(),
----> 7     styledict=styledict,
      8 
      9 ).add_to(m)

<ipython-input-2-a76e1ec42b39> in __init__(self, data, styledict, name, overlay, control, show)
     35         super(TimeSliderChoropleth, self).__init__(data, name=name,
     36                                                    overlay=overlay,
---> 37                                                    control=control, show=show)
     38         if not isinstance(styledict, dict):
     39             raise ValueError('styledict must be a dictionary, got {!r}'.format(styledict))  # noqa

TypeError: __init__() got an unexpected keyword argument 'show'
```
We can't find any clear answer to what this could be. Is there something we can do about this? If not and if we need 0.6.0, is there any indication when this will be online?

**Comment by Conengmo** [comment]
Hi Tim, the `show` argument was added in #772, so if you're on master it should work. I tried the TimeSliderChoropleth example and got no error. Maybe you have some stale files? Can you check if you have all the files updated from master?

**Comment by Conengmo** [comment]
Since I haven't heard back I'm assuming the issue has been resolved. If not feel free to reopen the issue with additional information.

**Comment by Conengmo** [comment]
If you want to use the most recent version you can install from git directly with pip using these instructions:
https://pip.pypa.io/en/stable/reference/pip_install/#git

I haven't tried this yet but using these links should work:

```
git://github.com/python-visualization/folium.git@master#egg=folium
git://github.com/python-visualization/branca.git@master#egg=branca
```

**Comment by Awsom1** [comment]
Hi @Conengmo Thanks for the reply mate. Really appreciate it
 I already tried this method by running:
(pip install -e git://github.com/python-visualization/folium.git@master#egg=folium)
but when I run the : 
print(folium.__version__) in jupyter it shows the 0.5.0 version and trying to import the 
from folium.plugins.time_slider_choropleth import TimeSliderChoropleth command only gives me an error 
ModuleNotFoundError: No module named 'folium.plugins.time_slider_choropleth'

any other ideas I could try? Do I need to restart my laptop?

**Comment by Awsom1** [comment]
That seems to do the trick. @Conengmo thanks again for the help. will try to plot my data now. Cheers
