### ISSUE TITLE
Is it possible to draw a ring with both inner and outer diameter in meters?

### ISSUE THREAD

**Issue by Agnpalm** [python-visualization/folium#832]
I'd like to draw a ring with known inner and outer diameter, both in meters. `folium.Cirlce()` draws a circle with radius in meters, and if I set `fill=False` and `weight` to something like 100 I get a ring, but since the weight is in pixels it changes depending on zoom.
![image](https://user-images.githubusercontent.com/25202385/37381025-6b8ae37a-273b-11e8-9cdd-478371082d48.png) 
![image](https://user-images.githubusercontent.com/25202385/37380997-4f6abf26-273b-11e8-870b-b79e5684addd.png)

Wouldn't it make sense to be able to specify the inner radius in meters as well? Is there a different way to draw a ring like this?

**Comment by Conengmo** [comment]
You're right, the `weight` parameter is in pixels. This is Leaflet behavior, so it is outside the scope of folium. See the options inherited from Path: http://leafletjs.com/reference-1.3.0.html#circle

I couldn't quickly see a way to do what you want. Maybe a hack could be to make multiple overlapping circles?
```
for i in range(20):
    folium.Circle([0, 0], radius=100 + i, weight=10).add_to(m)
```

**Comment by Conengmo** [comment]
I'm closing this issue, since it's not something we can fix in folium. If anybody finds a way to do it with the Leaflet api, please post it here.
