### ISSUE TITLE
[need help] save as high quality picture?

### ISSUE THREAD

**Issue by RiptideBo** [python-visualization/folium#833]
#### Problem description

Is there anyway to save the map result as picture format instead of html ？ especially with high resolution.

any solution to this?  Thanks!

**Comment by Conengmo** [comment]
This type of functionality is outside of the scope of folium. folium 'only' makes the html and javascript, it doesn't include anything to render the html and javascript. You would have to look elsewhere, I'm sure there are many options, maybe even within Python.

**Comment by Conengmo** [comment]
Actually, there is [a method in folium.Map](https://github.com/python-visualization/folium/blob/9e2ee744943de2de920ca72631173b56ff588fbf/folium/folium.py#L275) to render the map as png, but I'm not sure about it's status. I didn't get it to work immediately because of selenium. Maybe you can try it out and let us know when it works?

**Comment by RiptideBo** [comment]
Thanks for your advice a lot. I have tried this with folium 0.5.0. 

The method **to_png**  raised a PermissionError: [Errno 13] Permission.

I am not familiar with selenium and how the web driver works. If it is screen shot, the resolution might still be well enough for pulishing. Anyway, It is still a fantastic way for visualization. Thanks again.

**Comment by Conengmo** [comment]
I had the same error, something to do with permission to write a file in a temporary folder. Luckily Selenium is easy to use. I've been doing some webscraping lately so I'll share a method:

Get the Selenium bindings for Python if you don't already have them. `pip install selenium`

Get a webdriver. I'm on Windows and use phantomjs. Just get the phantomjs.exe [here](http://phantomjs.org/) and put it in a directory where your script can find it. For example the same folder.

Make a folium map, making sure you set the initial location and zoom as you want, and save.

```
m = folium.Map([initial_lat, initial_lon], zoom_start=initial_zoom)
m.save('map.html')
```

Load the map with Selenium and save a screenshot.
```
import selenium.webdriver
driver = selenium.webdriver.PhantomJS()
driver.set_window_size(4000, 3000)  # choose a resolution
driver.get('map.html')
# You may need to add time.sleep(seconds) here
driver.save_screenshot('screenshot.png')
```

**Comment by RiptideBo** [comment]
Thanks for your advice and sorry for replaying you so late.
I tried this solution with **headless chromedriver** instead of **Phantomjsdriver**, it works just well.

with time delay, I can save the exact result as photo format which in some circumstances is optional and helpful way for visualization. And it is true that html is the best in general. 

Thank you and folium again.

**Comment by ocefpaf** [comment]
@RiptideBo PR https://github.com/python-visualization/folium/pull/1015 tries to improve this a little bit but your opinion there is welcome! Closing this b/c, as @Conengmo said, folium's goal is not to provide that functionality and the `to_png()` is experimental for now.

**Comment by couzhei** [comment]
j
