### ISSUE TITLE
multiple instances of HeatMapWithTime

### ISSUE THREAD

**Issue by shis0u** [python-visualization/folium#834]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
cityMap = folium.Map(location=CITY_COORD, zoom_start=11,
                     tiles="cartodbpositron", height=700)

heatMapGrp = folium.FeatureGroup(name='Heatmap', overlay=False)
heatMapDN = plugins.HeatMapWithTime(carDataDN, index=timeIndexDN, name="DriveNow",
                                    auto_play=False, max_opacity=0.6)
heatMapGrp.add_child(heatMapDN)
heatMapC2G = plugins.HeatMapWithTime(carDataC2G, index=timeIndexC2G, name="Car2Go",
                                     auto_play=False, max_opacity=0.6)
heatMapGrp.add_child(heatMapC2G)

# cityMap.add_child(heatMapGrp)
cityMap.add_child(heatMapDN)
cityMap.add_child(heatMapC2G)

cityMap.add_child(folium.LayerControl())
cityMap.save(os.path.join('results', 'D:/heatmap_berlin_dn_all.html'))

```
#### Problem description

I have two data sets, both work separated without problems. 
Using `FreaturedGroup` doesn't seem to work at all (resulting in an empty map). Adding both directly to the map and `LayerControl` after that seems to work partly. Partly because two sliders are displayed simultaneously and if one data set is selected the `TileLayer`disappears.

Am I doing something wrong or is there a workaround for it? 

#### Expected Output

A Map with selectable instances of HeatMapWithTime

#### Output of ``folium.__version__``
0.5.0

**Comment by Conengmo** [comment]
I tried to reproduce your problem, but couldn't even get the heatmap with time example to work :(

Why do you add a feature group? If you want to be able to select which instance of HeatMapWithTime you want to display, you can add both add them to the map, and they should both turn up in layer control.

```
m = Map()
HeatMapWithTime(data1).add_to(m)
HeatMapWithTime(data2).add_to(m)
```

FYI, a feature group is meant to group items and display them together. The items themselves don't get added to the map directly. For example:
```
fg = FeatureGroup().add_to(m)
fg.add_child(Item1)
fg.add_child(Item2)
```

Does this answer your question?

**Comment by Conengmo** [comment]
I hope my answer solves your problem, so I'm closing this issue. Feel free to add any further info or question, or to reopen the issue.

**Comment by kjarus1** [comment]
The problem has not been solved.

FeatureGroup() does not seem to work with HeatMapWithTime and adding layers directly to the heatmap results in multiple time sliders on the side when there should be only one (common) time slider for all added layers.

**Comment by Conengmo** [comment]
Hi @kjarus1, if you want to have a single control you'll have to put all your data in a single geojson and use that.
