### ISSUE TITLE
Folium Map not Rendering in Jupyter Notebook When Markers are Added

### ISSUE THREAD

**Issue by flanabode** [python-visualization/folium#835]
I'm using code directly from http://folium.readthedocs.io/en/latest/quickstart.html

This will render the map just fine (with the markers commented out):

map_2 = folium.Map(location=[45.372, -121.6972],
                   zoom_start=12,
                   tiles='Stamen Terrain')
#folium.Marker([45.3288, -121.6625]).add_to(map_2)
#folium.Marker([45.3311, -121.7113]).add_to(map_2)
map_2

But when I un-comment those two Marker lines, I get no error message, but the map doesn't render, I just get a plain white space. I'm just trying to familiarize myself with folium, so sorry if I'm missing something obvious.

**Comment by flanabode** [comment]
It was a browser issue. Apparently, Microsoft Edge isn't fully supported. It worked great in Chrome.

**Comment by Conengmo** [comment]
Good to know that Leaflet in Edge may cause problems. I'm closing this issue.

**Comment by bag189** [comment]
I am having the same issue when trying to add 4000+ sized markers.  Working in Google Chrome
