### ISSUE TITLE
HereMaps support

### ISSUE THREAD

**Issue by grzjab** [python-visualization/folium#839]
Leaflet plugins allow Here Maps (previously Nokia Here) as a map provider: https://github.com/leaflet-extras/leaflet-providers

It would be useful to implement different providers also in folium.

**Comment by Conengmo** [comment]
There already are a couple free and non-free maps built in. They are listed in the getting started guide
(http://python-visualization.github.io/folium/docs-v0.5.0/quickstart.html#Getting-Started) and in the docstring for TileLayer. (http://python-visualization.github.io/folium/docs-v0.5.0/modules.html#folium.map.TileLayer)

Here Maps is not included, but you could add it by creating a new tile template (in folium/folium/templates/tiles). TileLayer accepts an `APIkey` argument, but for Here Maps you would need an app id and code, so this part of TileLayer must be altered for this.

**Comment by ocefpaf** [comment]
One can easily use different providers with the tiles keyword. Here is an example on how to add HERE MAPS:

```python
import os
import folium

keysc = map(os.getenv, ['HEREMAPS_APP_ID', 'HEREMAPS_APP_CODE'])

tiles = f(
    'https://1.base.maps.api.here.com/maptile/2.1/maptile/newest/normal.day/{z}/{x}/{y}/256/png8?'
    'lg=eng&
    'app_id={app_id}&'
    'app_code={app_code}'
)

folium.Map(location=(42, -42), tiles=tiles, zoom_start=10, attr='HERE.com')
```

Note that we don't plan to add more shortcut for providers b/c those change constantly and update the code to follow the changes can be taxing. So it is up to the end user to find the provider they want to use.

**Comment by KALAIVANIRAMALINGAM** [comment]
I have tried to load the heremaps in the folium, it is not loaded.Could you please help me how to load a heremaps in folium?
