### ISSUE TITLE
Folium Marker PopUps as well as ControlElements like the LayerSelector do no scale on mobile devices

### ISSUE THREAD

**Issue by agnahi** [python-visualization/folium#842]
#### Problem description

Folium Marker PopUps as well as ControlElements like the LayerSelector do no scale on mobile devices. On small displays they are displayed so small that this is not useable.

As a workaround I inject 
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
```

into the head section of the HTML output page after creation.

#### Expected Output

I am looking for an easy way to either inject custom HTML code into the generated output page
OR
a switch to enable mobile support (which does something like the manually injected line of code from above)

**Comment by Conengmo** [comment]
You're right, the elements don't scale on mobile. And your workaround is also what [Leaflet gives as an example](http://leafletjs.com/examples/mobile/).

You can add the line to the head section with this:

```
m.get_root().header.add_child(folium.Element(
    '<meta name="viewport" content="width=device-width,'
    ' initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />'
))
```

Do you think this should be added to folium maps by default? Assuming it doesn't affect behavior on desktop, and on mobile this is always wanted.
