### ISSUE TITLE
gdal problem when deploying to Heroku?

### ISSUE THREAD

**Issue by nomadcreator** [python-visualization/folium#843]
When I tried to deploy a Django website using Folium, I have an error (shown below) saying there is no  GDAL library.
The site runs without any problem on local, and the site on the server worked without any problem before implementing Folium.
 
I am not sure this is really caused by Folium since I tried to install various packages during try-and error of implementing Folium, but if there is anyone who has the same issue,  I want to ask how to fix. h

#### Expected Output

   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/admin/__init__.py", line 5, in <module>
remote:            from django.contrib.gis.admin.options import GeoModelAdmin, OSMGeoAdmin
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/admin/options.py", line 2, in <module>
remote:            from django.contrib.gis.admin.widgets import OpenLayersWidget
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/admin/widgets.py", line 3, in <module>
remote:            from django.contrib.gis.gdal import GDALException
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
remote:            from django.contrib.gis.gdal.datasource import DataSource
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
remote:            from django.contrib.gis.gdal.driver import Driver
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
remote:            from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
remote:            from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/gdal/libgdal.py", line 43, in <module>
remote:            % '", "'.join(lib_names)
remote:        django.core.exceptions.ImproperlyConfigured: **Could not find the GDAL library** (tried "gdal", "GDAL", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0", "gdal1.11.0", "gdal1.10.0", "gdal1.9.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
remote:
remote:  !     Error while running '$ python manage.py collectstatic --noinput'.
remote:        See traceback above for details.

**Comment by Conengmo** [comment]
As far as I know folium doesn't use GDAL. It seems [Django does](https://docs.djangoproject.com/en/2.0/ref/contrib/gis/gdal/) and also lists [your error in its installation guide](https://docs.djangoproject.com/en/2.0/ref/contrib/gis/install/geolibs/#gdaltrouble). My guess would be that folium has nothing to do with this problem, but maybe you can verify by disabling your usage of folium and seeing if the problem persists.

**Comment by nomadcreator** [comment]
Thank you. 
It is nice to know that this issue is nothing related with folium, and also know this is a typical issue of Django GeoSpatial.

**Comment by Conengmo** [comment]
Closing the issue since it seems unrelated to folium. Feel free to comment here or reopen the issue when you have updates. If you find a solution, it would be nice if you could report it here for future readers.
