### ISSUE TITLE
Dynamicaly change/update markers

### ISSUE THREAD

**Issue by siezyj** [python-visualization/folium#848]
I`m want to make webapp with Django which displays a map for every user on the main page. What I want to have:

1.Every user can add a marker to map and every other user see those markers immediately.
2.Every user can delete marker if he is owner of that marker and other user will see those changes immediately.
3.If user A "is intrested" with user B (this information is stored in DB) he (A) sees markers of user B in a different way than others ( different color or marker image).

My idea is to create once a html file without markers and creat separate function which will be updateing map for every user separetly. I want to use Memecahce to dynamic update the map. If somebody add new marker, specific  function shoudl add new marker without makeing and reolading whole map. I need that becouse application can have a lot of user with a lot of markers so it could be too expensive for server(reolading all markers after every update).

My question : How to change/add markers to map dynamicaly after creating a map file or maybe you have better idea to solve that problem.

**Comment by Conengmo** [comment]
Sounds like an interesting project! In short: unfortunately folium cannot do this, though it could be an interesting addition.

It's import to understand that folium generates the html with [Leaflet](http://leafletjs.com/) javascript and after that is finished. So anything that happens on the map after generation is outside of folium's scope.

Now there have been ideas of getting callbacks from javascript back to python, mainly for in the Jupyter environment. I can imagine something like that could also work for Flask or Django, where some javascript ajax calls retrieve new data. This is not available in folium though, but of course you're welcome to work on adding this.

folium works great for creating ad hoc maps with python data. For your application I would suggest not to use folium but to use Leaflet directly. You need a fixed map layout and very good integration with your web application, not to create various maps with differing Python data, which is folium's strong point. Of course you can use a map created by folium as inspiration for how to use Leaflet of course.

But that's my opinion. Hope it helps! Maybe others will chime in as well.

**Comment by Conengmo** [comment]
A quick search shows that there is a lot written about for example [dynamic data for Leaflet](http://leafletjs.com/plugins.html#dynamiccustom-data-loading). Good luck with this! I'll close the issue if that's alright with you, feel free to reopen if you have something that could be done about folium. Also, it would be great if you could add any solutions you come up with here and help others who are coming from folium and want to do a similar thing.
