### ISSUE TITLE
click event for a rectangle and draw

### ISSUE THREAD

**Issue by Jeisk** [python-visualization/folium#854]
Hi,   I have started recently to work with folium.  I would like to draw coordinates(like a line) when I click on a rectangle. I see that popup show text but Idk how to do

Thanks!

**Comment by Conengmo** [comment]
Hi Jeisk, I'm not sure what you're trying to do... You want a rectangle that if you click on it, another line appears? 

This is as far as I know not possible in folium. So this would probably require you to manipulate the underlying Leaflet Javascript. For example a click event on the rectangle polygon, that calls the AddTo method on the Polyline. I would recommend developing this in a [JSFiddle](https://jsfiddle.net/jsanz/Pe5xU/). Also, checkout the Leaflet documentation for how to do this:
http://leafletjs.com/reference-1.3.0.html#polyline

If you find some Javascript that works for you, you can add it to your map through folium:
```
m = folium.Map()
code = 'some javascript code'
m.get_root().script.add_child(folium.Element(code))
m
```

Also it would be nice if you can report your progress back here so others can learn from it as well!

**Comment by Conengmo** [comment]
I'm closing the issue, feel free to add new info or updates and we can reopen.

**Comment by aryberberian** [comment]
Hey @Conengmo , is there a way to add the code snippet at the end of the <script> ? I'm having problems because Folium generates variables after adding my JS snippet at the top and my map is not being loaded properly. I'll try to explain better. Since you can't add on-click events to a polygon from Folium, I'm passing a code that has both the on-click function and the polygon.on(click, 'myClickFunction'). The thing is that Folium is putting this snippet at the very beginning of the <script> and generating the variable after it which is crashing JS. Any idea how I can solve this ?

**Comment by Conengmo** [comment]
Folium renders every object in its tree in order. So things that got added first should appear first in the script. Have you tried adding your JS to the Map object last?

**Comment by aryberberian** [comment]
Thanks for the reply. I'm adding the JS to the map object in the last part of my code and it still shows up as the first thing in the <script>. Any idea why ?

**Comment by Conengmo** [comment]
I suppose it's because in the snippet I posted a year ago the element is added to the map's parent object (which is a Figure object). That's not commonly done. Instead you can try adding it to the `Map` object. This is where the other normal objects are as well. But you'll need to add script tags to the element's template:

```
m = folium.Map()
code = '{% macro script(this,kwargs) %}some javascript code{% endmacro %}'
m.add_child(folium.Element(code))
m
```

We use three custom Jinja2 template tags to sort out where the code should be put: either in the head, html body or script.

**Comment by aryberberian** [comment]
I'm having troubles because when I use m.add_child(folium.Element(code)), nothing is being added to the object. Can you perhaps have a quick look at my code and help me ? 

    fg_gov = folium.FeatureGroup('fg')

    for index, row in df.iterrows():
    
      my_poly = folium.Polygon(row[1], 
                                    fill_color = 'green',
                                    tooltip = folium.Tooltip(text = row[0], style = 'font-size:200%')
                                    )
    
      poly_name = my_poly.get_name()
    
      code_poly = '{% macro add_click() -%} <script type = "text/javascript"> ' + poly_name + ".on('click', onPolyClick);</script> {%- endmacro %}"
    
    
    
      fg_gov.add_child(my_poly)   
    
    
    
      m.add_child(folium.Element(code_poly))
    
    
    m.add_child(fg)

**Comment by Conengmo** [comment]
You have to use these exact Jinja2 tags: `{% macro script(this,kwargs) %}`

**Comment by aryberberian** [comment]
Is there a chance I can't get this working because I'm using Spyder ? I've tried every possible combination and the only way for me to add an element is to use get_root().script which is adding it at the top.

**Comment by aryberberian** [comment]
So I've being playing with Jinja2 (new to me) and the "element.py" file for the past hours and this is what I can say: 
1) When I debug, the folium.Element is created but not added to the map.
2) Below are few tests with the output of each. These elements are being added after creating a map and adding polygons to it, so logically, they should be added after I add the polygons to the map but it's not the case. 

```
code = """{% if True %}var ary;{% endif %}"""

m.add_child(folium.Element(code)) #not working


code2 = """{% if True %}var ary2;{% endif %}"""

m.get_root().script.add_child(folium.Element(code2)) #working but it's added at beginning of <script>


code3 = """var ary3;"""

m.add_child(folium.Element(code3)) #not working


code4 = """{% macro script(this, kwargs) %}

            function onPolyClick4(event){
                    alert("Click");
                } 
            {% endmacro %}"""

m.get_root().script.add_child(folium.Element(code4)) #not working



code5= """

            function onPolyClick5(event){
                    alert("Click");
                } 
            """

m.get_root().script.add_child(folium.Element(code5)) #working but added beginning


code6 = """

            function onPolyClick6(event){
                    alert("Click");
                } 
            """

m.add_child(folium.Element(code6)) #not working


code7 = """{% macro script(this, kwargs) %}

            function onPolyClick7(event){
                    alert("Click");
                } 
            {% endmacro %}"""

m.add_child(folium.Element(code7)) #not working



Hope someone can help me see clearer !

**Comment by valkczr** [comment]
@Conengmo  I am using a Folium map (in Django) to draw a polygon on the map, it works just fine with the export button and also I can see the coordinates displayed on the screen, after clicking the polygon. But what I really want is to include the javascript code in the python using jinja to check for the draw event and pass those custom coordinates  internally without actually clicking the export button which then further converts it to the geoJson format. Any pointers would be appreciated. Thanks.
