### ISSUE TITLE
Dynamic Symbology in the Layer Selector?

### ISSUE THREAD

**Issue by Allenite** [python-visualization/folium#856]
Hi Folium team,

This is a great package.  I am amazed at how elegant it is, even with medium-sized data sets (e.g., I have a 120MB html file that pans and zooms quickly).

I wanted to ask if you plan to add support for dynamic symbology (or if it's already there and I somehow missed it) or for a folium server?  Let's take a US river polyline file, for example.  I'd like to be able to select in the layer view to not just turn it on or off, but also to symbolize it based on the depth of the riverbed, or, alternatively, the temperature of the water.  Just an example.  I wanted to ask if this type of functionality is possible?  It would open up a world of possibilities, even more than what is currently possible.

I am currently using bokeh for this type of functionality.  It is not as elegant and admittedly not designed for web mapping, but it does offer this type of streaming and changes to symbology.

Finally, I read the contributing guidelines.  I am happy to help in any way that I can.  I am relatively new to python, but I am going through dozens of real-life data science and data viz case studies every week.

**Comment by Conengmo** [comment]
Nice to hear that you like folium! Your contribution is certainly welcome. folium is built and maintained by volunteers such as yourself.

I'm not sure what you mean by 'symbology'. Do you mean different colors? You can already do that for example by creating color values with a `LinearColorMap` and then adding a `PolyLine` for each line and color. But I guess you mean something else, so please elaborate.

You can help out by:
- commenting on issues and PR's
- reviewing ideas and PR's
- writing documentation or creating example notebooks

Just pick an issue or PR that you can understand and share your solution or opinion!

**Comment by Allenite** [comment]
I was looking to add multiple types of symbology on the same data set (e.g., based on different columns or thresholds for column values).  This is actually already built-in because Folium does allow you to add multiple feature groups attached to the same data source.  So you can add the different symbology layers, and a user can turn them on and off in the layer selector.  Problem solved, I think.  

Thanks for the suggestion on documentation and example notebooks.  I'll try to work on those.
