### ISSUE TITLE
Dynamically update marker / heatmap data

### ISSUE THREAD

**Issue by anderl80** [python-visualization/folium#857]
Can I update the marker /heatmap locations dynamically without loading the whole new figure?

**Comment by Conengmo** [comment]
This is not possible with folium. folium generates the html and mostly javascript, from there it's outside of Python and in your browser. If you want to do dynamic locations you would need to look into [Leaflet](https://leafletjs.com/), the javascript library that actually makes the maps. 

Also see #848
