### ISSUE TITLE
Feature request: Expose "tms" argument for TileLayer

### ISSUE THREAD

**Issue by mjgleason** [python-visualization/folium#858]
The leaflet TileLayer tms option (http://leafletjs.com/reference-1.3.0.html#tilelayer-tms) is not currently exposed in the folium.TileLayer object. This makes it so that certain sources for tiles cannot be displayed in a folium Map (e.g., those created by gdal2tiles.py).

I think this would be a fairly straightforward fix by adding a tms argument to the TileLayer __init__ and then adding it to the _options_ variable. e.g.:

```python
    def __init__(self, tiles='OpenStreetMap', min_zoom=0, max_zoom=18,
                 max_native_zoom=None, attr=None, API_key=None,
                 detect_retina=False, name=None, overlay=False,
                 control=True, show=True, no_wrap=False, subdomains='abc', tms=False):
        self.tile_name = (name if name is not None else
                          ''.join(tiles.lower().strip().split()))
        super(TileLayer, self).__init__(name=self.tile_name, overlay=overlay,
                                        control=control, show=show)
        self._name = 'TileLayer'
        self._env = ENV

        options = {'minZoom': min_zoom,
                   'maxZoom': max_zoom,
                   'maxNativeZoom': max_native_zoom or max_zoom,
                   'noWrap': no_wrap,
                   'attribution': attr,
                   'subdomains': subdomains,
                   'detectRetina': detect_retina,
                   'tms': tms}
```

**Comment by Conengmo** [comment]
Seems very straight forward. I don't know how common this use case is, but if you're using it than that should be enough :)

Do you want to create a PR with this? Please include a docstring, a test, and a small example in a notebook, I guess TilesExample.ipynb would be most appropriate. I'm on vacation for a week so if nobody else reviews it before then I'll be able to do it next week.

**Comment by mpickering** [comment]
I ran into this issue today, precisely after using gdal2tiles. The workaround was to directly edit the generated javascript.
