### ISSUE TITLE
Some notebooks are failing with current master

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#860]
- [ ] ImageOverlay
- [ ] VideoOverlayLayer
- [X] Geopandas

**Comment by Conengmo** [comment]
It seems this is no longer the case, all tests are succeeding on the current master.

**Comment by ocefpaf** [comment]
The `geopandas` issue happens only with Google Chromium/Chrome and Jupyter, everything is fine with Firefox and Jupyter or if I load the html on Chromium/Chrome  :confused:, either way I'm marking this one as solved :smile:

**Comment by ocefpaf** [comment]
As it turns out all the issues are browser related. The notebooks work on firefox but no Chromium.

![screenshot from 2018-08-10 13-25-53](https://user-images.githubusercontent.com/950575/43969724-6cdf059a-9ca1-11e8-9afd-6036bfcac628.png)
![screenshot from 2018-08-10 13-28-43](https://user-images.githubusercontent.com/950575/43969726-6d705176-9ca1-11e8-8df0-e3bc7b2e0e11.png)


Closing this as it is not actionable by us. I'm cutting a new release based on master and, hopefully, we can keep on releasing :wink:
