### ISSUE TITLE
conda install instructions

### ISSUE THREAD

**Issue by zapcity** [python-visualization/folium#861]
The conda install instructions listed on https://github.com/python-visualization/folium advise to use:

> $ conda install folium

However folium doesn't seem to reside on the default channel. Could the instructions be changed to read:

> $ conda install -c conda-forge folium

**Comment by ocefpaf** [comment]
Ouch! As a `folium` maintainer and core founder of `conda-forge` that is very embarrassing :flushed: 

Fixing it immediately! Thanks!!
