### ISSUE TITLE
Existing map query database to get the new points 

### ISSUE THREAD

**Issue by didopop3** [python-visualization/folium#865]
I am a newbie to JS but I have been playing with the folium api. 

As I understand so far,  if I want to add new data points to the map, I need to regenerate a new html map file.

Is it possible for the existing map to query the database  to get the points before rendering?

Thanks, Kaibo

**Comment by Conengmo** [comment]
Hi Kaibo, this is not possible with folium. It is not really meant as a webapp framework. You'd have to write some javascript yourself to collect data from your database and update the locations of e.g. markers. Maybe at that point it is easier to skip folium altogether and directly use the Leaflet API, but that's an opinion.

There are Leaflet plugins for using ajax, but those are currently not available in folium. If you find one of those useful, you could add it to folium. Contributions are always welcome.

**Comment by didopop3** [comment]
Thank you for letting me know.  If I find one, I will let you know. :)
