### ISSUE TITLE
Daily data /  TimeSlider

### ISSUE THREAD

**Issue by enavarroAI** [python-visualization/folium#870]
Hello!
This might not be the place to ask for this, but I am kind of lost with this.
I have daily data, and I wish to generate a Map with different markers (a marker per each daily event)., with some kind of control mechanism that lets me adjust the date (like a slider).
However, I do not find documentation regarding this... I've seen the plugin TimeStampedGeoJson but I am unsure this is what I am looking for.

I also see that there are some plugins like TimeSliderChoropleth that I cannot use, how can I install the latest version? (I have 0.5.0 through conda). I am looking for something like that in the notebook example, but I don't need to use Choropleth.

Thanks!

**Comment by Conengmo** [comment]
I'll close the issue, since this is not really in scope for folium. If somebody wants to make this, great! Probably best if you host it yourself and ask us to link to your package. We might also consider adopting it in the folium repo. Please share your findings with others here or in a new issue.
