### ISSUE TITLE
two differents MarkerCluster

### ISSUE THREAD

**Issue by HADDADENICAR** [python-visualization/folium#873]
i need to set two different  MarkerCluster, completely independents .
how to do that ?

**Comment by Conengmo** [comment]
I'm not sure if I understand your question. You want two MarkerClusters that are independent. You can already do this by adding them to separate FeatureGroups:

```
fg1 = folium.FeatureGroup().add_to(m)
fg2 = folium.FeatureGroup().add_to(m)
folium.plugins.MarkerCluster(data[:50], name='MC').add_to(fg1)
folium.plugins.MarkerCluster(data[50:], name='MC2').add_to(fg2)
```

**Comment by Conengmo** [comment]
Closing this issue, if you have additional information you are of course welcome to add it and reopen if needed
