### ISSUE TITLE
Non deterministic zoom level when exporting to Jupyter slides

### ISSUE THREAD

**Issue by Juanlu001** [python-visualization/folium#874]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

http://nbviewer.jupyter.org/format/slides/gist/Juanlu001/7feeffbada57114423d68fe0bf491352#/0/1

#### Problem description

[this should explain **why** the current behavior is a problem and what is the expected output.]

When opening the link above, sometimes I get a zoomed map and sometimes I get a world map. It depends on `F5` versus `Ctrl+F5` and has a random result. Tested on Linux Mint 18.3 with both Firefox and Chromium.

#### Expected Output

Always a zoomed map.

#### Output of ``folium.__version__``

```
$ python -c "import folium as f;print(f.__version__)"
0.5.0
```

**Comment by Juanlu001** [comment]
I attach a screencast of the observed behavior:

![ezgif com-optimize](https://user-images.githubusercontent.com/316517/40779358-fbc5bbf0-64d4-11e8-8771-356efc6744a4.gif)

**Comment by ocefpaf** [comment]
I believe that `ipyleaft` may be a better fit for this case. We cannot keep up with the constant changes in how jupyter/jupyterlab deals with HTML/JS display :-(

**Comment by Juanlu001** [comment]
Thanks for your quick answer @ocefpaf. It's a pity because `ipyleaflet` being a widget instead of an HTML content makes it trickier to share in some use cases, but we understand the issue and in fact we have been doing experiments with both.

**Comment by ocefpaf** [comment]
> being a widget instead of an HTML content makes it trickier to share in some use cases

I know, that is the only reason why we are still keeping `folium` afloat.

> but we understand the issue and in fact we have been doing experiments with both.

The changes in how they handle HTML/JS made me loose my interest in this sort of thing. For example, to get `folium` to work with JupyterLab I have to actually write JS but the whole reason behind `folium` is to not write JS :laughing:

**Comment by ocefpaf** [comment]
@Juanlu001 I looked into this and I could not find the culprit. Something with revealjs does not play well with how we are loading all the `folium` JS deps. Closing this as "unsolvable" but I'll keep looking into a better way ti isolate things.

PS: note that the `m.fit_bounds(m.get_bounds())` may help you there.
