### ISSUE TITLE
The name of MarkerCluster algorithme 

### ISSUE THREAD

**Issue by HADDADENICAR** [python-visualization/folium#876]
I'm doing researches for my final year project .
I use folium with markerCluster for clustering inside the map, I need to know if it's possible the name of the algorithme you used to create that markerCluster, thanks

**Comment by Conengmo** [comment]
We use the Leaflet.markercluster Javascript plugin, so there are actually no algorithms implemented in folium for this. I suggest you check out their code to see how it works:
https://github.com/Leaflet/Leaflet.markercluster
