### ISSUE TITLE
folium with pyspark-folium type is not serializable

### ISSUE THREAD

**Issue by HADDADENICAR** [python-visualization/folium#878]
I m trying to use folium with pyspark , when i run the foreach method of Spark dataframe Rdd  i got this error : 

    PicklingError: Could not serialize object: TypeError: can't pickle weakref objects

and this is my code : 
  
     import findspark
     findspark.init()
     from pyspark import SparkContext, SparkConf, SparkSession

      #readmultiple csv with pyspark
      spark2 = SparkSession \
      .builder \
      .appName("Python Spark SQL basic example") \
      .getOrCreate()

      df = spark2.read.csv("Desktop/train  /train.csv",header=True).select("pickup_datetime","pickup_longitude","pickup_latitude","dropoff_datetime","dropoff_longitude","dropoff_latitude")

      df.rdd.foreach(lambda row : folium.CircleMarker(location=(float(row.pickup_latitude),
                                  float(row.pickup_longitude)),
                        radius=20,
                        color="#0A8A9F",fill=True).add_to(folium_map_pickups))

**Comment by Conengmo** [comment]
Similar problem as #796. Indeed you cannot pickle folium objects, and we're not going to fix this in folium. Unless someone has an idea how to reasonably do this. 

I advice you to collect your data from pyspark and create a folium map with markers outside of pyspark. You cannot create a map with millions of markers anyway, so you won't need parallel processing to add markers.
