### ISSUE TITLE
Heatmap javascript resources blocked by adblockers

### ISSUE THREAD

**Issue by ugoproto** [python-visualization/folium#881]
#### Problem description

Compared with Heatmap.ipynb, HeatMapWithTime.ipynb does not show any result.

#### Expected Output

We run the code, the code is ok, but heatmap shows up?

**Comment by Conengmo** [comment]
I need some more info to help troubleshoot your problem. Which version of folium and branca are you using?

```
import folium
import branca
print(folium.__version__)
print(branca.__version__)
```

You'll need branca version 0.3. Can you try installing folium from the git master branch?

**Comment by k0pernicus** [comment]
I confirm.

This is my local configuration:
```
>>> print(folium.__version__)
0.5.0
>>> print(branca.__version__)
0.3.0
```

**Comment by ugoproto** [comment]
With
```python
import folium
import branca
print(folium.__version__); print(branca.__version__)
```
I get
```python
0+unknown
0.3.0
```
In the terminal, with
```bash
conda list folium
```
I get
```bash
# packages in environment at /home/ugo/anaconda3:
#
# Name                    Version                   Build  Channel
folium                    0.5.0                      py_0    conda-forge
```

All other examples (Notebooks) work. My own Notebooks work.
Except HeatMapWithTime.ipynb
I use Ubuntu 16.04LTS, Anaconda3.

**Comment by ugoproto** [comment]
I use Python 3.5.5. In the Interpretor, I get what k0pernicus above get.

**Comment by Conengmo** [comment]
This may be the same as #852. Can you try disabling your adblocker?

**Comment by k0pernicus** [comment]
Thanks @Conengmo 
Disabling the adblocker works for me (using Firefox) :)

**Comment by Conengmo** [comment]
Good to hear. The `heatmap.js` library we use is unfairly blocked because of its name. I'm not sure how we can solve this. Maybe include the library file in folium? Are we allowed to do that?

**Comment by Conengmo** [comment]
Seems that we are allowed to host the heatmap.js library, since it is under an MIT license.

**Comment by Conengmo** [comment]
I merged the fix. @k0pernicus can you update folium from the git master branch and check if it works for you with your adblocker enabled as well?

**Comment by k0pernicus** [comment]
@Conengmo I will check this tonight / tomorrow morning 👍

**Comment by k0pernicus** [comment]
@Conengmo I can't confirm.
I updated the code from the git master branch, and UBlock still blocks the heatmap :/

**Comment by Conengmo** [comment]
Can you check in the logger of your adblocker which resources are still disabled?

**Comment by k0pernicus** [comment]
@Conengmo 
Still some calls to `heatmap.min.js` 🤔 

<img width="1059" alt="capture d ecran 2018-06-20 a 13 04 38" src="https://user-images.githubusercontent.com/3605451/41654708-9ea01f36-748a-11e8-8872-06f13b017f7d.png">

**Comment by Conengmo** [comment]
Can you double check you got the right folium version and are making a new html file? The link you're showing is no longer in the code.

**Comment by k0pernicus** [comment]
Soory @Conengmo, I forgot to reload my Jupyter instance after the update -_-

I confirm, it works well :)

Thanks a lot for your work/help 👍

**Comment by Conengmo** [comment]
Great, I'll close the issue again then.
