### ISSUE TITLE
PermissionError  - _to_png().

### ISSUE THREAD

**Issue by mihalw28** [python-visualization/folium#882]
#### Problem description
I try to follow that python cartography tutorial: https://github.com/vincentropy/python_cartography_tutorial and when executing code below (3rd part) I have permission error (below). Author of this tutorial said, that could be caused by folium and _to_png() function. 
Could you point me where can I find solution for this error?

```python
def go_arrivals_frame(i, hour_of_day, save_path):
    
    #create the map object
    data = get_trip_counts_by_minute(hour_of_day, dfs)
    my_frame = ff.plot_station_counts(data, zoom_start=14)
    
    #generate the png file as a byte array
    png = my_frame._to_png()

    
    # now add a caption to the image to indicate the time-of-day
    hour = int(hour_of_day)
    minutes = int((hour_of_day % 1) * 60)
    
    #create a PIL image object
    image = Image.open(io.BytesIO(png))
    draw = ImageDraw.ImageDraw(image)
    
    #load a font
    #font = ImageFont.truetype("Roboto-Light.ttf", 30)
    
    # draw time of day text
    draw.text((20,image.height - 50), 
              "time: {:0>2}:{:0>2}h".format(hour, minutes),
              fill=(255, 255, 255), 
              font=font)
    
    # draw title
    draw.text((image.width - 400,20), 
              "Net Arrivals vs Time of Day",
              fill=(255, 255, 255), 
              font=font)
    
    # write to a png file
   
    filename = os.path.join(save_path, "frame_{:0>5}.png".format(i))
    image.save(filename, "PNG")
    return image

go_arrivals_frame(1, 8.5, "frames")
```
```python
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-7-3b5d53f0c3fb> in <module>()
----> 1 go_arrivals_frame(1, 8.5, "frames")

<ipython-input-6-98bf3b936679> in go_arrivals_frame(i, hour_of_day, save_path)
     10 
     11     #generate the png file as a byte array
---> 12     png = my_frame._to_png()
     13 
     14 

~\Anaconda3\lib\site-packages\folium\map.py in _to_png(self)
    259             with tempfile.NamedTemporaryFile(suffix='.html') as f:
    260                 fname = f.name
--> 261                 self.save(fname, close_file=False)
    262                 driver = selenium.webdriver.PhantomJS(
    263                     service_log_path=os.path.devnull

~\Anaconda3\lib\site-packages\branca\element.py in save(self, outfile, close_file, **kwargs)
    150         """
    151         if isinstance(outfile, text_type) or isinstance(outfile, binary_type):
--> 152             fid = open(outfile, 'wb')
    153         else:
    154             fid = outfile

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\micha\\AppData\\Local\\Temp\\tmpcpcs71zp.html'

```
I`m not alone with this error. Another user had the same issue: https://github.com/vincentropy/python_cartography_tutorial/issues/1

**Comment by Conengmo** [comment]
I have the same issue on Windows 10. It has to do with the use of a temporary file that is being opened three times, this does not work. In the `Map._to_png()` method:

- `self.save(fname)` means the temporary files will be attempted to be opened again, inside the `with tempfile` statement.
- then `driver.get('file://{}'.format(fname))` also attempts to open the file.

From [the `tempfile` module documentation](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile):

> Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later).

A solution would be to reuse the temporary file handle for both. Problem is that selenium does not accept file handles AFAIK. 

Can we skip using a file altogether by providing selenium with a html string? I tried this but did not get it to work quickly:
https://stackoverflow.com/questions/22538457/put-a-string-with-html-javascript-into-selenium-webdriver

**Comment by Conengmo** [comment]
Hi @mihalw28, I put together a quick fix, can you pull my branch and see if this solves your issue? 
https://github.com/Conengmo/folium/tree/to-png-without-temp-file

**Comment by mihalw28** [comment]
Great! @Conengmo, it works. Thank you.

**Comment by mihalw28** [comment]
I hurried up. What a mess! PhantomJS webdriver is depreceted so I suppose, that your solution will be outdated soon. 

>C:\Users\micha\Anaconda3\lib\site-packages\selenium\webdriver\phantomjs\webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
  warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '<

Please, take into consideration that I am a novice and I could have missed something significant.

**Comment by ocefpaf** [comment]
Indeed. We need to use chrome or firefox headless.

I've been meaning to take a look at https://github.com/altair-viz/altair/pull/554/files for inspiration.

@Conengmo do you want to give it a go? (If not that is in my To Do list for next month when I get back into office.)

**Comment by Conengmo** [comment]
You're right, we should move away from Phantomjs. I'll open a new issue for it (seems there isn't one yet). I'll merge the PR with the fix for the permission error and close this issue.
