### ISSUE TITLE
Hide layers in order to avoid performance issues

### ISSUE THREAD

**Issue by k0pernicus** [python-visualization/folium#888]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
m = folium.Map(location=[48.9, 2.3], tiles="stamentoner", zoom_start=10)

for hour in st_dbscan_data:
    fg = folium.FeatureGroup(name=hour, overlay=True)
    current_clusters = st_dbscan_data[hour]['clusters']
    for index, cluster in enumerate(current_clusters):
        folium.plugins.MarkerCluster(
            locations=cluster,
            name='cluster %d' % index
        ).add_to(fg)
    fg.add_to(m)
    
folium.LayerControl().add_to(m)
    
m
```
#### Problem description

I am using `Jupyter` and `folium` to render and visualize clusters of points in a map.

Currently, I want to visualize my points, grouped in clusters, per hour (between 6AM and 10PM).
Each hour contains ~ 4 clusters (`cluster` in code), and the number of points per hour is ~ 500 points (so, 125 points per cluster).

I wanted to create a `MarkerCluster` per cluster of points, and a `FeatureGroup` per hour, in order to visualize the clusters hour after hour...

The problem here is that the rendering is very slow, and Jupyter does not display the map after the rendering (I checked the source code in my browser console, and the body of the cell is null - no error in the Jupyter/browser console either).

I think this behaviour is the result of performance issues, so I wanted to know if an option exists to disable the rendering of each `FeatureGroup` when building the map ?
In this case, I would like to enable the rendering "on the fly" when checking the layer in the map, and avoid the performance issues.
I checked the documentation for both `FeatureGroup` and `MarkerCluster`, but I did not found anything useful...

Thanks a lot :)

**Comment by Conengmo** [comment]
I have two tips you could try:

Stuff breaks down earlier in Jupyter. Try to save your map as an html file and open that in your browser. It should allow for more markers.

`m.save('map.html')`

Have you tried the `show` parameter? By setting `show=False` an overlay is not shown when opening your map. This makes moving the map less sluggish. But it doesn't seem to impact loading time. I tried opening a map with 100000 markers and it failed, and with `show=False` it also failed.
N.B. `overlay` is true by default.

`folium.FeatureGroup(name=hour, show=False)`

**Comment by denson** [comment]
@Conengmo, which version are you running? I have 0.5.0 and I get an error whenever I attempt the "show" keyword:
folium.FeatureGroup(name='test', show=False)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-e155c073eec9> in <module>()
----> 1 folium.FeatureGroup(name='test', show=False)

TypeError: __init__() got an unexpected keyword argument 'show'

**Comment by Conengmo** [comment]
That's right, it's not in 0.5 and 0.6 hasn't been released yet. You can install from the git master Branch to try it out.

**Comment by Conengmo** [comment]
I'm closing this old issue since it doesn't seem actionable. Feel free to add new, relevant information, we can open if needed.
