### ISSUE TITLE
Support for categorical/discrete colour maps in map.geo_json()

### ISSUE THREAD

**Issue by psychemedia** [python-visualization/folium#89]
The colour mapping when generating choropleth style maps is based around d3.js colour brewer sequential scales.

When generating thematic maps based on a categorical variable (such as election prediction or outcomes by party), it would be convenient to be able to pass in a colour map as a dict that maps `{'colvar1':color1, 'colvar2':color2, ..., 'colvarN':colorN}`

One option would be to support colorbrewer qualitative scales, though it would also be useful to be able to define color maps for cases where conventional colorings are used (as for political parties, for example).

I can't offhand see how to do that currently?

I note that is a *quantize_fill* parameter in `json_style` within the `geo_json` function. Is that provided as a stub for such a feature?

**Comment by ocefpaf** [comment]
@BibMartin I did not try your hint for using mpl stuff as arg.  Would that fix this issue?

**Comment by BibMartin** [comment]
I guess it's possible. I have to build an example/test.

**Comment by BibMartin** [comment]
Sorry, it's not possible for the moment. The 'hint' trick is for `ImageOverlay` not for `GeoJson`. We definitely have to do something for simplifying choropleth stuff.

**Comment by ocefpaf** [comment]
> We definitely have to do something for simplifying choropleth stuff.

:+1:

**Comment by BibMartin** [comment]
@ocefpaf 
Can we close this based on #266 merge, or do you want to wait for an example in the docs ?

**Comment by ocefpaf** [comment]
> Can we close this based on #266 merge, or do you want to wait for an example in the docs ?

Let's write an example first.  @psychemedia if you beat us to it please share here :wink:

**Comment by BibMartin** [comment]
To keep track of things, we need to review #292 before closing this issue.
@ocefpaf can you assign yourself to this please ? (I cannot review myself)

**Comment by psychemedia** [comment]
@ocefpaf 
Exciting:-) I will try to have a look at this - but it probably won't be before the end of this week.

**Comment by ocefpaf** [comment]
I think #300 covered all that.
