### ISSUE TITLE
Update Folium Polygon color without having to re-save the map and re-load the page?

### ISSUE THREAD

**Issue by EdwardDeaver** [python-visualization/folium#890]
I'm new to folium, I'm trying to see if my JS Leaflet code would work in folium. 

In my JS I have a polygon that when a message comes in updates it's color:
Ex. Polygon   (JS)			

polygon = L.polygon(latlngs, {color: 'red'}).addTo(mymap);

Then when a message comes through I just:

polygon.setStyle({color: 'purple'});

And it just updates in real time. 

Is this possible to do with folium, it seems like folium is meant for static maps not dynamic ones?

**Comment by Conengmo** [comment]
You're right, folium is not mean for dynamic maps. You create all the objects and add them to a `Map` object, and when you render that a single html page is created. It's not meant as a dynamic web app kind of thing. You could use folium in something dynamic, but you have to inject some javascript that does that.

Does that help? I don't know what you're use case is exactly of course.

**Comment by EdwardDeaver** [comment]
Hi Conengmo,

Thank you for getting back to me so quickly. 

It helped tremendously. 

Thank you again.

-Edward

**Comment by Conengmo** [comment]
Good to hear. I'll close the issue then, but feel free to add more, we'll reopen if needed.
