### ISSUE TITLE
Use Firefox or Chrome for Selenium instead of Phantomjs

### ISSUE THREAD

**Issue by Conengmo** [python-visualization/folium#891]
Phantomjs is being deprecated, though it works for the moment, so not a bug yet.

```
C:\Users\micha\Anaconda3\lib\site-packages\selenium\webdriver\phantomjs\webdriver.py:49: 
UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '<
```

We need to use chrome or firefox headless. Take a look at https://github.com/altair-viz/altair/pull/554/files for inspiration.

**Comment by ocefpaf** [comment]
Addressed in https://github.com/python-visualization/folium/pull/1015
