### ISSUE TITLE
Radius Bug

### ISSUE THREAD

**Issue by kevin-reilly** [python-visualization/folium#892]
I think there is a bug in how the radius option is working with Folium.  I have the following code:

```python
import folium

lat = 40.7787006
lon = -73.9654842

map = folium.Map(location=[lat, lon], zoom_start=20)
folium.Marker([lat, lon]).add_to(map)
folium.CircleMarker([lat, lon],
                    radius=40
                   ).add_to(map)

map
```
I have seen a number of places (including [here](https://github.com/python-visualization/folium/issues/415)) where it states that `radius=40` should show a 40 meter radius around the marker.

The result of this code is:

<img width="791" alt="screen shot 2018-06-20 at 2 04 42 pm" src="https://user-images.githubusercontent.com/2932575/41681717-83c3eca6-74a3-11e8-8a88-6660999cea69.png">

But if I change the zoom to `zoom_start=5` I get a wider view but a circle of the same size. This is not a 40 meter radius around the point.

<img width="790" alt="screen shot 2018-06-20 at 2 05 14 pm" src="https://user-images.githubusercontent.com/2932575/41681948-3e4c3f6a-74a4-11e8-8d8b-c52cd2afe629.png">

I would expect the radius when the `zoom_start=5` to be almost unperceivable.

Using Folium 0.5.0

**Comment by ocefpaf** [comment]
From our docs:

```
    radius: int
        The radius of the circle in pixels.
        For setting the radius in meter, use Circle.
```

You want `Circle`, not `CircleMarker`.

**Comment by kevin-reilly** [comment]
Excellent.  You are correct.  That works.  Thank you.
