### ISSUE TITLE
supercluster in folium map

### ISSUE THREAD

**Issue by HADDADENICAR** [python-visualization/folium#898]
Folium is the python implementation of leaflet.

It is possible in folium as well in leaflet to use markercluster when the number of gps grows.
But markercluster have a limit of 50k gps , recently i found that the owner of leaflet have created another clustring algorithme for huge spatial data called [supercluster](https://github.com/mapbox/supercluster) that can handle 6 millions of gps.

my question is:
Is it possible to use the leaflet supercluster on folium maps ?
if yes how to use it on folium ?

**Comment by ocefpaf** [comment]
> Folium is the python implementation of leaflet.

Nope. It is a wrapper. Leaflet is used under the hood.

> Is it possible to use the leaflet supercluster on folium maps ?

One would need to write a plugin for that. Take a look at our plugin folder and see if that is something you would like to tackle.

**Comment by ocefpaf** [comment]
I did not say it existed in the plugin folder. I said to look there for inspiration on how to implement it. Also, if that is something you feel comfortable tackling...

Closing this as features requests are not really a priority. If you can send a PR or find someone to do so we'll gladly review it.
