### ISSUE TITLE
Folium Map Language

### ISSUE THREAD

**Issue by thisisharis** [python-visualization/folium#903]
I was just getting started with folium. I wrote following code in jupyter:

**import folium
map=folium.Map(location=[38,99.09],zoom_start=6)
map.save("Map1.html")**

when i opened the html file, it shows locations in chinese language or whatever language that is. How can i change it to english?

**Comment by ocefpaf** [comment]
That is not folium, it is from the Open Street Maps tile. You can change the tile to get a different image there. Please check the docs for the tile options.
