### ISSUE TITLE
GeoJSON popup not working when GeoJSON in FeatureGroup

### ISSUE THREAD

**Issue by mfredk** [python-visualization/folium#904]
Based on this example:
[Highlight_Function.ipynb](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Highlight_Function.ipynb)

#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
import os
import folium
import pandas as pd

print(folium.__version__)

df = pd.read_csv('highlight_flight_trajectories.csv')

m = folium.Map(
    location=[40, 10],
    zoom_start=4,
    control_scale=True,
    prefer_canvas=True
)


def style_function(feature):
    return {
        'fillColor': '#ffaf00',
        'color': 'blue',
        'weight': 1.5,
        'dashArray': '5, 5'
    }


def highlight_function(feature):
    return {
        'fillColor': '#ffaf00',
        'color': 'green',
        'weight': 3,
        'dashArray': '5, 5'
    }

# Add Layer
layer = folium.FeatureGroup(name='layer')

for index, row in df.iterrows():
    c = folium.GeoJson(
        row['geojson'],
        name=('{}{}'.format(row['dep'], row['dest'])),
        overlay=True,
        style_function=style_function,
        highlight_function=highlight_function
    )
    folium.Popup('{}\n{}'.format(row['dep'], row['dest'])).add_to(c)
    c.add_to(layer)

layer.add_to(m)
folium.LayerControl().add_to(m)
m.save('maptest.html')

```
#### Problem description

Popup of a GeoJSON is not working, if the GeoJSON is contained in a FeatureGroup.

#### Expected Output

When clicking on a GeoJSON the popup should be displayed

#### Output of ``folium.__version__``
0+unknown (pulled from GIT today and installed via setup.py)

**Comment by mfredk** [comment]
Hi, thanks for having a look and for your comment.
I'm sorry, I am more the end-user type of guy, so that I unfortunately have no suggestion, why it does not work as intended. My current work-around is to add all the GeoJSONs to the main map. But as there are quite a few GeoJSONs I would have preferred to group them in a layer for easy toggling with the layer-control.

**Comment by davidolmo** [comment]
I think this issue was solved recently by a new version, or at least it seems like I could add custom popups to a a Feature Group

My code:

`layer_geom = folium.FeatureGroup(name='layer',control=False)

for i in range(len(data_geojson_dict["features"])):
    temp_geojson = {"features":[data_geojson_dict["features"][i]],"type":"FeatureCollection"}
    temp_geojson_layer = folium.GeoJson(temp_geojson,
                   highlight_function=lambda x: {'weight':3, 'color':'black'},
                    control=False,
                    style_function=lambda feature: {
                   'color': 'black',
                   'weight': 1},
                    tooltip=folium.features.GeoJsonTooltip(fields=list_tooltip_vars,
                                        aliases=[x.capitalize()+":" for x in list_tooltip_vars], 
                                          labels=True, 
                                          sticky=False))
    folium.Popup(temp_geojson["features"][0]["properties"]["productor"]).add_to(temp_geojson_layer)
    temp_geojson_layer.add_to(layer_geom)

layer_geom.add_to(m)`

**Comment by Conengmo** [comment]
I can confirm this is no longer an issue, on the main branch at least.
