### ISSUE TITLE
Consider adding esri plugins

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#91]
@birdage what do you think?

http://esri.github.io/esri-leaflet/

Is this something you would like to tackle?

Here is an example of the possibilities:
http://gcoos.org/products/maps/gulf_gliders/

**Comment by ocefpaf** [comment]
Or maybe we can just do this,

http://nbviewer.ipython.org/gist/ocefpaf/2429320eae4265253c71

and avoid bloating folium with methods/plugins?

**Comment by birdage** [comment]
i would say lets just add items to the base layer list....simple and works

**Comment by ocefpaf** [comment]
OK.  I was +0.5 and you :-1:, so lets close this.

**Comment by birdage** [comment]
@ocefpaf we might want to option in the api to add a `base layer` rather than a straight wms layer, radial vs checkbox list on the layer controls, but thats a minor.....

**Comment by ocefpaf** [comment]
Makes sense.  Right now I think we support only 1 base layer, correct?

**Comment by birdage** [comment]
correct
