### ISSUE TITLE
GPS track color coded with speed

### ISSUE THREAD

**Issue by tjansson60** [python-visualization/folium#910]
#### Question
I am trying to find a way to to color code a GPS track with various data, such as speed, pulse etc using folium, but I have not found any solution in the documentation or the example. The is a online image of the effect I am trying to achieve.

Is this possible in folium currently? 

![](http://a2.mzstatic.com/us/r30/Purple62/v4/31/5d/b0/315db05a-5a26-56d8-2b3c-b82be0cdb7c9/screen696x696.jpeg)

**Comment by Conengmo** [comment]
Yes this is possible. You can use the `ColorLine` class for this:

https://python-visualization.github.io/folium/docs-master/modules.html#folium.features.ColorLine

We also have a Notebook with some example usage:

https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Features.ipynb#ColorLine

If you need more specific behavior you can copy the code from the `ColorLine` class and hack it yourself. It's basically a wrapper around two other classes: `LinearColorMap` and `PolyLine`.

We don't have a legend feature yet, if you would like to work on this you're most welcome. I'll refer to the original issue: #528.

**Comment by tjansson60** [comment]
I am embarrassed that I did not find this myself, but thanks a lot for taking the time to help me. :) The ColorLine was exactly what I was looking for.

**Comment by Conengmo** [comment]
Great! Good luck with it. I'll close the issue then.
