### ISSUE TITLE
Bug when trying to set threshold_value in Choropeth

### ISSUE THREAD

**Issue by loganrudd** [python-visualization/folium#911]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
import pandas as pd
!pip install Folium==0.5.0
import folium
!pip install xlrd

df_can = pd.read_excel('https://ibm.box.com/shared/static/lw190pt9zpy5bd1ptyg2aw15awomz9pu.xlsx',
                     sheet_name='Canada by Citizenship',
                     skiprows=range(20),
                     skipfooter=2)

df_can.rename(columns={'OdName':'Country', 'AreaName':'Continent','RegName':'Region'}, inplace=True)

df_can['Total'] = df_can.sum(axis=1)

# download countries geojson file
!wget --quiet https://ibm.box.com/shared/static/cto2qv7nx6yq19logfcissyy4euo8lho.json -O world_countries.json
    
world_geo = r'world_countries.json' # geojson file

# create a plain world map
world_map = folium.Map(location=[0, 0], zoom_start=2, tiles='Mapbox Bright')

# generate choropleth map using the total immigration of each country to Canada from 1980 to 2013
world_map.choropleth(
    geo_data=world_geo,
    data=df_can,
    columns=['Country', 'Total'],
    key_on='feature.properties.name',
    fill_color='YlOrRd', 
    fill_opacity=0.7, 
    line_opacity=0.2,
    legend_name='Immigration to Canada',
    threshold_scale=[0, 100000, 200000, 350000, 450000, 550000]
)

# display map
world_map

```
#### Problem description

I have a jupyter notebook with the above code. When I comment out the threshold_scale in the code above, it generates the map fine, but when I run the code above with threshold_value parameter as shown above I get this error
#### Output of ``folium.__version__``
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/anaconda3/lib/python3.6/site-packages/folium/map.py in _repr_html_(self, **kwargs)
    249             self._parent = None
    250         else:
--> 251             out = self._parent._repr_html_(**kwargs)
    252         return out
    253 

~/anaconda3/lib/python3.6/site-packages/branca/element.py in _repr_html_(self, **kwargs)
    317 
    318         """
--> 319         html = self.render(**kwargs)
    320         html = "data:text/html;charset=utf-8;base64," + base64.b64encode(html.encode('utf8')).decode('utf8')  # noqa
    321 

~/anaconda3/lib/python3.6/site-packages/branca/element.py in render(self, **kwargs)
    307         """Renders the HTML representation of the element."""
    308         for name, child in self._children.items():
--> 309             child.render(**kwargs)
    310         return self._template.render(this=self, kwargs=kwargs)
    311 

~/anaconda3/lib/python3.6/site-packages/folium/map.py in render(self, **kwargs)
    336             '</style>'), name='map_style')
    337 
--> 338         super(LegacyMap, self).render(**kwargs)
    339 
    340 

~/anaconda3/lib/python3.6/site-packages/branca/element.py in render(self, **kwargs)
    622 
    623         for name, element in self._children.items():
--> 624             element.render(**kwargs)

~/anaconda3/lib/python3.6/site-packages/branca/element.py in render(self, **kwargs)
    618         script = self._template.module.__dict__.get('script', None)
    619         if script is not None:
--> 620             figure.script.add_child(Element(script(self, kwargs)),
    621                                     name=self.get_name())
    622 

~/anaconda3/lib/python3.6/site-packages/jinja2/runtime.py in __call__(self, *args, **kwargs)
    573                             (self.name, len(self.arguments)))
    574 
--> 575         return self._invoke(arguments, autoescape)
    576 
    577     def _invoke(self, arguments, autoescape):

~/anaconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py in _invoke(self, arguments, autoescape)
    108     def _invoke(self, arguments, autoescape):
    109         if not self._environment.is_async:
--> 110             return original_invoke(self, arguments, autoescape)
    111         return async_invoke(self, arguments, autoescape)
    112     return update_wrapper(_invoke, original_invoke)

~/anaconda3/lib/python3.6/site-packages/jinja2/runtime.py in _invoke(self, arguments, autoescape)
    577     def _invoke(self, arguments, autoescape):
    578         """This method is being swapped out by the async implementation."""
--> 579         rv = self._func(*arguments)
    580         if autoescape:
    581             rv = Markup(rv)

<template> in macro(l_1_this, l_1_kwargs)

~/anaconda3/lib/python3.6/site-packages/jinja2/runtime.py in call(_Context__self, _Context__obj, *args, **kwargs)
    260                 args = (__self.environment,) + args
    261         try:
--> 262             return __obj(*args, **kwargs)
    263         except StopIteration:
    264             return __self.environment.undefined('value was undefined because '

~/anaconda3/lib/python3.6/site-packages/folium/features.py in style_data(self)
    563 
    564         for feature in self.data['features']:
--> 565             feature.setdefault('properties', {}).setdefault('style', {}).update(self.style_function(feature))  # noqa
    566             feature.setdefault('properties', {}).setdefault('highlight', {}).update(self.highlight_function(feature))  # noqa
    567         return json.dumps(self.data, sort_keys=True)

~/anaconda3/lib/python3.6/site-packages/folium/folium.py in style_function(x)
    303                 'color': line_color,
    304                 'fillOpacity': fill_opacity,
--> 305                 'fillColor': color_scale_fun(x)
    306             }
    307 

~/anaconda3/lib/python3.6/site-packages/folium/folium.py in color_scale_fun(x)
    290             def color_scale_fun(x):
    291                 return color_range[len(
--> 292                     [u for u in color_domain if
    293                      get_by_key(x, key_on) in color_data and
    294                      u <= color_data[get_by_key(x, key_on)]])]

IndexError: list index out of range

<folium.folium.Map at 0x7f84101e1a58>

**Comment by Conengmo** [comment]
I got an unrelated error when running your example, but fixed it myself by manually altering the Excel file. Something with Pandas not importing the right sheet. I just deleted the other two sheets.

I didn't get your error though. Can you tell us which version of folium and branca you are using?

```
print(folium.__version__)
print(branca.__version__)
```

If your using branca version 0.2, make sure you upgrade to 0.3.

**Comment by loganrudd** [comment]
Ah, actually I think branca is irrelevant. Even if you take that part of
the code out and just manually put in a list of 5 numbers I get the same
error. I'll update my question with a better example to try and replicate
the error

**Comment by Conengmo** [comment]
I reproduced your bug using folium version 0.5. With the most recent version from the git master branch the bug doesn't occur. I didn't look into what fixed it, the import thing is it has been fixed.

Can you install folium from the git master branch? That should solve your problem.

**Comment by loganrudd** [comment]
Ah got it! Thanks again Frank!!

**Comment by Conengmo** [comment]
Good to hear, I'll close the issue then.
