### ISSUE TITLE
Release v0.6.0

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/folium#915]
@Conengmo I'm tagging some issues and PRs with the `v0.6.0` label. So far only #860 is tagged. Please feel free to tag those that you believe deserve our attention for the next release. I'm planning on sprinting on `folium` for the next two weeks.

**Comment by Conengmo** [comment]
Sounds good! I just looked through the issues and PR's and there's nothing in particular I think has to make 0.6. Enough stuff that could be included, but nothing critical.

Some PR's that I'm still invested in is #883 (that's taking some time, but no hurry), #916 and #908. But I don't mind if they don't make it in 0.6. Would be nice if you can take a look at #908 though, whether we can deprecate Python 2.7.

**Comment by Conengmo** [comment]
Are there some big topics you want to work on in your sprint? Maybe geojsoncss? I can help discuss/review stuff. If it's ready for 0.6 that's great, but I don't think it's wise to rush things in a release.

**Comment by ocefpaf** [comment]
> Are there some big topics you want to work on in your sprint? Maybe geojsoncss?

Yes, I guess we (I mostly) should work on `geojsoncss`.

> I can help discuss/review stuff.

Please do!

> If it's ready for 0.6 that's great, but I don't think it's wise to rush things in a release.

Agreed. I don't want to rush things I mostly want a new release to break the inertia. (As you can see I got side tracked again and did not respond here for 11 days :flushed:)

**Comment by Conengmo** [comment]
> I don't want to rush things I mostly want a new release to break the inertia.

I guess 0.6 has been long overdue. Maybe we should just release it now and do 0.7 in a month or so when we have all the geojson stuff (css, tooltip, marker) ready and stable. I think all these changes to geojson will interfere or integrate with each other so if we rush half of it in a release now and change it afterwards that may confuse users. @jtbaker what do you think?

Where are you working on `geojsoncss` and is there documentation/discussion on it already somewhere? I'm new to this topic so please point out where you want to discuss this.

**Comment by ocefpaf** [comment]
> I guess 0.6 has been long overdue. Maybe we should just release it now and do 0.7 

:+1: I'll work on it.

> 0.7 in a month or so when we have all the geojson stuff (css, tooltip, marker) ready and stable

Sure.

**Comment by Allenite** [comment]
Excellent!  Just saw the release.  Any sense when will it be available in the pip and conda channels?

**Comment by ocefpaf** [comment]
Should be pip installable now and `conda` in a few minutes.

**Comment by Conengmo** [comment]
I updated the release notes to include the full changelog.

@ocefpaf I noticed the docs didn't get updated with a 0.6.0 version. How can that be fixed? Do we need a 0.6.0 branch also?

**Comment by ocefpaf** [comment]
> @ocefpaf I noticed the docs didn't get updated with a 0.6.0 version. How can that be fixed? Do we need a 0.6.0 branch also?

Let me look into that today...

**Comment by ocefpaf** [comment]
Yep. It is not creating it from the tag, it needs a branch :-(
Let me see if I can fix that...

**Comment by ocefpaf** [comment]
All fixed, see http://python-visualization.github.io/folium/docs-v0.6.0/

BTW I want to move the latest master build to http://python-visualization.github.io/folium/master and let http://python-visualization.github.io/folium reflect the latest release. Not sure how to do that yet but it makes sense IMO.
