### ISSUE TITLE
Validate `key_on` in choropleth

### ISSUE THREAD

**Issue by Conengmo** [python-visualization/folium#918]
There have been issues in the (recent) past where users couldn't figure out why their choropleth wasn't working. Such as #913, #917, #793. These issues where due to a mismatch between the geojson data and the numerical data. The easiest mistake is to have a wrong `key_on` value. In #917 the value in the geojson and the numerical data had a different type leading to a mismatch. 

This can be solved by not making a mismatch happen silently. There are things we can validate before or during rendering that can lead to a meaningful error message:
- whether the `key_on` argument matches the fields in the geojson.
- whether both fields in the `column` argument are present in the data.
-  whether the values in the geojson and the numerical data under the `key_on` and `column[0]` argument match.
- whether those matches lead to valid values using the `column[1]` argument.

If someone wants to pick this up, you're welcome to do so!

**Comment by evwhiz** [comment]
Created #1144. @ocefpaf - please review that PR. You were great today :- ) Many Thanks!

**Comment by Conengmo** [comment]
We haven't seen any questions on this topic recently, so I assume our improvements payed off.
