### ISSUE TITLE
Generated Choropleth Map html does not render with Chrome or Chromium, but renders with Firefox

### ISSUE THREAD

**Issue by pybokeh** [python-visualization/folium#92]
When executing the choropleth map examples from folium's main page, the resulting html file doesn't render the map in Chrome or Chromium (just blank white screen), but renders ok in Firefox.

PC: Xubuntu 14.10 32-bit
Python 3.4.2 virtual environment via conda version 3.9.1
Firefox: version 36.01
Chrome: Version 41.0.2272.76
Chromium: Version 41.0.2272.76

Here is the script that I ran:
    
    import folium
    import pandas as pd

    state_geo = '/home/path/us-states.json'
    state_unemployment = '/home/path/US_Unemployment_Oct2012.csv'

    state_data = pd.read_csv(state_unemployment)

    #Let Folium determine the scale
    map = folium.Map(location=[48, -102], zoom_start=3)
    map.geo_json(geo_path=state_geo, data=state_data,
             columns=['State', 'Unemployment'],
             key_on='feature.id',
             fill_color='YlGn', fill_opacity=0.7, line_opacity=0.2,
             legend_name='Unemployment Rate (%)')
    map.create_map(path='/home/path/us_states_notebook.html')

This stamen example from folium main page works ok with Chrome/Chromium:
    
    stamen = folium.Map(location=[45.5236, -122.6750], tiles='Stamen Toner',
                    zoom_start=13)
    stamen.create_map(path='/home/path/stamen_toner.html')

List of packages/libraries installed in my conda environment via "conda list" command:
binstar                   0.10.1                   py34_2  
clyent                    0.3.2                    py34_0  
dateutil                  2.1                      py34_2  
folium                    0.1.3                     <pip>
freetype                  2.4.10                        0  
ipython                   3.0.0                    py34_0  
ipython-notebook          3.0.0                    py34_1  
jinja2                    2.7.3                    py34_1  
jsonschema                2.4.0                    py34_0  
libpng                    1.5.13                        1  
libsodium                 0.4.5                         0  
markupsafe                0.23                     py34_0  
matplotlib                1.4.3                np19py34_0  
mistune                   0.5                      py34_0  
numpy                     1.9.2                    py34_0  
openssl                   1.0.1k                        0  
pandas                    0.15.2               np19py34_0  
patsy                     0.3.0                np19py34_0  
pip                       6.0.8                    py34_0  
ptyprocess                0.4                      py34_0  
pygments                  2.0.2                    py34_0  
pyparsing                 2.0.3                    py34_0  
pyqt                      4.10.4                   py34_0  
python                    3.4.2                         0  
python-dateutil           2.1                       <pip>
pytz                      2014.9                   py34_0  
pyyaml                    3.11                     py34_0  
pyzmq                     14.5.0                   py34_0  
qt                        4.8.5                         0  
readline                  6.2                           2  
requests                  2.5.3                    py34_0  
rpy2                      2.5.6                     <pip>
scipy                     0.15.1               np19py34_0  
seaborn                   0.5.1                np19py34_0  
setuptools                12.4                     py34_0  
sip                       4.15.5                   py34_0  
six                       1.9.0                    py34_0  
sqlite                    3.8.4.1                       0  
statsmodels               0.6.1                np19py34_0  
system                    5.8                           1  
terminado                 0.5                      py34_0  
tk                        8.5.15                        0  
tornado                   4.1                      py34_0  
xz                        5.0.5                         0  
yaml                      0.1.4                         0  
zeromq                    4.0.4                         0  
zlib                      1.2.8                         0

**Comment by ocefpaf** [comment]
Your example worked fine here with Chromium 40.0.2214.111.

Quick question: are you opening the file or serving it?   If opening it see #72.

**Comment by pybokeh** [comment]
OK, at the terminal, I executed: python -m http.server 8000 in the folder that contains my HTML file.

Then with all 3 browsers (Chrome, Chromium, Firefox), the map renders, but without the states shaded according to their population.  So basically, a US states map with no coloring.

But if I view the HTML offline using Firefox, the map is rendered with the 50 states colored or shaded.  This is very strange.

Here's the content of the html file.  The URLs in the <head> tag have the "http" prefix, so it doesn't appear to be same issue as in issue #72.

    <!DOCTYPE html>
    <head>
       <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
       <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7/leaflet.css" />
       <script src="http://cdn.leafletjs.com/leaflet-0.7/leaflet.js"></script>
       <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
       <script src="http://d3js.org/queue.v1.min.js"></script>

       
       
       
       

       <style>

          html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
          }

          .legend {
              padding: 0px 0px;
              font: 10px sans-serif;
              background: white;
              background: rgba(255,255,255,0.8);
              box-shadow: 0 0 15px rgba(0,0,0,0.2);
              border-radius: 5px;
          }

          .key path {
            display: none;
          }

       </style>
    </head>

    <body>

       <div id="map" style="width: 960px; height: 500px"></div>

       <script>

          queue()
              .defer(d3.json, 'data.json')
              .defer(d3.json, '/home/pybokeh/Downloads/us-states.json')
              .await(makeMap)

          function makeMap(error, data_1,gjson_1) {

              

              

              function matchKey(datapoint, key_variable){
                  if (typeof key_variable[0][datapoint] === 'undefined') {
                      return null;
                  }
                  else {
                      return parseFloat(key_variable[0][datapoint]);
                  };
              };

              
              var color = d3.scale.threshold()
                  .domain([3.0, 7.0, 8.0, 9.0, 9.0])
                  .range(['#FFFFCC', '#D9F0A3', '#ADDD8E', '#78C679', '#41AB5D', '#238443']);
              

              var map = L.map('map').setView([48, -102], 3);

              L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                  maxZoom: 18,
                  attribution: 'Map data (c) <a href="http://openstreetmap.org">OpenStreetMap</a> contributors'
              }).addTo(map);

              

              

              

              

              
              function style_1(feature) {
        return {
            fillColor: color(matchKey(feature.id, data_1)),
            weight: 1,
            opacity: 0.2,
            color: 'black',
            fillOpacity: 0.7
        };
    }
              

              
              gJson_layer_1 = L.geoJson(gjson_1, {style: style_1}).addTo(map)
              

              
                  var legend = L.control({position: 'topright'});

        legend.onAdd = function (map) {var div = L.DomUtil.create('div', 'legend'); return div};

        legend.addTo(map);

        var x = d3.scale.linear()
        .domain([0, 9])
        .range([0, 400]);

        var xAxis = d3.svg.axis()
            .scale(x)
            .orient("top")
            .tickSize(1)
            .tickValues([3.0, 7.0, 8.0, 9.0, 9.0]);

        var svg = d3.select(".legend.leaflet-control").append("svg")
            .attr("id", 'legend')
            .attr("width", 450)
            .attr("height", 40);

        var g = svg.append("g")
            .attr("class", "key")
            .attr("transform", "translate(25,16)");

        g.selectAll("rect")
            .data(color.range().map(function(d, i) {
              return {
                x0: i ? x(color.domain()[i - 1]) : x.range()[0],
                x1: i < color.domain().length ? x(color.domain()[i]) : x.range()[1],
                z: d
              };
            }))
          .enter().append("rect")
            .attr("height", 10)
            .attr("x", function(d) { return d.x0; })
            .attr("width", function(d) { return d.x1 - d.x0; })
            .style("fill", function(d) { return d.z; });

        g.call(xAxis).append("text")
            .attr("class", "caption")
            .attr("y", 21)
            .text('Unemployment Rate (%)');
              

          };

       </script>
    </body>

**Comment by ocefpaf** [comment]
Based on:

```html
          .defer(d3.json, 'data.json')
          .defer(d3.json, '/home/pybokeh/Downloads/us-states.json')
```

I am guessing you are loading `us-states.json` from your `~/Downloads` directory, but you are working from another directory, correct?

This is served HTML and you need relative links to find stuff.  I recommend placing everything in the same directory to avoid this.

**Comment by pybokeh** [comment]
Hmm, not sure what I did wrong.  I downloaded the map json and population data into the Downloads folder and ran the example script from my ipython notebook server which generated the html file into the Downloads folder.  So, shouldn't that mean all my files were in the same directory?  Then I ran the http.server off of the Downloads folder.  I guess I can try running the script in a standalone py file within the Downloads folder instead of running it in ipython notebook.  Maybe that is where things went wrong?  Sorry not a web or javascript expert.

**Comment by pybokeh** [comment]
OK so I re-downloaded us-states.json into my Downloads file.  Re-downloaded the unemployment csv file into my Downloads file.  Then created a python script called f.py with the following contents:

    import folium
    import pandas as pd

    state_geo = '/home/pybokeh/Downloads/us-states.json'
    state_unemployment = '/home/pybokeh/Downloads/US_Unemployment_Oct2012.csv'

    state_data = pd.read_csv(state_unemployment)

#Let Folium determine the scale
    map = folium.Map(location=[48, -102], zoom_start=3)
    map.geo_json(geo_path=state_geo, data=state_data,
                 columns=['State', 'Unemployment'],
                 key_on='feature.id',
                 fill_color='YlGn', fill_opacity=0.7, line_opacity=0.2,
                 legend_name='Unemployment Rate (%)')
    map.create_map(path='/home/pybokeh/Downloads/us_states_notebook.html')

Then started http.server on port 8000, went to url: http://localhost:8000/us_states_notebook.html and still get a blank map with all 3 browsers.  But if I go folder and right-mouse click over us_states_notebook.html and open with Firefox, the map is rendered with the shaded states.  Man I feel cursed :-(

**Comment by ocefpaf** [comment]
As I said above you need relative links.  Drop the `/home/pybokeh/Downloads/` in your scripts and let me know if that works for you.

```html
state_geo = '/home/pybokeh/Downloads/us-states.json'
state_unemployment = '/home/pybokeh/Downloads/US_Unemployment_Oct2012.csv'
```

**Comment by pybokeh** [comment]
Aaaaahh sorry now I get what you mean!

**Comment by ocefpaf** [comment]
No worries. That just tells me one thing: "We need better docs."

**Comment by pybokeh** [comment]
Yeah I didn't expect that I would have to modify the resulting html or make
sure it is not referencing things with paths local to a specific machine.
I guess I expected the example to work straight out-of-the-box and my lack
of experience with web development didn't help either.  Sorry for the extra
issues that were generated that I caused.
