### ISSUE TITLE
AttributeError- 'MarkerCluster'

### ISSUE THREAD

**Issue by sreesomadas** [python-visualization/folium#927]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here
map2 = folium.Map(location=[53.232350, -1.422151], tiles='CartoDB dark_matter', zoom_start=11)

marker_cluster = folium.MarkerCluster().add_to(map2)

for point in range(0, len(locationlist)):
    folium.Marker(locationlist[point], popup=df_counters['Name'][point]).add_to(marker_cluster)
map2
```
#### Problem description
When I try to run the above code, I get the following error.
[this should explain **why** the current behavior is a problem and what is the expected output.]

#### Output of ``folium.__version__``
AttributeError                            Traceback (most recent call last)
<ipython-input-131-d98ae273548c> in <module>()
      6 map2 = folium.Map(location=[53.232350, -1.422151], tiles='CartoDB dark_matter', zoom_start=11)
      7 
----> 8 marker_cluster = folium.MarkerCluster().add_to(map2)
      9 
     10 for point in range(0, len(locationlist)):

AttributeError: module 'folium' has no attribute 'MarkerCluster'

**Comment by Conengmo** [comment]
To clarify, `MarkerCluster` is a plugin and is not available in the main folium module. So you cannot use it as `folium.MarkerCluster`. Instead you have to import the plugins and get it from there. Two options:

```
import folium.plugins
folium.plugins.MarkerCluster()
```

or

```
from folium.plugins import MarkerCluster
MarkerCluster()
```

I'm closing the issue. Feel free to add comments with additional questions of info. We can reopen the issue if needed.

**Comment by barbaramchd** [comment]
hi @Conengmo ! I have imported the plugins but I keep receiving the following message:
"Exception has occurred: AttributeError
module 'folium' has no attribute 'MarkerCluster'"

appreciate your help!

**Comment by Conengmo** [comment]
Can you share a code snippet?

**Comment by barbaramchd** [comment]
> Can you share a code snippet?

Thank you for your help, but I just solved the problem! 

Also, I need to say that your Github's files have been very helpful! I am just a beginner with Python, and I have found a lot of useful info in your account and your comments. Thank you so much!

**Comment by Conengmo** [comment]
@barbaramchd good to hear you solved it, and thanks for the kind words :)

**Comment by Dhajh** [comment]
@barbaramchd Hola, Cómo lo resolviste???

**Comment by Irene-123** [comment]
> To clarify, `MarkerCluster` is a plugin and is not available in the main folium module. So you cannot use it as `folium.MarkerCluster`. Instead you have to import the plugins and get it from there. Two options:
> 
> ```
> import folium.plugins
> folium.plugins.MarkerCluster()
> ```
> 
> or
> 
> ```
> from folium.plugins import MarkerCluster
> MarkerCluster()
> ```
> 
> I'm closing the issue. Feel free to add comments with additional questions of info. We can reopen the issue if needed.


`from folium.plugins import MarkerCluster
MarkerCluster()
m=folium.Map(location=[34.38,132.45], tiles='CartoDB dark_matter', zoom_start=11)
marker_cluster = folium.MarkerCluster().add_to(m)`

This is how I wrote inspiring from the comment but I still get the same error. Can anybody please help me out with this? 
I am running on jupyter notebook ; Windows 10 ; anaconda

**Comment by RobyGuardo** [comment]
> @barbaramchd Hola, Cómo lo resolviste???

Instead of writing:
`marker_cluster = folium.MarkerCluster().add_to(map2)`
write:
`marker_cluster = MarkerCluster().add_to(map2)`
