### ISSUE TITLE
TimestampedGeoJson duration parameter causes polygons to disappear

### ISSUE THREAD

**Issue by p3zo** [python-visualization/folium#934]
Hi all - I'm having trouble modifying a code snippet from the second TimestampedGeoJson example in the [Plugins example notebook](https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Plugins.ipynb).

```python
import folium
from folium.plugins import TimestampedGeoJson

m = folium.Map(location=[52.467697, -2.548828], zoom_start=6)

polygon = {
    'type': 'Feature',
    'geometry': {
        'type': 'MultiPolygon',
        'coordinates': [((
             (-2.548828, 51.467697),
             (-0.087891, 51.536086),
             (-1.516113, 53.800651),
             (-6.240234, 53.383328),
        ),)],
    },
    'properties': {
        'style': {
            'color': 'blue',
        },
        'times': ['2015-07-22T00:00:00', '2015-08-22T00:00:00', '2015-09-22T00:00:00']
    }
}

TimestampedGeoJson(
    {'type': 'FeatureCollection', 'features': [polygon]},
    period='P1M',
    duration='P1M',
    auto_play=False,
    loop=False,
    loop_button=True,
    date_options='YYYY/MM/DD',
).add_to(m)
    
m
```

The `duration` parameter is described as the "period of time which the features will be shown on the map after their time has passed. If None, all previous times will be shown."

I expect this geometry to be shown on the map for all three time periods, but instead I see it disappear after the first time period.

I'm using folium version 0.6.0 without an ad-blocker. This happens in both Jupyter and html export. The duration parameter was introduced in #894.

**Comment by Conengmo** [comment]
I haven't tried your code since I'm on mobile right now. It seems your duration value is now 1 month, which means each feature is displayed for 1 month. Since you expect them to all three be there, try setting duration to None or to P3M or higher.

**Comment by p3zo** [comment]
Yes, with `duration=None` the map functions as expected and the polygon drawn for all time periods after its first time period.

You say that because my duration value is 1 month I should expect that the feature is drawn for only 1 month, but the `duration` parameter is said to describe the period of time which features will be shown on the map **after their time has passed**. In this example, the polygon is active in all three time periods, so with `duration='P1M'` I expect it to be drawn for one month **after September**, which in this case means all three time periods - July, August, and September.

Take the case below with two polygons.

```python
import folium
from folium.plugins import TimestampedGeoJson

multipoly_1 = [((
     (-2.548828, 51.467697),
     (-0.087891, 51.536086),
     (-1.516113, 53.800651),
     (-6.240234, 53.383328),
),)]

multipoly_2 = [((
     (-3.548828, 50.467697),
     (-1.087891, 50.536086),
     (-2.516113, 52.800651),
     (-7.240234, 52.383328),
),)]

m = folium.Map(location=[52.467697, -2.548828], zoom_start=6)

feature1 = {
    'geometry': {
        'type': 'MultiPolygon',
        'coordinates': multipoly_1,
    },
    'properties': {
        'style': {
            'color': 'blue',
        },
        'times': ['2015-07-22T00:00:00', '2015-08-22T00:00:00',
                  '2015-09-22T00:00:00', '2015-10-22T00:00:00',
                  '2015-11-22T00:00:00', '2015-12-22T00:00:00']
    },
    'type': 'Feature'
}

feature2 = {
    'geometry': {
        'type': 'MultiPolygon',
        'coordinates': multipoly_2,
    },
    'properties': {
        'style': {
            'color': 'yellow',
        },
        'times': ['2015-07-22T00:00:00', '2015-08-22T00:00:00']
    },
    'type': 'Feature'
}

TimestampedGeoJson(
    {'type': 'FeatureCollection', 'features': [feature1, feature2]},
    period='P1M',
    duration='P1M',
    auto_play=False,
    loop=False,
    loop_button=True,
    date_options='YYYY/MM/DD',
).add_to(m)
    
m
```

The first is active from July to December and the second is active only in July and August. I expect the first polygon to be drawn for all time periods and the second to be drawn up until one month after its last month: so July, August and September. Instead what I see is that both polygons are drawn in the first period, disappear in the second, then the second polygon is drawn in September (the month after it's last), and then disappears again. To be clear:

#### Expected 

| Month | Polygon 1 | Polygon 2 |
| -- | -- | -- |
| July | X | X |
| August | X | X |
| September | X | X |
| October | X | |
| November | X | |
| December | X | |

#### Observed

| Month | Polygon 1 | Polygon 2 |
| -- | -- | -- |
| July | X | X |
| August | | |
| September | | X |
| October | | |
| November | | |
| December | | |

**Comment by andy23512** [comment]
According to the corresponding document of leaflet.js, ( https://github.com/socib/Leaflet.TimeDimension/tree/520cb80f645112e242c5160cb44b7d5f2cae380d#ltimedimensionlayergeojson )

_coordTimes, times or linestringTimestamps: array of times that can be **associated with a geometry** (datestrings or ms). In the case of a LineString, it must have **as many items as coordinates** in the LineString._

That means if one want to show the polygon at those 6 timestamps, the length of geometry coordinate list should be 6, in order to specify the polygon to be shown at corresponding timestamp.

In you case, you want to show the same polygon (polygon1) at those 6 timestamps. You can add `* 6` after the coordinate list to make copies.

So the code that meet your expectation would be:
```python
import folium
from folium.plugins import TimestampedGeoJson

m = folium.Map(location=[52.467697, -2.548828], zoom_start=6)

polygon_1 = {
    'type': 'Feature',
    'geometry': {
        'type': 'MultiPolygon',
        'coordinates': [((
             (-2.548828, 51.467697),
             (-0.087891, 51.536086),
             (-1.516113, 53.800651),
             (-6.240234, 53.383328),
        ),)] * 6, # duplicatation for matching 6 timestamps
    },
    'properties': {
        'style': {
            'color': 'blue',
        },
        'times': ['2015-07-22T00:00:00', '2015-08-22T00:00:00',
                  '2015-09-22T00:00:00', '2015-10-22T00:00:00',
                  '2015-11-22T00:00:00', '2015-12-22T00:00:00']
    }
}

polygon_2 = {
    'type': 'Feature',
    'geometry': {
        'type': 'MultiPolygon',
        'coordinates': [((
             (-3.548828, 50.467697),
             (-1.087891, 50.536086),
             (-2.516113, 52.800651),
             (-7.240234, 52.383328),
        ),)] * 2, # duplicatation for matching 2 timestamps
    },
    'properties': {
        'style': {
            'color': 'yellow',
        },
        'times': ['2015-07-22T00:00:00', '2015-08-22T00:00:00']
    }
}

TimestampedGeoJson(
    {'type': 'FeatureCollection', 'features': [polygon_1, polygon_2]},
    period='P1M',
    duration='P1M',
    auto_play=False,
    loop=False,
    loop_button=True,
    date_options='YYYY/MM/DD',
).add_to(m)
    
m
```

Hope that helps.

**Comment by p3zo** [comment]
@andy23512 That fixed my issue! Thanks a lot for your help.

**Comment by Celtics33** [comment]
how do you read a file of multipolygons from a geodataframe?
