### ISSUE TITLE
Remove Leaflet label

### ISSUE THREAD

**Issue by gavkon** [python-visualization/folium#935]
At Leaflet lib I can remove that small right corner label
```java
 L.map('map', {attributionControl: false, etc...})

```
#### Problem description
But with Folum it doesn't work
```python
 folium.Map(attr=False)
```
with attr I can only add new links to sources, but how I can remove all of them?
thanks!

**Comment by ocefpaf** [comment]
> At Leaflet lib I can remove that small right corner label

For the builtins tiles you cannot b/c it is mandatory due to the tiles license.
For any tiles you are adding yourself you are on your own to add it or not but we do recommend you read the license before doing something like that.

**Comment by Whitewind78** [comment]
> > At Leaflet lib I can remove that small right corner label
> 
> For the builtins tiles you cannot b/c it is mandatory due to the tiles license. For any tiles you are adding yourself you are on your own to add it or not but we do recommend you read the license before doing something like that.

Vladimir himself says it's OK to remove it: https://groups.google.com/d/msg/leaflet-js/fA6M7fbchOs/JTNVhqdc7JcJ, but it seems like you should leave it or acknowledge Leaflet in some way.
