### ISSUE TITLE
WmsTileLayer fmt parameter default should be 'image/jpeg' and not 'image/jpg'

### ISSUE THREAD

**Issue by davidlavy** [python-visualization/folium#938]
Hello everyone

I just upgraded to the last folium package and I now have a problem with the init function of the raster_layer object. my wms server accepts format of "image/jpeg" and now it was changed to "image/jpg" as default.

does it have a meaning or is it just a mistake? cause the documentation above the function literally says:

> fmt : str, default 'image/jpeg'
>         The format of the service output.
> as it should be.

but then the function accepts:
> 
>  def __init__(self, url, name=None, layers='', styles='',
>                  **fmt='image/jpg'**, transparent=False, version='1.1.1',
> attr='', overlay=True, control=True, show=True, **kwargs):

TL:DR
please change the default value of the fmt parameter from 'image/jpg' to 'image/jpeg' in the raster_layers.

Thank you in advance.

**Comment by Conengmo** [comment]
It seems to be a typo that was introduced in PR #838. This should indeed be corrected. Do you want to open a PR?

**Comment by Conengmo** [comment]
This has been fixed in #950. Anyone encountering this issue before 0.7.0 is released is advised to install folium from the git master branch, or pass `fmt='image/jpeg'` explicitly when initializing `WmsTileLayer`.
