### ISSUE TITLE
Map blanked when Icons and Popup are added with a high number of markers

### ISSUE THREAD

**Issue by ArBohe** [python-visualization/folium#942]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python

for point in range(0, len(locationlist_hm)):
    folium.Marker([locationlist_hm[point][1], locationlist_hm[point][2]], 
                  popup=folium.Popup('TEST'), parse_html=True),
                  icon=folium.Icon(color='green')).add_to(marker_cluster)

```
#### Problem description

Consider the code above, running with Folium 0.6.0

If I have 200 or 300 markers on a map, no worries, all goes well with icons & popups

If more than 1000-ish markers, the map is not rendered (just blank).
It works well when popup only (no icon=folium.Icon....) OR Icons, but no popup text.
I tested with or without market_cluster: same thing

No error text, just blank

**Comment by Conengmo** [comment]
Can you tell a bit more about what type of system you are using? Jupyter or not, browser, OS, computer hardware...

We've had reports before about limitations using Jupyter in Chrome.

**Comment by wckoeppen** [comment]
I've been having this issue as well, mostly with shapefiles. E.g., I can plot about 4 states at a time before the map starts coming back blank. I assume the number of vertices is akin to the number of markers, and I actually came to issues to see if anyone had posted a threshold of what goes and what doesn't.

I'm on Jupyter Notebook, Chrome, Linux Mint 18.2 (Cinnamon), 3.4 GHz x 4 CPU, 16 Gb memory. I'll try Firefox when I see it again.

**Comment by wckoeppen** [comment]
Oh yeah, seems like the same issue: https://github.com/python-visualization/folium/issues/812

**Comment by Conengmo** [comment]
I'm closing this issue since it's a duplicate. Anyone using Jupyter on Chrome is advised to use another browser or save the maps as html.
