### ISSUE TITLE
Text on markers

### ISSUE THREAD

**Issue by sajjadmurtaza** [python-visualization/folium#949]
Hello,

I want text on markers.
e.g. 
I mark on map and now i want text on these markers. If field finaldata[i][0][2] has highway then "1" otherwise "2" 

```python
finaldata = finaldata[:100]
map = folium.Map(location=[52.5251, 13.3694], zoom_start=12)
for i in range(0,len(finaldata)):
   folium.Marker([finaldata[i][0][1], finaldata[i][0][0]]).add_to(map)
 
map

```
Please guide me

![markers](https://user-images.githubusercontent.com/8552702/44944837-12874500-adde-11e8-83cb-82b8dba544e9.png)

**Comment by ocefpaf** [comment]
If you mean popups please take a look at our docs. There are other markers that allow for that kind of customization too, but not the simple marker. (The the example gallery for those.)
