### ISSUE TITLE
How can I hide the legend for choropleth chart?

### ISSUE THREAD

**Issue by Nyahua** [python-visualization/folium#956]
I have checked the parameters for the `choropleth()`  function. However can't figure out how to disable the legend. Is there any way to do that?

Many thanks!

```python
m.choropleth(
 geo_data, data=None, columns=None, key_on=None, threshold_scale=None, fill_color='blue', 
 fill_opacity=0.6, line_color='black', line_weight=1, line_opacity=1, name=None, legend_name='',
 topojson=None, reset=False, smooth_factor=None, highlight=None)
```

**Comment by Conengmo** [comment]
It's a bit of a hack, but you can delete the color scale after it was created:

```
m = folium.Map()
m.choropleth()
for key in m._children:
    if key.startswith('color_map'):
        del(m._children[key])
```

Why do you want to hide the legend? We should decide if this should be added as an argument.

**Comment by ocefpaf** [comment]
BTW, you can probably use the GeoJson class to achieve that.

Closing b/c having a `choropleth` with the legend is not the goal of the `.choropleth()` method. What we can do is to add some example on how to use the GeoJson for that though.

**Comment by clumzzey** [comment]
There are a couple of reasons why I do not want the scale bars:
- sometimes the scales are obvious
- if I have multiple layers with the same scale, they get redundant.
- If I have multiple layers they take way too much place
- If I have multiple layers the scale bar blocks the zoom button making zooming impossible (+/-)

**Comment by renelikestacos** [comment]
@Conengmo you might know how this works for newer folium versions? Using your approach seem not to work with newest version.

**Comment by Conengmo** [comment]
I didn't test it but does this work?

```
m = folium.Map()
choropleth = folium.Choropleth().add_to(m)
for key in choropleth._children:
    if key.startswith('color_map'):
        del(m._children[key])
```

**Comment by renelikestacos** [comment]
@Conengmo no unfortunately not. it ends in a key error. I am trying to create a bunch of choropleth maps and by hide the layer in the layer control I would like to hide the legend as well.
Do you have any other suggestion? I would really appreciate it. I think the whole legend thing generally is an issue at Folium.

**Comment by it176131** [comment]
@renelikestacos In combination with [this comment](https://github.com/python-visualization/folium/issues/956#issuecomment-639458301) and [this notebook](https://nbviewer.jupyter.org/gist/BibMartin/f153aa957ddc5fadc64929abdee9ff2e) I was able to delete the choropleth's legend and create a legend for each layer.

**Comment by nhpackard** [comment]
I found a slight variation of [Conengmo comment](https://github.com/python-visualization/folium/issues/956#issuecomment-639458301) works.  Delete key in `choropleth._children` before adding to `m`:

```
m = folium.Map()
choropleth = folium.Choropleth()
for key in choropleth._children:
    if key.startswith('color_map'):
        del(choropleth._children[key])
choropleth.add_to(m)
```

**Comment by mmaneesh619** [comment]
`fig.update_layout( showlegend=False)`
This solved for me. I was having choropleth plot with legends. I did this and legends got removed.
Thanks,
Maneesh Mohan.

**Comment by Mah-88** [comment]
@it176131 would you please explain how you do that? I have a choropleth map with several layers, and I could not find any way to create a legend for each layer. So all legends are on the map regardless of the layer.

**Comment by it176131** [comment]
> @it176131 would you please explain how you do that? I have a choropleth map with several layers, and I could not find any way to create a legend for each layer. So all legends are on the map regardless of the layer.

@Mah-88 just wanted you to know I've seen your message but have been busy. Here is a link to a notebook that shows how I did it using the comment and notebook I referred to a couple years ago.

https://github.com/it176131/Dynamic-Choropleth-Legends/blob/main/Dynamic%20Choropleth%20Legends.ipynb

**Comment by jennyresearch** [comment]
> > @it176131 would you please explain how you do that? I have a choropleth map with several layers, and I could not find any way to create a legend for each layer. So all legends are on the map regardless of the layer.
> 
> @Mah-88 just wanted you to know I've seen your message but have been busy. Here is a link to a notebook that shows how I did it using the comment and notebook I referred to a couple years ago.
> 
> https://github.com/it176131/Dynamic-Choropleth-Legends/blob/main/Dynamic%20Choropleth%20Legends.ipynb

Thanks a lot. This helped me a lot. 
However, I have further questions regarding on this. Now the map does not show any Choropleth data. but if I want to show the first Choropleth layer with legend, instead of clicking to show the data, could you advise me how to do it? Thanks in advance =)

**Comment by alperkent** [comment]
> @renelikestacos In combination with [this comment](https://github.com/python-visualization/folium/issues/956#issuecomment-639458301) and [this notebook](https://nbviewer.jupyter.org/gist/BibMartin/f153aa957ddc5fadc64929abdee9ff2e) I was able to delete the choropleth's legend and create a legend for each layer.

Thank you, this was very helpful for me as well.

I just want to leave here a minor modification to this code for those that are trying to map multiple Choropleth layers as base layers rather than overlays (in order to use radio buttons on `LayerControl` instead of checkboxes). In this case, the code assumes Choropleth layers will be overlays and automatically shows all legends regardless of which Choropleth is selected. To fix this, you need to modify two things in the macro script of `BindColormap` class: change `overlayadd` to `layeradd` and `overlayremove` to `layerremove`. This fixed it for me.
