### ISSUE TITLE
Question: add bounds to TileLayers

### ISSUE THREAD

**Issue by frdrk345** [python-visualization/folium#965]
#### psuedo code example

```python
MIN_ZOOM = 8
MIN_LEVEL = 12
MAX_LEVEL = 17

map = folium.Map(location=center, zoom_start=14)
for i in range(0, 5):
    map.add_tile_layer(max_zoom=MAX_LEVEL, min_zoom=MIN_ZOOM, tiles=styles[i])
...
for track in gpx_tracks:
    fg = folium.FeatureGroup(name=track.name)
    url = 'http://0.0.0.0:5000/smarttile/{customname}'.format(customname=make_word(track.name))
    tl = folium.TileLayer(
        tiles=url + '/{z}/{x}/{y}.png',
        attr='myself',
        min_zoom=MIN_LEVEL, max_zoom=MAX_LEVEL,
        name=name,
    )
    fg.add_child(tl)
    map.add_child(fg)
```
#### Problem description

This is a *question*. (And I am quite new at this. )

I am reading several gpx tracks (traces from hikes) and wants to generate tiles for these tracks on demand, and display it/them on a map.

Since a track has a bounding box, I would like to only request tiles for the inside of that bounding box, and I would like to be able to display several (mostly) disjoint tracks/areas.

Below is pseudo code of what I am trying to do, I tried to add something like this:
"folium.FitBounds([track.corner1, track.corner2])" but I did not get it to work like expected.

Is it possible to do what I want to do?

#### Output of ``folium.__version__``

```
$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import folium
>>> folium.__version__
'0.6.0'
```

**Comment by ocefpaf** [comment]
> I would like to be able to display several (mostly) disjoint tracks/areas.

I'm not sure what you mean by `isjoint tracks/areas`, but the MinMaxLimits example can show you how to limit to a bounding box. See http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/MinMaxLimits.ipynb

PS: the all the tiles in the viewing area are loaded automatically by the JS library, the only control we have is on the viewing area.

**Comment by frdrk345** [comment]
Oh, spelling misstake, it should be "disjoint tracks/areas".

The fact is that I would like the map to cover a large area, like the whole world or entire country of Sweden (447 000 km^2)  and be able to generate tiles for several small restricted areas from my tracks.
See this image I drew to try to illustrate it:

![map-example](https://user-images.githubusercontent.com/26288016/45647320-df270480-bac5-11e8-8e58-df65de8fa59a.png)

The red part is the map (from open street map or some other provider), the blue areas is the bounding boxes of my tracks, for which I want to deliver overlay tiles. Outside of these areas, I don't have anything to overlay.

Note that I might display one track, but I might want to have 20 tracks being drawn at different loctions  on the map.

**Comment by ocefpaf** [comment]
I don't think `leaflet` does that. If you find an option/plugin for it than we can try to implement it in `folium`.

**Comment by frdrk345** [comment]
Ok, so should I take my current code and let it generate a webpage, and when investigate the leaflet documentation and try to see if I manually can edit the wbepage/javascript code to see if I can do what I want to do?

When I check the leaflet documentation, I see that TileLayer extends GridLayer, and 
GridLayer has a bounds option. (https://leafletjs.com/reference-1.3.4.html#gridlayer)

Hmm, bounds is listed under TileLayer as an option inherited from GridLayer.

**Comment by ocefpaf** [comment]
> Ok, so should I take my current code and let it generate a webpage, and when investigate the leaflet documentation and try to see if I manually can edit the wbepage/javascript code to see if I can do what I want to do?

That is a start. If you figure that out we can probably wrap it into `folium`.
