### ISSUE TITLE
Minimap pluggin

### ISSUE THREAD

**Issue by talbertc-usgs** [python-visualization/folium#969]
Hopefully it's not too presumptuous of me, but I was excited to add a minimap (locator) plugin to folium.  

See it in action here:  http://nbviewer.jupyter.org/github/talbertc-usgs/folium/blob/minimap/examples/MiniMap.ipynb

PR submitted. #968

**Comment by Conengmo** [comment]
We can discuss further in your PR, so I'm closing this issue.
