### ISSUE TITLE
cdn from Cloudflare aren't loading correctly

### ISSUE THREAD

**Issue by fgcartographix** [python-visualization/folium#97]
Leaflet.js, leaflet.css and the markercluster plugin aren't loading.

In the my console, I have 
```
ReferenceError: L is not defined
var base_tile = L.tileLayer('http://{s}.tile.stamen.com/terrain/{z}/{x}/{y}.jpg'...
```
but when I replace them with the leafletjs.com version, it's working again...

**Comment by fgcartographix** [comment]
It working when I manually add "https://cdnjs.cloudflare.com" instead of "//cdnjs.cloudflare.com"

**Comment by ocefpaf** [comment]
Are you opening the file or serving it? If opening it see #72.

PS: HTMLs are meant to be served via http/s.  It can be with a side-salad if you wish :stuck_out_tongue_winking_eye:
