### ISSUE TITLE
How to add a custom text /numbers like the one in attached

### ISSUE THREAD

**Issue by foliers** [python-visualization/folium#970]
how can i add a custom text or number like temperatures for each lat long , something like in the attached image, any help would be appreciated
![folqn](https://user-images.githubusercontent.com/43539727/45950539-d8484680-c01d-11e8-8e9e-186fe3e2e37f.PNG)

**Comment by jtbaker** [comment]
Hi @foliers, for this you probably want to do something like this with `folium.Marker` and `folium.DivIcon`:

```
import folium, random

m=folium.Map(location=[35.3,-97.7],zoom_start=5,tiles='cartodbdark_matter')

# Generate some random values.
for x in range(2000):
    # Random temperature within range.
    temp = random.uniform(35,120)
    # Place marker at random location in the US.
    folium.Marker(location=[random.uniform(28,51),random.uniform(-120,-80)],
                  # Set icon fo DivIcon to with conditional formatting to reference the random temp value.
                  icon=folium.DivIcon(html=f"""<div style="font-family: courier new; color: {'lightblue' if temp < 50 else 'green' if temp <90 else 'red'}">{"{:.0f}".format(temp)}</div>""")
                 ).add_to(m)
```

**Comment by foliers** [comment]
awesome, is there any document for this? actually i have a csv file with lat long name and color and i want to plot them with layers, can i get colors from CSV file?

**Comment by sergiolucero** [comment]
Of course you can. Just try to understand the one line where the HTML
inside the div is built. Great trick!

**Comment by jtbaker** [comment]
> awesome, is there any document for this? actually i have a csv file with lat long name and color and i want to plot them with layers, can i get colors from CSV file?

Sure. Load up your csv in the module(standard csv, pandas, etc..) of your choice and loop over it and reference the values you want to insert by their indexed position. Folium idiom is generally to zip series from a dataframe, and loop over the zip so you can reference values by alias. Makes it easier to work with more complex datasets and conditional logic and is more memory efficient I think.

This uses's Python 3.6+ f-strings; if you're not familiar you should read up on them. You could use any other string methods too, but this makes it easy to inject a lot of different datatypes without having to do any conversion.
```
import pandas as pd

df = pd.read_csv(<your csv path>)

for lat, lon, value, color in zip(df['latitude'],df['longitude'],df['temperature'],df['color']):
    folium.Marker(location=[lat,lon],
                  icon=folium.DivIcon(html=f"""<div style="color: {color};">{value}</div>""")
                  ).add_to(m)
```

**Comment by foliers** [comment]
awesome, there is another case for me where i dont have color in csv file instead i need to generate color on the fly based on the column names. can i do that? please find below the data sample from csv file

Place,John,Jack,Susan,Madonna,Russel,Andrew,Johny,Sandra,Mexory,Latitude,Longitude
Duffy,50,"12,35","42,47",36,39,112,"18,310",14,110,27.6648,-81.5158
Marco Island,19,15,"21,23",113,112,63,"48,120","14,27",32,25.6648,-81.5158


i need the values to be displayed in different colors, if it is John it has to be yellow, if it is Jack it is white , if it is Susan it is pink and so on

**Comment by jtbaker** [comment]
That's exactly what I did in the first example. Are you familiar with how to use python and conditional logic?  Practice looping over the contents of your csv - for each item, modify a variable  with some `if/else` logic and do something with the variable. Here is a primer: http://www.openbookproject.net/books/bpp4awd/ch04.html

**Comment by foliers** [comment]
i am struck at this :(
```
for John,Jack,Susan,Madonna,Russel,Andrew,Johny,Sandra,Mexory,Latitude,Longitude in zip(df['John'],df['Jack'],df['Susan'],df['Madonna'],df['Russel'],df['Andrew'],df['Johny'],df['Sandra'],df['Mexory'],df['Latitude'],df['Longitude']):
    folium.Marker(location=[Latitude,Longitude],
                  icon=folium.DivIcon(
                      html=f"""<div style="font-family: courier new; color: {'purple' if John else 'pink' if Jack  else 'red'}"></div>""")
                  ).add_to(m)
```

i am not sure on how to use the format , any help would be appreciated

**Comment by jtbaker** [comment]
@foliers oh cool! I didn't remember `.itterrows()`

If you wrap your code into tick marks, it will display `like this`.

```
For a code block, triple tick marks.
```

**Comment by foliers** [comment]
i am unable to make this work, my csv is as below
```
Place,John,Jack,Susan,Madonna,Russel,Andrew,Johny,Sandra,Mexory,Latitude,Longitude
Duffy,50,"12,35","42,47",36,39,112,"18,310",14,110,27.6648,-81.5158
Marco Island,19,15,"21,23",113,112,63,"48,120","14,27",32,25.6648,-81.5158
```

the code i tried is as below

```
for John,Jack,Susan,Madonna,Russel,Andrew,Johny,Sandra,Mexory,Latitude,Longitude in zip(df['John'],df['Jack'],df['Susan'],df['Madonna'],df['Russel'],df['Andrew'],df['Johny'],df['Sandra'],df['Mexory'],df['Latitude'],df['Longitude']):
    folium.Marker(location=[Latitude,Longitude],
                  icon=folium.DivIcon(
                      html=f"""<div style="font-family: courier new; color: {'purple' if John else 'pink' if Jack  else 'red'}"></div>""")
                  ).add_to(m)
```

i am struck at using column names as values and also the format, any help? :(

**Comment by jtbaker** [comment]
Your `<div>` element has no contents between it's opening `<div>` and closing `</div>` tags; only styling attributes in the opening. To render content in HTML tags, you need to put some kind of text or content in between them, like this:

```
<div style="font-family: courier new; color: somecolor;">Some text or other valid HTML tagged content content here</div>
```

Here's some introductory reading on tag structure in HTML documents: https://www.w3schools.com/tags/tag_html.asp

You also probably want to add some additional logic to your styling string. Every variable in your dataset is going to return `True` in your `if` statement, so you should probably add some additional qualifying logic with an `==`, `<`, `>=`, etc. comparison operator; i.e.

```
html=f"""<div style="font-family: courier new; color: {'purple' if John==50 else 'pink' if len(Jack)>1  else 'red'}"></div>"""
``` 

I'm not sure exactly what you're trying to represent with your data or what information you're trying to convey with your map, but that should help with getting your content to display on the map.

**Comment by foliers** [comment]
```
Place,John,Jack,Susan,Madonna,Russel,Andrew,Johny,Sandra,Mexory,Latitude,Longitude
Duffy,50,"12,35","42,47",36,39,112,"18,310",14,110,27.6648,-81.5158
Marco Island,19,15,"21,23",113,112,63,"48,120","14,27",32,25.6648,-81.5158
```
Actually the column names are the ones with which i want to decide in what color the numbers are going to get displayed.
For example:

I want to display the number 12,35 in yellow color since it is Jack, in the latitude longitude of 27.6648,-81.5158 
display the number 50 in red color since it is John , in the latitude longitude of 27.6648,-81.5158 
and so on

**Comment by jtbaker** [comment]
You might want to reconfigure how your data is structured for then - Right now you have two values for `John`: `50` and `19`, as well as two values for `Jack`: `"12, 35"` and `15`. These are both representing the same instance of data - but it seems like you want them to represent separate instances. Both of these return `True`. You might consider representing your names as the index on a separate row as a "record" instead of a "column", which normally represents "attributes" of a record in this format of storing data.

**Comment by foliers** [comment]
> You might want to reconfigure how your data is structured for then - Right now you have two values for `John`: `50` and `19`, as well as two values for `Jack`: `"12, 35"` and `15`. These are both representing the same instance of data - but it seems like you want them to represent separate instances. Both of these return `True`. You might consider representing your names as the index on a separate row as a "record" instead of a "column", which normally represents "attributes" of a record in this format of storing data.

But the data is for 2 different locations :(

**Comment by ocefpaf** [comment]
This is an interesting discussion but it is mostly about folium/python usage than a `folium` issue. I'm closing this b/c it is not actionable by the devs. Feel free to continue the discussion here or, better yet, on the gitter channel.
