### ISSUE TITLE
Is there anyway to add a drop down menu to zoom on points just like search plugin but with a dropdown?

### ISSUE THREAD

**Issue by satiankit** [python-visualization/folium#972]
This is the geojson I am using fo search.
points =  {'type': 'FeatureCollection',
 'features': [{'type': 'Feature',
   'properties': {'name': 'Durham'},
   'geometry': {'type': 'Point',
    'coordinates': ['-78.98941245', '35.95038441']}}]}

Code for search plugin is:
```python
# Your code here
folium.plugins.Search(points, search_zoom=12, geom_type='Point').add_to(m)
```

**Comment by Conengmo** [comment]
What you could do is loop over your data and create a `Marker` and `FeatureGroup` for each point. That way, each point shows up in the layer control.

```
for point in data:
    fg = folium.FeatureGroup().add_to(m)
    folium.Marker(point lat lon).add_to(fg)
```

Something like this. As far as I know we don't have a plugin for this kind of behavior.

**Comment by satiankit** [comment]
> What you could do is loop over your data and create a `Marker` and `FeatureGroup` for each point. That way, each point shows up in the layer control.
> 
> ```
> for point in data:
>     fg = folium.FeatureGroup().add_to(m)
>     folium.Marker(point lat lon).add_to(fg)
> ```
> Something like this. As far as I know we don't have a plugin for this kind of behavior.

okay, anyway i can add that to my map? I tried your way but it just adds an on/off sort of switch for the marker. It doesn't allow me to zoom on it.
Thanks for the help.
