### ISSUE TITLE
Set Opacity to folium tile layers

### ISSUE THREAD

**Issue by meteoDaniel** [python-visualization/folium#978]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
base_map = folium.Map(location=[49.377157, 9.36088], zoom_start=6,
                      tiles='cartodbpositron', attr='Weather Data')

base_map.add_tile_layer(tiles='http://weatheroo.net/wordpress/gust/1/{z}/{y}/{x}.png',
                        attr='WGUST',)
base_map.save('wgust.html')

```
#### Problem description

How to set the opacity of the tile layer ? 

#### Expected Output
For JS with OpenLayers you can set like this
```
gust = new ol.layer.Tile({
  opacity: 0.6,
  source: new ol.source.XYZ({
  url: 'http://weatheroo.net/wordpress/gust/'+imagecounter+'/{z}/{y}/{x}.png'
  })
});
```

#### Output of ``folium.__version__``
0.5.0

**Comment by Conengmo** [comment]
Hi @meteoDaniel, you can do this by using the `TileLayer` class. For example:

```
m = folium.Map()
folium.TileLayer(opacity=0.42).add_to(m)
```

**Comment by meteoDaniel** [comment]
If I do this, i got this Error: 

`TypeError: __init__() got an unexpected keyword argument 'opacity'
`

**Comment by meteoDaniel** [comment]
Still the same with version 0.6

**Comment by Conengmo** [comment]
Huh apperently it was added after the 0.6 release. If you need it you should install folium from the master branch on git.

**Comment by guy1ziv2** [comment]
I am getting the same error. I tried installing from master branch but it did not help.
`__init__() got an unexpected keyword argument 'opacity'`

**Comment by Conengmo** [comment]
Are you sure? If can see the argument in the code:
https://github.com/python-visualization/folium/blob/ca745ef8674ad39d26e44fee2c081f3d3089f444/folium/raster_layers.py#L89

**Comment by guy1ziv2** [comment]
in the last version it is gone
https://github.com/python-visualization/folium/blob/v0.6.0/folium/raster_layers.py

Guy Ziv

**Comment by guy1ziv2** [comment]
update: you are right, it is on the master branch. If one install from github
'!pip install -q git+https://github.com/python-visualization/folium'
rather than
'!pip install folium'
then opacity works as expected


Guy Ziv

**Comment by guy1ziv2** [comment]
is there any idea when folium will be updated in pypi ?

Guy Ziv

**Comment by Conengmo** [comment]
> is there any idea when folium will be updated in pypi ?

Nope no date planned yet
