### ISSUE TITLE
Support for HTTPS/SSL

### ISSUE THREAD

**Issue by samzhang111** [python-visualization/folium#98]
I spent a bit of time trying to figure out why my map wasn't rendering inline in ipython notebook following these examples: http://nbviewer.ipython.org/gist/bburky/7763555/folium-ipython.ipynb. The problem is that I was running ipython notebook over https, and ssl isn't available for OpenStreetMap's public tiles.

Stamen makes SSL tiles freely available (http://maps.stamen.com/, ctrl-f ssl):

 > If you'd like to display these map tiles on a website that requires HTTPS, use our tile SSL endpoint by replacing http://tile.stamen.com with https://stamen-tiles.a.ssl.fastly.net. Multiple subdomains can be also be used: https://stamen-tiles-{S}.a.ssl.fastly.net
 > 
 > JavaScript can be loaded from https://stamen-maps.a.ssl.fastly.net/js/tile.stamen.js.

Perhaps using a protocol relative URL for stamen tiles, and making them default for SSL (or all the time-- they're gorgeous!), would make folium more easy to pick up, since some beginner ipython noteobok tutorials set up SSL.

A warning message in the documentation about the availability of certain tiles through SSL could be helpful as well.

**Comment by ocefpaf** [comment]
Hi @samzhang111,

Thanks to @apatil  (see PR #93) almost all the javascript is already loaded over https when available.  I will take a look to see what's left.

**Comment by samzhang111** [comment]
Actually it looks like this is identical to #83, since this is about map tiles. Stamen can handle being served over protocol agnostic URIs, not sure about the other ones.

**Comment by ocefpaf** [comment]
@birdage and @apatil The post below by Paul Irish made me wonder if we should just for HTTPS scheme everywhere.

http://www.paulirish.com/2010/the-protocol-relative-url/

What do you think?

**Comment by birdage** [comment]
@ocefpaf what are the downsides?

**Comment by ocefpaf** [comment]
Dunno!  My web expertise is == 0.  That's why I am asking for help  :stuck_out_tongue_winking_eye:

**Comment by samzhang111** [comment]
Downsides are not all the map tiles support https. Only stamen does out of the box, as far as I know. Mapbox and leaflet can with a paid API.

**Comment by ocefpaf** [comment]
Thanks @samzhang111!  With that info we now know that forcing https is a no no!  Let me go back and work start working on some more "agnostic-ing."
