### ISSUE TITLE
Creating documentation latex files fails (Python 3.5)

### ISSUE THREAD

**Issue by 1kastner** [python-visualization/folium#983]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```shell
cd ./docs
make latex
```

#### Problem description

Instead of creating the tex files the following happens:

```shell
sphinx-build -b latex -d _build/doctrees   . _build/latex
Running Sphinx v1.8.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/XXXXXXXXX/.local/lib/python3.5/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/XXXXXXXXX/.local/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/YYYYYYYYY/folium/folium/docs/conf.py", line 52, in <module>
    from folium._version import get_versions
ImportError: No module named 'folium'

Makefile:99: recipe for target 'latex' failed
make: *** [latex] Error 2
```

#### Expected Output

Nice latex files which I could use for creating a PDF.

#### Output of ``folium.__version__``
     0.6.0+30.g9f648a2.dirty'

**Comment by 1kastner** [comment]
PS: Of course in the PDF I want to have the version number of the folium I have checked out in that specific directory for which I am building the docs. Currently it seems to take the one from the system.

**Comment by Conengmo** [comment]
Hi @1kastner, for me this does work. Your error messages seems to suggest you didn't install folium. Can you check if it that's the case?

**Comment by 1kastner** [comment]
Once I installed folium it worked. But I might not want to install each version to build the docs. I thought that maybe with the sys.path trick the docs of an uninstalled folium could also be produced.

**Comment by Conengmo** [comment]
What is the use case that you want to create latex docs for multiple versions?

**Comment by 1kastner** [comment]
In my case I want to create the pdf of one version for internal communication in the scope of one project (I don't need the installation though) and use another version for my day-to-day tasks. I think that if you generate a documentation, it should be the documentation of the version you have checked out. This is how it is cleanly done. Now it would partly be the documentation which is checked out and partly the one which I have currently installed (maybe at another directory). That I consider not to be that beautiful.

So maybe in https://github.com/python-visualization/folium/blob/master/docs/conf.py we could add the following line

    sys.path.insert(0, "../folium")

or more general

    sys.path.insert(0, os.path.join(os.pardir, "folium")))

I did not try out the code but would do so soon. This is btw also the proposed way of how to use `autodoc` according to the sphinx docs, see [here](http://www.sphinx-doc.org/en/master/usage/quickstart.html#autodoc).
If you accept it, I would also work on a pull request for this.

**Comment by Conengmo** [comment]
Seems like a fairly simple change. If you open a PR we'll review it, see if there are no side effects in the CI.

**Comment by 1kastner** [comment]
See #990
