### ISSUE TITLE
How to use same folium map file multiple times

### ISSUE THREAD

**Issue by foliers** [python-visualization/folium#986]
I am saving a folium map with some data for certain places, when i create a map for a particular place i am saving it using below piece of code

`m.save(os.path.join('color_popups1234.html'))`
When i try to add some data to some other place in same file should i change anything in this code to make use of same file? because when i run it for some other place i am getting only the new place data and old data is not in there, what should i do to retain data for all places as i will be adding the data gradually for some places

**Comment by Conengmo** [comment]
Saving/rendering folium maps is a one way street, so you cannot add data to an already rendered map. You have to store your data some way else, and then make your map when your data is complete.
