### ISSUE TITLE
Use the leaflet-providers library

### ISSUE THREAD

**Issue by Conengmo** [python-visualization/folium#993]
I came across this Javascript library that contains configuration parameters for a lot of free tile providers. The library is more complete than our list of providers and is actively maintained. 

https://github.com/leaflet-extras/leaflet-providers

They also have a nice preview page to select a provider:
http://leaflet-extras.github.io/leaflet-providers/preview/index.html

How about replacing our current tile selection code with this library? 

\+ We wouldn't have to maintain tileset configurations anymore.
\+ This would solve #922 and #839.
\- We don't have control over this anymore and have to rely on another library.
\- We have to maintain the wrapping of this library.
\- Error checking will happen in Javascript, so users entering wrong tileset names won't see an error in Python.

I'm not really worried about losing control. We already rely on a lot of Leaflet librarie. We can always fork it if the original library is abandoned.

About maintaince, I think maintaining the wrapping will be easier than maintaining all these different tileset configurations.

The errors happening in Javascript is bothering me, that would be a deal breaker for me.

A solution could be to just copy their list of providers and use them in our code, without wrapping their Javascript file.

**Comment by ocefpaf** [comment]
I'm not against it but I'm not too keen to at it either and here is my thinking:

- We would still need to supported the list of tiles provides, or create a function to download it on fly. The former may go stale quickly and the latter is not clear to me on how to implement.

- The current implementation [takes a URL](https://github.com/python-visualization/folium/issues/839#issuecomment-437356991), so we don't need to worry about non-standard options like HERE maps `app_id` and `add_code` for example.

- By using that as a replacement to the current tile loader we are adding another JS that **must** be in the base HTML, that is not a big deal but the less the better IMO.

**Comment by Conengmo** [comment]
Let's not do it this way. We have some good default, built-in tilesets. In the documentation we now point to a list of public tilesets: http://leaflet-extras.github.io/leaflet-providers/preview/ Users can easily pass one of these urls to the `tiles` argument. I don't think we have to make things more complicated than this.
