### ISSUE TITLE
Can we add multiple overlay layers like Imageoverlay and geoJson layer but are mutually exclusive.

### ISSUE THREAD

**Issue by Elvin-John** [python-visualization/folium#994]
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python

m = folium.Map(location=[45.4556083414,38.8351840212],
       zoom_start=13)

for image_id in image_list:

    img = plugins.ImageOverlay(
        name=image_id[:-7],
        image='D:/Notebooks/'+field_id + '_jpg/' +image_id + '.jpeg',
        bounds =[[miny, minx], [maxy, maxx]],
        opacity=0.6,
        interactive=True,
        cross_origin=False,
        overlay=False,
        zindex=1,
    )

    folium.Popup(image_id).add_to(img)

    img.add_to(m)

for i in range(5):
    folium.GeoJson(alerts_json_data[i], name = zmb_sgt_32876_S20180501_ndvi_v',overlay=False).add_to(m)

folium.LayerControl(collapsed=False).add_to(m)

leafletfilename = 'ImageOverlay_v2_6.html'
m.save(leafletfilename)


```
#### Problem description

![image](https://user-images.githubusercontent.com/29055041/47038069-3213da80-d19e-11e8-9a4e-7e435d64a3de.png)

### two discrete layers which can be selected separately 
![image](https://user-images.githubusercontent.com/29055041/47038281-b1091300-d19e-11e8-9ade-75070fe2974b.png)

#### Output of ``folium.__version__``
**This isn't a bug
I just need guidance to implement my logic**

**Comment by Conengmo** [comment]
Does the FeatureGroupSubGroup plugin work for you? It doesn't make them mutually exclusive but it does make it easy to toggle multiple layers at once.

**Comment by Elvin-John** [comment]
Yeah I want each layer to be visible too

**Comment by Conengmo** [comment]
I'm closing the issue Elvin, since there is not really an action we can take on this. Also it's not really clear to me what you're asking.
