### ISSUE TITLE
Remove use of rawgit

### ISSUE THREAD

**Issue by Conengmo** [python-visualization/folium#997]
Rawgit is being deprecated: https://rawgit.com/

We cannot use it for new URL's and have to stop using it for current ones and move to other CDN's before October 2019.

Currently there are 13 places where we use Rawgit:
https://github.com/python-visualization/folium/search?q=rawgit&unscoped_q=rawgit

**Comment by jtbaker** [comment]
I've been using a clone at https://raw.githack.com/ - they have dev and prod CDN services through cloudflare, so should offer the same functionality.

Just pattern match/replace cdn.rawgit.com to  rawcdn.githack.com and should be good.

**Comment by jtbaker** [comment]
PR'd a fix in #1002
