### ISSUE TITLE
Plugin SemiCircle

### ISSUE THREAD

**Issue by syberworld** [python-visualization/folium#998]
Hi,
I have try to made port plugin for [Semicircle](https://github.com/jieter/Leaflet-semicircle/blob/master/README.md).
I'm newbe and I hope it's full working.
We can see it [here](https://github.com/syberworld/Folium-SemiCircle/blob/master/README.md)
This is a preview:
![](https://raw.githubusercontent.com/syberworld/Folium-SemiCircle/master/Screenshot.png)
Thank you for your job, it's a very beutifull.

**Comment by ocefpaf** [comment]
The code looks really nice! If you want you can send a PR to https://github.com/python-visualization/folium/tree/master/folium/plugins adding that to `folium` directly.

**Comment by syberworld** [comment]
Oh, great, thank you.
I try to add.

**Comment by ocefpaf** [comment]
> I must change `__init__.py` too ?

Yep. You'll want to import it there and add the the `__all__` list like the others.
We can guide you more on the PR itself.

**Comment by syberworld** [comment]
Yes, I need some help, it's my first time.

**Comment by ocefpaf** [comment]
> Yes, I need some help, it's my first time.

I send 100ths of PRs and I always need help :smile: 

Don't worry. We'll do our best to guide you along the way. (Ping @Conengmo who is a wonderful reviewer!)

How comfortable are you forking `folium`, creating a branch, and submitting a PR?

GitHub docs are a pretty good source of info: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by syberworld** [comment]
Ok, I study it and I will try

**Comment by ocefpaf** [comment]
> Ok, I study it and I will try

Feel free to ask anything along the way.

**Comment by syberworld** [comment]
Hi @Conengmo, it's ok or I wrong something ?

**Comment by Conengmo** [comment]
We'll continue the discussion in the related PR: #1000

**Comment by Conengmo** [comment]
This has been merged: https://github.com/python-visualization/folium/pull/1238
